import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{rotatePosition,transformBlock}from'../../../../hardware/gpu-layout-assembly.mjs';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{fileURLToPath}from'node:url';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),K=p=>`${p.x},${p.y},${p.z}`,parentEndpoints=read('../block-id-connected-v1/endpoint-map.json'),mapping=parentEndpoints.mapping,claims=new Map(Object.entries(mapping).map(([k,v])=>[k,v.body])),core=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H))),world=new Map(core.blocks.map(b=>[K(b.position),b.block])),cuts=parentEndpoints.cuts;
function upstream(target){const queue=[{p:target,parity:0}],seen=new Set([K(target)+':0']),found=new Map,unplaced=[],torchStages=new Set,receiverBody=claims.get(K(target)),receiverPassiveDust=[];for(let i=0;i<queue.length;i++){const {p,parity}=queue[i];for(const q of inputs(world,p)){const b=world.get(K(q)),invert=['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id),nextParity=parity+Number(invert)&1,k=K(q),state=k+':'+nextParity;if(seen.has(state))continue;seen.add(state);if(claims.has(k)){if(claims.get(k)===receiverBody&&b.id==='minecraft:redstone_wire'){receiverPassiveDust.push(q);queue.push({p:q,parity:nextParity});continue;}found.set(state,{position:q,parity:nextParity});continue;}if(invert){const ins=inputs(world,q);if(ins.length!==1){unplaced.push({position:q,block:b,reason:'not_unary_inverter',inputs:ins});continue;}torchStages.add(k);}else if(!['minecraft:redstone_wire','minecraft:repeater'].includes(b.id)){unplaced.push({position:q,block:b,reason:'not_transport'});continue;}else if(b.id==='minecraft:repeater'){const ins=inputs(world,q);if(ins.some(s=>Math.abs(q.x-s.x)+Math.abs(q.z-s.z)===1&&['minecraft:repeater','minecraft:comparator'].includes(world.get(K(s))?.id)&&((b.properties.facing==='north'||b.properties.facing==='south')?q.x!==s.x:q.z!==s.z))){unplaced.push({position:q,reason:'locked_transport'});continue;}}queue.push({p:q,parity:nextParity});}}return{found:[...found.values()],unplaced,visited:seen.size,unary_torch_stages:torchStages.size,receiver_passive_dust_component:receiverPassiveDust};}
const P=(x,y,z)=>({x,y,z}),planned=[
{name:'raw_reset_ACK_to_held_reset_D',source:P(976,209,-2),destination:P(1000,209,-72)},
{name:'RF_local_A_to_held_reset_OPEN',source:P(1050,53,3),destination:P(1008,208,-69)},
{name:'cold_mask_to_held_reset_D_clamp',source:P(1026,176,-107),destination:P(1004,209,-75)},
{name:'cold_mask_to_held_reset_Q_clamp',source:P(1026,176,-107),destination:P(1015,209,-75)},
{name:'held_reset_ACK_to_final_completion',source:P(1017,209,-72),destination:P(-192,235,565)},
{name:'held_reset_ACK_to_final_exit',source:P(1017,209,-72),destination:P(14,207,575)},
{name:'held_event_ACK_to_final_exit',source:P(1017,305,-72),destination:P(20,207,575)}],connections=[],unmatched=[];
for(const c of planned){const walk=upstream(c.destination),sources=walk.found.filter(q=>K(q.position)!==K(c.destination));if(walk.unplaced.length||sources.length!==1||K(sources[0].position)!==K(c.source)||sources[0].parity!==0){unmatched.push({...c,actual_sources:sources,unplaced:walk.unplaced});continue;}connections.push({...c,original_source:c.source,original_destination:c.destination,source:mapping[K(c.source)].position,destination:mapping[K(c.destination)].position,source_body:mapping[K(c.source)].body,target_body:mapping[K(c.destination)].body,actual_reference_upstream:sources,upstream_transport_nodes:walk.visited,unary_torch_stages:walk.unary_torch_stages,receiver_passive_dust_component:walk.receiver_passive_dust_component});}
const allCuts=read('../block-id-connected-v1/cut-census.json').all_current_body_cuts;for(const c of allCuts)assert(inputs(world,c.to).some(q=>K(q)===K(c.from)),'Inherited cut not actual '+K(c.from)+'>'+K(c.to));assert.equal(connections.length,7,'Held ACK prerequisite refused '+JSON.stringify(unmatched));assert.equal(unmatched.length,0);
const priorCutSet=new Set(cuts.map(c=>K(c.from)+'>'+K(c.to))),bindings=connections.map(c=>{const source=allCuts.filter(e=>K(e.from)===K(c.original_source)),receiver=allCuts.filter(e=>K(e.to)===K(c.original_destination));assert(source.length&&receiver.length,'Missing source/receiver cut '+c.name);return{name:c.name,original_source:c.original_source,original_receiver:c.original_destination,source_boundary_edges:source.map(e=>({...e,in_982_shared_island_ledger:priorCutSet.has(K(e.from)+'>'+K(e.to))})),receiver_boundary_edges:receiver.map(e=>({...e,in_982_shared_island_ledger:priorCutSet.has(K(e.from)+'>'+K(e.to))})),actual_transported_source_count:c.actual_reference_upstream.length,transported_polarity:'positive',full_source_fanout_closed:false};});
writeFileSync(new URL('exact-cut-bindings.json',H),JSON.stringify({status:'selected_actual_source_and_receiver_boundary_edges_bound',broader_mapped_body_directed_cut_count:allCuts.length,retained_original_shared_island_cuts:cuts.length,bindings,all_mapped_body_cuts:allCuts,complete_core:false,native_acceptance:false},null,2)+'\n');
writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({...parentEndpoints,mapping,cuts,connections,unmatched,inherited_open_obligations:'../block-id-connected-v1/timing-and-composition.json',selected_body_cuts:cuts.length,mapped_original_cells:claims.size,complete_core:false,native_acceptance:false})+'\n');console.log(JSON.stringify({connections:connections.map(c=>({name:c.name,source:c.source,destination:c.destination})),unmatched,cuts:cuts.length},null,2));
