import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeQualifiedCore,checkQualifiedCore} from './prepare.mjs';
import {makeCoreState,nextCoreState} from '../control-core-v1/prepare.mjs';
import {makePhaseQualifier} from '../control-event-gates-v1/prepare.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},d=makeQualifiedCore();
assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));
function inspect(d){const m=new Map(d.blocks.map(b=>[K(b.position),b])),at=p=>m.get(K(p))?.block;let preserved=0,directions=0;for(const[name,parent]of[['core',makeCoreState()],['qualifier',makePhaseQualifier()]])for(const b of parent.blocks){const o=d.parent_offsets[name];assert.deepEqual(at(P(b.position.x+o.x,b.position.y+o.y,b.position.z+o.z)),b.block);preserved++;}
 for(const r of d.routes){for(let i=0;i<r.path.length;i++){const p=r.path[i],b=at(p);assert(b);if(r.refresh_indices.includes(i)){const[x,z]=D[b.properties.facing];assert.equal(b.id,'minecraft:repeater');assert.deepEqual(r.path[i-1],P(p.x-x,p.y,p.z-z));assert.deepEqual(r.path[i+1],P(p.x+x,p.y,p.z+z));directions++;}else assert.equal(b.id,'minecraft:redstone_wire');}}
 const next=d.routes.find(r=>r.name==='qualified_next_open'),current=d.routes.find(r=>r.name==='qualified_current_open'),init=d.routes.find(r=>r.name==='initialize_to_core_clamps');assert.deepEqual([next.path[0],next.path.at(-1)],[P(-78,1,16),P(-22,0,3)]);assert.deepEqual([current.path[0],current.path.at(-1)],[P(-58,1,14),P(-10,0,3)]);assert.deepEqual([init.path[0],init.path.at(-1)],[P(-104,64,-6),P(28,64,4)]);
 for(const[p,f]of[[P(-58,1,15),'south'],[P(-101,1,-6),'east'],[P(-103,1,-6),'east'],[P(-105,1,-6),'east'],[P(-105,64,-6),'west']]){assert.deepEqual(at(p),{id:'minecraft:repeater',properties:{facing:f,delay:'1'}});directions++;}
 for(let y=1;y<=64;y++)assert.equal(at(P(-106,y,-6)).id,y%2?'minecraft:light_gray_concrete':'minecraft:redstone_torch');
 for(const value of[false,true]){let prior=value;for(let y=2;y<=64;y+=2)prior=!prior;assert.equal(prior,value);}
 // Inventory all contacts from newly added solid blocks to old electronic cells.
 // The single permitted contact is the support under the first OPEN rising wire,
 // beside its own output pad. It does not connect to a different parent net.
 const solidContacts=[];for(const b of d.blocks.filter(b=>!['core','qualifier'].includes(b.part)&&b.block.id.endsWith('_concrete')))for(const[x,y,z]of[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]){const p=P(b.position.x+x,b.position.y+y,b.position.z+z),o=m.get(K(p));if(o&&['core','qualifier'].includes(o.part)&&!o.block.id.endsWith('_concrete'))solidContacts.push([K(b.position),K(p),o.block.id]);}
 assert.deepEqual(solidContacts,[['-77,1,16','-78,1,16','minecraft:redstone_wire']]);
 const power=new Map(),adj=new Map();for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))adj.set(K(b.position),[]);for(const e of d.edges)if(adj.has(K(e.from))&&adj.has(K(e.to))){adj.get(K(e.from)).push(K(e.to));adj.get(K(e.to)).push(K(e.from));}const seed=p=>{if(adj.has(K(p)))power.set(K(p),15);};for(const p of Object.values(d.ports).filter(p=>p.direction==='input'))for(const b of p.bits)seed(b.position);for(const b of d.blocks){if(['minecraft:repeater','minecraft:comparator'].includes(b.block.id)){const[x,z]=D[b.block.properties.facing];seed(P(b.position.x+x,b.position.y,b.position.z+z));}if(['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.block.id))for(const[x,z]of Object.values(D))seed(P(b.position.x+x,b.position.y,b.position.z+z));}const q=[...power.keys()];for(let i=0;i<q.length;i++){const key=q[i],v=power.get(key)-1;if(v<=0)continue;for(const p of adj.get(key)??[])if((power.get(p)??0)<v){power.set(p,v);q.push(p);}}
 let rears=0;for(const b of d.blocks.filter(b=>!['core','qualifier'].includes(b.part)&&b.block.id==='minecraft:repeater')){const[x,z]=D[b.block.properties.facing],p=P(b.position.x-x,b.position.y,b.position.z-z);if(adj.has(K(p))){assert((power.get(K(p))??0)>0,'Unpowered possible route '+K(b.position));rears++;}}
 return{unchanged_parent_blocks:preserved,new_explicit_direction_checks:directions,new_solid_to_parent_electronic_contacts:solidContacts.length,possible_positive_new_wire_rears:rears,initialization_tower_inversions:32,route_nominal_repeater_ticks:Object.fromEntries(d.routes.map(r=>[r.name,2*r.refresh_indices.length]))};
}
const geometry=checkQualifiedCore(d),extra=inspect(d);let negatives=0;for(const f of[c=>c.blocks.find(b=>K(b.position)==='-58,1,15').block.properties.facing='north',c=>c.blocks.find(b=>K(b.position)==='-106,62,-6').block.id='minecraft:light_gray_concrete',c=>c.blocks.splice(c.blocks.findIndex(b=>K(b.position)==='-77,2,16'),1),c=>c.blocks.find(b=>K(b.position)==='-101,1,-6').block.properties.facing='west']){const c=structuredClone(d);f(c);assert.throws(()=>{checkQualifiedCore(c);inspect(c);});negatives++;}
let cases=0;for(let initial=0;initial<8;initial++){let state=initial,next=initial^7; // Wait for the actual tower/clamp before opening NEXT.
 next=nextCoreState(state,false,false,true);assert.equal(state,initial);state=next;assert.equal(state,0);for(const ret of[false,true]){state=0;for(let i=0;i<7;i++){next=nextCoreState(state,true,ret);const held=next;state=held;cases++;}assert.equal(state,ret?7:1);}}
const report={...geometry,...extra,abstract_initialized_sequence_steps:cases,corruptions_refused:negatives,limits:['Component-count delay sums omit wire/update scheduling and receiver paths; no operating bound is established.','Initialization can temporarily capture unknown state until its real clamp arrives. Architectural action is blank throughout; reset ack requires a complete settled zero transfer.','Source phase nonoverlap and intermodule advance/action producers remain required.','Solid-contact inventory is a static candidate screen, not a general redstone simulation.']};if(process.argv.includes('--save'))writeFileSync(new URL('offline-check.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
