// Connected local core bank OPEN and initialization paths. Offline only.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {makeCoreState} from '../control-core-v1/prepare.mjs';
import {makePhaseQualifier} from '../control-event-gates-v1/prepare.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,V={east:[1,0],west:[-1,0],south:[0,1],north:[0,-1]},F={east:'west',west:'east',south:'north',north:'south'};
export function makeQualifiedCore(){
 const parents={core:makeCoreState(),qualifier:makePhaseQualifier()},offsets={core:P(0,0,0),qualifier:P(-140,0,0)},map=new Map(),edges=[],routes=[],ports={};
 const move=(p,n)=>P(p.x+offsets[n].x,p.y+offsets[n].y,p.z+offsets[n].z),edge=(from,to)=>edges.push({from,to}),join=ps=>{for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);};
 function put(p,id,properties,part){const block={id:'minecraft:'+id,...(properties?{properties}:{})},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'Collision '+K(p));return;}map.set(K(p),{position:p,block,part});}
 const solid=(p,n)=>put(p,'light_gray_concrete',undefined,n),dev=(p,id,props,n)=>{solid(P(p.x,p.y-1,p.z),n+'_support');put(p,id,props,n);},wire=(p,n)=>dev(p,'redstone_wire',undefined,n),rep=(p,d,n)=>dev(p,'repeater',{facing:F[d],delay:'1'},n);
 for(const[n,d]of Object.entries(parents)){for(const b of d.blocks){const p=move(b.position,n);assert(!map.has(K(p)),'Parent overlap');put(p,b.block.id.slice(10),b.block.properties,n);map.get(K(p)).parent_part=b.part;}for(const e of d.edges)edge(move(e.from,n),move(e.to,n));}
 function route(name,ws){const path=[P(...ws[0])];for(let i=1;i<ws.length;i++){const a=ws[i-1],b=ws[i],delta=b.map((v,j)=>v-a[j]),steps=Math.abs(delta[0])+Math.abs(delta[2]);assert(steps&&(!delta[0]||!delta[2])&&(!delta[1]||Math.abs(delta[1])===steps));for(let j=1;j<=steps;j++)path.push(P(...a.map((v,k)=>v+Math.sign(delta[k])*j)));}
  const candidates=[-1];for(let i=1;i<path.length-1;i++){const a=path[i-1],p=path[i],b=path[i+1];if(!map.has(K(p))&&a.y===p.y&&b.y===p.y&&p.x-a.x===b.x-p.x&&p.z-a.z===b.z-p.z)candidates.push(i);}candidates.push(path.length);const cost=new Map([[-1,0]]),prev=new Map();for(const end of candidates.slice(1))for(const start of candidates){if(start>=end)break;if(!cost.has(start)||end-start>13)continue;const value=cost.get(start)+(end===path.length?0:1);if(value<(cost.get(end)??Infinity)){cost.set(end,value);prev.set(end,start);}}assert(prev.has(path.length),'Unrefreshable '+name);const refresh=[];for(let at=prev.get(path.length);at!==-1;at=prev.get(at))refresh.push(at);refresh.sort((a,b)=>a-b);
  for(let i=0;i<path.length;i++){const p=path[i],q=path[i+1];if(map.has(K(p)))assert.equal(map.get(K(p)).block.id,'minecraft:redstone_wire','Non-wire shared route '+name+' '+K(p));else if(refresh.includes(i)){const d=Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z);rep(p,d,name);}else wire(p,name);}join(path);routes.push({name,path,refresh_indices:refresh});
 }
 route('qualified_next_open',[[-78,1,16],[-74,5,16],[-36,5,16],[-36,5,20],[-32,5,20],[-32,0,15],[-22,0,15],[-22,0,3]]);
 rep(P(-58,1,15),'north','current_output_branch');wire(P(-58,1,14),'current_output_pad');join([P(-58,1,16),P(-58,1,15),P(-58,1,14)]);
 route('qualified_current_open',[[-58,1,14],[-54,5,14],[-16,5,14],[-16,5,10],[-16,0,5],[-10,0,5],[-10,0,3]]);
 // The initializer has one positive-polarity tower with two inversions per 4Y.
 // Its top is an actual source for the high NEXT clamp rail, not a remote alias.
 for(const x of[-101,-103,-105])rep(P(x,1,-6),'west','initialize_tower_input');for(const x of[-102,-104])wire(P(x,1,-6),'initialize_tower_feed');join([-100,-101,-102,-103,-104,-105,-106].map(x=>P(x,1,-6)));
 solid(P(-106,0,-6),'initialize_tower_floor');for(let y=1;y<=63;y++)if(y%2)solid(P(-106,y,-6),'initialize_tower');else put(P(-106,y,-6),'redstone_torch',undefined,'initialize_tower');put(P(-106,64,-6),'redstone_torch',undefined,'initialize_positive');rep(P(-105,64,-6),'east','initialize_top_export');wire(P(-104,64,-6),'initialize_top_pad');join([P(-106,64,-6),P(-105,64,-6),P(-104,64,-6)]);
 route('initialize_to_core_clamps',[[-104,64,-6],[28,64,-6],[28,64,4]]);
 for(const[n,d]of Object.entries(parents))for(const[name,p]of Object.entries(d.ports)){
  if(n==='core'&&['initialize','next_open','current_open'].includes(name))continue;
  if(n==='qualifier'&&['next_open','current_open'].includes(name))continue;
  assert(!ports[name],'Duplicate exported port');ports[name]={...structuredClone(p),bits:p.bits.map(bit=>({...bit,position:move(bit.position,n)}))};
 }
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=Math.min(...blocks.map(b=>b.position[a]));box.to[a]=Math.max(...blocks.map(b=>b.position[a]));}
 return{status:'offline_qualified_core_state_with_real_initialize_route',blocks,box,ports,edges,routes,parent_offsets:offsets,parents:Object.fromEntries(Object.entries(parents).map(([n,d])=>[n,{blocks:d.blocks.length}])),internal_connections:[{from:'qualifier.next_open',to:'core.next_open',route:'qualified_next_open'},{from:'qualifier.current_open',to:'core.current_open',route:'qualified_current_open'},{from:'qualifier.initialize',to:'core.initialize',route:'initialize_to_core_clamps',via:'positive32-inversiontower'}],metrics:{blocks:blocks.length,added_blocks:blocks.length-parents.core.blocks.length-parents.qualifier.blocks.length,stored_bits:6,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1]))},missing:['Shared phase producer fanout into phase_a/phase_b and all outer advance/ret/fault/permit/valid sources.','Initialization controller must blank actions, hold the real clamp through a complete NEXT-close-CURRENT-close, then settle before permitting normal state progress.','Actual worst-case OPEN closure, initialization tower/feedback delay and reset flush margins remain unmeasured.','Per-state/per-op/per-lane action qualification and all RF/ALU/LSU/fetch/PC handshake routes.'],native_acceptance:false,complete_gpu:false};
}
export function checkQualifiedCore(d){const map=new Map(d.blocks.map(b=>[K(b.position),b])),at=p=>map.get(K(p)),allowed=new Set(d.edges.map(e=>[K(e.from),K(e.to)].sort().join('|')));assert.equal(map.size,d.blocks.length);let supports=0,contacts=0,sides=0;const sameParent=(a,b)=>['core','qualifier'].includes(a.part)&&a.part===b.part;
 for(const b of d.blocks){if(b.block.id.endsWith('_concrete'))continue;let p=P(b.position.x,b.position.y-1,b.position.z);if(b.block.id==='minecraft:redstone_wall_torch'){const[x,z]=V[b.block.properties.facing];p=P(b.position.x-x,b.position.y,b.position.z-z);}assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(b.position));supports++;}
 for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))for(const[x,z]of Object.values(V))for(const dy of[-1,0,1]){const p=P(b.position.x+x,b.position.y+dy,b.position.z+z),o=at(p);if(!o||o.block.id.endsWith('_concrete')||sameParent(b,o))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at(P(b.position.x,b.position.y+1,b.position.z)))continue;if(dy===-1&&at(P(p.x,p.y+1,p.z)))continue;assert(allowed.has([K(b.position),K(p)].sort().join('|')),'Foreign contact '+K(b.position)+' '+K(p));contacts++;}
 for(const b of d.blocks.filter(b=>['minecraft:repeater','minecraft:comparator'].includes(b.block.id))){const dir=Object.keys(F).find(d=>F[d]===b.block.properties.facing),[dx,dz]=V[dir];for(const[x,z]of[[dz,dx],[-dz,-dx]]){const p=P(b.position.x+x,b.position.y,b.position.z+z),o=at(p);if(o&&['minecraft:repeater','minecraft:comparator'].includes(o.block.id)&&!sameParent(b,o))assert(allowed.has([K(b.position),K(p)].sort().join('|')),'Foreign diode side '+K(b.position));sides++;}}
 return{status:'author_static_qualified_core_checks_passed',...d.metrics,support_checks:supports,new_cross_component_dust_contacts:contacts,diode_side_faces:sides,native_acceptance:false};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeQualifiedCore(),r=checkQualifiedCore(d);if(process.argv.includes('--check'))assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(r,null,2));}
