import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{P,K}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),base=read('../shared-spine-v1/design.json'),g=read('../shared-state-inventory-v1/bodies.json').groups.find(g=>g.name==='shared_clock_scanner'),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>K(a)+'>'+K(b),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch';
const before=new Map(base.blocks.map(b=>[K(b.position),b.block])),after=new Map(d.blocks.map(b=>[K(b.position),b.block]));assert.equal(after.size,d.blocks.length);for(const b of base.blocks)assert.deepEqual(after.get(K(b.position)),b.block);for(const b of g.blocks)assert.deepEqual(after.get(K(A(b.position,d.clock_transform.delta))),b.block);
const expected=new Set(),preserved=[];for(const b of base.blocks)if(active(b.block))for(const q of inputs(before,b.position)){expected.add(pair(q,b.position));preserved.push({from:q,to:b.position});}for(const e of d.clock_internal){expected.add(pair(e.from,e.to));preserved.push(e);}for(const e of d.edges){expected.add(pair(e.from,e.to));if(after.get(K(e.from))?.id===W&&after.get(K(e.to))?.id===W)expected.add(pair(e.to,e.from));}
const actual=new Set,unexpected=[];let supports=0,receivers=0;for(const b of d.blocks){if([W,R,C,T].includes(b.block.id)){assert(after.get(K(P(b.position.x,b.position.y-1,b.position.z)))?.id.endsWith('_concrete'),'Support '+K(b.position));supports++;}if(!active(b.block))continue;receivers++;for(const q of inputs(after,b.position)){const p=pair(q,b.position);actual.add(p);if(!expected.has(p))unexpected.push({from:q,to:b.position,source:after.get(K(q)),target:b.block});}}
const lost=preserved.filter(e=>!actual.has(pair(e.from,e.to))),missing=d.edges.filter(e=>!actual.has(pair(e.from,e.to)));const dirs={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},stores=[];for(const b of d.blocks){if(b.block.id!==R)continue;const v=dirs[b.block.properties.facing],locks=[];for(const s of Object.values(dirs)){if(v.x*s.x+v.z*s.z)continue;const p=A(b.position,s),q=after.get(K(p));if([R,C].includes(q?.id)&&K(A(p,dirs[q.properties.facing]))===K(b.position))locks.push(p);}if(locks.length)stores.push({position:b.position,locks});}assert.equal(stores.length,1000);
const routeReports=[];for(const r of d.connections){const phase=r.name.includes('_a_')?'a':'b';assert.deepEqual(r.source,d.ports.shared_clock['phase_'+phase].bits[0].position);assert.deepEqual(r.destination,d.ports.rf_control['phase_'+phase].bits[0].position);assert.deepEqual(inputs(after,r.tap),[r.source]);assert.deepEqual(inputs(after,r.arrival),[r.end]);let power=15,minimum=15,ticks=0;const path=[r.source,r.tap,...r.path,r.arrival,r.destination];for(let i=1;i<path.length;i++){const p=path[i],b=after.get(K(p)),prev=after.get(K(path[i-1]));assert(inputs(after,p).some(q=>K(q)===K(path[i-1])));if(b.id===R){minimum=Math.min(minimum,power);assert(power>0);power=15;ticks+=2*Number(b.properties.delay);}else{assert.equal(b.id,W);power-=prev.id===W?1:0;assert(power>0);}}assert.equal(power,15);routeReports.push({name:r.name,nominal_route_ticks:ticks,minimum_rear_high:minimum,arrival_high:15});}
assert.equal(after.get(K(d.constant.source)).id,'minecraft:redstone_block');assert.deepEqual(inputs(after,d.constant.driver),[d.constant.source]);assert(inputs(after,d.constant.destination).some(p=>K(p)===K(d.constant.driver)));
// Detect actual scanner locks after extraction, and prove both repaired entry
// diodes remain necessary on source→lock paths. Incoming store edges are cut
// only for this structural clock-reachability query, not a data timing proof.
const movedStores=g.stores.map(s=>({position:A(s.position,d.clock_transform.delta),locks:s.locks.map(p=>A(p,d.clock_transform.delta)),phase:[302,260].includes(s.position.x)?'a':'b'})),storeKeys=new Set(movedStores.map(s=>K(s.position))),clockPositions=g.blocks.map(b=>A(b.position,d.clock_transform.delta));
function reach(world,source){const adj=new Map;for(const p of clockPositions){if(storeKeys.has(K(p)))continue;for(const q of inputs(world,p)){const k=K(q);if(!adj.has(k))adj.set(k,[]);adj.get(k).push(K(p));}}const seen=new Set([K(source)]),todo=[K(source)];for(let i=0;i<todo.length;i++)for(const k of adj.get(todo[i])??[])if(!seen.has(k)){seen.add(k);todo.push(k);}return seen;}
const phaseChecks=[];for(const phase of['a','b']){const source=d.ports.shared_clock['phase_'+phase].bits[0].position,seen=reach(after,source),own=movedStores.filter(s=>s.phase===phase),other=movedStores.filter(s=>s.phase!==phase);assert.equal(own.length,7);for(const s of own)assert(s.locks.every(p=>seen.has(K(p))),'Unreached scanner '+phase+' '+K(s.position));assert(other.every(s=>s.locks.every(p=>!seen.has(K(p)))));phaseChecks.push({phase,locks_reached:7,opposite_locks_reached:0});}
let negatives=0;for(const[local,wrong,phase]of[[P(-11,-2,3),'east','a'],[P(4,-2,0),'south','b']]){const p=A(local,d.clock_transform.translation),old=after.get(K(p));assert.equal(old.id,R);after.set(K(p),{...old,properties:{...old.properties,facing:wrong}});const seen=reach(after,d.ports.shared_clock['phase_'+phase].bits[0].position);assert(movedStores.filter(s=>s.phase===phase).some(s=>s.locks.some(p=>!seen.has(K(p)))),'Old clock-entry defect must refuse');after.set(K(p),old);negatives++;}
const r=d.connections[0],old=after.get(K(r.arrival));after.set(K(r.arrival),{...old,properties:{...old.properties,facing:'east'}});assert(!inputs(after,r.destination).some(p=>K(p)===K(r.arrival)));after.set(K(r.arrival),old);negatives++;
const report={status:unexpected.length||missing.length||lost.length?'refused':'actual_clock_scanner_and_RF_cadence_geometry_passed',cells:d.blocks.length,parent_cells:base.blocks.length,clock_cells:d.clock_cells,new_cells:d.cable_cells,stores:stores.length,remaining_shared_stores:117,supports,receivers,preserved_dependencies:preserved.length,actual_dependencies:actual.size,unexpected,lost,missing,routes:routeReports,scanner_phase_structural_reach:phaseChecks,negative_checks:negatives,source_sha256:Object.fromEntries(['prepare.mjs','check.mjs','design.json','paths.json','../shared-spine-v1/design.json','../shared-state-inventory-v1/bodies.json'].map(n=>[n,createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex')])),complete_core:false,native_acceptance:false};writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,unexpected:unexpected.slice(0,20),lost:lost.slice(0,20),missing:missing.slice(0,20)},null,2));assert.equal(report.status,'actual_clock_scanner_and_RF_cadence_geometry_passed');
