// Move the existing, actually repaired shared oscillator/scanner and connect
// two real RF bank cadence inputs. Action admission is not bypassed.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{P,K,V,F,searchPath,refreshIndices}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),under=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),W='minecraft:redstone_wire',R='minecraft:repeater',S='minecraft:light_gray_concrete';
const parent=read('../shared-spine-v1/design.json'),inventory=read('../shared-state-inventory-v1/bodies.json'),g=inventory.groups.find(g=>g.name==='shared_clock_scanner'),delta=P(320,-193,-162),seed=read('../../startup-scan-v1/clock/design.json'),sourceOrigin=P(300,233,-248),translation=A(sourceOrigin,delta),portSeed=materializeInstance({...seed,blocks:[]},{id:'shared_clock',translation}),addedBody=g.blocks.map(b=>({...b,position:A(b.position,delta),body:'shared/clock_scanner'})),rows=[...parent.blocks,...addedBody],map=new Map(rows.map(b=>[K(b.position),b]));assert.equal(map.size,rows.length);const parentCount=rows.length,edges=[],connections=[];let part='';
function put(p,id,pr){const block={id,...pr?{properties:pr}:{}},old=map.get(K(p));if(old){assert.equal(id,S,'Collision '+part+' '+K(p));assert.deepEqual(old.block,block);return;}const b={position:p,block,part};map.set(K(p),b);rows.push(b);}
const dev=(p,id,pr)=>{put(under(p),S);put(p,id,pr)},wire=p=>dev(p,W),rep=(p,d)=>dev(p,R,{facing:F[d],delay:'1'}),edge=(from,to)=>edges.push({from,to,route:part});
for(const phase of['a','b']){const source=portSeed.ports['phase_'+phase].bits[0].position,destination=parent.ports.rf_control['phase_'+phase].bits[0].position;connections.push({name:'shared_phase_'+phase+'_to_RF',source,destination,source_direction:'east',arrival_direction:'east',tap:P(source.x+1,source.y-1,source.z),start:P(source.x+2,source.y-2,source.z),arrival:step(destination,'east',-1),end:step(destination,'east',-2)});}
const reserve=c=>[...Array.from({length:14},(_,i)=>step(c.source,c.source_direction,i+2)),...Array.from({length:14},(_,i)=>step(c.destination,c.arrival_direction,-i-2))],reserved=connections.flatMap(reserve);for(const c of connections){part=c.name;rep(c.tap,'east');put(P(c.start.x,c.start.y+1,c.start.z),S);wire(c.start);rep(c.arrival,'east');wire(c.end);edge(c.source,c.tap);edge(c.tap,c.start);edge(c.end,c.arrival);edge(c.arrival,c.destination);}
const cacheUrl=new URL('paths.json',H),cache=existsSync(cacheUrl)?read('paths.json'):{};for(const c of connections){part=c.name;let path=cache[c.name]?.path;if(path){assert.deepEqual(cache[c.name].source,c.source);assert.deepEqual(cache[c.name].destination,c.destination);}else{const prefix=[...Array.from({length:4},(_,i)=>P(c.start.x,c.start.y-i,c.start.z-i)),P(c.start.x,c.start.y-3,c.start.z-4),P(c.start.x,c.start.y-3,c.start.z-5)];const r=searchPath(map,prefix.at(-1),c.end,{ignore:[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(under),...reserve(c),...prefix,...prefix.map(under)],reserved,limit:1600000});path=[...prefix,...r.path.slice(1)];cache[c.name]={source:c.source,destination:c.destination,path,expanded:r.expanded};writeFileSync(cacheUrl,JSON.stringify(cache)+'\n');console.log(c.name,path.length);}
const refresh=new Set(refreshIndices(path));for(let i=1;i<path.length-1;i++){const p=path[i];if(refresh.has(i))rep(p,Object.keys(V).find(d=>K(step(p,d))===K(path[i+1])));else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);c.path=path;c.refresh_indices=[...refresh];}
// The old RF distribution has this literal always-on source. Reset controls
// actions/initialization separately and must not halt controller bank cadence.
part='RF_bank_permit_constant';const permit=parent.ports.rf_control.bank_permit.bits[0].position,constant=step(permit,'east',-2),driver=step(permit,'east',-1);put(constant,'minecraft:redstone_block');rep(driver,'east');edge(constant,driver);edge(driver,permit);
const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const b of rows)for(const k of['x','y','z']){box.from[k]=Math.min(box.from[k],b.position[k]);box.to[k]=Math.max(box.to[k],b.position[k]);}
const out={status:'shared_clock_RF_cadence_connected_unchecked',blocks:rows,box,parent_cells:parentCount,prior_cells:parent.blocks.length,clock_cells:addedBody.length,cable_cells:rows.length-parentCount,clock_transform:{reference_origin:sourceOrigin,translation,delta},ports:{...parent.ports,shared_clock:portSeed.ports},clock_internal:g.internal.map(e=>({from:A(e.from,delta),to:A(e.to,delta)})),connections,edges,constant:{source:constant,driver,destination:permit},metrics:{cells:rows.length,physical_stores:1000,remaining_shared_stores:117},missing:['No phase timing claim: the real source-to-lock paths must be checked with all future fanout and state dependencies.','RF decoder conditioning, normal-zero initialization and action-window admission are still open and must not be replaced with raw phase.','ALU phase/init/admission and the other117 shared stores remain unfinished.'],complete_core:false,native_acceptance:false};writeFileSync(new URL('design.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({cells:rows.length,added:out.cable_cells,box}));
