import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{P,K,makeGate}from'./logic.mjs';import{evaluator}from'../rf-quiet-connected-v1/settled.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),parent=new URL('../final-exit-control-connected-v1/source-manifest.json',H);assert.equal(createHash('sha256').update(readFileSync(parent)).digest('hex'),'3d8d933de15da47ea748c551dd451b27eada9b6f6f2bfbfc749e8e14526f504e');const base=read('../final-exit-control-connected-v1/design.json'),prior=read('../final-exit-control-connected-v1/endpoint-map.json'),reference=read('original-functions.json'),old=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H))),original=new Map(old.blocks.map(b=>[K(b.position),b.block])),world=new Map(base.blocks.map(b=>[K(b.position),b.block])),mapping={...prior.mapping},replacement={...prior.replacement_interface_map},gates=[],connections=[],reports=[],roleBindings=[],addedMappings=[],fallbackDeliveries=[],existingTaps=read('existing-tap-proofs.json').reports,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),E=(a,b)=>K(a)+'>'+K(b),W='minecraft:redstone_wire';
function clear(g){if(g.blocks.some(b=>world.has(K(b.position))||['x','y','z'].some(a=>b.position[a]<base.box.from[a]||b.position[a]>base.box.to[a])))return false;const near=new Map;for(const b of g.blocks)for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++){if(Math.abs(x)+Math.abs(y)+Math.abs(z)>3)continue;const p=A(b.position,P(x,y,z));if(active(world.get(K(p))))near.set(K(p),p);}const expect=new Set(g.edges.map(e=>E(e.from,e.to)));for(const p of near.values())for(const q of inputs(world,p))expect.add(E(q,p));for(const b of g.blocks){world.set(K(b.position),b.block);if(active(b.block))near.set(K(b.position),b.position);}const actual=new Set;for(const p of near.values())for(const q of inputs(world,p))actual.add(E(q,p));for(const b of g.blocks)world.delete(K(b.position));return actual.size===expect.size&&[...actual].every(e=>expect.has(e));}
function add(g){assert(clear(g),'Gate contact '+g.kind);for(const b of g.blocks)world.set(K(b.position),b.block);gates.push(g);return g;}
function place(kind){for(const y of[204,212,220,228,196,188,180,172,164,156,148,140,132,124,116,108,100,92,84,76,68,60,52,44,36,28,20,12,4,-4,-12,-20,-28,-36,-44,-52])for(const z of[530,550,570,510,590,490,610,470,630,450,650,430])for(const x of[260,280,300,320,340,360,380,400,420,440,460,480,500,520,540,560]){const g=makeGate(kind,P(x,y,z));if(clear(g))return add(g);}throw Error('No isolated body '+kind);}
function fixedStub(kind,tap,dest){const d=mapping[K(dest)],shift=P(d.position.x-dest.x,d.position.y-dest.y,d.position.z-dest.z),dx=Math.sign(dest.x-tap.x),dz=Math.sign(dest.z-tap.z),arrival=P(tap.x+dx,tap.y,tap.z+dz),points=[tap,arrival],blocks=points.flatMap(p=>[P(p.x,p.y-1,p.z),p].map(original_position=>{assert(!mapping[K(original_position)]);const block=original.get(K(original_position));assert(block,'Missing exact stub '+K(original_position));return{position:A(original_position,shift),block,original_position,part:kind};})),g={kind,blocks,ports:{output:A(tap,shift),receiver:d.position},edges:[{from:A(tap,shift),to:A(arrival,shift)},{from:A(arrival,shift),to:d.position}],exact_original_translation:shift};if(!clear(g)){writeFileSync(new URL('rejected-exact-stub-'+kind+'.json',H),JSON.stringify({kind,attempted:g,occupied:blocks.filter(b=>world.has(K(b.position))).map(b=>({position:b.position,existing:world.get(K(b.position))})),resolution:'isolated function-preserving tap plus separately checked normalized arrival into the original receiver'},null,2)+'\n');const pad=place('historical_return_pad_'+kind);replacement[K(tap)]={position:pad.ports.output,body:pad.kind,mapping_kind:'historical_warm_only_tap_replacement_original_exact_stub_refused'};fallbackDeliveries.push({kind,tap,dest,arrival});return pad.ports.output;}add(g);for(const b of blocks){mapping[K(b.original_position)]={position:b.position,body:kind};addedMappings.push(b);}return g.ports.output;}
const historical=new Map(reference.historical_connections.map(r=>[r.name.replace('released_',''),r]));
const zeroStopTap=fixedStub('zero_stop_historical_delivery_stub',P(-416,197,433),P(-416,197,435));
const epochTap=fixedStub('warm_epoch_historical_delivery_stub',P(-104,64,-4),P(-104,64,-6));
const intentTap=fixedStub('intent_historical_delivery_stub',P(-44,-2,83),P(-44,-2,85));
const arch=place('architecture_mask_OR'),sample=place('sample_mask_OR'),local=place('withdrawal_local_subtract'),sampleTap=place('historical_return_pad');
const replacements=[['architecture_mask_return',P(-114,310,-90),arch.ports.output,arch.kind],['sample_mask_nominal',P(113,197,-110),sample.ports.output,sample.kind],['sample_mask_historical_return',P(446,197,-459),sampleTap.ports.output,sampleTap.kind],['local_reset_historical_return',P(-138,1,20),local.ports.output,local.kind]];for(const[name,p,position,body]of replacements){assert(!mapping[K(p)]);assert(!replacement[K(p)]);replacement[K(p)]={position,body,mapping_kind:'function_preserving_historical_interface_not_exact_cell_translation',name};}
const point=p=>mapping[K(p)]??replacement[K(p)];
function trace(name,source,target){const q=[target],seen=new Set(q.map(K));for(let i=0;i<q.length;i++){const p=q[i];if(K(p)===K(source))continue;for(const r of inputs(original,p))if(!seen.has(K(r))){seen.add(K(r));q.push(r);}}assert(seen.has(K(source)),'Original source missing '+name);const e=evaluator(original,q,{source}),cases=[0,1].map(source=>({source,value:e.solve({source}).at(target)}));assert(cases[0].value===0&&cases[1].value>0,'Original transport polarity '+name+JSON.stringify(cases));const report={name,original_source:source,original_receiver:target,nodes:q.map(position=>({position,block:original.get(K(position))})),cases};reports.push(report);return report;}
function conn(name,oldSource,oldDest,source=null,destination=null,kind='actual_original_positive_transport',role=null){const s=source??point(oldSource),t=destination??point(oldDest);assert(s&&t,name+' missing port');const r=trace(name,oldSource,oldDest);connections.push({name,source_passive_levels:existingTaps.find(t=>K(t.actual_historical_tap)===K(oldSource))?.passive_wire_component_signals??null,source_asserted_high:existingTaps.find(t=>K(t.actual_historical_tap)===K(oldSource))?.conditional_high??15,source:s.position,destination:t.position,original_source:oldSource,original_destination:oldDest,source_body:s.body,target_body:t.body,binding_kind:kind,functional_input_role:role,actual_reference_upstream:[{position:oldSource,parity:0}],upstream_transport_nodes:r.nodes.length,unary_torch_stages:r.nodes.filter(n=>n.block.id.includes('torch')).length});}
function gateInput(name,oldSource,oldDest,g,port){const entry={position:g.ports[port],body:g.kind};roleBindings.push({name,original_interface:oldDest,original_source:oldSource,current:entry,gate_role:port,classification:'function_preserving_input_interface_not_cell_translation'});conn(name,oldSource,oldDest,null,entry,'original_source_to_function_preserving_gate_input',port);}
for(const f of fallbackDeliveries)conn(f.kind+'_arrival',f.tap,f.arrival,null,point(f.dest),'positive_branch_arrival_into_existing_combined_receiver');
conn('external_initialize_to_retained_front',P(380,231,-263),P(-100,1,-8));
for(const row of reference.sources.slice(0,14)){const h=historical.get(row.name),source=row.old_tip;if(K(h.source)!==K(source)&&!existingTaps.some(t=>t.name===row.name&&t.status==='already_drawn_actual_parent_source_to_historical_tap_positive'))conn(row.name+'_restore_historical_source',source,h.source);conn('stage_clear_'+row.name,h.source,h.destination);}
gateInput('architecture_cold_input',P(-100,1,-8),P(-116,310,-90),arch,'A');gateInput('architecture_active_input',P(-213,141,310),P(-114,310,-92),arch,'B');conn('stage_clear_arch_mask',P(-114,310,-90),historical.get('arch_mask').destination);
conn('restore_warm_epoch_delivery',P(-336,228,445),P(-104,64,-4));conn('stage_clear_epoch_mask',P(-104,64,-4),historical.get('epoch_mask').destination);
conn('restore_intent_clear_delivery',P(-332,228,445),P(-44,-2,83));conn('stage_clear_intent_mask',P(-44,-2,83),historical.get('intent_mask').destination);
gateInput('sample_cold_input',P(380,231,-263),P(380,231,-263),sample,'A');gateInput('sample_warm_input',P(-328,228,445),P(-328,228,445),sample,'B');conn('restore_sample_historical_return',P(113,197,-110),P(446,197,-459));conn('stage_clear_sample_mask',P(446,197,-459),historical.get('sample_mask').destination);
gateInput('local_reset_rear_input',P(-324,228,445),P(-324,228,445),local,'A');gateInput('local_reset_withdrawal_input',P(344,174,545),P(-322,228,446),local,'B');conn('restore_local_reset_delivery',P(-138,1,20),P(-140,1,-2));conn('stage_clear_local_reset',P(-138,1,20),historical.get('local_reset').destination);
conn('stages_clear_to_final_logic',P(318,254,545),P(-524,62,575));
const gateCases=[];for(const g of[arch,sample,local]){const w=new Map(g.blocks.map(b=>[K(b.position),b.block])),e=evaluator(w,g.blocks.filter(b=>active(b.block)).map(b=>b.position),{A:g.ports.A,B:g.ports.B});for(let i=0;i<4;i++){const A=i&1,B=i>>1,v=e.solve({A,B}).at(g.ports.output);assert.equal(v,(g.kind.endsWith('_OR')?A||B:A&&!B)?15:0);gateCases.push({kind:g.kind,A,B,value:v});}}
const body={...base,blocks:[...base.blocks,...gates.flatMap(g=>g.blocks)],logic_bodies:gates,metrics:{cells:world.size,parent_cells:base.blocks.length,logic_body_additions:gates.reduce((n,g)=>n+g.blocks.length,0),new_transport_cells:0,stored_bits:1117}};writeFileSync(new URL('body-design.json',H),JSON.stringify(body)+'\n');writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({...prior,mapping,mapped_original_cells:Object.keys(mapping).length,replacement_interface_map:replacement,function_preserving_gate_input_roles:roleBindings,connections,cuts:prior.cuts,unmatched:[],inherited_open_obligations:'../final-exit-control-connected-v1/timing-and-composition.json',complete_core:false,native_acceptance:false})+'\n');writeFileSync(new URL('preflight.json',H),JSON.stringify({status:'isolated_predicate_bodies_and_exact_historical_delivery_stubs_placed',gates,gate_cases:gateCases,added_exact_original_mappings:addedMappings,replacement_interfaces:replacements.map(([name,original])=>({name,original,...replacement[K(original)]})),functional_gate_input_roles:roleBindings,routes:connections.map(c=>({name:c.name,source:c.source,receiver:c.destination,original_source:c.original_source,original_receiver:c.original_destination,kind:c.binding_kind})),metrics:body.metrics,complete_core:false,native_acceptance:false},null,2)+'\n');writeFileSync(new URL('transport-functions.json',H),JSON.stringify({status:'actual_original_positive_transports_and_identity_input_roles_proved',reports,complete_core:false,native_acceptance:false},null,2)+'\n');console.log(JSON.stringify({metrics:body.metrics,routes:connections.length,gates:gates.map(g=>({kind:g.kind,cells:g.blocks.length,ports:g.ports}))},null,2));
