import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {resolve,relative} from 'node:path';
const H=fileURLToPath(new URL('.',import.meta.url)),ROOT=resolve(H,'../../..'),C=resolve(H,'../compact-core-guard-v1'),read=p=>JSON.parse(readFileSync(p)),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const expected='cb4b955e6e7405a637e4573ef629f3a53ca3065377f9d519d0e9730150fab922';assert.equal(hash(resolve(C,'source-manifest.json')),expected);
const sources={...read(resolve(C,'source-manifest.json')).source_sha256};sources[relative(ROOT,resolve(C,'source-manifest.json'))]=expected;
const files=['README.md','freeze.mjs','candidate-pin-checks.json','discover.py','storage-discovery.json','check-phase.py','actual-graph-cache.npz','actual-graph-cache-pins.json','phase-checks.json','check-materialization.mjs','materialization-review.json','check-route-graph.py','route-graph-checks.json','check-selected-transfers.py','selected-transfer-checks.json','check-pc-feedback.py','pc-feedback-checks.json','pc-feedback-witnesses.json','check-direct-pairs.py','direct-pair-checks.json','check-pair-feedback.py','pair-feedback-checks.json','pair-feedback-negative-witnesses.json','check-pair-feedback-opening.py','pair-feedback-opening-checks.json','pair-feedback-opening-negative-witnesses.json','check-stored-dependencies.py','stored-dependency-checks.json','stored-pass-A.npz','stored-pass-B.npz','check-front-state-paths.py','front-state-checks.json'];
for(const n of files){const p=resolve(H,n);sources[relative(ROOT,p)]=hash(p);if(n.endsWith('.json')){const d=read(p);for(const [f,h]of Object.entries(d.source_sha256??{})){if(sources[f])assert.equal(sources[f],h,f);sources[f]=h;}}}
for(const [p,h]of Object.entries(sources))assert.equal(hash(resolve(ROOT,p)),h,p);
const m=read(resolve(H,'materialization-review.json')),p=read(resolve(H,'phase-checks.json')),g=read(resolve(H,'route-graph-checks.json')),t=read(resolve(H,'selected-transfer-checks.json')),f=read(resolve(H,'pc-feedback-checks.json')),pairs=read(resolve(H,'direct-pair-checks.json')),own=read(resolve(H,'pair-feedback-opening-checks.json')),all=read(resolve(H,'stored-dependency-checks.json'));
assert.equal(m.candidate_cells,1828787);assert.equal(p.stores,1117);assert.equal(g.actual_consecutive_edges,18849);assert.equal(g.routes.length,41);assert.equal(g.all_phase_latest_arrivals_nonincreasing,true);assert.equal(pairs.pairs,74);assert.equal(own.nonpositive_finite_rows,0);
const manifest={status:'bounded_independent_guard_geometry_and_selected_nominal_timing_review',candidate_manifest_sha256:expected,source_sha256:Object.fromEntries(Object.entries(sources).sort()),native_acceptance:false,full_core_timing_acceptance:false};
const mp=resolve(H,'source-manifest.json');if(process.argv.includes('--check'))assert.deepEqual(read(mp),manifest);else writeFileSync(mp,JSON.stringify(manifest,null,2)+'\n');
const report={status:'bounded_independent_guard_geometry_and_selected_timing_review_passed',manifest_sha256:hash(mp),candidate_manifest_sha256:expected,source_sha256:manifest.source_sha256,geometry:{cells:m.candidate_cells,translated_cells:8853,routes:41,actual_route_edges:g.actual_consecutive_edges,stores:1117,moved_port_coordinates:43,preserved_shared_boundary_cell_occurrences:m.shared_prefix_suffix_cells},nominal_timing:{pc_next_to_current:t.minimum_PC_nominal_setup,pc_own_feedback:f.minimum_finite_margin,fault_next_to_current:t.fault_nominal_setup,adjacent_pairs:pairs.pairs,adjacent_minimum_setup:pairs.minimum_nominal_data_setup,own_feedback_finite_minimum:own.minimum_finite_setup,own_feedback_unbounded:own.unbounded_rows},unqualified_inventory:all.summary,scope_limits:['Foreign-frame effective-input execution is source-bound author evidence; independent materialization and actual local graph/cables are replayed here.','All nominal setup claims require physical phase/pulse/stable-qualification conditions. Same-phase and mode-sensitive paths remain explicit.','Normal FETCH return-to-zero certificate has unearned integrated cold/reset entry gates. Smaller routes do not establish those gates.'],native_acceptance:false,full_core_timing_acceptance:false,selection_authorized:false};
const rp=resolve(H,'independent-review.json');if(process.argv.includes('--check'))assert.deepEqual(read(rp),report);else writeFileSync(rp,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({manifest_sha256:hash(mp),review_sha256:hash(rp),pins:Object.keys(sources).length,full_core_timing_acceptance:false}));
