import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeChannelBackendControl}from'../../../../hardware/memory-layout-channel-backend-compact-v1.mjs';import{makeStateBank}from'../../../../hardware/full-gpu-state-bank.mjs';
const d=makeChannelBackendControl(),saved=JSON.parse(readFileSync(new URL('design.json',import.meta.url)));const h=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');assert.equal(h(d),h(saved));const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block])),H=d.outputs.capture_set.y;
function geometry(mm){
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],b=mm.get(K(p));assert(b,'cut '+r.name);assert(['minecraft:redstone_wire','minecraft:repeater'].includes(b.id));if(b.id==='minecraft:repeater'){const v=D[b.properties.facing];if(i)assert.deepEqual(r.path[i-1],P(p.x-v.x,p.y,p.z-v.z));if(i+1<r.path.length)assert.deepEqual(r.path[i+1],P(p.x+v.x,p.y,p.z+v.z));}}
 for(const g of d.gates){const v=mm.get(K(g.gate));assert.deepEqual(v,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});assert.deepEqual(mm.get(K(g.rear)),{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(mm.get(K(g.mask)),{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});const key=g.literal.replace('!',''),x=d.variables.indexOf(key)*5,y=g.gate.y;assert.equal(mm.get(K(P(x,y,-3)))?.id,g.literal.startsWith('!')?'minecraft:redstone_wire':'minecraft:light_gray_concrete');if(!g.literal.startsWith('!'))assert.deepEqual(mm.get(K(P(x+1,y,-3))),{id:'minecraft:redstone_wall_torch',properties:{facing:'east'}});}
 for(const f of d.feedback){assert.equal(mm.get(K(f.destination))?.id,'minecraft:redstone_wire');assert.deepEqual(mm.get(K(f.normalizer)),{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});}
 const b=makeStateBank({width:8,pair:false});for(const v of b.blocks)assert.deepEqual(mm.get(K(P(v.position.x+130,v.position.y+H,v.position.z+100))),v.block);
 for(const v of d.states){for(const[name,dx,f]of[['positive',1,'east'],['negative',-1,'west']]){const p=v[name],q=P(p.x-dx,p.y,p.z);assert.deepEqual(mm.get(K(q)),{id:'minecraft:redstone_wall_torch',properties:{facing:f}});}assert.equal(mm.get(K(v.set))?.id,'minecraft:redstone_wire');assert.equal(mm.get(K(v.clear))?.id,'minecraft:redstone_wire');}
}
geometry(m);let cases=0;
const evalTerms=v=>Object.fromEntries(Object.entries(d.terms).map(([n,ts])=>[n,Number(ts.some(t=>t.every(l=>l.startsWith('!')?!v[l.slice(1)]:!!v[l])))]));
for(let bits=0;bits<2**d.variables.length;bits++){const v=Object.fromEntries(d.variables.map((n,i)=>[n,bits>>i&1]));const{active:a,bank_ready:r,owner_valid:o,reset_blocked:z,ready_t1:t1,ready_t2:t2,ready_t3:t3,retiring_t1:u1,retiring_t3:u3,captured:c,retiring:x}=v;const expected={capture_set:a&&r&&t2&&!z&&!x,capture_clear:z||!a||u1,retiring_set:a&&c&&!r&&!t3&&!o&&!z&&!x,retiring_clear:z||!a,bank_request:a&&!c&&!x&&!u3&&!z,open_response:a&&r&&!t1&&!c&&!x&&!z,consumer_ready:a&&c&&!r&&!t3&&!x&&!z,retire:x&&u3&&!c&&!r&&!t3&&!z,backend_busy:c||x||u3||r||t3};assert.deepEqual(evalTerms(v),Object.fromEntries(Object.entries(expected).map(([n,v])=>[n,Number(!!v)])));cases++;}
// Settled event ordering, distinct from native delay guarantees. The two SR
// values actually persist; ready falling alone must not clear CAPTURED.
let eventCases=0;for(const data of[0,1,0x55,0xaa,255]){let v=Object.fromEntries(d.variables.map(n=>[n,0])),stored=null;const update=patch=>{Object.assign(v,patch);let q=evalTerms(v);assert(!(q.capture_set&&q.capture_clear));assert(!(q.retiring_set&&q.retiring_clear));if(q.capture_clear)v.captured=0;else if(q.capture_set)v.captured=1;if(q.retiring_clear)v.retiring=0;else if(q.retiring_set)v.retiring=1;q=evalTerms(v);eventCases++;return q;};update({reset_blocked:1});update({reset_blocked:0,active:1,owner_valid:1});assert.equal(update({}).bank_request,1);assert.equal(update({bank_ready:1}).open_response,1);stored=data;assert.equal(update({ready_t1:1}).open_response,0);assert.equal(update({ready_t2:1,ready_t3:1}).bank_request,0);assert(v.captured);assert.equal(update({bank_ready:0}).consumer_ready,0);update({ready_t1:0,ready_t2:0});assert.equal(update({ready_t3:0}).consumer_ready,1);assert.equal(stored,data);assert.equal(update({owner_valid:0}).bank_request,0);assert(v.retiring&&v.captured);assert.equal(update({retiring_t1:1}).bank_request,0);assert(!v.captured);assert.equal(update({retiring_t3:1}).retire,1);assert.equal(update({active:0}).backend_busy,1);assert.equal(update({retiring_t1:0}).bank_request,0);assert.equal(update({retiring_t3:0}).backend_busy,0);}
let negative=0;for(const mutate of[mm=>mm.delete(K(d.routes[0].path[2])),mm=>mm.set(K(d.gates[0].mask),{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}}),mm=>mm.set(K(d.gates[0].gate),{id:'minecraft:comparator',properties:{facing:'west',mode:'compare'}}),mm=>mm.delete(K(d.response[7].lock)),mm=>mm.delete(K(d.states[0].set)),mm=>mm.delete(K(d.feedback.at(-1).destination))]){const mm=new Map(m);mutate(mm);assert.throws(()=>geometry(mm));negative++;}
const out={status:'offline_channel_backend_control_geometry_protocol_checks_pass',...d.metrics,exact_regeneration:true,boolean_input_cases:cases,settled_lifecycle_events:eventCases,corruptions_rejected:negative,complete_data_memory:false,native_acceptance:false,limits:['Settled retained event model only; no scheduled redstone or timing simulation.','Standalone local controller has real internal routes; full four-channel/bank/consumer external routes remain separate.']};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
