import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';
import{makeGlobalInputSampler,makeSampleConjunctions,SAMPLE_INPUTS,READY_INPUTS,GROUPS}from'../../../hardware/full-gpu-global-input-sampler-v1.mjs';
import{makeStateBank}from'../../../hardware/full-gpu-state-bank.mjs';
import{materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
import{possibleStrengths}from'../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeGlobalInputSampler();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));
const parents=d.parents.map(p=>materializeInstance(p.id==='sample0'?makeStateBank({width:8,pair:false}):p.id==='sample1'?makeStateBank({width:7,pair:false}):makeSampleConjunctions(),{id:p.id,translation:p.origin}));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to))),parentIds=new Set(d.parents.map(v=>v.id));assert.equal(m.size,d.blocks.length);let inherited=0,supports=0,contacts=0,directions=0;
 for(const p of parents)for(const v of p.blocks){assert.deepEqual(at(v.position)?.block,v.block);inherited++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete')||v.block.id==='minecraft:redstone_block')continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.output_y-c.bottom)%4,1);for(let y=c.bottom;y<c.output_y;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.output_y,c.z))?.block.id,'minecraft:redstone_wire');assert.deepEqual(add(c.injector,D[at(c.injector).block.properties.facing]),P(c.x,c.bottom,c.z));}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||o.block.id.endsWith('_concrete'))continue;if(parentIds.has(v.part)&&o.part===v.part)continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q));contacts++;}
 for(const v of d.blocks.filter(v=>!parentIds.has(v.part)&&v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const s of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete'),'Foreign side '+K(v.position));}directions++;}
 assert.equal(d.samples.length,15);assert.equal(d.connections.length,13);for(const[i,s]of d.samples.entries()){assert.equal(s.name,SAMPLE_INPUTS[i]);assert.deepEqual(s.source,parents[i<8?0:1].ports.state.bits[i%8].position);assert.equal(at(s.storage).block.id,'minecraft:repeater');assert.deepEqual(add(s.lock,D[at(s.lock).block.properties.facing]),s.storage);assert.deepEqual(d.ports[s.name].bits[0].position,parents[i<8?0:1].ports.next_data.bits[i%8].position);if(i>=2){const c=d.connections[i-2];assert.equal(c.name,s.name);assert.deepEqual(c.source,s.source);assert.deepEqual(c.destination,parents[2].ports[s.name].bits[0].position);assert.deepEqual(add(c.normalizer,D[at(c.normalizer).block.properties.facing]),c.destination);}}
 for(let i=0;i<2;i++){assert.deepEqual(d.ports['phase_B_'+i].bits,parents[i].ports.state_open.bits);assert.deepEqual(d.ports['sampled_'+SAMPLE_INPUTS[i]].bits,[{...parents[0].ports.state.bits[i],bit:0}]);}
 const power=possibleStrengths(d);assert.deepEqual(power.failed,[]);return{preserved_parent_cells:inherited,support_checks:supports,new_wire_contact_checks:contacts,new_directed_repeaters:directions,actual_sample_routes:13,possible_strength:power};}
const checks=check(d);let corruptions=0;for(const mutate of[c=>{const p=c.connections[0].normalizer;c.blocks.find(v=>K(v.position)===K(p)).block.properties.facing='south';},c=>{c.connections[1].source=c.connections[0].source;},c=>{const p=c.columns[0].injector;c.blocks=c.blocks.filter(v=>K(v.position)!==K(p));},c=>{c.ports.phase_B_1=c.ports.phase_B_0;}]){const v=structuredClone(d);mutate(v);assert.throws(()=>check(v));corruptions++;}
// Drawn literal masks after complete B closure and settling, not live events.
const logic=makeSampleConjunctions(),tower=new Map(logic.towers.map(t=>[t.name,t]));let truth=0;
for(let bits=0;bits<32768;bits++){const held=Object.fromEntries(SAMPLE_INPUTS.map((n,b)=>[n,!!(bits&(1<<b))]));for(const [out,names]of Object.entries(GROUPS)){const b=Object.keys(GROUPS).indexOf(out),rows=logic.rows.filter(r=>r.bits.includes(b)),actual=rows.some(r=>r.gates.every(g=>{const t=tower.get(g.name),parity=((r.y-t.first_y)/2)%2;assert(Number.isInteger(parity));return held[g.name]===!!(g.wanted^parity);}));assert.equal(actual,names.every(n=>held[n]));}truth++;}
const result={status:'authored_offline_global_individual_samples_and_conjunctions_pass',...d.metrics,...checks,drawn_sample_truth_cases:truth,corruption_refusals:corruptions,native_calls:0,native_acceptance:false,complete_gpu_layout:false,limits:d.missing};
if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,possible_strength:{...result.possible_strength,taps:undefined}}));
