import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('local-qualified.json'),p=JSON.parse(readFileSync(new URL('../channel-backend-compact-v1/design.json',H))),K=q=>`${q.x},${q.y},${q.z}`,P=(x,y,z)=>({x,y,z}),D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},m=new Map(d.blocks.map(v=>[K(v.position),v.block]));
for(const v of p.blocks)assert.deepEqual(m.get(K(v.position)),v.block);assert.deepEqual(d.states,p.states);assert.deepEqual(d.response,p.response);assert.deepEqual(d.delays,p.delays);assert.deepEqual(d.terms,p.terms);
const added=d.blocks.filter(v=>!p.nets[K(v.position)]);assert.equal(added.length,78);const q=d.bank_tail_qualification;
function evaluate(raw,rows=added){const map=new Map(rows.map(v=>[K(v.position),v.block])),fixed=new Map([['100,61,2',raw[0]*15],['104,61,2',raw[1]*15],['110,61,12',raw[2]*15]]),power=new Map(fixed);let passes=0;
 const at=q=>map.get(K(q)),val=q=>power.get(K(q))??0,travel=b=>D[b.properties.facing];
 for(;passes<100;passes++){const next=new Map(fixed);for(const[k,b]of map){if(fixed.has(k)||b.id.endsWith('_concrete'))continue;const[x,y,z]=k.split(',').map(Number);let n=0;
  if(b.id==='minecraft:redstone_wire'){for(const[dx,dz]of Object.values(D)){const s=P(x+dx,y,z+dz),bs=at(s);if(fixed.has(K(s))||bs?.id==='minecraft:redstone_wire')n=Math.max(n,val(s)-1);else if(['minecraft:repeater','minecraft:comparator'].includes(bs?.id)){const t=travel(bs);if(s.x+t[0]===x&&s.z+t[1]===z)n=Math.max(n,val(s));}}}
  else{const t=travel(b),rear=P(x-t[0],y,z-t[1]);n=val(rear);if(b.id==='minecraft:repeater')n=n>0?15:0;else{const sides=Object.values(D).filter(v=>v[0]*t[0]+v[1]*t[1]===0);n=Math.max(0,n-Math.max(...sides.map(([dx,dz])=>val(P(x+dx,y,z+dz)))));}}
  next.set(k,n);
 }const same=[...next].every(([k,v])=>v===power.get(k));power.clear();for(const[k,v]of next)power.set(k,v);if(same)break;}
 assert(passes<100,'Qualifier did not settle');return [power.get('100,61,8')??0,power.get('104,61,8')??0];
}
const cases=[];for(let v=0;v<8;v++){const raw=[v&1,v>>1&1,v>>2&1],expected=[raw[0]&&!raw[2]?15:0,raw[1]||raw[2]?15:0],actual=evaluate(raw);assert.deepEqual(actual,expected);cases.push({raw,expected,actual});}
let negatives=0;for(const pos of['100,61,6','99,61,6','105,61,6']){const bad=structuredClone(added),v=bad.find(v=>K(v.position)===pos);assert(v);v.block.properties.facing={north:'south',south:'north',east:'west',west:'east'}[v.block.properties.facing];let refused=false;try{refused=cases.some(c=>JSON.stringify(evaluate(c.raw,bad))!==JSON.stringify(c.expected));}catch(error){assert.equal(error.message,'Qualifier did not settle');refused=true;}assert(refused);negatives++;}
const result={status:'qualified_local_structural_and_settled_logic_passed',preserved_compact_cells:p.blocks.length,added_cells:78,retained_protocol_bits:2,retained_response_bits:8,slow_repeaters:d.metrics.slow_repeaters,cases,negative_direction_cases:negatives,limits:['This small normalized settled 3-input qualifier model is not a Minecraft event simulator or timing proof.','The complete frozen backend logic, response stores and physical delay chains remain byte-exact.'],native_acceptance:false};writeFileSync(new URL('local-checks.json',H),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({cases:cases.length,negatives,preserved:p.blocks.length,added:78}));
