// Exact explicit source manifest. Reviews and future attempts are not inputs.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';
import{makeSourcePinHasher}from'../../../../scripts/source-pin-hasher.mjs';
const H=new URL('./',import.meta.url),ROOT=fileURLToPath(new URL('../../../../',H)),B='artifacts/full-gpu-layout-v1/memory/channel-colocation-v1/',audit=makeSourcePinHasher(ROOT),read=p=>JSON.parse(readFileSync(ROOT+'/'+p)),files={};
const add=(p,h)=>{if(files[p])assert.equal(files[p],h,'Conflicting inherited source '+p);files[p]=h;};
const manifests=new Set(['artifacts/full-gpu-layout-v1/memory/channel-backend-compact-v1/source-manifest.json','artifacts/full-gpu-layout-v1/memory/internal-bank-response-v1/source-manifest.json','artifacts/full-gpu-layout-v1/memory/internal-runtime-timing-v1/source-manifest.json','artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v2/source-manifest.json']);
for(const n of['selected-frame.json','selected-frame-v2.json'])for(const c of read(B+n).instances){manifests.add(c.source_manifest);add(c.path,c.sha256);add(c.source_manifest,c.source_manifest_sha256);}
for(const p of manifests){add(p,audit.hash(p));const m=read(p),pins=m.source_sha256??m.files;assert(pins&&typeof pins==='object'&&!Array.isArray(pins),'Unsupported manifest '+p);for(const[k,v]of Object.entries(pins))add(k,v);}
const own=['extract.mjs','extraction.json','extracted-map.json','check-boundary.mjs','boundary-checks.json','search-placement.mjs','placement-search.json','local-qualified.json','check-local.mjs','local-checks.json','check-local-power.py','local-power-checks.json','layout.mjs','route.mjs','routes-with-foreign-candidate-3.json','trial-design.json','prepare-foreign.mjs','foreign-obstacles.json','selected-frame.json','check-effective.mjs','effective-checks.json','refresh-selection.mjs','selected-frame-v2.json','selection-refresh.json','reconcile-cold.mjs','cold-reconciliation.json','prepare-timing.mjs','timing-slices.json','check-local-timing.py','backend-events.json','backend-event-witnesses.json','check-transport-timing.py','control-cables.json','control-cable-witnesses.json','adjust-cable-timing.py','cable-delay.json','combine-timing.py','runtime-combined.json','audit-original-feedback.mjs','original-feedback-audit.json','comparison.json','retained-diagnostics.json','routes-candidate-3.json','failed-original-response-q-timing.log','failed-original-consumer-ready-timing.log','failed-partial-halo-timing.log','failed-stale-selection-reconciliation.log','README.md','RESUME.md','freeze.mjs'];
for(const p of own.map(n=>B+n).concat(['hardware/memory-layout-channel-backend-qualified-compact-v1.mjs','hardware/memory-layout-large-json-v2.mjs','scripts/source-pin-hasher.mjs','artifacts/full-gpu-layout-v1/control-commit-v2/route.mjs','artifacts/full-gpu-layout-v1/compact-core-fault-v1/check.mjs']))add(p,audit.hash(p));
for(const[p,h]of Object.entries(files))assert.equal(audit.hash(p),h,'Source drift '+p);audit.assertStable();
const expected={status:'source_frozen_unselected_complete_channel0_replacement_patch',geometry_filename:'trial-design.json',geometry_role:'explicit_removal_and_addition_patch_not_full_memory',source_sha256:Object.fromEntries(Object.entries(files).sort()),selected:false,complete_memory_acceptance:false,native_acceptance:false};
if(process.argv.includes('--check'))assert.deepEqual(read(B+'source-manifest.json'),expected);else writeFileSync(new URL('source-manifest.json',H),JSON.stringify(expected,null,2)+'\n');
console.log(JSON.stringify({status:expected.status,source_pins:Object.keys(files).length,manifest_sha256:audit.hash(B+'source-manifest.json'),...audit.stats()}));
