// Explicit full-cell comparison with the selected eight-substitution parent.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';
const H=new URL('./',import.meta.url),ROOT=fileURLToPath(new URL('../../../../',H)),K=p=>`${p.x},${p.y},${p.z}`,hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const selected=JSON.parse(readFileSync(new URL('selected-frame-v2.json',H))),prior=JSON.parse(readFileSync(new URL('selected-frame-v2.json',H))),refresh=JSON.parse(readFileSync(new URL('selection-refresh.json',H)));
if(process.argv.includes('--current-selection'))assert.deepEqual(JSON.parse(readFileSync(ROOT+'/artifacts/full-gpu-layout-v1/machine-candidate-v1/config.json')).instances,selected.instances,'Current frame differs from frozen frame');
assert.equal(refresh.status,'foreign_rows_unchanged_after_explicit_distant_core_replacement');
assert.deepEqual(selected.instances.filter(v=>v.name!=='memory'),prior.instances.filter(v=>v.name!=='memory'),'Foreign selection requires a new screen');
const memory=selected.instances.find(v=>v.name==='memory');assert.equal(memory.sha256,'364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');assert.equal(hash(ROOT+'/'+memory.path),memory.sha256);
const base=readLargeDesign(fileURLToPath(new URL('extracted-map.json',H))),d=readLargeDesign(ROOT+'/'+memory.path),trial=readLargeDesign(fileURLToPath(new URL('trial-design.json',H))),old=new Map([...base.blocks,...base.removed].map(v=>[K(v.position),v.block]));assert.equal(old.size,d.blocks.length);
const changes=[];for(const r of d.blocks){const b=old.get(K(r.position));assert(b,'Added coordinate');if(JSON.stringify(b)!==JSON.stringify(r.block))changes.push({position:r.position,before:b,after:r.block});}
assert.equal(changes.length,8);const expected=['-628,-30,896','-627,-30,896','-839,-38,860','521,-31,350','-111,-23,568','321,-23,568','-111,-23,1190','321,-23,1190'];assert.deepEqual(changes.map(v=>K(v.position)).sort(),expected.sort());
const changed=[...trial.blocks,...trial.removed];for(const r of changes){r.distance_to_relocation=changed.reduce((n,v)=>Math.min(n,Math.abs(v.position.x-r.position.x)+Math.abs(v.position.y-r.position.y)+Math.abs(v.position.z-r.position.z)),Infinity);assert(r.distance_to_relocation>4,'Cold change enters replacement power halo');}
const out={status:'explicit_cold_v2_reconciliation_passed',source_sha256:{[memory.path]:memory.sha256,[memory.source_manifest]:memory.source_manifest_sha256,'artifacts/full-gpu-layout-v1/memory/channel-colocation-v1/trial-design.json':hash(new URL('trial-design.json',H)),'artifacts/full-gpu-layout-v1/memory/channel-colocation-v1/reconcile-cold.mjs':hash(new URL('reconcile-cold.mjs',H))},old_cells:old.size,selected_cells:d.blocks.length,changes,foreign_instances_unchanged:true,materialized:false,selected:false,native_acceptance:false,cold_contract:d.cold_reset_contract};
writeFileSync(new URL('cold-reconciliation.json',H),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,changes:8,minimum_distance:Math.min(...changes.map(v=>v.distance_to_relocation))}));
