"""Offline acceptance specification, never a Minecraft execution record."""
from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;R=H.parents[2]
def read(name):return json.loads((H/name).read_text())
cases=read('cases.json');sources=read('image-source-map.json')
required=['wrong world/session refuses writes','shared writer lock has one owner','exact selected geometry and patch hashes match','bounded backup before each installation region','readbacks match all installed static states','all occupied ticking columns are verified active independent of player','clock phases observed advancing at current verified tick rate','body/view unchanged','all clocks run throughout cold conditioning and drains']
sequence=[
 {'stage':'initialize','actions':['START=0; IMAGE_VERIFIED=0; all four RAM WRITE strobes=0','Assert explicit BOOT for destructive pre-run conditioning','Hold through measured reset paths and required clock traversals; wait actual cold/conditioned witnesses','Withdraw BOOT only after checked physical dwell and drain criteria; do not infer timing from wall-clock sleep'],'observe':['global cold/normal state','core cold/reset ACK and all core faults','program ACTIVE/tail/reset-blocked','bank ACTIVE/owner/payload/commit/quiet','global memory admission-close witness']},
 {'stage':'acquire_load','actions':['Hold LOAD request high until physical loader owner and program/RAM grants are high','Keep START=0 and IMAGE_VERIFIED=0 throughout loading'],'refuse':['Any grant missing','Either core epoch-qualified completion missing','Any bank tail/accepted transaction still live']},
 {'stage':'program_image','actions':['Set exactly4096 ROM source positions from programEdits(case.program)','Read every source state back and reconstruct all256 words'],'forbidden':['Changing words without program grant','Loading expected outputs as program operands']},
 {'stage':'ram_image','actions':['For each of256 addresses, set slot4 address/data panel levers while WRITE=0','Assert WRITE; hold address/data until that slot WREADY=1','Withdraw WRITE; retain payload until WREADY=0 and bank tail/busy is low','Read all2048 retained RAM bits with all2048 side locks closed; compare all256 initial bytes'],'forbidden':['Directly setting RAM storage repeaters','Using expected_memory to initialize memory']},
 {'stage':'configure','actions':['With core reset held and DCR reset permit valid, set eight DCR input levers to case.thread_count','Use the actual DCR write control and read its eight held outputs','Verify complete ROM/RAM/DCR images, then raise IMAGE_VERIFIED','Release LOAD, wait grants/owner low and actual normal/admission-ready conditions']},
 {'stage':'launch','actions':['Raise START once and hold according to the physical launch protocol'],'runtime_host_compute_or_memory_writes':[],'observe':['Both core activity and assigned block IDs/lane masks','instruction retire events, PC, register/flag effects','physical memory accepts/commit owners/addresses/data','global DONE and per-core faults']},
 {'stage':'check','actions':['Wait for observed DONE or retained fault under a measured bounded watchdog','On success read all256 actual RAM bytes; compare with independent expected_memory','Validate masks/assignments cover exactly the requested logical threads','Validate untouched memory and inactive-lane suppression','Verify no unexpected fault and no residual write/owner activity after completion','Lower START only after evidence capture'],'timeout_policy':'A timeout is a failed/unfinished physical test, never a pass or substituted software result'}]
normal=[]
for c in cases['cases']:
 normal.append({'case':c['name'],'input_image_fields':['program','data','thread_count'],'oracle_read_only_fields':['expected_memory','oracle_final_registers','oracle_retired_core_instructions'],'required_final_bytes':256,'required_thread_ids':list(range(c['thread_count'])),'both_physical_cores_required':c['thread_count']>=8,'expected_logical_blocks':c['expected_blocks'],'required_no_launch':c['thread_count']==0,'result':None})
control=[]
for phase in ['before_fetch','owned_program_fetch','decode','register_read','alu_iterating','before_data_valid','owned_data_read','owned_data_write','register_writeback','pc_flags_commit','instruction_retire','between_blocks']:
 for request in ['warm_reset','load']:
  control.append({'name':request+'_during_'+phase,'trigger':'read-only observation identifies '+phase,'stimulus':'assert only the named external '+request+' request; do not synthesize internal ACK or alter data','checks':['new admission stops at the defined boundary','already accepted transactions drain exactly once','memory is not rolled back or silently rewritten','actual core held ACK waits RF/ALU/LSU/program closure','qualified completion matches current held reset epoch','LOAD grant waits both completions plus fresh memory close traversal','reset/rearm finishes with defined architectural zero/ID state','after full fresh image loading the next valid kernel passes'],'result':None})
control += [
 {'name':'load_at_completion_withdrawal','stimulus':'phase-sweep an external LOAD assertion around each qualified-completion falling edge','checks':['If owner accepts LOAD, held RESET remains high throughout ownership','No stale ACK can authorize another low-to-high reset epoch','No START while waiting for actual ACK-low'],'result':None},
 {'name':'consecutive_reset_epochs','stimulus':'hold RESET, release, then reassert at each observed rearm phase; hold demands for full sampled intervals','checks':['No stale core ACK accepted for a new epoch','No accepted demand lost','Shorter-than-sample pulses are not claimed captured'],'result':None},
 {'name':'save_reload_retention','stimulus':'save and reload preserved test copies at quiescent boundaries','checks':['all256 RAM bytes retained','stored RF/control state has defined restore/BOOT behavior','ticks/chunk coverage reverified after reload'],'result':None}]
for f in cases['fault_cases']:
 control.append({'name':f['name'],'input_image':f['name'],'checks':['retained physical fault, no successful DONE','no fabricated warm ACK from faulted core','explicit destructive BOOT plus full input image reload/readback restores a valid kernel'],'result':None})
evidence={'run_id':'unique','case_name':'one named case','stage_hashes':{},'game_version':'observed','helper_version':'observed or absent','world_save_and_session':'observed TinyGPU Workshop or explicit preserved acceptance copy','tick_query_before_after':{},'verified_ticking_coverage':[],'player_before_after':{},'actual_rom_before':[],'actual_ram_before':[],'actual_thread_count':None,'recording_start_end_ticks':[],'recorded_signals':[],'first_failure':None,'actual_ram_after':[],'actual_faults':[],'actual_core_assignments':[],'restoration':{},'observed_result':None}
result={'status':'offline_future_native_acceptance_plan','prerequisites':required,'sequence':sequence,'normal_cases':normal,'control_and_fault_campaigns':control,'evidence_schema':evidence,'final_unmodified_minecraft_gate':{'required':True,'world':'backed-up preserved copy of the selected complete machine','helper':'absent; no helper/mod/datapack may supply arithmetic, RAM, state transitions or runtime decisions','required_runs':['original_matadd','original_matmul','matadd_changed_overflow','matmul_changed_overflow','thread_identity_9'],'evidence':['same vanilla block/state geometry before launch','manually or natively loaded pre-run images','observed in-game completion and all required output bytes','no external runtime arithmetic/memory/control source'],'completed':False},'physical_runs':0,'native_acceptance':False,'source_sha256':{str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest()for p in [H/'cases.json',H/'image-source-map.json',Path(__file__).resolve()]},'limits':['Every result field is deliberately empty. This is a specification, not executed evidence.','Nominal offline delays do not set physical wall-clock deadlines. Establish event/pulse margins with selected circuits before whole-machine tests.','Read-only oracle comparisons may inspect the trace; they cannot drive the running GPU.','Passing an output test alone cannot establish absence of transient extra writes or pulses; record complete relevant tick traces.']}
(H/'native-plan.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'normal_cases':len(normal),'control_and_fault_campaigns':len(control),'physical_runs':0}))
