import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeConsumerDrain}from'../../../../hardware/memory-layout-consumer-drain.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),d=makeConsumerDrain(),saved=read('design.json'),parent=read('../channel-matching-request-v1/design.json');assert.equal(hash(d),hash(saved));const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block]));
function check(mm){for(const p of parent.blocks)assert.deepEqual(mm.get(K(p.position)),p.block);for(const b of d.masks){const X=128*b.channel,Y=80*b.channel,y=Y+1+4*b.consumer;assert.deepEqual(b.busy_source,P(X+48,Y+1,16));assert.deepEqual(b.not_owner_source,P(X+106,y,154));assert.equal(d.nets[K(b.not_owner_source)],'lookup'+b.channel+'/not_owner'+b.consumer);assert.deepEqual(mm.get(K(b.gate)),{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});assert.deepEqual(mm.get(K(b.rear)),{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(mm.get(K(b.side)),{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});assert.deepEqual(P(b.side.x,b.side.y,b.side.z+1),b.gate);}
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],b=mm.get(K(p));assert(b,'cut '+r.name);if(b.id==='minecraft:repeater'){const v=D[b.properties.facing];if(i)assert.deepEqual(r.path[i-1],P(p.x-v.x,p.y,p.z-v.z));if(i+1<r.path.length)assert.deepEqual(r.path[i+1],P(p.x+v.x,p.y,p.z+v.z));}else assert.equal(b.id,'minecraft:redstone_wire');}
 for(let i=0;i<8;i++){const p=d.ports.consumer_drained.positions[i],x=600+4*i,y=243+4*i;assert.deepEqual(p,P(x,y,181));assert.deepEqual(mm.get(K(P(x,y,179))),{id:'minecraft:redstone_wall_torch',properties:{facing:'south'}});assert.deepEqual(mm.get(K(P(x,y,180))),{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});assert.equal(mm.get(K(P(x,y,178)))?.id,'minecraft:light_gray_concrete');}
}
check(m);assert.equal(d.masks.length,32);let n=0;for(const b of d.masks){const mm=new Map(m);mm.set(K(b.side),{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});assert.throws(()=>check(mm));n++;}for(const p of [...d.ports.consumer_drained.positions.map(p=>P(p.x,p.y,179)),d.routes[0].path[5]]){const mm=new Map(m);mm.delete(K(p));assert.throws(()=>check(mm));n++;}
let cases=0;for(let packed=0;packed<9**4;packed++){let q=packed;const owner=Array.from({length:4},()=>{const v=q%9-1;q=Math.floor(q/9);return v;});for(let busy=0;busy<16;busy++)for(let consumer=0;consumer<8;consumer++){let combined=0;for(let c=0;c<4;c++){const rear=15*(busy>>c&1),side=15*Number(owner[c]!==consumer);combined|=Number(Math.max(0,rear-side)>0);}const drain=1-combined;assert.equal(drain,Number(!owner.some((o,c)=>o===consumer&&(busy>>c&1))));cases++;}}
const occupied=new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`));const out={status:'offline_actual_consumer_drain_geometry_pass',...d.metrics,exact_regeneration:true,occupied_chunk_columns:occupied.size,corruptions_rejected:n,settled_owner_busy_consumer_cases:cases,parent_maps_unchanged:true,remaining:d.missing,native_acceptance:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
