import assert from 'node:assert/strict';
import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeDispatchStateFeedback}from'../../../../hardware/full-gpu-dispatch-state-feedback.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeDispatchStateFeedback();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.instances.map(i=>i.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to)));assert.equal(m.size,d.blocks.length);let supports=0,directions=0,dustContacts=0,minRear=15;
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 const rep=(p,out)=>{assert.equal(at(p)?.block.id,'minecraft:repeater');assert.deepEqual(add(p,D[at(p).block.properties.facing]),out);directions++;};
 for(let y=-2;y<=17;y++)assert.equal(at(P(147,y,-3))?.block.id,'minecraft:'+(y%2===0?'light_gray_concrete':'redstone_torch'),'Initialize tower '+y);
 for(const r of d.routes){let power=15;for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut route');if(v.block.id==='minecraft:repeater'){rep(p,r.path[i+1]);minRear=Math.min(minRear,power);assert(power>0);power=15;}else{assert.equal(v.block.id,'minecraft:redstone_wire');if(i&&at(r.path[i-1]).block.id==='minecraft:redstone_wire')power--;assert(power>0);}}}
 for(const link of d.links){const y=link.clamp.y;rep(P(146,y,0),link.clamp);assert.deepEqual(at(link.clamp).block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});rep(P(147,y,-1),link.clamp);rep(P(149,y,0),link.next_input);assert.equal(at(P(148,y,0)).block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign wire contact '+pair(v.position,p));dustContacts++;}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&['minecraft:repeater','minecraft:comparator'].includes(v.block.id))){const dir=D[v.block.properties.facing];for(const side of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const p=add(v.position,side),o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;assert(v.block.id==='minecraft:comparator'&&allowed.has(pair(v.position,p))&&o.block.id==='minecraft:repeater','Foreign diode side '+K(v.position));}}
 let cases=0;for(let word=0;word<32;word++)for(const init of[0,1]){let actual=0;for(const link of d.links){let mask=init;for(let y=-1;y<=link.clamp.y;y+=2)mask=1-mask;assert.equal(mask,init);if(Math.max(0,((word>>link.bit)&1)*15-mask*15))actual|=1<<link.bit;}assert.equal(actual,init?0:word);cases++;}
 return{support_checks:supports,new_route_and_clamp_directions:directions,listed_external_wire_contacts:dustContacts,minimum_route_repeater_input:minRear,settled_initialize_clamp_cases:cases};}
const checks=check(d);const cut=structuredClone(d);cut.blocks=cut.blocks.filter(v=>K(v.position)!=='147,17,-3');assert.throws(()=>check(cut));const reverse=structuredClone(d);reverse.blocks.find(v=>K(v.position)==='149,9,0').block.properties.facing='east';assert.throws(()=>check(reverse));
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const result={status:'offline_conditional_next_to_retained_state_connection_checks_pass',...d.metrics,...checks,corruption_refusals:2,sources:{generator:sha('../../../../hardware/full-gpu-dispatch-state-feedback.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,limits:['Parent-internal topology inherits prior focused checks. All new neighbor faces are screened but weak/strong support-power simulation is absent.','Only candidate state transmission/zero clamp and retained banks are geometrically connected. State decode return, guard inputs and physical phase/init sources are still missing.','No measured clock margin or complete autonomous FSM claim.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
