// Full possible-input differential: reviewed lane+IR slice, extracted actual
// controllers, and only the declared new field/control cables.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{P,K,V,F}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),base=read('../four-lane-ir-fanout-v1/design.json'),ex=read('bodies.json'),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>K(a)+'>'+K(b),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',S='minecraft:light_gray_concrete';
const before=new Map(base.blocks.map(b=>[K(b.position),b.block])),after=new Map(d.blocks.map(b=>[K(b.position),b.block]));assert.equal(after.size,d.blocks.length);
for(const b of base.blocks)assert.deepEqual(after.get(K(b.position)),b.block);for(const g of ex.groups)for(const b of g.blocks)assert.deepEqual(after.get(K(A(b.position,g.translation))),b.block);
const expected=new Set(),preserved=[];for(const b of base.blocks)if(active(b.block))for(const q of inputs(before,b.position)){expected.add(pair(q,b.position));preserved.push({from:q,to:b.position});}for(const e of d.controller_internal){expected.add(pair(e.from,e.to));preserved.push(e);}for(const e of d.edges){expected.add(pair(e.from,e.to));if(after.get(K(e.from))?.id===W&&after.get(K(e.to))?.id===W)expected.add(pair(e.to,e.from));}
let supports=0,receivers=0;const actual=new Set(),unexpected=[];for(const b of d.blocks){if([W,R,C,T].includes(b.block.id)){assert(after.get(K(P(b.position.x,b.position.y-1,b.position.z)))?.id.endsWith('_concrete'),'Missing support '+K(b.position));supports++;}if(!active(b.block))continue;receivers++;for(const q of inputs(after,b.position)){const k=pair(q,b.position);actual.add(k);if(!expected.has(k))unexpected.push({from:q,to:b.position,source:after.get(K(q)),target:b.block});}}
const missing=d.edges.filter(e=>!actual.has(pair(e.from,e.to))),lost=preserved.filter(e=>!actual.has(pair(e.from,e.to)));let stores=0;const dr={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};for(const b of d.blocks){if(b.block.id!==R)continue;const v=dr[b.block.properties.facing];if(Object.values(dr).some(s=>{if(v.x*s.x+v.z*s.z)return false;const p=A(b.position,s),q=after.get(K(p));return[R,C].includes(q?.id)&&K(A(p,dr[q.properties.facing]))===K(b.position);} ))stores++;}assert.equal(stores,986);
const ir=d.ports.shared_ir,rf=d.ports.rf_control,alu=d.ports.alu_control,routeReports=[];for(const r of d.connections){let source,dest;if(r.name.startsWith('IR_reg_write')){source=ir.controls.bits.find(b=>b.name==='reg_write').position;dest=rf.reg_write.bits[0].position;}else if(/IR_(rs|rt|rd)/.test(r.name)){const[,field,bit]=r.name.match(/IR_(rs|rt|rd)(\d)/);source=ir[field].bits[Number(bit)].position;dest=rf[field].bits[Number(bit)].position;assert.equal(ir[field].bits[Number(bit)].instruction_bit,Number(bit)+(field==='rd'?8:field==='rs'?4:0));}else{const field=r.name.slice(3,-7);source=ir.controls.bits.find(b=>b.name===field).position;dest=alu[field==='compare'?'compare':field.endsWith('_0')?'mode0':'mode1'].bits[0].position;}assert.deepEqual(r.source,source);assert.deepEqual(r.destination,dest);assert.deepEqual(inputs(after,r.tap),[r.source]);assert.deepEqual(inputs(after,r.arrival),[r.end]);
 const path=[r.source,r.tap,...r.path,r.arrival,r.destination];let power=15,minimum=15,ticks=0,maxDust=0,dust=0;for(let i=1;i<path.length;i++){const p=path[i],b=after.get(K(p)),prev=after.get(K(path[i-1]));assert(inputs(after,p).some(q=>K(q)===K(path[i-1])),r.name+' actual edge '+K(p));if(b.id===R){minimum=Math.min(minimum,power);assert(power>0);power=15;dust=0;ticks+=2*Number(b.properties.delay);}else{assert.equal(b.id,W);power-=prev.id===W?1:0;maxDust=Math.max(maxDust,++dust);assert(power>0);}}assert.equal(power,15);routeReports.push({name:r.name,nominal_ticks:ticks,minimum_repeater_rear_high:minimum,max_dust_run:maxDust,source:r.source,destination:r.destination});}
let negatives=0;const r=d.connections[0],old=after.get(K(r.arrival));after.set(K(r.arrival),{...old,properties:{...old.properties,facing:old.properties.facing==='west'?'east':'west'}});assert(!inputs(after,r.destination).some(q=>K(q)===K(r.arrival)));after.set(K(r.arrival),old);negatives++;assert.throws(()=>assert.deepEqual(d.connections[0].source,ir.rs.bits[1].position));negatives++;
const report={status:unexpected.length||lost.length||missing.length?'refused':'partial_shared_controller_geometry_passed',cells:d.blocks.length,parent_data_cells:base.blocks.length,controller_cells:d.controller_cells,new_cable_cells:d.added_cells,stores,remaining_shared_stores:131,preserved_dependencies:preserved.length,actual_dependencies:actual.size,supports,receivers,unexpected,lost,missing,routes:routeReports,negative_checks:negatives,source_sha256:Object.fromEntries(['prepare.mjs','check.mjs','extract.mjs','design.json','paths.json','bodies.json','../four-lane-ir-fanout-v1/design.json'].map(n=>[n,createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex')])),complete_core:false,native_acceptance:false};writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,unexpected:unexpected.slice(0,20),lost:lost.slice(0,20),missing:missing.slice(0,20)},null,2));assert.equal(report.status,'partial_shared_controller_geometry_passed');
