// Actual retained controllers and bidirectional electrical cut from cb4b.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),B=new URL('../../',H),ROOT=new URL('../../../../',H),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),sub=(a,b)=>P(a.x-b.x,a.y-b.y,a.z-b.z),pins={};
function read(n){const p=new URL(n,B);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');return readLargeDesign(fileURLToPath(p));}
const core=read('compact-core-guard-v1/design.json');assert.equal(pins['artifacts/full-gpu-layout-v1/compact-core-guard-v1/design.json'],'2da4daf7365f65628fdbbda5573a00f0a5464fbb163f20c9a6e10e7d92f7c4e1');const world=new Map(core.blocks.map(v=>[K(v.position),v.block]));
const specs=[{name:'alu_control',path:'alu-control/initialized-feedback-v1/design.json',origin:P(1400,-34,0),translation:P(650,-34,0),expected_stores:26},{name:'rf_control',path:'register-sequencer-v1/controller-addresses/design.json',origin:P(900,53,0),translation:P(150,53,-330),expected_stores:20}],groups=[],claims=new Map,changes=[],absent=[],all=[];
for(const s of specs){const seed=read(s.path),blocks=[];for(const b of seed.blocks){const old=A(b.position,s.origin),k=K(old),actual=world.get(k);if(!actual){absent.push({body:s.name,position:old,old:b.block});continue;}assert(!claims.has(k));claims.set(k,s.name);if(JSON.stringify(actual)!==JSON.stringify(b.block))changes.push({body:s.name,position:old,old:b.block,actual});blocks.push({position:b.position,block:actual,original_position:old,body:s.name,seed_part:b.part});}groups.push({...s,ports:seed.ports,blocks});all.push(...blocks);console.log(s.name,blocks.length);}
const internal=[],crossings=[],byGroup={};let receivers=0;for(const r of core.blocks){if(!active(r.block))continue;const targetGroup=claims.get(K(r.position));for(const q of inputs(world,r.position)){const sourceGroup=claims.get(K(q));if(!targetGroup&&!sourceGroup)continue;receivers++;const e={from:q,to:r.position,source_group:sourceGroup??'outside',target_group:targetGroup??'outside',source_id:world.get(K(q)).id,target_id:r.block.id};if(sourceGroup&&sourceGroup===targetGroup)internal.push(e);else{crossings.push(e);const k=e.source_group+' -> '+e.target_group;byGroup[k]=(byGroup[k]??0)+1;}}}
const T={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},stores=[];for(const r of core.blocks){if(r.block.id!=='minecraft:repeater')continue;const dr=T[r.block.properties.facing],locks=[];for(const v of Object.values(T)){if(v.x*dr.x+v.z*dr.z)continue;const p=A(r.position,v),b=world.get(K(p));if(['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&K(A(p,T[b.properties.facing]))===K(r.position))locks.push(p);}if(locks.length)stores.push({position:r.position,locks,group:claims.get(K(r.position))??'other'});}
assert.equal(stores.length,1117);for(const s of specs){const own=stores.filter(v=>v.group===s.name);assert.equal(own.length,s.expected_stores);const group=groups.find(g=>g.name===s.name);group.stores=own;group.internal=internal.filter(v=>v.source_group===s.name).map(v=>({from:sub(v.from,s.origin),to:sub(v.to,s.origin)}));group.crossings=crossings.filter(v=>v.source_group===s.name||v.target_group===s.name);}
const out={status:'actual_controller_bodies_extracted_with_complete_bidirectional_cuts',groups,changes,absent,crossings,crossings_by_group:byGroup,remaining_shared_stores:177-46,source_sha256:pins,native_acceptance:false};writeFileSync(new URL('bodies.json',H),JSON.stringify(out)+'\n');writeFileSync(new URL('extraction.json',H),JSON.stringify({...out,groups:groups.map(({blocks,internal,...g})=>({...g,cells:blocks.length,internal_dependencies:internal.length})),crossings:crossings.length},null,2)+'\n');console.log(JSON.stringify({cells:all.length,changes:changes.length,absent:absent.length,internal:internal.length,crossings:crossings.length,byGroup,stores:46}));
