// Connected controller placement with the same shared retained instruction body.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{P,K,V,F,searchPath,refreshIndices}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),under=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),W='minecraft:redstone_wire',R='minecraft:repeater',S='minecraft:light_gray_concrete';
const base=read('../four-lane-ir-fanout-v1/design.json'),extracted=read('bodies.json'),groups=extracted.groups.map(g=>({...g,moved:materializeInstance(g,{id:g.name,translation:g.translation})})),parentRows=[...base.blocks,...groups.flatMap(g=>g.moved.blocks.map(b=>({...b,body:'shared/'+g.name})))],rows=[...parentRows],map=new Map(rows.map(b=>[K(b.position),b]));assert.equal(map.size,rows.length,'Parent collision');let part='';const edges=[],connections=[];
function put(p,id,properties){const block={id,...properties?{properties}:{}},old=map.get(K(p));if(old){assert.equal(id,S,'Collision '+part+' '+K(p));assert.deepEqual(old.block,block);return;}const b={position:p,block,part};map.set(K(p),b);rows.push(b);}
const dev=(p,id,pr)=>{put(under(p),S);put(p,id,pr)},wire=p=>dev(p,W),rep=(p,d)=>dev(p,R,{facing:F[d],delay:'1'}),edge=(from,to)=>edges.push({from,to,route:part});
const ir=base.ports.shared_ir,rf=groups.find(g=>g.name==='rf_control').moved.ports,alu=groups.find(g=>g.name==='alu_control').moved.ports,cn=n=>ir.controls.bits.find(p=>p.name===n),dir=p=>typeof p.travel==='string'?p.travel:Object.keys(V).find(d=>V[d][0]===p.travel.x&&V[d][1]===p.travel.z);
function add(name,s,d,sd=dir(s),ad=dir(d)){assert.equal(map.get(K(s.position))?.block.id,W);assert.equal(map.get(K(d.position))?.block.id,W);connections.push({name,source:s.position,destination:d.position,source_direction:sd,arrival_direction:ad,tap:step(s.position,sd),start:step(s.position,sd,2),arrival:step(d.position,ad,-1),end:step(d.position,ad,-2)});}
for(const field of['rs','rt','rd'])for(let bit=0;bit<4;bit++)add('IR_'+field+bit+'_to_RF',ir[field].bits[bit],rf[field].bits[bit],(field==='rt'||field==='rs'&&bit<2)?'north':dir(ir[field].bits[bit]));
for(const[name,field]of[['mode0','arithmetic_mux_0'],['mode1','arithmetic_mux_1'],['compare','compare']])add('IR_'+field+'_to_ALU',cn(field),alu[name].bits[0]);
add('IR_reg_write_to_RF',cn('reg_write'),rf.reg_write.bits[0]);
const reserve=c=>[...Array.from({length:12},(_,i)=>step(c.source,c.source_direction,i+2)),...Array.from({length:12},(_,i)=>step(c.destination,c.arrival_direction,-i-2))],reserved=connections.flatMap(reserve);
for(const c of connections){part=c.name;rep(c.tap,c.source_direction);wire(c.start);rep(c.arrival,c.arrival_direction);wire(c.end);edge(c.source,c.tap);edge(c.tap,c.start);edge(c.end,c.arrival);edge(c.arrival,c.destination);}
const url=new URL('paths.json',H),cache=existsSync(url)?read('paths.json'):{};
for(const c of connections){part=c.name;let path=cache[c.name]?.path;if(path){assert.deepEqual(cache[c.name].source,c.source);assert.deepEqual(cache[c.name].destination,c.destination);}else{const r=searchPath(map,c.start,c.end,{ignore:[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(under),...reserve(c)],reserved,limit:1600000});path=r.path;cache[c.name]={source:c.source,destination:c.destination,path,expanded:r.expanded};writeFileSync(url,JSON.stringify(cache)+'\n');console.log(JSON.stringify({name:c.name,points:path.length,expanded:r.expanded}));}
const refresh=new Set(refreshIndices(path));for(let i=1;i<path.length-1;i++){const p=path[i];if(refresh.has(i))rep(p,Object.keys(V).find(d=>K(step(p,d))===K(path[i+1])));else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);c.path=path;c.refresh_indices=[...refresh];}
const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const b of rows)for(const k of['x','y','z']){box.from[k]=Math.min(box.from[k],b.position[k]);box.to[k]=Math.max(box.to[k],b.position[k]);}
const d={status:'partial_connected_shared_controllers_unchecked',blocks:rows,box,parent_cells:parentRows.length,base_cells:base.blocks.length,controller_cells:parentRows.length-base.blocks.length,added_cells:rows.length-parentRows.length,ports:{...base.ports,rf_control:rf,alu_control:alu},groups:groups.map(({blocks,internal,moved,...g})=>({...g,cells:blocks.length})),controller_internal:groups.flatMap(g=>g.internal.map(e=>({from:A(e.from,g.translation),to:A(e.to,g.translation),body:g.name}))),connections,edges,metrics:{cells:rows.length,physical_stores:986,placed_shared_stores:62,remaining_shared_stores:131,new_instruction_connections:connections.length},missing:['131 other shared stores and associated logic and all their incoming/outgoing controls remain.','Both controller phase, initialization, admission, request/status and lane action fanouts remain mandatory and are listed by actual effective-input cuts.','No absent old data wire is counted as a routing saving. No full-core cost or timing acceptance.'],complete_core:false,native_acceptance:false};writeFileSync(new URL('design.json',H),JSON.stringify(d)+'\n');console.log(JSON.stringify({cells:rows.length,added:d.added_cells,box}));
