// Concrete public endpoints and route ledger in frame3; missing producers stay null.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {sourceBindings,iterateObstacles,translate} from './obstacles.mjs';
const H=new URL('.',import.meta.url),read=f=>JSON.parse(readFileSync(new URL(f,H))),f=read('frame-config.json'),c=read('composition-checks.json');
await sourceBindings();const local=read('local-ports.json'),memory=read('../memory/bank-sampled-admission-v1/ports.json');
assert.deepEqual(local.loader,memory.ports);local.loader={data:local.loader,...memory.preserved_interfaces};
const K=p=>`${p.x},${p.y},${p.z}`,meta=(v,t,key='')=>{if(Array.isArray(v))return v.map(x=>meta(x,t,key));if(!v||typeof v!=='object')return v;if(['x','y','z'].every(a=>Number.isSafeInteger(v[a]))&&key!=='travel')return translate(v,t);return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,meta(x,t,k)]));};
const masterPorts=Object.fromEntries(Object.entries(local).map(([n,p])=>[n,meta(p,f.instances[n].translation)]));
const previous=read('../floorplan-v2/placement.json'),nets=structuredClone(previous.candidates[0].external);
const allConnections=Object.values(f.route_deltas).flatMap(v=>JSON.parse(readFileSync(v.path)).connections);
for(let i=0;i<2;i++){const n=nets.find(v=>v.name==='dispatch_done_'+i),p=masterPorts['core'+i].core_done;n.driver={instance:'core'+i,port:'core_done',positions:p.bits.map(b=>b.position),declared_bits:p.bits,coordinate_frame:'master',direction:'output'};n.geometry_status='both_endpoints_drawn_route_missing';}
for(const n of nets){const known=n.driver.positions&&n.sink.positions;const matches=known?n.driver.positions.map((p,b)=>allConnections.find(c=>c.source_instance===n.driver.instance&&c.destination_instance===n.sink.instance&&K(c.source)===K(p)&&K(c.destination)===K(n.sink.positions[b]))):[];n.routed_bits=matches.filter(Boolean).length;n.routed_connections=matches.filter(Boolean).map(c=>c.name);n.geometry_status=!known?'physical_endpoint_missing':n.routed_bits===n.width?'all_bits_actually_routed':'both_endpoints_drawn_route_missing';delete n.manhattan_endpoint_distance;}
const named=new Set(nets.flatMap(n=>n.routed_connections));for(const r of allConnections)if(!named.has(r.name))nets.push({name:r.name,driver:{instance:r.source_instance,port:r.source_port,positions:[r.source]},sink:{instance:r.destination_instance,port:r.destination_port,positions:[r.destination]},width:1,routed_bits:1,routed_connections:[r.name],geometry_status:'all_bits_actually_routed'});
// Bind every advertised endpoint (including newly held DONE) to an actual occupied cell.
const wanted=new Map();for(const n of nets)for(const side of['driver','sink'])for(const p of n[side].positions??[]){const k=n[side].instance+'|'+K(p);wanted.set(k,{instance:n[side].instance,position:p});}
let found=0;for await(const row of iterateObstacles({verify:false})){const k=row.instance+'|'+K(row.position);if(wanted.has(k)){wanted.get(k).block=row.block;found++;}}
assert.equal(found,wanted.size);assert.equal(nets.reduce((s,n)=>s+n.routed_bits,0),f.external_routes_drawn);
const sources=await sourceBindings({verify:false}),ports={status:'actual_frame3_port_bindings_partial_routes',coordinate_frame:'master',instances:masterPorts,local_ports:local,final_core_reset_ack:null,missing_consumers:'Data-memory consumer read_ready/write_ready/read_data producers still pending',source_sha256:sources,native_acceptance:false};
const ledger={status:'actual_frame3_partial_routed_connection_ledger',total_blocks:c.total_blocks,routed_bit_connections:f.external_routes_drawn,known_unrouted_bits:nets.reduce((s,n)=>s+(n.driver.positions&&n.sink.positions?n.width-n.routed_bits:0),0),bits_missing_endpoint:nets.filter(n=>!n.driver.positions||!n.sink.positions).reduce((s,n)=>s+n.width,0),advertised_unique_endpoints_checked:found,nets,missing:['Final held core resetACK source remains null; RF resetACK and scratch/LSU status are not architectural completion.','Consumer data-memory ready/read-data outputs remain pending.','Remaining global completion joins, dispatcher/core payloads and program response/drain wires are not drawn here.','Complete physical timing/density/initialization and final whole-machine acceptance remain unproved.'],native_acceptance:false,complete_gpu_layout:false};
writeFileSync(new URL('ports.json',H),JSON.stringify(ports,null,2)+'\n');writeFileSync(new URL('connections.json',H),JSON.stringify(ledger,null,2)+'\n');console.log(JSON.stringify({...ledger,nets:undefined}));
