// Preserve all old slice dependencies and the actual extracted IR internals;
// admit only ten explicit new source-to-input cables.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{P,K}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),parent=read('../lane0-lower-alu-v1/lane0-draft.json'),ir=read('../shared-ir-body.json'),placed=materializeInstance(ir,{id:'shared_ir',...d.ir_transform}),before=new Map(parent.blocks.map(v=>[K(v.position),v.block])),after=new Map(d.blocks.map(v=>[K(v.position),v.block]));
const W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',S='minecraft:light_gray_concrete',solid=b=>b?.id.endsWith('_concrete'),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>K(a)+'>'+K(b);
assert.equal(after.size,d.blocks.length);for(const v of[...parent.blocks,...placed.blocks])assert.deepEqual(after.get(K(v.position)),v.block);
const expected=new Set(),preserved=[];for(const v of parent.blocks)if(active(v.block))for(const q of inputs(before,v.position)){expected.add(pair(q,v.position));preserved.push({from:q,to:v.position});}for(const e of d.shared_ir_original_internal_edges){expected.add(pair(e.from,e.to));preserved.push(e);}
for(const e of d.edges){expected.add(pair(e.from,e.to));if(after.get(K(e.from))?.id===W&&after.get(K(e.to))?.id===W)expected.add(pair(e.to,e.from));}
const actual=new Set(),unexpected=[];let supports=0,receivers=0;for(const v of d.blocks){if([W,R,C,T].includes(v.block.id)){assert(solid(after.get(K(P(v.position.x,v.position.y-1,v.position.z)))));supports++;}if(!active(v.block))continue;receivers++;for(const q of inputs(after,v.position)){const e=pair(q,v.position);actual.add(e);if(!expected.has(e))unexpected.push({from:q,to:v.position,from_block:after.get(K(q)),to_block:v.block});}}
const lost=preserved.filter(e=>!actual.has(pair(e.from,e.to))),missing=d.edges.filter(e=>!actual.has(pair(e.from,e.to)));const D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};let stores=0;for(const v of d.blocks){if(v.block.id!==R)continue;const dr=D[v.block.properties.facing];if(Object.values(D).some(s=>{if(s.x*dr.x+s.z*dr.z)return false;const q=add(v.position,s),qb=after.get(K(q));return[R,C].includes(qb?.id)&&K(add(q,D[qb.properties.facing]))===K(v.position);} ))stores++;}assert.equal(stores,247);
const wb=read('../../writeback/design.json'),routes=[];for(const r of d.connections){const isImm=r.name.startsWith('immediate'),src=isImm?placed.ports.immediate.bits[r.bit]:placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_'+r.bit),dst=add(wb.ports[isImm?'immediate':'select'].bits[r.bit].position,P(0,-10,-30));assert.deepEqual(r.source,src.position);assert.deepEqual(r.destination,dst);if(isImm)assert.equal(src.instruction_bit,r.bit);const qs=inputs(after,r.source);assert.equal(qs.length,1);assert.equal(after.get(K(qs[0])).id,R);assert.deepEqual(inputs(after,r.tap),[r.source]);assert.deepEqual(inputs(after,r.arrival),[r.end]);let run=0,max=0,delay=0;for(const p of[r.tap,...r.path,r.arrival]){const b=after.get(K(p));if(b.id===R){run=0;delay+=2*Number(b.properties.delay);}else{assert.equal(b.id,W);max=Math.max(max,++run);}}assert(max<=12);routes.push({name:r.name,source:r.source,destination:r.destination,cable_nominal_ticks:delay,max_dust_run:max,minimum_rear_high_power:16-max});}
let negatives=0;const r=d.connections[0],old=after.get(K(r.arrival));after.set(K(r.arrival),{...old,properties:{...old.properties,facing:'south'}});assert(!inputs(after,r.destination).some(q=>K(q)===K(r.arrival)));after.set(K(r.arrival),old);negatives++;const swapped=structuredClone(d.connections.find(r=>r.name==='select0'));swapped.source=placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_1').position;assert.throws(()=>assert.deepEqual(swapped.source,placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_'+swapped.bit).position));negatives++;
const status=unexpected.length||lost.length||missing.length?'refused':'actual_58_data_path_slice_dependency_screen_passed',report={status,cells:d.blocks.length,parent_lane_cells:parent.blocks.length,shared_ir_cells:placed.blocks.length,added_cable_cells:d.added_cells,stores,supports,receivers,preserved_dependencies:preserved.length,actual_dependencies:actual.size,unexpected,lost,missing,routes,negative_checks:negatives,source_sha256:Object.fromEntries(['prepare.mjs','check.mjs','design.json','paths.json','../lane0-lower-alu-v1/lane0-draft.json','../shared-ir-body.json'].map(n=>[n,createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex')])),scope:['All 34 missing bit connections for lane0 are now real paths from the retained RF/ALU/IR sources into actual receiving pads.','This does not connect the remaining three lanes or the shared phase/reset/control/status cuts. The same 16 IR stores are relocated, not added to the architectural state.','The body preservation and possible-input graph are static evidence, not pulse/timing/native acceptance.'],complete_core:false,native_acceptance:false};writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,unexpected:unexpected.slice(0,15),lost:lost.slice(0,15),missing:missing.slice(0,15)},null,2));assert.equal(status,'actual_58_data_path_slice_dependency_screen_passed');
