// The same shared16-bit held IR, moved once, supplies real immediate/select data.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{materializeInstance,rotatePosition}from'../../../../hardware/gpu-layout-assembly.mjs';import{P,K,V,F,searchPath,refreshIndices}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),W='minecraft:redstone_wire',R='minecraft:repeater',S='minecraft:light_gray_concrete',A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),under=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n);
const lane=read('../lane0-lower-alu-v1/lane0-draft.json'),ir=read('../shared-ir-body.json'),transform={quarter_turns:2,translation:P(-40,0,-40)},placed=materializeInstance(ir,{id:'shared_ir',...transform}),irAt=p=>A(rotatePosition(p,2),transform.translation);
const parentRows=[...lane.blocks,...placed.blocks.map(b=>({...b,body:'shared/held_ir'}))],map=new Map(parentRows.map(v=>[K(v.position),v])),rows=[...parentRows];assert.equal(map.size,rows.length,'Body overlap');let part='';const edges=[],connections=[];
function put(p,id,properties){const block={id,...properties?{properties}:{}},old=map.get(K(p));if(old){assert.equal(id,S,'Collision '+part+' '+K(p));assert.deepEqual(old.block,block,'Support collision '+part+' '+K(p));return;}const b={position:p,block,part};map.set(K(p),b);rows.push(b);}
const dev=(p,id,pr)=>{put(under(p),S);put(p,id,pr)},wire=p=>dev(p,W),rep=(p,d)=>dev(p,R,{facing:F[d],delay:'1'}),edge=(a,b)=>edges.push({from:a,to:b,route:part});
const wb=read('../../writeback/design.json'),wp=(name,bit)=>A(wb.ports[name].bits[bit].position,P(0,-10,-30));
function pending(name,source,sd,destination,ad,source_port,bit){assert.equal(map.get(K(source))?.block.id,W);assert.equal(map.get(K(destination))?.block.id,W);connections.push({name,source,source_direction:sd,destination,arrival_direction:ad,source_port,bit,was_missing_in_reference:true,tap:step(source,sd),start:step(source,sd,2),arrival:step(destination,ad,-1),end:step(destination,ad,-2)});}
for(let b=0;b<8;b++){const p=placed.ports.immediate.bits[b];pending('immediate'+b,p.position,p.travel,wp('immediate',b),'south','held_IR.immediate',b);}
for(let b=0;b<2;b++){const p=placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_'+b);pending('select'+b,p.position,p.travel,wp('select',b),b?'west':'east','held_IR.controls.reg_input_mux_'+b,b);}
const reserve=c=>[...Array.from({length:12},(_,i)=>step(c.source,c.source_direction,i+2)),...Array.from({length:12},(_,i)=>step(c.destination,c.arrival_direction,-i-2))],reserved=connections.flatMap(reserve);
for(const c of connections){part=c.name;rep(c.tap,c.source_direction);wire(c.start);rep(c.arrival,c.arrival_direction);wire(c.end);edge(c.source,c.tap);edge(c.tap,c.start);edge(c.end,c.arrival);edge(c.arrival,c.destination);}
const cacheURL=new URL('paths.json',H),cache=existsSync(cacheURL)?read('paths.json'):{};
for(const c of connections){part=c.name;let path=cache[c.name]?.path;if(!path){const ignore=[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(under),...reserve(c)];const r=searchPath(map,c.start,c.end,{ignore,reserved,limit:1200000});path=r.path;cache[c.name]={source:c.source,destination:c.destination,path,expanded:r.expanded};writeFileSync(cacheURL,JSON.stringify(cache)+'\n');console.log(JSON.stringify({name:c.name,cells:path.length,expanded:r.expanded}));}else{assert.deepEqual(cache[c.name].source,c.source);assert.deepEqual(cache[c.name].destination,c.destination);}
 const refresh=new Set(refreshIndices(path));for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.has(i)){const dir=Object.keys(V).find(n=>K(step(p,n))===K(q));assert(dir);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);c.path=path;c.refresh_indices=[...refresh];}
const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const r of rows)for(const a of['x','y','z']){box.from[a]=Math.min(box.from[a],r.position[a]);box.to[a]=Math.max(box.to[a],r.position[a]);}
const out={status:'actual_lane58_data_paths_unchecked',blocks:rows,connections,edges,ports:{shared_ir:placed.ports},ir_transform:transform,parent_cells:parentRows.length,ir_cells:placed.blocks.length,added_cells:rows.length-parentRows.length,box,metrics:{cells:rows.length,lane_stores:231,shared_IR_stores:16,total_stores:247,complete_data_paths:58,original_missing_bit_paths_completed_for_lane0:34},shared_ir_original_internal_edges:ir.internal.map(e=>({from:irAt(e.from),to:irAt(e.to)})),remaining:['IR fetch/open/decode/reset and all other shared control interfaces remain cut boundaries.','Three further lanes and177 other shared stores remain required; no complete-core claim.','Phase/init/status/control routing and far closure timing remain unproved.'],native_acceptance:false};writeFileSync(new URL('design.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({cells:rows.length,added:out.added_cells,box}));
