// Current physical input boundary of the islands considered by this pilot.
// A historical terminal list is never used instead of this physical cut.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{P,K}from'../../control-commit-v2/route.mjs';import{inputs,active}from'./cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),meta=JSON.parse(readFileSync(new URL('cell-labels.json',H))),labels=readFileSync(new URL('cell-labels.u16le',H)),buf=readFileSync(new URL(meta.parent,ROOT));
assert.equal(createHash('sha256').update(buf).digest('hex'),meta.parent_sha256);const parent=readLargeDesign(fileURLToPath(new URL(meta.parent,ROOT)));assert.equal(labels.length,parent.blocks.length*2);
const groups=new Set(['channel-allocator-v1/channel-allocator-v1',...['retained_owner','owner_hold','held_owner_mask','payload_mux','payload_collectors','payload_storage','payload_exports','payload_hold'].map(s=>'channel-retention-v1/'+s),...Array.from({length:4},(_,i)=>'channel-withdrawal-v1/lookup'+i),...Array.from({length:4},(_,i)=>'channel-backend-v1/backend'+i)]);
const world=new Map(),index=new Map(),selected=new Set(),counts={};
for(let i=0;i<parent.blocks.length;i++){const v=parent.blocks[i],k=K(v.position),g=meta.labels[labels.readUInt16LE(i*2)];world.set(k,v.block);index.set(k,i);if(groups.has(g)){selected.add(k);counts[g]=(counts[g]??0)+1;}}
assert.equal(Object.keys(counts).length,17);console.log(JSON.stringify({stage:'parent_loaded',cells:world.size,selected:selected.size,counts}));
const affected=new Set();for(const k of selected){const p=parent.blocks[index.get(k)].position;for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++){const q=P(p.x+dx,p.y+dy,p.z+dz),kq=K(q);if(active(world.get(kq)))affected.add(kq);}}
const describe=k=>{const i=index.get(k),v=parent.blocks[i];return{position:v.position,block:v.block,group:meta.labels[labels.readUInt16LE(i*2)],net:parent.nets?.[k]??null};};
const cuts=[];for(const k of affected){const p=parent.blocks[index.get(k)].position;for(const q of inputs(world,p)){const s=K(q);if(selected.has(k)===selected.has(s))continue;cuts.push({direction:selected.has(k)?'incoming':'outgoing',source:describe(s),target:describe(k)});}}
const byPair={};for(const c of cuts){const k=c.direction+':'+c.source.group+' -> '+c.target.group;byPair[k]=(byPair[k]??0)+1;}
const hash=n=>createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex');
const out={status:'current_cold_parent_actual_island_cut_inventory',parent:meta.parent,parent_sha256:meta.parent_sha256,source_sha256:{'cell-labels.json':hash('cell-labels.json'),'cell-labels.u16le':hash('cell-labels.u16le'),'extract-cuts.mjs':hash('extract-cuts.mjs'),'cut-inputs.mjs':hash('cut-inputs.mjs')},selected_cells:selected.size,groups:counts,affected_receivers:affected.size,actual_crossings:cuts.length,byPair,cuts,native_acceptance:false,selected:false,limits:['These are all immediate effective-input crossings in the chosen17 old body/allocator groups.','The old return transports carry known defects; this does not accept their behavior.','A complete replacement must account for every crossing, every changed transport and all retained state.','The presently drawn40/96 local joins are not a replacement for this full boundary.']};
writeFileSync(new URL('actual-cuts.json',H),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,selected_cells:selected.size,affected_receivers:affected.size,actual_crossings:cuts.length,byPair}));
