// Exact two-orientation correction of the one shared startup scanner per core.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
const R='artifacts/full-gpu-layout-v1/',parentPath=R+'control-reset-master-compatible-v2/design.json',scannerPath=R+'startup-scan-v1/clock/design.json',read=p=>JSON.parse(readFileSync(p)),sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),d=read(parentPath),scanner=read(scannerPath),K=p=>`${p.x},${p.y},${p.z}`,T=p=>({x:p.x+300,y:p.y+233,z:p.z-248}),map=new Map(d.blocks.map(v=>[K(v.position),v]));
for(const v of scanner.blocks)assert.deepEqual(map.get(K(T(v.position)))?.block,v.block,'Inherited scanner '+K(T(v.position)));
const fixes=[{local:{x:-11,y:-2,z:3},before:'east',after:'west',phase:'A'},{local:{x:4,y:-2,z:0},before:'south',after:'north',phase:'B'}],changes=[];
for(const f of fixes){const position=T(f.local),v=map.get(K(position)),before=structuredClone(v.block);assert.deepEqual(before,{id:'minecraft:repeater',properties:{facing:f.before,delay:'1'}});v.block.properties.facing=f.after;changes.push({position,from:before,to:structuredClone(v.block),phase:f.phase,reason:'The former orientation blocked the oscillator injection from the actual six-bit scan bank OPEN branch.'});}
d.status='offline_master_compatible_core_with_shared_scanner_entry_repair';d.scanner_entry_repairs=changes;d.scanner_repair_parent={path:parentPath,sha256:sha(parentPath)};d.native_acceptance=false;d.complete_gpu_layout=false;
const inventory={status:'exact_two_orientation_scanner_repair',parent:d.scanner_repair_parent,scanner:{path:scannerPath,sha256:sha(scannerPath),origin:{x:300,y:233,z:-248},inherited_cells_verified:scanner.blocks.length,physical_copies_per_core:1},changes,unchanged_cells:d.blocks.length-2,added_cells:0,added_stores:0,bounds_unchanged:true,all_external_ports_unchanged:true,phase_reachability_check:"check-scanner.py",complete_timing_acceptance:false,native_acceptance:false};
for(const[name,value]of Object.entries({'design.json':d,'replacement-inventory.json':inventory})){const p=R+'control-reset-master-compatible-v3/'+name,text=JSON.stringify(value)+'\n';if(process.argv.includes('--check'))assert.equal(readFileSync(p,'utf8'),text);else writeFileSync(p,text);}console.log(JSON.stringify({cells:d.blocks.length,scanner_cells:scanner.blocks.length,changed:changes}));
