import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeAluLoopCounter}from'../../../../hardware/full-gpu-alu-loop-counter.mjs';
import{makeAluPhaseLoop}from'../../../../hardware/full-gpu-alu-phase-loop.mjs';
import{makePcIncrementer}from'../../../../hardware/full-gpu-pc-incrementer.mjs';import{makeStateBank}from'../../../../hardware/full-gpu-state-bank.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0,minRear=15;
 const half=makePcIncrementer().blocks.filter(v=>['half_0','pc_input_0','pc_plus_one_0'].includes(v.part));for(let bit=0;bit<d.metrics.width;bit++){const parent=materializeInstance(makeStateBank({width:1}),{id:'bank',translation:P(0,8*bit,0)});for(const v of parent.blocks.concat(half.map(v=>({position:P(v.position.x+32,v.position.y+8*bit,v.position.z),block:v.block})))){assert.deepEqual(at(v.position)?.block,v.block,'Parent changed '+K(v.position));inherited++;}}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){for(let y=c.bottom;y<c.top;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.top,c.z))?.block.id,'minecraft:'+(c.wire_top?'redstone_wire':'redstone_torch'));if(c.wire_top)assert.equal((c.top-c.bottom)%4,1);}
 for(const r of d.routes){let power=15;for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);minRear=Math.min(minRear,power);assert(power>0);power=15;}else{assert.equal(v.block.id,'minecraft:redstone_wire');if(i&&at(r.path[i-1]).block.id==='minecraft:redstone_wire')power--;assert(power>0,'Attenuated '+r.name);}}}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 for(const b of d.bits)for(const p of[b.hold_comparator,b.increment_comparator,b.clear_comparator])assert.deepEqual(at(p)?.block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});
 return{preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,minimum_route_repeater_input:minRear};}

const reports=[];
for(const width of[2,3]){const d=makeAluLoopCounter({width});reports.push({width,blocks:d.blocks.length,...check(d)});for(const field of['hold_comparator','increment_comparator','clear_comparator']){const c=structuredClone(d),p=c.bits[0][field];c.blocks.find(v=>K(v.position)===K(p)).block.properties.mode='compare';assert.throws(()=>check(c));}}
const d=makeAluPhaseLoop();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
console.log(JSON.stringify({status:'inherited_counter_geometry_and_connected_phase_regeneration_passed',reports,comparator_corruptions_rejected:6,connected_blocks:d.blocks.length,native_calls:0}));
