import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{P,K,makeLogic}from'./logic.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),parent=new URL('../reset-ack-connected-v1/source-manifest.json',H);assert.equal(createHash('sha256').update(readFileSync(parent)).digest('hex'),'562207ab002c11d299500257a9ff6709654aad8a0b3f0df8b3fee2fd97a6ab7a');const base=read('../reset-ack-connected-v1/design.json'),ep=read('../reset-ack-connected-v1/endpoint-map.json'),orig=read('original-cones.json'),functions=read('original-functions.json'),mapping=ep.mapping,world=new Map(base.blocks.map(b=>[K(b.position),b.block])),E=(a,b)=>K(a)+'>'+K(b),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z);
function clearGate(g){if(g.blocks.some(b=>world.has(K(b.position))))return false;const neighbors=new Map;for(const b of g.blocks)for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++){if(Math.abs(x)+Math.abs(y)+Math.abs(z)>3)continue;const p=A(b.position,P(x,y,z));if(active(world.get(K(p))))neighbors.set(K(p),p);}const expected=new Set(g.edges.map(e=>E(e.from,e.to)));for(const p of neighbors.values())for(const q of inputs(world,p))expected.add(E(q,p));for(const b of g.blocks){world.set(K(b.position),b.block);if(active(b.block))neighbors.set(K(b.position),b.position);}const actual=new Set;for(const p of neighbors.values())for(const q of inputs(world,p))actual.add(E(q,p));for(const b of g.blocks)world.delete(K(b.position));return expected.size===actual.size&&[...expected].every(e=>actual.has(e));}

let g;outer:for(const y of[286,290,294,282,278,270])for(const z of[350,358,342,400,408,392])for(const x of[300,308,292,150,158,142]){const c=makeLogic(P(x,y,z));if(clearGate(c)){g=c;break outer;}}assert(g,'No isolated RF quiet body');const connections=[],replacement_interface_map={...ep.replacement_interface_map},reports=new Map(orig.reports.map(r=>[r.name,r]));
function conn(name,source,destination,oldSource,oldDest,sourceBody,targetBody,kind,report){connections.push({name,source,destination,original_source:oldSource,original_destination:oldDest,source_body:sourceBody,target_body:targetBody,binding_kind:kind,actual_reference_upstream:[{position:oldSource,parity:0}],upstream_transport_nodes:report?.nodes.length??null,unary_torch_stages:report?.nodes.filter(n=>n.block.id.includes('torch')).length??null});}
const oldOut=reports.get('matrix_rf_quiet_output').original_target,retirement=reports.get('RF_quiet_to_retirement');replacement_interface_map[K(oldOut)]={position:g.ports.output,body:g.kind,mapping_kind:'function_preserving_gate_output_not_cell_translation'};conn('RF_quiet_to_retirement',g.ports.output,retirement.current_target.position,oldOut,retirement.original_target,g.kind,retirement.current_target.body,'replacement_gate_output_to_original_retained_receiver',null);
for(const[name,oldName]of[['IDLE','matrix_owner_IDLE'],['COMPLETE','matrix_owner_COMPLETE'],['REQUEST','matrix_request'],['ACK','matrix_ACK']]){const r=reports.get(oldName);assert.equal(r.roots.length,1);const root=r.roots[0];replacement_interface_map[K(r.original_target)]={position:g.ports[name],body:g.kind,mapping_kind:'function_preserving_gate_input_not_cell_translation',original_root:root.original};conn(name+'_to_RF_quiet',root.current.position,g.ports[name],root.original,r.original_target,root.current.body,g.kind,'original_root_to_replacement_function_input',r);}
const observer=reports.get('REQUEST_to_final_intents_zero'),root=observer.roots[0];assert.equal(observer.roots.length,1);conn(observer.name,root.current.position,observer.current_target.position,root.original,observer.original_target,root.current.body,observer.current_target.body,'original_root_to_original_retained_receiver',observer);
const old=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H))),oldWorld=new Map(old.blocks.map(b=>[K(b.position),b.block]));
// Independently stop the retirement cone at the original quiet matrix output.
const queue=[retirement.original_target],seen=new Set(queue.map(K));let reached=false;for(let i=0;i<queue.length;i++){const p=queue[i];if(K(p)===K(oldOut)){reached=true;continue;}assert(['minecraft:redstone_wire','minecraft:repeater'].includes(oldWorld.get(K(p)).id),'Unexpected original output qualification');for(const q of inputs(oldWorld,p))if(!seen.has(K(q))){seen.add(K(q));queue.push(q);}}assert(reached);assert.equal(queue.filter(p=>mapping[K(p)]&&K(p)!==K(retirement.original_target)&&mapping[K(p)].body!==retirement.current_target.body).length,0);connections[0].upstream_transport_nodes=queue.length;connections[0].unary_torch_stages=0;
const wanted=new Set(connections.flatMap(c=>[K(c.original_source),K(c.original_destination)])),oldEdges=[];for(const b of old.blocks)if(active(b.block))for(const q of inputs(oldWorld,b.position))if(wanted.has(K(q))||wanted.has(K(b.position)))oldEdges.push({from:q,to:b.position});const prior=new Set(ep.cuts.map(c=>E(c.from,c.to))),bindings=connections.map(c=>{const source=oldEdges.filter(e=>K(e.from)===K(c.original_source)),receiver=oldEdges.filter(e=>K(e.to)===K(c.original_destination));assert(source.length&&receiver.length,c.name);return{name:c.name,original_source:c.original_source,original_receiver:c.original_destination,source_boundary_edges:source.map(e=>({...e,in_982_shared_island_ledger:prior.has(E(e.from,e.to))})),receiver_boundary_edges:receiver.map(e=>({...e,in_982_shared_island_ledger:prior.has(E(e.from,e.to))})),binding_kind:c.binding_kind,actual_transported_source_count:1,transported_polarity:'positive',full_source_fanout_closed:false};});
writeFileSync(new URL('body-design.json',H),JSON.stringify({...base,blocks:[...base.blocks,...g.blocks],logic_bodies:[g],metrics:{cells:base.blocks.length+g.blocks.length,parent_cells:base.blocks.length,logic_body_additions:g.blocks.length,new_transport_cells:0,stored_bits:1117}})+'\n');writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({...ep,mapping,replacement_interface_map,cuts:ep.cuts,connections,unmatched:[],inherited_open_obligations:'../reset-ack-connected-v1/timing-and-composition.json',complete_core:false,native_acceptance:false})+'\n');writeFileSync(new URL('exact-cut-bindings.json',H),JSON.stringify({status:'selected_actual_original_source_and_receiver_edges_bound_to_RF_quiet_logic_and_observer',retained_original_shared_island_cuts:982,inherited_broader_mapped_body_directed_cut_count:1925,bindings,selected_actual_original_edges:oldEdges,original_positive_output_transport_nodes:queue,limits:['Function-preserving gate interfaces are not exact old-cell translations. All 982 original cuts and prior 1925 census remain explicit; a new original ownership census is separate.'],complete_core:false,native_acceptance:false},null,2)+'\n');writeFileSync(new URL('body-placement.json',H),JSON.stringify({gate:g,parent_cells:base.blocks.length,added_body_cells:g.blocks.length,parent_manifest_sha256:'562207ab002c11d299500257a9ff6709654aad8a0b3f0df8b3fee2fd97a6ab7a',complete_core:false,native_acceptance:false},null,2)+'\n');console.log(JSON.stringify({gate:g.ports,parent:base.blocks.length,body_additions:g.blocks.length,routes:connections.length,old_output_transport:queue.length}));
