// Reconstruct every possible input from actual matrix and path geometry, then screen the full parent.
import assert from'node:assert/strict';import{P,K,A,R,W,C,D,pins,bytes,read,write,summary}from'./tools.mjs';import{loadBase}from'./frame.mjs';import{inputs,active}from'../cut-inputs.mjs';
const d=read('delta.json'),template=read('../../internal-bank-response-v1/collector.json'),base=loadBase(),world=base.world,newKeys=new Set(),bodyKeys=new Set(),expected=new Map(),arrivals=new Map(),local=new Map(template.blocks.map(r=>[K(r.position),r.block])),T=p=>A(p,d.matrix_origin),S=b=>b?.id.endsWith('_concrete'),UP=p=>P(p.x,p.y+1,p.z),DOWN=p=>P(p.x,p.y-1,p.z);
for(const r of d.new_cells){const k=K(r.position);assert(!world.has(k),'Actual occupied-cell collision '+k);assert(!newKeys.has(k));newKeys.add(k);world.set(k,r.block);}
for(const r of template.blocks){const p=T(r.position),k=K(p);assert.deepEqual(world.get(k),r.block);bodyKeys.add(k);if(active(r.block))expected.set(k,inputs(local,r.position).map(q=>K(T(q))));}
let vertices=0;const pathDevices=new Set();for(const c of d.connections){const path=[c.source,c.tap,...c.path,c.arrival,c.destination];assert.deepEqual(c.path[0],c.start);assert.deepEqual(c.path.at(-1),c.end);assert(!arrivals.has(K(c.destination)));arrivals.set(K(c.destination),K(c.arrival));vertices+=path.length;for(let i=1;i<path.length-1;i++){const p=path[i],k=K(p),b=world.get(k);assert([W,R].includes(b?.id));assert(newKeys.has(k));assert(!bodyKeys.has(k));assert(!pathDevices.has(k),'Shared unspecifed transport '+k);pathDevices.add(k);assert(newKeys.has(K(DOWN(p))));assert(S(world.get(K(DOWN(p)))));if(b.id===R){const v=D[b.properties.facing];assert.deepEqual(path[i-1],P(p.x-v.x,p.y,p.z-v.z));assert.deepEqual(path[i+1],A(p,v));}const ps=[K(path[i-1])];if(b.id===W&&world.get(K(path[i+1]))?.id===W)ps.push(K(path[i+1]));expected.set(k,ps);if(path[i-1].y!==p.y){const low=path[i-1].y<p.y?path[i-1]:p;assert(!world.has(K(UP(low))),'Actual capped dust stair '+K(low));}}
}
assert.equal(newKeys.size,bodyKeys.size+2*pathDevices.size);const baseline={get:k=>newKeys.has(k)?undefined:world.get(k)};let receivers=0,supports=0,parentInputs=0,bodyInputs=0,cableInputs=0,parentChanged=0,bodyChanged=0;for(const r of [...base.rows,...d.new_cells]){const p=r.position,k=K(p),b=world.get(k);if([W,R,C,'minecraft:redstone_torch','minecraft:lever'].includes(b.id)){assert(S(world.get(K(DOWN(p)))),'Unsupported '+k);supports++;}else if(b.id==='minecraft:redstone_wall_torch'){assert(S(world.get(K(A(p,D[b.properties.facing])))),'Unsupported wall torch '+k);supports++;}if(!active(b))continue;receivers++;const actual=inputs(world,p).map(K).sort();let wanted;if(newKeys.has(k)){wanted=[...expected.get(k)];if(bodyKeys.has(k)){bodyInputs+=wanted.length;if(arrivals.has(k)){wanted.push(arrivals.get(k));bodyChanged++;}}else cableInputs+=wanted.length;}else{wanted=inputs(baseline,p).map(K);parentInputs+=wanted.length;if(arrivals.has(k)){wanted.push(arrivals.get(k));parentChanged++;}}assert.deepEqual(actual,[...new Set(wanted)].sort(),'Unexpected actual possible input '+k);}
assert.equal(parentChanged,8);assert.equal(bodyChanged,36);const cost=summary(d.new_cells);assert(cost.box.from.x>=-660&&cost.box.to.x<=835&&cost.box.from.y>=-78&&cost.box.to.y<=301&&cost.box.from.z>=-647&&cost.box.to.z<=1830);for(const n of['check-map.mjs','frame.mjs','tools.mjs','../cut-inputs.mjs'])bytes(n);const result={status:'full_parent_and_shared_matrix_actual_input_support_screen_passed',parent_cells:base.rows.length,new_cells:newKeys.size,total_cells:world.size,receivers,supports,parentInputs,bodyInputs,cableInputs,parentChanged,bodyChanged,totalInputs:parentInputs+bodyInputs+cableInputs+parentChanged+bodyChanged,full_path_vertices:vertices,routed_path_vertices:d.connections.reduce((s,c)=>s+c.path.length,0),body_cells:bodyKeys.size,cable_and_stub_devices:pathDevices.size,cost,source_sha256:pins,limits:['Full physical possible-input model, not Minecraft event timing. All32 matrix inputs and four channel0 qualifiers are driven; only eight backend-D parent receivers gain arrivals.','Other channel qualifier pads have no newly accepted incoming source, and other backend-D pads are unchanged.']};write('map-checks.json',result);console.log(JSON.stringify({...result,cost:{cells:cost.cells,box:cost.box},source_sha256:undefined}));
