import assert from'node:assert/strict';import{P,K,A,H,pins,bytes,read,write}from'./tools.mjs';import{loadBase}from'./frame.mjs';import{V,F}from'./path-search.mjs';import{inputs,active}from'../cut-inputs.mjs';
const allocation=read('../../../response-routing-allocation-v1/assignment.json','1b7b3995d1a7cd4c76ea2e784011a526fba8b60634407fe61ccde8d7484ff766'),template=read('../../internal-bank-response-v1/collector.json'),{world:map}=loadBase(),added=[],refusals=[],connections=[],matrixRows=template.blocks.map(r=>({position:A(r.position,allocation.selected_matrix_origin),block:r.block,part:'shared_qualified_response_matrix'})),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',R='minecraft:repeater',U=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n);
function screen(rows,sources=[],allowed=[]){const proposed=new Map();for(const r of rows){if(map.has(K(r.position)))return{reason:'occupied',position:r.position};assert(!proposed.has(K(r.position)));proposed.set(K(r.position),r.block);}const component=new Map([...proposed,...sources.map(p=>[K(p),map.get(K(p))])]),after={get:k=>proposed.get(k)??map.get(k)},affected=new Map();for(const r of rows)for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++){const p=P(r.position.x+dx,r.position.y+dy,r.position.z+dz);if(active(after.get(K(p))))affected.set(K(p),p);}for(const[k,p]of affected){const actual=inputs(after,p).map(K).sort();const expected=proposed.has(k)?inputs(component,p).map(K).sort():[...new Set([...inputs(map,p).map(K),...allowed.filter(([a,b])=>K(b)===k).map(([a])=>K(a))])].sort();if(JSON.stringify(actual)!==JSON.stringify(expected))return{reason:proposed.has(k)?'new_foreign_input':'changed_parent_input',position:p,actual,expected};}return null;}
function commit(rows,part){for(const r of rows){assert(!map.has(K(r.position)));map.set(K(r.position),r.block);added.push({...r,part});}}
assert.equal(screen(matrixRows),null,'Allocated exact matrix contact');commit(matrixRows,'shared_qualified_response_matrix');
function stub(p,d,source){const tap=step(p,d,source?1:-1),pad=step(p,d,source?2:-2),rows=[{position:U(tap),block:{id:S}},{position:tap,block:{id:R,properties:{facing:F[d],delay:'1'}}},{position:U(pad),block:{id:S}},{position:pad,block:{id:W}}];return{rows,tap,pad};}
for(const a of allocation.connections){const name=a.kind+(a.bank!==undefined?'_bank'+a.bank:'')+(a.channel!==undefined?'_channel'+a.channel:'')+(a.bit!==undefined?'_bit'+a.bit:''),c={...a,name};let launch,arrival;
 for(const d of a.kind==='held_data'?['south','north','east','west']:a.kind==='actual_RR_OR_WR'?['east','south','west','north']:['east','south','north','west']){const s=stub(a.source,d,true),failure=screen(s.rows,[a.source]);if(failure){refusals.push({name,endpoint:'source',direction:d,failure});continue;}launch={source_direction:d,tap:s.tap,start:s.pad};commit(s.rows,name+'_source');break;}assert(launch,'No isolated actual source '+name);
 for(const d of a.kind==='qualified_backend_D'?['east','south','north','west']:['south','east','west','north']){const s=stub(a.destination,d,false),failure=screen(s.rows,[a.destination],[[s.tap,a.destination]]);if(failure){refusals.push({name,endpoint:'arrival',direction:d,failure});continue;}arrival={arrival_direction:d,arrival:s.tap,end:s.pad};commit(s.rows,name+'_arrival');break;}assert(arrival,'No isolated actual receiver '+name);connections.push({...c,...launch,...arrival});}
const future=read('../bank-response-collectors-v1/placement-proposal.json').passing[0].connections.filter(c=>c.channel>0),reserved=[];for(const c of future){const p=c.kind==='actual_RR_OR_WR'?c.destination:c.source,d=c.kind==='actual_RR_OR_WR'?'north':'east';for(let i=1;i<=7;i++){const q=step(p,d,i);reserved.push(q,U(q));}}
for(const n of['prepare.mjs','frame.mjs','tools.mjs','path-search.mjs','../cut-inputs.mjs'])bytes(n);write('placement.json',{status:'allocated_shared_matrix_and44_isolated_endpoints_drawn_cables_pending',base_cells:2192740,new_cells:added,body_cells:10272,stub_cells:added.length-10272,matrix_origin:allocation.selected_matrix_origin,connections,reserved_future_ports:reserved,refusals,source_sha256:pins,limits:['Exact allocated original shared matrix plus source/arrival stubs only. All44 cables remain undrawn; no cut credit.','Other three channels remain unconnected at their exact qualifier and backend-D interfaces.']});console.log(JSON.stringify({body_cells:10272,new_cells:added.length,connections:connections.length,refusals:refusals.length}));
