// Draw all44 allocated transports inside the accepted shared envelope.
import assert from'node:assert/strict';import{readFileSync,existsSync}from'node:fs';import{P,K,H,pins,bytes,read,write}from'./tools.mjs';import{loadBase}from'./frame.mjs';import{V,F,searchPath,refreshIndices}from'./path-search.mjs';
const base=loadBase(),placement=read('placement.json'),map=new Map(base.rows.map(r=>[K(r.position),r])),added=structuredClone(placement.new_cells),connections=structuredClone(placement.connections),U=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),cacheFile=new URL('paths.json',H),cache=existsSync(cacheFile)?JSON.parse(readFileSync(cacheFile)):{};
for(const r of added){assert(!map.has(K(r.position)));map.set(K(r.position),r);}const reserve=c=>[...Array.from({length:4},(_,i)=>step(c.start,c.source_direction,i)),...Array.from({length:4},(_,i)=>step(c.end,c.arrival_direction,-i))],reserved=[...connections.flatMap(reserve),...placement.reserved_future_ports];
function put(p,block,part){assert(!map.has(K(p)),'Route overlaps '+K(p));const row={position:p,block,part};map.set(K(p),row);added.push(row);}
for(const c of connections){let path=cache[c.name]?.path;if(path){assert.deepEqual(cache[c.name].source,c.start);assert.deepEqual(cache[c.name].destination,c.end);console.log(JSON.stringify({name:c.name,cached:true,points:path.length}));}else{const ignore=[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(U),...reserve(c)],found=searchPath(map,c.start,c.end,{ignore,reserved,forbidden:[P(c.arrival.x,c.arrival.y-2,c.arrival.z)],limit:4000000});path=found.path;cache[c.name]={source:c.start,destination:c.end,path,expanded:found.expanded};write('paths.json',cache);console.log(JSON.stringify({name:c.name,points:path.length,expanded:found.expanded}));}
 const indices=refreshIndices(path),rs=new Set(indices);for(let i=1;i<path.length-1;i++){const p=path[i],n=path[i+1],dir=Object.keys(V).find(d=>p.x+V[d][0]===n.x&&p.z+V[d][1]===n.z);assert(dir);put(U(p),{id:'minecraft:light_gray_concrete'},c.name);put(p,{id:rs.has(i)?'minecraft:repeater':'minecraft:redstone_wire',...rs.has(i)?{properties:{facing:F[dir],delay:'1'}}:{}},c.name);}c.path=path;c.refresh_indices=indices;
 write('in-progress-delta.json',{status:'partial_uncredited',base_cells:base.world.size,complete_routes:connections.filter(r=>r.path).length,new_cells:added,completed_connections:connections.filter(r=>r.path),pending_names:connections.filter(r=>!r.path).map(r=>r.name)});
}
for(const n of['route.mjs','frame.mjs','tools.mjs','path-search.mjs','placement.json','paths.json'])bytes(n);write('delta.json',{status:'drawn44_response_transports_requires_full_map_and_function_checks',base_cells:base.world.size,new_cells:added,matrix_origin:placement.matrix_origin,connections,metrics:{cells:base.world.size+added.length,added_cells:added.length,body_cells:10272,stubs:placement.stub_cells,cables:44,held_data:32,channel0_qualifiers:4,channel0_D:8,path_vertices:connections.reduce((s,c)=>s+c.path.length,0),new_state:0},source_sha256:pins,limits:['Other3channels still need12qualifier and24D transports. Shared bank input feeds are counted once.','No freeze/ledger credit before all exact parent inputs/supports, actual source-inclusive functions, strength and mutations pass.','All routing is bounded by existing common x/y/z envelope; timing/capture/native acceptance remains open.']});console.log(JSON.stringify({status:'drawn44',new_cells:added.length,path_vertices:connections.reduce((s,c)=>s+c.path.length,0)}));
