// Finite actual-map checks plus abstract ordering tests; no native simulation.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {makeProgramController} from '../../../../hardware/memory-layout-program-controller.mjs';
import {makeProgramCapture} from '../../../../hardware/memory-layout-program-capture.mjs';
const d=makeProgramController(),saved=JSON.parse(readFileSync(new URL('design.json',import.meta.url)));assert.deepEqual(d,saved);
const parent=makeProgramCapture(),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,O=P(-60,-50,-180),G=(x,y,z)=>P(x+O.x,y+O.y,z+O.z),S='minecraft:light_gray_concrete',V={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},m=new Map(d.blocks.map(v=>[K(v.position),v.block])),get=p=>m.get(K(p));
assert.equal(m.size,d.blocks.length);for(const v of parent.blocks)assert.deepEqual(get(v.position),v.block);assert.equal(d.blocks.length-parent.blocks.length,d.added_blocks.length);
const rep=(p,f,delay='1')=>assert.deepEqual(get(p),{id:'minecraft:repeater',properties:{facing:f,delay}}),wire=p=>assert.equal(get(p)?.id,'minecraft:redstone_wire'),cmp=(p,f)=>assert.deepEqual(get(p),{id:'minecraft:comparator',properties:{facing:f,mode:'subtract'}});
for(const r of d.routes){assert(r.max_dust_run<=13);for(const p of r.refresh){const i=r.path.findIndex(q=>K(q)===K(p)),a=r.path[i-1],b=r.path[i+1],[dx,dz]=V[get(p).properties.facing];assert.deepEqual(P(p.x-dx,p.y,p.z-dz),a);assert.deepEqual(P(p.x+dx,p.y,p.z+dz),b);}}
// Actual chronological normal/reset chains. Every extra contact of a chain
// element must be one of the five explicit output taps or entry/exit.
function pipeline(kind,len,dx,dz){let delay=0,slow=0;const ordered=[],taps={};for(let row=0;row<4;row++){for(let j=0;j<len;j++){const x=row%2?15+len-j:16+j,p=G(x+dx,5,row*4+dz),b=get(p);ordered.push(p);if(kind==='normal'&&[[31,0],[47,0],[63,0],[63,8],[79,8]].some(([xx,zz])=>xx===x&&zz===row*4)){wire(p);taps[K(p)]={chain_prefix_nominal_ticks:delay,chain_cells:ordered.length};}else{rep(p,row%2?'east':'west','4');slow++;delay+=8;}}if(row<3){const x=row%2?15:16+len;for(let z=row*4;z<=row*4+4;z++){const p=G(x+dx,5,z+dz);ordered.push(p);if(z===row*4+1||kind==='normal'&&row===2&&z===10){rep(p,'north');delay+=2;}else wire(p);}}}
 for(let i=1;i<ordered.length;i++){const a=ordered[i-1],b=ordered[i];assert.equal(Math.abs(a.x-b.x)+Math.abs(a.y-b.y)+Math.abs(a.z-b.z),1);}
 const index=new Map(ordered.map((p,i)=>[K(p),i]));let outputTaps=0;
 for(let i=0;i<ordered.length;i++){const p=ordered[i];for(const [dx,dz]of Object.values(V)){const q=P(p.x+dx,p.y,p.z+dz),b=get(q);if(!b||b.id===S)continue;const j=index.get(K(q));if(j!==undefined){assert.equal(Math.abs(j-i),1,'same-chain shortcut');continue;}
 if(i===0||i===ordered.length-1)continue;
 if(get(p).id==='minecraft:repeater'&&b.id==='minecraft:repeater'&&get(p).properties.facing===b.properties.facing){const [vx,vz]=V[b.properties.facing];if(vx*dx+vz*dz===0)continue;} // Parallel diodes neither rear-feed nor side-lock each other.
 if(kind==='normal'&&taps[K(p)]){const bit=d.stages.find(s=>K(s.position)===K(p));assert(bit);const south=p.z===O.z+8;assert.deepEqual(q,P(p.x,p.y,p.z+(south?1:-1)));rep(q,south?'north':'south');outputTaps++;}else assert.fail('unlisted delay contact '+K(p)+' -> '+K(q));}}
 return{slow_repeaters:slow,chain_cells:ordered.length,chain_nominal_ticks:delay,taps,output_taps:outputTaps};}
const normal=pipeline('normal',64,0,0),reset=pipeline('reset',128,-180,-60);assert.equal(normal.slow_repeaters,251);assert.equal(reset.slow_repeaters,512);assert.equal(normal.output_taps,5);
// All control endpoints are physically driven, including side masks.
for(const [x,z,f]of[[31,-12,'south'],[63,-12,'south'],[79,20,'north']])cmp(G(x,13,z),f);
cmp(G(8,5,12),'east');cmp(G(16,9,-4),'west');for(const x of[100,112])cmp(P(x,287,-94),'north');
for(const [p,f]of[[P(57,-37,-79),'east'],[P(75,-37,-77),'west'],[P(90,279,-49),'north'],[G(0,1,-1),'north'],[G(14,1,-1),'north'],[G(16,9,-3),'south']])rep(p,f);
const tapData=[];for(let b=0;b<16;b++){const y=b%2?283:279,z=-60-2*b;assert.equal(get(P(79,y,z))?.id,S);rep(P(79,y-1,z),'west');assert.equal(get(P(78,y-1,z))?.id,S);wire(P(78,y,z));for(const[x,yy]of[[80,y-1],[81,y-2],[82,y-2],[83,y-2]])wire(P(x,yy,z));rep(P(84,y-2,z),'west');for(let yy=y-2;yy<=y+10;yy++)assert.equal(get(P(85,yy,z))?.id,(yy-y+2)%2?'minecraft:redstone_torch':S);rep(P(88,y+10,z),'west');rep(P(87,y+10,z-1),'south');assert.deepEqual(d.ports.read_data.positions[b],P(89,y+10,z));assert.deepEqual(d.ports.read_data.positions[16+b],P(87,y+10,z-2));tapData.push({bit:b,cap:P(79,y,z),support:P(78,y-1,z),lower_repeater:P(79,y-1,z)});}
for(const [n,p]of Object.entries(d.ports)){assert.equal(p.positions.length,p.width,n);for(const q of p.positions)wire(q);}
// Every new torch support has exact physical source sets. This additionally
// catches same-net weak power around timing towers, not just foreign nets.
function candidates(p){const a=[];for(const [dx,dz]of Object.values(V)){const q=P(p.x-dx,p.y,p.z-dz),b=get(q);if(/:(repeater|comparator)$/.test(b?.id??'')&&JSON.stringify(V[b.properties.facing])===JSON.stringify([dx,dz])||b?.id==='minecraft:redstone_wire')a.push(K(q));}for(const [dy,id]of[[1,'minecraft:redstone_wire'],[-1,'minecraft:redstone_torch']]){const q=P(p.x,p.y+dy,p.z);if(get(q)?.id===id)a.push(K(q));}return a.sort();}
const special=new Map([[G(0,1,0),[G(-1,1,0),G(0,1,-1),G(0,1,1)]],[G(12,1,0),[G(12,1,-1),G(13,1,0)]],[G(-180,1,-60),[G(-181,1,-60),G(-180,1,-59)]],[G(-168,1,-60),[G(-168,1,-61),G(-167,1,-60)]]].map(([q,a])=>[K(q),a.map(K).sort()]));let torchSupports=0;
for(const v of d.added_blocks){const p=v.position,b=v.block;if(!['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id))continue;let q=P(p.x,p.y-1,p.z);if(b.id.endsWith('wall_torch')){const[dx,dz]=V[b.properties.facing];q=P(p.x+dx,p.y,p.z+dz);}const a=candidates(q);if(special.has(K(q)))assert.deepEqual(a,special.get(K(q)));else assert.equal(a.length,1,'torch source multiplicity '+K(q)+' '+a);torchSupports++;}
const cp=spawnSync('python3',[fileURLToPath(new URL('check-contacts.py',import.meta.url))],{encoding:'utf8'});assert.equal(cp.status,0,cp.stderr);const contact=JSON.parse(cp.stdout);for(const n of['foreign_faces','foreign_slopes','unknown_side_sources','foreign_strong_rear'])assert.deepEqual(contact[n],[]);
const protocol=spawnSync(process.execPath,[fileURLToPath(new URL('check-protocol.mjs',import.meta.url))],{encoding:'utf8'});assert.equal(protocol.status,0,protocol.stderr);const abstract=JSON.parse(protocol.stdout);
const columns=new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`));const result={status:'offline_connected_program_controller_geometry_and_abstract_ordering_checked',...d.metrics,parent_positions_preserved:parent.blocks.length,ports:Object.fromEntries(Object.entries(d.ports).map(([n,p])=>[n,p.width])),occupied_columns:columns.size,box:d.box,support_checks:contact.supports,torch_support_source_checks:torchSupports,normal_pipeline:normal,reset_pipeline:reset,foreign_faces:0,foreign_step_dust:0,foreign_diode_side_sources:0,foreign_strong_rear_paths:0,response_taps:tapData,abstract_protocol:abstract,full_gpu:false,native_acceptance:false,limits:['No Minecraft block-update or propagation simulation.','Nominal repeaters/torch polarity do not establish non-overlap or adequate ROM settle/flush margins.','Fixed priority may starve consumer 1 under continuous consumer 0 traffic, matching fixed-priority arbitration.','Reset and inactive data are unqualified retained payload; ready-low, not zero data, establishes invalidity.','Static one-solid and adjacency screens are bounded; independent/native review still required.']};
if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
