import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeFourBankService}from'../../../../hardware/memory-layout-four-bank-service.mjs';import{makeDataChannel}from'../../../../hardware/memory-layout-data-channel.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),d=makeFourBankService(),saved=read('design.json'),parent=read('../consumer-drain-v1/design.json');assert.equal(hash(d),hash(saved));const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',R='minecraft:repeater',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block]));
assert.equal(m.size,d.blocks.length);for(const v of parent.blocks)assert.deepEqual(m.get(K(v.position)),v.block);let exactBank=0;
for(const b of d.banks){const local=makeDataChannel({bankIndex:b.bank}),T=p=>P(p.x+b.origin.x,p.y+b.origin.y,p.z+b.origin.z);assert.equal(local.blocks.length,b.blocks);for(const v of local.blocks){assert.deepEqual(m.get(K(T(v.position))),v.block);exactBank++;}for(const[n,p]of Object.entries(local.ports))assert.deepEqual(b.ports[n].positions,p.positions.map(T));assert.deepEqual(b.connected_global_slots,[0,1,2,3]);assert.deepEqual(b.literal_quiet_slots,[4,5,6,7]);}
function paths(mm){for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],b=mm.get(K(p));assert(b,'cut '+r.name);if(b.id===R){const v=D[b.properties.facing];assert.deepEqual(r.path[i-1],P(p.x-v.x,p.y,p.z-v.z));assert.deepEqual(r.path[i+1],P(p.x+v.x,p.y,p.z+v.z));}else assert.equal(b.id,W);}}
function terminals(mm){for(const b of d.bindings){assert.deepEqual(mm.get(K(b.driver)),{id:R,properties:{facing:'north',delay:'1'}});assert.deepEqual(b.destination,P(b.driver.x,b.driver.y,b.driver.z+1));assert.equal(mm.get(K(b.destination)).id,W);assert.deepEqual(b.source,parent.ports.reset.positions[0]);}for(const q of d.quiet){assert(q.slot>=4&&q.slot<8);const dx=q.kind==='read_valid'?-1:1;assert.deepEqual(q.driver,P(q.pad.x+dx,q.pad.y,q.pad.z));assert.deepEqual(q.rear,P(q.pad.x+2*dx,q.pad.y,q.pad.z));assert.deepEqual(mm.get(K(q.driver)),{id:R,properties:{facing:dx<0?'west':'east',delay:'1'}});assert.deepEqual(mm.get(K(q.rear)),{id:S});assert.equal(q.value,0);}}
paths(m);terminals(m);let n=0;for(const q of d.quiet){const k=K(q.rear),old=m.get(k);m.set(k,{id:'minecraft:redstone_block'});assert.throws(()=>terminals(m));m.set(k,old);n++;}for(const b of d.bindings){const k=K(b.driver),old=m.get(k);m.set(k,{id:R,properties:{facing:'south',delay:'1'}});assert.throws(()=>terminals(m));m.set(k,old);n++;}const q=d.routes[0].path[4],old=m.get(K(q));m.delete(K(q));assert.throws(()=>paths(m));m.set(K(q),old);n++;
const chunks=new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`)),out={status:'offline_four_bank_service_baseline_geometry_pass',...d.metrics,exact_regeneration:true,exact_parent_cells:parent.blocks.length,exact_translated_bank_cells:exactBank,occupied_chunk_columns:chunks.size,reset_bindings:d.bindings.length,literal_quiet_driver_tests:d.quiet.length,corruptions_rejected:n,complete_component_geometry:false,native_acceptance:false};
if(process.argv.includes('--save')){writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');writeFileSync(new URL('inventory.json',import.meta.url),JSON.stringify(d.metrics,null,2)+'\n');writeFileSync(new URL('ports.json',import.meta.url),JSON.stringify({raw:d.ports,banks:d.banks.map(b=>({bank:b.bank,ports:b.ports,external_requester_slots:4,quiet_slots:b.literal_quiet_slots})),remaining:d.missing},null,2)+'\n');}console.log(JSON.stringify(out));
