import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeChannelRetention}from'../../../../hardware/memory-layout-channel-retention.mjs';import{makeChannelAllocator}from'../../../../hardware/memory-layout-channel-allocator.mjs';import{makeChannelAdmission}from'../../../../hardware/memory-layout-channel-admission.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',V={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},H=d=>createHash('sha256').update(JSON.stringify(d)).digest('hex');
const d=makeChannelRetention(),old=makeChannelAllocator(),a=makeChannelAdmission(),m=new Map(d.blocks.map(v=>[K(v.position),v.block]));assert.equal(H(d),H(JSON.parse(readFileSync(new URL('design.json',import.meta.url)))));assert.equal(m.size,d.blocks.length);
const rep=(f)=>({id:'minecraft:repeater',properties:{facing:f,delay:'1'}}),cmp=f=>({id:'minecraft:comparator',properties:{facing:f,mode:'subtract'}});
function check(map){let preserved=0;for(const v of old.blocks){assert.deepEqual(map.get(K(v.position)),v.block);preserved++;}
 for(const st of[...d.stores,...d.snapshots,...d.busySnapshots]){const owner=st.name==='owner',payload=st.name==='payload',free=st.kind==='free_request';const face=owner?'south':payload?'east':free?'north':'south';assert.deepEqual(map.get(K(st.storage)),rep(face));assert.deepEqual(map.get(K(st.driver)),rep(face));assert.deepEqual(map.get(K(st.lock)),rep(owner?'west':payload?'south':'east'));assert.equal(map.get(K(st.terminal))?.id,W);}
 for(const g of d.muxes){assert.deepEqual(map.get(K(g.gate)),cmp('east'));assert.deepEqual(map.get(K(g.rear)),rep('east'));assert.deepEqual(map.get(K(g.mask)),rep('north'));assert.equal(map.get(K(g.collector))?.id,S);}
 for(const g of d.claimGates){assert.deepEqual(map.get(K(g.gate)),cmp('north'));assert.deepEqual(map.get(K(g.owner_rear)),rep('north'));assert.deepEqual(map.get(K(g.inactive_mask)),rep('west'));assert.equal(map.get(K(g.collector))?.id,W);}
 for(const st of d.activeStates){assert.deepEqual(map.get(K(st.clear_gate)),cmp('west'));assert.deepEqual(map.get(K(st.barrier)),rep('north'));assert.deepEqual(map.get(K(P(st.set.x-2,st.set.y,st.set.z))),cmp('east'));assert.deepEqual(map.get(K(P(st.set.x-2,st.set.y,st.set.z-1))),rep('north'));}
 for(const ch of[0,1,2,3]){const X=128*ch,Y=80*ch;assert.deepEqual(map.get(K(P(X+46,Y+1,-10))),cmp('east'));assert.deepEqual(map.get(K(P(X+46,Y+1,-11))),rep('north'));assert.deepEqual(map.get(K(P(X+104,Y+32,-18))),cmp('north'));assert.deepEqual(map.get(K(P(X+103,Y+32,-18))),rep('west'));}
 for(const ph of['open_owner','open_address','write_phase','open_response']){const p=a.ports[ph];assert.equal(map.get(K(P(p.x+300,p.y-32,p.z+350)))?.id,W);assert.deepEqual(map.get(K(P(p.x+302,p.y-32,p.z+350))),cmp('east'));}
 return preserved;
}
const preserved=check(m);assert.equal(d.stores.length,100);assert.equal(d.snapshots.length,8);assert.equal(d.busySnapshots.length,4);assert.equal(d.claimGates.length,32);assert.equal(d.muxes.length,544);assert.deepEqual(d.fields.map(f=>f.name),[...Array.from({length:6},(_,i)=>'address'+(i+2)),...Array.from({length:8},(_,i)=>'write_data'+i),'is_write','address0','address1']);
let supports=0,steps=0;const solids=new Set([S,'minecraft:redstone_block']);for(const v of d.blocks){const p=v.position,b=v.block;if(solids.has(b.id))continue;let q=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const[dx,dz]=V[b.properties.facing];q=P(p.x+dx,p.y,p.z+dz);}assert.equal(m.get(K(q))?.id,S,'unsupported '+K(p));supports++;}
for(const rt of[...d.routes,...a.routes.map(r=>({...r,path:r.path.map(p=>P(p.x+300,p.y-32,p.z+350))}))])for(let i=0;i<rt.path.length;i++){const p=rt.path[i],b=m.get(K(p));assert(b,rt.name+' missing');if(i){const q=rt.path[i-1],h=Math.abs(p.x-q.x)+Math.abs(p.z-q.z);assert.equal(h,1);assert(Math.abs(p.y-q.y)<=1);steps++;}if(b.id==='minecraft:repeater'){const[dx,dz]=V[b.properties.facing];if(i)assert.deepEqual(rt.path[i-1],P(p.x-dx,p.y,p.z-dz),rt.name+' rear');if(i+1<rt.path.length)assert.deepEqual(rt.path[i+1],P(p.x+dx,p.y,p.z+dz),rt.name+' front');}else assert.equal(b.id,W);}
for(const coil of a.coils){assert.equal(coil.slow_cells.length,coil.kind==='active'?1024:1536);for(const p of coil.slow_cells)assert.equal(m.get(K(P(p.x+300,p.y-32,p.z+350)))?.properties.delay,'4');}
assert.deepEqual(a.taps.map(v=>v.index),[128,256,384,512,640,768,896,1024]);assert(a.nominal.reset_slow_game_ticks>a.nominal.normal_slow_game_ticks);assert.equal(a.nominal.capture_window_slow_game_ticks,1024);
// Separate integer scan vs Boolean matrix with ACTIVE-qualified claims. Every
// valid disjoint prior ownership assignment and every raw request mask appears.
const states=[];function rec(xs){if(xs.length===4){states.push(xs);return;}rec([...xs,-1]);for(let i=0;i<8;i++)if(!xs.includes(i))rec([...xs,i]);}rec([]);let vectors=0;
for(const owners of states){let busy=0,claimed=0;owners.forEach((v,c)=>{if(v>=0){busy|=1<<c;claimed|=1<<v;}});for(let request=0;request<256;request++){let free=request&~claimed;const expected=owners.slice();for(let c=0;c<4;c++)if(expected[c]===-1)for(let i=0;i<8;i++)if(free&(1<<i)){expected[c]=i;free&=~(1<<i);break;}
 let av=Array.from({length:8},(_,i)=>Number(!!(request&(1<<i))&&!(claimed&(1<<i))));const got=owners.slice();for(let c=0;c<4;c++){const g=av.map((v,i)=>Number(v&&!av.slice(0,i).some(Boolean)&&!(busy&(1<<c))));if(!(busy&(1<<c)))got[c]=g.findIndex(Boolean);av=av.map((v,i)=>Number(v&&!g[i]));}assert.deepEqual(got,expected);const active=got.filter(v=>v>=0);assert.equal(new Set(active).size,active.length);vectors++;}}
let phaseCases=0;for(let reset=0;reset<2;reset++)for(let busy=0;busy<2;busy++)for(let owner=0;owner<2;owner++)for(let retire=0;retire<2;retire++){
 const states=['snapshot','gap1','owners','gap2','payload','gap3','commit','tail','idle'];let held=owner;for(const phase of states){const active=phase!=='idle',openOwner=!reset&&!busy&&phase==='owners',openPayload=!reset&&!busy&&phase==='payload',commit=!reset&&phase==='commit'&&owner,clear=reset||(!active&&retire);assert(!(openOwner&&openPayload));assert(!active||reset||!clear);if(reset)held=0;else if(commit)held=1;else if(clear)held=0;if(reset)assert(!openOwner&&!openPayload&&!commit&&!held);phaseCases++;}}
let negatives=0;const bads=[...d.stores.slice(0,1),d.stores.find(v=>v.field==='address0'),d.stores.find(v=>v.field==='address1'),d.snapshots[0],d.busySnapshots[3]].map(v=>[v.lock,null]);bads.push([d.claimGates[31].inactive_mask,rep('east')],[d.activeStates[2].barrier,null],[P(62,1,171),null],[P(104,32,-18),cmp('south')],[P(340,-11,338),null],[old.blocks[0].position,null]);for(const[p,b]of bads){const mm=new Map(m);b?mm.set(K(p),b):mm.delete(K(p));assert.throws(()=>check(mm));negatives++;}
const out={status:'offline_connected_channel_retention_claims_admission_checks_pass',...d.metrics,parent_positions_preserved:preserved,supports,route_steps:steps,retained_stores_checked:112,owner_claim_gates:32,prior_ownership_states:states.length,settled_original_order_vectors:vectors,boolean_phase_cases:phaseCases,negative_cases:negatives,admission_nominal:a.nominal,complete_data_memory:false,native_acceptance:false,limits:'Geometry, source bindings, settled Boolean ownership and counted delay cells only; no dynamic simulator, source fanout/backend completion or native timing proof.'};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
