// Partition the other actual shared stores, not an inferred logical bit count.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),B=new URL('../../',H),ROOT=new URL('../../../../',H),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pins={};
function read(n){const p=new URL(n,B);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');return readLargeDesign(fileURLToPath(p));}
const core=read('compact-core-guard-v1/design.json'),world=new Map(core.blocks.map(b=>[K(b.position),b.block])),prior=read('core-lane-colocation-v1/shared-spine-v1/bodies.json'),lane=read('core-lane-colocation-v1/bodies.json'),ir=read('core-lane-colocation-v1/shared-ir-body.json'),priorKeys=new Set([...lane.blocks.map(b=>K(b.position)),...ir.blocks.map(b=>K(b.original_position)),...prior.groups.flatMap(g=>g.blocks.map(b=>K(b.original_position)))]),claims=new Map,groups=[],changes=[],absent=[];
function claim(name,path,test=()=>true,offset=P(0,0,0)){const seed=read(path),blocks=[],g={name,path,original_offset:offset,blocks};groups.push(g);for(const b of seed.blocks){if(!test(b))continue;const position=A(b.position,offset),k=K(position),block=world.get(k);if(!block){absent.push({group:name,position});continue;}assert(!priorKeys.has(k),'Already owned '+name+' '+k);const prev=claims.get(k);if(prev){assert(block.id.endsWith('_concrete'),'Shared active '+name+' / '+prev+' '+k);continue;}claims.set(k,name);if(JSON.stringify(block)!==JSON.stringify(b.block))changes.push({group:name,position,before:b.block,actual:block});blocks.push({position,block,group:name,original_part:b.part});}console.log(name,blocks.length);}
const parts=(...xs)=>b=>xs.includes(b.part),prefix=(...xs)=>b=>xs.some(x=>b.part?.startsWith(x));
claim('front_core_fetch_intents','control-front-v1/design.json',b=>['core','fetch','intents'].includes(b.part)||b.part?.startsWith('intent_data_clamp_')||['intent_initialize','intent_initialize_entry','fetch_tail_gate','operation_held_or','operation_export'].includes(b.part));
claim('pc_feedback','control-front-pc-v1/design.json',parts('pc_feedback'));
claim('flags_agreement','control-front-pc-v2/design.json',b=>b.part?.startsWith('nzp_lane_')||b.part==='agreement');
claim('commit_owner_intents','control-commit-v1/design.json',parts('commit','owner','update_intent','operand_intent','owner_kind','rf_intent'));
claim('release_intent','control-commit-v2/design.json',parts('release_intent'));
claim('other_claim','control-start-other-v1/design.json',parts('other_gate','other_claim'));
// Exact relocated fault AND guard logic; transport paths remain external.
claim('relocated_fault_guard','compact-core-guard-v1/design.json',parts('relocated_cluster'));
claim('alu_admission','alu-core-admission-v1/design.json',b=>['admission_logic_parent','switch_pair_parent','admit_pair_parent'].includes(b.part)||b.part?.startsWith('scan_decoder_gate_'));
claim('reset_park','control-reset-retire-v1/design.json',parts('logic','state','pending_feedback','pending_next','candidate_feedback','candidate_next','parked_feedback','parked_next'));
claim('scratch_reset','control-reset-scratch-v1/design.json',parts('logic','active_state','active_feedback','active_next'));
claim('alu_closure','control-reset-closure-v1/design.json',parts('logic','closure_state','lane0','lane1','lane2','lane3'));
claim('decision_samples_DONE','control-core-guards-v1/design.json',b=>['_advance_samples','_sample_clear'].some(x=>b.part?.endsWith(x))||b.part?.includes('_sample_clamp_')||['done_qualification','held_external_done','core_row6_inverse_cap'].includes(b.part));
claim('RF_held_status','control-rf-status-v1/design.json',b=>b.part?.startsWith('RF_'));
claim('architectural_zero','control-reset-zero-v1/design.json',parts('architectural_zero_logic','actual_clamp_returns','zero_active','zero_prepared','zero_transferred','zero_stop_after_full_transfer','local_A_fanout','local_B_fanout','preserved_cold_OPEN_enable','active_D','active_feedback','prepared_D','prepared_feedback','transferred_D','transferred_feedback','stop_D','stop_feedback','actual_A_held_NEXT_witness'));
claim('epoch','control-reset-epoch-v1/design.json',parts('epoch_logic','epoch_prepared','epoch_committed','epoch_settled','epoch_A_held_enable','epoch_A_fanout','epoch_B_fanout','prepared_D','prepared_feedback','committed_D','committed_feedback','settled_D','settled_feedback','enable_D','enable_feedback'));
claim('final_ACK','control-reset-final-v1/design.json',parts('final_reset_logic','final_withdraw','final_release','final_cleanup','internal_reset_complete','held_external_reset_ACK','final_A_fanout','final_B_fanout','arch_zero','epochs_zero','intents_zero','locks_closed','physical_reset_completion','actual_reset_exit_join','delivered_release_and_stage_clear','release_positive_injection','withdrawal_fanout','withdraw_D','withdraw_feedback','release_D','release_feedback','cleanup_D','cleanup_feedback','ack_D','ack_feedback','held_external_ACK_D'));
claim('shared_clock_scanner','startup-scan-v1/clock/design.json',()=>true,P(300,233,-248));
claim('RF_admission','register-startup-v1/distribution-v1/design.json',parts('admission_pair','not_admitted_inverter','not_ready_local_inverter','window_gates'),P(900,53,0));
const census=read('core-lane-colocation-v1/stores.json').stores,other=census.filter(s=>!priorKeys.has(K(s.position))),missing=other.filter(s=>!claims.has(K(s.position)));assert.equal(other.length,131);assert.equal(missing.length,0,'Unclaimed stores '+JSON.stringify(missing));for(const g of groups){g.stores=other.filter(s=>claims.get(K(s.position))===g.name);g.box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const b of g.blocks)for(const a of['x','y','z']){g.box.from[a]=Math.min(g.box.from[a],b.position[a]);g.box.to[a]=Math.max(g.box.to[a],b.position[a]);}g.internal=[];g.crossings=[];}
const gg=new Map(groups.map(g=>[g.name,g])),crossings=[];let inspected=0;for(const b of core.blocks){if(!active(b.block))continue;const target=claims.get(K(b.position));for(const q of inputs(world,b.position)){const source=claims.get(K(q));if(!source&&!target)continue;inspected++;const e={from:q,to:b.position,source_group:source??(priorKeys.has(K(q))?'already_placed':'outside'),target_group:target??(priorKeys.has(K(b.position))?'already_placed':'outside')};if(source===target){gg.get(source).internal.push(e);}else{crossings.push(e);if(source)gg.get(source).crossings.push(e);if(target)gg.get(target).crossings.push(e);}}}
const out={status:'remaining_131_actual_store_logic_cut_not_yet_relocated',groups,changes,absent,crossings,source_sha256:pins,actual_stores:131,cells:claims.size,complete_core:false,native_acceptance:false};writeFileSync(new URL('bodies.json',H),JSON.stringify(out)+'\n');writeFileSync(new URL('inventory.json',H),JSON.stringify({...out,groups:groups.map(({blocks,internal,crossings,...g})=>({...g,stores:g.stores.length,cells:blocks.length,internal_dependencies:internal.length,effective_crossings:crossings.length})),crossings:crossings.length},null,2)+'\n');console.log(JSON.stringify({cells:claims.size,stores:131,groups:groups.length,crossings:crossings.length,changes:changes.length,absent:absent.length}));
