import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z);
function bytes(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return b;}const read=n=>JSON.parse(bytes(n)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function scan(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,chunk=i,depth=0,quoted=false,escape=false,count=0,index=0;const accept=end=>{const s=buffer.subarray(chunk,end).toString();if(s.trim())for(const row of JSON.parse('['+s+']'))visit(row,index++);};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){accept(i);return index;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++count===4096){accept(i);chunk=i+1;count=0;}}throw Error('Unterminated stream');}
const memory=new Map(),memoryCells=scan(bytes('../../memory/fabric-colocation-v2/channel2-write-data-design.json'),v=>memory.set(K(v.position),v.block));assert.equal(memoryCells,1327786);assert.equal(memoryCells,memory.size);const panels=read('../../loader-bank-panels-v1/delta.json');for(const v of panels.blocks){assert(!memory.has(K(v.position)));memory.set(K(v.position),v.block);}assert.equal(panels.blocks.length,648);
bytes('../../memory/fabric-colocation-v2/channel2-write-data-source-manifest.json');bytes('../../loader-bank-panels-v1/source-manifest.json');bytes('../service-quiet-loader-link-v1/source-manifest.json');bytes('../service-witness-input-bindings-v1/source-manifest.json');
const loader=read('../service-quiet-loader-link-v1/connected-candidate.json'),bindings=read('../service-witness-input-bindings-v1/binding-contract.json'),scope=read('../reference-scope.json'),maskBodies=scope.blocks.filter(v=>/^loader\/runtime_new_request_mask_[0-7]$/.test(v.group)),maskLinks=scope.blocks.filter(v=>/^loader\/new_runtime_admission_mask_[1-7]$/.test(v.group));assert.equal(maskBodies.length,96);assert.equal(maskLinks.length,112);
const near=[];for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++)if(Math.abs(dx)+Math.abs(dy)+Math.abs(dz)<=2)near.push(P(dx,dy,dz));
function clear(rows,offset,map){for(const r of rows){const p=A(r.position,offset);if(map.has(K(p)))return{kind:'collision',point:p};for(const o of near)if(map.has(K(A(p,o))))return{kind:'near_foreign_cell',point:p,foreign:A(p,o)};}return null;}
const maskAlternatives=[];for(const z of [-48,-64,-80,-96,-112])for(const y of [-20,0,20,40])for(const x of [0,-40,40]){const offset=P(x,y,z),bad=clear([...maskBodies,...maskLinks],offset,memory),score=Math.abs(x)+Math.abs(y-(-40))+Math.abs(z-(-20));maskAlternatives.push({offset,bad,score});}
maskAlternatives.sort((a,b)=>a.score-b.score);const maskChosen=maskAlternatives.find(r=>!r.bad);assert(maskChosen,'No isolated actual mask body placement');const placedMasks=[...maskBodies,...maskLinks].map(v=>({...v,position:A(v.position,maskChosen.offset),original_position:v.position,composition_part:'preserved_mask_body_and_seven_local_input_links'}));for(const v of placedMasks)memory.set(K(v.position),v.block);
const alternatives=[];for(const z of [-240,-176,-112,272,400,528])for(const y of [-32,32,96,160,224])for(const x of [-160,0,160]){const offset=P(x,y,z);if(loader.blocks.some(v=>v.position.y+y>301||v.position.y+y< -78))continue;const bad=clear(loader.blocks,offset,memory);let score=0;for(const b of bindings.bindings){const target=A(b.witness_receiver_local,offset),src=b.current_effective_source??A(b.old_physical_pad,maskChosen.offset);score+=Math.abs(target.x-src.x)+Math.abs(target.y-src.y)+Math.abs(target.z-src.z);}const src=A(P(128,72,10),offset),maskInput=A(P(2,-4,-4),maskChosen.offset);score+=Math.abs(src.x-maskInput.x)+Math.abs(src.y-maskInput.y)+Math.abs(src.z-maskInput.z);for(const panel of panels.panels){const grant=A(P(90,72,10),offset);score+=Math.abs(grant.x-panel.grant.x)+Math.abs(grant.y-panel.grant.y)+Math.abs(grant.z-panel.grant.z);}alternatives.push({offset,bad,manhattan_all37_plus_mask_source_and_grants:score});}
alternatives.sort((a,b)=>a.manhattan_all37_plus_mask_source_and_grants-b.manhattan_all37_plus_mask_source_and_grants);const chosen=alternatives.find(r=>!r.bad);assert(chosen,'No isolated actual loader/service placement');
const placedLoader=loader.blocks.map(v=>({...v,local_position:v.position,position:A(v.position,chosen.offset),composition_part:'preserved_loader_service_parent'}));for(const v of placedLoader){assert(!memory.has(K(v.position)));memory.set(K(v.position),v.block);}
const replacements=Array.from({length:8},(_,i)=>{const position=P(5*i,-39,-26),before=memory.get(K(position));assert.deepEqual(before,{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});const after={id:'minecraft:comparator',properties:{facing:'north',mode:'subtract'}};return{position,before,after,mask:i};});
const output={status:'mutable_actual_shared_placement_selected_requires_routes_and_full_union_checks',memory_cells:memoryCells,panel_cells:648,loader_cells:loader.blocks.length,mask_body_cells:96,mask_local_input_link_cells:112,loader_translation:chosen.offset,mask_translation:maskChosen.offset,placed_loader:placedLoader,placed_masks:placedMasks,replacements,runtime_block:A(P(128,72,10),chosen.offset),mask_input:A(P(2,-4,-4),maskChosen.offset),mask_observations:Array.from({length:8},(_,i)=>({mask:i,source:A(P(2+5*i,1,-6),maskChosen.offset),source_isolator:A(P(1+5*i,1,-6),maskChosen.offset),receiver:P(5*i,-39,-26),witness_receiver:A(bindings.bindings.find(v=>v.name==='mask'+i).witness_receiver_local,chosen.offset)})),source_sha256:pins};
write('placement-alternatives.json',{maskAlternatives,loaderAlternatives:alternatives,selected:{mask:maskChosen,loader:chosen},note:'Manhattan scores are placement heuristics only. Actual routed cost and complete union screen still required; no density/savings claim.'});write('placement.json',output);console.log(JSON.stringify({loader:chosen,mask:maskChosen,cells:{memory:memoryCells,panels:648,loader:loader.blocks.length,mask:208},runtime_block:output.runtime_block,mask_input:output.mask_input}));
