import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{resolve}from'node:path';
import{makeAluMChoiceFanout}from'../../../hardware/full-gpu-alu-m-choice-fanout.mjs';import{makeAluQChoiceFanout}from'../../../hardware/full-gpu-alu-q-choice-fanout.mjs';import{makeAluCarryChoiceFanout}from'../../../hardware/full-gpu-alu-carry-choice-fanout.mjs';import{makeAluQAuxFanout}from'../../../hardware/full-gpu-alu-q-aux-fanout.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url)),prefix='artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v2/',parent='artifacts/full-gpu-layout-v1/alu-four-lane-v1/source-manifest.json',read=p=>readFileSync(resolve(root,p)),json=p=>JSON.parse(read(p)),sha=p=>createHash('sha256').update(read(p)).digest('hex'),enc=v=>JSON.stringify(v,null,2)+'\n';
const generators=[['design',makeAluMChoiceFanout],['q-design',makeAluQChoiceFanout],['carry-design',makeAluCarryChoiceFanout],['qaux-design',makeAluQAuxFanout]];
export function prepare({check=false}={}){
 assert.equal(sha(parent),'04c06c17d26cce4789203f90489265545f7ed4d003c18a2e0d53680e229aec0d');const files=new Set([parent]);for(const[p,h]of Object.entries(json(parent).source_sha256)){assert.equal(sha(p),h,'Frozen parent source '+p);files.add(p);}
 const groups=[];for(const[name,fn]of generators){const d=fn();assert.deepEqual(d,json(prefix+name+'.json'),'Exact regeneration '+name);groups.push({name,metrics:d.metrics,box:d.box,new_connections:d.connections,descent_blocks:d.descents.reduce((n,v)=>n+v.blocks,0)});}
 const selected=json(prefix+'qaux-design.json'),controller=json('artifacts/full-gpu-layout-v1/alu-control/initialized-feedback-v1/design.json'),blocks=new Map(selected.blocks.map(v=>[`${v.position.x},${v.position.y},${v.position.z}`,v.block]));const core_inputs=Object.fromEntries(Object.entries(controller.ports).filter(([,v])=>v.direction==='input'));
 for(const[n,p]of Object.entries(core_inputs))for(const b of p.bits)assert.equal(blocks.get(`${b.position.x},${b.position.y},${b.position.z}`)?.id,'minecraft:redstone_wire','Actual core receiving wire '+n);
 const commands=Object.keys(json('artifacts/full-gpu-layout-v1/alu-four-lane-v1/command-launch-draft.json').ports),done=new Set([...json('artifacts/full-gpu-layout-v1/alu-four-lane-v1/w-choice-height-matched.json').connections,...groups.flatMap(g=>g.new_connections)].map(c=>c.name));assert.equal(done.size,22);assert.equal(commands.length,41);
 const iface={status:'partial_drawn_physical_interconnect_not_functional_ALU',polarity:'active_high',bit_order:'lsb_first',controller_inputs:core_inputs,core_outputs:Object.fromEntries(['all_ready','any_fault','all_status_low'].map(k=>[k,selected.ports[k]])),lane_commands:Object.fromEntries([0,1,2,3].map(i=>['lane'+i,selected.ports['lane'+i+'_commands']])),delivered_commands:commands.filter(k=>done.has(k)),missing_commands:commands.filter(k=>!done.has(k)),internal_controller_fault_return_connected:false,core_input_producers_connected:false,lane_enable_mode_request_delivery_complete:false,data_OPEN_masks_complete:false,all_four_status_low_required_for_ack_drain:true,normal_fault_ack_drain_allowed:false,status_clear_is_generated_command:true,reset_clears_inactive_lanes:true,native_acceptance:false};
 const ip=prefix+'interface.json';if(check)assert.equal(read(ip).toString(),enc(iface));else writeFileSync(resolve(root,ip),enc(iface));
 for(const n of ['m-choice-fanout','q-choice-fanout','carry-choice-fanout','q-aux-fanout'])files.add('hardware/full-gpu-alu-'+n+'.mjs');files.add('hardware/full-gpu-signal-descent.mjs');
 for(const n of ['README.md','prepare.mjs','interface.json','check-all.mjs','checks.json','check-geometry.py','check-q-geometry.py','check-carry-geometry.py','check-qaux-geometry.py','check-connectivity.mjs','check-corruptions.py',...generators.map(([n])=>n+'.json')])files.add(prefix+n);
 const manifest={status:'offline_complete_W_M_Q_carry_Qaux_fanout_groups_partial_ALU',source_sha256:Object.fromEntries([...files].sort().map(p=>[p,sha(p)])),current_candidate:prefix+'qaux-design.json',parent_manifest_sha256:sha(parent),groups,metrics:selected.metrics,box:selected.box,commands_required:41,commands_physically_delivered:22,commands_missing:19,physical_destinations:88,distinct_sources:18,retained_lane_bits:228,retained_controller_bits:26,physical_data_OPEN_masks_complete:false,core_interfaces_complete:false,independent_full_geometry_review:false,native_calls:0,native_acceptance:false,missing:iface.missing_commands};
 const mp=prefix+'source-manifest.json';if(check)assert.equal(read(mp).toString(),enc(manifest));else writeFileSync(resolve(root,mp),enc(manifest));return{manifest_sha256:sha(mp),source_pins:files.size,blocks:selected.blocks.length,delivered_commands:22,remaining_commands:19,native_calls:0};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(prepare({check:process.argv.includes('--check')})));
