import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeScratchReset} from './prepare.mjs';
import {definition} from './logic.mjs';
import {makeMatrix} from '../control-lsu-v2/matrix.mjs';
import {screen} from '../control-reset-retire-v1/check-interactions.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
const d=makeScratchReset(),base=read('../control-reset-quiet-v1/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v]));assert.deepEqual(d,read('design.json'));
const changes=new Map(d.substitutions.map(v=>[K(v.position),v]));assert.equal(changes.size,1);for(const v of base.blocks){const changed=changes.get(K(v.position));if(changed){assert.deepEqual(changed.before,v.block);assert.deepEqual(changed.after,m.get(K(v.position)).block);}else assert.deepEqual(m.get(K(v.position))?.block,v.block,'Parent changed '+K(v.position));}
assert.deepEqual(m.get('-363,77,-184').block,{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});assert.equal(m.get('-363,77,-183').block.id,'minecraft:redstone_block');for(let power=0;power<=15;power++)assert.equal(Math.max(0,power-15),0);assert.deepEqual(d.ports.architectural_fault,base.ports.fault.fault_latched);assert.equal(d.connections.length,17);assert.equal(d.metrics.retained_bits,1036);
const def=definition(),matrix=makeMatrix(def),evaluate=v=>Object.fromEntries(def.outputs.map(out=>[out,def.products.some(t=>t.out===out&&Object.entries(t.literals).every(([n,w])=>!!v[n]===!!w))]));let cases=0,gates=0;
for(let mask=0;mask<2**def.inputs.length;mask++){const v=Object.fromEntries(def.inputs.map((n,i)=>[n,!!(mask&(1<<i))])),got=evaluate(v),want={active_D:!v.initialize&&!v.release_complete&&((v.service_ready&&!v.core_fault)||v.active),scratch_complete:v.active&&!v.initialize&&!v.release_complete&&v.lsu_ack&&v.alu_reset_wait&&v.alu_status_low&&![v.fault0,v.fault1,v.fault2,v.fault3].some(Boolean)&&v.closure&&!v.core_fault};assert.deepEqual(got,want);for(const t of matrix.products){let power=15;for(const g of t.gates){power=Math.max(0,power-(v[g.name]===!!g.want?0:15));gates++;}assert.equal(power>0,Object.entries(t.literals).every(([n,w])=>v[n]===!!w));}cases++;}
let initializationCases=0;for(let c=0;c<2;c++)for(let n=0;n<2;n++)for(const first of ['A','B']){let current=!!c,next=!!n;for(const phase of [first,...(first==='A'?['B']:['A','B'])]){if(phase==='A')next=evaluate({active:current,initialize:true}).active_D;else current=next;}assert.equal(current,false);assert.equal(next,false);initializationCases++;}
let state=false;for(const [inputs,expected]of [[{service_ready:true},true],[{},true],[{lsu_ack:true},true],[{release_complete:true},false]]){state=evaluate({...inputs,active:state}).active_D;assert.equal(state,expected);}
const all={active:true,lsu_ack:true,alu_reset_wait:true,alu_status_low:true,closure:true};assert(evaluate(all).scratch_complete);let guardRefusals=0;for(const name of ['lsu_ack','alu_reset_wait','alu_status_low','closure']){assert(!evaluate({...all,[name]:false}).scratch_complete);guardRefusals++;}for(const name of ['fault0','fault1','fault2','fault3','initialize','release_complete','core_fault']){assert(!evaluate({...all,[name]:true}).scratch_complete);guardRefusals++;}
// Injection lands on the exact original ALU reset route, after the isolated
// source and before its real receiving port. No other reset bus is joined.
const commit=read('../control-commit-v2/design.json'),alu=commit.routes.find(r=>r.name==='alu_reset_request'),inj=d.connections.find(c=>c.name==='scratch_reset_to_ALU');assert.deepEqual(inj.destination,P(1410,-37,14));assert(alu.path.some(p=>K(p)===K(inj.destination)));assert.deepEqual(commit.connections.find(c=>c.name===alu.name).destination,P(1422,-37,13));
for(const [name,p,driver,face]of [['ALU_RESET_WAIT',P(1415,-17,8),P(1415,-17,7),'north'],['all_ALU_status_low',P(2129,308,122),P(2128,308,122),'west'],['all_LSU_reset_ack',P(92,66,305),P(92,66,304),'north'],...Array.from({length:4},(_,i)=>['lane'+i+'_fault',P(1836+(i%2)*184,115+Math.floor(i/2)*124,-36),P(1835+(i%2)*184,115+Math.floor(i/2)*124,-36),'west'])]){assert.deepEqual(d.connections.find(c=>c.name===name).source,p);assert.deepEqual(m.get(K(driver)).block,{id:'minecraft:repeater',properties:{facing:face,delay:'1'}});}
// Actual pre-existing wire shape/step edges between all old cells stay intact.
const eligible=new Set(base.blocks.filter(v=>v.block.id==='minecraft:redstone_wire').map(v=>K(v.position)));let oldEdges=0;
function neighbors(p,map){const out=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(!eligible.has(K(q)))continue;if(y===1&&map.has(K(P(p.x,p.y+1,p.z))))continue;if(y===-1&&map.has(K(P(q.x,q.y+1,q.z))))continue;out.push(K(q));}return out.sort();}
for(const k of eligible){const p=old.get(k).position,a=neighbors(p,old);assert.deepEqual(neighbors(p,m),a,'Old wire graph changed '+k);oldEdges+=a.length;}
const r={status:'author_static_retained_scratch_reset_checks',...d.metrics,preserved_parent_cells:base.blocks.length-1,disabled_abort_receiver_substitutions:1,abort_input_power_cases:16,preserved_old_wire_edges:oldEdges,boolean_cases:cases,physical_product_gate_cases:gates,initialization_cases:initializationCases,missing_guard_refusals:guardRefusals,actual_completion_source_bindings:7,...screen(d),native_acceptance:false,far_closure_proven:false,reset_ack_proven:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({...r,taps:undefined}));
