import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeFront}from'./prepare.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=p=>P(-p.x,-p.y,-p.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
export function inspect(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(Object.keys(d.parents)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,contacts=0,sides=0,reps=0;
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;let p={...v.position,y:v.position.y-1};if(v.block.id==='minecraft:redstone_wall_torch')p=add(v.position,D[v.block.properties.facing]);assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const b=at(p);if(!b||b.block.id.endsWith('_concrete')||v.part===b.part&&parents.has(v.part))continue;if(dy&&b.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign wire '+v.part+' '+K(v.position)+' -> '+b.part+' '+K(p));contacts++;}
 for(const v of d.blocks.filter(v=>['minecraft:repeater','minecraft:comparator'].includes(v.block.id))){const delta=D[v.block.properties.facing];for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const b=at(add(v.position,side));if(b&&['minecraft:repeater','minecraft:comparator'].includes(b.block.id)&&!(v.part===b.part&&parents.has(v.part)))assert(allowed.has(pair(v.position,b.position)),'Foreign diode side '+K(v.position)+' '+K(b.position));sides++;}if(!parents.has(v.part)&&v.block.id==='minecraft:repeater'){const rear=add(v.position,neg(delta)),out=add(v.position,delta);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'New diode orientation '+K(v.position));reps++;}}
 for(const c of d.columns){for(let y=c.bottom;y<c.top;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2?'redstone_torch':'light_gray_concrete'));assert.equal(at(P(c.x,c.top,c.z))?.block.id,'minecraft:'+(c.wire_top?'redstone_wire':'redstone_torch'));}
 for(const y of[1,5])assert.equal(at(P(-38,y,91))?.block.properties.facing,'south','Intent actual lock direction');for(const y of[1,5])assert.deepEqual(at(P(-44,y,90))?.block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});assert.deepEqual(at(P(-26,1,90))?.block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});
 // Build one actual dust-capacity graph. All independent source outputs are
 // potential15, so this tests attenuation/forks only, never logic activation.
 const adj=new Map(),power=new Map();for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))adj.set(K(v.position),[]);const seed=p=>{if(adj.has(K(p)))power.set(K(p),15);};
 for(const v of d.blocks){const p=v.position,b=v.block;if(b.id==='minecraft:redstone_wire')for(const delta of dirs)for(const dy of[-1,0,1]){const q=add(p,delta);q.y+=dy;if(!adj.has(K(q)))continue;if(dy===1&&at({...p,y:p.y+1}))continue;if(dy===-1&&at({...q,y:p.y}))continue;adj.get(K(p)).push(K(q));}
 if(['minecraft:repeater','minecraft:comparator'].includes(b.id))seed(add(p,D[b.properties.facing]));
 if(['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id)){for(const delta of dirs)seed(add(p,delta));if(at({...p,y:p.y+1})?.block.id==='minecraft:light_gray_concrete')seed({...p,y:p.y+2});}}
 for(const p of Object.values(d.ports).filter(p=>p.direction==='input'))for(const b of p.bits)seed(b.position);
 const queue=[...power.keys()];for(let i=0;i<queue.length;i++){const key=queue[i],v=power.get(key)-1;if(v<=0)continue;for(const key2 of adj.get(key)??[])if((power.get(key2)??0)<v){power.set(key2,v);queue.push(key2);}}
 let rears=0,minRear=15;for(const v of d.blocks.filter(v=>!parents.has(v.part)&&['minecraft:repeater','minecraft:comparator'].includes(v.block.id))){const p=add(v.position,neg(D[v.block.properties.facing]));if(adj.has(K(p))){const n=power.get(K(p))??0;assert(n>0,'Unpowered possible rear '+K(v.position));rears++;minRear=Math.min(minRear,n);}}
 // Conservative new strong-solid source/sink pairs, not only dust adjacency.
 let mediated=0,crossMediated=0;for(const solid of d.blocks.filter(v=>v.block.id==='minecraft:light_gray_concrete')){const p=solid.position,src=[],dst=[];for(const delta of dirs){let v=at(add(p,neg(delta))),b=v?.block;if(b?.id==='minecraft:redstone_wire'||['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&JSON.stringify(D[b.properties.facing])===JSON.stringify(delta))src.push(v);v=at(add(p,delta));b=v?.block;if(b?.id==='minecraft:redstone_wire'||['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&JSON.stringify(D[b.properties.facing])===JSON.stringify(delta)||b?.id==='minecraft:redstone_wall_torch'&&JSON.stringify(D[b.properties.facing])===JSON.stringify(neg(delta)))dst.push(v);}
 const up=at({...p,y:p.y+1}),down=at({...p,y:p.y-1});if(up?.block.id==='minecraft:redstone_wire')src.push(up);if(down?.block.id==='minecraft:redstone_torch')src.push(down);if(['minecraft:redstone_wire','minecraft:redstone_torch'].includes(up?.block.id))dst.push(up);if(down?.block.id==='minecraft:redstone_wire')dst.push(down);
 for(const a of src)for(const b of dst){if(a===b||a.part===b.part&&parents.has(a.part))continue;mediated++;if(a.part===b.part)continue;crossMediated++;
 const ps=[a.part,b.part].sort().join('|');if(ps.startsWith('state_escape_')&&ps.includes('|state_tap_')){assert.equal(a.part.split('_').at(-1),b.part.split('_').at(-1));assert.equal(Math.abs(a.position.y-b.position.y),1);assert.equal(Math.abs(a.position.z-b.position.z),1);}
 else if(a.part.startsWith('operation_injection_')&&b.part==='operation_held_or'){assert.equal(a.position.x,63);assert.equal(b.position.x,64);assert.equal(b.position.y,a.position.y+1);}
 else assert(['intent_initialize_entry>intent_initialize','fetch_complete_rise_entry>fetch_complete_rise','decode_complete_entry>decode_complete_rise'].includes(a.part+'>'+b.part),'Foreign support power '+K(p)+' '+a.part+' -> '+b.part);
 }}
 assert.equal(crossMediated,20);
 // Every column's support source set is explicit, including the five OR taps.
 let columnSets=0;for(const c of d.columns){for(let y=c.bottom;y<c.top;y+=2){const p=P(c.x,y,c.z),got=[];for(const delta of dirs){const q=add(p,neg(delta)),b=at(q)?.block;if(b?.id==='minecraft:redstone_wire'||['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&JSON.stringify(D[b.properties.facing])===JSON.stringify(delta))got.push(K(q));}for(const[dy,id]of[[1,'minecraft:redstone_wire'],[-1,'minecraft:redstone_torch']]){const q=P(c.x,y+dy,c.z);if(at(q)?.block.id===id)got.push(K(q));}
 const want=[];if(y>c.bottom)want.push(K(P(c.x,y-1,c.z)));if(c.name==='operation_held_or'&&[21,29,37,45,53].includes(y))want.push(K(P(63,y,0)));if(y===c.bottom&&c.name!=='operation_held_or')want.push(K(P(c.x,y,c.z-1)));if(c.wire_top&&y===c.top-1)want.push(K(P(c.x,c.top,c.z)));assert.deepEqual(got.sort(),want.sort(),'Column source '+c.name+' '+K(p));columnSets++;}}
 return{blocks:d.blocks.length,supports,listed_cross_component_contacts:contacts,diode_side_faces:sides,new_directed_repeaters:reps,possible_positive_new_rears:rears,minimum_possible_rear_power:minRear,column_source_sets:columnSets,new_solid_mediated_pairs:mediated,cross_component_solid_mediated_pairs:crossMediated};}
const d=makeFront();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));const geometry=inspect(d);
let intentCases=0;for(let state=0;state<8;state++)for(let init=0;init<2;init++){let wireOr=false;for(let row=2;row<=6;row++)wireOr=wireOr||state===row;let level=0;for(let y=21;y<=56;y++){if(y%2===1&&[21,29,37,45,53].includes(y))level=Number(Boolean(level)||state===(y-5)/8);else if(y%2===0)level=1-level;}assert.equal(Boolean(level),wireOr);assert.equal(Number(wireOr&&!init),Number(state>=2&&state<=6&&!init));intentCases++;}
// Capture only during A, preserve intents through B and decoded transients.
const retainedIntent=(old,state,open,initialize)=>open?[Number(state===1&&!initialize),Number(state>=2&&state<=6&&!initialize)]:old;
let retainedCases=0;for(let original=0;original<8;original++)for(let target=0;target<8;target++){
 let held=retainedIntent([1,1],original,true,false),want=[Number(original===1),Number(original>=2&&original<=6)];assert.deepEqual(held,want);
 for(const transient of[0,1,7,target])held=retainedIntent(held,transient,false,false);assert.deepEqual(held,want,'Closed bank must not expose CURRENT transition decode');
 held=retainedIntent(held,target,true,false);assert.deepEqual(held,[Number(target===1),Number(target>=2&&target<=6)]);held=retainedIntent(held,target,true,true);assert.deepEqual(held,[0,0]);retainedCases++;}
// The explicit zero hazard: raw onehot FETCH on a 0->7 transition would make
// a request; the actually retained intent remains0 during the closed interval.
assert.equal(retainedIntent([0,0],1,false,false)[0],0);
let gateCases=0;for(let fetch=0;fetch<2;fetch++)for(let tail=0;tail<2;tail++){assert.equal(Math.max(0,15*fetch-15*tail)>0,Boolean(fetch&&!tail));gateCases++;}
let negatives=0;for(const f of[c=>c.blocks.find(v=>K(v.position)==='-38,1,91').block.properties.facing='north',c=>c.blocks.find(v=>K(v.position)==='63,37,0').block.properties.facing='east',c=>c.blocks.find(v=>K(v.position)==='-26,1,90').block.properties.mode='compare',c=>c.blocks=c.blocks.filter(v=>K(v.position)!=='160,0,-69')]){const c=structuredClone(d);f(c);assert.throws(()=>{inspect(c);for(const y of[1,5])assert.equal(c.blocks.find(v=>K(v.position)===K(P(-38,y,91)))?.block.properties.facing,'south');assert.equal(c.blocks.find(v=>K(v.position)==='-26,1,90').block.properties.mode,'subtract');});negatives++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const r={status:'author_offline_connected_frontend_checks_pass',...d.metrics,...geometry,parent_source_geometry_preserved:true,intent_boolean_cases:intentCases,closed_intent_state_transient_cases:retainedCases,tail_gate_cases:gateCases,corruptions_refused:negatives,source_sha256:{generator:sha('./prepare.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,limits:['Static contact/strength and abstract phase protocol, no Minecraft delay or glitch proof.','Intent captures require actual phase-A closure before any phase-B CURRENT transition; this is an unmeasured admission condition.','Initialization must blank external effects and fully flush fetch/IR tails before rearming.']};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r));
