import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeChannelPayload}from'../../../../hardware/memory-layout-channel-payload.mjs';
const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const d=makeChannelPayload(),saved=JSON.parse(readFileSync(new URL('design.json',import.meta.url))),parent=JSON.parse(readFileSync(new URL('../channel-retention-v1/design.json',import.meta.url))),m=new Map(d.blocks.map(v=>[K(v.position),v.block]));assert.equal(hash(d),hash(saved));assert.equal(m.size,d.blocks.length);
const rep=f=>({id:'minecraft:repeater',properties:{facing:f,delay:'1'}}),cmp=f=>({id:'minecraft:comparator',properties:{facing:f,mode:'subtract'}});
function core(mm){for(const v of parent.blocks)assert.deepEqual(mm.get(K(v.position)),v.block,'Parent changed '+K(v.position));
 for(const g of d.frontends){assert.equal(g.address_muxes.length,8);for(const c of g.address_muxes){assert.deepEqual(mm.get(K(c.read_gate)),cmp('east'));assert.deepEqual(mm.get(K(c.write_gate)),cmp('east'));assert.deepEqual(mm.get(K(c.read_mask)),rep('north'));assert.deepEqual(mm.get(K(c.write_mask)),rep('south'));assert.deepEqual(mm.get(K(c.output)),rep('east'));const field=c.bit<2?15+c.bit:c.bit-2;assert.equal(c.field,field);assert.equal(c.output.z,d.fields[field].z+2);}assert.deepEqual(mm.get(K(g.type_gate)),cmp('east'));}
 for(const c of d.bindings){const dst=parent.ports.candidate_payload.positions[c.channel*136+c.consumer*17+c.field];assert.deepEqual(c.destination,dst);assert.equal(mm.get(K(dst))?.id,W);assert.deepEqual(mm.get(K(c.source)),rep('east'));assert.deepEqual(mm.get(K(c.normalizer)),rep('south'));const p=c.normalizer;
  if(c.supportDrive){assert.equal(c.field,15);assert.deepEqual(c.supportDrive,P(p.x,p.y,p.z-1));assert.deepEqual(dst,P(p.x,p.y+1,p.z-1));assert.equal(mm.get(K(c.supportDrive))?.id,S);assert.equal(mm.get(K(P(p.x,p.y+1,p.z+1)))?.id,S,'Missing lower-tap cap');}
  else assert.deepEqual(dst,P(p.x,p.y,p.z-1));
 }
 for(const v of d.validReturns){assert.deepEqual(v.destination,parent.ports[v.kind+'_valid'].positions[v.consumer]);assert.deepEqual(mm.get(K(v.normalizer)),rep(v.kind==='read'?'north':'south'));}
}
core(m);assert.equal(d.bindings.length,544);assert.equal(d.validReturns.length,16);assert.equal(d.fanout.length,544);for(const[name,width]of Object.entries({read_valid:8,write_valid:8,read_address:64,write_address:64,write_data:64}))assert.equal(d.ports[name].width,width);assert(!d.ports.candidate_payload);
let support=0,steps=0;for(const v of d.blocks){const b=v.block,p=v.position;if([S,'minecraft:redstone_block'].includes(b.id))continue;let q=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const[x,z]=D[b.properties.facing];q=P(p.x+x,p.y,p.z+z);}assert.equal(m.get(K(q))?.id,S);support++;}
for(const rt of d.routes)for(let i=0;i<rt.path.length;i++){const p=rt.path[i],b=m.get(K(p));assert(b);if(i){const a=rt.path[i-1];assert.equal(Math.abs(a.x-p.x)+Math.abs(a.z-p.z),1);assert(Math.abs(a.y-p.y)<=1);steps++;}if(b.id==='minecraft:repeater'){const[x,z]=D[b.properties.facing];if(i)assert.deepEqual(rt.path[i-1],P(p.x-x,p.y,p.z-z),rt.name+' rear');if(i+1<rt.path.length)assert.deepEqual(rt.path[i+1],P(p.x+x,p.y,p.z+z),rt.name+' front');}else assert.equal(b.id,W);}
// Independent read-first truth table versus the actual normalized subtract
// branches and OR collector; no running memory contents are supplied by this.
let cases=0;for(const g of d.frontends)for(const field of g.address_muxes)for(let rv=0;rv<2;rv++)for(let wv=0;wv<2;wv++)for(let ra=0;ra<2;ra++)for(let wa=0;wa<2;wa++){const expected=rv?ra:wa,read=Math.max(15*ra-15*(1-rv),0)>0,write=Math.max(15*wa-15*rv,0)>0;assert.equal(Number(read||write),expected);assert.equal(Number(Math.max(15*wv-15*rv,0)>0),Number(!!wv&&!rv));cases++;}
let negatives=0;const bad=[[d.frontends[0].address_muxes[0].read_mask,rep('south')],[d.frontends[7].type_gate,cmp('north')],[d.bindings[0].normalizer,rep('north')],[d.bindings.at(-1).source,null],[d.validReturns[3].normalizer,null],[parent.blocks[0].position,null]];const cap=d.bindings.find(v=>v.supportDrive).normalizer;bad.push([P(cap.x,cap.y+1,cap.z+1),null]);for(const[p,v]of bad){const mm=new Map(m);v?mm.set(K(p),v):mm.delete(K(p));assert.throws(()=>core(mm));negatives++;}
const occupied=new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`));
const out={status:'offline_original_channel_payload_geometry_logic_checks_pass',...d.metrics,parent_positions_preserved:parent.blocks.length,supports:support,route_steps:steps,occupied_chunk_columns:occupied.size,read_first_bit_cases:cases,negative_cases:negatives,complete_data_memory:false,native_acceptance:false,limits:'Exact geometry, directed endpoints and settled read-first selection only; no native electrical/timing proof. Backend lifecycle and bank/consumer routes remain missing.'};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
