// Whole subgroup effective input, support, strength, function and exact cut checks.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{evaluate,K}from'../../dispatch-external-bindings-v1/transport-functions.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},P=(x,y,z)=>({x,y,z});function read(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return JSON.parse(b);}
const d=read('connected-candidate.json'),base=read('body-placement.json'),func=read('source-functions.json'),scope=read('../reference-scope.json'),allCuts=read('../actual-cuts.json'),w=new Map(d.blocks.map(v=>[K(v.position),v.block])),old=new Map([...scope.blocks,...scope.foreign_context].map(v=>[K(v.position),v.block])),orig=new Map(base.blocks.map(v=>[K(v.original_position),v])),at=new Map(base.blocks.map(v=>[K(v.position),v]));assert.equal(w.size,d.blocks.length);assert.equal(base.blocks.length,5231);assert.equal(d.new_cells.length,342);assert.equal(d.connections.length,3);
const edges=new Set(),routeAt=new Set();for(const r of d.routes)for(let i=0;i<r.path.length;i++){routeAt.add(K(r.path[i]));if(i){edges.add(K(r.path[i-1])+'>'+K(r.path[i]));edges.add(K(r.path[i])+'>'+K(r.path[i-1]));}}
let bodyReceivers=0,bodyInputs=0,allReceivers=0,allInputs=0,cableInputs=0;for(const v of d.blocks){const k=K(v.position);if(v.body)assert.deepEqual(v,base.blocks.find(b=>K(b.position)===k));if(!active(v.block))continue;allReceivers++;const actual=inputs(w,v.position).map(K).sort();allInputs+=actual.length;
 if(v.body){bodyReceivers++;const expected=inputs(old,v.original_position).filter(p=>orig.has(K(p))).map(p=>K(orig.get(K(p)).position));bodyInputs+=expected.length;for(const c of d.connections)if(K(c.destination)===k)expected.push(K(c.normalizer));assert.deepEqual(actual,[...new Set(expected)].sort(),'Altered actual body input '+k);}
 else{assert(routeAt.has(k));for(const p of actual)assert(edges.has(p+'>'+k),'New undeclared cable input '+p+'>'+k);cableInputs+=actual.length;}
}
// Every inherited support including floor and wall torch supports remains real.
const direction={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};let supports=0;for(const v of d.blocks){const p=v.position,b=v.block;let support=null;if(['minecraft:redstone_wire','minecraft:repeater','minecraft:comparator','minecraft:redstone_torch','minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const t=direction[b.properties.facing];support=P(p.x+t.x,p.y,p.z+t.z);}if(support){assert(w.get(K(support))?.id.endsWith('_concrete'),'Missing actual support '+K(p));supports++;}}
const graph=evaluate(w,new Set(d.added.filter(v=>active(v.block)).map(v=>K(v.position)))),pairs=[],negatives=[],boundCuts=new Map();let minimumRear=15;
for(const c of d.connections){const o=func.selected.find(o=>'local_'+o.name===c.name),r=d.routes.find(r=>r.name===c.name);assert(o);assert.deepEqual(c.source,o.new_source);assert.deepEqual(c.destination,o.new_destination);assert.deepEqual(graph.get(c.normalizer),{roots:[c.source],table:2});let power=15;for(let i=1;i<r.path.length;i++){const p=r.path[i],b=w.get(K(p));assert(inputs(w,p).some(q=>K(q)===K(r.path[i-1])));if(b.id==='minecraft:redstone_wire'){power--;assert(power>0);}else if(b.id==='minecraft:repeater'){assert(power>0);minimumRear=Math.min(minimumRear,power);power=15;}else assert.fail('Unexpected route device');}
 for(const endpoint of ['source_isolator','normalizer']){const mw=new Map(w),k=K(c[endpoint]),before=mw.get(k);mw.set(k,{...before,properties:{...before.properties,facing:{east:'west',west:'east',north:'south',south:'north'}[before.properties.facing]}});if(endpoint==='normalizer')assert(!inputs(mw,c.destination).some(p=>K(p)===k));else assert.notDeepEqual(evaluate(mw,new Set(d.added.filter(v=>active(v.block)).map(v=>K(v.position)))).get(c.normalizer),{roots:[c.source],table:2});negatives.push({route:c.name,case:'reverse_actual_'+endpoint});}
 if(c.receiver_delivery==='strongly_powered_existing_support'){const mw=new Map(w);mw.delete(K(c.receiving_anchor));assert(!inputs(mw,c.destination).some(p=>K(p)===K(c.normalizer)));negatives.push({route:c.name,case:'remove_actual_strong_receiver_support'});}
 const joins=func.full_incident_cuts.flatMap((cut,i)=>(K(cut.source)===K(o.source)&&cut.target_group==='loader/'+o.name||K(cut.target)===K(o.target)&&cut.source_group==='loader/'+o.name)?[i]:[]);assert.equal(joins.length,2);for(const i of joins)boundCuts.set(i,c.name);pairs.push({name:c.name,original_source:o.source,original_receiver:o.target,source:c.source,receiver:c.destination,normalizer:c.normalizer,receiver_delivery:c.receiver_delivery,truth_table:2,points:r.path.length,new_cells:d.new_cells.filter(v=>v.part===c.name).length,cut_indices:joins});
}
assert.equal(boundCuts.size,6);const metrics=blocks=>{const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const v of blocks)for(const a of ['x','y','z']){box.from[a]=Math.min(box.from[a],v.position[a]);box.to[a]=Math.max(box.to[a],v.position[a]);}return{cells:blocks.length,box,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1])),occupied_chunk_columns:new Set(blocks.map(v=>Math.floor(v.position.x/16)+','+Math.floor(v.position.z/16))).size};};
pins['artifacts/full-gpu-layout-v1/loader-program-colocation-v1/control-owner-v1/check.mjs']=createHash('sha256').update(readFileSync(fileURLToPath(import.meta.url))).digest('hex');
const report={status:'exact_loader_control_owner_subgroup_passes_full_static_checks',metrics:{body_cells:base.blocks.length,new_cells:d.new_cells.length,complete_cells:d.blocks.length,retained_loader_protocol_states:1,bodyReceivers,bodyInputs,allReceivers,allInputs,cableInputs,supports,route_vertices:d.routes.reduce((n,r)=>n+r.path.length,0),minimum_conditional_repeater_rear:minimumRear,original_incident_cuts:func.full_incident_cuts.length,resolved_incident_cuts:boundCuts.size,pending_incident_cuts:func.full_incident_cuts.length-boundCuts.size,negative_cases:negatives.length,old_same_scope:metrics(func.old_comparable_blocks),current_same_scope:metrics(d.blocks),saved_same_scope_cells:func.old_comparable_cells-d.blocks.length},actual_new_transport_graph:graph.metrics,pairs,negative_cases:negatives,source_sha256:pins,limits:['Only this exact control+one-owner+three-join scope is compared. All ROM, loader-bank interfaces and other routes remain excluded from the placement.','Source functions are from retained held producer boundaries; matrix semantics and SR scheduling/state convergence remain inherited and unproven physically.','Conditional power assumes asserted held body outputs. No old timing transfers; setup/hold, pulse width, reset/admission/drain ordering and native execution remain open.','Coordinates are local to this candidate; no whole-layout assembly transform is assigned.'],native_acceptance:false,complete_loader_program:false};
writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({coordinate_frame:'loader_control_owner_template_local',assembly_transform:null,ports:base.ports,mapping:Object.fromEntries(base.blocks.map(v=>[K(v.original_position),{position:v.position,body:v.body,block:v.block}])),source_sha256:pins},null,2)+'\n');
writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');writeFileSync(new URL('remaining-cuts.json',H),JSON.stringify({loader_control:func.full_incident_cuts.map((v,i)=>({...v,index:i,status:boundCuts.has(i)?'bound_by_actual_checked_owner_join':'pending',route:boundCuts.get(i)})),all_loader_program_external:allCuts.external,all_loader_program_between_groups:allCuts.between_groups,source_sha256:pins},null,2)+'\n');console.log(JSON.stringify(report.metrics));
