// Retain exact current control/state cells; move owner beside its producer outputs.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{evaluate,K}from'../../dispatch-external-bindings-v1/transport-functions.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={};function read(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return JSON.parse(b);}const scope=read('../reference-scope.json'),body=read('../loader-control-body.json'),interfaces=read('../interfaces.json'),cuts=read('../actual-cuts.json');
const names=['retained_owner_to_logic','loader_set_to_owner','loader_clear_to_owner'],oldRoutes=scope.blocks.filter(v=>names.includes(v.group.replace('loader/',''))),oldWorld=new Map([...scope.blocks,...scope.foreign_context].map(v=>[K(v.position),v.block])),func=evaluate(oldWorld,new Set(oldRoutes.filter(v=>active(v.block)).map(v=>K(v.position))));
const transforms={logic:{x:400,y:-16,z:-695},owner:{x:584,y:1,z:-692}},move=(p,t)=>({x:p.x+t.x,y:p.y+t.y,z:p.z+t.z}),blocks=body.blocks.map(v=>{const family=/^loader\/load_owner/.test(v.group)?'owner':'logic';return{position:move(v.position,transforms[family]),original_position:v.position,block:v.block,body:v.group,family};}),index=new Map(blocks.map(v=>[K(v.original_position),v])),selected=[];
for(const old of interfaces.loader.connections.filter(c=>names.includes(c.name))){const e=func.get(old.arrival);assert.deepEqual(e,{roots:[old.source],table:2});assert(inputs(oldWorld,old.destination).some(p=>K(p)===K(old.arrival)));assert(index.has(K(old.source))&&index.has(K(old.destination)));selected.push({name:old.name,source:old.source,target:old.destination,cut_source:old.arrival,immediate_source:old.arrival,old_route_function:e,required_new_function:'positive_single_source',new_source:index.get(K(old.source)).position,new_destination:index.get(K(old.destination)).position});}
assert.equal(selected.length,3);const ports=Object.fromEntries(Object.entries(interfaces.loader.ports.loader).map(([name,port])=>[name,{...port,bits:port.bits.map(bit=>({...bit,original_position:bit.position,position:index.get(K(bit.position))?.position??null}))}]));assert(Object.values(ports).every(v=>v.bits.every(b=>b.position)));
pins['artifacts/full-gpu-layout-v1/loader-program-colocation-v1/control-owner-v1/prepare.mjs']=createHash('sha256').update(readFileSync(fileURLToPath(import.meta.url))).digest('hex');
writeFileSync(new URL('body-placement.json',H),JSON.stringify({status:'provisional_source_exact_loader_control_owner_placement',blocks,added:[],connections:[],routes:[],new_branch_sources:[],body_transforms:transforms,metrics:{body_cells:blocks.length,retained_protocol_states:1},ports,source_sha256:pins})+'\n');
writeFileSync(new URL('source-functions.json',H),JSON.stringify({status:'three_actual_original_owner_join_functions_positive',selected,old_transport_metrics:func.metrics,old_route_cells:oldRoutes.length,old_comparable_cells:oldRoutes.length+body.blocks.length,old_comparable_blocks:[...body.blocks,...oldRoutes],full_incident_cuts:cuts.loader_control,source_sha256:pins,limits:['The loader SR owner and control matrix are retained exactly; this proves only the three transport functions.','All other original incident inputs/outputs remain required. No warm/cold state, event or native claim.']})+'\n');console.log(JSON.stringify({body_cells:blocks.length,old_route_cells:oldRoutes.length,old_graph:func.metrics,functions:selected.length}));
