// Actual routed OR truth and retained bank-state/phase qualification, without event simulation.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{loadBase,pins,read,H}from'./frame.mjs';import{K,P}from'../allocation-route.mjs';import{backwardCone}from'../settled-network.mjs';import{makeSettledEvaluator}from'../settled-bank-network.mjs';import{inputs}from'../cut-inputs.mjs';
const base=loadBase(),world=base.world,d=read('delta.json'),checks=read('checks.json'),sources=read('qualified-current-sources.json');assert.equal(checks.status,'ready_collectors_complete_shared_static_passed');for(const r of d.new_cells){assert(!world.has(K(r.position)));world.set(K(r.position),r.block);}let collectorCases=0,qualifiedCases=0,maxEvents=0;const collectorResults=[],qualifiedResults=[],mutations=[];
for(const row of checks.collector_cones){const evaluate=makeSettledEvaluator(world,row.cone,row.roots,{eventLimit:2000000}),truth=[];for(let mask=0;mask<256;mask++){const r=evaluate(new Map(row.roots.map((p,i)=>[K(p),mask>>i&1?15:0]))),level=r.power.get(K(row.output))??0;assert.equal(level,mask?15:0);truth.push({mask,level,events:r.events});maxEvents=Math.max(maxEvents,r.events);collectorCases++;}collectorResults.push({channel:row.channel,roots:row.roots,output:row.output,cone_devices:row.cone.length,truth});console.log(JSON.stringify({phase:'collector_or8',channel:row.channel,cases:256}));
 const roots=sources.rows.flatMap(r=>r.roots.filter(p=>['active','tail','reset','is_write','owner'+row.channel].includes(p.name)).map(p=>({...p,bank:r.bank})));assert.equal(roots.length,20);const stops=roots.map(r=>r.position),cone=backwardCone(world,row.output,stops);for(const r of roots)assert(cone.some(p=>K(p)===K(r.position)));const ev=makeSettledEvaluator(world,cone,stops,{eventLimit:2000000});const patterns=[];
 for(let bank=0;bank<4;bank++)for(let mask=0;mask<32;mask++)patterns.push({kind:'single_bank_all5_boundary_bits',bank,mask,values:roots.map((r,i)=>r.bank===bank?(mask>>(i%5)&1):0)});
 let seed=0x641385;for(let n=0;n<64;n++){const bits=[];for(let i=0;i<20;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;bits.push(seed>>>30&1);}patterns.push({kind:'multi_bank_deterministic',index:n,values:bits});}
 const levels=[];for(const p of patterns){const r=ev(new Map(roots.map((s,i)=>[K(s.position),p.values[i]?15:0]))),bankExpected=[];for(let bank=0;bank<4;bank++){const v=Object.fromEntries(roots.map((s,i)=>[s.bank===bank?s.name:'outside',p.values[i]]));bankExpected.push(!!v.active&&!!v.tail&&!v.reset&&!!v['owner'+row.channel]);}const expected=bankExpected.some(Boolean),actual=r.power.get(K(row.output))??0;assert.equal(actual,expected?15:0,'End-to-end retained qualification ch'+row.channel);levels.push({...p,level:actual,bankExpected,events:r.events});maxEvents=Math.max(maxEvents,r.events);qualifiedCases++;}qualifiedResults.push({channel:row.channel,roots,output:row.output,cone_devices:cone.length,levels,equation:'OR_b(ACTIVE[b] AND final_tail[b] AND !reset_blocked[b] AND retained_owner[b,c]); typed pair OR retains each actual is_write path, and agrees for both access types.'});console.log(JSON.stringify({phase:'qualified_sources_through_actual_collector',channel:row.channel,cases:patterns.length,cone:cone.length}));
}
const reverse={west:'east',east:'west',north:'south',south:'north'};
function mutate(position,change,channel,source,name){const old=world.get(K(position));assert(old);const r=checks.collector_cones[channel],values=new Map(r.roots.map(p=>[K(p),K(p)===K(source)?15:0]));try{const next=change(old);if(next)world.set(K(position),next);else world.delete(K(position));const cone=backwardCone(world,r.output,r.roots),ev=makeSettledEvaluator(world,cone,r.roots,{eventLimit:2000000}),actual=ev(values).power.get(K(r.output))??0;assert.notEqual(actual,15,'Actual mutation failed to change asserted transport '+name);mutations.push({position,name,channel,source,expected:15,actual});}finally{world.set(K(position),old);}}
for(const p of d.source_pairs){for(const[kind,pos,source]of[['read_tap',p.read_tap,p.read],['write_tap',p.write_tap,p.write]])mutate(pos,b=>({...b,properties:{...b.properties,facing:reverse[b.properties.facing]}}),p.channel,source,kind);mutate(p.tap,b=>({...b,properties:{...b.properties,facing:reverse[b.properties.facing]}}),p.channel,p.read,'pair_output_normalizer');}
for(const c of d.collectors){const src=d.source_pairs.find(p=>p.channel===c.channel&&p.bank===0).read;mutate(c.tap,b=>({...b,properties:{...b.properties,facing:reverse[b.properties.facing]}}),c.channel,src,'collector_output_normalizer');mutate(P(c.base.x,c.base.y+3,c.base.z),()=>undefined,c.channel,src,'remove_actual_positive_column_torch');const support=P(c.top.x,c.top.y,c.top.z),old=world.get(K(support));world.delete(K(support));assert(!inputs(world,c.tap).some(p=>p.x===c.top.x&&p.y===c.top.y-1&&p.z===c.top.z));world.set(K(support),old);mutations.push({position:support,name:'remove_actual_output_strong_solid',channel:c.channel,refused:'effective last-torch input to output normalizer is lost'});}
assert.equal(mutations.length,60);const hash=n=>createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex');const out={status:'actual_ready_collectors_numeric_and_qualified_source_composition_passed',collectorCases,collectorObservations:collectorCases,qualifiedCases,qualifiedObservations:qualifiedCases,maxEvents,collectorResults,qualifiedResults,actual_new_geometry_mutations:mutations,actual_static_arrival_mutations:checks.actual_arrival_mutations.length,total_new_actual_mutations:mutations.length+checks.actual_arrival_mutations.length,source_sha256:{...pins,...Object.fromEntries(['check-levels.mjs','delta.json','checks.json','qualified-current-sources.json','source-repair-reconciliation.json','../settled-bank-network.mjs','../settled-network.mjs','../cut-inputs.mjs'].map(n=>[n,hash(n)]))},limits:['Each bank qualification has separately passed all256 held assignments and is byte/input unchanged in the full assembly. All256 typed-source assignments per channel prove the collector OR. This is a modular Boolean/level proof, not exhaustive joint retained-state evolution.','Additional192 full source-cone patterns per channel include every single-bank five-boundary-bit assignment and64 deterministic multi-bank patterns. Storage Q/phase outputs are explicit clamps.','No ownership capture, READY/data arrival ordering, delayed flush event bound, reset protocol, clock selection, or native acceptance.']};writeFileSync(new URL('levels.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({...out,collectorResults:undefined,qualifiedResults:undefined,actual_new_geometry_mutations:mutations.length,source_sha256:undefined}));
