// Actual pair ORs, positive shared collectors, and isolated receiving stubs.
import assert from'node:assert/strict';import{writeFileSync,readFileSync}from'node:fs';import{createHash}from'node:crypto';import{loadBase,pins,read,H}from'./frame.mjs';import{P,K,V,F}from'../allocation-route.mjs';import{inputs,active}from'../cut-inputs.mjs';import{backwardCone}from'../settled-network.mjs';import{makeSettledEvaluator}from'../settled-bank-network.mjs';
const assignment=read('../next-bank-ready-assignment.json'),classification=read('qualified-current-sources.json'),reconciliation=read('source-repair-reconciliation.json');assert.equal(reconciliation.status,'all12_ready_cone_refreshes_match_frozen28_repair_witness_and_corrected_original_matches_current');const base=loadBase(),map=base.world,added=[],pairs=[],collectors=[],connections=[],refusals=[];const S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',R='minecraft:repeater',T='minecraft:redstone_torch',U=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),B=(id,properties)=>({id,...properties?{properties}:{}}),hash=n=>createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex');
function buildRows(){const rows=[];const put=(p,id,properties)=>rows.push({position:p,block:B(id,properties)}),dev=(p,id,properties)=>{put(U(p),S);put(p,id,properties);};return{rows,put,wire:p=>dev(p,W),rep:(p,d)=>dev(p,R,{facing:F[d],delay:'1'})};}
function screen(rows,sources=[],allowed=[]){const proposed=new Map();for(const r of rows){if(map.has(K(r.position)))return{reason:'occupied',position:r.position};assert(!proposed.has(K(r.position)));proposed.set(K(r.position),r.block);}const component=new Map([...proposed,...sources.map(p=>[K(p),map.get(K(p))])]),after={get:k=>proposed.get(k)??map.get(k)},wanted=new Set(allowed.map(([a,b])=>K(a)+'>'+K(b))),affected=new Map();for(const r of rows)for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++){const p=P(r.position.x+dx,r.position.y+dy,r.position.z+dz);if(active(after.get(K(p))))affected.set(K(p),p);}
 for(const[k,p]of affected){const actual=inputs(after,p).map(K).sort();if(proposed.has(k)){const expected=inputs(component,p).map(K).sort();if(JSON.stringify(actual)!==JSON.stringify(expected))return{reason:'new_foreign_input',position:p,actual,expected};}else{const expected=[...new Set([...inputs(map,p).map(K),...allowed.filter(([a,b])=>K(b)===k).map(([a])=>K(a))])].sort();if(JSON.stringify(actual)!==JSON.stringify(expected))return{reason:'changed_parent_input',position:p,actual,expected};}}
 return null;}
function commit(rows,part){for(const r of rows){assert(!map.has(K(r.position)));map.set(K(r.position),r.block);added.push({...r,part});}}
for(let bank=0;bank<4;bank++)for(let channel=0;channel<4;channel++){
 const pair=assignment.bindings.filter(b=>b.bank===bank&&b.channel===channel),rs=pair.find(b=>b.kind==='read_ready').current_source,ws=pair.find(b=>b.kind==='write_ready').current_source;assert.equal(ws.z-rs.z,4);assert.equal(ws.y,rs.y);const q=buildRows(),readTap=step(rs,'east'),writeTap=step(ws,'east');q.rep(readTap,'east');q.rep(writeTap,'east');for(let z=rs.z;z<=ws.z;z++)q.wire(P(rs.x+2,rs.y,z));const tap=P(rs.x+3,rs.y,rs.z+2),start=P(rs.x+4,rs.y,rs.z+2);q.rep(tap,'east');q.wire(start);const failure=screen(q.rows,[rs,ws]);assert.equal(failure,null,'Pair OR contact '+JSON.stringify({bank,channel,failure}));commit(q.rows,'bank'+bank+'_channel'+channel+'_typed_pair_or');
 const component=new Map([...q.rows.map(r=>[K(r.position),r.block]),[K(rs),map.get(K(rs))],[K(ws),map.get(K(ws))]]),cone=backwardCone(component,start,[rs,ws]),ev=makeSettledEvaluator(component,cone,[rs,ws]);for(let mask=0;mask<4;mask++)assert.equal(ev(new Map([[K(rs),mask&1?15:0],[K(ws),mask&2?15:0]])).power.get(K(start))??0,mask?15:0);pairs.push({bank,channel,read:rs,write:ws,read_tap:readTap,write_tap:writeTap,tap,start,source_direction:'east',bank_cut_indices:pair.map(b=>b.bank_cut_index)});
}
for(let channel=0;channel<4;channel++){
 const dst=assignment.groups[channel].backend_ready_destination,L=176*Math.floor(channel/2),X=480*(channel%2),lo=L-7,hi=L+9;let chosen;
 for(const z of[180,188,196,204,212,220,228,236]){if(chosen)break;for(const dx of[-16,-24,-32,-40,-48,16,24,32,40]){const x=X+dx,q=buildRows();for(let y=lo;y<=hi;y++)q.put(P(x,y,z),(y-lo)%2?T:S);const ins=Array.from({length:4},(_,bank)=>{const receiving=P(x,lo+4*bank,z),arrival=P(x-1,receiving.y,z),end=P(x-2,receiving.y,z);q.rep(arrival,'east');q.wire(end);return{bank,receiving,destination:P(x,receiving.y+1,z),arrival,end,arrival_direction:'east'};});const top=P(x,hi,z),tap=P(x+1,hi,z),start=P(x+2,hi,z);q.rep(tap,'east');q.wire(start);const fail=screen(q.rows);if(fail){refusals.push({kind:'collector',channel,x,z,failure:fail});continue;}chosen={channel,base:P(x,lo,z),top,inputs:ins,tap,start,source_direction:'east',rows:q.rows};break;}}
 assert(chosen,'No isolated collector channel'+channel);commit(chosen.rows,'channel'+channel+'_ready_or4');const cm=new Map(chosen.rows.map(r=>[K(r.position),r.block])),roots=chosen.inputs.map(i=>i.end),cone=backwardCone(cm,chosen.start,roots),ev=makeSettledEvaluator(cm,cone,roots);for(let mask=0;mask<16;mask++)assert.equal(ev(new Map(roots.map((p,i)=>[K(p),mask>>i&1?15:0]))).power.get(K(chosen.start))??0,mask?15:0);delete chosen.rows;collectors.push(chosen);
 let endStub;for(const dir of['south','east','west','north']){const q=buildRows(),arrival=step(dst,dir,-1),end=step(dst,dir,-2);q.rep(arrival,dir);q.wire(end);const fail=screen(q.rows,[dst],[[arrival,dst]]);if(fail){refusals.push({kind:'backend_arrival',channel,dir,failure:fail});continue;}endStub={destination:dst,arrival,end,arrival_direction:dir};commit(q.rows,'channel'+channel+'_backend_arrival');break;}assert(endStub,'No backend READY arrival channel'+channel);
 for(const p of pairs.filter(p=>p.channel===channel)){const i=chosen.inputs[p.bank];connections.push({name:'bank'+p.bank+'_channel'+channel+'_ready',kind:'qualified_bank_ready_pair',channel,bank:p.bank,source:p.tap,start:p.start,tap:p.tap,source_direction:p.source_direction,...i});}
 connections.push({name:'channel'+channel+'_backend_ready',kind:'actual_backend_ready',channel,source:P(chosen.top.x,chosen.top.y-1,chosen.top.z),tap:chosen.tap,start:chosen.start,source_direction:chosen.source_direction,...endStub});
}
const out={status:'drawn_isolated32_typed_taps16_pair_ORs4_shared_collectors_and20_cable_endpoints_only',base_cells:base.world.size-added.length,new_cells:added,source_pairs:pairs,collectors,connections,placement_refusals:refusals,source_sha256:{...pins,...Object.fromEntries(['prepare.mjs','frame.mjs','qualified-current-sources.json','source-repair-reconciliation.json','../allocation-route.mjs','../cut-inputs.mjs','../settled-bank-network.mjs'].map(n=>[n,hash(n)]))},limits:['Stub components pass exact affected-input isolation and standalone held OR truth. Twenty physical cables remain undrawn.','No bank READY cut is closed or credited until full real collector/delivery geometry and complete union/numeric/mutation checks pass.']};writeFileSync(new URL('placement.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({status:out.status,new_cells:added.length,pairs:pairs.length,collectors,connections:connections.length,refusals:refusals.length}));
