// Draw twenty physical supported, refreshed paths against the exact shared assembly.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{loadBase,pins,read,H}from'./frame.mjs';import{P,K,V,F,searchPath,refreshIndices}from'../allocation-route.mjs';
const base=loadBase(),placement=read('placement.json'),map=new Map(base.rows.map(r=>[K(r.position),r])),added=structuredClone(placement.new_cells),connections=structuredClone(placement.connections),edges=[],U=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),hash=n=>createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex');
for(const r of added){assert(!map.has(K(r.position)));map.set(K(r.position),r);}const cacheFile=new URL('paths.json',H),cache=existsSync(cacheFile)?JSON.parse(readFileSync(cacheFile)):{};
function put(p,block,part){assert(!map.has(K(p)),'New route overlaps '+K(p));const r={position:p,block,part};map.set(K(p),r);added.push(r);}
function device(p,id,properties,part){put(U(p),{id:'minecraft:light_gray_concrete'},part);put(p,{id,...properties?{properties}:{}},part);}
const reserve=c=>[...Array.from({length:4},(_,i)=>step(c.start,c.source_direction,i)),...Array.from({length:4},(_,i)=>step(c.end,c.arrival_direction,-i))],reserved=connections.flatMap(reserve);
for(const c of connections){let path=cache[c.name]?.path;if(path){assert.deepEqual(cache[c.name].source,c.start);assert.deepEqual(cache[c.name].destination,c.end);}else{const ignore=[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(U),...reserve(c)],found=searchPath(map,c.start,c.end,{ignore,reserved,forbidden:[P(c.arrival.x,c.arrival.y-2,c.arrival.z)],limit:4000000});path=found.path;cache[c.name]={source:c.start,destination:c.end,path,expanded:found.expanded};writeFileSync(cacheFile,JSON.stringify(cache)+'\n');console.log(JSON.stringify({name:c.name,points:path.length,expanded:found.expanded}));}
 const indices=refreshIndices(path),rs=new Set(indices);for(let i=1;i<path.length-1;i++){const p=path[i],n=path[i+1],dir=Object.keys(V).find(d=>p.x+V[d][0]===n.x&&p.z+V[d][1]===n.z);assert(dir);device(p,rs.has(i)?'minecraft:repeater':'minecraft:redstone_wire',rs.has(i)?{facing:F[dir],delay:'1'}:undefined,c.name);}for(let i=1;i<path.length;i++)edges.push({from:path[i-1],to:path[i],route:c.name});c.path=path;c.refresh_indices=indices;
 writeFileSync(new URL('in-progress-delta.json',H),JSON.stringify({status:'partial_uncredited',complete_routes:connections.filter(c=>c.path).length,placement_sha256:hash('placement.json'),new_cells:added})+'\n');
}
const out={status:'drawn_bank_ready_collectors_requires_full_checks',base_cells:base.world.size,new_cells:added,source_pairs:placement.source_pairs,collectors:placement.collectors,connections,edges,placement_sha256:hash('placement.json'),metrics:{cells:base.world.size+added.length,added_cells:added.length,typed_bank_sources:32,pair_ors:16,positive_shared_collectors:4,cables:connections.length,path_vertices:connections.reduce((n,c)=>n+c.path.length,0),new_state:0},source_sha256:{...pins,...Object.fromEntries(['route.mjs','frame.mjs','placement.json','paths.json','original-recovery.json','qualified-current-sources.json','source-repair-reconciliation.json','../allocation-route.mjs'].map(n=>[n,hash(n)]))},limits:['Actual32 source qualifications and original collector functions are separately recovered. New complete geometry is not accepted until whole union support/input/strength, numeric and corruption checks pass.','READY must be ordered relative to qualified response data and capture closure. No timing/state/native proof.']};writeFileSync(new URL('delta.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify(out.metrics));
