// Independently bound ledger delta: only transfer290/cut500/program21 may change.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`;
function read(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return JSON.parse(b);}
read('../program-global-delivery-v1/source-manifest.json','d6699fad6b40aa6ccefc7313cccf5907da67774300816ae5eab6020d98e3911d');
const before=read('../dispatcher-service-colocation-v1/remaining-cuts.json'),program=read('../program-service-composition-v1/remaining-cuts.json'),after=read('../program-global-delivery-v1/remaining-cuts.json'),delta=read('../program-global-delivery-v1/delta.json'),endpoint=read('../program-global-delivery-v1/endpoint-map.json'),c=delta.connections[0],changes=[];
for(const [field,n,selected]of[['transfers',352,290],['effective_cut_ledger',661,500],['direct_foreign_boundaries',48,-1]]){assert.equal(before.dispatch[field].length,n);assert.equal(after.dispatch[field].length,n);for(let i=0;i<n;i++){const a=before.dispatch[field][i],b=after.dispatch[field][i];if(i!==selected)assert.deepEqual(b,a,field+'/'+i);else{for(const[k,v]of Object.entries(a))if(!['status','reconciliation'].includes(k))assert.deepEqual(b[k],v,field+'/'+i+'/'+k);assert.notEqual(b.status,a.status);assert.deepEqual(b.shared_actual_producer,c.root);assert.deepEqual(b.shared_target,c.destination);assert.equal(b.shared_route,c.name);changes.push({ledger:field,index:i,old_status:a.status,new_status:b.status});}}}
assert.deepEqual(after.dispatch.transfers[290].shared_arrival_normalizer,c.normalizer);assert.deepEqual(after.dispatch.effective_cut_ledger[500].shared_source,c.normalizer);assert.deepEqual(after.service,before.service);
assert.equal(after.program.length,44);assert.equal(program.program.length,44);for(let i=0;i<44;i++){const a=program.program[i],b=after.program[i];if(i!==21)assert.deepEqual(b,a,'program/'+i);else{for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v);assert.notEqual(b.status,a.status);assert.deepEqual(b.shared_source,c.root);assert.deepEqual(b.shared_global_receiver,c.destination);assert.deepEqual(b.shared_arrival_normalizer,c.normalizer);assert.deepEqual(b.shared_departure_isolator,c.source_isolator);assert.equal(b.shared_route,c.name);assert.deepEqual(a.original_selected_world.source,endpoint.original_binding.old_connection.source);assert.deepEqual(a.original_selected_world.target,{x:-972,y:-47,z:845});changes.push({ledger:'program',index:21,old_status:a.status,new_status:b.status});}}
assert.deepEqual(endpoint.connection,c);assert.equal(after.dispatch.transfers.filter(r=>r.status==='external_source_transfer_pending').length,16);assert.equal(after.dispatch.direct_foreign_boundaries.filter(r=>r.status==='pending').length,31);assert.equal(after.program.filter(r=>r.status==='pending_external_master_connection').length,42);
const counts={};for(const r of after.dispatch.transfers)counts[r.status]=(counts[r.status]??0)+1;assert.deepEqual(after.dispatch.transfer_counts,counts);
const self=new URL('ledger-review.mjs',H);pins[fileURLToPath(self).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(self)).digest('hex');
const report={status:'passed_exact_program_global_ledger_delta',metrics:{transfers:352,effective_cuts:661,direct_foreign_cuts:48,program_cuts:44,changed_records:3,global_incoming_pending:16,direct_foreign_pending:31,program_pending:42},changes,source_sha256:pins,limits:['Only transfer290/cut500/program21 changes. All other entries and the complete service ledger are exactly unchanged.','Parent witness/input counts are historical scope; subsequent ACTIVE and commit-phase freezes have separate ledgers. No state or timing closure is inferred.']};writeFileSync(new URL('ledger-receipt.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
