// Independent bounded review: direct source loading, actual cold context,
// complete input differential, and a separate directed-network strength solver.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function insert(map,rows,{same=false}={}){for(const r of rows){const k=K(r.position);if(map.has(k)){assert(same,'Duplicate cell '+k);assert.deepEqual(map.get(k),r.block);}else map.set(k,r.block);}}
function scanBlocks(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const part=buffer.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){visit(r);count++;}};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated blocks');}
function cone(world,end,root){const roots=Array.isArray(root)?root:[root],stop=new Set(roots.map(K)),seen=new Map(),queue=Array.isArray(end)?[...end]:[end];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(world.get(k)),'Missing actual dependency '+k);seen.set(k,p);if(!stop.has(k))queue.push(...inputs(world,p));}for(const r of roots)assert(seen.has(K(r)),'Source absent from cone '+K(r));return [...seen.values()];}
function network(world,positions,root){
 const roots=Array.isArray(root)?root:[root],index=new Map(positions.map((p,i)=>[K(p),i])),rootIndices=new Set(roots.map(p=>index.get(K(p))));assert(!rootIndices.has(undefined));
 const rows=positions.map(p=>({p,b:world.get(K(p))})),incoming=positions.map(()=>[]),outgoing=positions.map(()=>[]);let edges=0;
 for(let i=0;i<rows.length;i++){assert([W,R,C,T,WT,'minecraft:redstone_block'].includes(rows[i].b.id),'Unexpected transport device '+rows[i].b.id+' '+K(rows[i].p));if(rootIndices.has(i))continue;const deps=inputs(world,rows[i].p);if(rows[i].b.id===R){const v=D[rows[i].b.properties.facing];assert(deps.every(q=>(q.x-rows[i].p.x)*v.x+(q.z-rows[i].p.z)*v.z<0),'Unmodeled side lock');}for(const q of deps){const j=index.get(K(q));assert.notEqual(j,undefined,'Foreign source '+K(q));incoming[i].push(j);outgoing[j].push(i);edges++;}}
 const visited=new Uint8Array(rows.length),order=[];for(let i=0;i<rows.length;i++)if(!visited[i]){visited[i]=1;const stack=[[i,0]];while(stack.length){const r=stack.at(-1);if(r[1]<outgoing[r[0]].length){const j=outgoing[r[0]][r[1]++];if(!visited[j]){visited[j]=1;stack.push([j,0]);}}else{order.push(r[0]);stack.pop();}}}
 const assigned=new Uint8Array(rows.length);let components=0,wireLoops=0;for(let n=order.length-1;n>=0;n--){const i=order[n];if(assigned[i])continue;const members=[i];assigned[i]=1;for(let at=0;at<members.length;at++)for(const j of incoming[members[at]])if(!assigned[j]){assigned[j]=1;members.push(j);}components++;if(members.length>1||outgoing[i].includes(i)){assert(members.every(j=>rows[j].b.id===W),'Nonwire transport feedback');wireLoops++;}}
 function power(strength){const values=new Uint8Array(rows.length),waiting=new Uint8Array(rows.length).fill(1),queue=rows.map((_,i)=>i);for(const p of roots)values[index.get(K(p))]=typeof strength==='number'?strength:strength.get(K(p))??0;let events=0;for(let at=0;at<queue.length;at++){const i=queue[at];waiting[i]=0;if(rootIndices.has(i))continue;assert(++events<1000000,'Nonconvergent network');let value=0;for(const j of incoming[i])value=Math.max(value,values[j]-(rows[i].b.id===W&&rows[j].b.id===W?1:0));if(rows[i].b.id===R)value=value>0?15:0;else if([T,WT].includes(rows[i].b.id))value=value>0?0:15;else if(rows[i].b.id==='minecraft:redstone_block')value=15;else if(rows[i].b.id===C){const d=D[rows[i].b.properties.facing],rear=incoming[i].filter(j=>(rows[j].p.x-rows[i].p.x)*d.x+(rows[j].p.z-rows[i].p.z)*d.z<0),side=incoming[i].filter(j=>!rear.includes(j)),a=Math.max(0,...rear.map(j=>values[j])),b=Math.max(0,...side.map(j=>values[j]));value=rows[i].b.properties.mode==='subtract'?Math.max(0,a-b):a>=b?a:0;}if(value!==values[i]){values[i]=value;for(const j of outgoing[i])if(!waiting[j]){waiting[j]=1;queue.push(j);}}}return {values,get:p=>values[index.get(K(p))]??0,events};}
 return {power,metrics:{devices:rows.length,edges,components,torch_vertices:rows.filter(r=>[T,WT].includes(r.b.id)).length,wire_conductance_components:wireLoops,nonwire_feedback_components:0},minimumRear(powers,subset){return Math.min(...rows.flatMap((r,i)=>r.b.id===R&&(!subset||subset.has(K(r.p)))?[Math.max(0,...incoming[i].map(j=>powers.values[j]))]:[]));}};
}
const frozen=read('../program-global-delivery-v1/source-manifest.json','d6699fad6b40aa6ccefc7313cccf5907da67774300816ae5eab6020d98e3911d');
const oldRoutes=read('../master-loader-control-routes-v1/design.json'),scope=read('../dispatch-global-colocation-v1/reference-scope.json'),oldProgram=read('../loader-program-colocation-v1/reference-scope.json'),interfaces=read('../loader-program-colocation-v1/interfaces.json'),bindings=read('../dispatch-external-bindings-v1/bindings.json'),parent=read('../dispatch-global-colocation-v8-dcr-cold-v1/connected-candidate.json');
const originalRoot=P(-973,-47,845),originalTarget=P(-1100,-38,550),originalArrival=P(-1101,-38,550),b=bindings.incoming.find(r=>r.transfer_index===290);assert.equal(b.old_connection.name,'global_program_quiet');assert.deepEqual(b.old_connection.source,originalRoot);assert.deepEqual(b.old_connection.destination,originalTarget);assert.deepEqual(b.old_connection.normalizer,originalArrival);
const discovery=new Map();insert(discovery,[...scope.blocks,...scope.foreign_context,...oldRoutes.blocks],{same:true});const sourceRow=[...oldProgram.blocks,...oldProgram.foreign_context].find(r=>K(r.position)===K(originalRoot));assert(sourceRow);insert(discovery,[sourceRow],{same:true});
const candidate=cone(discovery,originalTarget,originalRoot),want=new Set();for(const p of candidate)for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)want.add(K(A(p,P(x,y,z))));
const actualOld=new Map(),scanned=scanBlocks(bytes('../memory/master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f'),r=>{if(want.has(K(r.position)))insert(actualOld,[r]);});
const selected=read('../dispatch-global-colocation-v1/selected-config.json'),globalInstance=selected.instances.find(r=>r.name==='global'),globalBody=read('../global-command-assembly-v3/design.json',globalInstance.sha256);insert(actualOld,globalBody.blocks.map(r=>({position:A(r.position,globalInstance.translation),block:r.block})).filter(r=>want.has(K(r.position))),{same:true});insert(actualOld,oldRoutes.blocks.filter(r=>want.has(K(r.position))),{same:true});
const oldCone=cone(actualOld,originalTarget,originalRoot);assert.deepEqual(oldCone.map(K).sort(),candidate.map(K).sort());for(const p of oldCone){assert.deepEqual(actualOld.get(K(p)),discovery.get(K(p)));if(K(p)!==K(originalRoot))assert.deepEqual(inputs(actualOld,p).map(K).sort(),inputs(discovery,p).map(K).sort());}
const oldNet=network(actualOld,oldCone,originalRoot),originalCases=[0,15].map(n=>{const v=oldNet.power(n);assert.equal(v.get(originalTarget),n);return{source:n,arrival:v.get(originalArrival),receiver:v.get(originalTarget),minimum_rear:n?oldNet.minimumRear(v):null};});
// Rebuild the entire accepted candidate from exact individual geometry snapshots.
const memory=read('../memory/fabric-colocation-v2/channel3-write-data-design.json'),panels=read('../loader-bank-panels-v1/delta.json'),program=read('../program-service-composition-v1/new-program-obstacles.json'),programQuiet=read('../program-service-composition-v1/cable-delta.json'),masks=read('../loader-program-colocation-v1/service-mask-memory-composition-v1/composed-delta.json'),address0=read('../memory/fabric-colocation-v2/channel0-address-delta.json'),address1=read('../memory/fabric-colocation-v2/channel1-address-delta.json'),owner=read('../loader-program-colocation-v1/service-owner-open-delivery-v1/delta.json'),payload=read('../loader-program-colocation-v1/service-payload-open-delivery-v1/delta.json'),dispatch=read('../dispatcher-service-colocation-v1/placement.json'),serviceQuiet=read('../dispatcher-service-colocation-v1/delta.json');
const base=new Map();insert(base,[...memory.blocks,...panels.blocks,...program.blocks,...programQuiet.blocks,...masks.placed_loader,...masks.placed_masks,...masks.new_cells,...address0.blocks,...address1.blocks,...owner.new_cells,...payload.new_cells,...dispatch.blocks,...serviceQuiet.new_cells]);for(const r of masks.replacements){assert.deepEqual(base.get(K(r.position)),r.before);base.set(K(r.position),r.after);}assert.equal(base.size,2000594);
const delta=read('../program-global-delivery-v1/delta.json','a5b19f5f9da13117c0a79b6269d0df8fb04a2be811acc651133234935d46c35d'),world=new Map(base);insert(world,delta.new_cells);assert.equal(world.size,2002964);assert.equal(delta.connections.length,1);assert.equal(delta.routes.length,1);
const c=delta.connections[0],root=P(-529,-16,-197),target=P(268,110,-576),arrival=P(268,110,-577),loaderTarget=P(-54,-31,-176);assert.deepEqual(c.root,root);assert.deepEqual(c.destination,target);assert.deepEqual(c.normalizer,arrival);
const programBody=read('../program-rom-colocation-v1/quiet-connected-v1/connected-candidate.json'),programLocal=new Map(programBody.blocks.map(r=>[K(r.position),r])),placedSource=program.blocks.find(r=>K(r.position)===K(root)),sourceIdentity=programLocal.get(K(placedSource.local_position));assert.deepEqual(A(sourceIdentity.original_position,interfaces.program_translation),originalRoot);assert.deepEqual(A(sourceIdentity.position,program.translation),root);assert.deepEqual(sourceIdentity.block,actualOld.get(K(originalRoot)));assert.deepEqual(sourceIdentity.block,world.get(K(root)));
const receiverIdentity=parent.blocks.find(r=>r.original_position&&K(r.original_position)===K(originalTarget));assert(receiverIdentity);assert.equal(receiverIdentity.body,'global/sample0');assert.deepEqual(A(receiverIdentity.position,dispatch.translation),target);assert.deepEqual(receiverIdentity.block,actualOld.get(K(originalTarget)));
const edges=new Set(),path=delta.routes[0].path;assert.deepEqual(path[0],root);assert.deepEqual(path.at(-1),target);for(let i=1;i<path.length;i++){assert(inputs(world,path[i]).some(p=>K(p)===K(path[i-1])));edges.add(K(path[i-1])+'>'+K(path[i]));edges.add(K(path[i])+'>'+K(path[i-1]));}
const newKeys=new Set(delta.new_cells.filter(r=>active(r.block)).map(r=>K(r.position)));let receivers=0,supports=0,actualInputs=0,priorInputs=0,cableInputs=0,changedOldReceivers=0;
for(const [key,block]of world){const [x,y,z]=key.split(',').map(Number),p=P(x,y,z);let support;if(block.id===WT)support=A(p,D[block.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(block.id))support=P(x,y-1,z);if(support){assert(solid(world.get(K(support))),'Missing support '+key);supports++;}if(!active(block))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;if(base.has(key)){const expected=inputs(base,p).map(K);priorInputs+=expected.length;if(key===K(target)){expected.push(K(arrival));changedOldReceivers++;}assert.deepEqual(actual,[...new Set(expected)].sort(),'Retained input changed '+key);}else{assert(newKeys.has(key));for(const q of actual)assert(edges.has(q+'>'+key),'Undeclared cable contact '+q+'>'+key);cableInputs+=actual.length;}}
assert.equal(changedOldReceivers,1);
const currentCone=cone(world,target,root),currentNet=network(world,currentCone,root);assert.equal(currentCone.length,path.length);assert(currentCone.every(p=>K(p)===K(root)||K(p)===K(target)||newKeys.has(K(p))));const strengthCases=[];let high;
for(let strength=0;strength<=15;strength++){const v=currentNet.power(strength),expected=strength?15:0;assert.equal(v.get(arrival),expected);assert.equal(v.get(target),expected);strengthCases.push({source:strength,arrival:v.get(arrival),receiver:v.get(target)});if(strength===15)high=v;}
const minimum=currentNet.minimumRear(high,newKeys);assert.equal(minimum,5);
// Recover gate boundaries from the actual retained program candidate's three routes.
assert.deepEqual(programBody.connections.map(c=>c.name),['local_active','local_normal_tail','local_reset_blocked']);const gateRoots=programBody.connections.map(c=>A(c.source,program.translation));for(let i=0;i<3;i++){assert.deepEqual(world.get(K(gateRoots[i])),programLocal.get(K(programBody.connections[i].source)).block);}
const gateTargets=[root,loaderTarget,target],gateCone=cone(world,gateTargets,gateRoots),gateNet=network(world,gateCone,gateRoots),gateCases=[];
for(let bits=0;bits<8;bits++){const v=gateNet.power(new Map(gateRoots.map((p,i)=>[K(p),(bits>>i&1)*15]))),outputs=gateTargets.map(p=>v.get(p));assert.deepEqual(outputs,Array(3).fill(bits===0?15:0));gateCases.push({source_bits:bits,outputs});}
const negatives=[],opposite={east:'west',west:'east',north:'south',south:'north'};
for(const r of delta.new_cells.filter(r=>r.block.id===R)){const key=K(r.position);world.set(key,{...r.block,properties:{...r.block.properties,facing:opposite[r.block.properties.facing]}});let rejected=false;try{const n=network(world,cone(world,target,root),root);rejected=n.power(15).get(target)!==15;}catch{rejected=true;}assert(rejected,'Reversed repeater not rejected');world.set(key,r.block);negatives.push({kind:'reverse_actual_repeater',position:r.position});const support=P(r.position.x,r.position.y-1,r.position.z),before=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),before);negatives.push({kind:'delete_actual_repeater_support',position:support});}
const gateComparators=gateCone.filter(p=>world.get(K(p))?.id===C);assert.equal(gateComparators.length,3);
for(const p of gateComparators){const before=world.get(K(p));assert.equal(before.properties.mode,'subtract');world.set(K(p),{...before,properties:{...before.properties,mode:'compare'}});let rejected=false;try{const n=network(world,cone(world,gateTargets,gateRoots),gateRoots);for(let bits=0;bits<8;bits++){const v=n.power(new Map(gateRoots.map((p,i)=>[K(p),(bits>>i&1)*15])));if(gateTargets.some(p=>v.get(p)!==(bits===0?15:0)))rejected=true;}}catch{rejected=true;}assert(rejected);world.set(K(p),before);negatives.push({kind:'subtract_to_compare_actual_quiet_gate',position:p});}
bytes('review.mjs');bytes('../memory/fabric-colocation-v2/cut-inputs.mjs');
write('receipt.json',{status:'passed_independent_actual_program_global_quiet_delivery',metrics:{base_cells:base.size,cable_cells:delta.new_cells.length,total_cells:world.size,receivers,supports,actual_inputs:actualInputs,preserved_inputs:priorInputs,new_cable_inputs:cableInputs,changed_existing_receivers:changedOldReceivers,path_vertices:path.length,source_strength_cases:16,original_binary_cases:2,gate_assignments:8,gate_output_observations:24,current_minimum_repeater_rear:minimum,actual_block_mutations:negatives.length},original:{cold_cells_streamed:scanned,actual_context_cells:actualOld.size,source:originalRoot,arrival:originalArrival,receiver:originalTarget,graph:oldNet.metrics,cases:originalCases},current:{source:root,receiver:target,arrival,graph:currentNet.metrics,cases:strengthCases},gate:{held_sources:gateRoots,outputs:gateTargets,graph:gateNet.metrics,cases:gateCases},negative_cases:negatives,source_sha256:pins,limits:['Independent full-map reconstruction, old-source streaming and numeric/SCC solver. The normalized physical-input helper is shared and conditional, not independent Minecraft physics.','Only held quiet ACTIVE/normal-tail/reset-blocked source levels and their actual gate/cables are reviewed. Retained program state transitions, pulse widths, sampling and phase timing remain open.','Only accepted root scope2,002,964cells is screened here; later ACTIVE/address2/commit-phase unions have separate author receipts. No complete-machine or native claim.']});
console.log(JSON.stringify({status:'passed',cells:world.size,receivers,supports,actualInputs,old_graph:oldNet.metrics,current_graph:currentNet.metrics,gate_graph:gateNet.metrics,minimum,mutations:negatives.length}));
