import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeRegisterAddressSelect}from'../../../../hardware/full-gpu-register-address-select.mjs';import{makeRegisterDataSelector}from'../../../../hardware/full-gpu-register-data-selector.mjs';import{possibleStrengths}from'../connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.names),edges=new Set(d.edges.map(e=>pair(e.from,e.to)));assert.equal(m.size,d.blocks.length);let preserved=0,supports=0,reps=0,contacts=0;
 const template=makeRegisterDataSelector().blocks.filter(v=>v.position.y<=13&&!['fill_column','fill_input'].includes(v.part)&&!([6,7].includes(v.position.x)&&v.position.z===0));for(const p of d.parents)for(const v of template){assert.deepEqual(at(add(v.position,p.origin))?.block,v.block);preserved++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;assert.equal(at({...v.position,y:v.position.y-1})?.block.id,'minecraft:light_gray_concrete');supports++;}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const dd=D[v.block.properties.facing],rear=add(v.position,P(-dd.x,0,-dd.z)),front=add(v.position,dd);assert(edges.has(pair(rear,v.position))&&edges.has(pair(v.position,front)),'Reversed repeater '+K(v.position));for(const delta of dirs.filter(q=>q.x*dd.x+q.z*dd.z===0)){const b=at(add(v.position,delta));assert(!b||b.block.id.endsWith('_concrete'),'Possible side lock');}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const q=at(p);if(!q||q.block.id.endsWith('_concrete'))continue;if(v.part===q.part&&parents.has(v.part))continue;if(dy&&q.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(edges.has(pair(v.position,p)),'Unlisted external contact '+pair(v.position,p));contacts++;}
 const capacity=possibleStrengths({...d,connections:[]});assert.equal(capacity.failed.length,0);let words=0;
 for(let enables=0;enables<(1<<d.sources);enables++)for(let data=0;data<(1<<(4*d.sources));data++){let got=0;for(let b=0;b<4;b++){let value=0;for(let i=0;i<d.sources;i++){const y=1+4*b,z=20*i;assert.equal(at(P(2,y,z)).block.properties.mode,'subtract');let mask=!!(enables>>i&1);for(let yy=1;yy<=y;yy+=2){assert.equal(at(P(2,yy,z-3)).block.id,'minecraft:redstone_torch');mask=!mask;}value|=Math.max(0,((data>>(4*i+b)&1)?15:0)-(mask?15:0))>0?1:0;}got|=value<<b;}
 let want=0;for(let i=0;i<d.sources;i++)if(enables>>i&1)want|=data>>(4*i)&15;assert.equal(got,want);words++;}
 return{...d.metrics,retained_template_cells:preserved,support_checks:supports,new_directed_repeaters:reps,listed_contacts:contacts,actual_dust_capacity:capacity,settled_word_vectors:words};}
const reports=[];let negatives=0;for(const sources of[2,3]){const d=makeRegisterAddressSelect({sources});assert.deepEqual(d,JSON.parse(readFileSync(new URL(sources===3?'./read.json':'./write.json',import.meta.url))));reports.push(check(d));for(const mutation of[c=>{c.blocks.find(v=>K(v.position)==='13,1,4').block.properties.facing='east';},c=>{c.blocks=c.blocks.filter(v=>K(v.position)==='14,5,8');},c=>{c.blocks.find(v=>K(v.position)==='2,13,20').block.properties.mode='compare';}]){const c=structuredClone(d);mutation(c);assert.throws(()=>check(c));negatives++;}}
const hash=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const result={status:'offline_read_and_write_address_selector_checks_pass',reports,corruption_refusals:negatives,sources:{generator:hash('../../../../hardware/full-gpu-register-address-select.mjs'),checker:hash('./check.mjs'),read:hash('./read.json'),write:hash('./write.json')},native_acceptance:false,complete_gpu_layout:false,limits:['Positive-source capacity plus settled gate arithmetic only, not game propagation.','No selected source yields zero; multiple selects physically OR their words and are forbidden during admitted microprogram sampling.','No implicit decode, hidden register field, host-selected address or file fanout included.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
