import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeDispatchCounterPhased}from'../../../hardware/full-gpu-dispatch-counter-phased.mjs';import{makeDispatchCounter}from'../../../hardware/full-gpu-dispatch-counter.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');const parent=makeDispatchCounter(),original=new Set(parent.blocks.map(v=>K(v.position))),d=makeDispatchCounterPhased();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to)));assert.equal(m.size,d.blocks.length);for(const v of parent.blocks)assert.deepEqual(at(v.position)?.block,v.block);let support=0,contacts=0,phaseCases=0;
 const fresh=d.blocks.filter(v=>!original.has(K(v.position)));for(const v of fresh){if(v.block.id.endsWith('_concrete'))continue;const q=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(q)?.block.id,'minecraft:light_gray_concrete');support++;}
 for(const c of d.columns){for(let y=c.bottom;y<=c.top;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+(y%2===0?'light_gray_concrete':'redstone_torch'));
 for(const input of[0,1]){let solidPower=!!input;for(let y=c.bottom;y<=c.top;y+=2){if(y%8===0){const tap=at(P(c.x+1,y,c.z));assert.deepEqual(tap?.block,{id:'minecraft:redstone_wall_torch',properties:{facing:'east'}});const branch=!solidPower;assert.equal(branch,!!input,'Column phase inversion');const rep=at(P(c.x+3,y,c.z));assert.deepEqual(rep?.block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.equal(at(P(c.x+2,y,c.z))?.block.id,'minecraft:redstone_wire');assert.equal(at(P(c.x+4,y,c.z))?.block.id,'minecraft:redstone_wire');phaseCases++;}solidPower=!solidPower;}}}
 for(const v of fresh.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign wire contact '+pair(v.position,p));contacts++;}
 for(const v of fresh.filter(v=>v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],rear=add(v.position,neg(delta)),front=add(v.position,delta);assert(allowed.has(pair(rear,v.position))&&allowed.has(pair(front,v.position)));for(const s of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete'),'Foreign repeater side');}}
 assert.equal(d.connections.length,16);for(const c of d.connections)assert.deepEqual(add(c.normalizer,P(1,0,0)),c.destination);return{preserved_parent_cells:parent.blocks.length,new_support_checks:support,new_wire_contact_checks:contacts,settled_phase_receiver_cases:phaseCases};}
const checks=check(d);let negatives=0;for(const mut of[c=>{c.blocks.find(v=>K(v.position)==='-1,0,3').block.properties.facing='east';},c=>{c.blocks=c.blocks.filter(v=>K(v.position)!=='-4,23,3');}]){const c=structuredClone(d);mut(c);assert.throws(()=>check(c));negatives++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const r={status:'offline_common_dispatch_counter_phase_checks_pass',...d.metrics,...checks,corruption_refusals:negatives,sources:{generator:sha('../../../hardware/full-gpu-dispatch-counter-phased.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_calls:0,world_mutations:0,native_acceptance:false,complete_gpu_layout:false,limits:d.missing};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r));
