// Actual old/current local any-owner OR functions, before new geometry.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{H,ROOT,K,read,loadFrame,pins}from'./frame.mjs';import{inputs}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{backwardCone,makeSettledEvaluator}from'../../memory/fabric-colocation-v2/settled-network.mjs';import{checkFeedback}from'../service-mask-memory-composition-v1/feedback.mjs';
const {world}=loadFrame({includeForeign:false}),endpoints=read('../service-commit-phase-delivery-v1/endpoint-map.json'),recovered=read('../service-witness-input-bindings-v1/source-functions.json'),selected=endpoints.pending_witness_bindings.filter(v=>v.role==='any_owner'),records=[],P=(x,y,z)=>({x,y,z}),want=new Set();assert.equal(selected.length,4);
for(const binding of selected){const prior=recovered.bindings.find(v=>v.name===binding.name);for(const r of prior.original.cone)for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)want.add(K(P(r.position.x+x,r.position.y+y,r.position.z+z)));}
const old=new Map(),file=new URL('../../memory/master-cold-compatible-v2/design.json',H),bytes=readFileSync(file),sha=createHash('sha256').update(bytes).digest('hex');assert.equal(sha,'364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');pins[fileURLToPath(file).slice(fileURLToPath(ROOT).length)]=sha;
function scan(b){const at=b.indexOf(Buffer.from('"blocks"'));let i=b.indexOf(91,at)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const s=b.subarray(start,end).toString();if(s.trim())for(const r of JSON.parse('['+s+']')){count++;if(want.has(K(r.position))){assert(!old.has(K(r.position)));old.set(K(r.position),r.block);}}};for(;i<b.length;i++){const c=b[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unclosed blocks');}
const scanned=scan(bytes);assert.equal(scanned,3381962);
for(const binding of selected){const prior=recovered.bindings.find(v=>v.name===binding.name),roots=binding.current_held_boundaries.map(v=>v.position),oldRoots=binding.old_held_boundaries.map(v=>v.position);assert.equal(roots.length,8);assert.equal(oldRoots.length,8);const identities=[];
 for(let i=0;i<8;i++){assert.equal(binding.current_held_boundaries[i].role,'retained_negative_owner_'+i);assert.equal(binding.old_held_boundaries[i].role,'retained_negative_owner_'+i);assert.deepEqual(world.get(K(roots[i])),old.get(K(oldRoots[i])));identities.push({role:binding.current_held_boundaries[i].role,original:oldRoots[i],current:roots[i],block:world.get(K(roots[i]))});}
 const cones=[];for(const [map,source,held,expected]of [[old,binding.old_effective_source,oldRoots,prior.original],[world,binding.current_effective_source,roots,prior.current]]){const positions=backwardCone(map,source,held),reference=new Map(expected.cone.map(r=>[K(r.position),r])),stops=new Set(held.map(K));assert.equal(positions.length,reference.size);for(const p of positions){const r=reference.get(K(p));assert(r);assert.deepEqual(map.get(K(p)),r.block);assert.deepEqual((stops.has(K(p))?[]:inputs(map,p)).map(K).sort(),r.inputs.map(K).sort());}const ev=makeSettledEvaluator(map,positions,held),cases=[];for(let mask=0;mask<256;mask++){const v=ev(new Map(held.map((p,i)=>[K(p),(mask>>i&1)*15]))),value=v.power.get(K(source))??0;assert.equal(value,mask===255?0:15);assert.equal(value,expected.power_table[mask]);cases.push({negative_owner_mask:mask,output:value});}cones.push({endpoint:source,roots:held,positions:positions.map(p=>({position:p,block:map.get(K(p)),inputs:stops.has(K(p))?[]:inputs(map,p)})),cases,feedback:{...checkFeedback(map,positions,held),scope:'Actual local eight-retained-owner OR cone, with negative owner state outputs held. Ownership transitions and phase timing excluded.'}});}
 const fanout=[],source=binding.current_effective_source;for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++){const p=P(source.x+x,source.y+y,source.z+z);if(inputs(world,p).some(q=>K(q)===K(source)))fanout.push({position:p,block:world.get(K(p))});}assert.deepEqual(fanout,binding.current_direct_fanout);
 records.push({binding,retained_state_identities:identities,original:cones[0],current:cones[1],actual_current_fanout:fanout});}
const report={status:'four_actual_any_owner_functions_checked_before_routing',base_cells:world.size,original_cold_cells_streamed:scanned,original_context_cells:old.size,records,source_sha256:pins,limits:['Each source is the actual local OR of its eight retained positive owners, equivalently NOT(all eight retained negative owner outputs high).','The actual current source is a rebuilt local repeater, not an inferred translation of the old wire. Each channel-specific root and current fanout is preserved.','Owner state transitions, grants/reset, phase freshness and timing remain open. No native execution.']};writeFileSync(new URL('source-functions.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,base:world.size,cold:scanned,old_context:old.size,old_vertices:records.reduce((n,r)=>n+r.original.positions.length,0),current_vertices:records.reduce((n,r)=>n+r.current.positions.length,0),cases:2048,state_identities:32}));
