// Four actual positive commit-phase tower observations against the complete reserved frame.
import assert from'node:assert/strict';import{loadFrame,pins}from'./frame.mjs';import{evaluate}from'../../dispatch-external-bindings-v1/transport-functions.mjs';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{searchPath,refreshIndices,P,K,F}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v)+'\n'),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),S=(p,n)=>P(p.x*n,p.y*n,p.z*n),U=p=>A(p,P(0,-1,0)),DIR=[P(1,0,0),P(0,0,1),P(-1,0,0),P(0,0,-1)],dir=v=>v.x>0?'east':v.x<0?'west':v.z>0?'south':'north',W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',SOL='minecraft:light_gray_concrete';
const {world}=loadFrame(),functions=read('source-functions.json');assert.equal(functions.status,'four_actual_commit_phase_functions_checked_before_routing');
const near=[];for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)near.push(P(x,y,z));
const added=[],checks=[],refusals=[],routes=[],connections=[],cache=existsSync(new URL('paths.json',H))?read('paths.json'):{},dev=(p,id=W,properties)=>[{position:U(p),block:{id:SOL}},{position:p,block:{id,...properties?{properties}:{}}}];
function patch(name,rows,{extra=[],expectedInputs=[],commit=false}={}){
 const keys=new Set(),affected=new Map();for(const r of rows){const k=K(r.position);if(world.has(k)||keys.has(k))return{ok:false,why:'occupied_or_duplicate',point:r.position};keys.add(k);for(const o of near){const p=A(r.position,o),b=world.get(K(p));if(active(b)&&!affected.has(K(p)))affected.set(K(p),{p,inputs:inputs(world,p).map(K).sort()});}}
 for(const r of rows)world.set(K(r.position),r.block);let bad;for(const [k,v]of affected){const expected=[...new Set([...v.inputs,...extra.filter(e=>K(e.target)===k).map(e=>K(e.source))])].sort(),actual=inputs(world,v.p).map(K).sort();if(JSON.stringify(expected)!==JSON.stringify(actual)){bad={why:'old_input_changed',point:v.p,expected,actual};break;}}
 if(!bad)for(const e of expectedInputs){const actual=inputs(world,e.target).map(K).sort(),expected=e.sources.map(K).sort();if(JSON.stringify(actual)!==JSON.stringify(expected)){bad={why:'new_input_wrong',point:e.target,expected,actual};break;}}
 if(bad||!commit)for(const r of rows)world.delete(K(r.position));if(bad)return{ok:false,...bad};if(commit){added.push(...rows.map(r=>({...r,part:name})));checks.push({name,added_cells:rows.length,old_receivers:affected.size,permitted_extra:extra});}return{ok:true,rows,old_receivers:affected.size};
}
function knownPath(name,path,{existingFirst=true,existingLast=false,lastRepeater=false,direction,extra=[]}={}){const rows=[],expect=[];for(let i=existingFirst?1:0;i<path.length-(existingLast?1:0);i++){const p=path[i],isR=lastRepeater&&i===path.length-1;rows.push(...dev(p,isR?R:W,isR?{facing:F[direction],delay:'1'}:undefined));expect.push({target:p,sources:[path[i-1],!isR&&i+1<path.length&&world.get(K(path[i+1]))?.id!==R?path[i+1]:null].filter(Boolean)});}return{rows,expectedInputs:expect,extra};}
const plans=[];
function sourceStub(name,source,preferred=P(0,0,-1),effectiveSource=source){
 for(const d of [preferred,...DIR])for(const dy of [0,1,-1]){const path=[1,2,3,4,5,6].map(i=>A(A(source,S(d,i)),P(0,dy*Math.min(i-1,3),0))),rows=path.flatMap((p,i)=>dev(p,i===0||i===4?R:W,i===0||i===4?{facing:F[dir(d)],delay:'1'}:undefined)),expectedInputs=path.map((p,i)=>({target:p,sources:[i?path[i-1]:effectiveSource,i!==0&&i!==4&&i+1!==4?path[i+1]:null].filter(Boolean)}));
 const tip=path.at(-1),escape=A(tip,A(d,P(0,dy,0)));if(near.filter(o=>Math.abs(o.x)+Math.abs(o.y)+Math.abs(o.z)<=2).some(o=>world.has(K(A(escape,o)))))continue;
 const r=patch(name+'_departure',rows,{expectedInputs,commit:true});if(r.ok)return{source:effectiveSource,physical_source_pad:source,source_isolator:path[0],source_stub:path};refusals.push({name:name+'_departure',d,dy,...r});}return null;
}
function receiverStub(name,destination,preferred=P(0,0,-1)){
 // d points from terminal toward the receiving cable.
 for(const pattern of [{span:4,rise:0},{span:7,rise:-1},{span:7,rise:1}])for(const d of [preferred,...DIR]){const tail=Array.from({length:pattern.span},(_,n)=>pattern.span-n).map(i=>A(A(destination,S(d,i)),P(0,pattern.rise*Math.min(3,Math.max(0,i-2)),0))),normalizer=tail.at(-1),rows=tail.flatMap((p,i)=>dev(p,i===0||i===tail.length-1?R:W,i===0||i===tail.length-1?{facing:F[dir(S(d,-1))],delay:'1'}:undefined)),expectedInputs=tail.map((p,i)=>({target:p,sources:[tail[i-1],i>0&&i<tail.length-2?tail[i+1]:null].filter(Boolean)}));const r=patch(name+'_arrival',rows,{extra:[{target:destination,source:normalizer}],expectedInputs,commit:true});if(r.ok)return{destination,receiving_stub:tail,normalizer,extra:[{target:destination,source:normalizer}],final_graph:[...tail,destination]};refusals.push({name:name+'_arrival',d,pattern,...r});}write('refusals.json',refusals);throw Error('No receiver stub '+name);
}
for(const record of functions.records){const b=record.binding,name=b.name,source=sourceStub(name,b.shared_current_producer,P(0,0,-1),b.current_effective_source);if(!source){write('refusals.json',refusals);throw Error('No actual local commit-phase departure '+name);}plans.push({name,kind:'positive_local_commit_phase_observation',root:b.current_effective_source,...source,...receiverStub(name,b.shared_witness_receiver)});}
write('planned-connections.json',{plans,checks,refusals});
write('endpoint-delta.json',{status:'reservation_only_checked_commit_phase_endpoint_rows_before_routing',blocks:added,plans,source_sha256:{...functions.source_sha256,...pins}});
for(const c of plans){const front=c.source_stub,tail=c.receiving_stub,start=front.at(-1),end=tail[0],fixed=[...front,...tail,...front.map(U),...tail.map(U)],allow=new Set([start,end,...[start,end].flatMap(p=>DIR.flatMap(v=>[-1,0,1].map(dy=>A(A(p,v),P(0,dy,0)))))].map(K)),forbidden=[];
 for(const q of[c.source,c.destination,...front,...tail])for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)for(let dy=-2;dy<=2;dy++){if(Math.abs(dx)+Math.abs(dz)>1)continue;const p=A(q,P(dx,dy,dz));if(!allow.has(K(p)))forbidden.push(p);}const step=P(start.x-front.at(-2).x,0,start.z-front.at(-2).z);for(const dy of[-1,0,1])forbidden.push(A(start,P(-step.x,dy,-step.z)));
 const receiverRear=P(2*end.x-tail[1].x,end.y,2*end.z-tail[1].z);for(const v of DIR)for(const dy of[-1,0,1]){const p=A(A(end,v),P(0,dy,0));if(K(p)!==K(receiverRear))forbidden.push(p);}
 const reserved=plans.filter(v=>v.name!==c.name).flatMap(v=>[...v.source_stub,...v.receiving_stub]).flatMap(p=>[-1,0,1].map(dy=>A(p,P(0,dy,0))));let path=cache[c.name];if(path&&(K(path[0])!==K(start)||K(path.at(-1))!==K(end)||K(path.at(-2))!==K(receiverRear)))path=null;if(!path){
 const candidates=[];for(const y of[-42,-46,-50,-54])for(const dz of[-20,-28,-36,-44])for(const dx of[0,16,-16,32,-32]){const p=P(end.x+dx,y,end.z+dz);if(!near.some(v=>world.has(K(A(p,v)))))candidates.push(p);}
 candidates.sort((a,b)=>(Math.abs(a.x-start.x)+Math.abs(a.y-start.y)+Math.abs(a.z-start.z)+Math.abs(a.x-end.x)+Math.abs(a.y-end.y)+Math.abs(a.z-end.z))-(Math.abs(b.x-start.x)+Math.abs(b.y-start.y)+Math.abs(b.z-start.z)+Math.abs(b.x-end.x)+Math.abs(b.y-end.y)+Math.abs(b.z-end.z)));
 const attempts=[];for(const waypoint of candidates.slice(0,12)){try{const first=searchPath(world,start,waypoint,{limit:350000,ignore:[c.source,c.destination,...fixed],forbidden,reserved}),second=searchPath(world,waypoint,end,{limit:350000,ignore:[c.source,c.destination,waypoint,...fixed],forbidden:[...forbidden,...first.path.slice(0,-1)],reserved:[...reserved,...first.path.slice(0,-1).flatMap(p=>[p,U(p)])]});const trial=[...first.path,...second.path.slice(1)];refreshIndices(trial);path=trial;cache[c.name]=path;write('paths.json',cache);console.log(JSON.stringify({name:c.name,waypoint,vertices:path.length,expanded:first.expanded+second.expanded}));break;}catch(e){attempts.push({waypoint,error:String(e)});write('route-attempts-'+c.name+'.json',attempts);console.log(JSON.stringify({name:c.name,waypoint,refusal:String(e)}));}}
 if(!path)throw Error('No checked clear waypoint route '+c.name);
 }assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=new Set(refreshIndices(path)),rows=[];for(let i=1;i<path.length-1;i++){const p=path[i],v=P(path[i+1].x-p.x,0,path[i+1].z-p.z);rows.push(...dev(p,refresh.has(i)?R:W,refresh.has(i)?{facing:F[dir(v)],delay:'1'}:undefined));}
 // Endpoints were already drawn; add the selected route then require complete
 // normalized geometry in check.mjs, including all old/body input comparisons.
 for(const r of rows){assert(!world.has(K(r.position)),'Route collision '+c.name+' '+K(r.position));world.set(K(r.position),r.block);added.push({...r,part:c.name});}
 const complete=[c.source,...front.slice(0,-1),...path,...c.final_graph.slice(1)];
 routes.push({name:c.name,path:complete});connections.push({...c,path_vertices:complete.length});write('routing-progress.json',{completed:routes.map(r=>r.name),pending:plans.filter(v=>!routes.some(r=>r.name===v.name)).map(r=>r.name),added_cells:added.length});
}
const result={status:'mutable_commit_phase_delivery_requires_checks',base_cells:world.size-added.length,new_cells:added,connections,routes,source_stub_checks:checks,source_sha256:{...functions.source_sha256,...pins},new_routes:routes.length};write('delta.json',result);console.log(JSON.stringify({routes:routes.length,added_cells:added.length}));
