// Four actual bank-wide BUSY functions and loader deliveries; full retained-input check.
import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {H,ROOT,K,read,loadBase,pins} from './frame.mjs';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
import {backwardCone,makeSettledEvaluator} from '../program-global-delivery-v1/settled-program-network.mjs';
import {evaluate} from '../dispatch-external-bindings-v1/transport-functions.mjs';
import {makeSettledEvaluator as makeDag} from '../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs';
import {checkFeedback} from '../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
const P=(x,y,z)=>({x,y,z}),A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete'),write=(n,d)=>writeFileSync(new URL(n,H),JSON.stringify(d,null,2)+'\n');
const frame=loadBase(),base=frame.world,world=new Map(base),d=read('delta.json'),f=read('source-functions.json');assert.equal(d.connections.length,4);assert.equal(f.selected.length,4);const rows=[...frame.rows,...d.new_cells],extra=new Map();for(let i=0;i<4;i++){const c=d.connections[i];assert.deepEqual(c.root,f.selected[i].new_source);assert.deepEqual(c.destination,f.selected[i].new_destination);extra.set(K(c.destination),K(c.normalizer));}
for(const r of d.new_cells){assert(!world.has(K(r.position)),'Collision');world.set(K(r.position),r.block);}
const newKeys=new Set(d.new_cells.filter(v=>active(v.block)).map(v=>K(v.position))),edges=new Set();for(const r of d.routes)for(let i=1;i<r.path.length;i++){edges.add(K(r.path[i-1])+'>'+K(r.path[i]));edges.add(K(r.path[i])+'>'+K(r.path[i-1]));}
let receivers=0,supports=0,actualInputs=0,preservedInputs=0,newInputs=0,changedReceivers=0;
for(const r of rows){const p=r.position,k=K(p),b=r.block;let support;if(b.id===WT)support=A(p,D[b.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);if(support){assert(solid(world.get(K(support))),'Unsupported '+k);supports++;}if(!active(b))continue;const actual=inputs(world,p).map(K).sort();receivers++;actualInputs+=actual.length;
if(base.has(k)){const prior=inputs(base,p).map(K);preservedInputs+=prior.length;if(extra.has(k)){prior.push(extra.get(k));changedReceivers++;}assert.deepEqual(actual,[...new Set(prior)].sort(),'Changed retained input '+k);}else{assert(newKeys.has(k));for(const q of actual)assert(edges.has(q+'>'+k),'Foreign cable contact '+q+'>'+k);newInputs+=actual.length;}}
assert.equal(changedReceivers,4);for(const r of d.routes)for(let i=1;i<r.path.length;i++)assert(inputs(world,r.path[i]).some(p=>K(p)===K(r.path[i-1])),'Broken route '+r.name+'/'+i);
const transport=evaluate(world,newKeys),proofs=[],negative=[],gateMutations=[],rears=new Map(),opposite={east:'west',west:'east',north:'south',south:'north'};
for(let i=0;i<4;i++){const c=d.connections[i],s=f.sources[i];assert.deepEqual(transport.get(c.normalizer),{roots:[c.root],table:2});const roots=s.boundaries.map(v=>v.current),targets=[c.root,c.destination],union=new Map();for(const p of targets)for(const q of backwardCone(world,p,roots))union.set(K(q),q);const positions=[...union.values()],feedback=checkFeedback(world,positions,roots),ev=makeSettledEvaluator(world,positions,roots),dag=makeDag(world,positions,roots),cases=[];
for(const a of s.cases){const v=ev(new Map(s.boundaries.map(b=>[K(b.current),a.values[b.name]?15:0]))),out=targets.map(p=>v.power.get(K(p))??0);const independent=dag(new Map(s.boundaries.map(b=>[K(b.current),a.values[b.name]?15:0])));for(const p of positions)assert.equal(independent.power.get(K(p))??0,v.power.get(K(p))??0,'Evaluator level disagreement '+K(p));assert.deepEqual(out,[a.current_output,a.current_output]);cases.push({mask:a.mask,outputs:out});for(const r of d.new_cells)if(r.block.id===R&&v.power.get(K(r.position))>0){const ins=inputs(world,r.position),dir=D[r.block.properties.facing];assert(ins.every(q=>(q.x-r.position.x)*dir.x+(q.z-r.position.z)*dir.z<0));const rear=Math.max(0,...ins.map(q=>v.power.get(K(q))??0));assert(rear>0);rears.set(K(r.position),Math.min(rears.get(K(r.position))??15,rear));}}
const cablePositions=backwardCone(world,c.destination,[c.root]),cableEv=makeSettledEvaluator(world,cablePositions,[c.root]),strengths=[];for(let n=0;n<=15;n++){const v=cableEv(new Map([[K(c.root),n]]));assert.equal(v.power.get(K(c.destination))??0,n?15:0);strengths.push({source:n,arrival:v.power.get(K(c.destination))??0});}
const cableSet=new Set(cablePositions.map(K));for(const row of d.new_cells.filter(r=>r.block.id===R&&cableSet.has(K(r.position)))){const p=row.position,k=K(p);world.set(k,{...row.block,properties:{...row.block.properties,facing:opposite[row.block.properties.facing]}});let refused=false;try{const pos=backwardCone(world,c.destination,[c.root]),v=makeSettledEvaluator(world,pos,[c.root])(new Map([[K(c.root),15]]));refused=(v.power.get(K(c.destination))??0)!==15;}catch{refused=true;}assert(refused,'Reversed cable diode survived '+k);world.set(k,row.block);negative.push({transfer_index:s.transfer_index,kind:'reverse_actual_cable_repeater',position:p});}
// Mutate a real internal inverter per nontrivial gate; this is not a declaration-only test.
const gates=s.current_cone.filter(r=>[T,WT].includes(r.block.id));if(gates.length){let caught=false;for(const r of gates){const k=K(r.position),saved=world.get(k);world.set(k,{id:W});try{const bad=makeSettledEvaluator(world,backwardCone(world,c.destination,roots),roots);for(const a of s.cases){const v=bad(new Map(s.boundaries.map(b=>[K(b.current),a.values[b.name]?15:0])));if((v.power.get(K(c.destination))??0)!==a.current_output){caught=true;break;}}}catch{caught=true;}world.set(k,saved);if(caught){gateMutations.push({transfer_index:s.transfer_index,position:r.position,kind:'replace_actual_gate_torch_with_wire'});break;}}assert(caught,'Gate mutation not detected');}
const support=P(c.normalizer.x,c.normalizer.y-1,c.normalizer.z),saved=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),saved);negative.push({transfer_index:s.transfer_index,kind:'delete_actual_arrival_support',position:support});
proofs.push({transfer_index:s.transfer_index,roots,targets,cases,strengths,feedback});}
// Shared input identities must drive all four paths consistently in the same map.
const jointBoundary=new Map();for(const s of f.sources)for(const b of s.boundaries){if(jointBoundary.has(b.name))assert.deepEqual(jointBoundary.get(b.name),b.current);jointBoundary.set(b.name,b.current);}assert.equal(jointBoundary.size,12);const jointRoots=[...jointBoundary.values()],jointNames=[...jointBoundary.keys()],jointPositions=new Map();for(const c of d.connections)for(const p of backwardCone(world,c.destination,jointRoots))jointPositions.set(K(p),p);const jointEval=makeDag(world,[...jointPositions.values()],jointRoots),jointCases=[];
for(let mask=0;mask<4096;mask++){const v=Object.fromEntries(jointNames.map((name,i)=>[name,!!(mask>>i&1)])),out=jointEval(new Map(jointNames.map(name=>[K(jointBoundary.get(name)),v[name]?15:0]))),actual=d.connections.map(c=>out.power.get(K(c.destination))??0),want=Array.from({length:4},(_,bank)=>v['bank'+bank+'_active']||v['bank'+bank+'_tail']||v['bank'+bank+'_reset']).map(v=>v?15:0);assert.deepEqual(actual,want);jointCases.push({mask,values:v,outputs:actual});}
const addedRepeaters=d.new_cells.filter(r=>r.block.id===R);assert.equal(rears.size,addedRepeaters.length,'Missing high-state rear evidence');
function cost(rows){const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)},materials={},columns=new Set();for(const r of rows){for(const a of['x','y','z']){box.from[a]=Math.min(box.from[a],r.position[a]);box.to[a]=Math.max(box.to[a],r.position[a]);}materials[r.block.id]=(materials[r.block.id]??0)+1;columns.add(Math.floor(r.position.x/16)+','+Math.floor(r.position.z/16));}return{cells:rows.length,box,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1])),legal_y_translation:[-64-box.from.y,319-box.to.y],occupied_columns:columns.size,materials};}
const fullCost=cost(rows);assert(fullCost.legal_y_translation[0]<=fullCost.legal_y_translation[1]);for(const n of['frame.mjs','prepare.mjs','route.mjs','check.mjs','../program-global-delivery-v1/settled-program-network.mjs','../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs','../memory/fabric-colocation-v2/cut-inputs.mjs','../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs','../dispatch-external-bindings-v1/transport-functions.mjs']){const p=new URL(n,H);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');}
const metrics={accepted_base_cells:base.size,new_cells:d.new_cells.length,total_cells:world.size,new_routes:4,path_vertices:d.routes.reduce((n,r)=>n+r.path.length,0),receivers,supports,actual_inputs:actualInputs,preserved_inputs:preservedInputs,new_route_inputs:newInputs,changed_receivers:changedReceivers,bank_source_cases:proofs.reduce((n,r)=>n+r.cases.length,0),bank_source_delivery_observations:proofs.reduce((n,r)=>n+2*r.cases.length,0),joint_bank_cases:4096,joint_bank_source_delivery_observations:512,cable_strength_cases:64,added_repeaters:addedRepeaters.length,minimum_new_repeater_rear:Math.min(...rears.values()),cable_mutations:negative.length,gate_mutations:gateMutations.length};write('checks.json',{status:'passed_actual_bank_loader_busy_deliveries',metrics,proofs,joint_cases:jointCases,joint_feedback:checkFeedback(world,[...jointPositions.values()],jointRoots),transport:transport.metrics,rears:[...rears].map(([key,rear])=>({position:P(...key.split(',').map(Number)),rear})),negative,gate_mutations:gateMutations,cost:{complete:fullCost,addition:cost(d.new_cells)},source_sha256:{...d.source_sha256,...pins},limits:['Actual per-bank ACTIVE, final delayed flush and reset_blocked are held boundaries; new routes carry their real bank-wide BUSY OR. These are not runtime host drivers.','The first joint reference queue exceeded its200000update cap; a component-DAG evaluator now checks all4096jointassignments, with full per-vertex agreement to the reference on32source-inclusive cases. Update counts are not redstone ticks. State/drain/reset transitions and pulse timing remain open.','This shared frame includes READY, held global returns, live BUSY, panel inputs and channel0 response; both cores and remaining response/master/loading routes are excluded. Its full counted cost is partial, not density admission.','No Minecraft changes or execution; native and whole-kernel acceptance remain separate.']});console.log(JSON.stringify(metrics));
