// Exact bank-wide BUSY output and original loader-positive transport recovery.
import assert from'node:assert/strict';import{writeFileSync}from'node:fs';import{H,read,bytes,K,pins,loadFrame}from'./frame.mjs';import{inputs,active}from'../memory/fabric-colocation-v2/cut-inputs.mjs';import{backwardCone,makeSettledEvaluator}from'../program-global-delivery-v1/settled-program-network.mjs';import{scanBlocks}from'../global-loader-return-review-v1/independent-network.mjs';import{evaluate}from'../dispatch-external-bindings-v1/transport-functions.mjs';import{checkFeedback}from'../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
const P=(x,y,z)=>({x,y,z}),A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),write=(n,d)=>writeFileSync(new URL(n,H),JSON.stringify(d,null,2)+'\n');
const{world}=loadFrame(),ledger=read('../panel-loader-delivery-v1/remaining-cuts.json'),classification=read('../memory/fabric-colocation-v2/bank-tail-classification.json'),ports=read('../memory/fabric-colocation-v2/bank-tail-repaired-bodies.json').tailPorts.bank_busy_any,translation=P(0,-8,40),loaderTranslation=P(240,-48,-871),buffer=bytes('../memory/master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');
const routeRows=[],part=r=>String(r.part??r.group??'');const count=scanBlocks(buffer,r=>{if(/(^|\/)actual_bank_tail_[0-3]$/.test(part(r)))routeRows.push(r);});assert(routeRows.length,'No actual old loader transport parts');const currentCones=classification.rows.map((r,b)=>backwardCone(world,ports.positions[b],r.sources.slice(0,3).map(s=>s.position))),oldPoints=[...routeRows.map(r=>r.position),...currentCones.flat().map(p=>A(p,P(0,8,-40)))];for(let b=0;b<4;b++)oldPoints.push(ledger.service.loader_control[7+b].target);
const wanted=new Set();for(const p of oldPoints)for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++)wanted.add(K(A(p,P(x,y,z))));const old=new Map();scanBlocks(buffer,r=>{if(wanted.has(K(r.position))){assert(!old.has(K(r.position)));old.set(K(r.position),r.block);}});
const selected=[],sources=[];
for(let bank=0;bank<4;bank++){const bankIndex=536+bank,li=7+bank,be=ledger.memory_cut_ledger.bank_inventory.entries.find(r=>r.index===bankIndex),le=ledger.service.loader_control[li],source=ports.original_positions[bank],current=ports.positions[bank],target=le.target,destination=A(target,loaderTranslation),name='actual_bank_tail_'+bank;assert.deepEqual(source,be.original.source.position);assert.deepEqual(current,A(source,translation));assert.equal(le.status,'pending');assert.equal(be.status,'outside_this_group_reconciliation_pending');assert.deepEqual(world.get(K(destination)),le.target_block);assert.deepEqual(old.get(K(source)),world.get(K(current)));assert.deepEqual(old.get(K(target)),world.get(K(destination)));assert.equal(inputs(world,destination).length,0);
 const transport=backwardCone(old,le.source,[source]).filter(p=>K(p)!==K(source)),owned=new Set(routeRows.filter(r=>part(r).endsWith(name)).map(r=>K(r.position)));for(const p of transport)assert(owned.has(K(p)),'Unowned original transport '+K(p));assert.deepEqual(evaluate(old,new Set(transport.map(K))).get(le.source),{roots:[source],table:2});assert(inputs(old,target).some(p=>K(p)===K(le.source)));
 const boundaries=classification.rows[bank].sources.slice(0,3).map(s=>({name:'bank'+bank+'_'+s.name,role:s.name,old:s.original,current:s.position}));for(const b of boundaries)assert.deepEqual(old.get(K(b.old)),world.get(K(b.current)));const oldCone=backwardCone(old,source,boundaries.map(b=>b.old)),currentCone=currentCones[bank],oldEval=makeSettledEvaluator(old,oldCone,boundaries.map(b=>b.old)),currentEval=makeSettledEvaluator(world,currentCone,boundaries.map(b=>b.current)),oldDelivery=makeSettledEvaluator(old,backwardCone(old,target,boundaries.map(b=>b.old)),boundaries.map(b=>b.old)),cases=[];
 for(let mask=0;mask<8;mask++){const values=Object.fromEntries(boundaries.map((b,i)=>[b.name,!!(mask>>i&1)])),expected=mask?15:0,a=oldEval(new Map(boundaries.map(b=>[K(b.old),values[b.name]?15:0]))).power.get(K(source))??0,c=currentEval(new Map(boundaries.map(b=>[K(b.current),values[b.name]?15:0]))).power.get(K(current))??0,t=oldDelivery(new Map(boundaries.map(b=>[K(b.old),values[b.name]?15:0]))).power.get(K(target))??0;assert.deepEqual([a,c,t],[expected,expected,expected],'Actual bank'+bank+' case'+mask);cases.push({mask,values,old_output:a,current_output:c,old_arrival:t});}
 selected.push({name:'bank_'+bank+'_busy_to_loader',bank,bank_index:bankIndex,loader_index:li,transfer_index:bank,new_source:current,new_destination:destination,source,target,old_normalizer:le.source,old_departure:be.original.target.position,old_route_function:{roots:[source],table:2},old_transport_vertices:transport.length});sources.push({bank,transfer_index:bank,boundaries,cases,original_cone:oldCone.map(p=>({position:p,block:old.get(K(p)),inputs:boundaries.some(b=>K(b.old)===K(p))?[]:inputs(old,p)})),current_cone:currentCone.map(p=>({position:p,block:world.get(K(p)),inputs:boundaries.some(b=>K(b.current)===K(p))?[]:inputs(world,p)})),feedback:checkFeedback(world,currentCone,boundaries.map(b=>b.current))});}
bytes('../global-loader-return-review-v1/independent-network.mjs');write('source-functions.json',{status:'actual_original_bank_loader_busy_positive',selected,sources,scanned_original_cells:count,actual_old_context_cells:old.size,original_transport_cells:routeRows.length,source_sha256:pins,limits:['Bank-wide BUSY is ACTIVE OR final delayed flush OR reset_blocked. It is neither READY-low nor an owner-qualified channel witness.','All three real current source states per bank are held test boundaries only; actual capture/state generation/reset/drain timing remain unproved.','Original and current downstream source functions plus original actual loader transport checked; all parent fanout must survive. No world changes or native acceptance.']});console.log(JSON.stringify({status:'sources_pass',banks:4,cases:32,old_cells:count,old_context:old.size,old_transport_cells:routeRows.length,source_devices:sources.reduce((n,s)=>n+s.current_cone.length,0)}));
