import assert from 'node:assert/strict';
import{readFileSync,writeFileSync}from'node:fs';
import{makeFrontPcFlags}from'./prepare.mjs';
import{materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
import{possibleStrengths}from'../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(D),pair=(a,b)=>[K(a),K(b)].sort().join('|'),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',diode=b=>['minecraft:repeater','minecraft:comparator'].includes(b?.id),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export function screen(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(Object.keys(d.parents)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,contacts=0,sides=0,rears=0,sets=0;
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;let p=P(v.position.x,v.position.y-1,v.position.z);if(v.block.id==='minecraft:redstone_wall_torch'){const[x,z]=D[v.block.properties.facing];p=P(v.position.x+x,v.position.y,v.position.z+z);}assert.equal(at(p)?.block.id,S,'Support '+K(v.position));supports++;}
 for(const v of d.blocks.filter(v=>v.block.id===W))for(const[x,z]of dirs)for(const dy of[-1,0,1]){const p=P(v.position.x+x,v.position.y+dy,v.position.z+z),b=at(p);if(!b||b.block.id.endsWith('_concrete')||v.part===b.part&&parents.has(v.part))continue;if(dy&&b.block.id!==W)continue;if(dy===1&&at(P(v.position.x,v.position.y+1,v.position.z)))continue;if(dy===-1&&at(P(p.x,p.y+1,p.z)))continue;assert(allowed.has(pair(v.position,p)),'Foreign '+v.part+' '+K(v.position)+' -> '+b.part+' '+K(p));contacts++;}
 for(const v of d.blocks.filter(v=>diode(v.block))){const[x,z]=D[v.block.properties.facing];for(const[dx,dz]of[[z,x],[-z,-x]]){const b=at(P(v.position.x+dx,v.position.y,v.position.z+dz));if(diode(b?.block)&&!(b.part===v.part&&parents.has(v.part)))assert(allowed.has(pair(v.position,b.position)),'Foreign diode side '+K(v.position));sides++;}if(!parents.has(v.part)&&v.block.id==='minecraft:repeater'){const rear=P(v.position.x-x,v.position.y,v.position.z-z),out=P(v.position.x+x,v.position.y,v.position.z+z);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'New diode direction '+K(v.position));rears++;}}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);assert.equal(at(P(c.x,c.top,c.z))?.block.id,W);for(let y=c.bottom;y<c.top;y+=2){const p=P(c.x,y,c.z),got=[];assert.equal(at(p)?.block.id,S);assert.equal(at(P(c.x,y+1,c.z))?.block.id,y+1===c.top?W:'minecraft:redstone_torch');for(const[x,z]of dirs){const q=P(p.x-x,y,p.z-z),b=at(q)?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z]))got.push(K(q));}for(const[dy,id]of[[1,W],[-1,'minecraft:redstone_torch']]){const q=P(c.x,y+dy,c.z);if(at(q)?.block.id===id)got.push(K(q));}
  const want=[K(y===c.bottom?c.entry:P(c.x,y-1,c.z))];if(y===c.top-1)want.push(K(P(c.x,c.top,c.z)));assert.deepEqual(got.sort(),want.sort(),'Column source '+c.name+' '+K(p));sets++;
 }}

 let mediated=0,cross=0,diodeFeeds=0,stairs=0;
 for(const solid of d.blocks.filter(v=>v.block.id===S)){const p=solid.position,src=[],dst=[];for(const[x,z]of dirs){let v=at(P(p.x-x,p.y,p.z-z)),b=v?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z]))src.push(v);v=at(P(p.x+x,p.y,p.z+z));b=v?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z])||b?.id==='minecraft:redstone_wall_torch'&&eq(D[b.properties.facing],[-x,-z]))dst.push(v);}const up=at(P(p.x,p.y+1,p.z)),down=at(P(p.x,p.y-1,p.z));if(up?.block.id===W)src.push(up);if(down?.block.id==='minecraft:redstone_torch')src.push(down);if([W,'minecraft:redstone_torch'].includes(up?.block.id))dst.push(up);if(down?.block.id===W)dst.push(down);for(const a of src)for(const b of dst){if(a===b||a.part===b.part&&parents.has(a.part))continue;mediated++;if(a.part===b.part)continue;cross++;if(a.block.id==='minecraft:repeater'&&b.block.id==='minecraft:redstone_torch'){const c=d.columns.find(c=>K(p)===K(P(c.x,c.bottom,c.z)));assert(c);assert.deepEqual(a.position,c.entry);assert.deepEqual(b.position,P(c.x,c.bottom+1,c.z));diodeFeeds++;}else{assert.equal(a.block.id,W);assert.equal(b.block.id,W);assert(allowed.has(pair(a.position,b.position)),'Unlisted solid stair pair '+K(p));stairs++;}}}
 assert.equal(mediated,1398);assert.equal(cross,88);assert.equal(diodeFeeds,24);assert.equal(stairs,64);
 const capacity=possibleStrengths({...d,parents:[...parents].map(id=>({id}))});assert.equal(capacity.failed.length,0,JSON.stringify(capacity.failed));return{supports,listed_contacts:contacts,diode_side_faces:sides,new_directed_repeaters:rears,positive_column_source_sets:sets,conservative_solid_paths:mediated,cross_part_solid_paths:cross,actual_diode_column_feeds:diodeFeeds,same_net_stair_pairs:stairs,...capacity};}

const d=makeFrontPcFlags();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
const structural=screen(d),map=new Map(d.blocks.map(v=>[K(v.position),v]));let preserved=0;
for(const[name,file,translation]of[['front','../control-front-pc-v1/design.json',P(0,0,0)],...Array.from({length:4},(_,i)=>['nzp_lane_'+i,'../control-nextpc-v1/branch-lane.json',P(180+32*i,284,-8)]),['agreement','../control-nextpc-v2/design.json',P(100,288,0)]])for(const v of materializeInstance(JSON.parse(readFileSync(new URL(file,import.meta.url))),{id:name,translation}).blocks){assert.deepEqual(map.get(K(v.position))?.block,v.block);preserved++;}
function bindings(d){const cs=new Map(d.connections.map(c=>[c.name,c]));assert.equal(cs.size,37);const front=JSON.parse(readFileSync(new URL('../control-front-pc-v1/design.json',import.meta.url)));for(let lane=0;lane<4;lane++){for(let b=0;b<3;b++){const c=cs.get('held_mask_'+b+'_lane_'+lane);assert.deepEqual(c.source,front.ports.branch_mask.bits[b].position);assert.deepEqual(c.destination,P(171+32*lane,285,-20+16*b));}assert.deepEqual(cs.get('decoded_br_lane_'+lane).source,P(170,124,82));assert.deepEqual(cs.get('decoded_br_lane_'+lane).destination,P(161+32*lane,285,36));assert.deepEqual(cs.get('predicate_lane_'+lane).source,P(166+32*lane,285,38));assert.deepEqual(cs.get('predicate_lane_'+lane).destination,P(lane?98:94,289,[-4,8,32,56][lane]));}
 for(let b=0;b<8;b++)for(const[kind,y,z]of[['immediate',249,16*b],['incremented_pc',241,8+16*b]]){const c=cs.get('agreement_'+kind+'_'+b);assert.deepEqual(c.source,P(20,y,-4+8*b));assert.deepEqual(c.destination,P(158,289,z));}
 assert.deepEqual(cs.get('predicate0_to_pc_selection').source,P(166,285,38));assert.deepEqual(cs.get('predicate0_to_pc_selection').destination,front.ports.pc_select_immediate.bits[0].position);assert(!d.ports.pc_select_immediate);assert.equal(d.ports.cmp_nzp.width,12);assert.equal(d.ports.flags_open.width,4);assert.equal(d.ports.nzp.width,12);assert.equal(d.metrics.stored_bits,53);return cs.size;}
let laneCases=0;for(let lane=0;lane<4;lane++)for(let flags=0;flags<8;flags++)for(let mask=0;mask<8;mask++)for(const br of[0,1]){const originalActive=br&&!!(flags&mask),actual=br&&[0,1,2].some(b=>(flags>>b&1)&&(mask>>b&1));assert.equal(!!actual,!!originalActive);laneCases++;}
let agreementCases=0;for(let active=0;active<16;active++)for(let predicates=0;predicates<16;predicates++)for(const sameTarget of[false,true]){const incremented=91,immediate=sameTarget?91:178,selected=predicates&1?immediate:incremented,candidates=Array.from({length:4},(_,i)=>predicates>>i&1?immediate:incremented),different=[1,2,3].some(i=>(active>>i&1)&&((predicates>>i&1)!==(predicates&1))),actual=!(active&1)||(different&&!sameTarget),expected=!(active&1)||candidates.some((p,i)=>(active>>i&1)&&p!==selected);assert.equal(actual,expected);agreementCases++;}
let corruptions=0;for(const f of[c=>c.blocks.find(v=>K(v.position)==='169,281,60').block={id:W},c=>c.blocks.find(v=>K(v.position)==='140,1,20').block.properties.facing='east',c=>c.blocks.find(v=>K(v.position)==='20,260,-6').block.id=W,c=>c.connections.find(c=>c.name==='predicate_lane_1').destination.z=32,c=>c.connections.find(c=>c.name==='agreement_immediate_7').destination.z=96,c=>c.blocks.find(v=>K(v.position)==='-3,241,-12').block.properties.facing='east']){const c=structuredClone(d);f(c);assert.throws(()=>{screen(c);bindings(c);});corruptions++;}
const result={status:'author_static_connected_front_pc_nzp_checks_pass',...d.metrics,...structural,preserved_primary_parent_cells:preserved,exact_bindings:bindings(d),lane_flag_mask_cases:laneCases,active_mask_predicate_target_cases:agreementCases,corruptions_refused:corruptions,native_acceptance:false,selected_density_layout:false,limits:d.missing};if(process.argv.includes('--save'))writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
