// Connected frontend/PC, four private NZP banks and actual selected-target agreement.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';import{pathToFileURL}from'node:url';
import {makeFrontPc} from '../control-front-pc-v1/prepare.mjs';
import {makeBranchLane} from '../control-nextpc-v1/prepare.mjs';
import {makeTargetAgreement} from '../control-nextpc-v2/prepare.mjs';
import {makeSignalDescent} from '../../../hardware/full-gpu-signal-descent.mjs';
import {materializeInstance} from '../../../hardware/gpu-layout-assembly.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,F={east:'west',west:'east',north:'south',south:'north'};
export function makeFrontPcFlags(){
 const map=new Map(),parents={},routes=[],edges=[],columns=[],connections=[];let part='';const at=p=>map.get(K(p));
 function put(p,id,properties){assert(!at(p),'Collision '+part+' '+K(p)+' '+at(p)?.part);map.set(K(p),{position:p,block:{id:'minecraft:'+id,...(properties?{properties}:{})},part});}
 const solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid({...p,y:p.y-1});put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'}),edge=(a,b)=>edges.push({from:a,to:b});
 function insert(name,d,translation){const moved=materializeInstance(d,{id:name,translation});for(const v of moved.blocks){assert(!at(v.position),'Parent collision '+name+' '+K(v.position));map.set(K(v.position),{...v,part:name});}parents[name]={blocks:d.blocks.length,translation};return moved;}
 function route(name,ws,{branches=[]}={}){part=name;const path=[P(...ws[0])];for(let n=1;n<ws.length;n++){const a=ws[n-1],b=ws[n],delta=b.map((v,i)=>v-a[i]),steps=Math.abs(delta[0])+Math.abs(delta[2]);assert(steps&&(!delta[0]||!delta[2])&&(!delta[1]||Math.abs(delta[1])===steps),'Invalid route '+name);for(let i=1;i<=steps;i++)path.push(P(...a.map((v,k)=>v+Math.sign(delta[k])*i)));}
  const forbid=new Set(branches.map(K)),candidates=[-1];for(let i=1;i<path.length-1;i++){const a=path[i-1],p=path[i],b=path[i+1];if(!at(p)&&!forbid.has(K(p))&&a.y===p.y&&b.y===p.y&&p.x-a.x===b.x-p.x&&p.z-a.z===b.z-p.z)candidates.push(i);}candidates.push(path.length);const cost=new Map([[-1,0]]),prev=new Map();for(const end of candidates.slice(1))for(const start of candidates){if(start>=end)break;if(!cost.has(start)||end-start>12)continue;const value=cost.get(start)+(end===path.length?0:1);if(value<(cost.get(end)??Infinity)){cost.set(end,value);prev.set(end,start);}}assert(prev.has(path.length),'Unrefreshable '+name);const refresh=[];for(let p=prev.get(path.length);p!==-1;p=prev.get(p))refresh.push(p);
  for(let i=0;i<path.length;i++){const p=path[i];if(at(p)){assert(i===0||i===path.length-1,'Internal overlap '+name+' '+K(p));assert.equal(at(p).block.id,'minecraft:redstone_wire');}else if(refresh.includes(i)){const q=path[i+1];rep(p,q.x>p.x?'east':q.x<p.x?'west':q.z>p.z?'south':'north');}else wire(p);if(i)edge(path[i-1],p);}routes.push({name,path,refresh_indices:refresh.sort((a,b)=>a-b)});return path;
 }
 function lift(name,x,z,bottom,top,entry){part=name;assert.equal((top-bottom)%4,1);for(let y=bottom;y<top;y++)if((y-bottom)%2===0)solid(P(x,y,z));else put(P(x,y,z),'redstone_torch');put(P(x,top,z),'redstone_wire');columns.push({name,x,z,bottom,top,wire_top:true,entry});}
 const front0=makeFrontPc();assert.deepEqual(front0,JSON.parse(readFileSync(new URL('../control-front-pc-v1/design.json',import.meta.url))));
 const front=insert('front',front0,P(0,0,0)),lanes=Array.from({length:4},(_,lane)=>insert('nzp_lane_'+lane,makeBranchLane(),P(180+32*lane,284,-8))),agreement=insert('agreement',makeTargetAgreement(),P(100,288,0));
 // Three retained instruction-mask wires fan out through isolated branches.
 for(let bit=0;bit<3;bit++){
  const s=front.ports.branch_mask.bits[bit].position,row=lanes[0].ports.branch_mask.bits[bit].position.z,busZ=row-7,corridor=145+4*bit;
  part='mask_source_'+bit;rep(P(s.x+1,s.y,s.z),'east');edge(s,P(s.x+1,s.y,s.z));edge(P(s.x+1,s.y,s.z),P(s.x+2,s.y,s.z));lift('mask_lift_'+bit,s.x+2,s.z,s.y,282,P(s.x+1,s.y,s.z));
  route('mask_bus_'+bit,[[s.x+2,282,s.z],[corridor,282,s.z],[corridor,282,busZ],[lanes[3].ports.branch_mask.bits[bit].position.x,282,busZ]],{branches:lanes.map(l=>P(l.ports.branch_mask.bits[bit].position.x,282,busZ))});
  for(let lane=0;lane<4;lane++){const p=lanes[lane].ports.branch_mask.bits[bit].position;part='mask_branch_'+bit+'_'+lane;rep(P(p.x,282,busZ+1),'south');wire(P(p.x,282,busZ+2));edge(P(p.x,282,busZ),P(p.x,282,busZ+1));edge(P(p.x,282,busZ+1),P(p.x,282,busZ+2));route(part+'_rise',[[p.x,282,busZ+2],[p.x,285,p.z-2]]);part='mask_branch_'+bit+'_'+lane;rep(P(p.x,285,p.z-1),'south');edge(P(p.x,285,p.z-2),P(p.x,285,p.z-1));edge(P(p.x,285,p.z-1),p);connections.push({name:'held_mask_'+bit+'_lane_'+lane,source:s,destination:p});}
 }
 // BR is broadcast. Inactive predicates are unqualified data; agreement
 // alone applies the retained active mask, avoiding four redundant AND gates.
 const br=front.ports.controls.bits.find(b=>b.name==='pc_mux').position;part='br_source';rep(P(br.x,br.y,br.z-1),'north');edge(br,P(br.x,br.y,br.z-1));edge(P(br.x,br.y,br.z-1),P(br.x,br.y,br.z-2));lift('br_lift',br.x,br.z-2,br.y,281,P(br.x,br.y,br.z-1));
 route('br_depart',[[170,281,80],[170,281,60]]);part='br_fork';for(const dx of[-1,1]){rep(P(170+dx,281,60),dx<0?'west':'east');wire(P(170+2*dx,281,60));edge(P(170,281,60),P(170+dx,281,60));edge(P(170+dx,281,60),P(170+2*dx,281,60));}route('br_bus_left',[[168,281,60],[153,281,60]],{branches:[P(153,281,60)]});route('br_bus_right',[[172,281,60],[249,281,60]],{branches:[185,217,249].map(x=>P(x,281,60))});
 for(let lane=0;lane<4;lane++){const p=lanes[lane].ports.branch_enable.bits[0].position,x=p.x-8;part='br_branch_'+lane;rep(P(x,281,59),'north');wire(P(x,281,58));edge(P(x,281,60),P(x,281,59));edge(P(x,281,59),P(x,281,58));route(part+'_arrive',[[x,281,58],[x,285,54],[x,285,p.z],[p.x-2,285,p.z]]);part='br_branch_'+lane;rep(P(p.x-1,285,p.z),'east');edge(P(p.x-2,285,p.z),P(p.x-1,285,p.z));edge(P(p.x-1,285,p.z),p);connections.push({name:'decoded_br_lane_'+lane,source:br,destination:p});}
 // Each predicate is physically forwarded into the active-value agreement.
 for(let lane=0;lane<4;lane++){const s=lanes[lane].ports.branch_taken.bits[0].position,p=agreement.ports.branch_taken.bits[lane].position;part='predicate_source_'+lane;rep(P(s.x,s.y,s.z+1),'south');edge(s,P(s.x,s.y,s.z+1));wire(P(s.x,s.y,s.z+2));edge(P(s.x,s.y,s.z+1),P(s.x,s.y,s.z+2));route('predicate_escape_'+lane,[[s.x,s.y,s.z+2],[s.x,s.y,142]]);part='predicate_lift_feed_'+lane;rep(P(s.x,s.y,143),'south');edge(P(s.x,s.y,142),P(s.x,s.y,143));edge(P(s.x,s.y,143),P(s.x,s.y,144));lift('predicate_lift_'+lane,s.x,144,s.y,302+4*lane,P(s.x,s.y,143));const west=-24-12*lane,corridor=148+16*lane,level=302+4*lane,origin=P(west,level,p.z-8),landing=lane?293:289,descent=insert('predicate_descent_'+lane,makeSignalDescent({drop:level-landing}),origin);
  route('predicate_route_'+lane,[[s.x,level,144],[s.x,level,corridor],[west,level,corridor],[west,level,origin.z]]);const out=descent.ports.output.bits[0],q=P(out.position.x+2*out.travel.x,landing,out.position.z+2*out.travel.z),ws=[[out.position.x,landing,out.position.z],[q.x,landing,q.z]];if(out.travel.x<0)ws.push([q.x,landing,origin.z-8]);ws.push([west+12,landing,ws.at(-1)[2]]);if(lane)ws.push([west+12,landing,p.z+8],[p.x,landing,p.z+8],[p.x,289,p.z+4],[p.x,289,p.z+2]);else ws.push([west+12,landing,p.z],[p.x-2,289,p.z]);route('predicate_return_'+lane,ws);part='predicate_arrive_'+lane;if(lane){rep(P(p.x,289,p.z+1),'north');edge(P(p.x,289,p.z+2),P(p.x,289,p.z+1));edge(P(p.x,289,p.z+1),p);}else{rep(P(p.x-1,289,p.z),'east');edge(P(p.x-2,289,p.z),P(p.x-1,289,p.z));edge(P(p.x-1,289,p.z),p);}connections.push({name:'predicate_lane_'+lane,source:s,destination:p});
 }
 // Two real target bytes are tapped after their existing arrival normalizers,
 // then normalized independently before each target XOR input.
 for(let bit=0;bit<8;bit++)for(const [kind,dy,side,index]of[['immediate',249,-1,2*bit],['incremented_pc',241,1,2*bit+1]]){
  const source=P(20,dy,-4+8*bit),entry=P(20,dy,source.z+side),base=P(20,dy,source.z+2*side),p=agreement.ports[kind].bits[bit].position,turn=120-4*index;
  part='target_source_'+index;rep(entry,side<0?'north':'south');edge(source,entry);edge(entry,base);lift('target_lift_'+index,base.x,base.z,dy,298,entry);
  route('target_route_'+index,[[20,298,base.z],[turn,298,base.z],[turn,298,p.z],[p.x-14,298,p.z]]);part='target_arrive_'+index;rep(P(p.x-13,298,p.z),'east');wire(P(p.x-12,298,p.z));edge(P(p.x-14,298,p.z),P(p.x-13,298,p.z));edge(P(p.x-13,298,p.z),P(p.x-12,298,p.z));route(part+'_descent',[[p.x-12,298,p.z],[p.x-3,289,p.z],[p.x-2,289,p.z]]);part='target_arrive_'+index;rep(P(p.x-1,289,p.z),'east');edge(P(p.x-2,289,p.z),P(p.x-1,289,p.z));edge(P(p.x-1,289,p.z),p);connections.push({name:'agreement_'+kind+'_'+bit,source,destination:p});
 }
 // Predicate0 selects the common candidate. A later real fault/OPEN producer
 // must prevent commit on disagreement; combinational selection is not ack.
 const pred=P(166,302,144);part='selection_branch';rep(P(165,302,144),'west');wire(P(164,302,144));edge(pred,P(165,302,144));edge(P(165,302,144),P(164,302,144));const desc=insert('selection_descent',makeSignalDescent({drop:61}),P(154,302,144));route('selection_depart',[[164,302,144],[164,302,136],[150,302,136],[150,302,144],[154,302,144]]);const o=desc.ports.output.bits[0],s=o.position,t=o.travel,q=P(s.x+2*t.x,s.y,s.z+2*t.z);route('selection_return',[[s.x,s.y,s.z],[q.x,q.y,q.z],[178,241,q.z],[178,241,-40],[-36,241,-40],[-36,241,-12],[-4,241,-12]]);part='selection_arrive';rep(P(-3,241,-12),'east');edge(P(-4,241,-12),P(-3,241,-12));edge(P(-3,241,-12),front.ports.pc_select_immediate.bits[0].position);connections.push({name:'predicate0_to_pc_selection',source:lanes[0].ports.branch_taken.bits[0].position,destination:front.ports.pc_select_immediate.bits[0].position});
 const ports=structuredClone(front.ports);delete ports.pc_select_immediate;ports.lane_enable=agreement.ports.lane_enable;ports.branch_disagreement=agreement.ports.disagreement;ports.branch_agreement=agreement.ports.agreement;ports.targets_equal=agreement.ports.targets_equal;
 for(const[name,key]of[['cmp_nzp','cmp_nzp'],['flags_open','flags_open'],['nzp','nzp']])ports[name]={direction:name==='nzp'?'output':'input',width:lanes.reduce((n,l)=>n+l.ports[key].width,0),polarity:'active_high',bit_order:'lane_major_each_word_lsb_first',bits:lanes.flatMap((l,lane)=>l.ports[key].bits.map(b=>({...b,bit:lane*l.ports[key].width+b.bit,lane,local_bit:b.bit}))),meaning:name==='cmp_nzp'?'Independent physical ALU CMP P/Z/N per lane, held until corresponding flag locks close. Actual ALU routes and reset-zero selectors are missing.':name==='flags_open'?'Actual CMP-only enabled UPDATE/reset qualifier producers and measured closure acknowledgement are missing.':'Independent retained P/Z/N by lane; not shared flags.'};
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=Math.min(...blocks.map(v=>v.position[a]));box.to[a]=Math.max(...blocks.map(v=>v.position[a]));}
 return{status:'offline_connected_front_pc_nzp_target_agreement_draft',blocks,parents,ports,edges,routes,columns,connections,box,metrics:{blocks:blocks.length,stored_bits:53,new_connections:connections.length,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1]))},native_acceptance:false,complete_gpu_layout:false,selected_density_layout:false,refinement:'Decoded BR reaches all lane predicates; only retained active-mask bits qualify their contribution in selected-value agreement. Inactive predicates are unqualified data and cannot cause a fault or change lane0 selection. Lane0 must be active.',missing:['Actual independent ALU CMP12 routes and zero/reset selectors, enabled CMP-only UPDATE flag OPEN producers and closure detection.','Retained disagreement/fault capture and safe PC NEXT/CURRENT/init producers; candidate selection alone does not authorize a PC commit.','UPDATE RF+flags+PC closure join and ALU response drain before instruction release; initial R13 assignment and full controller startup admission.','Global program memory/dispatch/phase connections, timing/conditioning and compact complete-machine placement.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeFrontPcFlags();if(process.argv.includes('--check'))assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
