// Source-to-terminal strength over actual directed diode and bidirectional wire edges.
import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
const h=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,h))),key=p=>`${p.x},${p.y},${p.z}`;
const selected=read('fault-design.json'),blocks=new Map(selected.blocks.map(v=>[key(v.position),v.block])),adj=new Map(),connections=[];
function edge(a,b){if(!adj.has(a))adj.set(a,new Set());adj.get(a).add(b);}
for(const n of ['../alu-four-lane-v1/w-choice-height-matched.json','../alu-four-lane-fanout-v2/design.json','../alu-four-lane-fanout-v2/q-design.json','../alu-four-lane-fanout-v2/carry-design.json','../alu-four-lane-fanout-v2/qaux-design.json','../alu-four-lane-fanout-v3/load-design.json','../alu-four-lane-fanout-v3/addend-design.json','../alu-four-lane-fanout-v3/arithmetic-design.json','../alu-four-lane-fanout-v3/status-design.json','fault-design.json']){const d=read(n);connections.push(...d.connections);for(const e of d.edges){const a=key(e.from),b=key(e.to);edge(a,b);if(blocks.get(a)?.id==='minecraft:redstone_wire'&&blocks.get(b)?.id==='minecraft:redstone_wire')edge(b,a);}}
const outputs=new Set(connections.map(c=>key(c.target))),groups=new Map();for(const c of connections){const k=key(c.source);if(!groups.has(k))groups.set(k,new Set());groups.get(k).add(key(c.target));}
let terminals=0,min=15;
for(const[start,expected]of groups){const power=new Map([[start,1]]),q=[start];for(let i=0;i<q.length;i++){const p=q[i],v=power.get(p);for(const t of adj.get(p)??[]){const id=blocks.get(t)?.id,from=blocks.get(p)?.id;assert(['minecraft:redstone_wire','minecraft:repeater'].includes(id),'Unexpected unmodelled signal element '+t);const next=id==='minecraft:repeater'?15:v-(id==='minecraft:redstone_wire'&&from==='minecraft:redstone_wire'?1:0);if(next>0&&next>(power.get(t)??0)){power.set(t,next);q.push(t);}}}
 assert.deepEqual(new Set([...power.keys()].filter(p=>outputs.has(p))),expected,'Exact destinations '+start);for(const p of expected){assert.equal(power.get(p),15,'Normalized receiving terminal '+p);min=Math.min(min,power.get(p));terminals++;}}
assert.equal(groups.size,31);assert.equal(terminals,141);console.log(JSON.stringify({status:'all_actual_command_and_fault_terminals_normalized_from_weak_positive_sources',sources:31,logical_commands:35,command_destinations:140,fault_return_destinations:1,minimum_terminal_power:min,wrong_command_destinations:0,scope:'settled signal strength only; no pulse width or torch timing claim',native_calls:0}));
