import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{resolve}from'node:path';
import{makeAluFaultReturn}from'../../../hardware/full-gpu-alu-fault-return.mjs';import{makeAluOpenInhibits}from'../../../hardware/full-gpu-alu-open-inhibits.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url)),prefix='artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v4/',parent='artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v3/source-manifest.json',read=p=>readFileSync(resolve(root,p)),json=p=>JSON.parse(read(p)),sha=p=>createHash('sha256').update(read(p)).digest('hex'),enc=v=>JSON.stringify(v,null,2)+'\n';
export function prepare({check=false}={}){
 assert.equal(sha(parent),'810486fe57e52f4bbea3b18c8b8fa49cf93bc115d423dc74eb0a9d989b0cc2f2');const files=new Set([parent]);for(const[p,h]of Object.entries(json(parent).source_sha256)){assert.equal(sha(p),h,'Frozen source '+p);files.add(p);}
 const groups=[];for(const[name,fn]of[['fault-design',makeAluFaultReturn],['inhibit-design',makeAluOpenInhibits]]){const d=fn();assert.deepEqual(d,json(prefix+name+'.json'),'Exact regeneration '+name);groups.push({name,metrics:d.metrics,box:d.box,new_connections:d.connections});}
 const selected=json(prefix+'inhibit-design.json'),old=json('artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v3/interface.json');
 const iface={...old,status:'partial_ALU_35_commands_actual_fault_return_and_OPEN_inhibits',internal_controller_fault_return_connected:true,lane_OPEN_inhibit_outputs:selected.ports.lane_data_open_inhibit,reset_decoder_alias:selected.reset_decoder_alias,data_OPEN_masks_complete:false,physical_mask_producers_complete:true,mask_delivery_complete:false};
 const ip=prefix+'interface.json';if(check)assert.equal(read(ip).toString(),enc(iface));else writeFileSync(resolve(root,ip),enc(iface));
 for(const n of['fault-return','open-inhibits'])files.add('hardware/full-gpu-alu-'+n+'.mjs');
 for(const n of['README.md','prepare.mjs','interface.json','check-all.mjs','checks.json','check-fault-geometry.py','check-inhibit-geometry.py','check-inhibit-logic.py','check-signal.mjs','fault-design.json','inhibit-design.json'])files.add(prefix+n);
 const manifest={status:'offline_35_command_fault_feedback_and_four_OPEN_inhibit_producers_delivery_pending',source_sha256:Object.fromEntries([...files].sort().map(p=>[p,sha(p)])),current_candidate:prefix+'inhibit-design.json',parent_manifest_sha256:sha(parent),groups,metrics:selected.metrics,box:selected.box,commands_required:41,commands_physically_delivered:35,commands_missing:6,physical_destinations:140,physical_lane_OPEN_inhibits:4,retained_lane_bits:228,retained_controller_bits:26,physical_data_OPEN_masks_complete:false,core_interfaces_complete:false,independent_full_geometry_review:false,native_calls:0,native_acceptance:false,missing:selected.missing};
 const mp=prefix+'source-manifest.json';if(check)assert.equal(read(mp).toString(),enc(manifest));else writeFileSync(resolve(root,mp),enc(manifest));return{manifest_sha256:sha(mp),source_pins:files.size,blocks:selected.blocks.length,delivered_commands:35,remaining_commands:6,native_calls:0};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(prepare({check:process.argv.includes('--check')})));
