import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeAdmissionCloseJoined}from'../../../../hardware/memory-layout-admission-close-joined.mjs';import{makeAdmissionClose}from'../../../../hardware/memory-layout-admission-close.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),d=makeAdmissionCloseJoined();assert.equal(sha(JSON.stringify(d)+'\n'),sha(readFileSync(new URL('design.json',import.meta.url))));
const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',R='minecraft:repeater',W='minecraft:redstone_wire',T='minecraft:redstone_torch',V={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},add=(p,v,n=1)=>P(p.x+n*v.x,p.y+n*v.y,p.z+n*v.z),m=new Map(d.blocks.map(v=>[K(v.position),v.block]));assert.equal(m.size,d.blocks.length);
const local=makeAdmissionClose(),o=d.witness.origin;for(const b of local.blocks)assert.deepEqual(m.get(K(add(b.position,o))),b.block);assert.equal(d.bindings.length,74);assert.equal(Object.keys(d.sources).length,37);assert.equal(d.columns.length,37);assert.equal(d.descents.length,37);
const expected={};for(let i=0;i<8;i++)expected['mask'+i]=P(5*i+2,1,-6);for(let c=0;c<4;c++){const X=128*c,Y=80*c;Object.assign(expected,{['owner_open'+c]:P(X+44,Y+1,-10),['payload_open'+c]:P(X+104,Y+32,-16),['commit_phase'+c]:P(X+172,Y+29,124),['any_owner'+c]:P(X+170,Y+29,128),['active'+c]:P(X+50,Y+5,174),['busy'+c]:P(X+52,Y+1,16),['commit_input'+c]:P(X+64,Y+1,172)});}expected.initialize=P(536,-31,350);assert.deepEqual(d.sources,expected);
function bind(b){const v=m.get(K(b.driver));assert.equal(v?.id,R);assert.equal(v.properties.delay,'1');const tv=V[v.properties.facing];if(b.kind==='source'){assert.deepEqual(add(b.driver,tv,-1),expected[b.name]);assert([S,W].includes(m.get(K(b.source))?.id));}else{assert.equal(b.kind,'destination');assert.deepEqual(b.destination,d.witness.ports[b.name].positions[0]);assert.deepEqual(add(b.driver,tv),b.destination);}}
for(const b of d.bindings)bind(b);
function route(r){for(let i=0;i<r.path.length;i++){const p=r.path[i],v=m.get(K(p));assert(v,'missing '+r.name+' '+K(p));assert.equal(d.nets[K(p)],r.net);if(v.id===R){assert(i>0&&i<r.path.length-1);const tv=V[v.properties.facing];assert.deepEqual(r.path[i-1],add(p,tv,-1));assert.deepEqual(r.path[i+1],add(p,tv));}else assert.equal(v.id,W);}}
for(const r of d.routes)route(r);for(const r of d.descents)route(r);
function column(c){assert.equal((c.hi-c.lo)%4,0);for(let y=c.lo;y<=c.hi;y++)assert.equal(m.get(K(P(c.x,y,c.z)))?.id,(y-c.lo)%2?T:S);}
for(const c of d.columns)column(c);
// Boundaries retain the exact loader overrides and real downstream RETIRE qualifiers.
assert.equal(d.changes.length,10);for(const c of d.changes)assert.deepEqual(m.get(K(c.position)),c.to);for(let c=0;c<4;c++){const x=128*c;for(let k=0;k<8;k++)assert.equal(m.get(K(P(x+46,80*c+1+4*k,-5)))?.id,W);assert.equal(m.get(K(P(x+48,80*c+1,16)))?.id,W);}
assert.deepEqual(d.ports.global_channels_quiet.positions,[d.output_binding.destination]);assert.deepEqual(d.ports.global_channels_quiet.bits[0].position,d.output_binding.destination);assert.deepEqual(add(d.output_binding.output_driver,V[m.get(K(d.output_binding.output_driver)).properties.facing]),d.output_binding.destination);assert.equal(m.get(K(d.output_binding.destination)).id,W);
let negatives=0;for(const b of d.bindings){const k=K(b.driver),old=m.get(k);m.set(k,{...old,properties:{...old.properties,facing:old.properties.facing==='north'?'south':'north'}});assert.throws(()=>bind(b));m.set(k,old);negatives++;}for(const c of d.columns){const k=K(P(c.x,c.lo+1,c.z)),old=m.get(k);m.delete(k);assert.throws(()=>column(c));m.set(k,old);negatives++;}for(const r of d.descents){const k=K(r.path[1]),old=m.get(k);m.delete(k);assert.throws(()=>route(r));m.set(k,old);negatives++;}
const sums=Object.fromEntries(Object.keys(expected).map(n=>[n,{repeaters:0,torches:0,nominal_component_game_ticks:0}]));for(const b of d.blocks){const k=K(b.position),n=d.nets[k];if(!sums[n]||['memory_parent','loader_parent','witness'].includes(d.groups[k]))continue;if(b.block.id===R)sums[n].repeaters++;else if(b.block.id===T)sums[n].torches++;}for(const v of Object.values(sums))v.nominal_component_game_ticks=2*(v.repeaters+v.torches);
const result={status:'offline_joined_actual_admission_close_geometry_checks_pass',...d.metrics,exact_regeneration:true,canonical_witness_cells:local.blocks.length,actual_source_joins:37,normalized_destination_joins:37,positive_columns:37,descending_paths:37,parent_overrides_preserved:d.parent_overrides_preserved,negative_checks:negatives,legal_y_translation:[-64-d.box.from.y,319-d.box.to.y],occupied_chunk_columns:new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`)).size,nominal_source_path_sums:sums,nominal_sum_limit:'Sums of drawn diode/torch delays only, not achieved event timing or a worst-case propagation bound; input matrix, SR flags, original source-to-tap and final consumer routes excluded.',native_acceptance:false};console.log(JSON.stringify(result));if(process.argv.includes('--save')){writeFileSync(new URL('joined-checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');writeFileSync(new URL('inventory.json',import.meta.url),JSON.stringify(d.metrics,null,2)+'\n');writeFileSync(new URL('ports.json',import.meta.url),JSON.stringify({global_channels_quiet:d.ports.global_channels_quiet,memory_admission_block:d.ports.memory_admission_block,sources:d.sources,bindings:d.bindings,missing:d.missing},null,2)+'\n');}
