import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeAdmissionClose}from'../../../../hardware/memory-layout-admission-close.mjs';import{makeLiteralNetwork}from'../../../../hardware/full-gpu-literal-network.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';import{INPUTS,OUTPUTS,FLAGS,MASKS,terms,evaluate,step}from'./logic.mjs';
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),d=makeAdmissionClose(),saved=JSON.parse(readFileSync(new URL('controller.json',import.meta.url)));assert.equal(hash(d),hash(saved));const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',R='minecraft:repeater',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block]));assert.equal(m.size,d.blocks.length);
const logic=makeLiteralNetwork({inputs:INPUTS,outputs:OUTPUTS,terms:terms()});for(const v of logic.blocks)assert.deepEqual(m.get(K(v.position)),v.block);
function route(r){for(let i=0;i<r.path.length;i++){const p=r.path[i],b=m.get(K(p));assert(b,r.name+' missing '+K(p));assert.equal(d.nets[K(p)],r.net);if(b.id===R){const t=D[b.properties.facing];assert.deepEqual(r.path[i-1],P(p.x-t.x,p.y,p.z-t.z));assert.deepEqual(r.path[i+1],P(p.x+t.x,p.y,p.z+t.z));}else assert.equal(b.id,W);}}
for(const r of d.routes)route(r);
function column(c){assert.equal((c.hi-c.lo)%4,0);for(let y=c.lo;y<=c.hi;y++)assert.equal(m.get(K(P(c.x,y,c.z)))?.id,(y-c.lo)%2?T:S);}
for(const c of d.columns)column(c);
let descentCells=0;for(const v of d.descents){const canon=makeSignalDescent({drop:v.drop});for(const b of canon.blocks){const p=P(b.position.x+v.origin.x,b.position.y+v.origin.y,b.position.z+v.origin.z);assert.deepEqual(m.get(K(p)),b.block);descentCells++;}}
for(const l of d.latches){const {x,y,z}=l.origin;assert.deepEqual(m.get(K(P(x+1,y,z))),{id:WT,properties:{facing:'east'}});assert.deepEqual(m.get(K(P(x+11,y,z))),{id:WT,properties:{facing:'west'}});assert.equal(m.get(K(l.q)).id,W);assert.equal(m.get(K(P(x-1,y,z))).properties.facing,'west');assert.equal(m.get(K(P(x+13,y,z))).properties.facing,'east');}
const blank=()=>Object.fromEntries(INPUTS.map(n=>[n,false])),eq=(n,v)=>Object.fromEntries(Array.from({length:4},(_,i)=>[n+i,v]));let physical=0;
function physicalEvaluate(v){const product=logic.rows.map(row=>{let level=15;for(const g of row.gates){let bit=+!!v[g.name],tower=logic.towers.find(t=>t.name===g.name);for(let y=tower.first_y+1;y<row.y;y+=2)bit=1-bit;const side=g.wanted?1-bit:bit;level=Math.max(0,level-15*side);}return level>0;});return Object.fromEntries(logic.or_columns.map(c=>{let state=false;for(let y=1;y<c.output_y;y+=2){const ri=logic.rows.findIndex(r=>r.y===y),inject=ri>=0&&product[ri]&&logic.rows[ri].bits.includes(c.bit);state=!(state||inject);}return[OUTPUTS[c.bit],state];}));}
for(const t of terms()){const v={...blank(),...t.literals};assert.deepEqual(physicalEvaluate(v),evaluate(v));physical++;for(const n of Object.keys(t.literals)){const x={...v,[n]:!v[n]};assert.deepEqual(physicalEvaluate(x),evaluate(x));physical++;}}
let ordered=0,negatives=0;const enabled={...blank(),...MASKS};
function advance(state,v,n=2){for(let i=0;i<n;i++){assert.deepEqual(physicalEvaluate({...v,...state}),evaluate({...v,...state}));state=step(v,state);}return state;}
const seq=[{},eq('owner_open',1),{},eq('payload_open',1),{},eq('commit_phase',1),{}];
for(let bits=0;bits<128;bits++){let state=Object.fromEntries(FLAGS.map((n,i)=>[n,!!(bits>>i&1)]));state=advance(state,{...enabled,initialize:true});assert(FLAGS.every(n=>!state[n]));for(let i=0;i<seq.length;i++){state=advance(state,{...enabled,...seq[i]});assert.equal(evaluate({...enabled,...seq[i],...state}).global_channels_quiet,i===6);ordered++;}for(let i=0;i<8;i++){const withdrawn={...enabled,['mask'+i]:0};assert(!evaluate({...withdrawn,...state}).global_channels_quiet);const cleared=advance(state,withdrawn);assert(FLAGS.every(n=>!cleared[n]));assert(!evaluate({...enabled,...cleared}).global_channels_quiet);negatives++;}}
// Omitted or unequal phase levels cannot manufacture a completed traversal.
for(const phase of['owner_open','payload_open','commit_phase'])for(let c=0;c<4;c++){let st=blank();for(const s of seq){const v={...enabled,...s};v[phase+c]=false;st=advance(st,v);}assert(!evaluate({...enabled,...st}).global_channels_quiet);negatives++;}
for(const n of ['any_owner','active','busy','commit_input','owner_open','payload_open','commit_phase'])for(let c=0;c<4;c++){const st=Object.fromEntries(FLAGS.map(n=>[n,true]));assert(!evaluate({...enabled,...st,[n+c]:true}).global_channels_quiet);negatives++;}
// Distinct physical phases can deadlock without overlapping all-channel highs.
let skew=blank();for(const phase of['owner_open','payload_open','commit_phase'])for(let c=0;c<4;c++){skew=advance(skew,{...enabled,[phase+c]:true});skew=advance(skew,enabled);}assert(!evaluate({...enabled,...skew}).global_channels_quiet);negatives++;
// A zero-duration model pulse does not simulate physical clearing: stale flags are unsafe.
const stale=Object.fromEntries(FLAGS.map(n=>[n,true]));assert(!evaluate({...enabled,...stale,mask0:false}).global_channels_quiet);assert(evaluate({...enabled,...stale}).global_channels_quiet); // Explicit duration obligation, never called a pass against short pulses.
for(const r of d.routes){const k=K(r.path[0]),old=m.get(k);m.delete(k);assert.throws(()=>route(r));m.set(k,old);negatives++;}
for(const c of d.columns){const k=K(P(c.x,c.lo+1,c.z)),old=m.get(k);m.delete(k);assert.throws(()=>column(c));m.set(k,old);negatives++;}
const out={status:'offline_retained_admission_close_component_checks_pass',...d.metrics,canonical_logic_cells:logic.blocks.length,canonical_descent_cells:descentCells,physical_product_cases:physical,arbitrary_initial_flag_patterns:128,ordered_phase_checks:ordered,negative_checks:negatives,shared_cadence_overlap_required:true,held_mask_clear_duration_required:true,native_acceptance:false,complete_component_geometry:false};console.log(JSON.stringify(out));if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');
