// Check the complete authored route delta against source-bound actual parent cells.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeMasterCoreServiceRoutes}from'../../../hardware/full-gpu-master-core-service-routes-v1.mjs';
import{possibleStrengths}from'../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
import{decodeSlice}from'../floorplan-v3/obstacles.mjs';
import{routeDelays}from'../../../scripts/check-route-delay.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=JSON.parse(readFileSync(new URL('./design.json',import.meta.url))),frame=JSON.parse(readFileSync(d.obstacle_path)),sha=b=>createHash('sha256').update(b).digest('hex');assert.deepEqual(makeMasterCoreServiceRoutes(),d);
const parents=[...decodeSlice(frame)].map(v=>({...v,part:'parent:'+v.instance})),parentIds=new Set(parents.map(v=>v.part));
function check(d,{expensive=true}={}){
 const all=[...parents,...d.blocks],m=new Map(all.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,all.length,'Collision');let supports=0,contacts=0,rears=0;const newKeys=new Set(d.blocks.map(v=>K(v.position)));
 for(const v of d.blocks){assert(v.position.y>=-64&&v.position.y<=319);if(v.block.id.endsWith('_concrete'))continue;const p={...v.position,y:v.position.y-1},support=at(p);assert(support,'Support '+K(v.position));if(v.block.id==='minecraft:redstone_wire'&&support.block.id==='minecraft:redstone_torch'){assert(d.columns.some(c=>c.x===v.position.x&&c.z===v.position.z&&c.output_y===v.position.y));}else assert.equal(support.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.output_y-c.bottom)%4,1);for(let y=c.bottom;y<c.output_y;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.output_y,c.z))?.block.id,'minecraft:redstone_wire');}
 for(const v of all.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||(!newKeys.has(K(v.position))&&!newKeys.has(K(q)))||o.block.id.endsWith('_concrete'))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q)+' '+v.part+' / '+o.part);contacts++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const s of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete'),'Foreign side '+K(v.position));}rears++;}
 assert.equal(d.connections.length,4);for(const c of d.connections){const permit=c.name.startsWith('core_normal'),core=Number(c.name.at(-1));assert([0,1].includes(core));assert.deepEqual(c.source,permit?P(-555,-46,550):P(-981+4*core,-47,845));assert.deepEqual(c.destination,permit?P(-542,1,-1552-1520*core):P(-758,77,-1737-1520*core));assert(at(c.source)&&parentIds.has(at(c.source).part));assert(at(c.destination)&&parentIds.has(at(c.destination).part));const r=at(c.normalizer);assert.equal(r?.block.id,'minecraft:repeater');assert.deepEqual(add(c.normalizer,D[r.block.properties.facing]),permit?c.injection_support:c.destination);
  if(permit){assert.equal(c.arrival_kind,'upper_solid_adapter');assert.deepEqual(c.injection_support,{...c.destination,y:c.destination.y+1});assert.deepEqual(c.rear_solid,{...c.input_wire,y:c.input_wire.y-1});assert.deepEqual(add(c.normalizer,neg(D[r.block.properties.facing])),c.rear_solid);assert.equal(at(c.rear_solid)?.block.id,'minecraft:light_gray_concrete');assert.equal(at(c.injection_support)?.block.id,'minecraft:light_gray_concrete');assert.equal(at(c.input_wire)?.block.id,'minecraft:redstone_wire');assert(d.borrowed_supports.some(s=>K(s.source)===K(c.normalizer)&&K(s.position)===K(c.injection_support)&&K(s.destination)===K(c.destination)));}
 }
 // Added support/route cells must not cap an inherited dust-step edge.
 const baseMap=new Map(parents.map(v=>[K(v.position),v])),affected=new Map();for(const v of d.blocks){const p={...v.position,y:v.position.y-1};if(baseMap.get(K(p))?.block.id==='minecraft:redstone_wire')affected.set(K(p),p);}
 const oldNeighbors=(p,world)=>{const out=[];for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(p,dir);q.y+=dy;if(baseMap.get(K(q))?.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&world.has(K({...p,y:p.y+1})))continue;if(dy===-1&&world.has(K({...q,y:q.y+1})))continue;out.push(K(q));}return out.sort();};for(const p of affected.values()){assert.deepEqual(oldNeighbors(p,m),oldNeighbors(p,baseMap),'Changed parent step '+K(p));for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(p,dir);q.y+=dy;if(baseMap.get(K(q))?.block.id==='minecraft:redstone_wire')assert.deepEqual(oldNeighbors(q,m),oldNeighbors(q,baseMap),'Changed reverse parent step '+K(q));}}
 // A new strongly driven solid may not acquire an unaccounted parent dust sink.
 let strongSolidScreens=0;for(const v of d.blocks.filter(v=>v.block.id==='minecraft:repeater')){const q=add(v.position,D[v.block.properties.facing]);if(at(q)?.block.id!=='minecraft:light_gray_concrete')continue;for(const delta of[...dirs,P(0,1,0),P(0,-1,0)]){const o=at(add(q,delta));assert(!o||o.block.id!=='minecraft:redstone_wire'||!parentIds.has(o.part)||d.borrowed_supports.some(s=>K(s.source)===K(v.position)&&K(s.position)===K(q)&&K(s.destination)===K(o.position)),'New strong solid powers parent dust '+K(q));strongSolidScreens++;}}
 const merged={...d,blocks:all,parents:[...parentIds].map(id=>({id})),ports:{}};
 const timing=routeDelays(merged);let power=null;if(expensive){power=possibleStrengths(merged);assert.deepEqual(power.failed,[]);assert(power.taps.every(v=>v.source_power>0),'Unpowered source tap');const inputPower=possibleStrengths({...merged,connections:d.connections.filter(c=>c.input_wire).map(c=>({name:c.name,source:c.input_wire}))});assert(inputPower.taps.every(v=>v.source_power>=3),'Unpowered solid-rear input');power.upper_adapter_input_power=inputPower.taps;}
 return{potentially_capped_parent_wires_checked:affected.size,new_supports:supports,new_contact_checks:contacts,new_directed_repeaters:rears,strong_solid_neighbor_screens:strongSolidScreens,possible_strength:power,nominal_timing:timing};
}
const result=check(d);let negatives=0;for(const mutate of[c=>{const p=c.connections[0].normalizer;c.blocks.find(v=>K(v.position)===K(p)).block.properties.facing='east';},c=>{const p=c.connections[1].normalizer;c.blocks=c.blocks.filter(v=>K(v.position)!==K(p));},c=>{c.connections[0].source=c.connections[2].source;}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c,{expensive:false}));negatives++;}
const output={status:'offline_master_program_quiet_front_permission_routes_checked',...d.metrics,...result,negative_refusals:negatives,source:{design:sha(readFileSync(new URL('./design.json',import.meta.url))),generator:sha(readFileSync(new URL('../../../hardware/full-gpu-master-core-service-routes-v1.mjs',import.meta.url))),obstacles:sha(readFileSync(d.obstacle_path))},complete_gpu_layout:false,native_calls:0,world_mutations:0,native_acceptance:false,limits:d.limits};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({...output,possible_strength:{...output.possible_strength,taps:undefined},nominal_timing:output.nominal_timing.routes.map(r=>({name:r.name,ticks:r.nominal_max_ticks}))}));
