// Source-bound rerouting only: one identical core template safe against both master cable copies.
import assert from'node:assert/strict';
import{readFileSync,writeFileSync,existsSync}from'node:fs';
import{createHash}from'node:crypto';
import{pathToFileURL}from'node:url';
import{P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),ROOT='artifacts/full-gpu-layout-v1/',W='minecraft:redstone_wire',S='minecraft:light_gray_concrete',sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
export function makeCompatible({plan=false}={}){
 assert.equal(sha(ROOT+'control-reset-final-v1/source-manifest.json'),'131bd19104a1822a2c041ebf29b1f7c4271ca1eee4f6a233c47bfa89e427517b');
 const base=read('../control-reset-final-v1/design.json'),frame=read('master-obstacles.json'),map=new Map(base.blocks.map(v=>[K(v.position),{...v,part:'core_parent'}])),parents={core_parent:{blocks:base.blocks.length}},edges=[],routes=[],connections=[],removed=[],restored_supports=[],master=[];
 const targets=[...Array.from({length:8},(_,i)=>['control-reset-zero-v1','pc_'+i+'_arrival_return']),['control-reset-epoch-v1','reset_blank_actual_return'],...Array.from({length:8},(_,i)=>['control-reset-final-v1','arch_zero_pc'+i]),...['external_reset_request','released_barrier1','exit_program_quiet','actual_START_low_guard','locks_closed_owner_next','locks_closed_owner_current'].map(n=>['control-reset-final-v1',n])];
 const configs=[];for(const pkg of new Set(targets.map(x=>x[0]))){const d=read('../'+pkg+'/design.json');for(const[owner,name]of targets.filter(x=>x[0]===pkg)){const c=d.connections.find(v=>v.name===name);assert(c,name);configs.push({...c,owner});const selected=d.blocks.filter(v=>v.part===name);assert(selected.length,name+' ownership');for(const v of selected){const old=map.get(K(v.position));assert.deepEqual(old?.block,v.block,'Parent route changed '+name+' '+K(v.position));removed.push({...v,owner});map.delete(K(v.position));}}}
 // A concrete support can have been borrowed by a later cable; retain those supports.
 for(const v of removed.filter(v=>v.block.id===S)){const above=map.get(K(P(v.position.x,v.position.y+1,v.position.z)));if(above&&!above.block.id.endsWith('_concrete')){map.set(K(v.position),{...v,part:'core_parent'});restored_supports.push(v.position);}}
 const removedKeys=new Set(removed.filter(v=>!map.has(K(v.position))).map(v=>K(v.position)));for(const e of base.edges)if(!removedKeys.has(K(e.from))&&!removedKeys.has(K(e.to)))edges.push(e);
 const allObstacles=new Map(map),pins={};for(const[name,c]of Object.entries(frame.route_deltas)){pins[c.path]=sha(c.path);pins[c.manifest]=sha(c.manifest);const d=JSON.parse(readFileSync(c.path));for(let core=0;core<2;core++)for(const v of d.blocks){const p=P(v.position.x+400,v.position.y,v.position.z+1552+1520*core);if(p.x<base.box.from.x-3||p.x>base.box.to.x+3||p.z<base.box.from.z-3||p.z>base.box.to.z+3)continue;master.push({position:p,block:v.block,part:'master_'+core+'_'+name,master_instance:core,original_position:v.position});if(!allObstacles.has(K(p)))allObstacles.set(K(p),{position:p,block:v.block,part:'external_obstacle'});}}
 // Payload receiving adapters are reserved explicitly while their full source freeze is pending.
 const reserved=[];for(let bit=0;bit<4;bit++){const s=base.ports.front.lane_enable.bits[bit].position;for(let x=-3;x<=5;x++)for(let y=-3;y<=5;y++)for(let z=-4;z<=4;z++)reserved.push(P(s.x+x,s.y+y,s.z+z));}
 let part='';const at=p=>allObstacles.get(K(p)),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),edge=(a,b)=>edges.push({from:a,to:b});
 function put(p,id,props){const block={id,...props?{properties:props}:{}};if(map.has(K(p))){assert(id===S&&map.get(K(p)).block.id===S,'Collision '+part+' '+K(p));return;}assert(!allObstacles.has(K(p)),'External collision '+part+' '+K(p));const row={position:p,block,part};map.set(K(p),row);allObstacles.set(K(p),row);}
 const solid=p=>put(p,S),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,W),rep=(p,d)=>dev(p,'minecraft:repeater',{facing:F[d],delay:'1'});
 const cacheURL=new URL('routes.json',import.meta.url),cache=existsSync(cacheURL)?read('routes.json'):{},pending=[],inherited=[];
 for(const file of Object.keys(read('../control-reset-final-v1/source-manifest.json').source_sha256).filter(p=>p.endsWith('/routes.json'))){const data=JSON.parse(readFileSync(file));for(const[name,r]of Object.entries(data))if(r?.source&&Array.isArray(r.path))inherited.push({file,name,...r});}
 for(const c of configs){if(c.name==='arch_zero_pc6'){const carrier=P(c.source.x,c.source.y-1,c.source.z),cap=P(c.source.x,c.source.y+1,c.source.z),tap=P(carrier.x,carrier.y,carrier.z+1),start=P(carrier.x,carrier.y,carrier.z+2);assert.equal(map.get(K(carrier))?.block.id,S);part=c.name;solid(cap);rep(tap,'south');wire(start);edge(c.source,carrier);edge(c.source,tap);edge(P(-275,57,-125),tap);edge(carrier,tap);edge(tap,start);const ad='south',end=step(c.destination,ad,-2);rep(c.arrival,ad);wire(end);edge(end,c.arrival);edge(c.arrival,c.destination);pending.push({...c,source_direction:'south',tap,start,end,arrival_direction:ad,carrier,cap});continue;}if(c.name==='actual_START_low_guard'){const carrier=P(-274,57,-125),tap=P(-274,57,-126),start=P(-274,57,-127);assert.deepEqual(map.get(K(P(-275,57,-125)))?.block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.equal(map.get(K(carrier))?.block.id,S);part=c.name;rep(tap,'north');wire(start);edge(P(-275,57,-125),tap);edge(carrier,tap);edge(tap,start);const ad='south',end=step(c.destination,ad,-2);rep(c.arrival,ad);wire(end);edge(end,c.arrival);edge(c.arrival,c.destination);pending.push({...c,source_direction:'north',tap,start,end,arrival_direction:ad,carrier,existing_source_normalizer:P(-275,57,-125)});continue;}const oldDir=Object.keys(V).find(d=>K(step(c.source,d))===K(c.tap)),ad=Object.keys(V).find(d=>K(step(c.arrival,d))===K(c.destination));assert(ad,c.name+' arrival');let dir=cache[c.name]?.source_direction;
 const free=(s,d)=>{if(!d||![1,2].every(i=>{const p=step(s,d,i);return !at(p)&&(!at(P(p.x,p.y-1,p.z))||at(P(p.x,p.y-1,p.z)).block.id===S)&&at(P(p.x,p.y-2,p.z))?.block.id!==W;}))return false;const st=step(s,d,2),allowed=new Set([K(s),K(step(s,d)),K(st),K(P(st.x,st.y-1,st.z)),K(P(step(s,d).x,s.y-1,step(s,d).z))]);return Object.values(V).some(([dx,dz])=>[-1,0,1].some(dy=>{const p=P(st.x+dx,st.y+dy,st.z+dz);if(at(p)||at(P(p.x,p.y-1,p.z)))return false;for(const[x,z]of Object.values(V))for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(at(q)&&!allowed.has(K(q)))return false;}for(const y of[-2,1,2]){const q=P(p.x,p.y+y,p.z);if(at(q)&&!allowed.has(K(q)))return false;}return true;}));};
 if(cache[c.name]?.original_source){c.original_source=cache[c.name].original_source;c.source=cache[c.name].source;c.inherited_observation=cache[c.name].inherited_observation;}
 if(!dir&&c.name.startsWith('arch_zero_pc')&&[1,2].every(i=>!at(step(c.source,oldDir,i))&&!at(P(step(c.source,oldDir,i).x,c.source.y-1,step(c.source,oldDir,i).z))))dir=oldDir;
 if(!dir)dir=[oldDir,...Object.keys(V).filter(d=>d!==oldDir)].find(d=>free(c.source,d));
 if(!dir){outer:for(const r of inherited.filter(r=>K(r.source)===K(c.source)||K(r.destination)===K(c.source))){if(!r.path.every(p=>['minecraft:redstone_wire','minecraft:repeater'].includes(map.get(K(p))?.block.id)))continue;for(let i=0;i<r.path.length;i++){const p=r.path[i];if(map.get(K(p))?.block.id!==W)continue;dir=Object.keys(V).find(d=>free(p,d));if(dir){c.original_source=c.source;c.source=p;c.inherited_observation={file:r.file,name:r.name,index:i};break outer;}}}}assert(dir,'No free tap '+c.name);const tap=step(c.source,dir),start=step(c.source,dir,2),end=step(c.destination,ad,-2);part=c.name;rep(tap,dir);wire(start);rep(c.arrival,ad);wire(end);edge(c.source,tap);edge(tap,start);edge(end,c.arrival);edge(c.arrival,c.destination);pending.push({...c,source_direction:dir,tap,start,end,arrival_direction:ad});}
 const tails=Object.fromEntries(pending.map(c=>[c.name,Array.from({length:c.name==='pc_3_arrival_return'?5:17},(_,i)=>step(c.end,c.arrival_direction,i-(c.name==='pc_3_arrival_return'?4:16)))]));for(const tail of Object.values(tails))reserved.push(...tail);
 for(const c of pending){part=c.name;let path=cache[c.name]?.path;if(!path){assert(plan,'Missing route '+c.name);const ignore=[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(p=>P(p.x,p.y-1,p.z))],forbidden=[c.tap,c.arrival].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![c.source,c.start,c.end,c.destination].some(q=>K(p)===K(q)));const prefix=c.name==='pc_6_arrival_return'?[P(29,252,48),P(28,252,48),P(27,252,48)]:[c.start];ignore.push(...prefix,...prefix.map(p=>P(p.x,p.y-1,p.z)));for(const p of prefix.slice(0,-1))forbidden.push(...[-2,-1,0,1,2].map(y=>P(p.x,p.y+y,p.z)),...Object.values(V).flatMap(([x,z])=>[-1,0,1].map(y=>P(p.x+x,p.y+y,p.z+z))));const tail=tails[c.name],goal=tail[0];ignore.push(...tail,...tail.map(p=>P(p.x,p.y-1,p.z)));for(const p of tail.slice(1))forbidden.push(...[-2,-1,0,1,2].map(y=>P(p.x,p.y+y,p.z)),...Object.values(V).flatMap(([x,z])=>[-1,0,1].map(y=>P(p.x+x,p.y+y,p.z+z))));let result;try{result=searchPath(allObstacles,prefix.at(-1),goal,{limit:650000,ignore,forbidden,reserved:[...reserved,...pending.filter(q=>q!==c).flatMap(q=>[q.start,q.end])]});}catch(error){writeFileSync(new URL('route-failure.json',import.meta.url),JSON.stringify({name:c.name,start:c.start,goal,near:[...allObstacles.values()].filter(v=>Math.abs(v.position.x-c.start.x)<=4&&Math.abs(v.position.y-c.start.y)<=4&&Math.abs(v.position.z-c.start.z)<=4)},null,2));throw error;}path=[...prefix.slice(0,-1),...result.path,...tail.slice(1)];cache[c.name]={source:c.source,destination:c.destination,source_direction:c.source_direction,path,expanded:result.expanded,...c.original_source?{original_source:c.original_source,inherited_observation:c.inherited_observation}:{}};writeFileSync(cacheURL,JSON.stringify(cache)+'\n');console.error(c.name+': '+path.length);}
 assert.deepEqual(path[0],c.start);assert.deepEqual(path.at(-1),c.end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],n=path[i+1],dir=Object.keys(V).find(d=>K(step(p,d))===K(n));if(refresh.includes(i)){assert(dir);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name:c.name,path,refresh_indices:refresh});connections.push(c);}
 const blocks=[...map.values()];return{status:'mutable_core_master_compatibility_reroute',blocks,box:base.box,parents,ports:base.ports,edges,routes,connections,removed:removed.filter(v=>removedKeys.has(K(v.position))),restored_supports,master_obstacle_source_sha256:pins,metrics:{blocks:blocks.length,retained_bits:base.metrics.retained_bits,replaced_routes:configs.length,connections:connections.length},native_acceptance:false,master_composition_accepted:false};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeCompatible({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
