import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeChannelAllocator}from'../../../../hardware/memory-layout-channel-allocator.mjs';import{makeDataOwner}from'../../../../hardware/memory-layout-data-owner.mjs';
const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),V={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',digest=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const d=makeChannelAllocator(),parent=makeDataOwner(),m=new Map(d.blocks.map(v=>[K(v.position),v.block]));assert.equal(digest(d),digest(JSON.parse(readFileSync(new URL('design.json',import.meta.url)))));
function check(map){let preserved=0;for(let channel=0;channel<4;channel++)for(const v of parent.blocks)if(['eligible_columns','priority_product'].includes(parent.groups[K(v.position)])){const p=P(v.position.x+128*channel,v.position.y+80*channel,v.position.z);assert.deepEqual(map.get(K(p)),v.block);preserved++;}
 for(const g of d.matrices){for(const p of[g.grant_gate,g.availability_gate])assert.deepEqual(map.get(K(p)),{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});for(const p of[g.busy_mask,g.grant_mask])assert.deepEqual(map.get(K(p)),{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});}
 for(const l of d.links){assert.deepEqual(map.get(K(l.driver)),{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});assert.equal(map.get(K(l.next_input))?.id,W);assert.deepEqual(l.next_input,P(128*(l.channel+1)+5*l.consumer,80*(l.channel+1)+1,-7));}
 for(const p of d.ports.grant.positions)assert.equal(map.get(K(p))?.id,W);return preserved;
}
const preserved=check(m);let supports=0,steps=0;for(const v of d.blocks){const p=v.position,b=v.block;if(b.id===S||b.id==='minecraft:redstone_block')continue;let q=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const[dx,dz]=V[b.properties.facing];q=P(p.x+dx,p.y,p.z+dz);}assert.equal(m.get(K(q))?.id,S,'support '+K(p));supports++;}
for(const r of d.routes){assert(r.max_dust_run<=14);for(let i=0;i<r.path.length;i++){const p=r.path[i],b=m.get(K(p));if(i)steps++;if(b.id==='minecraft:repeater'){const[dx,dz]=V[b.properties.facing];assert.deepEqual(r.path[i-1],P(p.x-dx,p.y,p.z-dz));assert.deepEqual(r.path[i+1],P(p.x+dx,p.y,p.z+dz));}else assert.equal(b.id,W);}}
let cases=0;for(let req=0;req<256;req++)for(let busy=0;busy<16;busy++){
 const expected=Array.from({length:4},()=>Array(8).fill(0));let unused=req;for(let c=0;c<4;c++)if(!(busy&(1<<c)))for(let i=0;i<8;i++)if(unused&(1<<i)){expected[c][i]=1;unused&=~(1<<i);break;}
 let a=Array.from({length:8},(_,i)=>(req>>i)&1);const actual=[];for(let c=0;c<4;c++){const g=a.map((v,i)=>Number(v&&!a.slice(0,i).some(Boolean)&&!(busy&(1<<c))));actual.push(g);a=a.map((v,i)=>Number(v&&!g[i]));}assert.deepEqual(actual,expected);assert.equal(a.reduce((n,v,i)=>n+(v<<i),0),unused);cases++;
}
let negatives=0;for(const[p,b]of[[P(44,1,0),{id:'minecraft:comparator',properties:{facing:'east',mode:'subtract'}}],[P(60,37,-54),{id:'minecraft:comparator',properties:{facing:'west',mode:'compare'}}],[P(128,81,-8),null],[P(256+5*7,161,-8),null],[P(44,1,1),null],[P(46,1,0),null]]){const mm=new Map(m);if(b===null)mm.delete(K(p));else mm.set(K(p),b);assert.throws(()=>check(mm));negatives++;}
const out={status:'offline_original_order_grant_matrix_checks_pass',...d.metrics,priority_subset_positions_preserved:preserved,supports,route_steps:steps,settled_request_busy_vectors:cases,negative_cases:negatives,complete_allocator_with_state_and_barrier:false,native_acceptance:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
