// Classify actual transport SCCs against the intended seven-SR-state contract.
// Settled fixed points are conditional offline evidence, not Minecraft events.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{evaluate,K}from'../../dispatch-external-bindings-v1/transport-functions.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},P=(x,y,z)=>({x,y,z});function bytes(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return b;}const read=n=>JSON.parse(bytes(n)),scope=read('reference-scope.json'),body=read('witness-bodies.json'),refusal=read('transport-cycle-refusal.json'),controller=read('../../memory/admission-close-v1/controller.json'),w=new Map([...scope.blocks,...scope.foreign_context].map(v=>[K(v.position),v.block])),bodyKeys=new Set(body.blocks.map(v=>K(v.position))),transport=new Set(scope.blocks.filter(v=>active(v.block)&&!bodyKeys.has(K(v.position))).map(v=>K(v.position)));
for(const l of body.latches)transport.add(K(l.clear));const D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},results=[];
for(const component of refusal.components){const members=new Set(component.cells.map(v=>K(v.position))),names=[...new Set(component.cells.map(v=>controller.nets[K(P(v.position.x-680,v.position.y,v.position.z+380))]))];assert.equal(names.length,1);const name=names[0],latch=body.latches.find(l=>l.name===name);assert(latch);const entries=component.cells.flatMap(v=>inputs(w,v.position).filter(p=>!members.has(K(p))).map(p=>({source:p,target:v.position})));assert.equal(entries.length,1);const entry=entries[0],prefix=new Set(),todo=[entry.source];for(let i=0;i<todo.length;i++){const p=todo[i],k=K(p);if(prefix.has(k)||!transport.has(k))continue;assert(!members.has(k));prefix.add(k);todo.push(...inputs(w,p));}const prefixFunction=evaluate(w,prefix).get(entry.source);assert.deepEqual(prefixFunction,{roots:[latch.q],table:2});
 const repeaters=component.cells.filter(v=>v.block.id==='minecraft:repeater');assert.equal(repeaters.length,7);for(const v of repeaters){const d=D[v.block.properties.facing],rear=P(v.position.x-d.x,v.position.y,v.position.z-d.z);assert.deepEqual(inputs(w,v.position),[rear],'Additional rear/lock/clear input');assert.equal(w.get(K(rear)).id,'minecraft:redstone_wire');}
 const levels=new Map(repeaters.map(v=>[K(v.position),15]));let changed=true;while(changed){changed=false;for(const v of component.cells.filter(v=>v.block.id==='minecraft:redstone_wire')){const n=Math.max(0,...inputs(w,v.position).map(p=>{const level=members.has(K(p))?(levels.get(K(p))??0):0;return Math.max(0,level-(w.get(K(p)).id==='minecraft:redstone_wire'?1:0));}));if(n>(levels.get(K(v.position))??0)){levels.set(K(v.position),n);changed=true;}}}
 let rearMin=15;for(const v of component.cells){const received=inputs(w,v.position).map(p=>members.has(K(p))?(levels.get(K(p))??0):0);const n=v.block.id==='minecraft:repeater'?(Math.max(...received)>0?15:0):Math.max(0,...inputs(w,v.position).map(p=>Math.max(0,(members.has(K(p))?(levels.get(K(p))??0):0)-(w.get(K(p)).id==='minecraft:redstone_wire'?1:0))));assert.equal(levels.get(K(v.position))??0,n,'Not an actual strength fixed point');if(v.block.id==='minecraft:repeater')rearMin=Math.min(rearMin,...received);}
 assert(rearMin>0);assert(component.cells.every(v=>inputs(w,v.position).every(p=>members.has(K(p))||K(p)===K(entry.source))));
 results.push({flag:name,classification:'unintended_stale_positive_transport_retention_under_original_seven_SR_state_contract',expected_state:latch,component_vertices:89,dust_vertices:82,repeater_vertices:7,entry,prefix_function:prefixFunction,phase_or_clear_gates_inside_component:0,repeater_side_lock_inputs:0,source_low_fixed_points:{all_low:true,high_ring:true,high_ring_minimum_repeater_rear:rearMin,high_ring_levels:Object.fromEntries(levels)},conditional_cases:[{source_Q:0,ring:'low',result:'valid_low_fixed_point'},{source_Q:1,ring:'high',result:'valid_asserted_transport_state'},{source_Q:0,ring:'previously_high',result:'valid_uncommanded_high_fixed_point_exists'},{all_masks_held:false,SR_Q_after_successful_clear:0,result:'no_direct_ring_clear_input; stale_high_fixed_point_still_exists'},{initialize:true,SR_Q_after_successful_clear:0,result:'no_direct_ring_clear_input; stale_high_fixed_point_still_exists'}],repair_requirement:'In a new derivative, redraw this Q-to-logic return as an isolated positive acyclic cable; retain the actual SR state and reset/clear source semantics. Then prove source-high, source-low, release after high, and clear/init delivery in the corrected graph; event/state timing remains a separate gate.'});
}
bytes('classify-cycles.mjs');bytes('../../memory/admission-close-v1/logic.mjs');bytes('../../memory/admission-close-v1/README.md');bytes('../../../../hardware/memory-layout-admission-close.mjs');bytes('../../dispatch-external-bindings-v1/transport-functions.mjs');bytes('../../memory/fabric-colocation-v2/cut-inputs.mjs');
const report={status:'seven_original_feedback_SCCs_classified_as_unintended_extra_transport_retention_conditionally',metrics:{cycles:results.length,cycle_vertices:623,extra_repeater_vertices:49,declared_SR_state_bits:7,held_source_release_cases:35},classifications:results,source_sha256:pins,limits:['The contract explicitly supplies seven SR stores and Q-to-literal feedback cables; it does not specify these seven unreset positive repeater rings as additional state or phase machinery.','Existence of a valid source-low high-ring fixed point under the actual effective input/strength model distinguishes extra retention from a simple transport path; it is not a native scheduling trace or proof every falling event gets trapped.','No source map has been changed and no corrected service-quiet body is selected.','Physical reset/state transition timing and arbitrary startup are not established by held-boundary fixed points.'],native_acceptance:false};writeFileSync(new URL('cycle-classification.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
