// Read-only recovery of actual repaired source cells; never regenerate stale parents.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
function bytes(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return b;}const read=n=>JSON.parse(bytes(n));
const meta=read('../../memory/fabric-colocation-v2/cell-labels.json'),census=read('../../memory/fabric-colocation-v2/boundary-census.json'),labelBytes=bytes('../../memory/fabric-colocation-v2/cell-labels.u16le'),buffer=bytes('../../memory/master-cold-compatible-v2/design.json');assert.equal(pins['artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v2/design.json'],'364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');
const labels=new Uint16Array(labelBytes.buffer,labelBytes.byteOffset,labelBytes.length/2),ids=new Set(meta.labels.flatMap((n,i)=>['current/witness','current/actual_mask_returns','current/actual_channel_phase_and_state_returns','current/actual_initialize_return','current/actual_witness_source_connections','current/quiet_output_export'].includes(n)?[i]:[]));
function scanBuffer(buffer,visit,expected=null){const marker=Buffer.from('"blocks"'),at=buffer.indexOf(marker);assert(at>=0);const start=buffer.indexOf(91,at+marker.length);let i=start+1,chunk=i,depth=0,quoted=false,escape=false,count=0,index=0;const accept=end=>{const str=buffer.subarray(chunk,end).toString();if(str.trim())for(const row of JSON.parse('['+str+']'))visit(row,index++);};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){accept(i);if(expected!==null)assert.equal(index,expected);return index;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0){if(++count===4096){accept(i);chunk=i+1;count=0;}}}throw Error('Unterminated block stream');}
const own=[],selected=new Map(),buckets=new Set(),bucket=p=>`${Math.floor(p.x/16)},${Math.floor(p.y/16)},${Math.floor(p.z/16)}`,groupCounts={};
scanBuffer(buffer,(v,i)=>{if(!ids.has(labels[i]))return;const group=meta.labels[labels[i]],r={...v,group};own.push(r);selected.set(K(v.position),r);groupCounts[group]=(groupCounts[group]??0)+1;for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)buckets.add(bucket(P(v.position.x+16*x,v.position.y+16*y,v.position.z+16*z)));});assert.equal(own.length,199408);console.log(JSON.stringify({selected:own.length,groups:Object.keys(groupCounts).length}));
const offsets=[];for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)offsets.push(P(x,y,z));
const world=new Map(own.map(r=>[K(r.position),r.block])),context=[],groups=new Map(own.map(r=>[K(r.position),r.group]));
scanBuffer(buffer,(v,i)=>{if(ids.has(labels[i])||!buckets.has(bucket(v.position)))return;if(!offsets.some(o=>selected.has(K(P(v.position.x+o.x,v.position.y+o.y,v.position.z+o.z)))))return;world.set(K(v.position),v.block);groups.set(K(v.position),meta.labels[labels[i]]);context.push({...v,group:meta.labels[labels[i]]});});console.log(JSON.stringify({actual_foreign_halo:context.length}));
// External master routes are absent from the memory design; bind the exact original selected world.
const cfg=read('../../dispatch-global-colocation-v1/selected-config.json'),master=[];
const paths=[...new Set(cfg.instances.filter(c=>c.name!=='memory').map(c=>c.path))];
for(const path of paths){const data=bytes('../../../../'+path),frames=cfg.instances.filter(c=>c.path===path);for(const c of frames)assert.equal(pins[path],c.sha256);
 const count=scanBuffer(data,v=>{for(const c of frames){const p=P(v.position.x+c.translation.x,v.position.y+c.translation.y,v.position.z+c.translation.z);if(!buckets.has(bucket(p))||!offsets.some(o=>selected.has(K(P(p.x+o.x,p.y+o.y,p.z+o.z)))))continue;const k=K(p);assert(!world.has(k),'Foreign overlap '+c.name+' '+k);world.set(k,v.block);groups.set(k,'master/'+c.name);const row={position:p,block:v.block,group:'master/'+c.name};context.push(row);master.push(row);}});console.log(JSON.stringify({foreign_source:path,scanned:count,retained_master:master.length}));
}
const cuts=[],groupCuts=[],internalCounts={},stores=[],R='minecraft:repeater',DIR={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};let activeReceivers=0,internalInputs=0;
for(const [k,b]of world){if(!active(b))continue;const target=selected.get(k),p=P(...k.split(',').map(Number));if(!target&&!offsets.some(o=>Math.abs(o.x)+Math.abs(o.y)+Math.abs(o.z)<=2&&selected.has(K(P(p.x+o.x,p.y+o.y,p.z+o.z)))))continue;if(target)activeReceivers++;for(const q of inputs(world,p)){const source=selected.get(K(q));if(!source&&!target)continue;const row={source:q,target:p,source_group:groups.get(K(q)),target_group:groups.get(k),source_block:world.get(K(q)),target_block:b};if(source&&target){internalInputs++;if(source.group===target.group)internalCounts[source.group]=(internalCounts[source.group]??0)+1;else groupCuts.push(row);}else cuts.push({...row,direction:source?'outgoing':'incoming'});}
 if(target&&b.id===R){const d=DIR[b.properties.facing],locks=[];for(const o of Object.values(DIR)){if(o.x*d.x+o.z*d.z)continue;const q=P(p.x+o.x,p.y,p.z+o.z),other=world.get(K(q));if([R,'minecraft:comparator'].includes(other?.id)){const v=DIR[other.properties.facing];if(K(P(q.x+v.x,q.y,q.z+v.z))===k)locks.push(q);}}if(locks.length)stores.push({position:p,block:b,locks,group:target.group});}
}
const controller=read('../../memory/admission-close-v1/controller.json'),ports=read('../../memory/admission-close-v1/ports.json'),T=p=>P(p.x+680,p.y,p.z-380),witness=[];
assert.equal(controller.blocks.length,27473);for(const v of controller.blocks){const p=T(v.position),actual=selected.get(K(p));assert(actual?.group==='current/witness');assert.deepEqual(actual.block,v.block);witness.push({...actual,part:controller.groups[K(v.position)],original_template_position:v.position});}
const latches=controller.latches.map(l=>({...l,origin:T(l.origin),q:T(l.q),set:T(l.set),clear:T(l.clear)}));assert.equal(latches.length,7);assert.equal(stores.length,0);
const preciseGroup=new Map(own.map(v=>[K(v.position),v.group]));for(const v of witness)preciseGroup.set(K(v.position),'witness/'+v.part);
const fineCuts=[];for(const v of own)if(active(v.block))for(const p of inputs(world,v.position)){if(selected.has(K(p))&&preciseGroup.get(K(p))!==preciseGroup.get(K(v.position)))fineCuts.push({source:p,target:v.position,source_group:preciseGroup.get(K(p)),target_group:preciseGroup.get(K(v.position)),source_block:world.get(K(p)),target_block:v.block});}
const bodyKeys=new Set(witness.filter(v=>['phase_logic','phase_witness_latches'].includes(v.part)).map(v=>K(v.position))),body=own.filter(v=>bodyKeys.has(K(v.position))).map(v=>({...v,body:preciseGroup.get(K(v.position))})),incident=[...fineCuts,...cuts].filter(v=>bodyKeys.has(K(v.source))!==bodyKeys.has(K(v.target)));
bytes('extract.mjs');bytes('../../memory/fabric-colocation-v2/cut-inputs.mjs');bytes('../../control-commit-v2/route.mjs');bytes('../../memory/admission-close-v1/logic.mjs');bytes('../../../../hardware/memory-layout-admission-close.mjs');bytes('../../../../hardware/memory-layout-admission-close-joined.mjs');
const metrics={actual_original_cells:own.length,witness_cells:witness.length,witness_matrix_and_state_body_cells:body.length,retained_SR_witness_states:7,side_locked_stores:stores.length,actual_original_input_sources:Object.keys(ports.sources).length,active_receivers:activeReceivers,internal_effective_inputs:internalInputs,external_cuts:cuts.length,coarse_group_cuts:groupCuts.length,fine_group_cuts:fineCuts.length,body_incident_cuts:incident.length,foreign_context:context.length,master_context:master.length,export_cells:groupCounts['current/quiet_output_export'],original_transport_and_export_cells:own.length-body.length};
const semantics={flags:controller.latches.map(v=>v.name),logic:controller.logic,meaning:'Seven retained flags require mask-held, initialize-low, ordered all-channel owner/payload/commit traversal and live empty owner/ACTIVE/BUSY/commit/phase conditions. Actual mask withdrawal or initialize clears every flag.',raw_global_quiet_alias_not_allowed:true,input_sources:ports.sources,input_bindings:ports.bindings,output:ports.global_channels_quiet,latches};
const report={status:'actual_service_quiet_producer_and_full_source_transport_inventory_unplaced',metrics,groupCounts,semantics,source_sha256:pins,limits:['All 199408 original cells are inventoried, not newly placed or claimed connected to compact modules.','The 12965 actual matrix/state bodies and 21 state/control joins are a possible bounded refold; real current memory source bindings still require source-specific mapping.','The 37 actual input sources are not interchangeable with generic phase, drain or READY signals. Every external cut and old source identity remains explicit.','Retained flags are physical state, not host runtime state. Shared phase overlap, low-mask clear duration, source freshness, arbitrary startup and full timing/native behavior remain open.'],native_acceptance:false};
writeFileSync(new URL('inventory.json',H),JSON.stringify(report,null,2)+'\n');writeFileSync(new URL('reference-scope.json',H),JSON.stringify({blocks:own,foreign_context:context,witness,source_sha256:pins})+'\n');writeFileSync(new URL('actual-cuts.json',H),JSON.stringify({external:cuts,between_groups:groupCuts,fine_witness_cuts:fineCuts,body_incident:incident,source_sha256:pins},null,2)+'\n');writeFileSync(new URL('witness-bodies.json',H),JSON.stringify({blocks:body,latches,source_sha256:pins})+'\n');console.log(JSON.stringify(metrics));
