import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {makeDispatchStartupLogic,INPUTS} from '../../../../hardware/full-gpu-dispatch-startup-logic.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeDispatchStartupLogic(),dense=makeDispatchStartupLogic({dense:true});assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to)));assert.equal(m.size,d.blocks.length);let supports=0,dustScreens=0,directions=0,minRear=15,sideScreens=0;
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const support=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(support)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 const rep=(p,out)=>{assert.equal(at(p)?.block.id,'minecraft:repeater','Repeater '+K(p));assert.deepEqual(add(p,D[at(p).block.properties.facing]),out);directions++;};
 for(const t of d.towers){for(let y=t.first_y;y<=t.last_y;y++)assert.equal(at(P(t.x,y,t.z))?.block.id,'minecraft:'+(y%2?'light_gray_concrete':'redstone_torch'));const p=d.ports[t.name].bits[0];rep(p.receiver,P(t.x,t.first_y,-5));}
 for(const row of d.rows){let power=15;for(let i=0;i<row.path.length;i++){const p=row.path[i],v=at(p),prior=at(row.path[i-1]??p);assert(v);if(v.block.id==='minecraft:repeater'){rep(p,add(p,P(1,0,0)));minRear=Math.min(minRear,power);assert(power>0);power=15;}else if(v.block.id==='minecraft:comparator'){assert.deepEqual(v.block.properties,{facing:'west',mode:'subtract'});assert.equal(prior.block.id,'minecraft:repeater');power=15;}else if(v.block.id==='minecraft:redstone_wire'){if(prior.block.id==='minecraft:redstone_wire')power--;assert(power>0);}else assert.equal(v.block.id,'minecraft:redstone_block');}
  for(const gate of row.gates){const {x,y,z}=gate.tower;assert.equal(z,-5);assert.equal(at(P(x,y,-4))?.block.id,'minecraft:'+(gate.wanted?'redstone_wall_torch':'redstone_wire'));if(gate.wanted)assert.equal(at(P(x,y,-4)).block.properties.facing,'south');else rep(P(x,y,-3),P(x,y,-2));rep(gate.mask,gate.comparator);assert.equal(at(P(x,y,-2)).block.id,'minecraft:redstone_wire');assert.equal(at(P(x+1,y,-2)).block.id,'minecraft:redstone_wire');}
  for(const bit of row.bits){const c=d.or_columns[bit];rep(P(c.x,row.y,2),P(c.x,row.y,3));assert.equal(at(P(c.x,row.y,1)).block.id,'minecraft:redstone_wire');}
 }
 for(const c of d.or_columns){for(let y=1;y<c.output_y;y++)assert.equal(at(P(c.x,y,3)).block.id,'minecraft:'+(y%2?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.output_y,3)).block.id,'minecraft:redstone_torch');rep(P(c.x,c.output_y,4),P(c.x,c.output_y,5));if(c.fixed_injection_y)rep(P(c.x+1,c.fixed_injection_y,3),P(c.x,c.fixed_injection_y,3));}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs){const p=add(v.position,delta),o=at(p);if(o&&!o.block.id.endsWith('_concrete'))assert(allowed.has(pair(v.position,p)),'Unlisted contact '+pair(v.position,p));for(const dy of[-1,1]){const q={...p,y:p.y+dy};if(at(q)?.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert.fail('Unexpected dust step '+pair(v.position,q));}dustScreens++;}
 for(const v of d.blocks.filter(v=>['minecraft:repeater','minecraft:comparator'].includes(v.block.id))){const delta=D[v.block.properties.facing];for(const s of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,s),b=at(p)?.block;if(b&&!b.id.endsWith('_concrete'))assert(v.block.id==='minecraft:comparator'&&b.id==='minecraft:repeater'&&allowed.has(pair(v.position,p)),'Unexpected diode side '+pair(v.position,p));sideScreens++;}}
 let cases=0;for(let mask=0;mask<2048;mask++){const inputs=Object.fromEntries(INPUTS.map((n,i)=>[n,Number(mask>>i&1)]));
  const products=d.rows.map(row=>{let value=15;for(const g of row.gates){const t=d.towers.find(t=>t.name===g.name);let signal=inputs[g.name];for(let y=t.first_y+1;y<row.y;y+=2)signal=1-signal;const mask=g.wanted?1-signal:signal;value=Math.max(0,value-mask*15);}return value>0;});
  let actual=0;for(const c of d.or_columns){let previous=false;for(let y=1;y<c.output_y;y+=2){const index=d.rows.findIndex(r=>r.y===y),inject=(index>=0&&products[index]&&d.rows[index].bits.includes(c.bit))||(y===c.fixed_injection_y&&!!inputs['fixed_next_'+c.bit]);previous=!(previous||inject);}if(previous)actual|=1<<c.bit;}
  const i=inputs,p=!!(i.ready&&i.selected&&i.admitted),cold=!p,expected=Number(!!i.ready)|(Number(!!(i.ready&&i.selected))<<1)|(Number(p)<<2)|(Number(cold)<<3)|(Number(!!(i.phase_a&&(cold||(i.capture&&!i.owner))))<<4)|(Number(!!(i.phase_a&&(cold||(i.capture&&i.owner))))<<5)|(Number(p&&!!i.done)<<6)|(Number(p&&!!i.start0)<<7)|(Number(cold||!!i.reset0)<<8)|(Number(p&&!!i.start1)<<9)|(Number(cold||!!i.reset1)<<10);assert.equal(actual,expected,JSON.stringify({mask}));cases++;
 }
 return{support_checks:supports,directed_repeater_checks:directions,dust_neighbor_screens:dustScreens,diode_side_screens:sideScreens,minimum_true_row_rear_power:minRear,complete_conditional_domain_cases:cases};}
const checks=check(d),baseline=check(dense);const bad=structuredClone(d);bad.blocks.find(v=>K(v.position)===K(bad.rows[0].gates[0].mask)).block.properties.facing='south';assert.throws(()=>check(bad));const cut=structuredClone(d);cut.blocks=cut.blocks.filter(v=>K(v.position)!==K(cut.ports.owner.bits[0].receiver));assert.throws(()=>check(cut));
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const result={status:'offline_dispatch_startup_boundary_gate_checks_pass',...d.metrics,...checks,corruption_refusals:2,dense_comparison:{blocks:dense.metrics.blocks,checks:baseline,saved_local_blocks:dense.metrics.blocks-d.metrics.blocks,scope:'Same11logicalinputs/11outputs; all gate costs counted, full route cost and timing separate.'},sources:{generator:sha('../../../../hardware/full-gpu-dispatch-startup-logic.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,limits:['Finite settled model follows declared gates and verified polarity; not native block updates or weak/strong-power simulation.','All2048 Boolean inputs checked, including arbitrary READY/SELECT/ADMIT and illegal simultaneous phase/capture combinations; raw initialize must force READY low through the specified full transfer before release.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
