// Shared-PC refinement: compare selected target values, not predicate identity.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {makeBranchAgreement} from '../control-nextpc-v1/agreement.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,V={east:[1,0],west:[-1,0],south:[0,1],north:[0,-1]},F={east:'west',west:'east',south:'north',north:'south'};
export function makeTargetAgreement(){
 const parent=makeBranchAgreement(),map=new Map(parent.blocks.map(b=>[K(b.position),structuredClone(b)])),edges=structuredClone(parent.edges),routes=[],xors=[];
 const edge=(a,b)=>edges.push({from:a,to:b}),join=ps=>{for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);};
 function put(p,id,props,part){const block={id:'minecraft:'+id,...(props?{properties:props}:{})},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'collision '+K(p));return;}map.set(K(p),{position:p,block,part});}
 const solid=(p,n)=>put(p,'light_gray_concrete',undefined,n),dev=(p,id,props,n)=>{solid(P(p.x,p.y-1,p.z),n+'_support');put(p,id,props,n);},wire=(p,n)=>dev(p,'redstone_wire',undefined,n),rep=(p,d,n)=>dev(p,'repeater',{facing:F[d],delay:'1'},n);
 const xorBlocks=parent.blocks.filter(b=>b.part==='xor1'||b.part==='xor1_support'),xorSet=new Set(xorBlocks.map(b=>K(b.position))),xorEdges=parent.edges.filter(e=>xorSet.has(K(e.from))&&xorSet.has(K(e.to)));
 for(let bit=0;bit<8;bit++){const move=p=>P(p.x+60,p.y,p.z+16*bit);for(const b of xorBlocks)put(move(b.position),b.block.id.slice(10),b.block.properties,'target_xor_'+bit);for(const e of xorEdges)edge(move(e.from),move(e.to));const y=1,z=4+16*bit;
  rep(P(73,y,z),'east','target_merge_'+bit);wire(P(74,y,z),'target_merge_'+bit);wire(P(75,y,z),'target_merge_'+bit);wire(P(76,y,z),'target_merge_'+bit);join([72,73,74,75,76].map(x=>P(x,y,z)));xors.push({bit,immediate:move(P(-2,1,0)),incremented_pc:move(P(-2,1,8)),xor:move(P(12,1,4)),merge:P(76,y,z)});
 }
 for(let z=4;z<=130;z++){if([15,27,39,51,63,75,87,99,111,123].includes(z))rep(P(76,1,z),'south','target_difference_refresh');else wire(P(76,1,z),'target_difference_rail');if(z>4)edge(P(76,1,z-1),P(76,1,z));}
 rep(P(76,1,131),'south','difference_export');wire(P(76,1,132),'difference_pad');rep(P(76,1,133),'south','equality_inverter_input');solid(P(76,1,134),'equality_support');solid(P(76,0,134),'equality_floor');put(P(76,1,135),'redstone_wall_torch',{facing:'south'},'equality_torch');rep(P(76,1,136),'south','equality_normalizer');wire(P(76,1,137),'equality_pad');join([130,131,132,133,134].map(z=>P(76,1,z)));join([135,136,137].map(z=>P(76,1,z)));
 function route(n,ws){const path=[P(...ws[0])];for(let i=1;i<ws.length;i++){const a=ws[i-1],b=ws[i],delta=b.map((v,j)=>v-a[j]),steps=Math.abs(delta[0])+Math.abs(delta[2]);assert(steps&&(!delta[0]||!delta[2])&&(!delta[1]||Math.abs(delta[1])===steps));for(let j=1;j<=steps;j++)path.push(P(...a.map((v,k)=>v+Math.sign(delta[k])*j)));}
  const candidates=[-1];for(let i=1;i<path.length-1;i++){const a=path[i-1],p=path[i],b=path[i+1];if(!map.has(K(p))&&a.y===p.y&&b.y===p.y&&p.x-a.x===b.x-p.x&&p.z-a.z===b.z-p.z)candidates.push(i);}candidates.push(path.length);const cost=new Map([[-1,0]]),prev=new Map();for(const end of candidates.slice(1))for(const start of candidates){if(start>=end)break;if(!cost.has(start)||end-start>13)continue;const value=cost.get(start)+(end===path.length?0:1);if(value<(cost.get(end)??Infinity)){cost.set(end,value);prev.set(end,start);}}assert(prev.has(path.length),'unrefreshable '+n);const refresh=[];for(let at=prev.get(path.length);at!==-1;at=prev.get(at))refresh.push(at);refresh.sort((a,b)=>a-b);
  let power=15;for(let i=0;i<path.length;i++){const p=path[i],b=path[i+1],old=map.get(K(p));if(old){assert.equal(old.block.id,'minecraft:redstone_wire','route endpoint '+n);power=15;}else if(refresh.includes(i)){const d=Object.keys(V).find(d=>p.x+V[d][0]===b.x&&p.z+V[d][1]===b.z);rep(p,d,n);power=15;}else{wire(p,n);power--;assert(power>0,'attenuation '+n);}}join(path);routes.push({name:n,path,refresh_indices:refresh,nominal_ticks:refresh.length*2});return path;}
 // Existing predicate disagreement includes invalid !enable0. Target equality
 // masks only disagreement; an independent !enable0 injection keeps it invalid.
 rep(P(21,1,62),'east','predicate_difference_branch');wire(P(22,1,62),'predicate_difference_pad');join([P(20,1,62),P(21,1,62),P(22,1,62)]);route('predicate_to_gate',[[22,1,62],[26,1,62],[26,1,90],[28,1,90]]);
 rep(P(29,1,90),'east','predicate_gate_rear');dev(P(30,1,90),'comparator',{facing:'west',mode:'subtract'},'value_disagreement_gate');rep(P(31,1,90),'east','value_disagreement_output');for(let x=32;x<=34;x++)wire(P(x,1,90),'final_fault_merge');join([28,29,30,31,32,33,34].map(x=>P(x,1,90)));
 route('target_equal_mask',[[76,1,137],[46,1,137],[46,1,80],[42,5,80],[34,5,80],[30,1,80],[30,1,88]]);rep(P(30,1,89),'south','equality_side');join([P(30,1,88),P(30,1,89),P(30,1,90)]);
 rep(P(21,1,-14),'east','enable0_branch');wire(P(22,1,-14),'enable0_pad');rep(P(23,1,-14),'east','enable0_input');solid(P(24,1,-14),'enable0_support');solid(P(24,0,-14),'enable0_floor');put(P(25,1,-14),'redstone_wall_torch',{facing:'east'},'enable0_not');wire(P(26,1,-14),'enable0_not_pad');rep(P(27,1,-14),'east','enable0_normalize');wire(P(28,1,-14),'enable0_not_wire');join([20,21,22,23,24].map(x=>P(x,1,-14)));join([25,26,27,28].map(x=>P(x,1,-14)));
 route('invalid_lane0_to_fault',[[28,1,-14],[36,1,-14],[36,1,90]]);rep(P(35,1,90),'west','invalid_lane0_merge');join([P(36,1,90),P(35,1,90),P(34,1,90)]);
 rep(P(34,1,91),'south','fault_export');wire(P(34,1,92),'fault_pad');rep(P(34,1,93),'south','agreement_input');solid(P(34,1,94),'agreement_support');solid(P(34,0,94),'agreement_floor');put(P(34,1,95),'redstone_wall_torch',{facing:'south'},'agreement_torch');rep(P(34,1,96),'south','agreement_export');wire(P(34,1,97),'agreement_pad');join([90,91,92,93,94].map(z=>P(34,1,z)));join([95,96,97].map(z=>P(34,1,z)));
 const ports=structuredClone(parent.ports);for(const[name,key]of[['immediate','immediate'],['incremented_pc','incremented_pc']])ports[name]={direction:'input',width:8,polarity:'active_high',bit_order:'LSB_first',bits:xors.map(v=>({bit:v.bit,position:v[key],required_high_power:15}))};ports.disagreement.bits[0].position=P(34,1,92);ports.agreement.bits[0].position=P(34,1,97);ports.targets_equal={direction:'output',width:1,polarity:'active_high',bits:[{bit:0,position:P(76,1,137),high_power:15}]};
 const blocks=[...map.values()],box={from:{},to:{}};for(const axis of['x','y','z']){box.from[axis]=Math.min(...blocks.map(b=>b.position[axis]));box.to[axis]=Math.max(...blocks.map(b=>b.position[axis]));}
 return{status:'offline_selected_value_branch_agreement_candidate',blocks,edges,routes,box,ports,xors,parent_blocks:parent.blocks.length,metrics:{blocks:blocks.length,added_blocks:blocks.length-parent.blocks.length,target_xors:8,predicate_xors:3,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1]))},semantics:'fault = !enable0 OR (any enabled predicate differs from predicate0 AND immediate != incremented_pc). Equal branch targets never fault solely for differing predicates.',supersedes:'control-nextpc-v1/agreement.json raw predicate equality is insufficient as a semantic replacement for per-lane next-PC value comparison.',protocol:'Qualify branch predicates as in v1; stabilize both target words and all active predicates, then retain fault before PC NEXT opens. Agreement is combinational, not an acknowledgement. Independent !enable0 remains an unconditional refusal even when targets match.',missing:['External immediate/incremented-PC/predicate/enable wiring and retained fault/action qualification.','Measured target and predicate arrival/settle before fault sampling and NEXT opening.'],native_acceptance:false,complete_gpu:false};
}
export function checkTargetAgreement(d){const map=new Map(d.blocks.map(b=>[K(b.position),b])),allowed=new Set(d.edges.map(e=>[K(e.from),K(e.to)].sort().join('|')));assert.equal(map.size,d.blocks.length);let supports=0,contacts=0,sides=0;
 for(const b of d.blocks){if(b.block.id.endsWith('_concrete'))continue;let p=P(b.position.x,b.position.y-1,b.position.z);if(b.block.id==='minecraft:redstone_wall_torch'){const[x,z]=V[b.block.properties.facing];p=P(b.position.x-x,b.position.y,b.position.z-z);}assert.equal(map.get(K(p))?.block.id,'minecraft:light_gray_concrete','support '+K(b.position));supports++;}
 for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))for(const[x,z]of Object.values(V))for(const dy of[-1,0,1]){const p=P(b.position.x+x,b.position.y+dy,b.position.z+z),o=map.get(K(p));if(!o||o.block.id.endsWith('_concrete'))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&map.has(K(P(b.position.x,b.position.y+1,b.position.z))))continue;if(dy===-1&&map.has(K(P(p.x,p.y+1,p.z))))continue;assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign dust '+K(b.position)+' '+K(p));contacts++;}
 for(const b of d.blocks.filter(b=>['minecraft:repeater','minecraft:comparator'].includes(b.block.id))){const dir=Object.keys(F).find(d=>F[d]===b.block.properties.facing),[dx,dz]=V[dir];for(const[x,z]of[[dz,dx],[-dz,-dx]]){const p=P(b.position.x+x,b.position.y,b.position.z+z),o=map.get(K(p));if(o&&['minecraft:repeater','minecraft:comparator'].includes(o.block.id))assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign diode side');sides++;}}
 let cases=0;for(let enabled=0;enabled<16;enabled++)for(let predicates=0;predicates<16;predicates++)for(const equal of[false,true]){const inc=23,imm=equal?23:188,ref=predicates&1;const raw=! (enabled&1)||[1,2,3].some(j=>(enabled>>j&1)&&(predicates>>j&1)!==ref),actual=!(enabled&1)||(raw&&imm!==inc),values=Array.from({length:4},(_,j)=>(predicates>>j&1)?imm:inc),expected=!(enabled&1)||values.some((v,j)=>(enabled>>j&1)&&v!==values[0]);assert.equal(actual,expected);cases++;}
 let targetCases=0;for(let a=0;a<256;a++)for(let b=0;b<256;b++){const diff=Array.from({length:8},(_,i)=>Math.max(((a>>i)&1)-((b>>i)&1),0)||Math.max(((b>>i)&1)-((a>>i)&1),0)).some(Boolean);assert.equal(diff,a!==b);targetCases++;}
 return{status:'author_value_agreement_static_checks_passed',...d.metrics,support_checks:supports,dust_contacts:contacts,diode_side_faces:sides,predicate_enable_equal_unequal_cases:cases,target_pairs:targetCases,native_calls:0,limits:['Steady comparator algebra and local contacts only; no dynamic fault/phase acceptance.']};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeTargetAgreement(),r=checkTargetAgreement(d);if(process.argv.includes('--check'))assert.deepEqual(JSON.parse(readFileSync(new URL('design.json',import.meta.url))),d);else{writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');writeFileSync(new URL('offline-check.json',import.meta.url),JSON.stringify(r,null,2)+'\n');}console.log(JSON.stringify(r,null,2));}
