import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeDispatchCounts}from'../../../../hardware/full-gpu-dispatch-counts.mjs';import{makeDispatchCounterPhased}from'../../../../hardware/full-gpu-dispatch-counter-phased.mjs';import{makeByteComparison}from'../../../../hardware/full-gpu-byte-comparison.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');const d=makeDispatchCounts();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));const parents=d.parents.map(p=>materializeInstance(['dispatched','completed'].includes(p.id)?makeDispatchCounterPhased():makeByteComparison(),{id:p.id,translation:p.origin}));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to))),parentIds=new Set(d.parents.map(v=>v.id));assert.equal(m.size,d.blocks.length);let inherited=0,supports=0,contacts=0,directions=0;for(const p of parents)for(const v of p.blocks){assert.deepEqual(at(v.position)?.block,v.block);inherited++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||o.block.id.endsWith('_concrete'))continue;if(parentIds.has(v.part)&&o.part===v.part)continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q));contacts++;}
 for(const v of d.blocks.filter(v=>!parentIds.has(v.part)&&v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const side of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,side));assert(!o||o.block.id.endsWith('_concrete'),'Foreign side '+K(v.position));}directions++;}
 for(let bit=0;bit<8;bit++){const y=1+8*bit;for(const[n,source,dest]of[['dispatched_to_compare_',P(24,y,-8),P(98,y,0)],['completed_to_compare_',P(24,y,56),P(98,y,64)],['incremented_to_last_',P(48,y,4),P(162,y,0)]]){const c=d.connections.find(c=>c.name===n+bit);assert(c);assert.deepEqual(c.source,source);assert.deepEqual(c.destination,dest);}}
 const power=possibleStrengths(d);assert.deepEqual(power.failed,[]);for(const c of d.connections){assert.equal(at(c.source)?.block.id,'minecraft:redstone_wire');assert.equal(at(c.destination)?.block.id,'minecraft:redstone_wire');assert.deepEqual(add(c.normalizer,D[at(c.normalizer).block.properties.facing]),c.destination);}
 for(const p of d.parents.filter(p=>['remaining','last','all_done'].includes(p.id))){const q=add(p.origin,P(18,1,-4));for(const dir of dirs){const o=at(add(q,dir));assert(!o||o.block.id.endsWith('_concrete')||K(o.position)===K(add(q,P(1,0,0))),'Borrow0 externally driven');}}
 return{preserved_parent_cells:inherited,support_checks:supports,new_wire_contact_checks:contacts,new_directed_repeaters:directions,actual_operand_routes:d.connections.length,possible_strength:power};}
const checks=check(d);let negatives=0;for(const mutate of[c=>{c.blocks.find(v=>K(v.position)==='24,17,-9').block.properties.facing='north';},c=>{const p=c.routes.find(r=>r.name==='incremented_to_last_3').path[18];c.blocks=c.blocks.filter(v=>K(v.position)!==K(p));}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));negatives++;}const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),r={status:'offline_dispatch_counter_comparison_operand_routes_checks_pass',...d.metrics,...checks,corruption_refusals:negatives,sources:{generator:sha('../../../../hardware/full-gpu-dispatch-counts.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_calls:0,world_mutations:0,native_acceptance:false,complete_gpu_layout:false,limits:d.missing};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({...r,possible_strength:{...r.possible_strength,taps:undefined}}));
