// Independent bounded review: direct source loading, actual cold context,
// complete input differential, and a separate directed-network strength solver.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function insert(map,rows,{same=false}={}){for(const r of rows){const k=K(r.position);if(map.has(k)){assert(same,'Duplicate cell '+k);assert.deepEqual(map.get(k),r.block);}else map.set(k,r.block);}}
function scanBlocks(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const part=buffer.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){visit(r);count++;}};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated blocks');}
const memory=read('../memory/fabric-colocation-v2/channel3-write-data-design.json'),panels=read('../loader-bank-panels-v1/delta.json'),program=read('../program-service-composition-v1/new-program-obstacles.json'),programQuiet=read('../program-service-composition-v1/cable-delta.json'),masks=read('../loader-program-colocation-v1/service-mask-memory-composition-v1/composed-delta.json'),address0=read('../memory/fabric-colocation-v2/channel0-address-delta.json'),address1=read('../memory/fabric-colocation-v2/channel1-address-delta.json'),owner=read('../loader-program-colocation-v1/service-owner-open-delivery-v1/delta.json'),payload=read('../loader-program-colocation-v1/service-payload-open-delivery-v1/delta.json'),dispatch=read('../dispatcher-service-colocation-v1/placement.json'),serviceQuiet=read('../dispatcher-service-colocation-v1/delta.json');
const base=new Map();insert(base,[...memory.blocks,...panels.blocks,...program.blocks,...programQuiet.blocks,...masks.placed_loader,...masks.placed_masks,...masks.new_cells,...address0.blocks,...address1.blocks,...owner.new_cells,...payload.new_cells,...dispatch.blocks,...serviceQuiet.new_cells]);for(const r of masks.replacements){assert.deepEqual(base.get(K(r.position)),r.before);base.set(K(r.position),r.after);}assert.equal(base.size,2000594);
const programGlobal=read('../program-global-delivery-v1/delta.json'),activeWitness=read('../loader-program-colocation-v1/service-active-witness-delivery-v1/delta.json'),address2=read('../memory/fabric-colocation-v2/channel2-address-delta.json');insert(base,[...programGlobal.new_cells,...activeWitness.new_cells,...address2.blocks]);assert.equal(base.size,2054908);
const bankGlobal=read('../bank-global-delivery-v1/delta.json'),commit=read('../loader-program-colocation-v1/service-commit-phase-delivery-v1/delta.json'),address3=read('../memory/fabric-colocation-v2/channel3-address-delta.json'),anyOwner=read('../loader-program-colocation-v1/service-any-owner-delivery-v1/delta.json');insert(base,[...bankGlobal.new_cells,...commit.new_cells,...address3.blocks,...anyOwner.new_cells]);assert.equal(base.size,2128184);

const loader=read('../loader-global-delivery-v1/delta.json');insert(base,loader.new_cells);assert.equal(base.size,2135072);
const ready=read('../memory/fabric-colocation-v2/bank-ready-collectors-v1/delta.json','a250536391aaab40afa270de503a677e57574fcc7283e5c44c851f51c6495967'),returns=read('../global-loader-return-v1/delta.json','7a5a780a41e84b0967539e80841431d8971f52fb1c52dc5c2831289c7e2d2070'),busy=read('../loader-program-colocation-v1/service-live-busy-delivery-v1/delta.json','b6e76efe345a848db44cf462a5fdbbc9d3e649a5f92dfecac91ab5462c5efbdf');insert(base,[...ready.new_cells,...returns.new_cells,...busy.new_cells]);assert.equal(base.size,2192096);
export {H,ROOT,pins,P,K,A,W,R,C,T,WT,D,solid,bytes,read,write,insert,scanBlocks,base};
