// Independent exact six-record panel delivery delta; preserve all other scopes.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`;
function read(n,expected){const p=new URL(n,H),raw=readFileSync(p),hash=createHash('sha256').update(raw).digest('hex');if(expected)assert.equal(hash,expected);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=hash;return JSON.parse(raw);}
read('../panel-loader-delivery-v1/source-manifest.json','413433b319feb629fe58d5758a704b99487f4aa72bce9ec41f2d64a9acd76aee');
const before=read('../loader-program-colocation-v1/service-live-busy-delivery-v1/remaining-cuts.json'),after=read('../panel-loader-delivery-v1/remaining-cuts.json'),proof=read('receipt.json'),delta=read('../panel-loader-delivery-v1/delta.json','2ba7b2de9b54fba3bb10f1b7cde3ae95ce8e4a4898bb014f19c19a01cfbf10c2'),copy=structuredClone(before),old=new Map(),current=new Map(delta.new_cells.map(r=>[K(r.position),r.block])),changes=[],negative=[];
assert.equal(proof.status,'passed_independent_actual_panel_loader_review');assert.equal(proof.metrics.total_cells,2192740);
for(const row of proof.cost.original_actual_part_rows)for(const r of row.part_rows)old.set(K(r.position),r.block);
for(const p of proof.source_proofs){for(const r of p.old_source)old.set(K(r.position),r.block);for(const r of p.current_source)current.set(K(r.position),r.block);old.set(K(p.old_connection.destination),{id:'minecraft:redstone_wire'});current.set(K(p.current_connection.destination),{id:'minecraft:redstone_wire'});}
function checkDirect(a,p){const c=p.current_connection,o=p.old_connection;assert.equal(a.status,'bound_actual_panel_input_to_loader');assert.deepEqual(a.source,o.source);assert.deepEqual(a.target,o.tap);assert.deepEqual(a.shared_retained_source,c.root);assert.deepEqual(a.shared_departure,c.source_isolator);assert.deepEqual(a.shared_receiver,c.destination);assert.deepEqual(a.shared_normalizer,c.normalizer);assert.equal(a.shared_route,c.name);assert.deepEqual(a.source_block,old.get(K(a.source)));assert.deepEqual(a.target_block,old.get(K(a.target)));assert(inputs(old,a.target).some(q=>K(q)===K(a.source)));assert(inputs(current,a.shared_departure).some(q=>K(q)===K(c.root)));}
function checkEffective(a,p){const c=p.current_connection,o=p.old_connection;assert.equal(a.status,'bound_actual_panel_input_to_loader');assert.deepEqual(a.source,o.source);assert.deepEqual(a.target,o.tap);assert.deepEqual(a.shared_source,c.root);assert.deepEqual(a.shared_target,c.destination);assert.deepEqual(a.shared_arrival,c.normalizer);assert.equal(a.shared_route,c.name);}
function checkLoader(a,p,index){const c=p.current_connection,o=p.old_connection;assert.equal(a.status,'bound_actual_operator_panel_input');assert.deepEqual(a.source,o.arrival);assert.deepEqual(a.target,o.destination);assert.deepEqual(a.shared_source,c.root);assert.deepEqual(a.shared_target,c.destination);assert.deepEqual(a.shared_arrival,c.normalizer);assert.equal(a.shared_route,c.name);assert.equal(a.global_direct_index,index+1);assert.deepEqual(a.source_block,old.get(K(a.source)));assert.deepEqual(a.target_block,old.get(K(a.target)));assert(inputs(old,a.target).some(q=>K(q)===K(a.source)));assert(inputs(current,a.shared_target).some(q=>K(q)===K(a.shared_arrival)));}
for(let i=0;i<2;i++){const p=proof.source_proofs[i],other=proof.source_proofs[1-i],checks=[['direct',copy.dispatch.direct_foreign_boundaries,after.dispatch.direct_foreign_boundaries,i+1,checkDirect],['effective',copy.dispatch.effective_cut_ledger,after.dispatch.effective_cut_ledger,614+i,checkEffective],['loader',copy.service.loader_control,after.service.loader_control,i,(r,p)=>checkLoader(r,p,i)]];
 for(const[scope,a,b,index,fn]of checks){assert.equal(a[index].status,scope==='effective'?'pending_exact_external_or_transport_connection':'pending');for(const[k,v]of Object.entries(a[index]))if(k!=='status')assert.deepEqual(b[index][k],v,'Original identity changed');fn(b[index],p);const sourceField=scope==='direct'?'shared_retained_source':'shared_source',targetField=scope==='direct'?'shared_receiver':'shared_target';for(const[field,value]of [[sourceField,other.current_connection.root],[targetField,other.current_connection.destination]]){assert.throws(()=>fn({...b[index],[field]:value},p));negative.push({scope,index,field,wrong:value});}a[index]=structuredClone(b[index]);changes.push({scope,index});}
}
copy.service.counts.loader_pending=11;copy.service.counts.loader_control_pending=11;copy.service.counts.loader_control_bound_total=17;
for(const key of ['status','limits','source_sha256'])copy[key]=after[key];assert.deepEqual(copy,after,'Change outside exact six bindings and declared summaries');
assert.equal(after.dispatch.direct_foreign_boundaries.length,48);assert.equal(after.dispatch.effective_cut_ledger.length,661);assert.equal(after.dispatch.transfers.length,352);assert.equal(after.dispatch.direct_foreign_boundaries.filter(r=>r.status==='pending').length,27);assert.equal(after.service.loader_control.filter(r=>r.status==='pending').length,11);assert.equal(after.service.counts.witness_input_pending,5);assert.equal(negative.length,12);
for(const n of ['ledger-review.mjs','../memory/fabric-colocation-v2/cut-inputs.mjs']){const p=new URL(n,H);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');}
const report={status:'passed_exact_six_panel_ledger_changes',metrics:{direct_records:48,effective_records:661,dispatch_transfers:352,changed_direct:2,changed_effective:2,changed_loader:2,direct_pending:27,loader_pending:11,witness_pending:5,wrong_binding_refusals:negative.length},changes,negative,source_sha256:pins,limits:['Exactly direct1/2, effective614/615 and loader0/1 change. Original source/cut identities and all other ledger records are preserved.','Separate READY cut ledger is not implicitly merged; response, other raw-reset fanout, program and panel obligations retain their parent scope.','Held operator levels and actual source/delivery geometry are proved in the separate receipt. State sequencing, pulse width, timing and native acceptance remain open.']};writeFileSync(new URL('ledger-receipt.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
