// Independent actual operator source, transport, cost and whole-map review.
import assert from 'node:assert/strict';
import {H,ROOT,pins,P,K,A,W,R,C,T,WT,D,solid,bytes,read,write,insert,scanBlocks,base} from './frame.mjs';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
import {makeSettledEvaluator} from '../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs';
import {checkFeedback} from '../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
read('../panel-loader-delivery-v1/source-manifest.json','413433b319feb629fe58d5758a704b99487f4aa72bce9ec41f2d64a9acd76aee');
const delta=read('../panel-loader-delivery-v1/delta.json','2ba7b2de9b54fba3bb10f1b7cde3ae95ce8e4a4898bb014f19c19a01cfbf10c2'),masks=read('../loader-program-colocation-v1/service-mask-memory-composition-v1/composed-delta.json'),binding=read('../dispatch-external-bindings-v1/bindings.json'),dispatch=read('../dispatcher-service-colocation-v1/placement.json'),old=new Map(),parts=new Map(),oldBytes=bytes('../initial-loader-warm-drain-v3/design.json','a4f231c808b31f00d71d742465fcba0e90fb6622b1a25364493b1675758e2e0c'),names=['panel_start_to_loader','panel_reset_to_loader'];
const scanned=scanBlocks(oldBytes,row=>{insert(old,[row]);if(names.includes(row.part)){if(!parts.has(row.part))parts.set(row.part,[]);parts.get(row.part).push(row);}});assert.equal(scanned,1733112);
const oldMetadata=JSON.parse(oldBytes.subarray(0,oldBytes.indexOf(Buffer.from('"blocks"'))).toString().replace(/,\s*$/,'')+'}');
// The original file stores metadata after its blocks too. Read only the actual
// two named connection objects from that tail; no author's recovered functions.
const raw=oldBytes.toString(),connectionAt=raw.indexOf('"connections"');assert(connectionAt>=0);let j=raw.indexOf('[',connectionAt),depth=0,quoted=false,escaped=false,end;
for(let i=j;i<raw.length;i++){const c=raw[i];if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue;}if(c==='"'){quoted=true;continue;}if(c==='[')depth++;if(c===']'&&!--depth){end=i+1;break;}}
const oldConnections=JSON.parse(raw.slice(j,end));
const world=new Map(base);insert(world,delta.new_cells);assert.equal(world.size,2192740);assert.equal(delta.new_cells.length,644);
function cone(map,target,boundaries){const stop=new Set(boundaries.map(K)),found=new Map(),q=[target];for(let i=0;i<q.length;i++){const p=q[i],k=K(p);if(found.has(k))continue;assert(active(map.get(k)),'Absent source device '+k);found.set(k,p);if(!stop.has(k))q.push(...inputs(map,p));}for(const p of boundaries)assert(found.has(K(p)),'Source missing from cone '+K(p));return [...found.values()];}
function evaluator(map,positions,roots){return makeSettledEvaluator(map,positions,roots);}
const oldLevers=[P(-412,-4,584),P(-407,-4,595)],translation=P(296,-35,-880),proofs=[],costs=[],oldCellKeys=new Set(),newKeys=new Set(delta.new_cells.map(r=>K(r.position))),routeKeys=new Set(),permitted=new Map(),arrivals=new Map();
function add(source,target){const k=K(target);if(!permitted.has(k))permitted.set(k,new Set());permitted.get(k).add(K(source));}
for(let n=0;n<2;n++){
 const name=names[n],c=delta.connections.find(c=>c.name===name),o=oldConnections.find(c=>c.name===name),b=binding.direct.find(r=>r.direct_index===n+1).bindings[0],lever=oldLevers[n],currentLever=A(lever,translation);assert(c&&o);assert.deepEqual(o.source,b.producer.original_master_position);assert.deepEqual(o.destination,b.receiver.original_master_position);assert.deepEqual(c.root,A(b.producer.position,dispatch.translation));const receiver=masks.placed_loader.find(r=>K(r.position)===K(c.destination));assert(receiver);assert.deepEqual(receiver.original_position,o.destination);assert.deepEqual(old.get(K(o.destination)),receiver.block);assert.equal(inputs(base,c.destination).length,0);
 const oldSource=cone(old,o.source,[lever]),currentSource=cone(world,c.root,[currentLever]);assert.equal(oldSource.length,3);assert.equal(currentSource.length,3);assert.equal(old.get(K(lever)).id,'minecraft:lever');assert.deepEqual(old.get(K(lever)),world.get(K(currentLever)));assert.deepEqual(new Set(oldSource.map(p=>K(A(p,translation)))),new Set(currentSource.map(K)));for(const p of oldSource){assert.deepEqual(old.get(K(p)),world.get(K(A(p,translation))));assert.deepEqual(inputs(old,p).map(q=>K(A(q,translation))).sort(),inputs(world,A(p,translation)).map(K).sort());}
 const oldTransport=cone(old,o.arrival,[o.source]).filter(p=>K(p)!==K(o.source)),oldOwned=parts.get(name),actualActive=oldOwned.filter(r=>active(r.block)),supports=new Set(),materials={};assert.deepEqual(new Set(oldTransport.map(K)),new Set(actualActive.map(r=>K(r.position))));assert(inputs(old,o.destination).some(p=>K(p)===K(o.arrival)));
 for(const r of actualActive){assert([W,R].includes(r.block.id));const support=P(r.position.x,r.position.y-1,r.position.z);assert(solid(old.get(K(support))));assert(oldOwned.some(v=>K(v.position)===K(support)));supports.add(K(support));}assert.equal(supports.size,actualActive.length);assert.equal(oldOwned.length,actualActive.length+supports.size);for(const r of oldOwned){assert(!oldCellKeys.has(K(r.position)));oldCellKeys.add(K(r.position));materials[r.block.id]=(materials[r.block.id]??0)+1;}
 costs.push({name,actual_part_cells:oldOwned.length,active_devices:actualActive.length,unique_actual_supports:supports.size,materials,part_rows:oldOwned});
 const route=delta.routes.find(r=>r.name===name);assert.deepEqual(route.path[0],c.root);assert.deepEqual(route.path.at(-1),c.destination);assert.deepEqual(route.path[1],c.source_isolator);assert.deepEqual(route.path.at(-2),c.normalizer);for(let i=1;i<route.path.length;i++){const a=route.path[i-1],b=route.path[i];assert(inputs(world,b).some(p=>K(p)===K(a)));add(a,b);if(world.get(K(a)).id===W&&world.get(K(b)).id===W)add(b,a);}for(const p of route.path)if(newKeys.has(K(p)))routeKeys.add(K(p));arrivals.set(K(c.destination),K(c.normalizer));
 const oldFull=cone(old,o.destination,[lever]),currentFull=cone(world,c.destination,[currentLever]),a=evaluator(old,oldFull,[lever]),z=evaluator(world,currentFull,[currentLever]),cases=[];for(const level of [0,15]){const oldPower=a(new Map([[K(lever),level]])).power,newPower=z(new Map([[K(currentLever),level]])).power;const values=[oldPower.get(K(o.source))??0,oldPower.get(K(o.destination))??0,newPower.get(K(c.root))??0,newPower.get(K(c.destination))??0];assert.deepEqual(values,Array(4).fill(level));cases.push({level,values});}
 proofs.push({name,old_lever:lever,current_lever:currentLever,old_connection:o,current_connection:c,old_source:oldSource.map(p=>({position:p,block:old.get(K(p)),inputs:inputs(old,p)})),current_source:currentSource.map(p=>({position:p,block:world.get(K(p)),inputs:inputs(world,p)})),old_transport_devices:oldTransport.length,old_full_devices:oldFull.length,current_full_devices:currentFull.length,cases,feedback:{...checkFeedback(world,currentFull,[currentLever]),scope:'Actual lever and positive source/delivery chain; held operator levels only. No pulse or loader state-transition proof.'}});
}
assert.equal(oldCellKeys.size,524);assert.equal(routeKeys.size,322);console.log('direct original part cost',costs.map(c=>[c.name,c.actual_part_cells,c.active_devices,c.unique_actual_supports]));
let receivers=0,supports=0,oldInputs=0,actualInputs=0,newInputs=0;
for(const[k,b]of world){const p=P(...k.split(',').map(Number));let support;if(b.id===WT)support=A(p,D[b.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);if(support){assert(solid(world.get(K(support))),'Missing support '+k);supports++;}if(!active(b))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;if(base.has(k)){const expected=inputs(base,p).map(K);oldInputs+=expected.length;if(arrivals.has(k))expected.push(arrivals.get(k));assert.deepEqual(actual,[...new Set(expected)].sort(),'Changed retained input '+k);}else{assert.deepEqual(actual,[...(permitted.get(k)??[])].sort(),'Undeclared route contact '+k);newInputs+=actual.length;}}
console.log('full input screen',world.size,receivers,actualInputs);
const jointRoots=proofs.map(p=>p.current_lever),jointPositions=new Map();for(const p of proofs)for(const q of cone(world,p.current_connection.destination,[p.current_lever]))jointPositions.set(K(q),q);const joint=evaluator(world,[...jointPositions.values()],jointRoots),jointCases=[],strengthCases=[],newRear=new Map(),mutations=[],reverse={east:'west',west:'east',north:'south',south:'north'};
for(let mask=0;mask<4;mask++){const levels=jointRoots.map((p,i)=>mask>>i&1?15:0),v=joint(new Map(jointRoots.map((p,i)=>[K(p),levels[i]]))).power,outputs=proofs.map(p=>v.get(K(p.current_connection.destination))??0);assert.deepEqual(outputs,levels);jointCases.push({mask,levels,outputs});if(mask===3)for(const r of delta.new_cells.filter(r=>r.block.id===R)){const rear=Math.max(0,...inputs(world,r.position).map(q=>v.get(K(q))??0));assert(rear>0);newRear.set(K(r.position),rear);}}
for(const p of proofs){const c=p.current_connection,positions=cone(world,c.destination,[c.root]),ev=evaluator(world,positions,[c.root]);for(let level=0;level<=15;level++){const arrival=ev(new Map([[K(c.root),level]])).power.get(K(c.destination))??0;assert.equal(arrival,level?15:0);strengthCases.push({name:p.name,level,arrival});}
 const positionsSet=new Set(positions.map(K));for(const r of [...delta.new_cells.filter(r=>r.block.id===R&&positionsSet.has(K(r.position))),...p.current_source.filter(r=>r.block.id===R)]){const saved=world.get(K(r.position));world.set(K(r.position),{...saved,properties:{...saved.properties,facing:reverse[saved.properties.facing]}});let refused=false;try{const bad=evaluator(world,cone(world,c.destination,[p.current_lever]),[p.current_lever]),arrival=bad(new Map([[K(p.current_lever),15]])).power.get(K(c.destination))??0;refused=arrival!==15;}catch{refused=true;}world.set(K(r.position),saved);assert(refused,'Reversed actual repeater survived');mutations.push({name:p.name,kind:newKeys.has(K(r.position))?'route_repeater':'actual_panel_producer_repeater',position:r.position});}
 const s=P(c.normalizer.x,c.normalizer.y-1,c.normalizer.z),saved=world.get(K(s));world.delete(K(s));assert(!solid(world.get(K(s))));world.set(K(s),saved);mutations.push({name:p.name,kind:'arrival_support_deleted',position:s});
}
assert.equal(mutations.length,37);assert.equal(newRear.size,33);assert.equal(Math.min(...newRear.values()),5);assert.equal(oldInputs,1823402);
const materials={},columns=new Set(),box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const r of delta.new_cells)materials[r.block.id]=(materials[r.block.id]??0)+1;for(const k of world.keys()){const p=P(...k.split(',').map(Number));columns.add(Math.floor(p.x/16)+','+Math.floor(p.z/16));for(const a of ['x','y','z']){box.from[a]=Math.min(box.from[a],p[a]);box.to[a]=Math.max(box.to[a],p[a]);}}const yTranslation=[-64-box.from.y,319-box.to.y];assert(yTranslation[0]<=yTranslation[1]);
for(const n of ['review.mjs','frame.mjs','../memory/fabric-colocation-v2/cut-inputs.mjs','../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs','../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs'])bytes(n);
write('receipt.json',{status:'passed_independent_actual_panel_loader_review',metrics:{base_cells:base.size,new_cells:delta.new_cells.length,total_cells:world.size,receivers,supports,actual_inputs:actualInputs,preserved_inputs:oldInputs,new_inputs:newInputs,existing_arrivals:arrivals.size,old_assembly_cells:scanned,old_transport_cells:oldCellKeys.size,old_transport_active:costs.reduce((a,c)=>a+c.active_devices,0),actual_unique_old_supports:costs.reduce((a,c)=>a+c.unique_actual_supports,0),source_cases:4,joint_cases:4,strength_cases:strengthCases.length,actual_mutations:mutations.length,new_repeaters:newRear.size,minimum_rear:Math.min(...newRear.values())},source_proofs:proofs,joint_cases:jointCases,strength_cases:strengthCases,mutations,rears:[...newRear],cost:{original_actual_part_rows:costs,new_cells:delta.new_cells.length,matched_increase:delta.new_cells.length-oldCellKeys.size,new_materials:materials,whole_columns:columns.size,whole_box:box,legal_common_y_translation:yTranslation},source_sha256:pins,limits:['Actual old/current operator levers and positive three-device producer chains plus transport are reviewed using a distinct component-DAG numeric evaluator. Shared physical-input rules remain conditional.','The524 old cells are directly counted from two original transport parts and contain262 actual devices with262 distinct actual supports; no blanket device-times-two assumption is used.','Only held operator levels are tested. Loader state transitions, pulse width, reset/start timing, remaining assembly and native Minecraft acceptance remain open.','Exact2,192,740-cell partial frame includes READY, global-loader returns and live BUSY; both cores and unfinished links are excluded.']});console.log(JSON.stringify({status:'passed',cells:world.size,receivers,inputs:actualInputs,oldTransport:oldCellKeys.size,mutations:mutations.length,minRear:Math.min(...newRear.values())}));
