import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeProgramROM} from '../../../../hardware/memory-layout-program.mjs';
import {makeFoldedProgramROM,foldPosition,foldBlock,FOLD_AXIS} from '../../../../hardware/memory-layout-program-folded.mjs';
import {key} from '../../../../hardware/memory-layout-subarray.mjs';
import {circuitSchema} from '../../../../tools/minecraft-redstone/scripts/circuit-service.mjs';
const p=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',solid=b=>[S,'minecraft:redstone_block'].includes(b?.id),V={east:[-1,0],west:[1,0],north:[0,1],south:[0,-1]},H=Object.values(V);
const base=makeProgramROM(),d=makeFoldedProgramROM(),saved=JSON.parse(readFileSync(new URL('design.json',import.meta.url)));assert.deepEqual(saved,d);
const m=new Map(d.blocks.map(v=>[key(v.position),v.block])),get=(x,y,z)=>m.get(key(p(x,y,z)));assert.equal(m.size,d.blocks.length);
const rep=(x,y,z,facing)=>assert.deepEqual(get(x,y,z),{id:'minecraft:repeater',properties:{facing,delay:'1'}}),wire=(x,y,z)=>assert.equal(get(x,y,z)?.id,'minecraft:redstone_wire');
let inherited=0,removed=0,supports=0,maskContacts=0,tapContacts=0,foreignSteps=0,sideSources=0,pathCells=0,maxDust=0;
for(const v of base.blocks){const g=base.groups[key(v.position)];if(['address_global_rails','global_read_return'].includes(g)||g==='address_branch'&&v.position.x>=67){removed++;continue;}
 const stack=Math.floor((v.position.z+36)/96),q=foldPosition(v.position,stack);assert.deepEqual(m.get(key(q)),foldBlock(v.block,stack),'Exact inherited transform '+key(q));inherited++;}
assert.equal(inherited,d.inherited_cell_mapping.length);
for(const v of d.blocks){const a=v.position,b=v.block;if(solid(b))continue;let q=p(a.x,a.y-1,a.z);if(b.id==='minecraft:redstone_wall_torch'){const[dx,dz]=V[b.properties.facing];q=p(a.x+dx,a.y,a.z+dz);}assert(solid(m.get(key(q))),'Support '+key(a));supports++;
 if(d.groups[key(a)]!=='card'){
  for(const[dx,dz]of H){const q=p(a.x+dx,a.y,a.z+dz),bb=m.get(key(q));
   if(bb&&!solid(bb)&&d.nets[key(a)]!==d.nets[key(q)]){const forward=d.groups[key(a)]==='high_card_mask_distribution'&&b.id==='minecraft:repeater'&&d.groups[key(q)]==='high_card_output_selector'&&bb.id==='minecraft:comparator'&&q.x===a.x&&q.z===a.z+1;const backward=d.groups[key(q)]==='high_card_mask_distribution'&&bb.id==='minecraft:repeater'&&d.groups[key(a)]==='high_card_output_selector'&&b.id==='minecraft:comparator'&&a.x===q.x&&a.z===q.z+1;assert(forward||backward,'Foreign face '+key(a)+'>'+key(q));if(forward)maskContacts++;}
   if(b.id==='minecraft:redstone_wire')for(const dy of[-1,1]){const r=p(q.x,a.y+dy,q.z),rb=m.get(key(r));if(rb?.id!=='minecraft:redstone_wire'||d.nets[key(a)]===d.nets[key(r)])continue;if(dy>0&&m.has(key(p(a.x,a.y+1,a.z))))continue;if(dy<0&&m.has(key(p(r.x,a.y,r.z))))continue;foreignSteps++;assert.fail('Foreign step '+key(a)+'>'+key(r));}
  }
  if(b.id==='minecraft:repeater'){const[dx,dz]=V[b.properties.facing];for(const sign of[-1,1]){const q=p(a.x+sign*dz,a.y,a.z+sign*dx),bb=m.get(key(q));if(!['minecraft:repeater','minecraft:comparator'].includes(bb?.id))continue;const[tX,tZ]=V[bb.properties.facing];if(q.x+tX===a.x&&q.z+tZ===a.z){sideSources++;assert.fail('New side input '+key(a));}}}
 }
 if(['minecraft:repeater','minecraft:comparator'].includes(b.id)){const[dx,dz]=V[b.properties.facing],r=p(a.x-dx,a.y,a.z-dz);if(!solid(m.get(key(r))))continue;const sources=[],above=p(r.x,r.y+1,r.z);if(m.get(key(above))?.id==='minecraft:redstone_wire')sources.push(above);for(const[tX,tZ]of H){const q=p(r.x-tX,r.y,r.z-tZ),bb=m.get(key(q));if(['minecraft:repeater','minecraft:comparator'].includes(bb?.id)&&JSON.stringify(V[bb.properties.facing])===JSON.stringify([tX,tZ]))sources.push(q);}for(const q of sources){if(d.groups[key(q)]==='card'&&d.groups[key(a)]==='card'||d.nets[key(q)]===d.nets[key(a)])continue;assert.equal(d.groups[key(q)],'card');assert.equal(d.groups[key(a)],'capped_read_tap');assert.deepEqual(q,p(a.x,a.y+1,a.z+1));tapContacts++;}}
}
for(const r of d.routes){let run=0;for(let i=0;i<r.path.length;i++){const q=r.path[i],b=m.get(key(q));assert(['minecraft:redstone_wire','minecraft:repeater'].includes(b?.id));assert.equal(d.nets[key(q)],r.net);if(b.id==='minecraft:repeater'){assert.deepEqual(V[b.properties.facing],{east:[1,0],west:[-1,0],south:[0,1],north:[0,-1]}[r.travel]);run=0;}else{run++;maxDust=Math.max(maxDust,run);assert(run<=12,'Attenuation '+r.type);}
 if(i){const a=r.path[i-1],dx=Math.abs(a.x-q.x),dy=Math.abs(a.y-q.y),dz=Math.abs(a.z-q.z);assert(dx+dz===1&&dy<=1,'Disconnected path');if(dy){const low=a.y<q.y?a:q;assert(!m.has(key(p(low.x,low.y+1,low.z))),'Blocked ascending dust');}}pathCells++;}}
const depth=[-4,-8,-12,-16,-25,-21,-33,-29];for(let b=0;b<8;b++){assert.deepEqual(d.ports.address.positions[b],p(FOLD_AXIS,depth[b],-54));for(let row=0;row<4;row++){const z=(b%4<2?-18:-6)+(b>=4?-18:0)+96*row;wire(FOLD_AXIS,depth[b],z);rep(FOLD_AXIS-1,depth[b],z,'east');rep(FOLD_AXIS+1,depth[b],z,'west');wire(FOLD_AXIS-2,depth[b],z);wire(FOLD_AXIS+2,depth[b],z);}}
for(let b=0;b<16;b++){const j=b%8,x0=b>=8?38+4*j:-6-4*j,z=-60-2*b;for(const x of[x0,2*FOLD_AXIS-x0]){rep(x,271,z+1,'south');for(let y=271;y<=275;y++)assert.equal(get(x,y,z)?.id,(y-271)%2?'minecraft:redstone_torch':S);}rep(FOLD_AXIS-1,275,z,'west');rep(FOLD_AXIS+1,275,z,'east');for(let y=275;y<=279;y++)assert.equal(get(FOLD_AXIS,y,z)?.id,(y-275)%2?'minecraft:redstone_torch':S);rep(FOLD_AXIS+1,279,z,'west');wire(FOLD_AXIS+2,279,z);assert.deepEqual(d.ports.read_data.positions[b],p(FOLD_AXIS+2,279,z));}
assert.equal(d.configuration.length,4096);assert.equal(new Set(d.configuration.map(c=>key(c.position))).size,4096);for(let i=0;i<4096;i++){const a=base.configuration[i],b=d.configuration[i];assert.equal(a.address,b.address);assert.equal(a.bit,b.bit);assert.deepEqual(b.position,foldPosition(a.position,a.card%8));assert.deepEqual(m.get(key(b.position)),{id:S});}
// Decode card targets from actual mirrored/unmirrored arm blocks.
const targets=[];for(const c of base.cards){let t=0;for(let b=0;b<4;b++){const q=foldPosition(p(b%2?10:2,131+136*c.tier,-36+12*Math.floor(b/2)+96*c.stack),c.stack),bb=m.get(key(q));assert([S,'minecraft:repeater'].includes(bb?.id));if(bb.id===S)t|=1<<b;}assert.equal(t,c.card);targets.push(t);}assert.equal(new Set(targets).size,16);for(let a=0;a<256;a++)assert.deepEqual(targets.filter(t=>t===(a>>4)),[a>>4]);
circuitSchema.parse(d.circuit);assert.equal(d.circuit.signals.length,24);assert.equal(maskContacts,256);assert.equal(tapContacts,256);assert.equal(foreignSteps,0);assert.equal(sideSources,0);
const report={status:'offline_folded_ROM_static_checked_no_native_or_controller_acceptance',...d.metrics,comparison:d.comparison,inherited_cells_checked:inherited,replaced_baseline_routing_cells:removed,new_cells:d.blocks.length-inherited,support_checks:supports,configuration_positions_checked:4096,high_card_targets_checked:16,software_address_oracle_cases:256,route_cells_checked:pathCells,max_recorded_dust_run:maxDust,intended_mask_contacts:maskContacts,intended_floor_taps:tapContacts,foreign_step_dust_candidates:foreignSteps,new_diode_side_sources:sideSources,native_calls:0,limits:['No complete dynamic weak/strong-power simulation or physical response-time proof.','Program arbitration, owner/address/response latches and ready-generation remain missing.','Chunk counts are relative alignment calculations, not a selected/loaded site.']};
if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
