// Independent exact READY cut reconciliation, tied to the actual-map receipt.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs} from '../fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h));
read('../fabric-colocation-v2/bank-ready-collectors-v1/source-manifest.json','aa2eac00ab251ce74a650451a4c97fdeadf636effcf176a0d9fbc5ebd70b5125');
const before=read('../fabric-colocation-v2/channel3-address-cut-ledger.json'),after=read('../fabric-colocation-v2/bank-ready-collectors-v1/cut-ledger.json'),d=read('../fabric-colocation-v2/bank-ready-collectors-v1/delta.json','a250536391aaab40afa270de503a677e57574fcc7283e5c44c851f51c6495967'),proof=read('receipt.json'),bankCuts=read('../fabric-colocation-v2/bank-tail-body-cuts.json').cuts,fabricCuts=read('../fabric-colocation-v2/actual-cuts.json').cuts,bankIndices=new Set(Array.from({length:32},(_,i)=>504+i)),fabricIndices=new Set([713,737,761,785]),selectedCuts=[...bankIndices].map(i=>bankCuts[i]).concat([...fabricIndices].map(i=>fabricCuts[i])),near=new Set(),old=new Map(),world=new Map(d.new_cells.map(r=>[K(r.position),r.block])),changes=[],negatives=[];
assert.equal(proof.status,'passed_independent_actual_typed_bank_ready_review');assert.equal(proof.metrics.total_cells,2184528);
for(const cut of selectedCuts)for(const e of [cut.source,cut.target])for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++)near.add(K(P(e.position.x+x,e.position.y+y,e.position.z+z)));
// Independently stream the actual cold geometry for every selected original cut.
const buf=bytes('../master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');let i=buf.indexOf(91,buf.indexOf(Buffer.from('"blocks"'))+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,scanned=0;
function flush(end){const part=buf.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){scanned++;if(near.has(K(r.position)))old.set(K(r.position),r.block);}}
for(;i<buf.length;i++){const c=buf[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);break;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}
assert.equal(scanned,3381962);
for(const cut of selectedCuts){for(const e of [cut.source,cut.target])assert.deepEqual(old.get(K(e.position)),e.block);assert(inputs(old,cut.target.position).some(p=>K(p)===K(cut.source.position)));}
for(const bank of proof.source_proofs)for(const out of bank.outputs)world.set(K(out.current),old.get(K(out.old)));
for(const c of proof.collectors)world.set(K(c.destination),{id:'minecraft:redstone_wire'});
function bankBinding(b){
 const bank=proof.source_proofs.find(x=>x.bank===b.bank),out=bank?.outputs.find(x=>x.channel===b.channel&&x.kind===b.kind);assert(out);
 const index=504+8*b.channel+2*b.bank+(b.kind==='write_ready'?1:0),cut=bankCuts[index],pair=d.source_pairs.find(x=>x.bank===b.bank&&x.channel===b.channel),c=d.connections.find(x=>x.bank===b.bank&&x.channel===b.channel&&x.kind==='qualified_bank_ready_pair'),tap=b.kind==='read_ready'?pair.read_tap:pair.write_tap;
 assert.equal(b.bank_cut_index,index);assert.equal(b.cut_sha256,cut.cut_sha256);assert.deepEqual(b.original,cut);assert.equal(cut.source.group,'four-bank-service-v1/bank'+b.bank);assert.equal(cut.target.group,'bank-ready-return-v1/owned_bank_ready_returns');assert.deepEqual(cut.source.position,out.old);assert.deepEqual(b.current_source,out.current);assert.deepEqual(b.current_departure,tap);assert.deepEqual(b.pair_output,pair.start);assert.equal(b.collector_channel,b.channel);assert.equal(b.bank_to_collector_cable,c.name);assert.deepEqual(b.current_backend_ready_destination,proof.collectors[b.channel].destination);assert.deepEqual(b.backend_destination,proof.collectors[b.channel].destination);assert(inputs(world,tap).some(p=>K(p)===K(out.current)));assert.deepEqual(b.current_source_block,world.get(K(out.current)));return index;
}
for(let n=0;n<572;n++){const a=before.bank_inventory.entries[n],b=after.bank_inventory.entries[n];assert.equal(a.index,n);assert.deepEqual(a.original,bankCuts[n]);if(!bankIndices.has(n)){assert.deepEqual(b,a,'Unrelated bank record '+n);continue;}for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v);assert.equal(a.status,'outside_this_group_reconciliation_pending');assert.equal(b.status,'actual_qualified_bank_ready_collector_rebound');assert.equal(bankBinding(b.binding),n);assert.deepEqual(after.bank_bindings.find(x=>x.bank_cut_index===n),b.binding);for(const[field,value]of[['bank',(b.binding.bank+1)%4],['channel',(b.binding.channel+1)%4],['kind',b.binding.kind==='read_ready'?'write_ready':'read_ready']]){assert.throws(()=>bankBinding({...b.binding,[field]:value}));negatives.push({inventory:'bank',index:n,field,wrong:value});}changes.push({inventory:'bank',index:n});}
function fabricBinding(b){
 const channel=b.channel,index=713+24*channel,cut=fabricCuts[index],c=d.connections.find(x=>x.kind==='actual_backend_ready'&&x.channel===channel);assert(c);assert.equal(b.index,index);assert.deepEqual(b.original,cut);assert.deepEqual(cut.target.position,proof.old_collectors[channel].destination);assert.equal(cut.target.group,'channel-backend-v1/backend'+channel);assert.equal(cut.source.group,'bank-ready-return-v1/actual_channel_ready_inputs');assert.deepEqual(b.destination,proof.collectors[channel].destination);assert.deepEqual(b.destination,c.destination);assert.deepEqual(b.source,c.source);assert.deepEqual(b.actual_driver,c.arrival);assert.equal(b.cable,c.name);assert(inputs(world,c.destination).some(p=>K(p)===K(c.arrival)));assert.equal(proof.collectors[channel].roots.length,8);return index;
}
for(let n=0;n<944;n++){const a=before.fabric_inventory.entries[n],b=after.fabric_inventory.entries[n];assert.equal(a.index,n);assert.deepEqual(a.original,fabricCuts[n]);if(!fabricIndices.has(n)){assert.deepEqual(b,a,'Unrelated fabric record '+n);continue;}for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v);assert.equal(a.status,'outside_this_group_reconciliation_pending');assert.equal(b.status,'actual_bank_ready_or8_to_backend_rebound');assert.equal(fabricBinding(b.binding),n);assert.deepEqual(after.fabric_bindings.find(x=>x.index===n),b.binding);const wrong=(b.binding.channel+1)%4;assert.throws(()=>fabricBinding({...b.binding,channel:wrong}));negatives.push({inventory:'fabric',index:n,field:'channel',wrong});changes.push({inventory:'fabric',index:n});}
const pending=r=>r.status==='outside_this_group_reconciliation_pending',bankPending=after.bank_inventory.entries.filter(pending),fabricPending=after.fabric_inventory.entries.filter(pending);assert.equal(bankPending.length,104);assert.equal(fabricPending.length,832);assert.equal(after.bank_inventory.checked_cumulative,572-bankPending.length);assert.equal(after.fabric_inventory.checked_cumulative,944-fabricPending.length);assert.equal(bankPending.filter(r=>r.original.source.group.startsWith('loader/')).length,68);assert.equal(bankPending.filter(r=>r.original.target.group==='current/bank_held_response_cables').length,32);assert.deepEqual([536,537,538,539].map(n=>after.bank_inventory.entries[n]),[536,537,538,539].map(n=>before.bank_inventory.entries[n]));assert.equal(bankPending.filter(r=>['current/paired_bank_address_adapter','current/bank_write_data_adapter'].includes(r.original.source.group)).length,0);assert.equal(changes.length,36);assert.equal(negatives.length,100);
bytes('ledger-review.mjs');bytes('../fabric-colocation-v2/cut-inputs.mjs');
const report={status:'passed_exact_READY_cut_reconciliation',metrics:{actual_old_cells_scanned:scanned,actual_old_context_cells:old.size,bank_records:572,fabric_records:944,new_bank_bindings:32,new_fabric_bindings:4,unchanged_bank_records:540,unchanged_fabric_records:940,bank_bound:468,fabric_bound:112,bank_pending:104,fabric_pending:832,bank_loading_pending_in_this_ledger:68,bank_response_pending:32,bank_busy_to_loader_pending:4,runtime_payload_inputs_pending:0,wrong_binding_refusals:100},changes,negative_cases:negatives,source_sha256:pins,limits:['Only32 typed bank READY egress cuts504..535 and4 backend ingress cuts713/737/761/785 change. All other complete records are byte-value identical.','The independently derived source proof includes exactly12 prior refresh corrections; no raw-old source equivalence is asserted.','Root68 loading-panel bindings remain a separate ledger scope. Neither response delivery nor four loader bank-BUSY cuts536..539 are closed here.','All results concern held inputs and the READY-era2,184,528-cell frame; later returns/live BUSY, state/capture timing, READY/data ordering and native acceptance are excluded.']};
writeFileSync(new URL('ledger-receipt.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
