// Independent direct-map READY source, repair, collector and full-input review.
import assert from 'node:assert/strict';
import {H,ROOT,pins,P,K,A,W,R,C,T,WT,D,solid,bytes,read,write,insert,scanBlocks,base} from './frame.mjs';
import {inputs,active} from '../fabric-colocation-v2/cut-inputs.mjs';
import {makeSettledEvaluator} from '../../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs';
import {checkFeedback} from '../../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
read('../fabric-colocation-v2/bank-ready-collectors-v1/source-manifest.json','aa2eac00ab251ce74a650451a4c97fdeadf636effcf176a0d9fbc5ebd70b5125');
const delta=read('../fabric-colocation-v2/bank-ready-collectors-v1/delta.json','a250536391aaab40afa270de503a677e57574fcc7283e5c44c851f51c6495967'),placement=read('../fabric-colocation-v2/bank-ready-collectors-v1/placement.json'),bodies=read('../fabric-colocation-v2/bank-tail-bodies.json'),phase=read('../fabric-colocation-v2/bank-tail-classification.json'),repairs=read('../fabric-colocation-v2/bank-tail-attenuation-repair.json'),direct=read('../fabric-colocation-v2/direct-design.json'),backend=read('../channel-backend-v1/ports.json'),oldReady=read('../bank-ready-return-v1/ports.json'),labelsMeta=read('../fabric-colocation-v2/cell-labels.json'),labelBytes=bytes('../fabric-colocation-v2/cell-labels.u16le'),labels=new Uint16Array(labelBytes.buffer,labelBytes.byteOffset,labelBytes.length/2),old=new Map(),oldTransport=[],groups=new Set(['bank-ready-return-v1/ready_collectors','bank-ready-return-v1/owned_bank_ready_returns','bank-ready-return-v1/actual_channel_ready_inputs']);let oldIndex=0;
const scanned=scanBlocks(bytes('../master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f'),r=>{insert(old,[r]);const part=labelsMeta.labels[labels[oldIndex++]];if(groups.has(part))oldTransport.push({...r,part});});assert.equal(scanned,3381962);assert.equal(oldIndex,labels.length);assert.equal(oldTransport.length,87668);
const world=new Map(base);insert(world,delta.new_cells);assert.equal(world.size,2184528);assert.equal(delta.connections.length,20);assert.equal(delta.source_pairs.length,16);assert.equal(delta.collectors.length,4);
const inverse=p=>P(p.x,p.y+8,p.z-40),translation=p=>P(p.x,p.y-8,p.z+40),bodyMap=new Map(bodies.blocks.filter(r=>r.original_position).map(r=>[K(r.position),r])),sourceRows=[],allSourceKeys=new Set(),patches=[],rawMismatches=[],sourceTruth=[],stateIdentities=[];
function cone(map,ends,roots){const stops=new Set(roots.map(K)),seen=new Map(),queue=Array.isArray(ends)?[...ends]:[ends];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(map.get(k)),'Missing actual device '+k);seen.set(k,p);if(!stops.has(k))queue.push(...inputs(map,p));}for(const p of roots)assert(seen.has(K(p)),'Unused root '+K(p));return[...seen.values()];}
function evaluator(map,positions,roots){const constants=positions.filter(p=>map.get(K(p)).id==='minecraft:redstone_block'),boundary=[...roots,...constants],ev=makeSettledEvaluator(map,positions,boundary);return{constants,boundary,power:values=>ev(new Map([...constants.map(p=>[K(p),15]),...roots.map((p,i)=>[K(p),values[i]])])),feedback:{...checkFeedback(map,positions,boundary),scope:'Exact held READY source/collector cone; wire conductance components only. State/capture/timing not proved.'}};}
const expected=(values,output)=>values[0]&&values[1]&&!values[2]&&values[3+output.channel]&&!!values[7]===(output.kind==='write_ready')?15:0;
for(let bank=0;bank<4;bank++){const b=bodies.banks[bank],o=b.origin,at=p=>A(o,p),roots=phase.rows[bank].sources.filter(r=>['active','tail','reset'].includes(r.name)).map(r=>({name:r.name,current:r.position,old:r.original}));
 for(let c=0;c<4;c++)roots.push({name:'owner'+c,current:at(P(44,-52+4*c,-240)),old:inverse(at(P(44,-52+4*c,-240))),lock:at(P(44,-52+4*c,-239))});roots.push({name:'is_write',current:at(P(54,-21,-120)),old:inverse(at(P(54,-21,-120))),lock:at(P(54,-21,-119))});assert.deepEqual(roots.map(r=>r.name),['active','tail','reset','owner0','owner1','owner2','owner3','is_write']);
 for(const r of roots){const stored=bodyMap.get(K(r.current));assert(stored);assert.deepEqual(stored.original_position,r.old);assert.deepEqual(old.get(K(r.old)),world.get(K(r.current)));if(r.lock){const lockRow=bodyMap.get(K(r.lock));assert(lockRow);assert.deepEqual(lockRow.original_position,inverse(r.lock));assert.equal(world.get(K(r.current)).id,R);assert.equal(world.get(K(r.lock)).id,R);assert.deepEqual(old.get(K(inverse(r.lock))),world.get(K(r.lock)));assert(inputs(world,r.current).some(p=>K(p)===K(r.lock)));assert(inputs(old,r.old).some(p=>K(p)===K(inverse(r.lock))));stateIdentities.push({...r,block:world.get(K(r.current)),lock_block:world.get(K(r.lock))});}}
 const outputs=[];for(let channel=0;channel<4;channel++)for(const kind of ['read_ready','write_ready']){const current=b.ports[kind].positions[channel],original=b.ports[kind].original_positions[channel],p=delta.source_pairs.find(p=>p.bank===bank&&p.channel===channel);assert.deepEqual(kind==='read_ready'?p.read:p.write,current);assert.deepEqual(bodyMap.get(K(current)).original_position,original);outputs.push({channel,kind,current,old:original});}
 const currentPositions=cone(world,outputs.map(r=>r.current),roots.map(r=>r.current)),oldPositions=cone(old,outputs.map(r=>r.old),roots.map(r=>r.old)),oldN=evaluator(old,oldPositions,roots.map(r=>r.old)),newN=evaluator(world,currentPositions,roots.map(r=>r.current)),raw=[];
 for(const p of currentPositions){allSourceKeys.add(K(p));const oldp=inverse(p),a=old.get(K(oldp)),z=world.get(K(p));assert(a);if(JSON.stringify(a)!==JSON.stringify(z)){const matches=repairs.repairs.filter(r=>K(r.position)===K(p));assert.equal(matches.length,1);const r=matches[0];assert.deepEqual(r.original_position,oldp);assert.deepEqual(r.before,a);assert.deepEqual(r.after,z);patches.push(r);}}
 for(let mask=0;mask<256;mask++){const values=Array.from({length:8},(_,i)=>mask>>i&1?15:0),a=oldN.power(values),b=newN.power(values),expectedLevels=outputs.map(o=>expected(values,o)),oldLevels=outputs.map(o=>a.power.get(K(o.old))??0),currentLevels=outputs.map(o=>b.power.get(K(o.current))??0);assert.deepEqual(currentLevels,expectedLevels);for(let i=0;i<8;i++)if(oldLevels[i]!==currentLevels[i])rawMismatches.push({bank,mask,output:outputs[i],old:oldLevels[i],current:currentLevels[i]});raw.push({mask,old:oldLevels,current:currentLevels});}
 sourceRows.push({bank,roots,outputs,currentPositions,oldPositions,raw,current_feedback:newN.feedback});console.log('raw/current bank',bank,currentPositions.length);}
assert.equal(patches.length,12);assert.equal(new Set(patches.map(r=>K(r.position))).size,12);assert.equal(rawMismatches.length,256);assert.equal(stateIdentities.length,20);
const corrected=new Map(old);for(const r of patches)corrected.set(K(r.original_position),r.after);const repairMutations=[];let preservedSourceInputs=0;
for(const row of sourceRows){const oldRoots=row.roots.map(r=>r.old),newRoots=row.roots.map(r=>r.current),oldPositions=cone(corrected,row.outputs.map(o=>o.old),oldRoots),held=new Set(oldRoots.map(K)),ev=evaluator(corrected,oldPositions,oldRoots);assert.deepEqual(new Set(oldPositions.map(p=>K(translation(p)))),new Set(row.currentPositions.map(K)));for(const p of oldPositions){assert.deepEqual(corrected.get(K(p)),world.get(K(translation(p))));if(!held.has(K(p))){const a=inputs(corrected,p).map(q=>K(translation(q))).sort(),b=inputs(world,translation(p)).map(K).sort();assert.deepEqual(a,b);preservedSourceInputs+=a.length;}}
 for(let mask=0;mask<256;mask++){const values=Array.from({length:8},(_,i)=>mask>>i&1?15:0),v=ev.power(values),levels=row.outputs.map(o=>v.power.get(K(o.old))??0);assert.deepEqual(levels,row.raw[mask].current);sourceTruth.push({bank:row.bank,mask,levels});}
 for(const patch of patches.filter(p=>p.bank===row.bank)){corrected.set(K(patch.original_position),patch.before);const positions=cone(corrected,row.outputs.map(o=>o.old),oldRoots),bad=evaluator(corrected,positions,oldRoots);let witness;for(let mask=0;mask<256;mask++){const v=bad.power(Array.from({length:8},(_,i)=>mask>>i&1?15:0)),actual=row.outputs.map(o=>v.power.get(K(o.old))??0);if(JSON.stringify(actual)!==JSON.stringify(row.raw[mask].current)){witness={bank:row.bank,position:patch.original_position,mask,actual,expected:row.raw[mask].current};break;}}assert(witness);repairMutations.push(witness);corrected.set(K(patch.original_position),patch.after);}}
// Strict complete input differential, with isolated real components and actual
// consecutive cable vertices defining the only allowed new contacts.
const newKeys=new Set(delta.new_cells.map(r=>K(r.position))),isolated=new Map(placement.new_cells.map(r=>[K(r.position),r.block]));for(const p of delta.source_pairs.flatMap(r=>[r.read,r.write]))isolated.set(K(p),world.get(K(p)));for(const c of delta.connections.filter(c=>c.kind==='actual_backend_ready'))isolated.set(K(c.destination),world.get(K(c.destination)));
const permitted=new Map();function add(source,target){const k=K(target);if(!permitted.has(k))permitted.set(k,new Set());permitted.get(k).add(K(source));}for(const r of placement.new_cells)if(active(r.block))for(const q of inputs(isolated,r.position))add(q,r.position);
for(const c of delta.connections)for(let i=1;i<c.path.length;i++){const a=c.path[i-1],b=c.path[i];assert(inputs(world,b).some(p=>K(p)===K(a)));add(a,b);if(world.get(K(a)).id===W&&world.get(K(b)).id===W)add(b,a);}
const arrivals=new Map(delta.connections.filter(c=>c.kind==='actual_backend_ready').map(c=>[K(c.destination),K(c.arrival)]));let receivers=0,supports=0,oldInputs=0,newInputs=0,actualInputs=0;
for(const[k,b]of world){const p=P(...k.split(',').map(Number));let support;if(b.id===WT)support=A(p,D[b.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);if(support){assert(solid(world.get(K(support))),'Missing support '+k);supports++;}if(!active(b))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;if(base.has(k)){const expected=inputs(base,p).map(K);oldInputs+=expected.length;if(arrivals.has(k))expected.push(arrivals.get(k));assert.deepEqual(actual,[...new Set(expected)].sort(),'Changed old input '+k);}else{assert.deepEqual(actual,[...(permitted.get(k)??[])].sort(),'Undeclared new input '+k);newInputs+=actual.length;}}
console.log('full input screen',world.size,receivers,actualInputs);
const collectors=[],oldCollectors=[],newMutations=[],newRear=new Map(),reverse={east:'west',west:'east',north:'south',south:'north'},joint=[];
for(let channel=0;channel<4;channel++){const currentRoots=sourceRows.flatMap(r=>r.outputs.filter(o=>o.channel===channel).map(o=>o.current)),oldRoots=sourceRows.flatMap(r=>r.outputs.filter(o=>o.channel===channel).map(o=>o.old)),connection=delta.connections.find(c=>c.kind==='actual_backend_ready'&&c.channel===channel),destination=direct.ports['channel'+channel+'.backend.bank_ready'].positions[0],oldDestination=backend.controllers[channel].ports.bank_ready.positions[0],body=direct.blocks.find(r=>K(r.position)===K(destination));assert(body?.original_position);assert.deepEqual(A(body.original_position,backend.controllers[channel].origin),oldDestination);assert.deepEqual(connection.destination,destination);assert.deepEqual(world.get(K(destination)),old.get(K(oldDestination)));assert.deepEqual(oldReady.connections.find(c=>c.kind==='actual_backend_ready'&&c.channel===channel).destination,oldDestination);
 const oldPositions=cone(old,oldDestination,oldRoots),newPositions=cone(world,destination,currentRoots),oldEv=evaluator(old,oldPositions,oldRoots),newEv=evaluator(world,newPositions,currentRoots),truth=[];for(const p of newPositions)assert(newKeys.has(K(p))||[...currentRoots,destination].some(q=>K(q)===K(p)),'Foreign collector source');
 for(let mask=0;mask<256;mask++){const values=Array.from({length:8},(_,i)=>mask>>i&1?15:0),a=oldEv.power(values).power.get(K(oldDestination))??0,b=newEv.power(values);assert.equal(a,mask?15:0);assert.equal(b.power.get(K(destination))??0,a);truth.push({mask,old:a,current:b.power.get(K(destination))??0});if(mask===255)for(const p of newPositions)if(newKeys.has(K(p))&&world.get(K(p)).id===R){const rear=Math.max(0,...inputs(world,p).map(q=>b.power.get(K(q))??0));assert(rear>0);newRear.set(K(p),rear);}}
 collectors.push({channel,roots:currentRoots,destination,positions:newPositions,feedback:newEv.feedback,truth});oldCollectors.push({channel,roots:oldRoots,destination:oldDestination,devices:oldPositions.length,feedback:oldEv.feedback});
 const held=sourceRows.flatMap(r=>r.roots.filter(s=>['active','tail','reset','owner'+channel,'is_write'].includes(s.name)).map(s=>({...s,bank:r.bank}))),ps=cone(world,destination,held.map(s=>s.current)),full=evaluator(world,ps,held.map(s=>s.current));
 // Exhaust every bank's five relevant boundaries and every four-bank qualified
 // mask under both types; current source truth already covers all256 per bank.
 const patterns=[];for(let bank=0;bank<4;bank++)for(let mask=0;mask<32;mask++)patterns.push(held.map((s,i)=>s.bank===bank&&mask>>(i%5)&1?15:0));for(let mask=0;mask<16;mask++)for(const type of [0,15])patterns.push(held.map(s=>s.name==='is_write'?type:s.name==='reset'?0:mask>>s.bank&1?15:0));
 for(const values of patterns){const target=sourceRows.some(r=>{const v=Object.fromEntries(held.flatMap((s,i)=>s.bank===r.bank?[[s.name,values[i]]]:[]));return v.active&&v.tail&&!v.reset&&v['owner'+channel];}),actual=full.power(values).power.get(K(destination))??0;assert.equal(actual,target?15:0);joint.push({channel,values,actual});}
 function mutation(name,position,mutate,source){const original=world.get(K(position));assert(original);const next=mutate(original);if(next)world.set(K(position),next);else world.delete(K(position));let refused=false;try{const pos=cone(world,destination,currentRoots),bad=evaluator(world,pos,currentRoots),v=bad.power(currentRoots.map(p=>K(p)===K(source)?15:0));refused=(v.power.get(K(destination))??0)!==15;}catch{refused=true;}world.set(K(position),original);assert(refused,'Mutation survived '+name);newMutations.push({channel,name,position,source});}
 for(const pair of delta.source_pairs.filter(p=>p.channel===channel)){for(const[name,p,source]of [['read_tap',pair.read_tap,pair.read],['write_tap',pair.write_tap,pair.write],['pair_output',pair.tap,pair.read]])mutation(name,p,b=>({...b,properties:{...b.properties,facing:reverse[b.properties.facing]}}),source);}
 for(const c of delta.connections.filter(c=>c.channel===channel)){const source=delta.source_pairs.find(p=>p.channel===channel&&p.bank===(c.bank??0)).read;mutation('arrival',c.arrival,b=>({...b,properties:{...b.properties,facing:reverse[b.properties.facing]}}),source);}
 const col=delta.collectors[channel],source=currentRoots[0];mutation('collector_output',col.tap,b=>({...b,properties:{...b.properties,facing:reverse[b.properties.facing]}}),source);mutation('column_torch',P(col.base.x,col.base.y+3,col.base.z),()=>undefined,source);mutation('column_output_strong_solid',col.top,()=>undefined,source);console.log('collector',channel,'old/new',oldPositions.length,newPositions.length);}
assert.equal(newMutations.length,80);assert.equal(newRear.size,2147);assert.equal(Math.min(...newRear.values()),5);
const oldGroups={},materials={},columns=new Set();for(const r of oldTransport)oldGroups[r.part]=(oldGroups[r.part]??0)+1;for(const r of delta.new_cells)materials[r.block.id]=(materials[r.block.id]??0)+1;for(const k of world.keys()){const[x,,z]=k.split(',').map(Number);columns.add(Math.floor(x/16)+','+Math.floor(z/16));}
for(const n of ['review.mjs','frame.mjs','../fabric-colocation-v2/cut-inputs.mjs','../../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs','../../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs'])bytes(n);
write('receipt.json',{status:'passed_independent_actual_typed_bank_ready_review',metrics:{base_cells:base.size,new_cells:delta.new_cells.length,total_cells:world.size,receivers,supports,actual_inputs:actualInputs,preserved_inputs:oldInputs,new_inputs:newInputs,existing_arrivals:arrivals.size,old_cold_cells:scanned,source_devices:allSourceKeys.size,source_inputs:preservedSourceInputs,state_and_lock_identities:stateIdentities.length,source_cases:sourceTruth.length,source_observations:sourceTruth.length*8,raw_old_differing_observations:rawMismatches.length,inherited_refreshes:patches.length,refresh_reversion_refusals:repairMutations.length,collector_cases:1024,qualified_composition_cases:joint.length,new_geometry_mutations:newMutations.length,new_repeaters:newRear.size,minimum_rear:Math.min(...newRear.values())},state_identities:stateIdentities,source_proofs:sourceRows.map(({currentPositions,oldPositions,...r})=>({...r,current_devices:currentPositions.length,old_devices:oldPositions.length})),raw_differences:rawMismatches,corrected_source_truth:sourceTruth,exact_repairs:patches,repair_mutations:repairMutations,old_collectors:oldCollectors,collectors:collectors.map(({positions,...r})=>({...r,devices:positions.length})),qualified_composition:joint,new_geometry_mutations:newMutations,cost:{old_cells:oldTransport.length,old_groups:oldGroups,new_cells:delta.new_cells.length,saved_matched_scope:oldTransport.length-delta.new_cells.length,new_materials:materials,whole_columns:columns.size},source_sha256:pins,limits:['Direct actual old/full-current map reconstruction and distinct component-DAG settled evaluator. Physical-input rules are shared and conditional, not native Minecraft validation.','Raw old READY qualification is explicitly different; exactly12 previously frozen refreshes reconcile old/current source gates. No new body edits and no unconditional raw-equivalence claim.','Owner/type storage Q, ACTIVE, final tail and reset blocker are held boundaries. Capture, epochs, reset/start sequencing, READY/data order and routed timing remain open.','Exact2,184,528-cell READY-era partial frame excludes later root returns and live BUSY additions, both cores and unfinished response/master/loading links. No whole-GPU acceptance.']});console.log(JSON.stringify({status:'passed',cells:world.size,receivers,actualInputs,sourceDevices:allSourceKeys.size,sourceInputs:preservedSourceInputs,rawMismatches:rawMismatches.length,refreshes:patches.length,mutations:newMutations.length,minimum:Math.min(...newRear.values())}));
