import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';
import {makeDispatchInputSampling,SAMPLE_INPUTS} from '../../../hardware/full-gpu-dispatch-input-sampling-v1.mjs';
import {makeStateBank} from '../../../hardware/full-gpu-state-bank.mjs';
import {materializeInstance} from '../../../hardware/gpu-layout-assembly.mjs';
import {possibleStrengths} from '../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const base=read('../dispatch-startup-v1/admission-destinations/design.json'),bank=materializeInstance(makeStateBank({width:5,pair:false}),{id:'input_samples',translation:P(500,128,-64)}),d=makeDispatchInputSampling();assert.deepEqual(d,read('design.json'));
function check(d){
 const m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to))),ids=new Set(['dispatcher_parent','input_samples']);assert.equal(m.size,d.blocks.length);
 for(const v of [...base.blocks,...bank.blocks])assert.deepEqual(at(v.position)?.block,v.block,'Inherited '+K(v.position));
 let supports=0,contacts=0,directions=0,oldGraph=0;
 for(const v of d.blocks.filter(v=>v.part!=='dispatcher_parent')){if(v.block.id.endsWith('_concrete')||v.block.id==='minecraft:redstone_block')continue;const p=v.block.id==='minecraft:redstone_wall_torch'?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 const wireNeighbors=(map,p)=>{const out=[];for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(p,dir);q.y+=dy;const v=map.get(K(q));if(v?.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&map.has(K({...p,y:p.y+1})))continue;if(dy===-1&&map.has(K({...q,y:p.y})))continue;out.push(K(q));}return out.sort();};
 for(const v of base.blocks.filter(v=>v.block.id==='minecraft:redstone_wire')){assert.deepEqual(wireNeighbors(m,v.position).filter(k=>old.has(k)),wireNeighbors(old,v.position),'Old graph '+K(v.position));oldGraph++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||o.block.id.endsWith('_concrete'))continue;if(ids.has(v.part)&&o.part===v.part)continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q)+' '+v.part+'/'+o.part);contacts++;}
 for(const v of d.blocks.filter(v=>!ids.has(v.part)&&v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const s of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete'),'Foreign side '+K(v.position));}directions++;}
 for(const c of d.columns){assert.equal((c.output_y-c.bottom)%4,1);for(let y=c.bottom;y<c.output_y;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.deepEqual(add(c.injector,D[at(c.injector).block.properties.facing]),P(c.x,c.bottom,c.z));}
 assert.equal(d.samples.length,5);assert.equal(d.connections.length,6);
 for(const[i,s]of d.samples.entries()){assert.equal(s.name,SAMPLE_INPUTS[i]);assert.deepEqual(s.source,bank.ports.state.bits[i].position);assert.deepEqual(s.raw,bank.ports.next_data.bits[i].position);assert.deepEqual(s.destination,base.ports[s.name].bits[0].position);assert.deepEqual(d.ports[s.name].bits[0].position,s.raw);assert.deepEqual(add(s.lock,D[at(s.lock).block.properties.facing]),s.storage);const c=d.connections[i];assert.deepEqual(c.source,s.source);assert.deepEqual(c.destination,s.destination);assert.deepEqual(add(c.arrival,D[at(c.arrival).block.properties.facing]),s.destination);}
 assert.deepEqual(d.phase.source,P(581,-100,-420));assert.deepEqual(d.connections[5].destination,bank.ports.state_open.bits[0].position);
 // Unchanged command outputs are real stored cells, not raw macro-state exports.
 for(let bit=0;bit<6;bit++){assert.deepEqual(d.ports.output_state.bits[bit],base.ports.output_state.bits[bit]);const p=P(327,1+4*bit,-32);assert.equal(at(p).block.id,'minecraft:redstone_wire');}
 const power=possibleStrengths(d);assert.deepEqual(power.failed,[]);return{parent_cells:base.blocks.length,sample_bank_cells:bank.blocks.length,support_checks:supports,new_contact_checks:contacts,new_direction_checks:directions,preserved_old_wire_graphs:oldGraph,possible_strength:power};
}
const checks=check(d);let corruptions=0;
for(const mutate of[c=>{const p=c.connections[0].arrival;c.blocks.find(v=>K(v.position)===K(p)).block.properties.facing='south';},c=>{c.samples[1].source=c.samples[0].source;},c=>{const p=c.columns[0].injector;c.blocks=c.blocks.filter(v=>K(v.position)!==K(p));},c=>{c.ports.core_ack0=c.ports.core_ack1;}]){const v=structuredClone(d);mutate(v);assert.throws(()=>check(v));corruptions++;}
const result={status:'offline_dispatch_input_sampling_geometry_pass',...d.metrics,...checks,corruption_refusals:corruptions,native_calls:0,native_acceptance:false,limits:d.missing};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,possible_strength:{...result.possible_strength,taps:undefined}}));
