// Deterministic static geometry and integer oracle only. No native tool imports.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeDataBank64} from '../../../../hardware/memory-layout-data-bank.mjs';
import {makeMemorySubarray,key} from '../../../../hardware/memory-layout-subarray.mjs';
const d=makeDataBank64();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));
const card=makeMemorySubarray({kind:'ram',bits:8,id:'ram16x8'}),P=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',V={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(V);
function check(d){const m=new Map(d.blocks.map(v=>[key(v.position),v.block])),get=p=>m.get(key(p));assert.equal(m.size,d.blocks.length);const rep=(p,f)=>assert.deepEqual(get(p),{id:'minecraft:repeater',properties:{facing:f,delay:'1'}}),cmp=(p,f)=>assert.deepEqual(get(p),{id:'minecraft:comparator',properties:{facing:f,mode:'subtract'}}),wire=p=>assert.equal(get(p)?.id,'minecraft:redstone_wire'),edge=(a,b)=>[key(a),key(b)].sort().join('|'),allowed=new Set();let preserved=0,supports=0,faces=0;
 for(const c of d.cards){const omit=new Map(d.omitted_source_cells.filter(v=>v.card===c.card).map(v=>[key(v.position),v]));assert.equal(omit.size,c.tier?56:0);for(const v of card.blocks){const p=P(v.position.x,v.position.y+c.origin.y,v.position.z+c.origin.z);if(omit.has(key(p))){const q=omit.get(key(p));assert.deepEqual(q.block,v.block);const x=v.position.x,y=v.position.y,z=v.position.z;assert(c.tier&&y<=1);assert(card.ports.address.positions.some(t=>z===t.z&&[t.x,t.x===32?31:17].includes(x))||card.ports.write_data.positions.some(t=>z===t.z&&[t.x,t.x===-2?-1:13].includes(x))||y===0&&[0,12].includes(x)&&[0,8,16,24].includes(z));continue;}assert.deepEqual(get(p),v.block,'parent '+key(p));preserved++;}}
 for(const v of d.blocks){const p=v.position,b=v.block;if(b.id===S)continue;let q=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const [dx,dz]=V[b.properties.facing];q=P(p.x+dx,p.y,p.z+dz);}assert.equal(get(q)?.id,S,'support '+key(p));supports++;}
 for(const r of d.routes){assert(r.max_dust_run<=14);for(const p of r.refresh){const i=r.path.findIndex(q=>key(q)===key(p)),[dx,dz]=V[get(p).properties.facing];assert.deepEqual(r.path[i-1],P(p.x-dx,p.y,p.z-dz));assert.deepEqual(r.path[i+1],P(p.x+dx,p.y,p.z+dz));}}
 for(const c of d.cards){const n=c.card,Z=c.origin.z,Y=c.origin.y,y=-5+Y,high=131+Y;cmp(P(6,y+2,Z-21),'north');rep(P(5,y+2,Z-21),'west');rep(P(6,y+2,Z-22),'north');rep(P(6,y+2,Z-20),'north');rep(P(6,Y+1,Z-18),'north');wire(P(6,Y+1,Z-17));
  allowed.add(edge(P(6,y+2,Z-21),P(5,y+2,Z-21)));allowed.add(edge(P(6,y+2,Z-21),P(6,y+2,Z-22)));allowed.add(edge(P(6,Y+1,Z-17),P(6,Y+1,Z-16)));
  for(let a=0;a<2;a++){const x=a?10:2;assert.equal(get(P(x,y,Z-36))?.id,((n>>a)&1)?S:'minecraft:repeater');if((n>>a)&1)assert.equal(get(P(a?9:3,y,Z-36))?.id,'minecraft:redstone_wall_torch');else rep(P(x,y,Z-36),a?'east':'west');}
  for(let b=0;b<8;b++){const right=b>=4,z=8*(b%4)+Z,x=right?10:2,g=right?12:0;base: {const base=123+Y;rep(P(x,base,z-1),'south');assert.equal(get(P(x,base+1,z-1))?.id,S);for(let yy=base;yy<=high;yy++)assert.equal(get(P(x,yy,z-2))?.id,(yy-base)%2?'minecraft:redstone_torch':S);}
   cmp(P(g,high,z-2),right?'west':'east');rep(P(g,high,z-3),'north');rep(P(right?11:1,high,z-2),right?'west':'east');allowed.add(edge(P(g,high,z-2),P(g,high,z-3)));}
 }
 for(const v of d.blocks){const p=v.position,b=v.block;if(d.groups[key(p)]==='inherited_card'||b.id===S)continue;for(const[dx,dz]of dirs){const q=P(p.x+dx,p.y,p.z+dz),bb=get(q);if(bb&&bb.id!==S&&d.nets[key(p)]!==d.nets[key(q)]){assert(allowed.has(edge(p,q)),'foreign face '+key(p)+' '+key(q));faces++;}if(b.id==='minecraft:redstone_wire')for(const dy of[-1,1]){const q=P(p.x+dx,p.y+dy,p.z+dz);if(get(q)?.id!=='minecraft:redstone_wire'||d.nets[key(p)]===d.nets[key(q)])continue;if(dy>0&&get(P(p.x,p.y+1,p.z))||dy<0&&get(P(q.x,p.y,q.z)))continue;assert.fail('foreign slope '+key(p)+' '+key(q));}}
  if(['minecraft:repeater','minecraft:comparator'].includes(b.id)){const[dx,dz]=V[b.properties.facing];for(const[sx,sz]of dirs.filter(([x,z])=>x*dx+z*dz===0)){const q=P(p.x+sx,p.y,p.z+sz),bb=get(q);if(!['minecraft:repeater','minecraft:comparator'].includes(bb?.id))continue;const[x,z]=V[bb.properties.facing];if(q.x+x===p.x&&q.z+z===p.z)assert(b.id==='minecraft:comparator'&&allowed.has(edge(p,q)),'side source '+key(p));}}
 }
 for(let b=0;b<8;b++)for(let stack=0;stack<2;stack++)wire(P(6,-28-4*b,8*(b%4)+64*stack));
 for(const p of Object.values(d.ports))for(const q of p.positions)assert(get(q),'missing port');assert.equal(faces,84);assert.equal(preserved,45912);
 return{preserved_card_cells:preserved,explicit_upper_external_omissions:112,support_checks:supports,intended_directed_boundary_faces:faces,foreign_dust_slopes:0,unexpected_directed_side_sources:0};}
const checked=check(d);let negatives=0;function bad(fn){const x=structuredClone(d);fn(x);assert.throws(()=>check(x));negatives++;}
bad(x=>x.blocks.find(v=>key(v.position)==='6,-3,-21').block.properties.mode='compare');bad(x=>x.blocks=x.blocks.filter(v=>key(v.position)!=='5,-3,-21'));bad(x=>x.blocks.find(v=>key(v.position)==='0,131,-2').block.properties.facing='west');bad(x=>x.blocks=x.blocks.filter(v=>key(v.position)!=='2,124,-1'));bad(x=>x.blocks.find(v=>key(v.position)==='2,1,0').block.properties.facing='east');bad(x=>x.blocks.find(v=>key(v.position)==='6,-40,24').block={id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});bad(x=>x.omitted_source_cells.push({card:0,position:P(2,1,0),block:{id:'minecraft:repeater'}}));
// Independent address decomposition / store oracle. Values are software-only
// expectations, not native results or a replacement for runtime RAM.
let cases=0;for(let a=0;a<64;a++)for(let value=0;value<256;value++){const high=a>>4,row=a&15;const masks=Object.fromEntries(d.cards.map(c=>[c.card,Number(c.card!==high)]));assert.equal(Object.values(masks).filter(x=>!x).length,1);const before=Array.from({length:64},(_,i)=>(i*37+83)&255),after=[...before];for(const c of d.cards)for(let r=0;r<16;r++)if(!masks[c.card]&&r===row)after[16*c.card+r]=value;assert.equal(after[a],value);for(let i=0;i<64;i++)if(i!==a)assert.equal(after[i],before[i]);cases++;}
const out={status:'offline64_byte_bank_geometry_and_integer_oracle_pass',...d.metrics,...checked,software_write_isolation_cases:cases,geometry_negative_cases:negatives,native_acceptance:false,limits:d.missing};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
