// Independent bounded review: direct source loading, actual cold context,
// complete input differential, and a separate directed-network strength solver.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function insert(map,rows,{same=false}={}){for(const r of rows){const k=K(r.position);if(map.has(k)){assert(same,'Duplicate cell '+k);assert.deepEqual(map.get(k),r.block);}else map.set(k,r.block);}}
function scanBlocks(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const part=buffer.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){visit(r);count++;}};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated blocks');}
function cone(world,end,root){const roots=Array.isArray(root)?root:[root],stop=new Set(roots.map(K)),seen=new Map(),queue=Array.isArray(end)?[...end]:[end];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(world.get(k)),'Missing actual dependency '+k);seen.set(k,p);if(!stop.has(k))queue.push(...inputs(world,p));}for(const r of roots)assert(seen.has(K(r)),'Source absent from cone '+K(r));return [...seen.values()];}
function network(world,positions,root){
 const roots=Array.isArray(root)?root:[root],index=new Map(positions.map((p,i)=>[K(p),i])),rootIndices=new Set(roots.map(p=>index.get(K(p))));assert(!rootIndices.has(undefined));
 const rows=positions.map(p=>({p,b:world.get(K(p))})),incoming=positions.map(()=>[]),outgoing=positions.map(()=>[]);let edges=0;
 for(let i=0;i<rows.length;i++){assert([W,R,C,T,WT,'minecraft:redstone_block'].includes(rows[i].b.id),'Unexpected transport device '+rows[i].b.id+' '+K(rows[i].p));if(rootIndices.has(i))continue;const deps=inputs(world,rows[i].p);if(rows[i].b.id===R){const v=D[rows[i].b.properties.facing];assert(deps.every(q=>(q.x-rows[i].p.x)*v.x+(q.z-rows[i].p.z)*v.z<0),'Unmodeled side lock');}for(const q of deps){const j=index.get(K(q));assert.notEqual(j,undefined,'Foreign source '+K(q));incoming[i].push(j);outgoing[j].push(i);edges++;}}
 const visited=new Uint8Array(rows.length),order=[];for(let i=0;i<rows.length;i++)if(!visited[i]){visited[i]=1;const stack=[[i,0]];while(stack.length){const r=stack.at(-1);if(r[1]<outgoing[r[0]].length){const j=outgoing[r[0]][r[1]++];if(!visited[j]){visited[j]=1;stack.push([j,0]);}}else{order.push(r[0]);stack.pop();}}}
 const assigned=new Uint8Array(rows.length);let components=0,wireLoops=0;for(let n=order.length-1;n>=0;n--){const i=order[n];if(assigned[i])continue;const members=[i];assigned[i]=1;for(let at=0;at<members.length;at++)for(const j of incoming[members[at]])if(!assigned[j]){assigned[j]=1;members.push(j);}components++;if(members.length>1||outgoing[i].includes(i)){assert(members.every(j=>rows[j].b.id===W),'Nonwire transport feedback');wireLoops++;}}
 function power(strength){const values=new Uint8Array(rows.length),waiting=new Uint8Array(rows.length).fill(1),queue=rows.map((_,i)=>i);for(const p of roots)values[index.get(K(p))]=typeof strength==='number'?strength:strength.get(K(p))??0;let events=0;for(let at=0;at<queue.length;at++){const i=queue[at];waiting[i]=0;if(rootIndices.has(i))continue;assert(++events<1000000,'Nonconvergent network');let value=0;for(const j of incoming[i])value=Math.max(value,values[j]-(rows[i].b.id===W&&rows[j].b.id===W?1:0));if(rows[i].b.id===R)value=value>0?15:0;else if([T,WT].includes(rows[i].b.id))value=value>0?0:15;else if(rows[i].b.id==='minecraft:redstone_block')value=15;else if(rows[i].b.id===C){const d=D[rows[i].b.properties.facing],rear=incoming[i].filter(j=>(rows[j].p.x-rows[i].p.x)*d.x+(rows[j].p.z-rows[i].p.z)*d.z<0),side=incoming[i].filter(j=>!rear.includes(j)),a=Math.max(0,...rear.map(j=>values[j])),b=Math.max(0,...side.map(j=>values[j]));value=rows[i].b.properties.mode==='subtract'?Math.max(0,a-b):a>=b?a:0;}if(value!==values[i]){values[i]=value;for(const j of outgoing[i])if(!waiting[j]){waiting[j]=1;queue.push(j);}}}return {values,get:p=>values[index.get(K(p))]??0,events};}
 return {power,metrics:{devices:rows.length,edges,components,torch_vertices:rows.filter(r=>[T,WT].includes(r.b.id)).length,wire_conductance_components:wireLoops,nonwire_feedback_components:0},minimumRear(powers,subset){return Math.min(...rows.flatMap((r,i)=>r.b.id===R&&(!subset||subset.has(K(r.p)))?[Math.max(0,...incoming[i].map(j=>powers.values[j]))]:[]));}};
}

export {H,ROOT,pins,P,K,A,W,R,C,T,WT,D,solid,bytes,read,write,insert,scanBlocks,cone,network};
