// Independent ledger diff: infer the two cut chains from original geometry and ports.
import assert from'node:assert/strict';
import{read,write,bytes,pins,K,P,A,D,R,W,insert}from'./independent-network.mjs';
import{inputs}from'../memory/fabric-colocation-v2/cut-inputs.mjs';
const before=read('../loader-global-delivery-v1/remaining-cuts.json'),after=read('../global-loader-return-v1/remaining-cuts.json'),delta=read('../global-loader-return-v1/delta.json','7a5a780a41e84b0967539e80841431d8971f52fb1c52dc5c2831289c7e2d2070'),endpoints=read('../global-loader-return-v1/endpoint-map.json'),proof=read('receipt.json'),original=read('../master-loader-control-routes-v1/design.json'),oldMap=new Map();
insert(oldMap,original.blocks);for(const s of proof.body_records)insert(oldMap,[{position:s.original,block:s.block}],{same:true});
const chains=[];for(const port of['memory_admission_block','cold_initialized']){
 const route=original.connections.find(c=>c.source_instance==='global'&&c.source_port===port&&c.destination_instance==='loader'&&c.destination_port==='loader.'+port);assert(route);
 const source=proof.stores.find(s=>s.name===port);assert.deepEqual(source.original_output,route.source);
 const numerical=proof.original.proofs.find(p=>p.name===port);assert.deepEqual(numerical.source,route.source);assert.deepEqual(numerical.destination,route.destination);
 const current=proof.current.proofs.find(p=>p.name===port),c=delta.connections.find(c=>K(c.root)===K(source.current_output)&&K(c.destination)===K(current.destination));assert(c);
 const direct=before.dispatch.direct_foreign_boundaries.filter(r=>K(r.source)===K(route.source)&&r.target_body==='foreign/master-loader-control-routes-v1');assert.equal(direct.length,1);
 const a=direct[0];assert.equal(a.status,'pending');assert.deepEqual(oldMap.get(K(a.source)),a.source_block);assert.deepEqual(oldMap.get(K(a.target)),a.target_block);assert(inputs(oldMap,a.target).some(p=>K(p)===K(a.source)));
 const effective=before.dispatch.effective_cut_ledger.filter(r=>K(r.source)===K(a.source)&&K(r.target)===K(a.target));assert.equal(effective.length,1);
 const loader=before.service.loader_control.filter(r=>K(r.source)===K(route.normalizer)&&K(r.target)===K(route.destination));assert.equal(loader.length,1);assert.equal(loader[0].status,'pending');
 assert.deepEqual(oldMap.get(K(route.normalizer)),loader[0].source_block);oldMap.set(K(route.destination),loader[0].target_block);assert(inputs(oldMap,route.destination).some(p=>K(p)===K(route.normalizer)));
 chains.push({port,direct_index:a.index,effective_index:effective[0].index,loader_index:loader[0].index,original_source:route.source,original_departure:a.target,original_arrival:route.normalizer,original_target:route.destination,current:c});
}
assert.deepEqual(chains.map(c=>[c.direct_index,c.effective_index,c.loader_index]),[[19,632,23],[20,633,22]]);
const expected=structuredClone(before);for(const c of chains){const n=c.current;Object.assign(expected.dispatch.direct_foreign_boundaries[c.direct_index],{status:'bound_actual_held_global_return_to_loader',shared_departure:n.source_isolator,shared_receiver:n.destination,shared_normalizer:n.normalizer,shared_route:n.name});Object.assign(expected.dispatch.effective_cut_ledger[c.effective_index],{status:'bound_actual_held_global_return_to_loader',shared_source:n.root,shared_target:n.destination,shared_arrival:n.normalizer,shared_route:n.name});Object.assign(expected.service.loader_control[c.loader_index],{status:'bound_actual_global_held_return',shared_source:n.root,shared_target:n.destination,shared_arrival:n.normalizer,shared_route:n.name,global_direct_index:c.direct_index});}
Object.assign(expected.service.counts,{loader_pending:13,loader_control_bound_total:15,loader_control_pending:13});
// Narrative status/limitations and added provenance are checked separately; every ledger record stays exact.
expected.status=after.status;expected.limits=after.limits;expected.source_sha256=after.source_sha256;
function verify(candidate){assert.deepEqual(candidate,expected);}
verify(after);assert.deepEqual(endpoints.connections,delta.connections);assert.equal(endpoints.retained_stores.length,5);for(const row of endpoints.retained_stores){const s=proof.stores.find(x=>x.name===row.name);assert(s);assert.deepEqual(row,{name:s.name,original_q:s.original_q,current_q:s.current_q,original_output:s.original_output,current_output:s.current_output,block:s.storage_block,original_lock:s.original_lock,current_lock:s.current_lock,lock_block:s.lock_block});}
assert.equal(after.dispatch.transfers.length,352);assert.equal(after.dispatch.effective_cut_ledger.length,661);assert.equal(after.dispatch.direct_foreign_boundaries.length,48);assert.equal(after.service.loader_control.length,28);assert.equal(after.service.panel_cuts.length,79);assert.equal(after.service.witness_external_inputs.length,37);assert.equal(after.program.length,44);
for(const [p,h]of Object.entries(before.source_sha256))assert.equal(after.source_sha256[p],h);
const remaining={global_incoming:after.dispatch.transfers.filter(r=>r.status==='external_source_transfer_pending').length,global_direct:after.dispatch.direct_foreign_boundaries.filter(r=>r.status==='pending').length,program:after.program.filter(r=>r.status.startsWith('pending')).length,loader:after.service.loader_control.filter(r=>r.status==='pending').length,panel:after.service.panel_cuts.filter(r=>r.status==='pending_global_grant_or_writer_observation').length,witness:after.service.witness_external_inputs.filter(r=>r.status==='pending_actual_shared_frame_cable').length};
// Count exact status literals from the unchanged witness/panel records, without inheriting summary totals.
assert.equal(remaining.witness,after.service.counts.witness_input_pending);assert.equal(remaining.panel,after.service.counts.panel_pending);
assert.deepEqual(remaining,{global_incoming:8,global_direct:29,program:42,loader:13,panel:11,witness:9});assert.deepEqual(endpoints.remaining,remaining);assert.equal(after.dispatch.direct_foreign_boundaries[22].status,'pending');
const negative=[];for(const c of chains)for(const [section,array,index,field]of[
 ['dispatch','direct_foreign_boundaries',c.direct_index,'shared_retained_source'],['dispatch','direct_foreign_boundaries',c.direct_index,'shared_departure'],['dispatch','direct_foreign_boundaries',c.direct_index,'shared_receiver'],['dispatch','direct_foreign_boundaries',c.direct_index,'shared_normalizer'],['dispatch','effective_cut_ledger',c.effective_index,'shared_source'],['dispatch','effective_cut_ledger',c.effective_index,'shared_target'],['dispatch','effective_cut_ledger',c.effective_index,'shared_arrival'],['service','loader_control',c.loader_index,'shared_source'],['service','loader_control',c.loader_index,'shared_target'],['service','loader_control',c.loader_index,'shared_arrival']]){
 const bad=structuredClone(after);bad[section][array][index][field].x++;assert.throws(()=>verify(bad));negative.push({section,array,index,field,mutation:'shift exact cut endpoint by one block'});
}
for(const c of chains){const bad=structuredClone(after);bad.service.loader_control[c.loader_index].global_direct_index=chains.find(x=>x!==c).direct_index;assert.throws(()=>verify(bad));negative.push({index:c.loader_index,mutation:'swap originating global command index'});}
{const bad=structuredClone(after);bad.dispatch.direct_foreign_boundaries[22].status='bound_actual_held_global_return_to_loader';assert.throws(()=>verify(bad));negative.push({index:22,mutation:'claim distinct core-service fanout'});}
bytes('ledger-review.mjs');write('ledger-receipt.json',{status:'independent_exact_two_return_ledger_passed',chains,metrics:{transfers:352,effective_cuts:661,direct_foreign_cuts:48,loader_cuts:28,changed_records:6,unchanged_global_transfer_records:352,remaining,wrong_bindings_refused:negative.length},negative,source_sha256:pins,limits:['Only two source-specific cut chains are newly bound. All other original record identities and statuses remain exact.','READY compatibility has no ledger credit in this review. The inherited memory ledger and separate bank-quiet fields remain byte-equivalent as parsed records.']});console.log(JSON.stringify({status:'independent_exact_two_return_ledger_passed',remaining,negative:negative.length}));
