// Offline, versioned replacement of the embedded ALU body and its local conflicting adapters.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';import{materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),sha=n=>createHash('sha256').update(readFileSync(new URL(n,import.meta.url))).digest('hex'),W='minecraft:redstone_wire',T=P(1400,-34,0),atAlu=p=>P(p.x+T.x,p.y+T.y,p.z+T.z);
export function makeAluCore({plan=false}={}){
 assert.equal(sha('../control-start-other-v1/source-manifest.json'),'71db6605a08aeb8e9d66fa4f7bf9c18c952b656baee2d01fd9fc2b0ea86d0323');assert.equal(sha('../alu-four-lane-fanout-v5/source-manifest.json'),'c19608b6016bcabde2501c7577abf2ad41f2781f811bb57ddfab21ec00c8ab56');
 const core=read('../control-start-other-v1/design.json'),alu=read('../alu-four-lane-fanout-v5/design.json'),oldAlu=read('../alu-four-lane-fanout-v2/qaux-design.json'),fault=read('../alu-four-lane-fanout-v4/fault-design.json'),inhib=read('../alu-four-lane-fanout-v4/inhibit-design.json');
 const oldCore=read('../control-commit-v2/design.json'),replacedCore=oldCore.blocks.filter(v=>v.part==='actual_all_status_low'),replacedCoreKeys=new Set(replacedCore.map(v=>K(v.position))),oldStatusConnection=oldCore.connections.find(v=>v.name==='actual_all_status_low');
 const coreMap=new Map(core.blocks.map(v=>[K(v.position),v.block]));for(const v of replacedCore)assert.deepEqual(coreMap.get(K(v.position)),v.block,'Exact removed old status route '+K(v.position));
 const old=new Map(oldAlu.blocks.map(v=>[K(v.position),v.block])),removedLocal=new Map([...fault.blocks.filter(v=>v.part!=='matched_parent'),...inhib.blocks.filter(v=>/^lane\d_actual_enable_to_allow$/.test(v.part))].map(v=>[K(v.position),v])),map=new Map(core.blocks.filter(v=>!replacedCoreKeys.has(K(v.position))).map(v=>[K(v.position),{...v,part:'core_parent'}]));let inherited=0,newAlu=0;
 for(const v of alu.blocks){const k=K(v.position),p=atAlu(v.position);if(old.has(k)){assert.deepEqual(v.block,old.get(k));assert.deepEqual(map.get(K(p))?.block,v.block,'Original embedded ALU '+K(p));inherited++;continue;}if(removedLocal.has(k))continue;assert(!map.has(K(p)),'Unresolved composition overlap '+K(p));map.set(K(p),{position:p,block:v.block,part:'alu_extension'});newAlu++;}
 assert.equal(inherited,348349);const edges=[],routes=[],connections=[],columns=inhib.columns.map(c=>({...c,x:c.x+T.x,z:c.z+T.z,bottom:c.bottom+T.y,top:c.top+T.y,output_y:c.output_y+T.y,injection_y:c.injection_y.map(y=>y+T.y)}));
 for(const n of['load-design','addend-design','arithmetic-design','status-design']){const d=read('../alu-four-lane-fanout-v3/'+n+'.json');for(const e of d.edges)edges.push({from:atAlu(e.from),to:atAlu(e.to)});}
 for(const d of[inhib,alu])for(const e of d.edges)if(!removedLocal.has(K(e.from))&&!removedLocal.has(K(e.to)))edges.push({from:atAlu(e.from),to:atAlu(e.to)});
 let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to});
 function put(p,id,properties){const block={id:'minecraft:'+id,...properties?{properties}:{}},o=at(p);if(o){assert.equal(id,'light_gray_concrete','Collision '+part+' '+K(p)+' '+o.part);assert.deepEqual(o.block,block,'Support collision '+part+' '+K(p)+' '+o.part);return;}map.set(K(p),{position:p,block,part});}
 const solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'});
 function fixed(name,ws){part=name;const path=[ws[0]];for(let n=1;n<ws.length;n++){const a=ws[n-1],b=ws[n],dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,steps=Math.abs(dx)+Math.abs(dz);assert(steps&&(!dx||!dz)&&(!dy||Math.abs(dy)===steps));for(let i=1;i<=steps;i++)path.push(P(a.x+Math.sign(dx)*i,a.y+Math.sign(dy)*i,a.z+Math.sign(dz)*i));}const refresh=refreshIndices(path);for(let i=0;i<path.length;i++){const p=path[i],q=path[i+1];if(refresh.includes(i)){const d=Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z);rep(p,d);}else wire(p);if(i)edge(path[i-1],p);}routes.push({name,path,refresh_indices:refresh});}
 // Preserve the four real source and comparator endpoints while clearing incoming core lane-mask routes.
 for(let i=0;i<4;i++){const y=309+8*i,ws=[[738,y,158],[738,y+4,154],[738,y+4,150],[762,y+4,150],[762,y+4,156],[762,y,160]].map(v=>atAlu(P(...v)));fixed('lane'+i+'_enable_to_OPEN_allow_repair',ws);edge(atAlu(P(738,y,159)),ws[0]);edge(ws.at(-1),atAlu(P(763,y,160)));connections.push({name:'lane'+i+'_enable_to_OPEN_allow_repair',source:atAlu(P(738,y,160)),tap:atAlu(P(738,y,159)),destination:atAlu(P(764,y,160)),arrival:atAlu(P(763,y,160))});}
 const cacheURL=new URL('routes.json',import.meta.url),cache=existsSync(cacheURL)?read('routes.json'):{},pending=[],reserved=[],step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),reserve=(s,sd,d,ad)=>[...Array.from({length:18},(_,i)=>step(s,sd,i+2)),...Array.from({length:18},(_,i)=>step(d,ad,-i-2))];
 function draw(name,source,sd,destination,ad,stubs=false){part=name;assert.equal(at(source)?.block.id,W,'source '+name);assert.equal(at(destination)?.block.id,W,'destination '+name);const first=step(source,sd),start=step(source,sd,2),last=step(destination,ad,-1),end=step(destination,ad,-2);if(stubs){rep(first,sd);wire(start);rep(last,ad);wire(end);edge(source,first);edge(first,start);edge(end,last);edge(last,destination);return;}let path=cache[name]?.path;if(!path){assert(plan,'Missing route '+name);const ignore=[...reserve(source,sd,destination,ad),first,start,last,end,...[first,start,last,end].map(p=>P(p.x,p.y-1,p.z))],forbidden=[first,last].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![source,start,end,destination].some(q=>K(p)===K(q))),r=searchPath(map,start,end,{ignore,reserved,forbidden});path=r.path;cache[name]={source,destination,path,expanded:r.expanded};writeFileSync(cacheURL,JSON.stringify(cache)+'\n');console.error(name+': '+path.length+' / '+r.expanded);}assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i)){const dir=Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source,tap:first,destination,arrival:last});}
 pending.push(['all_four_status_low_to_core_repair',oldStatusConnection.source,'east',oldStatusConnection.destination,'south']);
 pending.push(['enabled_fault_to_ALU_controller_repair',atAlu(P(744,336,176)),'north',atAlu(P(28,-3,13)),'west']);
 // Retained IR-derived control outputs, held by the existing REQUEST/UPDATE ownership protocol.
 for(const[name,x,targetX]of[['mode0',158,52],['mode1',162,58],['compare',166,46]])pending.push(['held_IR_'+name+'_to_ALU',P(x,124,82),'north',atAlu(P(targetX,-3,13)),'south']);
 const laneOrigin=i=>P([400,584,400,584][i],[112,112,236,236][i],0),lanePort=(i,p)=>{const t=laneOrigin(i);return atAlu(P(p.x+t.x,p.y+t.y,p.z+t.z));};
 for(let i=0;i<4;i++)pending.push(['actual_enable_to_lane_'+i,atAlu(P(762,309+8*i,160)),'west',lanePort(i,P(60,61,-24)),'east']);
 // A single stable boundary value is forwarded through isolated normalized receiving pads;
 // each lane remains physically independent and keeps its own data/status storage.
 for(const[name,x,local]of[['execute_request',34,P(60,61,-12)],['mode0',52,P(0,61,0)],['mode1',58,P(0,61,12)],['compare',46,P(0,61,24)]]){
  let source=atAlu(P(x,-3,13)),direction='east';for(const i of[0,1,3,2]){const target=lanePort(i,local);pending.push([name+'_to_lane_'+i,source,direction,target,name==='execute_request'?'east':'south']);source=target;direction=name==='execute_request'?'north':'south';}
 }

 for(const[,s,sd,d,ad]of pending)reserved.push(...reserve(s,sd,d,ad));for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=blocks.reduce((n,v)=>Math.min(n,v.position[a]),Infinity);box.to[a]=blocks.reduce((n,v)=>Math.max(n,v.position[a]),-Infinity);}
 const ports={...core.ports,alu:materializeInstance({blocks:[],ports:alu.ports},{id:'alu',translation:T}).ports};
 return{status:'offline_core_ALU41_high_level_controls_connected_conditioning_pending',blocks,box,ports,edges,routes,connections,columns,removed_core_route_cells:replacedCore,removed_ALU_adapter_cells:[...removedLocal.values()].map(v=>({...v,position:atAlu(v.position)})),parents:{core:{blocks:core.blocks.length},new_ALU:{blocks:alu.blocks.length,translation:T,shared_blocks:inherited,inserted_blocks:newAlu}},metrics:{blocks:blocks.length,parent_core_blocks:core.blocks.length,rerouted_core_cells:replacedCore.length,ALU_extension_blocks:newAlu,rerouted_ALU_adapter_cells:removedLocal.size,new_connections:connections.length,retained_bits:876},native_calls:0,native_acceptance:false,missing:['Actual phase/initialize/admission/conditioning connections remain pending; mode, compare, request and lane enable are physically delivered.','Measured mask-before-pulse/farthest closure and complete cold/reset protocol remain unproved.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeAluCore({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
