import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{resolve}from'node:path';import{makeAluDataOpenFanout}from'../../../hardware/full-gpu-alu-data-open-fanout.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url)),prefix='artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v5/',parent='artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v4/source-manifest.json',read=p=>readFileSync(resolve(root,p)),json=p=>JSON.parse(read(p)),sha=p=>createHash('sha256').update(read(p)).digest('hex'),enc=v=>JSON.stringify(v,null,2)+'\n';
export function prepare({check=false}={}){
 assert.equal(sha(parent),'a27b3c292953f0678d6b227dadd3601c6efa196ab3f4ce3b09e35e31c8702f53');const files=new Set([parent]);for(const[p,h]of Object.entries(json(parent).source_sha256)){assert.equal(sha(p),h,'Frozen source '+p);files.add(p);}
 const selected=makeAluDataOpenFanout();assert.deepEqual(selected,json(prefix+'design.json'),'Exact regeneration');assert.equal(selected.blocks.length,460817);assert.equal(selected.masks.length,24);
 const old=json('artifacts/full-gpu-layout-v1/alu-four-lane-fanout-v4/interface.json'),commands=Object.keys(json('artifacts/full-gpu-layout-v1/alu-four-lane-v1/command-launch-draft.json').ports),delivered=new Set([...old.delivered_commands,...selected.connections.map(c=>c.name)]);assert.equal(commands.length,41);assert.deepEqual(new Set(commands),delivered);for(const name of old.missing_commands)assert.deepEqual(selected.connections.filter(c=>c.name===name).map(c=>c.lane),[0,1,2,3]);
 const parts={};for(const v of selected.blocks)parts[v.part]=(parts[v.part]??0)+1;const costs={parent_blocks:selected.metrics.parent_blocks,total_blocks:selected.blocks.length,added_blocks:selected.metrics.added_blocks,descents:selected.descents.map(v=>({name:v.name,lane:v.lane,blocks:v.blocks,drop:v.drop})),all_parts:parts,native:false};assert.deepEqual(costs,json(prefix+'costs.json'));
 const iface={...old,status:'all41_command_deliveries_drawn_external_core_interfaces_incomplete',delivered_commands:commands,missing_commands:[],lane_OPEN_inhibit_outputs:selected.ports.lane_data_open_inhibit,data_OPEN_masks_complete:true,physical_mask_producers_complete:true,mask_delivery_complete:true,mask_equation:'pulse && (RESET_macro || (lane_enable && !actual_lane_fault))',physical_data_OPEN_masks:selected.masks,all_bank_receivers:164,qualified_timing_verified:false,full_physical_acceptance:false};
 const ip=prefix+'interface.json';if(check)assert.equal(read(ip).toString(),enc(iface));else writeFileSync(resolve(root,ip),enc(iface));
 files.add('hardware/full-gpu-alu-data-open-fanout.mjs');for(const n of['README.md','prepare.mjs','interface.json','check-all.mjs','checks.json','check-geometry.py','check-open-logic.mjs','design.json','costs.json'])files.add(prefix+n);
 const manifest={status:'offline_all41_command_fanouts_and24_masks_drawn_external_integration_incomplete',source_sha256:Object.fromEntries([...files].sort().map(p=>[p,sha(p)])),current_candidate:prefix+'design.json',parent_manifest_sha256:sha(parent),metrics:selected.metrics,box:selected.box,commands_required:41,commands_physically_delivered:41,commands_missing:0,physical_destinations:164,physical_lane_OPEN_inhibits:4,physical_data_OPEN_masks:24,retained_lane_bits:228,retained_controller_bits:26,core_interfaces_complete:false,independent_full_geometry_review:false,native_calls:0,native_acceptance:false,missing:selected.missing};
 const mp=prefix+'source-manifest.json';if(check)assert.equal(read(mp).toString(),enc(manifest));else writeFileSync(resolve(root,mp),enc(manifest));return{manifest_sha256:sha(mp),design_sha256:sha(prefix+'design.json'),source_pins:files.size,blocks:selected.blocks.length,delivered_commands:41,physical_masks:24,native_calls:0};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(prepare({check:process.argv.includes('--check')})));
