import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),hash=u=>createHash('sha256').update(readFileSync(u)).digest('hex'),read=u=>JSON.parse(readFileSync(u)),pins={};
function pin(u,expected){const h=hash(u),key=fileURLToPath(u).slice(fileURLToPath(ROOT).length);if(expected)assert.equal(h,expected,key);if(pins[key])assert.equal(pins[key],h,key);pins[key]=h;}
for(const[n,expected]of [
 ['../../core-advance-constants-v1/source-manifest.json','0bc833ba51e26d17356b0c7040f4a244c77b838d9e347d17606214a0aa727e21'],
 ['../../core-historical-endpoints-review-v1/source-manifest.json','a262687149db6cf169e9970c7cc882fb2aa50fd9d2839757096432ff8da4a815'],
 ['../../core-block-id-bindings-v1/source-manifest.json','20377ec1f26ed174d3fdedf834fdef61996e934d05797779c9424e13fd964c60']
]){const u=new URL(n,H);pin(u,expected);for(const[p,h]of Object.entries(read(u).source_sha256)){if(pins[p])assert.equal(pins[p],h,p);pins[p]=h;}}
for(const name of readdirSync(H).filter(n=>/\.(mjs|json|md)$/.test(n)&&n!=='source-manifest.json'))pin(new URL(name,H));
for(const[p,h]of Object.entries(pins))assert.equal(hash(new URL(p,ROOT)),h,p);
const c=read(new URL('checks.json',H)),a=read(new URL('arrival-obligations.json',H)),p=read(new URL('phase-identity.json',H)),f=read(new URL('function-checks.json',H)),t=read(new URL('timing-and-composition.json',H)),e=read(new URL('endpoint-map.json',H)),x=read(new URL('exact-cut-bindings.json',H)),b=read(new URL('body-placement.json',H)),v=read(new URL('preflight.json',H));
assert.equal(c.status,'partial_owner_control_geometry_and_store_identity_passed');assert.equal(c.metrics.cells,843220);assert.equal(c.metrics.parent_cells,840790);assert.equal(c.metrics.logic_body_additions,48);assert.equal(c.metrics.new_transport_cells,2382);assert.equal(c.metrics.original_store_identities_preserved,1117);assert.equal(c.negative_checks,9);assert.equal(c.exact_cut_binding_checks,9);assert.equal(c.receivers,421037);assert.equal(c.actual_dependencies,697028);for(const k of ['unexpected','lost','unsupported'])assert.equal(c[k].length,0);assert.equal(Math.min(...c.routes.map(r=>r.minimum_asserted_rear_high)),4);
assert.equal(a.routes.length,9);assert.equal(p.status,'actual_intent_and_owner_kind_OPEN_lock_identities_passed');assert.equal(p.phase_lock_targets,4);assert.equal(p.reports.filter(r=>r.reverse_arrival_mutation==='refused_body_reach').length,3);assert.equal(f.status,'actual_owner_kind_ACK_low_intent_and_A_paths_match_original_functions');assert.equal(f.cases.length,32);assert.equal(f.negative_mutations.length,3);assert.equal(f.actual_nodes,2275);assert.equal(t.status,'fourteen_historical_commit_entries_have_geometry_full_timing_still_open');assert.equal(t.historical_entries.length,14);assert.deepEqual(t.nominal_composed_paths.map(r=>r.nominal_source_to_receiver_ticks),[114,72,144]);assert.equal(e.cuts.length,982);assert.equal(Object.keys(e.mapping).length,636927);assert.equal(Object.keys(e.replacement_interface_map).length,5);assert.equal(x.broader_mapped_body_directed_cut_count,1907);assert.equal(b.original_constant_mappings_preserved,35);assert.equal(v.connections.length,9);
const out={status:'frozen_partial_core_owner_kind_release_intent_geometry',source_sha256:Object.fromEntries(Object.entries(pins).sort()),metrics:c.metrics,box:c.box,checked_receivers:c.receivers,checked_effective_inputs:c.actual_dependencies,drawn_owner_control_transports:9,new_logic_body_cells:48,retained_original_stores:1117,inherited_constant_rails:7,scoped_transport_totals:c.scoped_transport_totals,retained_directed_incident_cuts:982,broader_mapped_body_cut_count:1907,original_OPEN_lock_targets:4,actual_function_nodes:f.actual_nodes,settled_function_cases:32,negative_route_arrivals:9,negative_OPEN_body_reach_mutations:3,negative_actual_gate_mutations:3,bounded_historical_entries_with_geometry:14,conditional_nominal_composed_ticks:Object.fromEntries(t.nominal_composed_paths.map(r=>[r.input_route,r.nominal_source_to_receiver_ticks])),full_timing_acceptance:false,complete_core:false,native_acceptance:false,limits:t.limitations};
writeFileSync(new URL('source-manifest.json',H),JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify({manifest_sha256:hash(new URL('source-manifest.json',H)),design_sha256:hash(new URL('design.json',H)),checks_sha256:hash(new URL('checks.json',H)),function_checks_sha256:hash(new URL('function-checks.json',H)),pins:Object.keys(pins).length,metrics:c.metrics}));
