// Physical assignment fanout over the frozen single-copy core/RF composition.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';
import{makeControlMatrix}from'./matrix.mjs';import{makeStateBank}from'../../../hardware/full-gpu-state-bank.mjs';import{materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),W='minecraft:redstone_wire';
export function makeStartupOther({plan=false}={}){
 const bytes=readFileSync(new URL('../control-assignment-v1/source-manifest.json',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),'fd43a256460e0f7627a012d77ac4905cfd7c93b881e356ff450950afa7e952a7');
 const base=read('../control-assignment-v1/design.json'),map=new Map(base.blocks.map(v=>[K(v.position),{...v,part:'composed_parent'}])),edges=[],routes=[],connections=[],receivers=[];let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to});
 const put=(p,id,properties)=>{const block={id:'minecraft:'+id,...properties?{properties}:{}},old=at(p);if(old){assert.equal(id,'light_gray_concrete','collision '+part+' '+K(p)+' '+old.part);assert.deepEqual(old.block,block,part+' support collision '+K(p));return;}map.set(K(p),{position:p,block,part});},solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'});
 const cacheUrl=new URL('routes.json',import.meta.url),cache=existsSync(cacheUrl)?read('routes.json'):{},pending=[],reserved=[],step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),reserve=(s,sd,d,ad)=>[...Array.from({length:18},(_,i)=>step(s,sd,i+2)),...Array.from({length:18},(_,i)=>step(d,ad,-i-2))];
 function draw(name,source,sd,destination,ad,stubs=false){part=name;assert.equal(at(source)?.block.id,W,'source '+name);assert.equal(at(destination)?.block.id,W,'destination '+name);const first=step(source,sd),start=step(source,sd,2),last=step(destination,ad,-1),end=step(destination,ad,-2);if(stubs){rep(first,sd);wire(start);rep(last,ad);wire(end);edge(source,first);edge(first,start);edge(end,last);edge(last,destination);return;}
  let path=cache[name]?.path;if(!path){assert(plan,'Missing route '+name);const ignore=[...reserve(source,sd,destination,ad),first,start,last,end,...[first,start,last,end].map(p=>P(p.x,p.y-1,p.z))],forbidden=[first,last].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![source,start,end,destination].some(q=>K(p)===K(q))),r=searchPath(map,start,end,{ignore,reserved,forbidden});path=r.path;cache[name]={source,destination,path,expanded:r.expanded};writeFileSync(cacheUrl,JSON.stringify(cache)+'\n');console.error(name+': '+path.length+' / '+r.expanded);}
  assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i)){const dir=Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source,tap:first,destination,arrival:last});
 }
 function insert(name,d,t){const r=materializeInstance(d,{id:name,translation:t});for(const b of r.blocks){assert(!at(b.position),'component collision '+name+' '+K(b.position));map.set(K(b.position),{...b,part:name});}return r;}
 const gate=insert('other_gate',makeControlMatrix(),P(-280,60,-120)),bank=insert('other_claim',makeStateBank({width:1,pair:false}),P(-260,80,-90));
 const gp=n=>gate.ports[n].bits[0].position,bp=n=>bank.ports[n].bits[0].position;
 pending.push(['idle_to_claim',P(14,1,6),'north',gp('idle'),'south']);
 pending.push(['permit_to_claim',P(-142,1,0),'west',gp('permit'),'south']);
 pending.push(['reset_to_claim',P(-138,1,-2),'north',gp('reset'),'south']);
 pending.push(['initialize_to_claim',P(-100,-4,-10),'west',gp('initialize'),'south']);
 pending.push(['claim_data',gp('claim'),'south',bp('next_data'),'east']);
 pending.push(['claim_open',P(-82,-4,14),'west',bp('state_open'),'east']);
 pending.push(['held_other_to_owner',bp('state'),'east',P(304,177,-745),'south']);
 pending.push(['other_complete_to_idle',P(356,296,-735),'west',P(22,1,-4),'south']);
 for(const[,s,sd,d,ad]of pending)reserved.push(...reserve(s,sd,d,ad));for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=blocks.reduce((n,v)=>Math.min(n,v.position[a]),Infinity);box.to[a]=blocks.reduce((n,v)=>Math.max(n,v.position[a]),-Infinity);}
 return{status:'retained_startup_other_connection_draft',blocks,parents:{composed_parent:{blocks:base.blocks.length,translation:P(0,0,0)},other_gate:{blocks:gate.blocks.length,translation:P(-280,60,-120)},other_claim:{blocks:bank.blocks.length,translation:P(-260,80,-90)}},ports:{...base.ports,start_request:gate.ports.start,other_claim:bank.ports.state},edges,routes,connections,box,metrics:{blocks:blocks.length,parent_blocks:base.blocks.length,added_blocks:blocks.length-base.blocks.length,connections:connections.length,retained_bits:876},native_acceptance:false,complete_controller:false,missing:['Retained START/reset-ack/busy/done admission and complete reset/drain producer remain missing; start_request only legal after full reset release and assignment settlement.','LSU ownership/reset join remains missing.','Raw shared phase captures a blanked OTHER claim. Initialization must clear this cell before owner or architectural admission.','Remote source/state/lock closure and common initialization timing remain unmeasured.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeStartupOther({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
