// Exact ledger preservation; global QUIET does not close loader BUSY egress.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`;
function read(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return JSON.parse(b);}
read('../bank-global-delivery-v1/source-manifest.json','a51f6460b976309bdc63834af00d4212705c6ea1ef53b844eee6690fcb40c91b');
const before=read('../program-global-delivery-v1/remaining-cuts.json'),after=read('../bank-global-delivery-v1/remaining-cuts.json'),service=read('../loader-program-colocation-v1/service-active-witness-delivery-v1/remaining-cuts.json'),memory=read('../memory/fabric-colocation-v2/channel2-address-cut-ledger.json'),delta=read('../bank-global-delivery-v1/delta.json'),endpoint=read('../bank-global-delivery-v1/endpoint-map.json'),selected=new Map([292,293,295,296].map((v,i)=>[v,delta.connections[i]])),cutSelected=new Map(),changes=[];
for(const [index,c]of selected){const t=before.dispatch.transfers[index],matches=before.dispatch.effective_cut_ledger.map((v,i)=>[v,i]).filter(([v])=>K(v.source)===K(t.source)&&K(v.target)===K(t.target));assert.equal(matches.length,1);cutSelected.set(matches[0][1],c);}
for(const [field,n,picks]of[['transfers',352,selected],['effective_cut_ledger',661,cutSelected],['direct_foreign_boundaries',48,new Map()]]){assert.equal(before.dispatch[field].length,n);assert.equal(after.dispatch[field].length,n);for(let i=0;i<n;i++){const a=before.dispatch[field][i],b=after.dispatch[field][i],c=picks.get(i);if(!c)assert.deepEqual(b,a,field+'/'+i);else{for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v,field+'/'+i+'/'+k);assert.notEqual(b.status,a.status);assert.deepEqual(b.shared_actual_producer,c.root);assert.deepEqual(b.shared_target,c.destination);assert.equal(b.shared_route,c.name);if(field==='transfers')assert.deepEqual(b.shared_arrival_normalizer,c.normalizer);else assert.deepEqual(b.shared_source,c.normalizer);changes.push({ledger:field,index:i,old_status:a.status,new_status:b.status});}}}
assert.deepEqual(after.service,service);assert.equal(after.service.counts.witness_input_bound_total,20);assert.equal(after.service.counts.witness_input_pending,17);assert.deepEqual(after.program,before.program);assert.equal(after.program.length,44);assert.equal(after.program.filter(r=>r.status==='pending_external_master_connection').length,42);
const untouched=memory.bank_inventory.entries.filter(r=>[536,537,538,539].includes(r.index));assert.equal(untouched.length,4);assert(untouched.every(r=>r.status==='outside_this_group_reconciliation_pending'));assert.deepEqual(after.bank_quiet.separate_loader_busy_egress_unchanged,untouched);assert.equal(after.bank_quiet.bank_inventory_changed,false);assert.equal(after.bank_quiet.bank_entries,572);assert.equal(after.bank_quiet.fabric_entries,944);assert.equal(memory.bank_inventory.entries.length,572);
for(let i=0;i<4;i++){const b=after.bank_quiet.bindings[i],c=delta.connections[i];assert.equal(b.bank,i);assert.equal(b.transfer_index,[292,293,295,296][i]);assert.deepEqual(b.destination,c.destination);assert.equal(b.route,c.name);assert.deepEqual(b.source.quiet,c.root);}
assert.deepEqual(endpoint.connections,delta.connections);const counts={};for(const r of after.dispatch.transfers)counts[r.status]=(counts[r.status]??0)+1;assert.deepEqual(after.dispatch.transfer_counts,counts);assert.equal(counts.external_source_transfer_pending,12);assert.equal(after.dispatch.direct_foreign_boundaries.filter(r=>r.status==='pending').length,31);
const self=new URL('ledger-review.mjs',H);pins[fileURLToPath(self).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(self)).digest('hex');
const report={status:'passed_exact_bank_global_ledger_delta',metrics:{transfers:352,effective_cuts:661,direct_foreign_cuts:48,program_cuts:44,bank_inventory_entries:572,fabric_inventory_entries:944,changed_global_records:8,global_incoming_pending:12,direct_foreign_pending:31,program_pending:42,loader_BUSY_egress_unchanged:4,service_witness_bound:20,service_witness_pending:17},changes,source_sha256:pins,limits:['Only four global bank QUIET transfers and their four matching effective cuts change. Program and all direct foreign records are exactly unchanged.','Service ledger intentionally advances to the already frozen ACTIVE parent20/37; it does not claim later commit-phase24/37 credit.','Loader bank-BUSY egress536..539 remains pending and exactly retained; no inversion cable substitutes for those separate deliveries.']};writeFileSync(new URL('ledger-receipt.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
