// Independent bounded review: direct source loading, actual cold context,
// complete input differential, and a separate directed-network strength solver.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function insert(map,rows,{same=false}={}){for(const r of rows){const k=K(r.position);if(map.has(k)){assert(same,'Duplicate cell '+k);assert.deepEqual(map.get(k),r.block);}else map.set(k,r.block);}}
function scanBlocks(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const part=buffer.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){visit(r);count++;}};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated blocks');}
function cone(world,end,root){const roots=Array.isArray(root)?root:[root],stop=new Set(roots.map(K)),seen=new Map(),queue=Array.isArray(end)?[...end]:[end];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(world.get(k)),'Missing actual dependency '+k);seen.set(k,p);if(!stop.has(k))queue.push(...inputs(world,p));}for(const r of roots)assert(seen.has(K(r)),'Source absent from cone '+K(r));return [...seen.values()];}
function network(world,positions,root){
 const roots=Array.isArray(root)?root:[root],index=new Map(positions.map((p,i)=>[K(p),i])),rootIndices=new Set(roots.map(p=>index.get(K(p))));assert(!rootIndices.has(undefined));
 const rows=positions.map(p=>({p,b:world.get(K(p))})),incoming=positions.map(()=>[]),outgoing=positions.map(()=>[]);let edges=0;
 for(let i=0;i<rows.length;i++){assert([W,R,C,T,WT,'minecraft:redstone_block'].includes(rows[i].b.id),'Unexpected transport device '+rows[i].b.id+' '+K(rows[i].p));if(rootIndices.has(i))continue;const deps=inputs(world,rows[i].p);if(rows[i].b.id===R){const v=D[rows[i].b.properties.facing];assert(deps.every(q=>(q.x-rows[i].p.x)*v.x+(q.z-rows[i].p.z)*v.z<0),'Unmodeled side lock');}for(const q of deps){const j=index.get(K(q));assert.notEqual(j,undefined,'Foreign source '+K(q));incoming[i].push(j);outgoing[j].push(i);edges++;}}
 const visited=new Uint8Array(rows.length),order=[];for(let i=0;i<rows.length;i++)if(!visited[i]){visited[i]=1;const stack=[[i,0]];while(stack.length){const r=stack.at(-1);if(r[1]<outgoing[r[0]].length){const j=outgoing[r[0]][r[1]++];if(!visited[j]){visited[j]=1;stack.push([j,0]);}}else{order.push(r[0]);stack.pop();}}}
 const assigned=new Uint8Array(rows.length);let components=0,wireLoops=0;for(let n=order.length-1;n>=0;n--){const i=order[n];if(assigned[i])continue;const members=[i];assigned[i]=1;for(let at=0;at<members.length;at++)for(const j of incoming[members[at]])if(!assigned[j]){assigned[j]=1;members.push(j);}components++;if(members.length>1||outgoing[i].includes(i)){assert(members.every(j=>rows[j].b.id===W),'Nonwire transport feedback');wireLoops++;}}
 function power(strength){const values=new Uint8Array(rows.length),waiting=new Uint8Array(rows.length).fill(1),queue=rows.map((_,i)=>i);for(const p of roots)values[index.get(K(p))]=typeof strength==='number'?strength:strength.get(K(p))??0;let events=0;for(let at=0;at<queue.length;at++){const i=queue[at];waiting[i]=0;if(rootIndices.has(i))continue;assert(++events<1000000,'Nonconvergent network');let value=0;for(const j of incoming[i])value=Math.max(value,values[j]-(rows[i].b.id===W&&rows[j].b.id===W?1:0));if(rows[i].b.id===R)value=value>0?15:0;else if([T,WT].includes(rows[i].b.id))value=value>0?0:15;else if(rows[i].b.id==='minecraft:redstone_block')value=15;else if(rows[i].b.id===C){const d=D[rows[i].b.properties.facing],rear=incoming[i].filter(j=>(rows[j].p.x-rows[i].p.x)*d.x+(rows[j].p.z-rows[i].p.z)*d.z<0),side=incoming[i].filter(j=>!rear.includes(j)),a=Math.max(0,...rear.map(j=>values[j])),b=Math.max(0,...side.map(j=>values[j]));value=rows[i].b.properties.mode==='subtract'?Math.max(0,a-b):a>=b?a:0;}if(value!==values[i]){values[i]=value;for(const j of outgoing[i])if(!waiting[j]){waiting[j]=1;queue.push(j);}}}return {values,get:p=>values[index.get(K(p))]??0,events};}
 return {power,metrics:{devices:rows.length,edges,components,torch_vertices:rows.filter(r=>[T,WT].includes(r.b.id)).length,wire_conductance_components:wireLoops,nonwire_feedback_components:0},minimumRear(powers,subset){return Math.min(...rows.flatMap((r,i)=>r.b.id===R&&(!subset||subset.has(K(r.p)))?[Math.max(0,...incoming[i].map(j=>powers.values[j]))]:[]));}};
}
read('../bank-global-delivery-v1/source-manifest.json','a51f6460b976309bdc63834af00d4212705c6ea1ef53b844eee6690fcb40c91b');
const memory=read('../memory/fabric-colocation-v2/channel3-write-data-design.json'),panels=read('../loader-bank-panels-v1/delta.json'),program=read('../program-service-composition-v1/new-program-obstacles.json'),programQuiet=read('../program-service-composition-v1/cable-delta.json'),masks=read('../loader-program-colocation-v1/service-mask-memory-composition-v1/composed-delta.json'),address0=read('../memory/fabric-colocation-v2/channel0-address-delta.json'),address1=read('../memory/fabric-colocation-v2/channel1-address-delta.json'),owner=read('../loader-program-colocation-v1/service-owner-open-delivery-v1/delta.json'),payload=read('../loader-program-colocation-v1/service-payload-open-delivery-v1/delta.json'),dispatch=read('../dispatcher-service-colocation-v1/placement.json'),serviceQuiet=read('../dispatcher-service-colocation-v1/delta.json');
const base=new Map();insert(base,[...memory.blocks,...panels.blocks,...program.blocks,...programQuiet.blocks,...masks.placed_loader,...masks.placed_masks,...masks.new_cells,...address0.blocks,...address1.blocks,...owner.new_cells,...payload.new_cells,...dispatch.blocks,...serviceQuiet.new_cells]);for(const r of masks.replacements){assert.deepEqual(base.get(K(r.position)),r.before);base.set(K(r.position),r.after);}assert.equal(base.size,2000594);
const programGlobal=read('../program-global-delivery-v1/delta.json'),activeWitness=read('../loader-program-colocation-v1/service-active-witness-delivery-v1/delta.json'),address2=read('../memory/fabric-colocation-v2/channel2-address-delta.json');insert(base,[...programGlobal.new_cells,...activeWitness.new_cells,...address2.blocks]);assert.equal(base.size,2054908);
const delta=read('../bank-global-delivery-v1/delta.json','5cf36a5ec7f3ed5aebaac22b3d937593760a603911fe7223890d3c38e2df7ca9'),world=new Map(base);insert(world,delta.new_cells);assert.equal(world.size,2072756);assert.equal(delta.connections.length,4);assert.equal(delta.routes.length,4);
const originalAdapters=read('../master-bank-quiet-adapters-v1/design.json'),oldRoutes=read('../master-bank-quiet-routes-v1/design.json'),scope=read('../dispatch-global-colocation-v1/reference-scope.json'),bindings=read('../dispatch-external-bindings-v1/bindings.json'),parent=read('../dispatch-global-colocation-v8-dcr-cold-v1/connected-candidate.json'),tail=read('../memory/fabric-colocation-v2/bank-tail-repaired-bodies.json'),classification=read('../memory/fabric-colocation-v2/bank-tail-classification.json'),translation=P(0,-8,40),tailMap=new Map(tail.blocks.map(r=>[K(r.position),r]));
assert.deepEqual(tail.translation,translation);const discovery=new Map();insert(discovery,[...scope.blocks,...scope.foreign_context,...oldRoutes.blocks,...originalAdapters.blocks],{same:true});
const adapterKeys=new Set(),adapterByKey=new Map();for(const row of originalAdapters.blocks){const p=A(row.position,translation),k=K(p);adapterKeys.add(k);adapterByKey.set(k,row);assert.deepEqual(world.get(k),row.block);assert(!base.has(k));}assert.equal(adapterKeys.size,32);assert.equal(delta.new_cells.filter(r=>r.part==='original_bank_quiet_adapter').length,32);
const oldProofs=[],identities=[],want=new Set(),oldTargets=[],oldRoots=[];
for(let bank=0;bank<4;bank++){const adapter=originalAdapters.adapters[bank],c=delta.connections[bank],binding=bindings.incoming.find(r=>r.transfer_index===[292,293,295,296][bank]),record=classification.rows[bank];assert.equal(record.bank,bank);assert.deepEqual(record.outputs[0],A(adapter.source,translation));assert.deepEqual(c.root,A(adapter.destination,translation));assert.deepEqual(binding.old_connection.source,adapter.destination);assert.deepEqual(record.sources.slice(0,3).map(r=>r.name),['active','tail','reset']);
 for(const r of [...record.sources.slice(0,3),{name:'bank_any_busy',position:record.outputs[0],original:adapter.source}]){const body=tailMap.get(K(r.position));assert(body);assert.deepEqual(body.original_position,r.original);assert.deepEqual(body.block,base.get(K(r.position)));assert.deepEqual(A(r.original,translation),r.position);identities.push({bank,role:r.name,original:r.original,current:r.position,block:body.block});want.add(K(r.original));if(r.name==='bank_any_busy')insert(discovery,[{position:r.original,block:body.block}],{same:true});}
 const target=binding.old_connection.destination,root=adapter.source,positions=cone(discovery,target,root);oldTargets.push(target);oldRoots.push(root);oldProofs.push({bank,positions});for(const p of positions)for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)want.add(K(A(p,P(x,y,z))));
 const receiver=parent.blocks.find(r=>r.original_position&&K(r.original_position)===K(target));assert(receiver);assert.deepEqual(A(receiver.position,dispatch.translation),c.destination);assert.deepEqual(world.get(K(c.destination)),receiver.block);
}
const actualOld=new Map(),scanned=scanBlocks(bytes('../memory/master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f'),r=>{if(want.has(K(r.position)))insert(actualOld,[r]);});
const selected=read('../dispatch-global-colocation-v1/selected-config.json'),globalInstance=selected.instances.find(r=>r.name==='global'),globalBody=read('../global-command-assembly-v3/design.json',globalInstance.sha256);insert(actualOld,[...oldRoutes.blocks,...originalAdapters.blocks,...globalBody.blocks.map(r=>({position:A(r.position,globalInstance.translation),block:r.block}))].filter(r=>want.has(K(r.position))),{same:true});
for(const r of identities)assert.deepEqual(actualOld.get(K(r.original)),r.block,'Actual old state/source identity '+r.role);const oldCases=[];
for(const p of oldProofs){const actual=cone(actualOld,oldTargets[p.bank],oldRoots[p.bank]);assert.deepEqual(actual.map(K).sort(),p.positions.map(K).sort());for(const q of actual){assert.deepEqual(actualOld.get(K(q)),discovery.get(K(q)));if(K(q)!==K(oldRoots[p.bank]))assert.deepEqual(inputs(actualOld,q).map(K).sort(),inputs(discovery,q).map(K).sort());}const n=network(actualOld,actual,oldRoots[p.bank]),cases=[];for(const busy of[0,15]){const v=n.power(busy),quiet=busy?0:15;assert.equal(v.get(oldTargets[p.bank]),quiet);cases.push({busy,quiet:v.get(originalAdapters.adapters[p.bank].destination),receiver:v.get(oldTargets[p.bank])});}oldCases.push({bank:p.bank,graph:n.metrics,cases});}
const edges=new Set(),extras=new Map(),newKeys=new Set(delta.new_cells.filter(r=>active(r.block)).map(r=>K(r.position)));
for(let bank=0;bank<4;bank++){const c=delta.connections[bank],r=delta.routes[bank];assert.deepEqual(r.path[0],c.root);assert.deepEqual(r.path.at(-1),c.destination);extras.set(K(c.destination),K(c.normalizer));for(let i=1;i<r.path.length;i++){assert(inputs(world,r.path[i]).some(p=>K(p)===K(r.path[i-1])));edges.add(K(r.path[i-1])+'>'+K(r.path[i]));edges.add(K(r.path[i])+'>'+K(r.path[i-1]));}}
let receivers=0,supports=0,actualInputs=0,priorInputs=0,newInputs=0,changedOldReceivers=0;
for(const [key,block]of world){const [x,y,z]=key.split(',').map(Number),p=P(x,y,z);let support;if(block.id===WT)support=A(p,D[block.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(block.id))support=P(x,y-1,z);if(support){assert(solid(world.get(K(support))),'Missing support '+key);supports++;}if(!active(block))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;if(base.has(key)){const expected=inputs(base,p).map(K);priorInputs+=expected.length;if(extras.has(key)){expected.push(extras.get(key));changedOldReceivers++;}assert.deepEqual(actual,[...new Set(expected)].sort(),'Retained input changed '+key);}else{assert(newKeys.has(key));if(adapterKeys.has(key)){const row=adapterByKey.get(key),expected=inputs(actualOld,row.position).map(p=>K(A(p,translation))).sort();assert.deepEqual(actual,expected,'Original adapter input mismatch '+key);}else for(const q of actual)assert(edges.has(q+'>'+key),'Undeclared cable contact '+q+'>'+key);newInputs+=actual.length;}}
assert.equal(changedOldReceivers,4);
const gateProofs=[],negatives=[],rears=new Map(),allRoots=[],allPositions=new Map(),opposite={east:'west',west:'east',north:'south',south:'north'};
for(let bank=0;bank<4;bank++){const c=delta.connections[bank],roots=classification.rows[bank].sources.slice(0,3).map(r=>r.position),busy=A(originalAdapters.adapters[bank].source,translation),targets=[busy,c.root,c.destination],positions=cone(world,targets,roots),n=network(world,positions,roots),cases=[];allRoots.push(...roots);for(const p of positions)allPositions.set(K(p),p);
 for(let bits=0;bits<8;bits++){const v=n.power(new Map(roots.map((p,i)=>[K(p),(bits>>i&1)*15]))),outputs=targets.map(p=>v.get(p));assert.deepEqual(outputs,[bits?15:0,bits?0:15,bits?0:15]);cases.push({source_bits:bits,outputs});for(const p of positions)if(newKeys.has(K(p))&&world.get(K(p)).id===R&&v.get(p)>0){const rear=Math.max(0,...inputs(world,p).map(q=>v.get(q)));rears.set(K(p),Math.min(rears.get(K(p))??15,rear));}}
 const cablePositions=cone(world,c.destination,c.root),cable=network(world,cablePositions,c.root),strengths=[];for(let strength=0;strength<16;strength++){const v=cable.power(strength);assert.equal(v.get(c.destination),strength?15:0);strengths.push({strength,output:v.get(c.destination)});}
 for(const p of positions){const k=K(p),saved=world.get(k);if(!newKeys.has(k)||saved.id!==R)continue;world.set(k,{...saved,properties:{...saved.properties,facing:opposite[saved.properties.facing]}});let rejected=false;try{const wrong=network(world,cone(world,c.destination,roots),roots);for(const bits of[0,1,2,4,7]){const v=wrong.power(new Map(roots.map((p,i)=>[K(p),(bits>>i&1)*15])));if(v.get(c.destination)!==(bits?0:15)){rejected=true;break;}}}catch{rejected=true;}assert(rejected,'Reverse diode survived '+k);world.set(k,saved);negatives.push({bank,kind:'reverse_actual_repeater',position:p});}
 const torch=A(originalAdapters.adapters[bank].torch,translation),saved=world.get(K(torch));world.set(K(torch),{id:W});let rejected=false;try{const wrong=network(world,cone(world,c.destination,roots),roots);for(const bits of[0,1]){const v=wrong.power(new Map(roots.map((p,i)=>[K(p),(bits>>i&1)*15])));if(v.get(c.destination)!==(bits?0:15))rejected=true;}}catch{rejected=true;}assert(rejected);world.set(K(torch),saved);negatives.push({bank,kind:'replace_inverter_with_wire',position:torch});
 const support=P(c.normalizer.x,c.normalizer.y-1,c.normalizer.z),savedSupport=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),savedSupport);negatives.push({bank,kind:'delete_actual_arrival_support',position:support});
 gateProofs.push({bank,roots,busy,quiet:c.root,receiver:c.destination,graph:n.metrics,cases,cable_graph:cable.metrics,strengths});
}
const jointNet=network(world,[...allPositions.values()],allRoots),joint=[];for(let mask=0;mask<16;mask++){const values=new Map(allRoots.map((p,i)=>[K(p),i%3===0&&(mask>>(i/3|0)&1)?15:0])),v=jointNet.power(values),outputs=delta.connections.map(c=>v.get(c.destination));assert.deepEqual(outputs,Array.from({length:4},(_,i)=>mask>>i&1?0:15));joint.push({active_bank_mask:mask,outputs});}
assert.equal(rears.size,delta.new_cells.filter(r=>r.block.id===R).length);const minimum=Math.min(...rears.values());assert.equal(minimum,5);assert.equal(negatives.length,777);
bytes('review.mjs');bytes('../memory/fabric-colocation-v2/cut-inputs.mjs');write('receipt.json',{status:'passed_independent_actual_bank_global_quiet_deliveries',metrics:{base_cells:base.size,new_cells:delta.new_cells.length,original_adapter_cells:32,total_cells:world.size,receivers,supports,actual_inputs:actualInputs,preserved_inputs:priorInputs,new_inputs:newInputs,changed_existing_receivers:changedOldReceivers,path_vertices:delta.routes.reduce((n,r)=>n+r.path.length,0),old_busy_polarity_cases:8,gate_assignments:32,gate_output_observations:96,independent_bank_assignments:16,independent_bank_observations:64,source_strength_cases:64,minimum_new_repeater_rear:minimum,actual_block_mutations:negatives.length},original:{cold_cells_streamed:scanned,actual_context_cells:actualOld.size,retained_state_source_identities:identities,proofs:oldCases},current:{proofs:gateProofs,joint_graph:jointNet.metrics,joint_cases:joint},negative_cases:negatives,source_sha256:pins,limits:['Independent reconstruction, original cold source streaming, and numeric/SCC evaluator. The physical-input rule helper is shared and conditional; this is not independent Minecraft physics.','Actual bank ACTIVE/finaltail/resetblocked levels are explicit held boundaries. Their state-transition, release/freshness, setup/hold, pulse and native behavior are unproved.','Only accepted root2,072,756-cell scope is screened; commit-phase and subsequent channel3 geometry require separately named union receipts. No unrelated loader bank-BUSY cuts or complete-machine credit.']});console.log(JSON.stringify({status:'passed',cells:world.size,receivers,supports,actualInputs,minimum,mutations:negatives.length,jointGraph:jointNet.metrics}));
