// Freeze this source/design checkpoint only; no geometry or ledger credit.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,readdirSync,existsSync}from'node:fs';import{fileURLToPath}from'node:url';import{join,relative}from'node:path';import{makeSourcePinHasher}from'../../../../../scripts/source-pin-hasher.mjs';
const H=fileURLToPath(new URL('./',import.meta.url)),ROOT=fileURLToPath(new URL('../../../../../',import.meta.url)),target=join(H,'source-recovery-manifest.json'),hasher=makeSourcePinHasher(ROOT),read=p=>JSON.parse(readFileSync(p)),pins={};function merge(m){for(const[p,h]of Object.entries(m)){assert(!pins[p]||pins[p]===h,'Conflicting source '+p);pins[p]=h;}}function verify(m){for(const[p,h]of Object.entries(m))assert.equal(hasher.hash(p),h,p);hasher.assertStable();}
if(process.argv.includes('--check')){const m=read(target);assert.equal(m.new_cells,0);assert.equal(m.new_closed_cuts,0);verify(m.source_sha256);console.log(JSON.stringify({status:'source_recovery_checkpoint_integrity_passed',manifest_sha256:hasher.hash(target),pins:Object.keys(m.source_sha256).length,...hasher.stats()}));process.exit(0);}assert(!existsSync(target),'Checkpoint already frozen');
const ids=read(join(H,'source-identities.json')),functions=read(join(H,'source-functions.json')),capture=read(join(H,'backend-capture-functions.json')),visibility=read(join(H,'consumer-visibility-functions.json')),negative=read(join(H,'source-negative-checks.json')),proposal=read(join(H,'placement-proposal.json')),assignment=read(join(H,'assignment.json')),prior=read(join(H,'../bank-ready-collectors-v1/cut-ledger.json'));
assert.equal(hasher.hash(join(H,'assignment.json')),'3dde5a7a9064e58e93f91560a470d8b19010febbeae1f219577cbec04673dca2');assert.equal(ids.sourceRows.length,32);assert.equal(ids.backendRows.length,32);assert.equal(ids.pairRows.length,16);assert.equal(functions.cases,8192);assert.equal(functions.matched_transport.cells,240216);assert.equal(functions.junctionRepairs.length,2);assert.equal(capture.cases,512);assert.equal(visibility.cases,2064);assert.equal(negative.total,160);assert.equal(proposal.parent_cells,2192740);assert.equal(proposal.passing.length,3);assert.equal(proposal.preserved_qualified_source_repairs.length,12);assert.equal(proposal.new_cells,0);assert.equal(proposal.new_closed_cuts,0);
for(const s of assignment.sources){const e=prior.bank_inventory.entries[s.bank_cut_index];assert.equal(e.status,'outside_this_group_reconciliation_pending');assert.equal(e.cut_sha256,s.cut_sha256);assert.deepEqual(e.original,s.original);}for(const d of assignment.destinations){const e=prior.fabric_inventory.entries[d.fabric_cut_index];assert.equal(e.status,'outside_this_group_reconciliation_pending');assert.equal(e.cut_sha256,d.cut_sha256);assert.deepEqual(e.original,d.original);}
for(const[n,h]of[
 ['artifacts/full-gpu-layout-v1/loader-program-colocation-v1/service-live-busy-delivery-v1/source-manifest.json','35b6f3385a71bdb9e413c7bf62b335b242c048fd93d4e437c43a362ecd182adf'],
 ['artifacts/full-gpu-layout-v1/panel-loader-delivery-v1/source-manifest.json','413433b319feb629fe58d5758a704b99487f4aa72bce9ec41f2d64a9acd76aee'],
 ['artifacts/full-gpu-layout-v1/memory/bank-ready-review-v1/source-manifest.json','840db841949ba92de54a566e6aa4ee3e307b3b2db8acbd60138a02aaa192f7d8']]){assert.equal(hasher.hash(n),h);merge(read(join(ROOT,n)).source_sha256);merge({[n]:h});}
for(const d of[ids,functions,capture,visibility,negative,proposal])merge(d.source_sha256);
for(const n of readdirSync(H).sort()){const p=join(H,n);if(p!==target)merge({[relative(ROOT,p)]:hasher.hash(p)});}merge({'scripts/source-pin-hasher.mjs':hasher.hash('scripts/source-pin-hasher.mjs')});verify(pins);
const out={status:'frozen_source_only_bank_response_recovery_and_unallocated_compact_proposal',original_source_sha256:'364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f',current_proposal_obstacle_cells:2192740,original_matched_cells:240216,actual_bank_Q_and_lock_identities:32,actual_backend_Q_and_lock_identities:32,qualified_pairs:16,original_response_function_cases:8192,backend_capture_visibility_cases:512,original_consumer_visibility_cases:2064,actual_mask_mutations:128,lock_identity_refusals:32,preferred_unallocated_origin:proposal.passing[0].origin,preferred_unallocated_box:proposal.passing[0].box,exact_template_cells_if_selected:10272,unrouted_cost_ranking_model:proposal.passing[0].score,new_cells:0,new_closed_cuts:0,pending_bank_response_indices:assignment.sources.map(s=>s.bank_cut_index),pending_fabric_response_indices:assignment.destinations.map(d=>d.fabric_cut_index),source_sha256:Object.fromEntries(Object.entries(pins).sort(([a],[b])=>a.localeCompare(b))),limits:proposal.limits,geometry_accepted:false,native_acceptance:false};writeFileSync(target,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:'source_only_checkpoint_frozen',manifest_sha256:hasher.hash(target),source_functions_sha256:hasher.hash(join(H,'source-functions.json')),proposal_sha256:hasher.hash(join(H,'placement-proposal.json')),pins:Object.keys(pins).length,...hasher.stats()}));
