// Original source/function and fully matched transport recovery only. No new cells.
import assert from'node:assert/strict';
import{H,ROOT,pins,P,K,A,W,R,C,D,bytes,read,write,streamBlocks,field,findStore,locked,summary}from'./source-tools.mjs';
import{loadBase}from'./source-frame.mjs';
import{inputs,active}from'../cut-inputs.mjs';import{backwardCone}from'../settled-network.mjs';import{makeSettledEvaluator}from'../settled-bank-network.mjs';
const assignment=read('assignment.json','3dde5a7a9064e58e93f91560a470d8b19010febbeae1f219577cbec04673dca2'),cold=bytes('../../master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f'),labelsMeta=read('../cell-labels.json'),lb=bytes('../cell-labels.u16le'),labels=new Uint16Array(lb.buffer,lb.byteOffset,lb.byteLength/2),legacy=read('../../internal-bank-response-v1/ports.json'),legacyReady=read('../../bank-ready-return-v1/ports.json'),banks=read('../bank-tail-bodies.json'),matrix=read('../../internal-bank-response-v1/collector.json'),raw=read('../raw-local-ports.json'),{world:current,rows:currentRows}=loadBase();
const transportGroups=new Set(['current/qualified_bank_response_matrix','current/bank_held_response_cables','current/owned_bank_ready_masks','current/qualified_response_d_cables']),selected=[],transport=[];const count=streamBlocks(cold,(r,i)=>{const part=labelsMeta.labels[labels[i]];if(transportGroups.has(part)){selected.push({...r,part});transport.push({...r,part});}else if(/^four-bank-service-v1\/bank[0-3]$/.test(part)||/^channel-backend-v1\/backend[0-3]$/.test(part)||part==='bank-ready-return-v1/owned_bank_ready_returns'||part==='bank-ready-return-v1/ready_collectors'||/^current\/typed_ready_gate[0-3]$/.test(part))selected.push({...r,part});});assert.equal(count,3381962);assert.equal(count,labels.length);const old=new Map(selected.map(r=>[K(r.position),r.block])),sourceRows=[],backendRows=[],pairRows=[],collectors=[],devices=new Map();
function add(positions){for(const p of positions)devices.set(K(p),p);}
function numeric(map,positions,roots,levels){const constants=positions.filter(p=>map.get(K(p))?.id==='minecraft:redstone_block'),ev=makeSettledEvaluator(map,positions,[...roots,...constants],{eventLimit:4000000});return ev(new Map([...roots.map((p,i)=>[K(p),levels[i]]),...constants.map(p=>[K(p),15])])) ;}
for(const s of assignment.sources){const out=s.original.source.position,a=findStore(old,out),b=findStore(current,s.current_source),T=p=>P(p.x,p.y-8,p.z+40);assert.deepEqual(T(a.q),b.q);assert.deepEqual(T(a.lock),b.lock);assert.deepEqual(new Set(a.cone.map(p=>K(T(p)))),new Set(b.cone.map(K)));const patches=[];for(const p of a.cone){const n=T(p);if(JSON.stringify(old.get(K(p)))!==JSON.stringify(current.get(K(n))))patches.push({original:p,current:n,before:old.get(K(p)),after:current.get(K(n))});}assert.equal(patches.length,0,'Unexpected response-export patch');assert.deepEqual(old.get(K(a.q)),current.get(K(b.q)));assert.deepEqual(old.get(K(a.lock)),current.get(K(b.lock)));add(a.cone);sourceRows.push({...s,original_q:a.q,current_q:b.q,original_lock:a.lock,current_lock:b.lock,storage_block:old.get(K(a.q)),lock_block:old.get(K(a.lock)),original_cone:a.cone,current_cone:b.cone,patches});}
for(const t of assignment.destinations){const nowOut=raw.ports['channel'+t.channel+'.backend.response'].positions[t.bit],offset=P(t.original.target.position.x-t.current_destination.x,t.original.target.position.y-t.current_destination.y,t.original.target.position.z-t.current_destination.z),out=A(nowOut,offset),a=findStore(old,out),b=findStore(current,nowOut);assert.deepEqual(A(b.q,offset),a.q);assert.deepEqual(A(b.lock,offset),a.lock);assert.deepEqual(old.get(K(a.q)),current.get(K(b.q)));assert.deepEqual(old.get(K(a.lock)),current.get(K(b.lock)));assert(inputs(current,b.q).some(p=>K(p)===K(b.lock)));const driverInputs=inputs(current,b.q).filter(p=>K(p)!==K(b.lock));assert.equal(driverInputs.length,1);const dCone=backwardCone(current,driverInputs[0],[t.current_destination]);assert(dCone.some(p=>K(p)===K(t.current_destination)));add(a.cone);backendRows.push({...t,original_q:a.q,current_q:b.q,original_lock:a.lock,current_lock:b.lock,current_output:nowOut,original_output:out,current_D_cone:dCone,storage_block:current.get(K(b.q)),lock_block:current.get(K(b.lock)),limits:'D must settle while this real side-locked response store is open. Capture timing and upstream lock generation are not simulated.'});}
for(const p of assignment.qualifications){const binding=legacy.bindings.find(b=>b.kind==='actual_owned_bank_ready'&&b.bank===p.bank&&b.channel===p.channel),r=legacyReady.connections.find(b=>b.kind==='collector_input'&&b.bank===p.bank&&b.channel===p.channel),body=banks.banks[p.bank];assert.deepEqual(binding.source,r.destination);const roots=['read_ready','write_ready'].map(n=>body.ports[n].original_positions[p.channel]),cone=backwardCone(old,binding.source,roots);assert(roots.every(p=>cone.some(q=>K(q)===K(p))));add(cone);pairRows.push({...p,original_pair:binding.source,original_roots:roots,original_cone:cone,original_mask_input:binding.destination,original_mask_arrival:binding.arrival});}
for(const d of assignment.destinations){const sources=sourceRows.filter(s=>s.bit===d.bit),pairs=pairRows.filter(p=>p.channel===d.channel),roots=[...sources.map(s=>s.original.source.position),...pairs.map(p=>p.original_pair)],cone=backwardCone(old,d.original.target.position,roots);assert(roots.every(p=>cone.some(q=>K(q)===K(p))));add(cone);collectors.push({channel:d.channel,bit:d.bit,roots:roots.map((p,i)=>({position:p,role:i<4?'held_bank_byte':'actual_RR_OR_WR',bank:i%4})),destination:d.original.target.position,cone});}
const footprint=new Set();for(const p of devices.values())for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++)footprint.add(K(P(p.x+x,p.y+y,p.z+z)));const context=[];streamBlocks(cold,(r,i)=>{if(footprint.has(K(r.position)))context.push({...r,part:labelsMeta.labels[labels[i]]});});const actual=new Map(context.map(r=>[K(r.position),r.block]));let checkedInputs=0;for(const p of devices.values()){assert.deepEqual(actual.get(K(p)),old.get(K(p)));assert.deepEqual(inputs(actual,p).map(K).sort(),inputs(old,p).map(K).sort(),'Full context changes source '+K(p));checkedInputs+=inputs(actual,p).length;}
console.log(JSON.stringify({phase:'source_context_recovered',bank_stores:sourceRows.length,backend_stores:backendRows.length,collector_cones:collectors.length,selected_devices:devices.size,context:context.length,matched_transport:transport.length}));
const sourcesTruth=[];for(const s of sourceRows){const levels=[];for(const value of[0,15]){const a=numeric(actual,s.original_cone,[s.original_q],[value]),b=numeric(current,s.current_cone,[s.current_q],[value]),x=a.power.get(K(s.original.source.position))??0,y=b.power.get(K(s.current_source))??0;assert.equal(x,value);assert.equal(y,value);levels.push({q:value,original:x,current:y});}sourcesTruth.push({bank:s.bank,bit:s.bit,levels});}
const pairTruth=[];for(const p of pairRows){const nowRoots=[p.read_ready,p.write_ready],nowCone=backwardCone(current,p.positive_pair_OR_output,nowRoots),truth=[];for(let mask=0;mask<4;mask++){const values=[mask&1?15:0,mask&2?15:0],a=numeric(actual,p.original_cone,p.original_roots,values),b=numeric(current,nowCone,nowRoots,values),x=a.power.get(K(p.original_pair))??0,y=b.power.get(K(p.positive_pair_OR_output))??0;assert.equal(x>0,mask!==0);assert.equal(y>0,mask!==0);truth.push({mask,original:x,current:y});}pairTruth.push({bank:p.bank,channel:p.channel,truth,current_cone:nowCone});}
write('source-identities.json',{status:'actual_bank_held_response_and_RR_OR_WR_sources_recovered_no_geometry',sourceRows,backendRows,pairRows,sourcesTruth,pairTruth,source_device_changes:[],source_sha256:pins,limits:['Actual 32 bank response Qs and 32 backend response Qs/locks are identified; storage dynamics remain open.','Mask input is the actual bank/channel RR OR WR. Writes may select internal D; no zero-on-write claim.','No response route is drawn or cut closed.']});
write('original-context.json',{blocks:context,selected_devices:devices.size,checkedInputs,collectors,source_sha256:pins});write('matched-original-transport.json',{...summary(transport),blocks:transport,source_sha256:pins});
const originalRoutes=field(cold,'bank_response_routes'),junctionRepairs=[];for(const name of['bank_data2_4_escape','bank_data1_5_source_escape']){const route=originalRoutes.find(r=>r.name===name);assert(route);const index=route.path.length-2,p=route.path[index];assert(route.refresh_indices.includes(index));assert.equal(actual.get(K(p))?.id,R);junctionRepairs.push({name,index,position:p,block:actual.get(K(p)),reason:'Previously fixed original cable-section junction attenuation, already present in authoritative cold source. No current geometry repair is added.'});}
const truth=[],events=[];for(const row of collectors){const roots=row.roots.map(r=>r.position),constants=row.cone.filter(p=>actual.get(K(p))?.id==='minecraft:redstone_block'),evaluate=makeSettledEvaluator(actual,row.cone,[...roots,...constants],{eventLimit:4000000}),cases=[];for(let mask=0;mask<256;mask++){const result=evaluate(new Map([...roots.map((p,i)=>[K(p),mask>>i&1?15:0]),...constants.map(p=>[K(p),15])])),level=result.power.get(K(row.destination))??0,expected=(mask&15)&(mask>>4)?15:0;assert.equal(level,expected,'Response selection '+JSON.stringify({channel:row.channel,bit:row.bit,mask}));cases.push({mask,level});events.push(result.events);}truth.push({channel:row.channel,bit:row.bit,devices:row.cone.length,cases});console.log(JSON.stringify({phase:'actual_original_response_function',channel:row.channel,bit:row.bit,cases:256,devices:row.cone.length}));}
write('source-functions.json',{status:'actual_original_qualified_response_cones_pass_no_geometry',equation:'backend_D[channel][bit] = OR_bank(held_bank_response[bank][bit] AND (read_ready[bank][channel] OR write_ready[bank][channel]))',cases:8192,outputs:32,truth,maximum_numeric_events:Math.max(...events),original_context_cells:context.length,original_selected_devices:devices.size,original_checked_inputs:checkedInputs,source_levels:sourcesTruth,pair_levels:pairTruth,junctionRepairs,matched_transport:summary(transport),new_cells:0,new_closed_cuts:0,source_sha256:pins,limits:['All 256 ready/data bit combinations per actual output include stale all-one unselected banks and invalid multi-bank selections. This tests combinational isolation, not one-hot protocol generation.','Each RR/WR signal remains the separately proven ACTIVE/final-tail/reset/owner/type-qualified export. Its 12 known earlier refresh corrections are preserved in the current source group; raw original phase qualification is not asserted equivalent.','Held response Q capture, current response routes, backend D setup/hold/lock closure, READY/data skew and final consumer visibility are separate gates.']});
