import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
import{inputs,active}from'../cut-inputs.mjs';
export const H=new URL('./',import.meta.url),ROOT=new URL('../../../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};
export function bytes(n,expected){const url=new URL(n,H),b=readFileSync(url),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(url).slice(fileURLToPath(ROOT).length)]=h;return b;}
export const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,d)=>writeFileSync(new URL(n,H),JSON.stringify(d)+'\n');
export function streamBlocks(buffer,visit){const marker=Buffer.from('"blocks":['),at=buffer.indexOf(marker);assert(at>=0);let i=at+marker.length,start=i,depth=0,quoted=false,escape=false,batch=0,index=0;function flush(end){const text=buffer.subarray(start,end).toString();if(text.trim())for(const row of JSON.parse('['+text+']'))visit(row,index++);}for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return index;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated source array');}
export function field(buffer,name){const at=buffer.indexOf(Buffer.from('"'+name+'":'));assert(at>=0,name);let start=at+name.length+3,i=start,depth=0,quoted=false,escape=false;for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if((c===44||c===125)&&depth===0)return JSON.parse(buffer.subarray(start,i));if(c===123||c===91)depth++;else if(c===125||c===93)depth--;}throw Error('Unterminated field '+name);}
export function locked(map,p){const b=map.get(K(p));if(b?.id!==R)return[];const v=D[b.properties.facing];return inputs(map,p).filter(q=>(q.x-p.x)*v.x+(q.z-p.z)*v.z===0&&[R,C].includes(map.get(K(q))?.id));}
export function findStore(map,out){const seen=new Map(),queue=[out],stores=[];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(map.get(k)),'Missing source '+k);seen.set(k,p);const locks=locked(map,p);if(locks.length){assert.equal(locks.length,1);stores.push({q:p,lock:locks[0]});continue;}queue.push(...inputs(map,p));}assert.equal(stores.length,1,'Export must reach one actual held Q '+K(out));return{...stores[0],cone:[...seen.values()]};}
export function summary(rows){const groups={},materials={},box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const r of rows){groups[r.part]=(groups[r.part]??0)+1;materials[r.block.id]=(materials[r.block.id]??0)+1;for(const a of['x','y','z']){box.from[a]=Math.min(box.from[a],r.position[a]);box.to[a]=Math.max(box.to[a],r.position[a]);}}return{cells:rows.length,groups,materials,box};}
