import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{rotatePosition,transformBlock}from'../../../../hardware/gpu-layout-assembly.mjs';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{fileURLToPath}from'node:url';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),K=p=>`${p.x},${p.y},${p.z}`,parentEndpoints=read('../pc-flags-connected-v1/endpoint-map.json'),mapping=parentEndpoints.mapping,claims=new Map(Object.entries(mapping).map(([k,v])=>[k,v.body])),core=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H))),world=new Map(core.blocks.map(b=>[K(b.position),b.block])),cuts=parentEndpoints.cuts;
function upstream(target){const queue=[{p:target,parity:0}],seen=new Set([K(target)+':0']),found=new Map,unplaced=[],torchStages=new Set;for(let i=0;i<queue.length;i++){const {p,parity}=queue[i];for(const q of inputs(world,p)){const b=world.get(K(q)),invert=['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id),nextParity=parity+Number(invert)&1,k=K(q),state=k+':'+nextParity;if(seen.has(state))continue;seen.add(state);if(claims.has(k)){found.set(state,{position:q,parity:nextParity});continue;}if(invert){const ins=inputs(world,q);if(ins.length!==1){unplaced.push({position:q,block:b,reason:'not_unary_inverter',inputs:ins});continue;}torchStages.add(k);}else if(!['minecraft:redstone_wire','minecraft:repeater'].includes(b.id)){unplaced.push({position:q,block:b,reason:'not_transport'});continue;}else if(b.id==='minecraft:repeater'){const ins=inputs(world,q);if(ins.some(s=>Math.abs(q.x-s.x)+Math.abs(q.z-s.z)===1&&['minecraft:repeater','minecraft:comparator'].includes(world.get(K(s))?.id)&&((b.properties.facing==='north'||b.properties.facing==='south')?q.x!==s.x:q.z!==s.z))){unplaced.push({position:q,reason:'locked_transport'});continue;}}queue.push({p:q,parity:nextParity});}}return{found:[...found.values()],unplaced,visited:seen.size,unary_torch_stages:torchStages.size};}
const old=read('../../control-commit-v1/design.json'),planned=old.connections.filter(c=>mapping[K(c.source)]&&mapping[K(c.destination)]),connections=[],unmatched=[],pending=old.connections.filter(c=>!mapping[K(c.source)]||!mapping[K(c.destination)]);
for(const c of planned){const walk=upstream(c.destination),sources=walk.found.filter(q=>K(q.position)!==K(c.destination));if(walk.unplaced.length||sources.length!==1||K(sources[0].position)!==K(c.source)||sources[0].parity!==0){unmatched.push({...c,actual_sources:sources,unplaced:walk.unplaced});continue;}connections.push({...c,original_source:c.source,original_destination:c.destination,source:mapping[K(c.source)].position,destination:mapping[K(c.destination)].position,source_body:mapping[K(c.source)].body,target_body:mapping[K(c.destination)].body,actual_reference_upstream:sources,upstream_transport_nodes:walk.visited,unary_torch_stages:walk.unary_torch_stages});}
const allCuts=[];for(const b of core.blocks){if(!active(b.block))continue;const target=claims.get(K(b.position));for(const q of inputs(world,b.position)){const source=claims.get(K(q));if((source||target)&&source!==target)allCuts.push({from:q,to:b.position,source_body:source??null,target_body:target??null});}}
const priorCutSet=new Set(cuts.map(c=>K(c.from)+'>'+K(c.to))),bindings=connections.map(c=>{const source=allCuts.filter(e=>K(e.from)===K(c.original_source)),receiver=allCuts.filter(e=>K(e.to)===K(c.original_destination));assert(source.length&&receiver.length,'Missing source/receiver cut '+c.name);return{name:c.name,original_source:c.original_source,original_receiver:c.original_destination,source_boundary_edges:source.map(e=>({...e,in_982_shared_island_ledger:priorCutSet.has(K(e.from)+'>'+K(e.to))})),receiver_boundary_edges:receiver.map(e=>({...e,in_982_shared_island_ledger:priorCutSet.has(K(e.from)+'>'+K(e.to))})),actual_transported_source_count:c.actual_reference_upstream.length,transported_polarity:'positive',full_source_fanout_closed:false};});
writeFileSync(new URL('exact-cut-bindings.json',H),JSON.stringify({status:'selected_actual_source_and_receiver_boundary_edges_bound',broader_mapped_body_directed_cut_count:allCuts.length,retained_original_shared_island_cuts:cuts.length,bindings,all_mapped_body_cuts:allCuts,complete_core:false,native_acceptance:false},null,2)+'\n');
writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({mapping,cuts,connections,unmatched,pending_unmapped_historical_endpoints:pending,selected_body_cuts:cuts.length,mapped_original_cells:claims.size,complete_core:false,native_acceptance:false})+'\n');console.log(JSON.stringify({connections:connections.map(c=>({name:c.name,source:c.source,destination:c.destination})),unmatched,pending:pending.map(c=>c.name),cuts:cuts.length},null,2));
