import assert from'node:assert/strict';import{readFileSync,readdirSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{makeSourcePinHasher}from'../../../scripts/source-pin-hasher.mjs';
const ROOT=fileURLToPath(new URL('../../../',import.meta.url)),B='artifacts/full-gpu-layout-v1/',here=B+'compact-core-guard-v1/',audit=makeSourcePinHasher(ROOT),pins={};
const read=p=>JSON.parse(readFileSync(new URL('../../../'+p,import.meta.url)));
function add(p,h){const actual=audit.hash(p);assert.equal(actual,h??actual,p);assert(!pins[p]||pins[p]===actual,'Conflicting pin');pins[p]=actual;}
const cfg=read(here+'machine-config.json');for(const c of cfg.instances){add(c.source_manifest,c.source_manifest_sha256);const m=read(c.source_manifest);for(const[p,h]of Object.entries(m.source_sha256??m.files??m.pins))add(p,h);}
for(const n of['extraction.json','trial-design.json','checks.json','foreign-equivalence.json','foreign-obstacles.json'])for(const[p,h]of Object.entries(read(here+n).source_sha256))add(p,h);
assert.equal(read(here+'checks.json').status,'relocation_actual_cell_dependency_screen_passed');assert.equal(read(here+'foreign-equivalence.json').status,'fresh_selected_foreign_rows_equal_routing_obstacles');const mat=read(here+'materialization.json');add(here+'design.json',mat.design_sha256);assert.equal(mat.retained_bits,1117);assert.equal(mat.blocks,1828787);
function directory(prefix){for(const e of readdirSync(new URL('../../../'+prefix,import.meta.url),{withFileTypes:true})){if(e.name==='source-manifest.json')continue;const p=prefix+e.name;if(e.isDirectory())directory(p+'/');else if(e.isFile())add(p);else assert.fail('Unexpected source kind '+p);}}directory(here);
for(const n of['hardware/memory-layout-large-json-v2.mjs','scripts/source-pin-hasher.mjs','artifacts/full-gpu-layout-v1/control-commit-v2/route.mjs'])add(n);
audit.assertStable();const out={status:'frozen_connected_guard_relocation_author_geometry_pending_independent_timing',source_sha256:Object.fromEntries(Object.entries(pins).sort()),physical_core_cells:mat.blocks,declared_retained_bits:1117,core_cells_saved_against_fault_parent:25000,incident_connections:41,master_geometry_selected:false,complete_gpu_layout:false,native_calls:0,world_mutations:0,native_acceptance:false};writeFileSync(new URL('source-manifest.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({manifest_sha256:audit.hash(here+'source-manifest.json'),pins:Object.keys(pins).length,...audit.stats()}));
