// Recover original route polarity and actual old/current loader source gates.
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {H,read,K,pins,loadFrame} from './frame.mjs';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
import {evaluate} from '../dispatch-external-bindings-v1/transport-functions.mjs';
import {backwardCone,makeSettledEvaluator} from '../program-global-delivery-v1/settled-program-network.mjs';
import {checkFeedback} from '../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
const P=(x,y,z)=>({x,y,z}),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),write=(n,d)=>writeFileSync(new URL(n,H),JSON.stringify(d,null,2)+'\n');
const assignment=read('../loader-global-transfer-recovery-v1/assignment.json'),ledger=read('../bank-global-delivery-v1/remaining-cuts.json'),dispatchScope=read('../dispatch-global-colocation-v1/reference-scope.json'),loaderScope=read('../loader-program-colocation-v1/reference-scope.json'),routes=read('../master-loader-control-routes-v1/design.json'),endpoints=read('../loader-program-colocation-v1/control-owner-v1/endpoint-map.json');
const old=new Map();for(const r of [...dispatchScope.blocks,...dispatchScope.foreign_context,...loaderScope.blocks,...loaderScope.foreign_context,...routes.blocks]){const k=K(r.position);if(old.has(k))assert.deepEqual(old.get(k),r.block);old.set(k,r.block);}
const {world}=loadFrame(),owned=new Set(routes.blocks.filter(r=>active(r.block)).map(r=>K(r.position))),allBoundaries=Object.entries(endpoints.ports).filter(([n,p])=>p.direction==='input').map(([name,p])=>({name,old:p.bits[0].original_position,current:A(p.bits[0].position,P(-160,-32,-176))})),selected=[],sources=[];
const expected=(index,v)=>index===261?!!v.boot:index===287?!!v.load_request:index===319?!!v.raw_start&&!v.raw_reset&&!v.load_request&&!v.owner&&!v.boot&&!!v.cold_initialized&&!!v.image_verified:!!v.raw_reset||!!v.load_request||!!v.owner||!!v.boot;
for(const record of assignment.records){const index=record.transfer_index,b=record.original_binding,original=b.old_connection;assert.equal(ledger.dispatch.transfers[index].status,'external_source_transfer_pending');assert.deepEqual(record.shared_target,ledger.dispatch.transfers[index].shared_retained_target);assert.deepEqual(world.get(K(record.source_row.position)),record.source_row.block);assert.deepEqual(world.get(K(record.shared_target)),b.receiver.block);assert.deepEqual(old.get(K(original.source)),record.source_row.block);
const transport=new Set(),todo=[original.normalizer];for(let i=0;i<todo.length;i++){const p=todo[i],k=K(p);if(k===K(original.source)||transport.has(k))continue;assert(owned.has(k),'Foreign old route root '+k);transport.add(k);todo.push(...inputs(old,p));}const f=evaluate(old,transport).get(original.normalizer);assert.deepEqual(f,{roots:[original.source],table:2});assert(inputs(old,original.destination).some(p=>K(p)===K(original.normalizer)));
const oldPositions=backwardCone(old,original.source,allBoundaries.map(v=>v.old)),currentPositions=backwardCone(world,record.source_row.position,allBoundaries.map(v=>v.current)),oldKeys=new Set(oldPositions.map(K)),currentKeys=new Set(currentPositions.map(K));const boundaries=allBoundaries.filter(v=>oldKeys.has(K(v.old))||currentKeys.has(K(v.current)));for(const v of boundaries){assert(oldKeys.has(K(v.old))&&currentKeys.has(K(v.current)));assert.deepEqual(old.get(K(v.old)),world.get(K(v.current)));}
const oldEv=makeSettledEvaluator(old,oldPositions,boundaries.map(v=>v.old)),newEv=makeSettledEvaluator(world,currentPositions,boundaries.map(v=>v.current)),cases=[];assert(boundaries.length<=7);
for(let mask=0;mask<2**boundaries.length;mask++){const values=Object.fromEntries(boundaries.map((v,i)=>[v.name,!!(mask>>i&1)])),a=oldEv(new Map(boundaries.map(v=>[K(v.old),values[v.name]?15:0]))).power.get(K(original.source))??0,c=newEv(new Map(boundaries.map(v=>[K(v.current),values[v.name]?15:0]))).power.get(K(record.source_row.position))??0,want=expected(index,values)?15:0;assert.equal(a,want);assert.equal(c,want);cases.push({mask,values,old_output:a,current_output:c});}
const fanout=[];for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++){const p=A(record.source_row.position,P(x,y,z));if(inputs(world,p).some(q=>K(q)===K(record.source_row.position)))fanout.push({position:p,block:world.get(K(p))});}
selected.push({name:record.name,transfer_index:index,new_source:record.source_row.position,new_destination:record.shared_target,source:original.source,target:original.destination,old_normalizer:original.normalizer,old_route_function:f,old_transport_vertices:transport.size,old_source_successors:[...transport].map(k=>P(...k.split(',').map(Number))).filter(p=>inputs(old,p).some(q=>K(q)===K(original.source)))});sources.push({transfer_index:index,boundaries,cases,actual_current_fanout:fanout,original_cone:oldPositions.map(p=>({position:p,block:old.get(K(p)),inputs:boundaries.some(b=>K(b.old)===K(p))?[]:inputs(old,p)})),current_cone:currentPositions.map(p=>({position:p,block:world.get(K(p)),inputs:boundaries.some(b=>K(b.current)===K(p))?[]:inputs(world,p)})),feedback:checkFeedback(world,currentPositions,boundaries.map(v=>v.current))});
}
write('source-functions.json',{status:'actual_original_loader_global_deliveries_positive',selected,sources,source_sha256:pins,limits:['Loader input ports are held test boundaries; combinational source checks do not prove owner/reset/drain state generation or command pulse timing.','All new routes must preserve current actual fanout and all old receiver inputs; no producer input is invented as a runtime driver.','No world mutation or native proof.']});console.log(JSON.stringify({status:'sources_pass',routes:selected.length,cases:sources.reduce((n,r)=>n+r.cases.length,0),old_transport:selected.reduce((n,r)=>n+r.old_transport_vertices,0),old_gates:sources.reduce((n,r)=>n+r.original_cone.length,0),new_gates:sources.reduce((n,r)=>n+r.current_cone.length,0)}));
