// Physical assignment fanout over the frozen single-copy core/RF composition.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),W='minecraft:redstone_wire';
export function makeAssignment({plan=false}={}){
 const bytes=readFileSync(new URL('../control-rf-composed-v1/source-manifest.json',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),'9e3761c1001dd879c741d64137671219912aa1b41f8dd671a62383c8311fa21a');
 const base=read('../control-rf-composed-v1/design.json'),map=new Map(base.blocks.map(v=>[K(v.position),{...v,part:'composed_parent'}])),edges=[],routes=[],connections=[],receivers=[];let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to});
 const put=(p,id,properties)=>{const block={id:'minecraft:'+id,...properties?{properties}:{}},old=at(p);if(old){assert.equal(id,'light_gray_concrete','collision '+part+' '+K(p)+' '+old.part);assert.deepEqual(old.block,block,part+' support collision '+K(p));return;}map.set(K(p),{position:p,block,part});},solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'});
 const cacheUrl=new URL('routes.json',import.meta.url),cache=existsSync(cacheUrl)?read('routes.json'):{},pending=[],reserved=[],step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),reserve=(s,sd,d,ad)=>[...Array.from({length:18},(_,i)=>step(s,sd,i+2)),...Array.from({length:18},(_,i)=>step(d,ad,-i-2))];
 function draw(name,source,sd,destination,ad,stubs=false){part=name;assert.equal(at(source)?.block.id,W,'source '+name);assert.equal(at(destination)?.block.id,W,'destination '+name);const first=step(source,sd),start=step(source,sd,2),last=step(destination,ad,-1),end=step(destination,ad,-2);if(stubs){rep(first,sd);wire(start);rep(last,ad);wire(end);edge(source,first);edge(first,start);edge(end,last);edge(last,destination);return;}
  let path=cache[name]?.path;if(!path){assert(plan,'Missing route '+name);const ignore=[...reserve(source,sd,destination,ad),first,start,last,end,...[first,start,last,end].map(p=>P(p.x,p.y-1,p.z))],forbidden=[first,last].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![source,start,end,destination].some(q=>K(p)===K(q))),r=searchPath(map,start,end,{ignore,reserved,forbidden});path=r.path;cache[name]={source,destination,path,expanded:r.expanded};writeFileSync(cacheUrl,JSON.stringify(cache)+'\n');console.error(name+': '+path.length+' / '+r.expanded);}
  assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i)){const dir=Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source,tap:first,destination,arrival:last});
 }
 for(let i=0;i<4;i++){
  const inherited=i===2?base:read('../control-commit-v2/design.json'),sourceRoute=inherited.routes.find(r=>r.name==='input_enable'+i),coreSource=sourceRoute.path[11],sourceDirection=i===2?'north':'east',rf=P(718,194+4*i,92),alu=P(2136,275+8*i,160);assert(sourceRoute.refresh_indices.includes(10));assert.equal(at(sourceRoute.path[10]).block.id,'minecraft:repeater');
  pending.push(['mask_to_rf_'+i,coreSource,sourceDirection,rf,'south']);
  pending.push(['mask_to_alu_'+i,rf,'east',alu,'east']);
  receivers.push({lane:i,core_normalized_tap:coreSource,source_route:'input_enable'+i,source_index:11,rf,alu,meaning:'Same held dispatch lane-enable; entire fanout must settle before START admission.'});
 }
 pending.push(['reset_to_rf',P(-140,1,-2),'east',P(1090,242,-7),'south']);
 for(const[,s,sd,d,ad]of pending)reserved.push(...reserve(s,sd,d,ad));for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=blocks.reduce((n,v)=>Math.min(n,v.position[a]),Infinity);box.to[a]=blocks.reduce((n,v)=>Math.max(n,v.position[a]),-Infinity);}
 return{status:'shared_assignment_reset_delivery_draft',blocks,parents:{composed_parent:{blocks:base.blocks.length,translation:P(0,0,0)}},ports:base.ports,edges,routes,connections,assignment_receivers:receivers,box,metrics:{blocks:blocks.length,parent_blocks:base.blocks.length,added_blocks:blocks.length-base.blocks.length,connections:connections.length,retained_bits:875},native_acceptance:false,complete_controller:false,missing:['Retained dispatcher START/reset-ack/busy/done and complete reset/drain producer remain missing.','OTHER startup assignment producer and LSU ownership/reset join remain missing.','This fanout reaches the frozen ALU join-enable receivers, not later unpublished lane delivery.','All far-end source settlement and reset closure timing remain unmeasured.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeAssignment({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
