// Three physical XORs and enabled-lane mismatch collector. No native calls.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,F={east:'west',west:'east',north:'south',south:'north'},V={east:[1,0],west:[-1,0],north:[0,-1],south:[0,1]};
export function makeBranchAgreement(){
 const map=new Map(),edges=[],ports={},comparisons=[];const edge=(a,b)=>edges.push({from:a,to:b}),join=ps=>{for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);};
 function put(p,id,props,part){const block={id:'minecraft:'+id,...(props?{properties:props}:{})},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'collision '+K(p));return;}map.set(K(p),{position:p,block,part});}
 const solid=(p,part)=>put(p,'light_gray_concrete',undefined,part),dev=(p,id,props,part)=>{solid(P(p.x,p.y-1,p.z),part+'_support');put(p,id,props,part);};
 const wire=(x,y,z,part)=>dev(P(x,y,z),'redstone_wire',undefined,part),rep=(x,y,z,d,part)=>dev(P(x,y,z),'repeater',{facing:F[d],delay:'1'},part);
 function line(x1,z1,x2,z2,y,part){assert(x1===x2||z1===z2);const n=Math.abs(x2-x1)+Math.abs(z2-z1),ps=[];for(let i=0;i<=n;i++){const p=P(x1+Math.sign(x2-x1)*i,y,z1+Math.sign(z2-z1)*i);wire(p.x,p.y,p.z,part);ps.push(p);}join(ps);return ps;}
 for(let lane=1;lane<4;lane++){
  const z0=24*(lane-1),w=(x,y,z)=>wire(x,y+1,z0+z,'xor'+lane),r=(x,y,z,d)=>rep(x,y+1,z0+z,d,'xor'+lane),ln=(x,z,x2,z2,y=0)=>line(x,z0+z,x2,z0+z2,y+1,'xor'+lane);
  for(const z of [0,8]){ln(0,z,3,z);r(4,0,z,'east');dev(P(5,1,z0+z),'comparator',{facing:'west',mode:'subtract'},'xor'+lane);w(6,0,z);r(7,0,z,'east');ln(8,z,9,z);join([3,4,5,6,7,8].map(x=>P(x,1,z0+z)));}
  ln(1,8,1,2);ln(1,2,5,2);r(5,0,1,'north');join([P(5,1,z0+2),P(5,1,z0+1),P(5,1,z0)]);
  let prev=P(1,1,z0);for(let k=1;k<=3;k++){w(1,k,-k);edge(prev,P(1,1+k,z0-k));prev=P(1,1+k,z0-k);}ln(1,-3,2,-3,3);r(3,3,-3,'east');ln(4,-3,5,-3,3);ln(5,-3,5,-1,3);r(5,3,0,'south');ln(5,1,5,3,3);join([P(2,4,z0-3),P(3,4,z0-3),P(4,4,z0-3)]);join([P(5,4,z0-1),P(5,4,z0),P(5,4,z0+1)]);
  prev=P(5,4,z0+3);for(let k=1;k<=3;k++){w(5,3-k,3+k);edge(prev,P(5,4-k,z0+3+k));prev=P(5,4-k,z0+3+k);}r(5,0,7,'south');join([P(5,1,z0+6),P(5,1,z0+7),P(5,1,z0+8)]);
  ln(9,0,9,8);w(10,0,4);r(11,0,4,'east');w(12,0,4);join([P(9,1,z0+4),P(10,1,z0+4),P(11,1,z0+4),P(12,1,z0+4)]);
  for(const z of [0,8]){w(-2,0,z);r(-1,0,z,'east');join([P(-2,1,z0+z),P(-1,1,z0+z),P(0,1,z0+z)]);}
  rep(-5,1,z0,'east','ref_branch');const ref=line(-4,z0,-2,z0,1,'ref_branch');join([P(-6,1,z0),P(-5,1,z0),...ref]);
  // XOR result AND active: subtract the strong !active mask.
  rep(13,1,z0+4,'east','difference_data');wire(14,1,z0+4,'difference_pad');dev(P(15,1,z0+4),'comparator',{facing:'west',mode:'subtract'},'active_gate');rep(16,1,z0+4,'east','active_output');const out=line(17,z0+4,20,z0+4,1,'fault_branch');join([P(12,1,z0+4),P(13,1,z0+4),P(14,1,z0+4),P(15,1,z0+4),P(16,1,z0+4),...out]);
  wire(15,1,z0-6,'lane_enable');rep(15,1,z0-5,'south','enable_input');solid(P(15,1,z0-4),'enable_support');solid(P(15,0,z0-4),'enable_floor');put(P(15,1,z0-3),'redstone_wall_torch',{facing:'south'},'enable_not');wire(15,1,z0-2,'enable_not_pad');rep(15,1,z0-1,'south','enable_normalize');const en=line(15,z0,15,z0+2,1,'enable_mask');rep(15,1,z0+3,'south','enable_side');join([P(15,1,z0-6),P(15,1,z0-5),P(15,1,z0-4)]);join([P(15,1,z0-3),P(15,1,z0-2),P(15,1,z0-1),...en,P(15,1,z0+3),P(15,1,z0+4)]);
  comparisons.push({lane,reference:P(-2,1,z0),taken:P(-2,1,z0+8),enable:P(15,1,z0-6),xor:P(12,1,z0+4),qualified:P(16,1,z0+4)});
 }
 wire(-6,1,-4,'taken0');rep(-6,1,-3,'south','taken0_driver');let prev=P(-6,1,-3);for(let z=-2;z<=48;z++){if([9,21,33,45].includes(z))rep(-6,1,z,'south','reference_refresh');else wire(-6,1,z,'reference_rail');edge(prev,P(-6,1,z));prev=P(-6,1,z);}edge(P(-6,1,-4),P(-6,1,-3));
 // lane0 must be active for any dispatched core; IDLE may show fault but cannot commit.
 wire(20,1,-14,'lane0_enable');rep(20,1,-13,'south','lane0_input');solid(P(20,1,-12),'lane0_support');solid(P(20,0,-12),'lane0_floor');put(P(20,1,-11),'redstone_wall_torch',{facing:'south'},'lane0_not');wire(20,1,-10,'lane0_not_pad');rep(20,1,-9,'south','lane0_driver');join([P(20,1,-14),P(20,1,-13),P(20,1,-12)]);join([P(20,1,-11),P(20,1,-10),P(20,1,-9)]);
 prev=P(20,1,-9);for(let z=-8;z<=60;z++){if([-1,11,23,35,47,59].includes(z))rep(20,1,z,'south','fault_refresh');else wire(20,1,z,'fault_rail');edge(prev,P(20,1,z));prev=P(20,1,z);}rep(20,1,61,'south','fault_output');wire(20,1,62,'fault_terminal');rep(20,1,63,'south','agree_input');solid(P(20,1,64),'agree_support');solid(P(20,0,64),'agree_floor');put(P(20,1,65),'redstone_wall_torch',{facing:'south'},'agree_not');rep(20,1,66,'south','agree_output');wire(20,1,67,'agree_terminal');join([prev,P(20,1,61),P(20,1,62),P(20,1,63),P(20,1,64)]);join([P(20,1,65),P(20,1,66),P(20,1,67)]);
 const port=(name,dir,ps)=>ports[name]={direction:dir,width:ps.length,polarity:'active_high',bit_order:'lane_index_LSB_first',bits:ps.map((position,bit)=>({bit,position,...(dir==='input'?{required_high_power:15}:{high_power:15})}))};
 port('branch_taken','input',[P(-6,1,-4),...comparisons.map(c=>c.taken)]);port('lane_enable','input',[P(20,1,-14),...comparisons.map(c=>c.enable)]);port('disagreement','output',[P(20,1,62)]);port('agreement','output',[P(20,1,67)]);
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of ['x','y','z']){box.from[a]=Math.min(...blocks.map(b=>b.position[a]));box.to[a]=Math.max(...blocks.map(b=>b.position[a]));}
 return{status:'physical_active_lane_branch_agreement_offline_unverified',blocks,box,ports,edges,comparisons,metrics:{blocks:blocks.length,xors:3,active_gates:3,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1]))},semantics:'fault = !enable0 OR any j=1..3 (enable[j] AND (taken[j] XOR taken[0])); agreement = !fault. The dispatched enabled mask is contiguous1/3/7/15. Current PC and immediate are common, so agreeing branch decisions imply agreeing next PC.',protocol:'Evaluate only after every active retained flag/IR/BR predicate settles; sample and retain any fault before opening NEXT. A high transient agreement is not a handshake or permission to write. IDLE enable0=0 deliberately refuses commit.',native_acceptance:false,complete_gpu:false,missing:['All four lane predicate/enable routes, error latch and sequencer gating.','Measured agreement settle under simultaneous 7→8-like transitions and fault capture.']};
}
export function checkBranchAgreement(d){
 const m=new Map(d.blocks.map(b=>[K(b.position),b])),allowed=new Set(d.edges.map(e=>[K(e.from),K(e.to)].sort().join('|')));assert.equal(m.size,d.blocks.length);let supports=0,contacts=0;
 for(const b of d.blocks){if(b.block.id.endsWith('_concrete'))continue;let p=P(b.position.x,b.position.y-1,b.position.z);if(b.block.id==='minecraft:redstone_wall_torch'){const [x,z]=V[b.block.properties.facing];p=P(b.position.x-x,b.position.y,b.position.z-z);}assert.equal(m.get(K(p))?.block.id,'minecraft:light_gray_concrete','support');supports++;}
 for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))for(const[x,z]of Object.values(V))for(const y of [-1,0,1]){const p=P(b.position.x+x,b.position.y+y,b.position.z+z),o=m.get(K(p));if(!o||o.block.id.endsWith('_concrete'))continue;if(y&&o.block.id!=='minecraft:redstone_wire')continue;if(y===1&&m.has(K(P(b.position.x,b.position.y+1,b.position.z))))continue;if(y===-1&&m.has(K(P(p.x,p.y+1,p.z))))continue;assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign dust '+K(b.position)+' '+K(p));contacts++;}
 let cases=0;for(let takes=0;takes<16;takes++)for(let enabled=0;enabled<16;enabled++){const ref=takes&1;let fault=!(enabled&1);for(let j=1;j<4;j++){const t=(takes>>>j)&1,e=(enabled>>>j)&1,xor=+(Math.max(15*ref-15*t,0)+Math.max(15*t-15*ref,0)>0),term=+(Math.max(15*xor-15*(1-e),0)>0);fault||=!!term;}const expected=!(enabled&1)||[1,2,3].some(j=>(enabled&(1<<j))&&((takes>>>j)&1)!==ref);assert.equal(fault,expected);cases++;}
 return{status:'author_branch_agreement_static_checks_passed',...d.metrics,support_checks:supports,dust_contacts:contacts,all_masks_and_predicates:cases,native_calls:0,limits:['Steady algebra plus drawn contacts, not dynamic fault/phase acceptance.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeBranchAgreement(),r=checkBranchAgreement(d);if(process.argv.includes('--check'))assert.deepEqual(JSON.parse(readFileSync(new URL('agreement.json',import.meta.url))),d);else{writeFileSync(new URL('agreement.json',import.meta.url),JSON.stringify(d)+'\n');writeFileSync(new URL('agreement-check.json',import.meta.url),JSON.stringify(r,null,2)+'\n');}console.log(JSON.stringify(r,null,2));}
