import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeLaneJoin,makeStickyFault,makePhaseQualifier,checkMap} from './prepare.mjs';
const K=p=>`${p.x},${p.y},${p.z}`,D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},P=(x,y,z)=>({x,y,z});
const designs={lane_join:makeLaneJoin(),sticky_fault:makeStickyFault(),phase_qualifier:makePhaseQualifier()};for(const[n,d]of Object.entries(designs))assert.deepEqual(d,JSON.parse(readFileSync(new URL(n+'.json',import.meta.url))));
function directions(d){const m=new Map(d.blocks.map(v=>[K(v.position),v.block]));let checks=0;for(const r of d.routes)for(const i of r.refresh_indices){const p=r.path[i],v=D[m.get(K(p)).properties.facing];assert.deepEqual(r.path[i+1],P(p.x+v[0],p.y,p.z+v[1]));assert.deepEqual(r.path[i-1],P(p.x-v[0],p.y,p.z-v[1]));checks++;}for(const b of d.blocks.filter(b=>b.block.id==='minecraft:comparator')){assert.deepEqual(b.block.properties,{facing:'west',mode:'subtract'});checks++;}return checks;}
function phaseDirections(d){const m=new Map(d.blocks.map(v=>[K(v.position),v.block]));for(const g of d.gates)for(const[x,z,face]of[[-1,0,'west'],[1,0,'west'],[0,-1,'north']])assert.equal(m.get(`${g.center.x+x},1,${g.center.z+z}`)?.properties.facing,face);assert.deepEqual(m.get('47,1,0'),{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}},'Initialize OR must not backfeed the run-only action mask');}
function wireCapacity(d){
 const adj=new Map(),power=new Map();for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))adj.set(K(b.position),[]);
 for(const e of d.edges)if(adj.has(K(e.from))&&adj.has(K(e.to))){adj.get(K(e.from)).push(K(e.to));adj.get(K(e.to)).push(K(e.from));}
 const seed=p=>{if(adj.has(K(p)))power.set(K(p),15);};
 for(const p of Object.values(d.ports).filter(p=>p.direction==='input'))for(const bit of p.bits)seed(bit.position);
 for(const b of d.blocks){if(['minecraft:repeater','minecraft:comparator'].includes(b.block.id)){const[x,z]=D[b.block.properties.facing];seed(P(b.position.x+x,b.position.y,b.position.z+z));}if(['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.block.id))for(const[x,z]of Object.values(D))seed(P(b.position.x+x,b.position.y,b.position.z+z));}
 const queue=[...power.keys()];for(let i=0;i<queue.length;i++){const k=queue[i],v=power.get(k)-1;if(v<=0)continue;for(const p of adj.get(k)??[])if((power.get(p)??0)<v){power.set(p,v);queue.push(p);}}
 let rears=0;for(const b of d.blocks.filter(b=>b.part!=='bank_parent'&&['minecraft:repeater','minecraft:comparator'].includes(b.block.id))){const[x,z]=D[b.block.properties.facing],p=P(b.position.x-x,b.position.y,b.position.z-z);if(adj.has(K(p))){assert((power.get(K(p))??0)>0,'No positive declared wire span to '+K(b.position));rears++;}}
 return rears;
}
const reports=Object.fromEntries(Object.entries(designs).map(([n,d])=>[n,{...checkMap(d),direction_checks:directions(d),positive_possible_wire_rears:wireCapacity(d)}]));phaseDirections(designs.phase_qualifier);
let joins=0;for(let enabled=0;enabled<16;enabled++)for(let ready=0;ready<16;ready++)for(let fault=0;fault<16;fault++){let busyTorch=false,faultTorch=false;for(let y=1;y<=27;y+=2){const lane=(y-1)/8,valid=Number.isInteger(lane),e=valid?15*(enabled>>lane&1):0,r=valid?15*(ready>>lane&1):0,f=valid?15*(fault>>lane&1):0,busy=valid&&Math.max(e-r,0)>0,bad=valid&&Math.max(e-(15-f),0)>0;busyTorch=!(busyTorch||busy);faultTorch=!(faultTorch||bad);}const expectedPending=(enabled&~ready)!==0,expectedFault=(enabled&fault)!==0;assert.equal(busyTorch,expectedPending);assert.equal(!busyTorch,!expectedPending);assert.equal(faultTorch,expectedFault);joins++;}
let phases=0;for(let bits=0;bits<128;bits++){const[p,reset,fault,init,a,b,valid]=Array.from({length:7},(_,i)=>(bits>>i)&1),q=x=>x?15:0;let run=q(p);run=Math.max(run-q(reset),0);run=Math.max(run-q(fault),0);run=Math.max(run-q(init),0);const enabled=Math.max(run,q(init)),next=Math.max(q(a)-(15-enabled),0)>0,current=Math.max(q(b)-(15-enabled),0)>0,action=Math.max(Math.max(q(a)-(15-run),0)-(15-q(valid)),0)>0;const enabledExpected=!!init||!!p&&!reset&&!fault&&!init;assert.equal(next,!!a&&enabledExpected);assert.equal(current,!!b&&enabledExpected);assert.equal(action,!!a&&!!p&&!reset&&!fault&&!init&&!!valid);if(reset||init||fault)assert(!action);phases++;}
let sticky=0;for(let start=0;start<4;start++)for(let sequence=0;sequence<256;sequence++){let current=start&1,next=start>>1; // Initialization from every actual two-bank state.
 next=0;current=next;assert.equal(current,0);for(let step=0;step<4;step++){const raw=sequence>>(step*2)&1,clear=sequence>>(step*2+1)&1,previous=current;next=Number((current||raw)&&!clear);const held=next;current=held;assert.equal(current,clear?0:Number(previous||raw));assert.equal(next,held);}sticky++;}
let negative=0;for(const change of[d=>d.blocks.find(v=>K(v.position)==='47,1,0').block.id='minecraft:redstone_wire',d=>d.blocks.find(v=>K(v.position)==='47,1,0').block.properties.facing='east',d=>d.blocks.find(v=>K(v.position)==='60,1,15').block.properties.facing='south',d=>d.blocks.find(v=>K(v.position)==='40,1,0').block.properties.mode='compare']){const d=structuredClone(designs.phase_qualifier);change(d);assert.throws(()=>{checkMap(d);directions(d);phaseDirections(d);});negative++;}
const result={status:'author_static_control_event_gate_checks_passed',components:reports,all_lane_enable_ready_fault_vectors:joins,phase_qualification_vectors:phases,initialized_sticky_fault_sequences:sticky,corruptions_refused:negative,native_acceptance:false,limits:['Algebra/direction/contact checks do not prove native timing or fault-pulse capture.','Wire capacity seeds each diode as a possible normalized source; it is not a logical activation or solid-power simulation.','NEXT/CURRENT nonoverlap is a required input condition; this qualifier cannot repair overlapping producer phases.','All external request/ready/fault sources and intermodule routes remain unconnected.']};if(process.argv.includes('--save'))writeFileSync(new URL('offline-check.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
