// Concrete four-lane readiness/fault reduction and retained fault feedback.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {makeStateBank} from '../../../hardware/full-gpu-state-bank.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,V={east:[1,0],west:[-1,0],south:[0,1],north:[0,-1]},F={east:'west',west:'east',south:'north',north:'south'};
function build(){const map=new Map(),edges=[],ports={},routes=[],gates=[];const edge=(from,to)=>edges.push({from,to}),join=ps=>{for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);};
 function put(p,id,properties,part){const block={id:'minecraft:'+id,...(properties?{properties}:{})},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'collision '+K(p));return;}map.set(K(p),{position:p,block,part});}
 const solid=(p,n)=>put(p,'light_gray_concrete',undefined,n),dev=(p,id,props,n)=>{solid(P(p.x,p.y-1,p.z),n+'_support');put(p,id,props,n);},wire=(p,n)=>dev(p,'redstone_wire',undefined,n),rep=(p,d,n)=>dev(p,'repeater',{facing:F[d],delay:'1'},n);
 function route(n,ws){const path=[P(...ws[0])];for(let i=1;i<ws.length;i++){const a=ws[i-1],b=ws[i],delta=b.map((v,j)=>v-a[j]),steps=Math.abs(delta[0])+Math.abs(delta[2]);assert(steps&&(!delta[0]||!delta[2])&&(!delta[1]||Math.abs(delta[1])===steps));for(let j=1;j<=steps;j++)path.push(P(...a.map((v,k)=>v+Math.sign(delta[k])*j)));}const candidates=[-1];for(let i=1;i<path.length-1;i++){const a=path[i-1],p=path[i],b=path[i+1];if(!map.has(K(p))&&a.y===p.y&&b.y===p.y&&p.x-a.x===b.x-p.x&&p.z-a.z===b.z-p.z)candidates.push(i);}candidates.push(path.length);const cost=new Map([[-1,0]]),prev=new Map();for(const end of candidates.slice(1))for(const start of candidates){if(start>=end)break;if(!cost.has(start)||end-start>13)continue;const value=cost.get(start)+(end===path.length?0:1);if(value<(cost.get(end)??Infinity)){cost.set(end,value);prev.set(end,start);}}assert(prev.has(path.length),'unrefreshable '+n);const refresh=[];for(let at=prev.get(path.length);at!==-1;at=prev.get(at))refresh.push(at);refresh.sort((a,b)=>a-b);for(let i=0;i<path.length;i++){const p=path[i],b=path[i+1];if(map.has(K(p)))assert.equal(map.get(K(p)).block.id,'minecraft:redstone_wire');else if(refresh.includes(i)){const d=Object.keys(V).find(d=>p.x+V[d][0]===b.x&&p.z+V[d][1]===b.z);rep(p,d,n);}else wire(p,n);}join(path);routes.push({name:n,path,refresh_indices:refresh});}
 const port=(name,direction,ps,meaning)=>ports[name]={direction,width:ps.length,polarity:'active_high',bit_order:'LSB_first',bits:ps.map((position,bit)=>({bit,position})),meaning};
 function finish(status,extra){const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=Math.min(...blocks.map(b=>b.position[a]));box.to[a]=Math.max(...blocks.map(b=>b.position[a]));}return{status,blocks,box,ports,edges,routes,gates,metrics:{blocks:blocks.length,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1]))},...extra,native_acceptance:false,complete_gpu:false};}
 return{map,edges,ports,routes,gates,put,solid,dev,wire,rep,route,edge,join,port,finish};}
export function makeLaneJoin(){const b=build(),{solid,put,wire,rep,dev,edge,join,port,finish,gates}=b,lanes=[];
 for(let lane=0;lane<4;lane++){const y=1+8*lane;
  wire(P(0,y,0),'enable');rep(P(1,y,0),'east','enable_driver');wire(P(2,y,0),'enable_pad');rep(P(3,y,0),'east','ready_rear');dev(P(4,y,0),'comparator',{facing:'west',mode:'subtract'},'not_ready_gate');rep(P(5,y,0),'east','not_ready_output');join([0,1,2,3,4,5,6].map(x=>P(x,y,0)));
  wire(P(4,y,-4),'ready');rep(P(4,y,-3),'south','ready_driver');wire(P(4,y,-2),'ready_pad');rep(P(4,y,-1),'south','ready_side');join([-4,-3,-2,-1,0].map(z=>P(4,y,z)));
  rep(P(2,y,1),'south','enable_fault_branch');join([P(2,y,0),P(2,y,1),P(2,y,2)]);for(let z=2;z<=16;z++){if(z===10)rep(P(2,y,z),'south','enable_fault_refresh');else wire(P(2,y,z),'enable_fault_route');if(z>2)edge(P(2,y,z-1),P(2,y,z));}
  rep(P(3,y,16),'east','fault_rear');dev(P(4,y,16),'comparator',{facing:'west',mode:'subtract'},'fault_gate');rep(P(5,y,16),'east','fault_output');join([2,3,4,5,6].map(x=>P(x,y,16)));
  wire(P(4,y,24),'fault');rep(P(4,y,23),'north','fault_input');solid(P(4,y,22),'fault_inverter');solid(P(4,y-1,22),'fault_inverter_floor');put(P(4,y,21),'redstone_wall_torch',{facing:'north'},'fault_not');wire(P(4,y,20),'fault_not_pad');rep(P(4,y,19),'north','fault_not_normalize');wire(P(4,y,18),'fault_not_wire');rep(P(4,y,17),'north','fault_side');join([24,23,22].map(z=>P(4,y,z)));join([21,20,19,18,17,16].map(z=>P(4,y,z)));
  gates.push({lane,ready:P(4,y,0),fault:P(4,y,16)});lanes.push({lane,enable:P(0,y,0),ready:P(4,y,-4),fault:P(4,y,24)});
 }
 for(const z of[0,16]){for(let y=1;y<=27;y++)if(y%2)solid(P(6,y,z),'reduction_or');else put(P(6,y,z),'redstone_torch',undefined,'reduction_or');solid(P(6,0,z),'reduction_floor');put(P(6,28,z),'redstone_torch',undefined,'reduction_positive');rep(P(7,28,z),'east','reduction_out');wire(P(8,28,z),'reduction_terminal');join([P(6,28,z),P(7,28,z),P(8,28,z)]);}
 rep(P(9,28,0),'east','all_ready_input');solid(P(10,28,0),'all_ready_inverter');solid(P(10,27,0),'all_ready_floor');put(P(11,28,0),'redstone_wall_torch',{facing:'east'},'all_ready_torch');rep(P(12,28,0),'east','all_ready_export');wire(P(13,28,0),'all_ready_pad');join([8,9,10].map(x=>P(x,28,0)));join([11,12,13].map(x=>P(x,28,0)));
 for(const n of['enable','ready','fault'])port(n,'input',lanes.map(l=>l[n]),'Independent physical lane-indexed inputs, normalized at local receivers.');port('any_pending','output',[P(8,28,0)],'Any enabled lane is not ready.');port('all_ready','output',[P(13,28,0)],'Vacuously true for enable0000; valid-dispatch/start qualification remains external.');port('any_fault','output',[P(8,28,16)],'Any enabled lane reports fault; feed immediate action blanking and retained fault capture.');
 return finish('physical_four_lane_ready_fault_join_offline_candidate',{lanes,semantics:{any_pending:'OR(enable[i] && !ready[i])',all_ready:'!any_pending',any_fault:'OR(enable[i] && fault[i])'},missing:['Eight-lane module fanout/reduction input routes and measured settling.','Valid-dispatch gate, raw-fault immediate blanking, retained error and core advance qualification.']});}
export function makeStickyFault(){const b=build(),{put,wire,rep,dev,route,join,port,finish}=b,parent=makeStateBank({width:1,pair:true});for(const v of parent.blocks)put(v.position,v.block.id.slice(10),v.block.properties,'bank_parent');
 rep(P(18,1,0),'east','retained_fault_isolate');wire(P(19,1,0),'fault_or');join([P(17,1,0),P(18,1,0),P(19,1,0)]);
 wire(P(19,1,-8),'raw_fault');rep(P(19,1,-7),'south','raw_fault_input');wire(P(19,1,-6),'raw_fault_pad');route('raw_fault_to_or',[[19,1,-6],[19,1,-2]]);rep(P(19,1,-1),'south','raw_fault_merge');join([P(19,1,-8),P(19,1,-7),P(19,1,-6)]);join([P(19,1,-2),P(19,1,-1),P(19,1,0)]);
 rep(P(20,1,0),'east','fault_or_normalize');wire(P(21,1,0),'fault_or_wire');wire(P(22,1,0),'fault_rear_pad');rep(P(23,1,0),'east','fault_rear');dev(P(24,1,0),'comparator',{facing:'west',mode:'subtract'},'fault_clear_gate');rep(P(25,1,0),'east','fault_next_normalize');wire(P(26,1,0),'fault_next_pad');join([19,20,21,22,23,24,25,26].map(x=>P(x,1,0)));
 wire(P(24,1,-4),'fault_clear');rep(P(24,1,-3),'south','fault_clear_input');wire(P(24,1,-2),'fault_clear_pad');rep(P(24,1,-1),'south','fault_clear_side');join([-4,-3,-2,-1,0].map(z=>P(24,1,z)));
 route('fault_next_feedback',[[26,1,0],[30,5,0],[30,5,8],[-8,5,8],[-8,5,0],[-4,1,0],[0,1,0]]);
 port('raw_fault','input',[P(19,1,-8)],'Held/observed fault sources. Short events require enough width to be captured; direct raw-fault action blanking remains independent.');port('initialize_clear','input',[P(24,1,-4)],'Actual NEXT clamp; reset runs NEXT-close-CURRENT-close under blanking, never assumes Q initially0.');for(const name of['next_open','current_open'])port(name,'input',[parent.ports[name].bits[0].position],'Qualified physical phase; fault capture must continue even if normal state progress is inhibited.');port('fault_latched','output',[P(17,1,0)],'Retained until actual initialize transfer clears it.');
 return finish('physical_current_next_sticky_fault_offline_candidate',{stored_bits:2,parent_keys:parent.blocks.map(b=>K(b.position)),semantics:'Fnext = (Fcurrent OR raw_fault) AND !initialize_clear; CURRENT receives held NEXT only through the drawn bank link.',missing:['Raw fault OR from all core sources and immediate action inhibition.','Phase qualification, reset acknowledgement and actual closure timing.','This is not an asynchronous pulse stretcher; unqualified short fault pulses may be missed.']});}
export function makePhaseQualifier(){const b=build(),{solid,put,dev,wire,rep,route,join,port,finish,gates}=b;
 const gate=(name,x,z)=>{wire(P(x-2,1,z),name+'_rear');rep(P(x-1,1,z),'east',name+'_rear_driver');dev(P(x,1,z),'comparator',{facing:'west',mode:'subtract'},name);rep(P(x+1,1,z),'east',name+'_out_driver');wire(P(x+2,1,z),name+'_out');wire(P(x,1,z-2),name+'_mask');rep(P(x,1,z-1),'south',name+'_mask_driver');join([x-2,x-1,x,x+1,x+2].map(x=>P(x,1,z)));join([z-2,z-1,z].map(z=>P(x,1,z)));const g={name,center:P(x,1,z),rear:P(x-2,1,z),mask:P(x,1,z-2),out:P(x+2,1,z)};gates.push(g);return g;};
 const reset=gate('run_without_reset',0,0),fault=gate('run_without_fault',20,0),init=gate('run_without_initialize',40,0),next=gate('next_phase',60,16),current=gate('current_phase',80,16),action=gate('normal_action',60,40),decoded=gate('decoded_action',80,40);
 route('run1',[[2,1,0],[18,1,0]]);route('run2',[[22,1,0],[38,1,0]]);route('run_to_bank_isolator',[[42,1,0],[46,1,0]]);rep(P(47,1,0),'east','run_bank_or_isolate');wire(P(48,1,0),'run_bank_or_pad');join([P(46,1,0),P(47,1,0),P(48,1,0)]);route('run_to_bank_or',[[48,1,0],[50,1,0]]);
 wire(P(40,1,-8),'initialize');rep(P(40,1,-7),'south','initialize_normalize');wire(P(40,1,-6),'initialize_pad');join([P(40,1,-8),P(40,1,-7),P(40,1,-6)]);route('initialize_to_run_mask',[[40,1,-6],[40,1,-2]]);rep(P(41,1,-6),'east','initialize_bank_branch');wire(P(42,1,-6),'initialize_bank_pad');join([P(40,1,-6),P(41,1,-6),P(42,1,-6)]);route('initialize_to_bank_or',[[42,1,-6],[50,1,-6],[50,1,-2]]);rep(P(50,1,-1),'south','initialize_bank_merge');join([P(50,1,-2),P(50,1,-1),P(50,1,0)]);
 for(const[x,name]of[[44,'not_run'],[50,'not_bank_enable']]){rep(P(x,1,1),'south',name+'_input');solid(P(x,1,2),name+'_support');solid(P(x,0,2),name+'_floor');put(P(x,1,3),'redstone_wall_torch',{facing:'south'},name);rep(P(x,1,4),'south',name+'_normalize');wire(P(x,1,5),name+'_pad');join([0,1,2].map(z=>P(x,1,z)));join([3,4,5].map(z=>P(x,1,z)));}
 route('not_bank_enable_rail',[[50,1,5],[50,1,6],[80,1,6]]);for(const x of[60,80]){rep(P(x,1,7),'south','bank_mask_branch');wire(P(x,1,8),'bank_mask_pad');join([P(x,1,6),P(x,1,7),P(x,1,8)]);route('bank_mask_'+x,[[x,1,8],[x,1,14]]);}
 route('not_run_to_action',[[44,1,5],[44,1,32],[60,1,32],[60,1,38]]);
 rep(P(58,1,17),'south','phase_a_action_branch');wire(P(58,1,18),'phase_a_action_pad');join([P(58,1,16),P(58,1,17),P(58,1,18)]);route('phase_a_to_action',[[58,1,18],[84,1,18],[84,1,44],[58,1,44],[58,1,40]]);route('action_to_decode_gate',[[62,1,40],[78,1,40]]);
 wire(P(80,1,28),'decode_valid');rep(P(80,1,29),'south','decode_valid_input');solid(P(80,1,30),'decode_valid_support');solid(P(80,0,30),'decode_valid_floor');put(P(80,1,31),'redstone_wall_torch',{facing:'south'},'decode_invalid');wire(P(80,1,32),'decode_invalid_pad');rep(P(80,1,33),'south','decode_invalid_normalize');wire(P(80,1,34),'decode_invalid_wire');join([28,29,30].map(z=>P(80,1,z)));join([31,32,33,34].map(z=>P(80,1,z)));route('decode_mask',[[80,1,34],[80,1,38]]);
 for(const[name,p]of[['normal_permit',reset.rear],['reset_request',reset.mask],['fault_any',fault.mask],['initialize',P(40,1,-8)],['phase_a',next.rear],['phase_b',current.rear],['decode_valid',P(80,1,28)]])port(name,'input',[p],'Held active-high physical source; actual propagation/nonoverlap remains a phase producer contract.');for(const[name,p]of[['next_open',next.out],['current_open',current.out],['action_window',decoded.out]])port(name,'output',[p],'Positive isolated terminal; action_window still needs instruction/state/lane qualification, not a direct write strobe.');
 return finish('physical_core_local_phase_qualification_offline_candidate',{semantics:{run:'normal_permit && !reset_request && !fault_any && !initialize',bank_enable:'initialize || run',next_open:'phase_a && bank_enable',current_open:'phase_b && bank_enable',action_window:'phase_a && run && decode_valid'},reset_contract:'Raw reset closes architectural action; initialization overrides internal bank eligibility so the shared cadence can still clear state. Never tie raw reset to oscillator inhibit. Fault bank capture uses its own qualified cadence, not these fault-stalled core-state OPEN outputs.',missing:['Actual phase producer and every external permit/fault/valid route.','Guaranteed nonoverlap/closure at real bank locks under attached fanout.','Per-state/per-op/per-lane architectural action gates and initialization controller.']});}
export function checkMap(d){const map=new Map(d.blocks.map(b=>[K(b.position),b])),parent=new Set(d.parent_keys??[]),allowed=new Set(d.edges.map(e=>[K(e.from),K(e.to)].sort().join('|')));assert.equal(map.size,d.blocks.length);let supports=0,contacts=0,sides=0;
 for(const b of d.blocks){if(b.block.id.endsWith('_concrete'))continue;let p=P(b.position.x,b.position.y-1,b.position.z);if(b.block.id==='minecraft:redstone_wall_torch'){const[x,z]=V[b.block.properties.facing];p=P(b.position.x-x,b.position.y,b.position.z-z);}assert.equal(map.get(K(p))?.block.id,'minecraft:light_gray_concrete','support '+K(b.position));supports++;}
 for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))for(const[x,z]of Object.values(V))for(const dy of[-1,0,1]){const p=P(b.position.x+x,b.position.y+dy,b.position.z+z),o=map.get(K(p));if(!o||o.block.id.endsWith('_concrete'))continue;if(parent.has(K(b.position))&&parent.has(K(p)))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&map.has(K(P(b.position.x,b.position.y+1,b.position.z))))continue;if(dy===-1&&map.has(K(P(p.x,p.y+1,p.z))))continue;assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign dust '+K(b.position)+' '+K(p));contacts++;}
 for(const b of d.blocks.filter(b=>['minecraft:repeater','minecraft:comparator'].includes(b.block.id))){const dir=Object.keys(F).find(d=>F[d]===b.block.properties.facing),[dx,dz]=V[dir];for(const[x,z]of[[dz,dx],[-dz,-dx]]){const p=P(b.position.x+x,b.position.y,b.position.z+z),o=map.get(K(p));if(o&&['minecraft:repeater','minecraft:comparator'].includes(o.block.id)&&!(parent.has(K(b.position))&&parent.has(K(p))))assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign diode side');sides++;}}
 return{blocks:d.blocks.length,support_checks:supports,dust_contacts:contacts,diode_side_faces:sides};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const all={lane_join:makeLaneJoin(),sticky_fault:makeStickyFault(),phase_qualifier:makePhaseQualifier()},checks={};for(const[name,d]of Object.entries(all)){checks[name]=checkMap(d);const u=new URL(name+'.json',import.meta.url);if(process.argv.includes('--check'))assert.deepEqual(JSON.parse(readFileSync(u)),d);else writeFileSync(u,JSON.stringify(d)+'\n');}console.log(JSON.stringify(checks,null,2));}
