// Static settled power on actual placed diode/dust/route blocks. No live answers.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),gate=d.gate_body,K=p=>`${p.x},${p.y},${p.z}`,W='minecraft:redstone_wire',R='minecraft:repeater',map=new Map(d.blocks.map(b=>[K(b.position),b.block])),rows=d.connections.filter(c=>c.name!=='qualified_A_to_request_OPEN'),a=rows.find(c=>c.name==='REQUEST_START_to_request_OR'),b=rows.find(c=>c.name==='WAIT_ACK_to_request_OR'),out=rows.find(c=>c.name==='request_OR_to_request_data'),nodes=new Map;
for(const cell of gate.cells)if(active(cell.block))nodes.set(K(cell.position),cell.position);for(const c of rows)for(const p of c.path)nodes.set(K(p),p);
function solve(A,B){const seeds=new Map([[K(a.actual_source),A?a.source_high:0],[K(b.actual_source),B?b.source_high:0]]),values=new Map([...nodes.keys()].map(k=>[k,0]));for(const[k,v]of seeds)values.set(k,v);let rounds=0;for(;;){let changed=false;const next=new Map(values);for(const[k,p]of nodes){if(seeds.has(k))continue;const block=map.get(k);assert([W,R].includes(block.id),'Unexpected logic in OR route '+k);let value=0;for(const q of inputs(map,p)){const v=values.get(K(q))??0;value=Math.max(value,block.id===R?(v>0?15:0):Math.max(0,v-Number(map.get(K(q))?.id===W)));}if(value!==values.get(k)){next.set(k,value);changed=true;}}for(const[k,v]of next)values.set(k,v);rounds++;assert(rounds<5000,'Did not settle');if(!changed)break;}return{values,rounds};}
const cases=[];for(let A=0;A<2;A++)for(let B=0;B<2;B++){const r=solve(A,B),wanted=A||B?15:0;assert.equal(r.values.get(K(gate.ports.output)),wanted,'Gate truth');assert.equal(r.values.get(K(out.destination)),wanted,'End-to-end request D truth');assert.equal(r.values.get(K(gate.ports.request_start)),A?15:0,'Input A backpower');assert.equal(r.values.get(K(gate.ports.wait_ack)),B?15:0,'Input B backpower');cases.push({REQUEST_START:A,WAIT_ACK:B,gate_output:r.values.get(K(gate.ports.output)),request_D:r.values.get(K(out.destination)),settled_relaxation_rounds:r.rounds,rounds_are_not_game_ticks:true});}
const negatives=[];for(const[p,A,B]of[[gate.diodes[0],1,0],[gate.diodes[1],0,1],[gate.output_buffer,1,0]]){const old=map.get(K(p));map.set(K(p),{...old,properties:{...old.properties,facing:'south'}});const r=solve(A,B);assert.notEqual(r.values.get(K(out.destination)),15,'Reversed diode did not break expected case');map.set(K(p),old);negatives.push({position:p,mutation:'reverse_actual_OR_repeater',case:[A,B],result:'wrong_request_D_rejected'});}
const arrivals=read('arrival-obligations.json'),byName=new Map(arrivals.routes.map(r=>[r.name,r])),inputToD=[a,b].map(c=>({source:c.name,nominal_input_transport_ticks:byName.get(c.name).nominal_origin_to_receiver_ticks,gate_repeater_ticks:4,output_transport_ticks:byName.get(out.name).nominal_origin_to_receiver_ticks,nominal_source_to_request_D_ticks:byName.get(c.name).nominal_origin_to_receiver_ticks+4+byName.get(out.name).nominal_origin_to_receiver_ticks}));
const report={status:'actual_new_request_OR_and_drawn_data_paths_static_truth_power_isolation_passed',gate_cells:gate.cells.length,active_gate_cells:gate.cells.filter(c=>active(c.block)).length,truth_cases:cases,negative_mutations:negatives,nominal_source_to_D:inputToD,OPEN_nominal_origin_to_port_ticks:byName.get('qualified_A_to_request_OPEN').nominal_origin_to_receiver_ticks,assumptions:['Actual owner source taps are clamped to their declared stable high/low values. Upstream owner-state one-hot behavior, capture and cold initialization are not established here.','Settled relaxation rounds are an offline graph algorithm, not time or Minecraft execution. No host code supplies running state or request values.','Two original shared-OR metadata entries are implemented by one actual isolated diode OR, never two independent drivers of D.','Request OPEN now has real qualified A geometry, but complete setup/hold, pulse width, request withdrawal, ACK sampling/release and cold timing remain mandatory.'],complete_core:false,native_acceptance:false};writeFileSync(new URL('gate-checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,assumptions:undefined},null,2));
