import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,E=(a,b)=>K(a)+'>'+K(b),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),W='minecraft:redstone_wire',R='minecraft:repeater',S='minecraft:light_gray_concrete',base=read('../commit-owner-connected-v1/design.json'),ep=read('../commit-owner-connected-v1/endpoint-map.json'),world=new Map(base.blocks.map(b=>[K(b.position),b.block]));
function body(origin){const cells=[],at=(x,z)=>A(origin,P(x,0,z));function put(x,z,r=false){const p=at(x,z);cells.push({position:P(p.x,p.y-1,p.z),block:{id:S},part:'owner_request_OR_body'},{position:p,block:r?{id:R,properties:{facing:'north',delay:'1'}}:{id:W},part:'owner_request_OR_body'});}for(const x of[0,4]){put(x,-3);put(x,-2,true);put(x,-1);}for(let x=0;x<=4;x++)put(x,0);put(2,1,true);put(2,2);return{cells,ports:{request_start:at(0,-3),wait_ack:at(4,-3),output:at(2,2)},diodes:[at(0,-2),at(4,-2)],output_buffer:at(2,1)};}
function tryPlace(g){if(g.cells.some(b=>world.has(K(b.position))))return false;const isolated=new Map(g.cells.map(b=>[K(b.position),b.block])),around=new Map;for(const b of g.cells)for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++){if(Math.abs(x)+Math.abs(y)+Math.abs(z)>3)continue;const p=A(b.position,P(x,y,z));if(active(world.get(K(p))))around.set(K(p),p);}const expected=new Set;for(const p of around.values())for(const q of inputs(world,p))expected.add(E(q,p));for(const b of g.cells){if(active(b.block))for(const q of inputs(isolated,b.position))expected.add(E(q,b.position));world.set(K(b.position),b.block);}for(const b of g.cells)if(active(b.block))around.set(K(b.position),b.position);const actual=new Set;for(const p of around.values())for(const q of inputs(world,p))actual.add(E(q,p));for(const b of g.cells)world.delete(K(b.position));return expected.size===actual.size&&[...expected].every(e=>actual.has(e));}
let gate;outer:for(const y of[286,290,282,294,278])for(const z of[380,390,370,400,360])for(const x of[320,330,310,340,300]){const g=body(P(x,y,z));if(tryPlace(g)){gate=g;break outer;}}assert(gate,'No isolated OR placement');for(const b of gate.cells)world.set(K(b.position),b.block);const bodyEdges=gate.cells.filter(b=>active(b.block)).flatMap(b=>inputs(world,b.position).map(q=>({from:q,to:b.position,body:'owner_request_OR_body'})));
const originalInterfaces={request_start:P(667,225,-420),wait_ack:P(667,233,-420),output:P(668,250,-420)},replacement_interface_map=Object.fromEntries(Object.entries(originalInterfaces).map(([name,p])=>[K(p),{position:gate.ports[name],body:'owner_request_OR_body',mapping_kind:'function_preserving_interface_replacement_not_cell_translation'}]));
const core=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H))),oldWorld=new Map(core.blocks.map(b=>[K(b.position),b.block])),claims=new Map(Object.entries(ep.mapping).map(([k,v])=>[k,v.body]));for(const b of core.blocks){const p=b.position;if(p.x===668&&p.z===-420&&p.y>=224&&p.y<=250||p.x===667&&p.z===-420&&[224,225,232,233].includes(p.y))claims.set(K(p),'owner_request_OR_body');}
function trace(target){const queue=[{position:target,parity:0}],seen=new Set([K(target)+':0']),found=new Map;let torches=0;for(let i=0;i<queue.length;i++)for(const q of inputs(oldWorld,queue[i].position)){const b=oldWorld.get(K(q)),inv=b.id.includes('torch'),parity=(queue[i].parity+Number(inv))&1,key=K(q)+':'+parity;if(seen.has(key))continue;seen.add(key);if(claims.has(K(q))){found.set(key,{position:q,parity});continue;}assert([W,R,'minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id));if(inv){assert.equal(inputs(oldWorld,q).length,1);torches++;}queue.push({position:q,parity});}return{found:[...found.values()],visited:seen.size,torches};}
const specs=[['REQUEST_START_to_request_OR',P(614,225,-394),originalInterfaces.request_start,ep.mapping[K(P(614,225,-394))].position,gate.ports.request_start,'commit_owner_intents_5','owner_request_OR_body'],['WAIT_ACK_to_request_OR',P(614,233,-394),originalInterfaces.wait_ack,ep.mapping[K(P(614,233,-394))].position,gate.ports.wait_ack,'commit_owner_intents_5','owner_request_OR_body'],['request_OR_to_request_data',originalInterfaces.output,P(640,250,-320),gate.ports.output,ep.mapping[K(P(640,250,-320))].position,'owner_request_OR_body','commit_owner_intents_14']];
specs.push(['qualified_A_to_request_OPEN',P(-70,5,16),P(640,249,-317),ep.mapping[K(P(-70,5,16))].position,ep.mapping[K(P(640,249,-317))].position,'front_core_fetch_intents_0','commit_owner_intents_14']);
specs.unshift(specs.pop());
const connections=specs.map(([name,os,od,source,destination,source_body,target_body])=>{const t=trace(od);assert.deepEqual(t.found,[{position:os,parity:0}],name);return{name,original_source:os,original_destination:od,source,destination,source_body,target_body,actual_reference_upstream:t.found,upstream_transport_nodes:t.visited,unary_torch_stages:t.torches};});
const allCuts=[];for(const b of core.blocks)if(active(b.block)){const target=claims.get(K(b.position));for(const q of inputs(oldWorld,b.position)){const source=claims.get(K(q));if((source||target)&&source!==target)allCuts.push({from:q,to:b.position,source_body:source??null,target_body:target??null});}}const priorSet=new Set(ep.cuts.map(c=>E(c.from,c.to))),bindings=connections.map(c=>{const source=allCuts.filter(e=>K(e.from)===K(c.original_source)),receiver=allCuts.filter(e=>K(e.to)===K(c.original_destination));assert(source.length&&receiver.length);return{name:c.name,original_source:c.original_source,original_receiver:c.original_destination,source_boundary_edges:source.map(e=>({...e,in_982_shared_island_ledger:priorSet.has(E(e.from,e.to))})),receiver_boundary_edges:receiver.map(e=>({...e,in_982_shared_island_ledger:priorSet.has(E(e.from,e.to))})),actual_transported_source_count:1,transported_polarity:'positive',full_source_fanout_closed:false};});
const gateOut={status:'actual_positive_repeater_dust_OR_body_drawn',...gate,edges:bodyEdges,original_interfaces:originalInterfaces,replacement_interface_map,source_contract:read('../commit-owner-connected-v1/qualification-obligations.json').shared_request_OR,gate_truth_requires_separate_check:true,phase_OPEN_requires_separate_route:true,complete_core:false,native_acceptance:false};writeFileSync(new URL('gate.json',H),JSON.stringify(gateOut,null,2)+'\n');
writeFileSync(new URL('body-design.json',H),JSON.stringify({...base,blocks:[...base.blocks,...gate.cells],gate_body:gateOut,metrics:{...base.metrics,cells:base.blocks.length+gate.cells.length,parent_cells:base.blocks.length,logic_body_additions:gate.cells.length,new_transport_cells:0}})+'\n');writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({mapping:ep.mapping,replacement_interface_map,cuts:ep.cuts,connections,prior_qualification_obligations:'../commit-owner-connected-v1/qualification-obligations.json',complete_core:false,native_acceptance:false})+'\n');writeFileSync(new URL('exact-cut-bindings.json',H),JSON.stringify({status:'selected_actual_source_and_receiver_boundary_edges_bound',broader_mapped_body_directed_cut_count:allCuts.length,retained_original_shared_island_cuts:ep.cuts.length,bindings,all_mapped_body_cuts:allCuts,complete_core:false,native_acceptance:false},null,2)+'\n');console.log(JSON.stringify({gate_cells:gate.cells.length,gate_ports:gate.ports,body_dependencies:bodyEdges.length,connections,boundary_cuts:allCuts.length}));
