// New connected local admission derivative. Offline only; all routes are counted.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';import{materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';import{makeStateBank}from'../../../hardware/full-gpu-state-bank.mjs';import{makeControlMatrix}from'./logic/matrix.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),sha=n=>createHash('sha256').update(readFileSync(new URL(n,import.meta.url))).digest('hex'),W='minecraft:redstone_wire';
export function makeAluAdmission({plan=false}={}){
 assert.equal(sha('../alu-core-connected-v1/source-manifest.json'),'d58c11560f6154a218d13db80f4a2383c0672c853ea39274336603b140761881');
 const parent=read('../alu-core-connected-v1/design.json'),map=new Map(parent.blocks.map(v=>[K(v.position),{...v,part:'core_parent'}])),edges=[],routes=[],connections=[],components=[];let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to});
 function insert(name,d,t){const q=materializeInstance(d,{id:name,translation:t});for(const v of q.blocks){assert(!map.has(K(v.position)),'Component overlap '+name+' '+K(v.position));map.set(K(v.position),{...v,part:name+'_parent'});}for(const e of d.edges??[])edges.push({from:P(e.from.x+t.x,e.from.y+t.y,e.from.z+t.z),to:P(e.to.x+t.x,e.to.y+t.y,e.to.z+t.z)});components.push({name,blocks:d.blocks.length,translation:t});return q;}
 const logic=insert('admission_logic',makeControlMatrix(),P(1170,250,-200)),select=insert('switch_pair',makeStateBank({width:1}),P(1210,230,-170)),admit=insert('admit_pair',makeStateBank({width:1}),P(1250,230,-170));
 function put(p,id,properties){const block={id:'minecraft:'+id,...properties?{properties}:{}},o=at(p);if(o){assert.equal(id,'light_gray_concrete','Collision '+part+' '+K(p)+' '+o.part);assert.deepEqual(o.block,block,'Support collision '+part+' '+K(p)+' '+o.part);return;}map.set(K(p),{position:p,block,part});}
 const solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'});
 const cacheURL=new URL('routes.json',import.meta.url),cache=existsSync(cacheURL)?read('routes.json'):{},pending=[],reserved=[],step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),reserve=(s,sd,d,ad)=>[...Array.from({length:18},(_,i)=>step(s,sd,i+2)),...Array.from({length:18},(_,i)=>step(d,ad,-i-2))];
 function draw(name,source,sd,destination,ad,stubs=false){part=name;assert.equal(at(source)?.block.id,W,'source '+name);assert.equal(at(destination)?.block.id,W,'destination '+name);const first=step(source,sd),start=step(source,sd,2),last=step(destination,ad,-1),end=step(destination,ad,-2);if(stubs){rep(first,sd);wire(start);rep(last,ad);wire(end);edge(source,first);edge(first,start);edge(end,last);edge(last,destination);return;}let path=cache[name]?.path;if(!path){assert(plan,'Missing route '+name);const ignore=[...reserve(source,sd,destination,ad),first,start,last,end,...[first,start,last,end].map(p=>P(p.x,p.y-1,p.z))],forbidden=[first,last].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![source,start,end,destination].some(q=>K(p)===K(q))),r=searchPath(map,start,end,{ignore,reserved,forbidden});path=r.path;cache[name]={source,destination,path,expanded:r.expanded};writeFileSync(cacheURL,JSON.stringify(cache)+'\n');console.error(name+': '+path.length+' / '+r.expanded);}assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i)){const dir=Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source,tap:first,destination,arrival:last});}
 const changes=[],scanPorts=[],normalMaskPorts=[],scanMaskPorts=[],columns=[];
 for(const [i,x,z]of[[0,1398,0],[1,1414,0],[2,1398,12],[3,1414,12],[4,1422,0]]){
  const p=P(x,-37,z),normal=P(1666,235+4*i,120),v=at(normal);assert.equal(v?.block.id,'minecraft:repeater');const next={id:'minecraft:comparator',properties:{facing:v.block.properties.facing,mode:'subtract'}};changes.push({position:normal,from:v.block,to:next});v.block=next;v.part='normal_decoder_mask_'+i;edge(P(1665,normal.y,120),normal);edge(normal,P(1667,normal.y,120));
  part='scan_decoder_gate_'+i;const side=[1,1,1,1,1][i],gate=P(x,-46,z-3),input=P(x,-46,z-5),sm=P(x+2*side,-46,z-3),nm=P(normal.x,normal.y,122);
  wire(input);rep(P(x,-46,z-4),'south');dev(gate,'comparator',{facing:'north',mode:'subtract'});wire(P(x,-46,z-2));rep(P(x,-46,z-1),'south');for(let j=5;j>0;j--)edge(P(x,-46,z-j),P(x,-46,z-j+1));
  for(let y=-46;y<=-39;y++)put(P(x,y,z),y%2===0?'light_gray_concrete':'redstone_torch');assert.equal(at(P(x,-38,z))?.block.id,'minecraft:light_gray_concrete');for(let y=-46;y<-37;y++)edge(P(x,y,z),P(x,y+1,z));columns.push({name:'positive_scan_injection_'+i,x,z,bottom:-46,top:-38,output_y:-37});
  wire(sm);rep(P(x+side,-46,z-3),side>0?'west':'east');edge(sm,P(x+side,-46,z-3));edge(P(x+side,-46,z-3),gate);
  wire(nm);rep(P(normal.x,normal.y,121),'north');edge(nm,P(normal.x,normal.y,121));edge(P(normal.x,normal.y,121),normal);
  scanPorts.push(input);scanMaskPorts.push(sm);normalMaskPorts.push(nm);
 }
 part='held_request_admission';const requestMask=P(1402,-37,10),requestRear=P(1401,-37,10),requestMaskInput=P(1402,-37,12);
 for(const [p,to]of[[requestMask,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}}],[requestRear,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}}]]){const v=at(p);assert(v);changes.push({position:p,from:v.block,to});v.block=to;v.part=part;}
 wire(requestMaskInput);rep(P(1402,-37,11),'north');edge(requestMaskInput,P(1402,-37,11));edge(P(1402,-37,11),requestMask);edge(P(1400,-37,10),requestRear);edge(requestRear,requestMask);edge(requestMask,P(1403,-37,10));
 const port=(d,n)=>d.ports[n].bits[0].position,L=n=>port(logic,n);
 pending.push(['shared_raw_A_to_local_guard',P(-82,-4,14),'east',L('raw_A'),'south'],['shared_initialize_to_local_guard',P(-100,-4,-10),'east',L('initialize'),'south'],['shared_scan_ready_to_local_guard',P(280,231,-204),'north',L('scan_ready'),'south']);
 pending.push(['held_switch_to_logic',port(select,'state'),'east',L('selected'),'south'],['held_admitted_to_logic',port(admit,'state'),'east',L('admitted'),'south'],['local_switch_data',L('select_data'),'south',port(select,'next_data'),'east'],['local_admission_data',L('admit_data'),'south',port(admit,'next_data'),'east']);
 pending.push(['raw_A_to_switch_next',L('raw_A'),'south',port(select,'next_open'),'north'],['raw_A_to_admit_next',port(select,'next_open'),'west',port(admit,'next_open'),'north']);
 pending.push(['raw_B_to_switch_current',P(-62,-4,14),'east',port(select,'current_open'),'north'],['raw_B_to_admit_current',port(select,'current_open'),'west',port(admit,'current_open'),'north']);
 pending.push(['local_A_to_controller_NEXT',port(admit,'next_open'),'west',P(1390,234,-27),'south'],['local_B_to_controller_CURRENT',port(admit,'current_open'),'west',P(1404,234,-27),'south']);
 pending.push(['RESET_row0_to_guard',P(2072,230,-216),'north',L('reset_row0'),'south'],['RESET_row1_to_guard',P(1564,218,2),'east',L('reset_row1'),'south'],['reset_request_to_guard',P(1422,-37,13),'east',L('reset_request'),'south'],['enabled_fault_to_guard',P(1428,-37,17),'west',L('any_fault'),'south']);
 pending.push(['qualified_A_to_controller',L('qualified_action_A'),'south',P(1376,218,-14),'south'],['held_initialize_to_controller',L('initialize_hold'),'south',P(1588,302,30),'east']);
 pending.push(['actual_IDLE_to_local_guard',P(1415,-9,8),'east',L('idle'),'south'],['local_request_admission_mask',L('request_inhibit'),'south',requestMaskInput,'west']);
 for(let i=0;i<5;i++)pending.push(['shared_scan_bit_'+i,P(317,234+8*i,-248),'north',scanPorts[i],'south']);
 let selectedSource=L('selected'),notSelectedSource=L('scan_owns_decode');
 for(let i=0;i<5;i++){pending.push(['local_switch_masks_scan_'+i,selectedSource,i===4?'east':'south',scanMaskPorts[i],'south']);selectedSource=scanMaskPorts[i];pending.push(['local_switch_masks_normal_'+i,notSelectedSource,'south',normalMaskPorts[i],'east']);notSelectedSource=normalMaskPorts[i];}
 for(const n of ['actual_IDLE_to_local_guard','enabled_fault_to_guard'])pending.unshift(...pending.splice(pending.findIndex(v=>v[0]===n),1));
 for(const[,s,sd,d,ad]of pending)reserved.push(...reserve(s,sd,d,ad));for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=blocks.reduce((n,v)=>Math.min(n,v.position[a]),Infinity);box.to[a]=blocks.reduce((n,v)=>Math.max(n,v.position[a]),-Infinity);}
 return{status:'offline_local_ALU_guard_retained_admission_and_macro_scan_connected',blocks,box,ports:{...parent.ports,alu_startup:{logic:logic.ports,switch:select.ports,admission:admit.ports}},edges,routes,connections,components,columns,changes,requestMask,requestRear,requestMaskInput,scanPorts,normalMaskPorts,scanMaskPorts,metrics:{blocks:blocks.length,parent_blocks:parent.blocks.length,added_blocks:blocks.length-parent.blocks.length,connections:connections.length,new_retained_bits:4,retained_bits:880},native_calls:0,native_acceptance:false,missing:['First NEXT/CURRENT after conditioning, all decoder return settling and global architectural admission remain unproved.','Global normal_permit remains an explicit all-required-conditioning input.','Phase widths, local closure, far scan dwell and switch-back settling are unmeasured.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeAluAdmission({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
