import{makeRegisterDataSelector}from'../../../../hardware/full-gpu-register-data-selector.mjs';
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeQualifiedRegisterActions}from'../../../../hardware/full-gpu-register-actions-qualified.mjs';import{makeRegisterControllerActions}from'../../../../hardware/full-gpu-register-controller-actions.mjs';import{makeRegisterFileAddressStage}from'../../../../hardware/full-gpu-register-file-address-stage.mjs';import{makeRegisterFileWriteStage}from'../../../../hardware/full-gpu-register-file-write-stage.mjs';import{makeGpuRegisterBank}from'../../../../hardware/full-gpu-register-bank.mjs';import{makeRegisterSharedControl}from'../../../../hardware/full-gpu-register-shared-control.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';import{makeRegisterActions}from'../../../../hardware/full-gpu-register-actions.mjs';import{makeRegisterActionEligibility}from'../../../../hardware/full-gpu-register-action-eligibility.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');

function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0;
 for(const p of d.parents){const source=makeRegisterFileWriteStage({lane:d.lane}),component=materializeInstance(source,{id:p.id,translation:p.origin});for(const v of component.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Changed frozen parent '+K(v.position));inherited++;}}
 for(const v of d.blocks){if(parents.has(v.part)||v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);for(let y=c.bottom;y<=c.top;y++){const id=y===c.top?'redstone_wire':(y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch';assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+id);}}
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);}else assert.equal(v.block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 for(const c of d.connections){const r=at(c.normalizer);assert.equal(r.block.id,'minecraft:repeater');assert.deepEqual(add(c.normalizer,D[r.block.properties.facing]),c.destination,'No direct strength15 output at port');}
 const capacity=possibleStrengths(d);assert.equal(capacity.failed.length,0,'Actual dust capacity failure');assert.equal(d.connections.length,8);for(const c of d.connections){assert.equal(at(c.source)?.block.id,'minecraft:redstone_wire');assert.equal(at(c.destination)?.block.id,'minecraft:redstone_wire');}
 return{preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,actual_dust_capacity:capacity};}
const reports=[];let rejected=0;for(let lane=0;lane<4;lane++){const d=makeRegisterFileAddressStage({lane});assert.deepEqual(d,JSON.parse(readFileSync(new URL('./lane'+lane+'.json',import.meta.url))));reports.push({lane,...d.metrics,...check(d)});if(lane===0)for(const mutate of[c=>{c.blocks.find(v=>K(v.position)==='21,-7,0').block.properties.facing='east';},c=>{c.blocks=c.blocks.filter(v=>K(v.position)==='-6,-2,0');},c=>{c.blocks.find(v=>K(v.position)==='-3,1,0').block.properties.facing='east';},c=>{c.blocks=c.blocks.filter(v=>K(v.position)==='30,-31,-32');}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));rejected++;}}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),result={status:'offline_all_four_file_address_input_derivatives_checks_pass',reports,corruption_refusals:rejected,sources:{generator:sha('../../../../hardware/full-gpu-register-file-address-stage.mjs'),checker:sha('./check.mjs'),lanes:Array.from({length:4},(_,lane)=>sha('./lane'+lane+'.json'))},native_acceptance:false,complete_gpu_layout:false,limits:['Original parent native evidence does not transfer to these new selectors/routes/lane identities.','Every address terminal receives an actual direct repeater output at strength15 when asserted; startup and time-dependent capture remain untested.','External writeback/control/address/block-ID producers and four-file placement/fanout remain missing.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
