import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeRegisterCounterControl}from'../../../../hardware/full-gpu-register-counter-control.mjs';
import{makeRegisterCounterDatapath}from'../../../../hardware/full-gpu-register-counter-datapath.mjs';import{makeCounterGuards}from'../../../../hardware/full-gpu-counter-guards.mjs';import{step}from'../microprogram.mjs';import{makeStateBank}from'../../../../hardware/full-gpu-state-bank.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeRegisterCounterControl();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0,minRear=15;
 const originals=[makeRegisterCounterDatapath(),materializeInstance(makeCounterGuards(),{id:'guard',translation:P(160,0,40)}),materializeInstance(makeStateBank({width:1}),{id:'boot',translation:P(130,0,80)})];
 for(const parent of originals)for(const v of parent.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Parent changed '+K(v.position));inherited++;}

 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){for(let y=c.bottom;y<c.top;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.top,c.z))?.block.id,'minecraft:'+(c.wire_top?'redstone_wire':'redstone_torch'));if(c.wire_top)assert.equal((c.top-c.bottom)%4,1);}
 for(const r of d.routes){let power=15;for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);minRear=Math.min(minRear,power);assert(power>0);power=15;}else{assert.equal(v.block.id,'minecraft:redstone_wire');if(i&&at(r.path[i-1]).block.id==='minecraft:redstone_wire')power--;assert(power>0,'Attenuated '+r.name);}}}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 for(const p of[P(190,1,46),P(153,1,80)])assert.deepEqual(at(p)?.block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});
 return{preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,minimum_route_repeater_input:minRear};}
const checks=check(d);
// Stable decoded microstate controls; initialization overrides next storage.
// No simulator claim: this exhausts the Boolean/ordering mapping of this
// component against the separately reviewed microprogram, not Minecraft ticks.
let cases=0;for(let state=0;state<32;state++)for(let address=0;address<16;address++)for(const boot of[false,true])for(const initialize of[false,true]){
 const sweep=state===4,zero=state===9,is12=address===12,inc=sweep||(zero&&!is12),clear=initialize||state===0||state===5;
 let carry=15,next=0;for(let bit=0;bit<4;bit++){const a=15*(address>>bit&1),ab=Math.max(0,a-carry),ba=Math.max(0,carry-a),sum=(ab||ba)?15:0;carry=Math.max(0,carry-(ba?15:0))?15:0;const hold=Math.max(0,a-15*inc),increment=Math.max(0,sum-15*(!inc)),mux=(hold||increment)?15:0,value=Math.max(0,mux-15*clear);next|=(value?1:0)<<bit;}
 const bootNext=(boot||state===0)&&state!==19&&!initialize,want=step(state,boot,address,{lanes:0,reset:false,req:false,kind:0,rs:0,rt:0,rd:0,reg_write:false});assert.equal(next,initialize?0:want.address);assert.equal(bootNext,initialize?false:want.boot);assert.equal(carry>0,address===15);cases++;
}
let negatives=0;for(const mutate of[c=>{const r=c.routes.find(r=>r.name==='increment_qualified_return');c.blocks=c.blocks.filter(v=>K(v.position)!==K(r.path[20]));},c=>{c.blocks.find(v=>v.part==='guard_lift_1'&&v.block.id==='minecraft:repeater').block.properties.facing='south';},c=>{c.blocks.find(v=>K(v.position)==='153,1,80').block.properties.mode='compare';}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));negatives++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),result={status:'offline_counter_guard_boot_connection_checks_pass',...d.metrics,...checks,microprogram_state_address_boot_init_cases:cases,corruption_refusals:negatives,sources:{generator:sha('../../../../hardware/full-gpu-register-counter-control.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,complete_gpu_layout:false,limits:['Static exact geometry plus settled arithmetic only, not arbitrary game updates or storage initialization.','Microstate and startup control producers, zero/init OR and shared qualified OPEN fanout remain missing.','A smaller incomplete datapath cannot be compared as a complete controller saving.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
