// Extract the actual shared held-IR component from the full selected core.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{readLargeDesign}from'../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),root=new URL('../../../',H),B=new URL('../',H),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pins={};
function read(n){const p=new URL(n,B);pins[fileURLToPath(p).slice(fileURLToPath(root).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');return readLargeDesign(fileURLToPath(p));}
const core=read('compact-core-fault-v1/design.json'),seed=read('control-held-ir-v1/design.json'),world=new Map(core.blocks.map(v=>[K(v.position),v.block])),origin=P(120,0,80),selected=new Set(),changes=[],blocks=[];
for(const b of seed.blocks){const old=add(b.position,origin),block=world.get(K(old));assert(block,'Missing IR body '+K(old));selected.add(K(old));if(JSON.stringify(block)!==JSON.stringify(b.block))changes.push({position:old,before:b.block,actual:block});blocks.push({position:b.position,block,original_position:old,part:b.part,body:'shared/held_ir'});}
const internal=[],crossings=[],near=new Map();for(const b of blocks)for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++){const p=add(b.original_position,P(x,y,z));if(active(world.get(K(p))))near.set(K(p),p);}
for(const[k,p]of near)for(const q of inputs(world,p)){const a=selected.has(K(q)),b=selected.has(k);if(a&&b)internal.push({from:P(q.x-origin.x,q.y-origin.y,q.z-origin.z),to:P(p.x-origin.x,p.y-origin.y,p.z-origin.z)});else if(a||b)crossings.push({from:q,to:p,source_in_ir:a,target_in_ir:b});}
const out={status:'actual_shared_ir_body_and_complete_incident_cut',blocks,ports:seed.ports,origin_in_reference:origin,changes,internal,crossings,body_cells:blocks.length,stored_bits:16,source_sha256:pins,native_acceptance:false};writeFileSync(new URL('shared-ir-body.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({cells:blocks.length,changes,internal:internal.length,crossings:crossings.length}));
