// Exact interaction-only union: preserve each scope's actual independent input map.
import assert from'node:assert/strict';import{writeFileSync}from'node:fs';import{H,K,read,loadFrame,pins}from'./frame.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const frame=loadFrame(),base=frame.world,own=read('delta.json'),program=read('program-global-reservation.json'),memory=read('channel2-address-reservation.json');
const layers=[{name:'ACTIVE',rows:own.new_cells},{name:'program_global_quiet',rows:program.new_cells},{name:'partial_channel2_address',rows:memory.blocks}],world=new Map(base),owner=new Map(),expected=new Map(),deltas=new Map(),P=(x,y,z)=>({x,y,z}),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),solid=b=>b?.id.endsWith('_concrete');
const near=[];for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)near.push(P(x,y,z));
for(const layer of layers){const affected=new Map();for(const r of layer.rows){assert(!base.has(K(r.position)));assert(!owner.has(K(r.position)),'Cross-layer collision '+K(r.position));owner.set(K(r.position),layer.name);for(const o of near){const p=A(r.position,o);if(active(base.get(K(p))))affected.set(K(p),p);}base.set(K(r.position),r.block);}
 for(const r of layer.rows)if(active(r.block))expected.set(K(r.position),inputs(base,r.position).map(K).sort());
 for(const [k,p]of affected){if(owner.has(k))continue;const after=inputs(base,p).map(K);deltas.set(k,[...(deltas.get(k)??[]),{name:layer.name,after}]);}
 for(const r of layer.rows)base.delete(K(r.position));
}
for(const layer of layers)for(const r of layer.rows)world.set(K(r.position),r.block);
let receivers=0,supports=0,inputCount=0,baselineInputs=0,permittedAddedInputs=0;
for(const row of [...frame.rows,...layers.flatMap(v=>v.rows)]){const p=row.position,k=K(p),b=row.block;let support;if(b.id==='minecraft:redstone_wall_torch')support=A(p,D[b.properties.facing]);else if(['minecraft:redstone_wire','minecraft:repeater','minecraft:comparator','minecraft:redstone_torch','minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);if(support){assert(solid(world.get(K(support))),'Missing support '+k);supports++;}if(!active(b))continue;receivers++;const actual=inputs(world,p).map(K).sort();inputCount+=actual.length;
 let wanted=expected.get(k);if(!wanted){const prior=inputs(base,p).map(K);baselineInputs+=prior.length;const changes=deltas.get(k)??[];for(const change of changes)assert(prior.every(q=>change.after.includes(q)),'Independent layer loses baseline input '+k);wanted=[...new Set([...prior,...changes.flatMap(c=>c.after)])].sort();permittedAddedInputs+=wanted.length-prior.length;}assert.deepEqual(actual,wanted,'Cross-scope actual input difference '+k);
}
const report={status:'passed_exact_three_layer_interaction_union',metrics:{accepted_base_cells:base.size,owned_ACTIVE_cells:own.new_cells.length,foreign_program_quiet_reservation_cells:program.new_cells.length,foreign_partial_channel2_reservation_cells:memory.blocks.length,total_cells:world.size,receivers,supports,actual_inputs:inputCount,preserved_baseline_inputs:baselineInputs,independent_layer_added_baseline_inputs:permittedAddedInputs},source_sha256:pins,limits:['This union certifies exact collision/support/input compatibility of each independently evaluated overlay against the frozen accepted base. Only the four ACTIVE deliveries are authored and accepted here.','Program-global cable and partial channel2 rows are exact reservations with no source, routing-completeness, protocol or acceptance credit here. Further changes require a new union.','Whole GPU, state transitions, timing, pulses and native acceptance remain open.']};writeFileSync(new URL('union-checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
