import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeChannelTypedRequest}from'../../../../hardware/memory-layout-channel-typed-request.mjs';import{makeLiteralNetwork}from'../../../../hardware/full-gpu-literal-network.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),d=makeChannelTypedRequest(),saved=read('design.json'),parent=read('../four-bank-service-v1/design.json');assert.equal(hash(d),hash(saved));const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),W='minecraft:redstone_wire',R='minecraft:repeater',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block]));
assert.equal(m.size,d.blocks.length);for(const v of parent.blocks)assert.deepEqual(m.get(K(v.position)),v.block);const logic=makeLiteralNetwork({inputs:['request','type'],outputs:['read_request','write_request'],terms:[{name:'read',literals:{request:1,type:0},bits:[0]},{name:'write',literals:{request:1,type:1},bits:[1]}]});let literalCells=0,descentCells=0;
for(const g of d.gates){const T=p=>P(p.x+g.origin.x,p.y+g.origin.y,p.z+g.origin.z);for(const v of logic.blocks){assert.deepEqual(m.get(K(T(v.position))),v.block);literalCells++;}for(const[n,p]of Object.entries(logic.ports))assert.deepEqual(g.ports[n].bits.map(v=>v.position),p.bits.map(v=>T(v.position)));}
for(const v of d.descents){const local=makeSignalDescent({drop:v.drop}),T=p=>P(p.x+v.origin.x,p.y+v.origin.y,p.z+v.origin.z);for(const b of local.blocks){assert.deepEqual(m.get(K(T(b.position))),b.block);descentCells++;}}
function check(mm){for(const b of d.bindings){assert.deepEqual(mm.get(K(b.driver)),{id:R,properties:{facing:'north',delay:'1'}});assert.deepEqual(b.destination,P(b.driver.x,b.driver.y,b.driver.z+1));assert.equal(mm.get(K(b.destination)).id,W);if(b.kind==='type'){assert.deepEqual(b.source,P(100+128*b.channel,-3+80*b.channel,180));assert.equal(parent.nets[K(b.source)],'payload'+b.channel+'_14');}else assert.deepEqual(b.source,parent.controllers[b.channel].ports.bank_request.positions[0]);}
for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],b=mm.get(K(p));assert(b,'cut '+r.name);if(b.id===R){const v=D[b.properties.facing];assert.deepEqual(r.path[i-1],P(p.x-v.x,p.y,p.z-v.z));assert.deepEqual(r.path[i+1],P(p.x+v.x,p.y,p.z+v.z));}else assert.equal(b.id,W);}for(const c of d.columns)for(let y=c.lo;y<=c.hi;y++)assert.equal(mm.get(K(P(c.x,y,c.z)))?.id,(y-c.lo)%2?'minecraft:redstone_torch':'minecraft:light_gray_concrete');}
check(m);let n=0;for(const b of d.bindings){const k=K(b.driver),old=m.get(k);m.set(k,{id:R,properties:{facing:'south',delay:'1'}});assert.throws(()=>check(m));m.set(k,old);n++;}for(const c of d.columns){const k=K(P(c.x,c.lo+1,c.z)),old=m.get(k);m.delete(k);assert.throws(()=>check(m));m.set(k,old);n++;}for(const r of d.routes){const k=K(r.path[1]),old=m.get(k);m.delete(k);assert.throws(()=>check(m));m.set(k,old);n++;}
let truth=0;for(let request=0;request<2;request++)for(let type=0;type<2;type++){const v={request,type},product=logic.rows.map(row=>{let p=15;for(const g of row.gates){let x=v[g.name],tower=logic.towers.find(t=>t.name===g.name);for(let y=tower.first_y+1;y<row.y;y+=2)x=1-x;const side=g.wanted?1-x:x;p=Math.max(0,p-side*15);}return p>0;});const actual=logic.or_columns.map(c=>{let prev=false;for(let y=1;y<c.output_y;y+=2){const ri=logic.rows.findIndex(r=>r.y===y),inj=ri>=0&&product[ri]&&logic.rows[ri].bits.includes(c.bit);prev=!(prev||inj);}return +prev;});assert.deepEqual(actual,[request&(1-type),request&type]);truth++;}
const out={status:'offline_actual_backend_request_and_retained_type_routes_pass',...d.metrics,exact_regeneration:true,exact_parent_cells:parent.blocks.length,canonical_literal_cells:literalCells,canonical_descent_cells:descentCells,all_input_combinations:truth,corruptions_rejected:n,occupied_chunk_columns:new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`)).size,complete_component_geometry:false,native_acceptance:false};if(process.argv.includes('--save')){writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');writeFileSync(new URL('inventory.json',import.meta.url),JSON.stringify(d.metrics,null,2)+'\n');writeFileSync(new URL('ports.json',import.meta.url),JSON.stringify({typed_bank_request:d.ports.typed_bank_request,sources:d.bindings,remaining:d.missing},null,2)+'\n');}console.log(JSON.stringify(out));
