// Independent bounded endpoint/ownership seam audit, not a second full power simulator.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{decodeSlice}from'../floorplan-v2/obstacles.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),F={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};
const d=read('design.json'),p=read('../floorplan-v2/placement.json'),obs=read('obstacles.json'),m=new Map([...decodeSlice(obs)].map(v=>[K(v.position),v.block])),before=m.size;
for(const v of d.blocks){assert(!m.has(K(v.position)));m.set(K(v.position),v.block);}assert.equal(d.blocks.length,115595);assert.equal(d.connections.length,19);assert.equal(d.borrowed_supports.length,1);
const names=['global_boot','global_raw_reset','global_program_quiet','raw_load_to_global','loader_start_to_gate','loader_reset_to_gate','global_memory_admission_block_to_loader','global_initialized_to_loader','global_channel_quiet','global_drained_to_loader'];
const expected=[];const dc=p.candidates[0].external.find(v=>v.name==='dcr_thread_count');for(let bit=0;bit<8;bit++)expected.push({name:'dcr_thread_count_'+bit,source:dc.driver.positions[bit],destination:dc.sink.positions[bit],source_port:'config.thread_count',destination_port:'thread_count',source_bit:bit,destination_bit:bit});
for(const name of names){const e=p.candidates[0].external.find(v=>v.name===name);assert(e);expected.push({name,source:e.driver.positions[0],destination:e.sink.positions[0],source_port:e.driver.port,destination_port:e.sink.port});}
expected.push({name:'global_cold_initialize_dispatch',source:A(p.components.global.ports.cold_initialize.bits[0].position,P(-1000,-55,550)),destination:A(p.components.dispatch.ports.startup_initialize_request.bits[0].position,P(-1712,55,-600)),source_port:'cold_initialize',destination_port:'startup_initialize_request'});
const byName=new Map(d.connections.map(v=>[v.name,v]));assert.equal(byName.size,19);
for(const e of expected){const c=byName.get(e.name);for(const [k,v]of Object.entries(e))assert.deepEqual(c[k],v,e.name+'/'+k);assert(m.has(K(c.source)));assert.equal(m.get(K(c.destination)).id,'minecraft:redstone_wire');const r=m.get(K(c.normalizer));assert.equal(r.id,'minecraft:repeater');const to=A(c.normalizer,F[r.properties.facing]);if(c.arrival_kind)assert.deepEqual(to,P(-372,12,695));else assert.deepEqual(to,c.destination);}
for(const n of['global_channel_quiet','global_drained_to_loader'])assert.deepEqual(byName.get(n).source,P(1024,68,-375));assert.deepEqual(byName.get('global_memory_admission_block_to_loader').destination,P(-288,17,695));assert.equal(byName.get('raw_load_to_global').destination_port,'raw_load');assert.equal(byName.get('global_initialized_to_loader').source_port,'cold_initialized');
const borrowed=d.borrowed_supports[0];assert.deepEqual(borrowed.source,P(-372,15,695));assert.deepEqual(borrowed.position,P(-372,16,695));assert.deepEqual(borrowed.destination,P(-372,17,695));for(let y=12;y<=16;y++)assert.equal(m.get(K(P(-372,y,695))).id,y%2?'minecraft:redstone_torch':'minecraft:light_gray_concrete');
// Walk declared physical routes, adding only the explicit even-inversion columns.
const graph=new Map();const edge=(a,b)=>{assert(m.has(K(a))&&m.has(K(b)));let s=graph.get(K(a));if(!s)graph.set(K(a),s=new Set());s.add(K(b));};for(const e of d.edges)edge(e.from,e.to);for(const c of d.columns){if(c.borrowed_top){assert.equal((c.output_y-c.bottom-1)%4,0);edge(P(c.x,c.bottom,c.z),P(c.x,c.output_y,c.z));}else{assert.equal((c.output_y-c.bottom)%4,1);edge(P(c.x,c.bottom,c.z),P(c.x,c.output_y,c.z));}}
function reaches(src,dst){const q=[K(src)],seen=new Set(q);for(let i=0;i<q.length;i++){if(q[i]===K(dst))return true;for(const n of graph.get(q[i])??[])if(!seen.has(n)){seen.add(n);q.push(n);}}return false;}
for(const c of d.connections)assert(reaches(c.source,c.destination),'missing declared path '+c.name);
let negatives=0;for(const name of['global_channel_quiet','raw_load_to_global','global_memory_admission_block_to_loader']){const c=structuredClone(byName.get(name));c.source.x++;assert.throws(()=>assert.deepEqual(c.source,expected.find(v=>v.name===name).source));negatives++;}
const report={status:'bounded_offline_master_loader_endpoint_review_pass',exact_connections:19,dcr_bits:8,control_connections:11,baseline_slice_cells:before,new_cells:d.blocks.length,declared_directed_paths:19,positive_underpad_recipients:1,source_identity_negatives:negatives,native_acceptance:false};console.log(JSON.stringify(report));if(process.argv.includes('--save'))writeFileSync(new URL('reviewer-check.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
