import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{screen}from'../control-reset-final-v1/check-interactions.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');
const d=read('design.json'),b=read('../control-reset-final-v1/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(b.blocks.map(v=>[K(v.position),v])),gone=new Map(d.removed.map(v=>[K(v.position),v]));assert.equal(m.size,d.blocks.length);let preserved=0;
for(const v of b.blocks){if(gone.has(K(v.position)))continue;assert.deepEqual(m.get(K(v.position))?.block,v.block,'Unexpected parent change '+K(v.position));preserved++;}assert.deepEqual(d.ports,b.ports);for(const v of d.removed)assert.deepEqual(old.get(K(v.position))?.block,v.block);assert.equal(d.connections.length,24);
// The new two lower/solid-fed taps each have exactly one effective source.
const dirs=[[1,0],[-1,0],[0,1],[0,-1]],F={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},W='minecraft:redstone_wire';function sources(p){const out=[];for(const[x,z]of dirs){let q=P(p.x-x,p.y,p.z-z),v=m.get(K(q));if(v?.block.id===W||['minecraft:repeater','minecraft:comparator'].includes(v?.block.id)&&F[v.block.properties.facing][0]===x&&F[v.block.properties.facing][1]===z)out.push(K(q));}for(const[y,id]of[[-1,'minecraft:redstone_torch'],[1,W]]){const q=P(p.x,p.y+y,p.z);if(m.get(K(q))?.block.id===id)out.push(K(q));}return out.sort();}
assert.deepEqual(sources(P(31,255,44)),['31,256,44']);assert.deepEqual(sources(P(-274,57,-125)),['-275,57,-125']);
// Every preserved old-to-old dust edge must survive the new caps/supports.
let dustEdges=0;const neighbors=(p,world)=>{const out=[];for(const[x,z]of dirs)for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(old.get(K(q))?.block.id!==W||gone.has(K(q)))continue;if(y===1&&world.has(K(P(p.x,p.y+1,p.z))))continue;if(y===-1&&world.has(K(P(q.x,q.y+1,q.z))))continue;out.push(K(q));}return out.sort();};for(const v of b.blocks)if(v.block.id===W&&!gone.has(K(v.position))){const before=neighbors(v.position,old),after=neighbors(v.position,m);assert.deepEqual(after,before,'Changed retained dust shape '+K(v.position));dustEdges+=before.length;}
const r=screen({...d,clear_columns:[],positive_columns:[],terminal_columns:[],lower_taps:[]});const out={status:'author_checked_rerouted_core_only',design_sha256:sha('design.json'),generator_sha256:sha('prepare.mjs'),preserved_parent_cells:preserved,explicit_removed_cells:gone.size,new_or_restored_cells:m.size-preserved,preserved_directed_old_dust_edges:dustEdges,exact_solid_source_sets:2,...r,native_acceptance:false,master_composition_accepted:false};writeFileSync(new URL('core-checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({...out,taps:undefined}));
