import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeStartupScanClock}from'../../../../hardware/full-gpu-startup-scan-clock.mjs';import{makeStateBank}from'../../../../hardware/full-gpu-state-bank.mjs';import{makeRegisterStartupDistribution}from'../../../../hardware/full-gpu-register-startup-distribution.mjs';import{makeRegisterFourFilesBlockControl}from'../../../../hardware/full-gpu-register-four-files-block-control.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const saved=JSON.parse(readFileSync(new URL('./design.json',import.meta.url))),fast=process.argv.includes('--debug');const d=fast?saved:makeRegisterStartupDistribution();assert.deepEqual(d,saved);const frozenRegisters=JSON.parse(readFileSync(new URL('../override-v1/design.json',import.meta.url))),frozenScanner=JSON.parse(readFileSync(new URL('../../startup-scan-v1/clock/design.json',import.meta.url)));const parentCache=new Map();
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0;
 for(const p of d.parents){if(!parentCache.has(p.id)){const source=p.id==='registers'?frozenRegisters:p.id==='admission_pair'?makeStateBank(p.parameters):makeSignalDescent(p.parameters);parentCache.set(p.id,materializeInstance(source,{id:p.id,translation:p.origin}));}const component=parentCache.get(p.id);for(const v of component.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Changed frozen parent '+K(v.position));inherited++;}}
 for(const v of d.blocks){if(!['redstone_wire','repeater','comparator','redstone_torch','redstone_wall_torch'].some(id=>v.block.id==='minecraft:'+id))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);for(let y=c.bottom;y<=c.top;y++){const id=y===c.top?'redstone_wire':(y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch';assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+id);}}


 const base=new Map([...parentCache.values()].flatMap(c=>c.blocks.map(v=>[K(v.position),v])));
 function actualSources(index,p){const got=[];for(const[f,d]of Object.entries(D)){const q=add(p,neg(d)),b=index.get(K(q))?.block;if(b?.id==='minecraft:redstone_wire'||['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&b.properties.facing===f)got.push(K(q));}for(const[dy,id]of[[1,'minecraft:redstone_wire'],[-1,'minecraft:redstone_torch']]){const q=P(p.x,p.y+dy,p.z);if(index.get(K(q))?.block.id===id)got.push(K(q));}return got.sort();}
 let parentTorchSets=0,parentSolidRearSets=0;
 for(const v of base.values()){if(v.block.id==='minecraft:redstone_torch'||v.block.id==='minecraft:redstone_wall_torch'){const q=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):P(v.position.x,v.position.y-1,v.position.z);assert.deepEqual(actualSources(m,q),actualSources(base,q),'Changed parent torch sources '+K(v.position));parentTorchSets++;}if(['minecraft:repeater','minecraft:comparator'].includes(v.block.id)){const q=add(v.position,neg(D[v.block.properties.facing]));if(base.get(K(q))?.block.id==='minecraft:light_gray_concrete'){assert.deepEqual(actualSources(m,q),actualSources(base,q),'Changed parent solid rear '+K(v.position));parentSolidRearSets++;}}}
 let sourceSets=0;for(const col of d.columns){for(let y=col.bottom;y<col.top;y+=2){const p=P(col.x,y,col.z),got=[];for(const [f,delta]of Object.entries(D)){const q=add(p,neg(delta)),b=at(q)?.block;if(b?.id==='minecraft:redstone_wire'||['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&b.properties.facing===f)got.push(K(q));}for(const[dy,id]of[[1,'minecraft:redstone_wire'],[-1,'minecraft:redstone_torch']]){const q=P(p.x,p.y+dy,p.z);if(at(q)?.block.id===id)got.push(K(q));}const expected=y===col.bottom?d.edges.filter(e=>K(e.to)===K(p)).map(e=>K(e.from)):[K(P(p.x,y-1,p.z))];if(y===col.top-1)expected.push(K(P(p.x,col.top,p.z)));assert.deepEqual(got.sort(),expected.sort(),'Foreign actual column source '+K(p));sourceSets++;}}
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);}else assert.equal(v.block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 for(const c of d.connections){const r=at(c.normalizer);assert.equal(r.block.id,'minecraft:repeater');assert.deepEqual(add(c.normalizer,D[r.block.properties.facing]),c.destination,'No direct strength15 output at port');}const capacity=possibleStrengths(d);assert.equal(capacity.failed.length,0,'Actual dust capacity failure');assert.equal(d.connections.length,11);for(const c of d.connections){assert(['minecraft:redstone_wire','minecraft:redstone_torch','minecraft:redstone_block'].includes(at(c.source)?.block.id));assert.equal(at(c.destination)?.block.id,c.role?'minecraft:comparator':'minecraft:redstone_wire');}
 return{unchanged_parent_torch_source_sets:parentTorchSets,unchanged_parent_solid_rear_source_sets:parentSolidRearSets,new_column_source_sets:sourceSets,preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,actual_dust_capacity:capacity};}

function checkAdmission(d){const m=new Map(d.blocks.map(v=>[K(v.position),v.block])),block=(p,id,properties)=>assert.deepEqual(m.get(K(p)),{id:'minecraft:'+id,...(properties?{properties}:{})});
 for(const z of[86,90])block(P(-190,135,z),'comparator',{facing:'north',mode:'subtract'});
 for(const z of[85,88,91])block(P(-190,135,z),'repeater',{facing:'north',delay:'1'});
 for(const z of[86,90])block(P(-189,135,z),'repeater',{facing:'east',delay:'1'});
 for(const[x,y,z]of[[-205,133,84],[-249,131,82]]){block(P(x,y,z),'light_gray_concrete');block(P(x-1,y,z),'repeater',{facing:'west',delay:'1'});block(P(x+1,y,z),'redstone_wall_torch',{facing:'east'});}
 assert.equal(((133-(-86)+1)/2)%2,0,'Phase A torch tap must be positive');assert.equal(((131-(-52)+1)/2)%2,0,'READY torch tap must be positive');
 block(P(377,-110,96),'repeater',{facing:'east',delay:'1'});block(P(376,-110,96),'redstone_wire');block(P(376,-110,91),'repeater',{facing:'north',delay:'1'});block(P(-66,-82,148),'redstone_block');
 let wordCases=0;for(const phase of[0,1])for(const ready of[0,1])for(const admitted of[0,1]){const first=Math.max(0,15*phase-15*(1-admitted));const output=Math.max(0,(first?15:0)-15*(1-ready));assert.equal(Boolean(output),Boolean(phase&&ready&&admitted));assert.equal(Boolean((1-ready)||(1-admitted)),!(ready&&admitted));wordCases++;}
 let traces=0;for(let initial=0;initial<4;initial++)for(const startsB of[false,true]){let next=initial&1,current=(initial>>1)&1;const capture=(phase,ready)=>{if(phase==='A')next=ready;else current=next;return {window:phase==='A'&&ready&&current,clamp:!ready||!current};};const sequence=startsB?['B','A','B']:['A','B'];for(const p of sequence){const observed=capture(p,0);assert(!observed.window&&observed.clamp);}assert.equal(next|current,0);assert.equal(current,0);const firstA=capture('A',1);assert(!firstA.window&&firstA.clamp);capture('B',1);assert.equal(current,1);assert(capture('A',1).window);for(const p of['A','B'])assert(capture(p,0).clamp);traces++;}
 return{settled_window_and_clamp_cases:wordCases,arbitrary_admission_state_ordered_traces:traces,limits:['Ideal ordered capture events only. This does not establish remote timing, transient-free enable or complete startup admission.']};}
const structural=check(d),admission=checkAdmission(d);assert.deepEqual(d.blocks.find(v=>K(v.position)==='-66,-82,148').block,{id:'minecraft:redstone_block'});let rejected=0;for(const mutate of[c=>{c.blocks.find(v=>K(v.position)==='-55,-82,140').block.properties.facing='east';},c=>{const col=c.columns[0];c.blocks=c.blocks.filter(v=>K(v.position)!==K(P(col.x,col.bottom+2,col.z)));},c=>{const r=c.routes.find(r=>r.name==='initialize_return');c.blocks=c.blocks.filter(v=>K(v.position)!==K(r.path[5]));},c=>{c.blocks.find(v=>K(v.position)==='-65,-82,148').block.properties.facing='east';},c=>{c.blocks.find(v=>K(v.position)==='-190,135,90').block.properties.mode='compare';},c=>{c.blocks.find(v=>K(v.position)==='-189,135,86').block.properties.facing='west';}]){const c=structuredClone(d);mutate(c);assert.throws(()=>{check(c);checkAdmission(c);});rejected++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),result={status:fast?'debug_geometry_checks_only_not_reproduction_acceptance':'offline_register_phase_and_cold_clamp_author_checks_pass',...d.metrics,...structural,corruption_refusals:rejected,admission,sources:{generator:sha('../../../../hardware/full-gpu-register-startup-distribution.mjs'),parent:sha('../override-v1/design.json'),scanner:sha('../../startup-scan-v1/clock/design.json'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,complete_gpu_layout:false,limits:['Listed contact/support/possible power checks only, not native timing, startup or full functional correctness.','The retained window and shared phases/clamps have geometry; full admission and native closure/timing remain unproved.']};writeFileSync(new URL(fast?'./debug-checks.json':'./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
