import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeDataOwner} from '../../../../hardware/memory-layout-data-owner.mjs';
const W='minecraft:redstone_wire',P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,S='minecraft:light_gray_concrete',V={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(V),edge=(p,q)=>[K(p),K(q)].sort().join('|');
const d=makeDataOwner();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v.block])),get=p=>m.get(K(p));assert.equal(m.size,d.blocks.length);const rep=(p,f)=>assert.deepEqual(get(p),{id:'minecraft:repeater',properties:{facing:f,delay:'1'}}),cmp=(p,f)=>assert.deepEqual(get(p),{id:'minecraft:comparator',properties:{facing:f,mode:'subtract'}}),allowed=new Set();let supports=0,faces=0;
 for(const v of d.blocks){const p=v.position,b=v.block;if([S,'minecraft:redstone_block'].includes(b.id))continue;let q=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const[dx,dz]=V[b.properties.facing];q=P(p.x+dx,p.y,p.z+dz);}assert.equal(get(q)?.id,S,'support '+K(p));supports++;}
 assert.equal(d.priority.length,36);for(const g of d.priority){cmp(g.gate,'west');rep(g.rear,'west');rep(g.side,'north');assert.equal(g.wanted,g.consumer===g.mask_consumer);allowed.add(edge(g.gate,g.side));if(g.wanted)assert.deepEqual(get(g.inverter),{id:'minecraft:redstone_wall_torch',properties:{facing:'east'}});}
 assert.equal(d.stores.length,23);for(const s of d.stores){const f=s.name==='owner'?'west':'east';rep(s.driver,f);rep(s.storage,f);rep(s.lock,'south');allowed.add(edge(s.driver,s.storage));allowed.add(edge(s.storage,s.lock));assert.equal(s.lock.x,s.storage.x);assert.equal(s.lock.y,s.storage.y);assert.equal(s.lock.z,s.storage.z+1);}
 assert.equal(d.muxes.length,120);for(const q of d.muxes){cmp(q.gate,'east');rep(q.rear,'east');rep(q.mask,'north');allowed.add(edge(q.gate,q.rear));allowed.add(edge(q.gate,q.mask));const p=q.collector;assert.equal(p.y,1+4*q.consumer);assert.equal(get(p)?.id,S);rep(P(59,p.y,p.z),'east');}
 for(let i=0;i<8;i++){const y=1+4*i;rep(P(48,y,0),'west');assert.equal(get(P(49,y,0))?.id,S);assert.deepEqual(get(P(50,y,0)),{id:'minecraft:redstone_wall_torch',properties:{facing:'east'}});rep(P(48,y,3),'south');rep(P(47,y,2),'east');}
 for(let b=0;b<15;b++){const z=8*b+8;assert.equal(get(P(48,32,z+2))?.id,W);for(let i=0;i<8;i++)assert.equal(get(P(64,1+4*i,z-2))?.id,W);for(let y=1;y<=32;y++)assert.equal(get(P(58,y,z))?.id,y%2?S:'minecraft:redstone_torch');rep(P(51,31,z-1),'south');assert.equal(get(P(51,32,z-1))?.id,S);for(let y=31;y<=35;y++)assert.equal(get(P(51,y,z-2))?.id,y%2?S:'minecraft:redstone_torch');rep(P(50,35,z-2),'east');rep(P(49,32,z+2),'west');}
 for(const v of d.blocks){const p=v.position,b=v.block;if([S,'minecraft:redstone_block'].includes(b.id))continue;for(const[dx,dz]of dirs){const q=P(p.x+dx,p.y,p.z+dz),bb=get(q);if(bb&&!([S,'minecraft:redstone_block'].includes(bb.id))&&d.nets[K(p)]!==d.nets[K(q)]){assert(allowed.has(edge(p,q)),'foreign face '+K(p)+' '+K(q));faces++;}if(b.id==='minecraft:redstone_wire')for(const dy of[-1,1]){const q=P(p.x+dx,p.y+dy,p.z+dz);if(get(q)?.id!=='minecraft:redstone_wire'||d.nets[K(p)]===d.nets[K(q)])continue;if(dy>0&&get(P(p.x,p.y+1,p.z))||dy<0&&get(P(q.x,p.y,q.z)))continue;assert.fail('foreign slope '+K(p)+' '+K(q));}}if(['minecraft:repeater','minecraft:comparator'].includes(b.id)){const[dx,dz]=V[b.properties.facing];for(const[sx,sz]of dirs.filter(([x,z])=>x*dx+z*dz===0)){const q=P(p.x+sx,p.y,p.z+sz),bb=get(q);if(!['minecraft:repeater','minecraft:comparator'].includes(bb?.id))continue;const[x,z]=V[bb.properties.facing];if(q.x+x===p.x&&q.z+z===p.z)assert(allowed.has(edge(p,q)),'side source '+K(p));}}}
 assert.equal(faces,644);for(const route of d.routes){assert(route.max_dust_run<=12);for(const p of route.refresh){const i=route.path.findIndex(q=>K(q)===K(p)),[dx,dz]=V[get(p).properties.facing];assert.deepEqual(route.path[i-1],P(p.x-dx,p.y,p.z-dz));assert.deepEqual(route.path[i+1],P(p.x+dx,p.y,p.z+dz));}}
 // Every inverter's attached solid has exactly its intended diode source.
 let inverterSources=0;for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wall_torch')){const p=v.position,[dx,dz]=V[v.block.properties.facing],support=P(p.x+dx,p.y,p.z+dz),sources=[];for(const[x,z]of dirs){const q=P(support.x+x,support.y,support.z+z),b=get(q);if(!['minecraft:repeater','minecraft:comparator'].includes(b?.id))continue;const[a,c]=V[b.properties.facing];if(q.x+a===support.x&&q.z+c===support.z)sources.push(q);}assert.equal(sources.length,1,'inverter support sources '+K(p));inverterSources++;}
 return{support_checks:supports,declared_directed_contact_faces:faces,foreign_dust_steps:0,inverter_single_diode_supports:inverterSources,retained_stores:23};}
const checked=check(d);let negatives=0;function bad(fn){const x=structuredClone(d);fn(x);assert.throws(()=>check(x));negatives++;}
bad(x=>x.blocks.find(v=>K(v.position)==='2,1,0').block.properties.mode='compare');bad(x=>x.blocks.find(v=>K(v.position)==='44,1,1').block.properties.facing='north');bad(x=>x.blocks.find(v=>K(v.position)==='60,1,8').block.properties.facing='west');bad(x=>x.blocks=x.blocks.filter(v=>K(v.position)!=='51,32,7'));bad(x=>x.blocks.find(v=>K(v.position)==='58,32,8').block.id=S);bad(x=>x.blocks.find(v=>K(v.position)==='50,1,0').block.properties.facing='west');bad(x=>x.blocks.find(v=>K(v.position)==='64,1,22').block={id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});bad(x=>x.blocks.find(v=>K(v.position)==='48,32,10').block={id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});
let cases=0;for(let valid=0;valid<256;valid++){const bits=Array.from({length:8},(_,i)=>(valid>>i)&1),grants=Array.from({length:8},(_,i)=>d.priority.filter(g=>g.consumer===i).reduce((v,g)=>v&&(g.wanted?bits[g.mask_consumer]:!bits[g.mask_consumer]),1)),expected=bits.findIndex(Boolean);assert.equal(grants.filter(Boolean).length,expected<0?0:1);for(let i=0;i<8;i++)assert.equal(Number(grants[i]),Number(expected===i));for(let pattern=0;pattern<256;pattern++)for(let field=0;field<15;field++){const actual=d.muxes.filter(q=>q.field===field).some(q=>((pattern>>q.consumer)&1)&&grants[q.consumer]);assert.equal(Number(actual),expected<0?0:(pattern>>expected)&1);cases++;}}
const out={status:'offline_owned_priority_payload_geometry_pass',...d.metrics,...checked,software_priority_payload_bit_cases:cases,negative_cases:negatives,native_acceptance:false,complete_channel:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
