import assert from 'node:assert/strict';
import{readFileSync,writeFileSync}from'node:fs';
import{makeFrontPc}from'./prepare.mjs';import{makePcPaths}from'./pc-paths.mjs';
import{materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
import{possibleStrengths}from'../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(D),pair=(a,b)=>[K(a),K(b)].sort().join('|'),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',diode=b=>['minecraft:repeater','minecraft:comparator'].includes(b?.id),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export function screen(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(Object.keys(d.parents)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,contacts=0,sides=0,rears=0,sets=0;
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;let p=P(v.position.x,v.position.y-1,v.position.z);if(v.block.id==='minecraft:redstone_wall_torch'){const[x,z]=D[v.block.properties.facing];p=P(v.position.x+x,v.position.y,v.position.z+z);}assert.equal(at(p)?.block.id,S,'Support '+K(v.position));supports++;}
 for(const v of d.blocks.filter(v=>v.block.id===W))for(const[x,z]of dirs)for(const dy of[-1,0,1]){const p=P(v.position.x+x,v.position.y+dy,v.position.z+z),b=at(p);if(!b||b.block.id.endsWith('_concrete')||v.part===b.part&&parents.has(v.part))continue;if(dy&&b.block.id!==W)continue;if(dy===1&&at(P(v.position.x,v.position.y+1,v.position.z)))continue;if(dy===-1&&at(P(p.x,p.y+1,p.z)))continue;assert(allowed.has(pair(v.position,p)),'Foreign '+v.part+' '+K(v.position)+' -> '+b.part+' '+K(p));contacts++;}
 for(const v of d.blocks.filter(v=>diode(v.block))){const[x,z]=D[v.block.properties.facing];for(const[dx,dz]of[[z,x],[-z,-x]]){const b=at(P(v.position.x+dx,v.position.y,v.position.z+dz));if(diode(b?.block)&&!(b.part===v.part&&parents.has(v.part)))assert(allowed.has(pair(v.position,b.position)),'Foreign diode side '+K(v.position));sides++;}if(!parents.has(v.part)&&v.block.id==='minecraft:repeater'){const rear=P(v.position.x-x,v.position.y,v.position.z-z),out=P(v.position.x+x,v.position.y,v.position.z+z);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'New diode direction '+K(v.position));rears++;}}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);assert.equal(at(P(c.x,c.top,c.z))?.block.id,W);for(let y=c.bottom;y<c.top;y+=2){const p=P(c.x,y,c.z),got=[];assert.equal(at(p)?.block.id,S);assert.equal(at(P(c.x,y+1,c.z))?.block.id,y+1===c.top?W:'minecraft:redstone_torch');for(const[x,z]of dirs){const q=P(p.x-x,y,p.z-z),b=at(q)?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z]))got.push(K(q));}for(const[dy,id]of[[1,W],[-1,'minecraft:redstone_torch']]){const q=P(c.x,y+dy,c.z);if(at(q)?.block.id===id)got.push(K(q));}
  let entry;if(c.name.startsWith('immediate_source_lift_'))entry=P(c.x+(+c.name.split('_').at(-1)<6?1:-1),c.bottom,c.z);else if(c.name.startsWith('immediate_arrival_lift_'))entry=P(c.x,c.bottom,c.z-1);else entry=P(c.x-1,c.bottom,c.z);
  const want=[K(y===c.bottom?entry:P(c.x,y-1,c.z))];if(y===c.top-1){want.push(K(P(c.x,c.top,c.z)));if(c.name.startsWith('increment_input_lift_'))want.push(K(P(c.x,c.top-1,c.z+(+c.name.split('_').at(-1)<4?1:-1))));}assert.deepEqual(got.sort(),want.sort(),'Column source '+c.name+' '+K(p));sets++;
 }}
 let mediated=0,cross=0;for(const solid of d.blocks.filter(v=>v.block.id===S)){const p=solid.position,src=[],dst=[];for(const[x,z]of dirs){let v=at(P(p.x-x,p.y,p.z-z)),b=v?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z]))src.push(v);v=at(P(p.x+x,p.y,p.z+z));b=v?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z])||b?.id==='minecraft:redstone_wall_torch'&&eq(D[b.properties.facing],[-x,-z]))dst.push(v);}const up=at(P(p.x,p.y+1,p.z)),down=at(P(p.x,p.y-1,p.z));if(up?.block.id===W)src.push(up);if(down?.block.id==='minecraft:redstone_torch')src.push(down);if([W,'minecraft:redstone_torch'].includes(up?.block.id))dst.push(up);if(down?.block.id===W)dst.push(down);for(const a of src)for(const b of dst){if(a===b||a.part===b.part&&parents.has(a.part))continue;mediated++;if(a.part===b.part)continue;cross++;assert.equal(a.part.split('_').at(-1),b.part.split('_').at(-1),'Different-bit solid coupling '+K(p));const names=[a.part,b.part].map(n=>n.replace(/_\d+$/,'')).sort().join('|');assert(['increment_input_lift|increment_input_lift_feed','increment_input_arrive|increment_input_lift','increment_escape|increment_export','pc_increment_lift|pc_increment_lift_feed','immediate_export|immediate_source_lift','immediate_arrival_feed|immediate_arrival_lift','held_immediate|immediate_source_lift'].includes(names),'Unexpected solid coupling '+K(p)+' '+names);}}
 const capacity=possibleStrengths({...d,parents:[...parents].map(id=>({id}))});assert.equal(capacity.failed.length,0,JSON.stringify(capacity.failed));return{supports,listed_contacts:contacts,diode_side_faces:sides,new_directed_repeaters:rears,positive_column_source_sets:sets,conservative_solid_paths:mediated,same_signal_cross_part_solid_paths:cross,...capacity};}
const pc=makePcPaths(),d=makeFrontPc();assert.deepEqual(pc,JSON.parse(readFileSync(new URL('./pc-paths.json',import.meta.url))));assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
const pcCheck=screen(pc),frontCheck=screen(d),m=new Map(d.blocks.map(v=>[K(v.position),v]));let preserved=0;
for(const[name,file,translation]of[['front','../control-front-v1/design.json',P(0,0,0)],['pc_feedback','./pc-paths.json',P(0,240,-12)]])for(const v of materializeInstance(JSON.parse(readFileSync(new URL(file,import.meta.url))),{id:name,translation}).blocks){assert.deepEqual(m.get(K(v.position))?.block,v.block);preserved++;}
for(let b=0;b<8;b++){const c=d.connections[b];assert.equal(c.from_bit,b);assert.equal(c.to_bit,b);assert.equal(c.from,'front.immediate');assert.equal(c.to,'pc_feedback.immediate');assert.deepEqual(c.destination,P(20,249,-4+8*b));assert.equal(d.ports.program_address.bits[b].high_power,15);}
// Functional contract checks exercise actual staged storage obligations only;
// they do not substitute for propagation, memory ownership or OPEN producers.
let stagedCases=0;for(let old=0;old<256;old++)for(const target of[0,old,(old+1)&255,255]){let current=old,next=target;const frozen=next;current=frozen;assert.equal(current,target);assert.equal(next,frozen);stagedCases++;}
let negatives=0;for(const f of[c=>c.blocks.find(v=>K(v.position)==='112,1,-4').block.properties.facing='west',c=>c.blocks.find(v=>K(v.position)==='6,200,-4').block.id=W,c=>c.connections[2].to_bit=3,c=>c.blocks.find(v=>K(v.position)==='19,249,-4').block.properties.facing='east']){const v=structuredClone(d);f(v);assert.throws(()=>{screen(v);for(let i=0;i<8;i++)assert.equal(v.connections[i].to_bit,i);});negatives++;}
const result={status:'author_offline_front_pc_data_routes_pass',...d.metrics,pc_feedback:pcCheck,front_added:frontCheck,preserved_parent_cells:preserved,staged_word_cases:stagedCases,corruptions_refused:negatives,native_acceptance:false,selected_density_layout:false,limits:d.missing};if(process.argv.includes('--save'))writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
