import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync,openSync,writeSync,closeSync}from'node:fs';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{resolve}from'node:path';
import{readLargeDesign}from'../../../hardware/memory-layout-large-json-v2.mjs';import{makeSourcePinHasher}from'../../../scripts/source-pin-hasher.mjs';import{key,position,encode,repeater,findFeedback}from'./dependencies.mjs';
const ROOT=fileURLToPath(new URL('../../../',import.meta.url)),HERE='artifacts/full-gpu-layout-v1/repeater-feedback-census-v1/',audit=makeSourcePinHasher(ROOT),sha=p=>audit.hash(p),local=n=>resolve(ROOT,HERE+n),read=n=>JSON.parse(readFileSync(local(n)));
const cfg=read('config.json'),pins={[HERE+'config.json']:sha(HERE+'config.json')};for(const c of cfg.instances){assert.equal(sha(c.path),c.sha256);pins[c.path]=c.sha256;assert.equal(sha(c.source_manifest),c.source_manifest_sha256);pins[c.source_manifest]=c.source_manifest_sha256;}
const world=new Map(),diodes=[],histogram={},chunkSet=new Set(),box={from:{x:Infinity,y:Infinity,z:Infinity},to:{x:-Infinity,y:-Infinity,z:-Infinity}},instances=[];
if(existsSync(local('packed-world.json'))){const cache=read('packed-world.json');assert.deepEqual(cache.source_sha256,pins);assert.equal(sha(HERE+'packed-world.bin'),cache.binary_sha256);const data=readFileSync(local('packed-world.bin'));assert.equal(data.length,cache.unique_cells*12);for(let i=0;i<data.length;i+=12){const k=data.readUInt32LE(i)+data.readUInt32LE(i+4)*2**32,v=data.readUInt32LE(i+8);world.set(k,v);if(repeater(v&255))diodes.push(k);}Object.assign(histogram,cache.materials);Object.assign(box,cache.box);instances.push(...cache.instances);console.error(JSON.stringify({stage:'cached_complete_reference_loaded',cells:world.size,repeaters:diodes.length}));}
else{for(let ci=0;ci<cfg.instances.length;ci++){const c=cfg.instances[ci];let d=readLargeDesign(resolve(ROOT,c.path));let count=0;for(const row of d.blocks){const p={x:row.position.x+c.translation.x,y:row.position.y+c.translation.y,z:row.position.z+c.translation.z},k=key(p);assert(!world.has(k),'Selected physical overlap at '+JSON.stringify(p)+' for '+c.name);const v=encode(row.block)|(ci+1)<<8;world.set(k,v);if(repeater(v&255))diodes.push(k);histogram[row.block.id]=(histogram[row.block.id]+1)||1;chunkSet.add((Math.floor(p.x/16)+65536)*131072+Math.floor(p.z/16)+65536);for(const a of['x','y','z']){box.from[a]=Math.min(box.from[a],p[a]);box.to[a]=Math.max(box.to[a],p[a]);}count++;}instances.push({name:c.name,cells:count});d=null;global.gc?.();console.error(JSON.stringify({stage:'reference_component_loaded',name:c.name,cells:count,unique_cells:world.size}));}
 const fd=openSync(local('packed-world.bin'),'w'),buffer=Buffer.allocUnsafe(12*8192);let used=0;for(const[k,v]of world){buffer.writeUInt32LE(k%2**32,used);buffer.writeUInt32LE(Math.floor(k/2**32),used+4);buffer.writeUInt32LE(v,used+8);used+=12;if(used===buffer.length){writeSync(fd,buffer);used=0;}}if(used)writeSync(fd,buffer.subarray(0,used));closeSync(fd);
 const cache={status:'exact_selected_reference_geometry_cache_not_build_admission',source_sha256:pins,binary_sha256:sha(HERE+'packed-world.bin'),unique_cells:world.size,occupied_chunk_columns:chunkSet.size,box,materials:histogram,instances,encoding:'12-byte little endian records: low32/high32 packed coordinate, uint32 source-instance-plus-physical-class; diode delay deliberately absent because this is a reachability screen, not a time model.'};writeFileSync(local('packed-world.json'),JSON.stringify(cache,null,2)+'\n');}
const byInstance={},witnesses=[];for(let i=0;i<diodes.length;i++){const k=diodes[i],w=findFeedback(world,k);if(w){const ci=(world.get(k)>>>8)-1;w.component=cfg.instances[ci].name;w.local_repeater=Object.fromEntries(['x','y','z'].map(a=>[a,w.repeater[a]-cfg.instances[ci].translation[a]]));witnesses.push(w);byInstance[w.component]=(byInstance[w.component]??0)+1;}if((i+1)%50000===0)console.error(JSON.stringify({stage:'repeaters_checked',checked:i+1,total:diodes.length,witnesses:witnesses.length}));}
const knownPath='artifacts/full-gpu-layout-v1/memory/channel-colocation-v1/original-feedback-audit.json',known=JSON.parse(readFileSync(resolve(ROOT,knownPath))),knownRows=known.witnesses.filter(w=>w.feedback_found),keys=new Set(witnesses.map(w=>key(w.repeater)));
for(const w of knownRows)assert(keys.has(key(w.driver)),'Lost known positive '+w.name);
let supported=0;for(const w of witnesses)for(const p of[w.repeater,...w.wire_path]){assert.equal((world.get(key(p)-1)??0)&255,1,'Unsupported witness at '+JSON.stringify(p));supported++;}
pins[knownPath]=sha(knownPath);audit.assertStable();const cache=read('packed-world.json');const out={status:'bounded_repeater_feedback_census_complete',source_sha256:{...pins,[HERE+'dependencies.mjs']:sha(HERE+'dependencies.mjs'),[HERE+'census.mjs']:sha(HERE+'census.mjs'),[HERE+'packed-world.json']:sha(HERE+'packed-world.json'),[HERE+'fixture-checks.json']:sha(HERE+'fixture-checks.json')},unique_reference_cells:world.size,occupied_chunk_columns:cache.occupied_chunk_columns,box,repeaters_checked:diodes.length,feedback_witnesses:witnesses.length,by_component:byInstance,witnesses,known_author_positive_count:knownRows.length,known_author_positives_reproduced:knownRows.length,witness_supports_checked:supported,complete_gpu_layout:false,native_acceptance:false,native_calls:0,limits:['Only own-output to own-rear paths through at most15 actual dust vertices, optionally a directly powered front solid or weakly powered rear solid. Longer loops, multiple-device loops, torches, event order and burnout are outside this bounded census.','Side-locked repeaters are retained and identified; witnesses require source-high/unlocked conditions. Each unexpected witness needs ownership classification before repair.','No logical net name exempts a physical wire contact. No scheduling or native execution claim.']};writeFileSync(local('census.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,unique_reference_cells:world.size,occupied_chunk_columns:cache.occupied_chunk_columns,repeaters_checked:diodes.length,feedback_witnesses:witnesses.length,by_component:byInstance,known_author_positives_reproduced:knownRows.length,...audit.stats()}));
