// Nominal arithmetic over actual frozen-path cells. This is not event simulation.
import assert from'node:assert/strict';import{writeFileSync,createReadStream}from'node:fs';import{createHash}from'node:crypto';
import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';
import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';
import{routeDelays}from'../../../../scripts/check-route-delay.mjs';
const H=new URL('.',import.meta.url),d=readLargeDesign(new URL('../internal-bank-response-v1/design.json',H)),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block])),edges=[],unique=new Set(),connections=[];
const sideEdges=new Set(d.bank_response_matrix.branches.map(b=>K(b.side)+'>'+K(b.gate))),diode=b=>['minecraft:repeater','minecraft:comparator'].includes(b?.id);
function edge(a,b){const ab=m.get(K(a)),bb=m.get(K(b));assert(ab&&bb);if(diode(ab))assert.deepEqual(A(a,D[ab.properties.facing]),b);if(diode(bb)&&!sideEdges.has(K(a)+'>'+K(b)))assert.deepEqual(A(a,D[bb.properties.facing]),b);const k=K(a)+'>'+K(b);if(!unique.has(k)){edges.push({from:a,to:b});unique.add(k);}}
function path(ps){for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);}
for(const r of[...d.address_routes,...d.write_data_routes,...d.bank_response_routes,...d.bank_response_matrix.routes])path(r.path);
for(const t of[...d.address_descents,...d.write_data_descents,...d.bank_response_descents]){path(makeSignalDescent({drop:t.drop}).path.map(p=>A(p,t.origin)));edge(t.output,t.normalizer);}
for(const t of[...d.address_columns,...d.write_data_columns,...d.bank_response_columns,...d.bank_response_matrix.columns]){assert.equal((t.hi-t.lo)%4,0);for(let y=t.lo;y<t.hi;y++)edge(P(t.x,y,t.z),P(t.x,y+1,t.z));}
// The first cable derivative starts after the source-bound consumer-return parent.
const first=2366128;assert(d.blocks.length>first);
for(const v of d.blocks.slice(first)){if(!diode(v.block))continue;const p=v.position,f=D[v.block.properties.facing],rear=P(p.x-f.x,p.y,p.z-f.z),front=A(p,f);if(m.has(K(rear)))edge(rear,p);if(m.has(K(front))&&!diode(m.get(K(front))))edge(p,front);}
for(const a of d.address_adapters){const p=a.input,{x,y,z}=a.solid,ps=[];for(let xx=p.x;xx>=x+4;xx--)ps.push(P(xx,y-2,z));ps.push(P(x+3,y-1,z),P(x+2,y,z),a.driver,a.solid);path(ps);edge(a.solid,a.read);edge(a.solid,a.write);}
for(const a of d.write_data_adapters){const{x,y,z}=a.destination,p=a.input,uz=z+(a.bit===7?2:0),ps=[];for(let xx=p.x;xx>=x+20;xx--)ps.push(P(xx,y-2,z));for(let zz=z+1;zz<=uz;zz++)ps.push(P(x+20,y-2,zz));for(let xx=x+19;xx>=x+4;xx--)ps.push(P(xx,y-2,uz));for(let zz=uz-1;zz>=z;zz--)ps.push(P(x+4,y-2,zz));ps.push(P(x+3,y-1,z),P(x+2,y,z),a.driver,a.destination);path(ps);}
for(const b of d.bank_response_matrix.branches){const{x,y,z}=b.gate;path([P(x+2,y,z),P(x+2,y+1,z+1),P(x+2,y+2,z+2)]);edge(b.side,b.gate);}
for(const p of d.bank_response_matrix.ports.bank_channel_owned_ready.positions){const solid=P(p.x,p.y,p.z+2),torch=P(p.x,p.y,p.z+3),wire=P(p.x,p.y,p.z+4);assert.equal(m.get(K(torch)).id,'minecraft:redstone_wall_torch');assert.equal(m.get(K(torch)).properties.facing,'south');edge(solid,torch);edge(torch,wire);}
for(const b of d.address_bindings)for(const kind of['read','write'])connections.push({name:`address_c${b.channel}_b${b.bank}_bit${b.bit}_${kind}`,source:b.source,destination:b[kind]});
for(const b of d.write_data_bindings)connections.push({name:`write_c${b.channel}_b${b.bank}_bit${b.bit}`,source:b.source,destination:b.write});
for(const b of d.bank_response_bindings.filter(b=>b.kind==='bank_held_data'))for(let ch=0;ch<4;ch++)connections.push({name:`response_data_b${b.bank}_c${ch}_bit${b.bit}`,source:b.source,destination:d.bank_response_bindings.find(v=>v.kind==='qualified_backend_d'&&v.channel===ch&&v.bit===b.bit).destination});
for(const b of d.bank_response_bindings.filter(b=>b.kind==='actual_owned_bank_ready'))for(let bit=0;bit<8;bit++)connections.push({name:`response_qualifier_b${b.bank}_c${b.channel}_bit${bit}`,source:b.source,destination:d.bank_response_bindings.find(v=>v.kind==='qualified_backend_d'&&v.channel===b.channel&&v.bit===bit).destination});
assert.equal(connections.length,640);
const result=routeDelays({blocks:d.blocks,edges,connections},{requireNoninverting:false}),groups={};
for(const prefix of['address_','write_','response_data_','response_qualifier_']){const rows=result.routes.filter(r=>r.name.startsWith(prefix));groups[prefix]={paths:rows.length,nominal_min_ticks:Math.min(...rows.map(r=>r.nominal_min_ticks)),nominal_max_ticks:Math.max(...rows.map(r=>r.nominal_max_ticks))};}
const source_sha256={},root=new URL('../../../../',H);for(const url of [new URL(import.meta.url),new URL('../internal-bank-response-v1/design.json',H),new URL('../../../../hardware/memory-layout-large-json-v2.mjs',H),new URL('../../../../hardware/full-gpu-signal-descent.mjs',H),new URL('../../../../scripts/check-route-delay.mjs',H)]){const h=createHash('sha256');for await(const chunk of createReadStream(url))h.update(chunk);source_sha256[url.pathname.slice(root.pathname.length)]=h.digest('hex');}
const out={...result,status:'offline_internal_transport_nominal_only',groups,explicit_edges:edges.length,source_sha256,scope:['Retained global address/write Q to actual bank input pads; does not yet include bank selection/payload capture logic.','Held bank DATA and per-bank owner-qualified READY to actual global response D, including all matrix branch and selector paths.','Comparator side edges are sensitivity paths with a two-tick component charge; Boolean selection and pulse width are separate.','No OPEN/close comparison or timing admission is established by this transport-only report.'],capture_hold_ordering_closed:false};
if(process.argv.includes('--save'))writeFileSync(new URL('cable-delay.json',H),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,edges:edges.length,groups}));
