// Exact per-copy cross-boundary delta check against every currently frozen master cable.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
const root='artifacts/full-gpu-layout-v1/',read=p=>JSON.parse(readFileSync(p)),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,W='minecraft:redstone_wire',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',diode=b=>['minecraft:repeater','minecraft:comparator'].includes(b?.id),solid=b=>b?.id.endsWith('_concrete'),D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(D),pair=(a,b)=>[K(a),K(b)].sort().join('|'),sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const d=read(root+'control-reset-master-compatible-v1/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v.block])),f=read(root+'control-reset-master-address-review-v1/master-obstacles.json'),oldPath=read(root+'floorplan-v3/frame-config.json').instances.core0.path,old=new Map(read(oldPath).blocks.map(v=>[K(v.position),v.block])),report=[];
const sources=(at,p)=>{const out=[];for(const[x,z]of dirs){const q=P(p.x-x,p.y,p.z-z),b=at(q);if(b?.id===W||diode(b)&&D[b.properties.facing][0]===x&&D[b.properties.facing][1]===z)out.push(q);}for(const[y,id]of[[-1,T],[1,W]]){const q=P(p.x,p.y+y,p.z),b=at(q);if(b?.id===id||id===T&&b?.id===WT)out.push(q);}return out;};
for(let core=0;core<2;core++){
 const ext=new Map,pins={},names=new Map;let collisions=[];for(const[n,c]of Object.entries(f.route_deltas)){if(n==='master-lsu-address-routes-v1'){assert.equal(sha(c.manifest),'22558a2223759daf8c8118a90488ef546961f150b7be0ca069b4bc9e24c7f215');assert.equal(sha(c.path),'a5cf9d50e2ff3be80076e1c0f247d17d6f2d5b5011e82d7454d0967b08b97431');}else{assert.equal(sha(c.path),d.master_obstacle_source_sha256[c.path]);assert.equal(sha(c.manifest),d.master_obstacle_source_sha256[c.manifest]);}pins[c.path]=sha(c.path);for(const v of read(c.path).blocks){const p=P(v.position.x+400,v.position.y,v.position.z+1552+1520*core);if(['x','y','z'].some(a=>p[a]<d.box.from[a]-4||p[a]>d.box.to[a]+4))continue;const k=K(p);assert(!ext.has(k),'Master delta collision '+k);ext.set(k,v.block);names.set(k,n);if(m.has(k))collisions.push({position:p,master:n,core:m.get(k),external:v.block});}}
 const after=p=>m.get(K(p))??ext.get(K(p)),before=p=>old.get(K(p))??ext.get(K(p)),coreOnly=p=>m.get(K(p)),isCross=(a,b)=>ext.has(K(a))!==ext.has(K(b))&&[a,b].some(p=>ext.has(K(p)))&&[a,b].some(p=>m.has(K(p))),crossContacts=new Set,beforeContacts=new Set,affectedCore=new Map,solids=new Map;
 function contactSet(at,cm){const out=new Set;for(const[k,b]of ext){const[x,y,z]=k.split(',').map(Number),p=P(x,y,z);for(const[dx,dz]of dirs)for(const dy of[-1,0,1]){const q=P(x+dx,y+dy,z+dz),v=cm.get(K(q));if(!v||solid(v)||solid(b))continue;if(dy&&!(v.id===W&&b.id===W))continue;if(!dy&&b.id!==W&&v.id!==W)continue;const low=dy<0?q:p,high=dy<0?p:q;if(dy&&at(P(low.x,low.y+1,low.z)))continue;out.add(pair(p,q));}if(diode(b)){const[dx,dz]=D[b.properties.facing];for(const[sx,sz]of[[dz,dx],[-dz,-dx]]){const q=P(x+sx,y,z+sz);if(diode(cm.get(K(q))))out.add('side:'+pair(p,q));}}}return out;}
 for(const[k,b]of ext){const[x,y,z]=k.split(',').map(Number),p=P(x,y,z);for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++){const q=P(x+dx,y+dy,z+dz),v=m.get(K(q));if(v)affectedCore.set(K(q),v);if(solid(v)||solid(ext.get(K(q))))solids.set(K(q),q);}}
 const ac=contactSet(after,m),bc=contactSet(before,old),addedContacts=[...ac].filter(k=>!bc.has(k));
 const changedMasterDust=[],neighborKeys=(p,at)=>{const out=[];for(const[x,z]of dirs)for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(ext.get(K(q))?.id!==W)continue;if(y===1&&at(P(p.x,p.y+1,p.z)))continue;if(y===-1&&at(P(q.x,q.y+1,q.z)))continue;out.push(K(q));}return out.sort();};let masterDust=0;for(const[k,b]of ext)if(b.id===W){const[x,y,z]=k.split(',').map(Number),p=P(x,y,z),a=neighborKeys(p,after),o=neighborKeys(p,before);masterDust++;if(JSON.stringify(a)!==JSON.stringify(o))changedMasterDust.push({position:p,before:o,after:a});}

 const changedSourceSets=[];let newCoreTorch=0,newCoreSolidRears=0,masterTorch=0,masterSolidRears=0;function sourceKeys(at,p){return sources(at,p).map(K).sort();}
 for(const[k,b]of ext){const[x,y,z]=k.split(',').map(Number),p=P(x,y,z);let s;if(b.id===T||b.id===WT){const v=b.id===T?[0,-1,0]:[...D[b.properties.facing].slice(0,1),0,D[b.properties.facing][1]];s=P(x+v[0],y+v[1],z+v[2]);masterTorch++;}else if(diode(b)){const[dx,dz]=D[b.properties.facing],q=P(x-dx,y,z-dz);if(solid(after(q))){s=q;masterSolidRears++;}}if(s){const a=sourceKeys(after,s),o=sourceKeys(before,s);if(JSON.stringify(a)!==JSON.stringify(o))changedSourceSets.push({kind:'master_device',position:p,support:s,before:o,after:a});}}
 for(const[k,b]of affectedCore){const[x,y,z]=k.split(',').map(Number),p=P(x,y,z);let s;if(b.id===T){s=P(x,y-1,z);newCoreTorch++;}else if(b.id===WT){const[dx,dz]=D[b.properties.facing];s=P(x+dx,y,z+dz);newCoreTorch++;}else if(diode(b)){const[dx,dz]=D[b.properties.facing],q=P(x-dx,y,z-dz);if(solid(after(q))){s=q;newCoreSolidRears++;}}if(s){const a=sourceKeys(after,s),o=sourceKeys(coreOnly,s);if(JSON.stringify(a)!==JSON.stringify(o)){// An unchanged old receiving interface is an existing bound master connection.
 const prev=old.get(k),same=JSON.stringify(prev)===JSON.stringify(b),baseline=sourceKeys(before,s);if(!same||JSON.stringify(a)!==JSON.stringify(baseline))changedSourceSets.push({kind:'core_device',position:p,support:s,core_only:o,after:a});}}}
 function crossPower(at,cm){const out=new Set;for(const p of solids.values()){if(!solid(at(p)))continue;for(const a of sources(at,p))for(const[dx,dy,dz]of[...dirs.map(([x,z])=>[x,0,z]),[0,1,0],[0,-1,0]]){const q=P(p.x+dx,p.y+dy,p.z+dz),b=at(q);if(!b||K(a)===K(q)||!(ext.has(K(a))&&cm.has(K(q))||cm.has(K(a))&&ext.has(K(q))))continue;const ab=at(a);if(b.id===W&&ab.id!==W)out.add(K(a)+'>'+K(p)+'>'+K(q));else if(diode(b)){const[x,z]=D[b.properties.facing];if(K(P(q.x-x,q.y,q.z-z))===K(p))out.add(K(a)+'>'+K(p)+'>'+K(q));}else if(b.id===T&&q.y===p.y+1||b.id===WT&&K(P(q.x+D[b.properties.facing][0],q.y,q.z+D[b.properties.facing][1]))===K(p))out.add(K(a)+'>'+K(p)+'>'+K(q));}}return out;}
 const ap=crossPower(after,m),bp=crossPower(before,old),addedPower=[...ap].filter(k=>!bp.has(k));
 report.push({core,master_dust_vertices:masterDust,changed_master_dust_edges:changedMasterDust,master_cells:ext.size,core_halo_cells:affectedCore.size,collisions,added_cross_contacts:addedContacts,changed_source_sets:changedSourceSets,new_cross_solid_power_paths:addedPower,master_torch_source_sets:masterTorch,master_solid_rears:masterSolidRears,core_torch_source_sets:newCoreTorch,core_solid_rears:newCoreSolidRears,existing_cross_contacts:bc.size,existing_cross_power:bp.size});console.log(JSON.stringify({...report.at(-1),collisions:collisions.slice(0,10),added_cross_contacts:addedContacts.slice(0,20),changed_source_sets:changedSourceSets.slice(0,10),new_cross_solid_power_paths:addedPower.slice(0,20)}));
}
const ok=report.every(r=>!r.collisions.length&&!r.changed_master_dust_edges.length&&!r.added_cross_contacts.length&&!r.changed_source_sets.length&&!r.new_cross_solid_power_paths.length),out={status:ok?'author_checked_both_master_cable_boundaries':'master_contact_repair_required',design_sha256:sha(root+'control-reset-master-compatible-v1/design.json'),reports:report,native_acceptance:false,limits:['This checks both core copies against every listed frozen master cable, preserving original receiving contacts. Unfrozen future cable deltas require a new screen.','Conservative conductor-source inventory is not a scheduled redstone transient proof.']};writeFileSync(new URL('master-checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');assert(ok,'Master interaction changes remain');
