// Full input/support preservation plus real bank gates, inversions and returns.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {H,ROOT,K,read,pins,loadBase} from './frame.mjs';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
import {backwardCone,makeSettledEvaluator} from '../program-global-delivery-v1/settled-program-network.mjs';
import {evaluate} from '../dispatch-external-bindings-v1/transport-functions.mjs';
import {checkFeedback} from '../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
const P=(x,y,z)=>({x,y,z}),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete'),write=(n,d)=>writeFileSync(new URL(n,H),JSON.stringify(d,null,2)+'\n');
const reserve=process.env.RESERVE==='1',frame=loadBase(),base=frame.world,world=new Map(base),d=read('delta.json'),f=read('source-functions.json');
assert.equal(d.connections.length,4);const rows=[...frame.rows,...d.new_cells];let obstacles=0;
if(reserve){const r=read('commit-phase-reservation.json');obstacles=r.blocks.length;for(const v of r.blocks){assert(!base.has(K(v.position)));base.set(K(v.position),v.block);world.set(K(v.position),v.block);rows.push(v);}}
for(const r of d.new_cells){assert(!world.has(K(r.position)),'Collision '+K(r.position));world.set(K(r.position),r.block);}
const cableKeys=new Set(d.new_cells.filter(r=>r.part!=='original_bank_quiet_adapter'&&active(r.block)).map(r=>K(r.position))),adapterKeys=new Set(f.adapter_blocks.filter(r=>active(r.block)).map(r=>K(r.position))),edges=new Set(),extra=new Map(),adapterExpected=new Map();
for(const route of d.routes)for(let i=1;i<route.path.length;i++){edges.add(K(route.path[i-1])+'>'+K(route.path[i]));edges.add(K(route.path[i])+'>'+K(route.path[i-1]));}
for(let i=0;i<4;i++){const c=d.connections[i],s=f.selected[i],a=f.sources[i].adapter;assert.deepEqual(c.root,s.new_source);assert.deepEqual(c.destination,s.new_destination);extra.set(K(c.destination),K(c.normalizer));for(const [target,source]of[[a.input_normalizer,a.source],[a.torch,a.input_normalizer],[a.output_normalizer,a.torch],[a.destination,a.output_normalizer]])adapterExpected.set(K(target),[K(source)]);}
let receivers=0,supports=0,actualInputs=0,preservedInputs=0,newInputs=0,changedReceivers=0;
for(const r of rows){const p=r.position,k=K(p),b=r.block;let s;if(b.id===WT)s=A(p,D[b.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(b.id))s=P(p.x,p.y-1,p.z);if(s){assert(solid(world.get(K(s))),'Unsupported '+k);supports++;}if(!active(b))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;
 if(base.has(k)){const expected=inputs(base,p).map(K);preservedInputs+=expected.length;if(extra.has(k)){expected.push(extra.get(k));changedReceivers++;}assert.deepEqual(actual,[...new Set(expected)].sort(),'Changed retained input '+k);}
 else if(adapterKeys.has(k)){assert.deepEqual(actual,adapterExpected.get(k),'Adapter source mismatch '+k);newInputs+=actual.length;}
 else{assert(cableKeys.has(k),'Unclassified addition '+k);for(const q of actual)assert(edges.has(q+'>'+k),'Foreign cable contact '+q+'>'+k);newInputs+=actual.length;}
}
assert.equal(changedReceivers,4);for(const route of d.routes)for(let i=1;i<route.path.length;i++)assert(inputs(world,route.path[i]).some(p=>K(p)===K(route.path[i-1])),'Broken route '+route.name+'/'+i);
const transport=evaluate(world,cableKeys);for(const c of d.connections)assert.deepEqual(transport.get(c.normalizer),{roots:[c.root],table:2});
const proofs=[],negative=[],allRoots=f.sources.flatMap(s=>s.actual_status_sources.map(r=>r.position)),allTargets=d.connections.map(c=>c.destination),allCone=new Map(),rears=new Map(),opposite={east:'west',west:'east',north:'south',south:'north'};
for(let bank=0;bank<4;bank++){
 const c=d.connections[bank],s=f.sources[bank],roots=s.actual_status_sources.map(r=>r.position),targets=[s.busy,s.quiet,c.destination],cone=new Map();for(const p of targets)for(const q of backwardCone(world,p,roots))cone.set(K(q),q);for(const [k,p]of cone)allCone.set(k,p);const positions=[...cone.values()],ev=makeSettledEvaluator(world,positions,roots),feedback=checkFeedback(world,positions,roots),cases=[];
 for(let a=0;a<8;a++){const values=ev(new Map(roots.map((p,i)=>[K(p),(a>>i&1)*15]))),outputs=targets.map(p=>values.power.get(K(p))??0);assert.deepEqual(outputs,[a?15:0,a?0:15,a?0:15]);cases.push({assignment:a,outputs});for(const p of positions){const k=K(p),b=world.get(k);if(b.id!==R||base.has(k)||!(values.power.get(k)>0))continue;const direction=D[b.properties.facing],ins=inputs(world,p);assert(ins.every(q=>(q.x-p.x)*direction.x+(q.z-p.z)*direction.z<0),'Unexpected lock');const rear=Math.max(0,...ins.map(q=>values.power.get(K(q))??0));assert(rear>0);rears.set(k,Math.min(rears.get(k)??15,rear));}}
 const cableCone=backwardCone(world,c.destination,[c.root]),cableEv=makeSettledEvaluator(world,cableCone,[c.root]),strengths=[];for(let n=0;n<=15;n++){const v=cableEv(new Map([[K(c.root),n]]));assert.equal(v.power.get(K(c.destination))??0,n?15:0);strengths.push({strength:n,output:v.power.get(K(c.destination))??0});}
 // Each real added diode is reversed and evaluated through its actual cone.
 for(const p of positions){const k=K(p),saved=world.get(k);if(saved.id!==R||base.has(k))continue;world.set(k,{...saved,properties:{...saved.properties,facing:opposite[saved.properties.facing]}});let refused=false;try{const badPositions=backwardCone(world,c.destination,roots),bad=makeSettledEvaluator(world,badPositions,roots);for(const a of[0,1,2,4,7]){const v=bad(new Map(roots.map((r,i)=>[K(r),(a>>i&1)*15])));if((v.power.get(K(c.destination))??0)!==(a?0:15)){refused=true;break;}}}catch{refused=true;}assert(refused,'Reversed diode survived '+k);world.set(k,saved);negative.push({bank,kind:'reverse_actual_added_repeater',position:p});}
 const adapterTorch=s.adapter.torch,savedTorch=world.get(K(adapterTorch));world.set(K(adapterTorch),{id:W});let refused=false;try{const bad=makeSettledEvaluator(world,backwardCone(world,c.destination,roots),roots);for(const a of[0,1])if((bad(new Map(roots.map((r,i)=>[K(r),(a>>i&1)*15]))).power.get(K(c.destination))??0)!==(a?0:15))refused=true;}catch{refused=true;}assert(refused,'Missing inverter survived');world.set(K(adapterTorch),savedTorch);negative.push({bank,kind:'replace_quiet_inverter_with_wire',position:adapterTorch});
 const support=P(c.normalizer.x,c.normalizer.y-1,c.normalizer.z),savedSupport=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),savedSupport);negative.push({bank,kind:'remove_arrival_support',position:support});
 proofs.push({bank,roots,targets,devices:positions.length,cases,strengths,feedback});
}
const joint=makeSettledEvaluator(world,[...allCone.values()],allRoots),independentBanks=[];for(let a=0;a<16;a++){const values=new Map();for(let bank=0;bank<4;bank++)f.sources[bank].actual_status_sources.forEach((r,i)=>values.set(K(r.position),i===0&&(a>>bank&1)?15:0));const v=joint(values),outputs=allTargets.map(p=>v.power.get(K(p))??0);assert.deepEqual(outputs,Array.from({length:4},(_,i)=>a>>i&1?0:15));independentBanks.push({active_mask:a,outputs});}
const addedRepeaters=d.new_cells.filter(r=>r.block.id===R);assert.equal(rears.size,addedRepeaters.length,'Every added diode needs an observed high-state rear');
function cost(rows){const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)},materials={},columns=new Set();for(const r of rows){for(const a of['x','y','z']){box.from[a]=Math.min(box.from[a],r.position[a]);box.to[a]=Math.max(box.to[a],r.position[a]);}materials[r.block.id]=(materials[r.block.id]??0)+1;columns.add(Math.floor(r.position.x/16)+','+Math.floor(r.position.z/16));}return{cells:rows.length,box,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1])),legal_y_translation:[-64-box.from.y,319-box.to.y],occupied_columns:columns.size,materials};}
const fullCost=cost(rows);assert(fullCost.legal_y_translation[0]<=fullCost.legal_y_translation[1]);
for(const n of['frame.mjs','prepare.mjs','route.mjs','check.mjs','../memory/fabric-colocation-v2/cut-inputs.mjs','../program-global-delivery-v1/settled-program-network.mjs','../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs','../dispatch-external-bindings-v1/transport-functions.mjs']){const p=new URL(n,H);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');}
const metrics={accepted_base_cells:2054908,new_cells:d.new_cells.length,adapter_cells:32,uncredited_concurrent_obstacle_cells:obstacles,total_cells:world.size,new_routes:4,path_vertices:d.routes.reduce((n,r)=>n+r.path.length,0),receivers,supports,actual_inputs:actualInputs,preserved_inputs:preservedInputs,new_inputs:newInputs,changed_receivers:changedReceivers,bank_gate_cases:32,bank_gate_observations:96,independent_bank_patterns:16,independent_bank_observations:64,cable_strength_cases:64,added_repeaters:addedRepeaters.length,minimum_new_repeater_rear:Math.min(...rears.values()),negative_cases:negative.length};
write(reserve?'reservation-checks.json':'checks.json',{status:reserve?'passed_exact_commit_phase_obstacle_compatibility':'passed_actual_bank_quiet_global_deliveries',metrics,proofs,independent_banks:independentBanks,rears:[...rears].map(([key,rear])=>({position:P(...key.split(',').map(Number)),rear})),negative,cost:{complete:fullCost,addition:cost(d.new_cells)},source_sha256:{...d.source_sha256,...pins},limits:['Bank ACTIVE/finaltail/resetblocked sources are the actual held driver boundaries, not a sequential bank-memory proof.','Four source-specific quiet delivery cones pass only the normalized static and settled-level models; freshness, setup/hold, clocking and native Minecraft remain separate.','The accepted shared frame excludes cores and remaining master/loading/response links. Its cost is partial, not compact-build admission.','Concurrent commit-phase rows are an exact obstacle-only snapshot; this package does not change their acceptance or witness ledger.']});console.log(JSON.stringify(metrics));console.log(JSON.stringify(fullCost));
