// Complete actual-input screen and four actual channel-specific eight-owner OR observations.
import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {H,ROOT,K,read,pins} from './frame.mjs';
import {loadFrame} from './routing-frame.mjs';
import {inputs,active} from '../../memory/fabric-colocation-v2/cut-inputs.mjs';
import {backwardCone} from '../../memory/fabric-colocation-v2/settled-network.mjs';
import {makeSettledEvaluator} from './settled-dag.mjs';
import {evaluate} from '../../dispatch-external-bindings-v1/transport-functions.mjs';
import {checkFeedback} from '../service-mask-memory-composition-v1/feedback.mjs';
const P=(x,y,z)=>({x,y,z}),A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
const frame=loadFrame(),base=frame.world,world=new Map(base),d=read('delta.json'),functions=read('source-functions.json');
assert.equal(d.connections.length,4);assert.equal(d.new_cells.length,3920);
for(const row of d.new_cells){assert(!world.has(K(row.position)),'Collision');world.set(K(row.position),row.block);}
const rows=[...frame.rows,...d.new_cells],newKeys=new Set(d.new_cells.filter(v=>active(v.block)).map(v=>K(v.position))),extra=new Map(d.connections.map(c=>[K(c.destination),K(c.normalizer)])),edges=new Set();
for(const r of d.routes)for(let i=1;i<r.path.length;i++){edges.add(K(r.path[i-1])+'>'+K(r.path[i]));edges.add(K(r.path[i])+'>'+K(r.path[i-1]));}
let receivers=0,supports=0,actualInputs=0,preservedInputs=0,newInputs=0;
for(const row of rows){const p=row.position,k=K(p),b=row.block;let support;
 if(b.id===WT)support=A(p,D[b.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);
 if(support){assert(solid(world.get(K(support))),'Unsupported device '+k);supports++;}
 if(!active(b))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;
 if(base.has(k)){const prior=inputs(base,p).map(K);preservedInputs+=prior.length;assert.deepEqual(actual,[...new Set([...prior,...(extra.has(k)?[extra.get(k)]:[])])].sort(),'Unexpected old input '+k);}
 else {assert(newKeys.has(k));for(const q of actual)assert(edges.has(q+'>'+k),'Foreign cable contact '+q+'>'+k);newInputs+=actual.length;}
}
for(const r of d.routes)for(let i=1;i<r.path.length;i++)assert(inputs(world,r.path[i]).some(p=>K(p)===K(r.path[i-1])),'Broken route '+r.name+' '+i);
const transportKeys=new Set([...newKeys,...d.connections.flatMap(c=>c.existing_source_cone.map(K))]);const transport=evaluate(world,transportKeys);for(const c of d.connections)assert.deepEqual(transport.get(c.normalizer),{roots:[c.root],table:2});
const rootsByKey=new Map(),union=new Map(),cases=[],proofs=[],rears=new Map(),negative=[],opposite={east:'west',west:'east',north:'south',south:'north'};
for(let channel=0;channel<4;channel++){
 const c=d.connections[channel],record=functions.records[channel],source=record.source_proofs.find(r=>r.kind==='current'),held=source.held_boundaries.map(v=>v.position),positions=backwardCone(world,c.destination,held),constants=positions.filter(p=>world.get(K(p)).id==='minecraft:redstone_block'),boundary=[...held,...constants],ev=makeSettledEvaluator(world,positions,boundary),feedback={...checkFeedback(world,positions,boundary),scope:'Complete actual local live BUSY and four owned-bank source cones through this witness arrival. Held channel ACTIVE/raw backend plus actual per-bank ACTIVE/final tail/reset blocker/negative owner boundaries.'};for(const p of positions)union.set(K(p),p);for(const p of boundary)rootsByKey.set(K(p),p);
 const actualSource=backwardCone(world,c.root,held),reference=new Map(source.expanded.rows.map(r=>[K(r.position),r])),stops=new Set(boundary.map(K));assert.equal(actualSource.length,reference.size);for(const p of actualSource){const r=reference.get(K(p));assert(r);assert.deepEqual(world.get(K(p)),r.block);assert.deepEqual(stops.has(K(p))?[]:inputs(world,p),r.inputs);}
 const force=values=>new Map([...constants.map(p=>[K(p),15]),...held.map((p,i)=>[K(p),values[i]])]);
 for(const test of source.expanded.cases){const v=ev(force(test.values)),outputs=[v.power.get(K(c.root))??0,v.power.get(K(c.destination))??0];assert.deepEqual(outputs,[test.level,test.expected?15:0]);cases.push({channel,mode:test.mode,values:test.values,outputs});if(test.expected)for(const p of positions)if(newKeys.has(K(p))&&world.get(K(p)).id===R){const rear=Math.max(0,...inputs(world,p).map(q=>v.power.get(K(q))??0));assert(rear>0);rears.set(K(p),Math.min(rears.get(K(p))??15,rear));}}
 const high=source.expanded.cases.find(t=>t.mode==='active'&&t.localBits===1).values;
 for(const [kind,p]of [['arrival',c.normalizer],['source_isolator',c.source_isolator]]){const saved=world.get(K(p));world.set(K(p),{...saved,properties:{...saved.properties,facing:opposite[saved.properties.facing]}});let refused=false;try{const ps=backwardCone(world,c.destination,held),consts=ps.filter(q=>world.get(K(q)).id==='minecraft:redstone_block'),bad=makeSettledEvaluator(world,ps,[...held.filter(h=>ps.some(q=>K(q)===K(h))),...consts]);refused=(bad(force(high)).power.get(K(c.destination))??0)!==15;}catch{refused=true;}assert(refused);world.set(K(p),saved);negative.push({name:c.name,kind:'reverse_actual_'+kind,position:p});}
 const support=P(c.normalizer.x,c.normalizer.y-1,c.normalizer.z),saved=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),saved);negative.push({name:c.name,kind:'delete_actual_arrival_support',position:support});const wrong=d.connections[(channel+1)%4].root;assert.notDeepEqual(transport.get(c.normalizer),{roots:[wrong],table:2});negative.push({name:c.name,kind:'reject_other_channel_busy_source',actual:c.root,wrong});
 proofs.push({channel,held_boundaries:source.held_boundaries,constants,feedback,positions:positions.length,cases:source.expanded.cases.length});
}
const roots=[...rootsByKey.values()],positions=[...union.values()],feedback={...checkFeedback(world,positions,roots),scope:'Four actual local BUSY cones plus their own witness deliveries. Shared bank status sources are deduplicated; each channel retains its own negative-owner and ACTIVE/raw-backend boundaries. Conditional settled functions only.'},ev=makeSettledEvaluator(world,positions,roots),joint=[];
function defaults(){const v=new Map(roots.map(p=>[K(p),world.get(K(p)).id==='minecraft:redstone_block'?15:0]));for(const record of functions.records)for(const s of record.source_proofs.find(p=>p.kind==='current').held_boundaries)if(s.role.includes('not_owner'))v.set(K(s.position),15);return v;}
function observe(kind,values,expected,meta){const v=ev(values),outputs=[];for(let ch=0;ch<4;ch++){const c=d.connections[ch],source=v.power.get(K(c.root))??0,arrival=v.power.get(K(c.destination))??0;assert.equal(source>0,expected[ch]);assert.equal(arrival,expected[ch]?15:0);outputs.push(source,arrival);}joint.push({kind,...meta,outputs});}
for(const type of ['retained_ACTIVE_Q','raw_backend_busy'])for(let mask=0;mask<16;mask++){const v=defaults();for(let ch=0;ch<4;ch++){const p=functions.records[ch].binding.current_held_boundaries.find(p=>p.role===type).position;v.set(K(p),mask>>ch&1?15:0);}observe('independent_'+type,v,Array.from({length:4},(_,ch)=>!!(mask>>ch&1)),{mask});}
for(let bank=0;bank<4;bank++)for(let status=0;status<8;status++)for(let ownerMask=0;ownerMask<16;ownerMask++){const v=defaults();for(const s of functions.banks[bank].sources){if(['active','tail','reset'].includes(s.name))v.set(K(s.position),status>>['active','tail','reset'].indexOf(s.name)&1?15:0);else v.set(K(s.position),ownerMask>>Number(s.name.at(-1))&1?0:15);}observe('shared_bank_status_and_distinct_ownership',v,Array.from({length:4},(_,ch)=>!!status&&!!(ownerMask>>ch&1)),{bank,status,ownerMask});}
const allNewRepeaters=d.new_cells.filter(r=>r.block.id===R);assert.equal(rears.size,allNewRepeaters.length);const newRears=allNewRepeaters.map(r=>({position:r.position,rear:rears.get(K(r.position))}));
function cost(rows){const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)},materials={},columns=new Set();for(const v of rows){for(const a of ['x','y','z']){box.from[a]=Math.min(box.from[a],v.position[a]);box.to[a]=Math.max(box.to[a],v.position[a]);}materials[v.block.id]=(materials[v.block.id]??0)+1;columns.add(Math.floor(v.position.x/16)+','+Math.floor(v.position.z/16));}return {cells:rows.length,box,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1])),legal_y_translation:[-64-box.from.y,319-box.to.y],occupied_columns:columns.size,materials};}
const completeCost=cost(rows);assert(completeCost.legal_y_translation[0]<=completeCost.legal_y_translation[1]);
for(const n of ['frame.mjs','routing-frame.mjs','prepare.mjs','route.mjs','check.mjs','settled-dag.mjs','verify-evaluator.mjs','../../memory/fabric-colocation-v2/cut-inputs.mjs','../../memory/fabric-colocation-v2/settled-network.mjs','../service-mask-memory-composition-v1/feedback.mjs','../../dispatch-external-bindings-v1/transport-functions.mjs']){const p=new URL(n,H);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');}

const report={status:'passed_actual_four_live_busy_witness_deliveries',metrics:{base_cells:base.size,new_cells:d.new_cells.length,total_cells:world.size,new_routes:4,path_vertices:d.routes.reduce((n,r)=>n+r.path.length,0),receivers,supports,actual_inputs:actualInputs,preserved_inputs:preservedInputs,new_route_inputs:newInputs,expanded_source_cases:cases.length,source_arrival_observations:cases.length*2,joint_cases:joint.length,joint_observations:joint.length*8,minimum_new_repeater_rear:Math.min(...newRears.map(r=>r.rear)),new_repeaters:allNewRepeaters.length,negative_cases:negative.length},proofs,cases,joint,transport:transport.metrics,full_function_feedback:feedback,new_rears:newRears,negative,cost:{complete:completeCost,addition:cost(d.new_cells)},source_sha256:{...d.source_sha256,...pins},limits:['Complete partial shared frame includes exact READY a2505363 and root-return7a5a780a reservations; acceptance of those foreign groups requires their separate exact freezes.','Four source-specific live BUSY pads retain all bank ACTIVE/final normal tail/reset-blocker and retained-owner qualification. The named state/raw-backend boundaries are held; source transitions, reset/retire order and complete routed timing remain open.','Separate bank BUSY-to-loader egress536..539 is untouched. No implicit new loader-control or panel closure.','Both core instances and remaining master/response/loading connections are absent. No whole-GPU density selection or native Minecraft acceptance.']};writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));console.log(JSON.stringify(report.cost));
