// Exact materialized replacement: no implicit removals or duplicate overlaid cells.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync,createReadStream}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{readLargeDesign,writeLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';
const root=new URL('../../../../',import.meta.url),p='artifacts/full-gpu-layout-v1/memory/program-cold-mask-repair-v1/',hash=async p=>{const h=createHash('sha256');for await(const b of createReadStream(new URL(p,root)))h.update(b);return h.digest('hex');},read=p=>JSON.parse(readFileSync(new URL(p,root))),K=p=>[p.x,p.y,p.z].join(',');
const m=read(p+'source-manifest.json'),delta=read(p+'delta.json');for(const[f,h]of Object.entries(m.source_sha256))assert.equal(await hash(f),h,f);
assert.equal(await hash(delta.parent_design),delta.parent_design_sha256);const d=readLargeDesign(fileURLToPath(new URL(delta.parent_design,root))),replacements=new Map(delta.changes.map(v=>[K(v.position),v]));assert.equal(replacements.size,2);let changed=0;const portsBefore=JSON.stringify(d.ports),boundsBefore=JSON.stringify(d.box),count=d.blocks.length;
for(const v of d.blocks){const c=replacements.get(K(v.position));if(c){assert.deepEqual(v.block,c.before);v.block=structuredClone(c.after);changed++;}}
assert.equal(changed,2);assert.equal(count,3381962);assert.equal(JSON.stringify(d.ports),portsBefore);assert.equal(JSON.stringify(d.box),boundsBefore);
d.status='offline_memory_with_exact_program_cold_mask_replacement';d.replacement={parent:delta.parent_design,parent_sha256:delta.parent_design_sha256,patch:p+'delta.json',patch_sha256:await hash(p+'delta.json'),changes:delta.changes};d.native_acceptance=false;d.complete_gpu_layout=false;
writeLargeDesign(fileURLToPath(new URL('design.json',import.meta.url)),d);const source_sha256={...m.source_sha256};for(const f of [p+'source-manifest.json','artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v1/prepare.mjs','artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v1/design.json','hardware/memory-layout-large-json-v2.mjs'])source_sha256[f]=await hash(f);
writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify({status:'exact_two_cell_memory_replacement_materialized',source_sha256,actual_cells:count,blocks_replaced:changed,added:0,removed:0,interfaces_and_bounds_unchanged:true,native_acceptance:false,limits:['Author patch has its own bounded electrical check. Whole-machine composition and independent review remain separate.','All other memory cells preserved in the copied array; serialized geometry hashes identify the exact replacement.']},null,2)+'\n');console.log(JSON.stringify({blocks:count,replacements:changed,design_sha256:source_sha256['artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v1/design.json']}));
