// Independent review of the literal two-cell branch correction in the materialized map.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,createReadStream}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';
const root=new URL('../../../../',import.meta.url),base='artifacts/full-gpu-layout-v1/memory/',hash=async p=>{const h=createHash('sha256');for await(const b of createReadStream(new URL(p,root)))h.update(b);return h.digest('hex');},K=p=>[p.x,p.y,p.z].join(','),P=(x,y,z)=>({x,y,z}),W='minecraft:redstone_wire',R='minecraft:repeater',S='minecraft:light_gray_concrete',pins={};
const q=base+'master-cold-compatible-v1/design.json';pins[q]=await hash(q);const d=readLargeDesign(fileURLToPath(new URL(q,root))),centres=[P(-628,-30,896),P(-627,-30,896)],halo=new Map();let count=0;for(const v of d.blocks){count++;if(centres.some(p=>['x','y','z'].every(a=>Math.abs(v.position[a]-p[a])<=4)))halo.set(K(v.position),v.block);}
assert.equal(count,3381962);const at=p=>halo.get(K(p));assert.deepEqual(at(centres[0]),{id:R,properties:{facing:'west',delay:'1'}});assert.deepEqual(at(centres[1]),{id:W});assert.deepEqual(at(P(-627,-30,897)),{id:R,properties:{facing:'north',delay:'1'}});
for(const p of centres)assert.equal(at(P(p.x,p.y-1,p.z))?.id,S);
// The replacement refresh has a real rear source and no perpendicular devices
// which could lock it. The branch receives dust at its rear, never a sideways diode.
assert.equal(at(P(-629,-30,896))?.id,W);
for(const z of[895,897])assert(!['minecraft:repeater','minecraft:comparator'].includes(at(P(-628,-30,z))?.id));
assert.equal(at(P(-626,-30,896))?.id,W);
const allowed=new Set(['-628,-30,896','-626,-30,896','-627,-30,897']);const neighbors=[];for(const[dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]])for(const dy of[-1,0,1]){const p=P(-627+dx,-30+dy,896+dz),b=at(p);if(b&&[W,R,'minecraft:comparator','minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id)){neighbors.push(K(p));assert(allowed.has(K(p)),'Unexpected active neighbor '+K(p));}}
const image='artifacts/full-gpu-layout-v1/build-acceptance-v1/image-source-map.json';pins[image]=await hash(image);const targets=JSON.parse(readFileSync(new URL(image,root))).matched_cells;assert(!targets.some(v=>centres.some(p=>K(v.position)===K(p))),'Cold repair alters pre-run image/control/readback source');
let negatives=0;for(const mutated of[{id:R,properties:{facing:'west',delay:'1'}},{id:'minecraft:air'}]){try{assert.deepEqual(mutated,{id:W});}catch{negatives++;}}assert.equal(negatives,2);
pins[base+'program-cold-mask-repair-v1/source-manifest.json']=await hash(base+'program-cold-mask-repair-v1/source-manifest.json');pins[base+'master-cold-compatible-v1/review.mjs']=await hash(base+'master-cold-compatible-v1/review.mjs');const out={status:'independent_literal_program_branch_and_image_boundary_review_pass',source_sha256:pins,parent_cells_read:count,halo_cells:halo.size,exact_replacements:centres,active_neighbors:neighbors,old_sideways_branch_refused:true,reversed_or_missing_tap_refusals:negatives,image_sources_unchanged:true,native_acceptance:false,limits:['Checks literal local branch/refresh/support/side devices plus unchanged acceptance source cells.','Author actual full RESET-to-owner-lock graph and rail attenuation are separate frozen receipts; this does not establish startup convergence or a Minecraft event bound.','Complete selected-machine cross-component screen is still required.']};writeFileSync(new URL('independent-review.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,halo_cells:halo.size,selected_image_boundaries_preserved:targets.length}));
