// Explicit sparse replacement of both old frame cores. Offline only.
import assert from 'node:assert/strict';
import{readFileSync,writeFileSync,createReadStream}from'node:fs';
import{createHash}from'node:crypto';
const H=new URL('.',import.meta.url),P='artifacts/full-gpu-layout-v1/',read=p=>JSON.parse(readFileSync(p)),K=p=>`${p.x},${p.y},${p.z}`,axes=['x','y','z'],move=(p,t)=>({x:p.x+t.x,y:p.y+t.y,z:p.z+t.z});
const sha=async p=>{const h=createHash('sha256');for await(const b of createReadStream(p))h.update(b);return h.digest('hex');};
const state=b=>JSON.stringify([b.id,Object.entries(b.properties??{}).sort(([a],[b])=>a.localeCompare(b))]);
const frame=read(P+'floorplan-v3/frame-config.json'),f=structuredClone(frame),pins={};
for(const n of['core0','core1'])Object.assign(f.instances[n],{path:P+'control-reset-final-v1/design.json',manifest:P+'control-reset-final-v1/source-manifest.json',manifest_sha256:'131bd19104a1822a2c041ebf29b1f7c4271ca1eee4f6a233c47bfa89e427517b',previous_path:frame.instances[n].path});
f.instances.loader={...f.instances.loader,path:P+'memory/consumer-return-v1/design.json',manifest:P+'memory/consumer-return-v1/source-manifest.json',previous_path:frame.instances.loader.path};f.instances.loader.manifest_sha256=await sha(f.instances.loader.manifest);
for(const name of['master-program-data-v1','master-core-done-routes-v1','master-core-command-routes-v1','master-core-service-routes-v1','master-core-conditioning-routes-v1','master-memory-cold-routes-v1','master-memory-address-adapter-v1','master-bank-quiet-adapters-v1']){const manifest=P+name+'/source-manifest.json';f.route_deltas[name]={path:P+name+'/design.json',manifest,manifest_sha256:await sha(manifest),translation:{x:0,y:0,z:0}};}
function addPin(p,h){assert(!pins[p]||pins[p]===h,'Source conflict '+p);pins[p]=h;}
for(const c of [...Object.values(f.instances),...Object.values(f.route_deltas)]){assert.equal(await sha(c.manifest),c.manifest_sha256);addPin(c.manifest,c.manifest_sha256);const m=read(c.manifest);for(const[p,h]of Object.entries(m.files??m.source_sha256))addPin(p,h);}
for(const name of['source-manifest.json','frame-config.json','composition-checks.json'])addPin(P+'floorplan-v3/'+name,await sha(P+'floorplan-v3/'+name));
for(const[p,h]of Object.entries(pins))assert.equal(await sha(p),h,p);
const buckets=new Map(),keys=new Map(),nearBuckets=new Set(),bk=p=>axes.map(a=>Math.floor(p[a]/4));
function near(p){const k=bk(p);if(!nearBuckets.has(k.join(',')))return false;for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)for(const q of buckets.get([k[0]+x,k[1]+y,k[2]+z].join(','))??[])if(axes.every(a=>Math.abs(p[a]-q.position[a])<=3))return true;return false;}
let routeCount=0;const routeCounts={};
for(const[n,c]of Object.entries(f.route_deltas)){const d=read(c.path);routeCounts[n]=d.blocks.length;for(const r of d.blocks){const k=K(r.position);assert(!keys.has(k),'Two existing route deltas overlap '+n+' '+k);keys.set(k,{instance:n,block:r.block});const b=bk(r.position),j=b.join(',');if(!buckets.has(j)){buckets.set(j,[]);for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)nearBuckets.add([b[0]+x,b[1]+y,b[2]+z].join(','));}buckets.get(j).push(r);routeCount++;}}
const stats=[],failures=[],boxes={},sparse=new Map();
const groups=new Map();for(const[n,c]of Object.entries(f.instances)){if(!groups.has(c.path))groups.set(c.path,[]);groups.get(c.path).push({name:n,...c});}
for(const[path,instances]of groups){const d=read(path);for(const v of instances){const after=new Map(),box={from:{x:Infinity,y:Infinity,z:Infinity},to:{x:-Infinity,y:-Infinity,z:-Infinity}};let collisions=0;for(const r of d.blocks){const p=move(r.position,v.translation),k=K(p);for(const a of axes){box.from[a]=Math.min(box.from[a],p[a]);box.to[a]=Math.max(box.to[a],p[a]);}if(keys.has(k)){collisions++;if(failures.length<150)failures.push({type:'route_collision',instance:v.name,position:p,route:keys.get(k).instance});}if(near(p))after.set(k,state(r.block));}assert(box.from.y>=-64&&box.to.y<=319);boxes[v.name]={box,blocks:d.blocks.length};sparse.set(v.name,after);if(!v.previous_path){stats.push({instance:v.name,blocks:d.blocks.length,route_collisions:collisions,halo:after.size});continue;}
 const old=read(v.previous_path),before=new Map();for(const r of old.blocks){const p=move(r.position,v.translation);if(near(p))before.set(K(p),state(r.block));}let changed=0;for(const[k,s]of before)if(after.get(k)!==s){changed++;if(failures.length<150)failures.push({type:'old_halo_change',instance:v.name,position:k,before:s,after:after.get(k)??null});}for(const[k,s]of after)if(!before.has(k)){changed++;if(failures.length<150)failures.push({type:'added_halo_cell',instance:v.name,position:k,after:s});}stats.push({instance:v.name,old_blocks:old.blocks.length,new_blocks:d.blocks.length,old_halo:before.size,new_halo:after.size,changed_halo:changed,route_collisions:collisions});}
}
const out={status:failures.length?'replacement_requires_contact_repair':'current_core_replacement_preserves_existing_cable_halos',source_pins_verified:Object.keys(pins).length,route_cells:routeCount,route_counts:routeCounts,instances:boxes,replacements:stats,failures,native_acceptance:false,full_timing_acceptance:false,limits:['Exact existing master cable cells and Chebyshev-distance3 parent neighborhoods only; upcoming payload and bank-quiet cables must be added before final frame admission.','Each source-bound route retains its own electrical proof. This is not a new inter-delta electrical proof or a final whole-machine composition receipt.']};
writeFileSync(new URL('replacement-checks.json',H),JSON.stringify(out,null,2)+'\n');writeFileSync(new URL('frame-config.json',H),JSON.stringify(f,null,2)+'\n');writeFileSync(new URL('source-bindings.json',H),JSON.stringify(pins,null,2)+'\n');console.log(JSON.stringify(out));assert.equal(failures.length,0,'Core replacement changes existing master cable neighborhood');
