import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{P,K}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),base=read('../shared-clock-v1/design.json'),g=read('body.json'),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>K(a)+'>'+K(b),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch';
const before=new Map(base.blocks.map(b=>[K(b.position),b.block])),after=new Map(d.blocks.map(b=>[K(b.position),b.block]));assert.equal(after.size,d.blocks.length);for(const b of base.blocks)assert.deepEqual(after.get(K(b.position)),b.block);for(const b of g.blocks)assert.deepEqual(after.get(K(b.position)),b.block);
const expected=new Set(),preserved=[];for(const b of base.blocks)if(active(b.block))for(const q of inputs(before,b.position)){expected.add(pair(q,b.position));preserved.push({from:q,to:b.position});}for(const e of d.body_internal){expected.add(pair(e.from,e.to));preserved.push(e);}for(const e of d.edges){expected.add(pair(e.from,e.to));if(after.get(K(e.from))?.id===W&&after.get(K(e.to))?.id===W)expected.add(pair(e.to,e.from));}
const actual=new Set,unexpected=[];let supports=0,receivers=0;for(const b of d.blocks){if([W,R,C,T].includes(b.block.id)){assert(after.get(K(P(b.position.x,b.position.y-1,b.position.z)))?.id.endsWith('_concrete'),'Support '+K(b.position));supports++;}if(!active(b.block))continue;receivers++;for(const q of inputs(after,b.position)){const p=pair(q,b.position);actual.add(p);if(!expected.has(p))unexpected.push({from:q,to:b.position,source:after.get(K(q)),target:b.block});}}
const lost=preserved.filter(e=>!actual.has(pair(e.from,e.to))),missing=d.edges.filter(e=>!actual.has(pair(e.from,e.to)));const dirs={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},stores=[];for(const b of d.blocks){if(b.block.id!==R)continue;const v=dirs[b.block.properties.facing],locks=[];for(const s of Object.values(dirs)){if(v.x*s.x+v.z*s.z)continue;const p=A(b.position,s),q=after.get(K(p));if([R,C].includes(q?.id)&&K(A(p,dirs[q.properties.facing]))===K(b.position))locks.push(p);}if(locks.length)stores.push({position:b.position,locks});}assert.equal(stores.length,1002);
const routeReports=[];for(const r of d.connections){assert.deepEqual(inputs(after,r.tap),[r.source]);assert.deepEqual(inputs(after,r.arrival),[r.end]);let power=r.source_high,minimum=15,ticks=0;const path=[r.source,r.tap,...r.path,r.arrival,r.destination];for(let i=1;i<path.length;i++){const p=path[i],b=after.get(K(p)),prev=after.get(K(path[i-1]));assert(inputs(after,p).some(q=>K(q)===K(path[i-1])),'Missing cable edge '+r.name+' '+K(p));if(b.id===R){minimum=Math.min(minimum,power);assert(power>0);power=15;ticks+=2*Number(b.properties.delay);}else if(b.id===C){assert.equal(i,path.length-1);assert.equal(power,15);}else{assert.equal(b.id,W);power-=prev.id===W?1:0;assert(power>0);}}assert.equal(power,15);routeReports.push({name:r.name,nominal_route_ticks:ticks,minimum_rear_high:minimum,arrival_high:15});}
// Actual new phase-to-lock reach with only the two retained admission stores
// cut at their data inputs. This is structural phase identity, not a timing cut.
const cut=new Set(['-72,186,-246','-60,186,-246']),newKeys=new Set(d.blocks.filter(b=>!before.has(K(b.position))).map(b=>K(b.position))),adj=new Map;for(const b of d.blocks){if(!newKeys.has(K(b.position))||cut.has(K(b.position))||!active(b.block))continue;for(const q of inputs(after,b.position)){const k=K(q);if(!adj.has(k))adj.set(k,[]);adj.get(k).push(K(b.position));}}
function reach(source){const seen=new Set([K(source)]),q=[K(source)];for(let i=0;i<q.length;i++)for(const t of adj.get(q[i])??[])if(!seen.has(t)){seen.add(t);q.push(t);}return seen;}
const locks=['-72,186,-245','-60,186,-245'];for(const [i,n]of['phase_a','phase_b'].entries()){const seen=reach(d.ports.rf_control[n].bits[0].position);assert(seen.has(locks[i]));assert(!seen.has(locks[1-i]));}
let negatives=0;for(const r of d.connections){const old=after.get(K(r.arrival));after.set(K(r.arrival),{...old,properties:{...old.properties,facing:({east:'west',west:'east',north:'south',south:'north'})[old.properties.facing]}});assert(!inputs(after,r.destination).some(p=>K(p)===K(r.arrival)));after.set(K(r.arrival),old);negatives++;}
const report={status:unexpected.length||missing.length||lost.length?'refused':'actual_RF_conditioning_admission_geometry_passed',metrics:d.metrics,supports,receivers,stores:stores.length,preserved_dependencies:preserved.length,actual_dependencies:actual.size,unexpected,lost,missing,routes:routeReports,phase_lock_identity_checks:2,negative_checks:negatives,complete_core:false,native_acceptance:false};writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,unexpected:unexpected.slice(0,20),lost:lost.slice(0,20),missing:missing.slice(0,20)},null,2));assert.equal(report.status,'actual_RF_conditioning_admission_geometry_passed');
