// Settled power propagation over actual new cells, with declared held-source
// boundaries. This is not a transient, clock-skew or cold-convergence proof.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),base=read('../shared-clock-v1/design.json'),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},world=new Map(d.blocks.map(b=>[K(b.position),b.block])),old=new Set(base.blocks.map(b=>K(b.position))),positions=d.blocks.filter(b=>!old.has(K(b.position))&&active(b.block)).map(b=>b.position),normalPads=[[148,50,-330],[164,50,-330],[148,50,-318],[164,50,-318],[172,50,-330]],normalDrivers=[[147,50,-330],[165,50,-330],[147,50,-318],[165,50,-318],[173,50,-330]],outputs=[...normalPads.map(v=>P(...v)),P(-40,188,-238),P(480,-57,-220)],extra=[...normalDrivers.map(v=>P(...v)),...outputs];
positions.push(...extra);const keys=new Set(positions.map(K)),nodes=[...keys].map(k=>({k,p:Object.fromEntries(['x','y','z'].map((x,i)=>[x,+k.split(',')[i]])),b:world.get(k)}));for(const n of nodes){n.preds=inputs(world,n.p).map(K);n.side=[];if(n.b.id===C){const v=D[n.b.properties.facing];n.side=n.preds.filter(k=>{const q=k.split(',').map(Number);return q[1]===n.p.y&&Math.abs(q[0]-n.p.x)+Math.abs(q[2]-n.p.z)===1&&(q[0]-n.p.x)*v.x+(q[2]-n.p.z)*v.z===0;});}}
const by=new Map(nodes.map(n=>[n.k,n])),followers=new Map;for(const n of nodes)for(const q of n.preds){if(!followers.has(q))followers.set(q,[]);followers.get(q).push(n.k);}
const boundaries={};function evaluate({ready,admitted,phase,scan,normal},mutation){const fixed=new Map;for(const c of d.connections.filter(c=>c.name.startsWith('scan_bit_')))fixed.set(K(c.source),(scan>>Number(c.name.at(-1))&1)?14:0);for(const n of['READY_to_decoder_masks'])fixed.set(K(d.connections.find(c=>c.name===n).source),ready?15:0);fixed.set(K(d.ports.rf_control.phase_a.bits[0].position),phase?15:0);fixed.set(K(d.ports.rf_control.phase_b.bits[0].position),0);fixed.set('-60,186,-246',admitted?15:0);fixed.set('-72,186,-246',ready?15:0);
for(let bit=0;bit<5;bit++){const n=by.get(K(P(...normalDrivers[bit]))),ext=n.preds.filter(k=>!keys.has(k));assert.equal(ext.length,1);fixed.set(ext[0],normal>>bit&1?15:0);boundaries['normal_bit_'+bit]=ext[0];}
const power=new Map(nodes.map(n=>[n.k,0])),queue=nodes.map(n=>n.k),waiting=new Set(queue);let updates=0;const val=k=>fixed.get(k)??power.get(k)??0;for(let i=0;i<queue.length;i++){const k=queue[i];waiting.delete(k);const n=by.get(k);let v;if(fixed.has(k))v=fixed.get(k);else if(n.b.id===W)v=Math.max(0,...n.preds.map(q=>val(q)-(world.get(q)?.id===W?1:0)));else if(n.b.id===R)v=n.preds.some(q=>val(q)>0)?15:0;else if([T,WT].includes(n.b.id))v=n.preds.some(q=>val(q)>0)?0:15;else if(n.b.id===C){const rear=Math.max(0,...n.preds.filter(q=>!n.side.includes(q)).map(val)),side=Math.max(0,...n.side.map(val));v=n.b.properties.mode==='subtract'?Math.max(0,rear-side):(rear>=side?rear:0);}else v=0;if(mutation?.k===k)v=mutation.value;if(v!==power.get(k)){power.set(k,v);updates++;assert(updates<400000,'Settled propagation did not converge');for(const q of followers.get(k)??[])if(!waiting.has(q)){queue.push(q);waiting.add(q);}}}
const word=outputs.slice(0,5).reduce((x,p,i)=>x|((val(K(p))>0?1:0)<<i),0);return{word,window:val(K(outputs[5]))>0,initialize:val(K(outputs[6]))>0,updates};}
let cases=0,maxUpdates=0;for(let phase=0;phase<2;phase++)for(let ready=0;ready<2;ready++)for(let admitted=0;admitted<2;admitted++)for(let scan=0;scan<32;scan++){const normal=scan^31,r=evaluate({phase,ready,admitted,scan,normal});assert.equal(r.word,ready?normal:scan,JSON.stringify({phase,ready,admitted,scan,r}));assert.equal(r.window,Boolean(phase&&ready&&admitted));assert.equal(r.initialize,!ready||!admitted);cases++;maxUpdates=Math.max(maxUpdates,r.updates);}
// Suppression and clamp corruptions actually perturb the computed gate graph.
let negatives=0;for(const m of[{k:'-40,188,-243',value:15},{k:'-40,188,-239',value:15},{k:'479,-57,-220',value:0}]){let rejected=false;for(let ready=0;ready<2;ready++)for(let admitted=0;admitted<2;admitted++){const r=evaluate({phase:1,ready,admitted,scan:21,normal:10},m);if(r.window!==Boolean(ready&&admitted)||r.initialize!==(!ready||!admitted))rejected=true;}assert(rejected,JSON.stringify(m));negatives++;}
const report={status:'actual_settled_RF_scan_normal_window_clamp_logic_passed',cases,negative_checks:negatives,active_nodes:nodes.length,max_updates:maxUpdates,normal_source_boundaries:boundaries,clock_timing:false,cold_convergence:false,native_acceptance:false};writeFileSync(new URL('logic-checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
