import{fileURLToPath}from'node:url';import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),B=new URL('../../',H),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),read=n=>JSON.parse(readFileSync(new URL(n,H)));
const ref=readLargeDesign(fileURLToPath(new URL('compact-core-guard-v1/design.json',B))),world=new Map(ref.blocks.map(b=>[K(b.position),b.block])),over=read('../../register-startup-v1/override-v1/design.json'),admit=read('../shared-state-inventory-v1/bodies.json').groups.find(g=>g.name==='RF_admission'),origin=P(900,53,0),delta=P(-750,0,-330),base=read('../shared-clock-v1/design.json'),parent=new Map(base.blocks.map(b=>[K(b.position),b.block]));
const blocks=[],original=new Set,parts={};function take(b){const old=b.position,k=K(old);if(original.has(k))return;const block=world.get(k);assert(block,k);original.add(k);const position=A(old,delta),prior=parent.get(K(position));if(prior){assert.deepEqual(prior,block);return;}blocks.push({position,original_position:old,block,body:'RF_conditioning',seed_part:b.part??b.original_part});parts[b.part??b.original_part]=(parts[b.part??b.original_part]??0)+1;}
for(const b of over.blocks){const n=b.part;let yes=/^scan_input_[0-4]$/.test(n)||/^scan[0-4]_(lift_driver|lift|arrive)$/.test(n)||/^ready[0-4]_(column|scan_mask|scan_terminal|branch|feed|driver)$/.test(n)||/^not_ready[0-4]_(lift_driver|lift|arrive|normal_terminal|bus_feed)$/.test(n)||['not_ready_tap','not_ready_bus','not_ready_first_normalizer','not_ready_first_column'].includes(n);
if(n==='ready_return'&&b.position.z===-12&&b.position.x>=-12&&b.position.x<=28)yes=true;
if(/^scan[0-4]_return$/.test(n)){const bit=Number(n[4]),pads=[[-2,0],[14,0],[-2,12],[14,12],[22,0]],baseY=-48+4*bit,[x,z]=pads[bit];yes=b.position.x===x&&b.position.z===z-10&&[baseY-1,baseY].includes(b.position.y);}
if(yes)take({...b,position:A(b.position,origin)});}
for(const b of admit.blocks)take(b);
const claimed=new Set(blocks.map(b=>K(b.original_position))),mapToNew=p=>A(p,delta),referenceRF=read('../shared-spine-v1/bodies.json').groups.find(g=>g.name==='rf_control'),rfPositions=new Set(referenceRF.blocks.map(b=>K(b.original_position))),edges=[],crossings=[];
for(const b of ref.blocks){const target=claimed.has(K(b.position));if(!active(b.block))continue;for(const q of inputs(world,b.position)){const source=claimed.has(K(q));if(!source&&!target)continue;if((source||rfPositions.has(K(q)))&&(target||rfPositions.has(K(b.position))))edges.push({from:mapToNew(q),to:mapToNew(b.position)});else crossings.push({from:q,to:b.position,source_claimed:source,target_claimed:target});}}
const out={status:'actual_RF_conditioning_logic_extracted',blocks,internal:edges,crossings,parts,delta,actual_stores:2,source_sha256:{reference:createHash('sha256').update(readFileSync(new URL('compact-core-guard-v1/design.json',B))).digest('hex')}};writeFileSync(new URL('body.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({cells:blocks.length,edges:edges.length,parts,crossings}));
