// Exact small-control extraction before any offline relocation. No game calls.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{readLargeDesign}from'../../../hardware/memory-layout-large-json-v2.mjs';
const B=new URL('../',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,B))),sha=n=>createHash('sha256').update(readFileSync(new URL(n,B))).digest('hex'),K=p=>[p.x,p.y,p.z].join(','),P=(x,y,z)=>({x,y,z}),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z);
const current=readLargeDesign(fileURLToPath(new URL('control-reset-master-compatible-v3/design.json',B))),actual=new Map(current.blocks.map(v=>[K(v.position),v])),old=read('control-commit-v2/design.json'),fault=read('control-event-gates-v1/sticky_fault.json'),routeFile=read('control-commit-v2/routes.json');
const names=['branch_fault_update','branch_fault_agreement','branch_fault_to_sticky','branch_fault_idle','branch_fault_phase','alu_fault_to_sticky','sticky_fault_next','sticky_fault_current','sticky_fault_clear','immediate_or_retained_fault'];
const cells=[...fault.blocks.map(v=>({...v,position:add(v.position,P(530,280,-720))})),...old.blocks.filter(v=>['branch_fault_gate','branch_fault_admission'].includes(v.part))],component=new Set(cells.map(v=>K(v.position)));assert.equal(cells.length,component.size);
const differences=[];for(const v of cells){const a=actual.get(K(v.position));if(JSON.stringify(a?.block)!==JSON.stringify(v.block))differences.push({position:v.position,expected:v.block,actual:a?.block??null});}
const extra=[['control-core-guards-v1','done_fault'],['control-lsu-core-v1','core_fault_request'],['control-lsu-core-v1','lsu_fault_to_core'],['control-reset-scratch-v1','retained_core_fault'],['control-reset-zero-v1','fault_blocks_zero_actions']];
for(const[folder,name]of extra){const r=read(folder+'/routes.json')[name];routeFile[name]=r;names.push(name);const midpoint=(a,b)=>P((a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2);const tap=midpoint(r.source,r.path[0]),arrival=midpoint(r.destination,r.path.at(-1));assert([tap,arrival].every(p=>['x','y','z'].every(a=>Number.isInteger(p[a]))));old.connections.push({name,source:r.source,destination:r.destination,tap,arrival});}
const routes=names.map(n=>{const r=routeFile[n],c=old.connections.find(v=>v.name===n);assert(r&&c);const missing=r.path.filter(p=>!['minecraft:redstone_wire','minecraft:repeater'].includes(actual.get(K(p))?.block.id));return{name:n,...c,path:r.path,points:r.path.length,missing_current_points:missing,source_is_component:component.has(K(c.source)),destination_is_component:component.has(K(c.destination)),source_moves_with_cluster:component.has(K(c.source))||n==='fault_blocks_zero_actions',destination_moves_with_cluster:component.has(K(c.destination))};});
const anchors=routes.flatMap(r=>[r.source,r.destination].filter(p=>component.has(K(p))));const box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=Math.min(...cells.map(v=>v.position[a]));box.to[a]=Math.max(...cells.map(v=>v.position[a]));}
const out={status:'extracted_control_cluster_not_relocated',source_sha256:Object.fromEntries(['control-reset-master-compatible-v3/design.json','control-commit-v2/design.json','control-event-gates-v1/sticky_fault.json','control-commit-v2/routes.json',...extra.map(([folder])=>folder+'/routes.json')].map(n=>['artifacts/full-gpu-layout-v1/'+n,sha(n)])),cluster_cells:cells,cluster_box:box,cluster_cell_mismatches:differences,connections:routes,anchor_positions:anchors,extra_route_sources:extra.map(([folder,name])=>({folder,name,sha256:sha(folder+'/routes.json')})),protected_source_prefixes:['sticky_fault_next','branch_fault_idle'],protected_destination_suffixes:['fault_blocks_zero_actions'],ports:fault.ports,complete_gpu_layout:false,native_acceptance:false};writeFileSync(new URL('extraction.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({cluster_cells:cells.length,cell_mismatches:differences.length,routes:routes.length,missing_current_points:routes.map(v=>[v.name,v.missing_current_points.length]),box}));
