// Materialize an exact replacement core with every exported moved port rebound.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
import{readLargeDesign,writeLargeDesign}from'../../../hardware/memory-layout-large-json-v2.mjs';import{K,add}from'./layout.mjs';
const read=n=>readLargeDesign(fileURLToPath(new URL(n,import.meta.url))),d=read('trial-design.json'),e=read('extraction.json'),checks=read('checks.json'),old=read('../control-reset-master-compatible-v3/design.json');
assert.equal(checks.status,'relocation_actual_cell_dependency_screen_passed');const sha=n=>createHash('sha256').update(readFileSync(new URL(n,import.meta.url))).digest('hex');assert.equal(checks.source_sha256['artifacts/full-gpu-layout-v1/compact-core-fault-v1/trial-design.json'],sha('trial-design.json'));
const removed=new Map(d.removed.map(v=>[K(v.position),v])),moves=new Map(e.cluster_cells.map(v=>[K(v.position),add(v.position,d.candidate.translation)]));
for(const r of e.connections){if(r.source_moves_with_cluster)moves.set(K(r.source),add(r.source,d.candidate.translation));if(r.destination_moves_with_cluster)moves.set(K(r.destination),add(r.destination,d.candidate.translation));}
const portMoves=[];function remap(value,path='ports'){if(!value||typeof value!=='object')return value;if(['x','y','z'].every(a=>Number.isInteger(value[a]))){const k=K(value);if(moves.has(k)){const to=moves.get(k);portMoves.push({path,from:value,to});return to;}assert(!removed.has(k),'Deleted exported port '+path+' '+k);return value;}if(Array.isArray(value))return value.map((v,i)=>remap(v,path+'.'+i));return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,remap(v,path+'.'+k)]));}
const blocks=[];let count=0;for(const row of old.blocks){const r=removed.get(K(row.position));if(r){assert.deepEqual(row.block,r.block);count++;}else blocks.push(row);}assert.equal(count,removed.size);blocks.push(...d.blocks);assert.equal(new Set(blocks.map(v=>K(v.position))).size,blocks.length);
const ports=remap(old.ports),box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=Infinity;box.to[a]=-Infinity;for(const row of blocks){box.from[a]=Math.min(box.from[a],row.position[a]);box.to[a]=Math.max(box.to[a],row.position[a]);}}
const out={...old,status:'materialized_compact_fault_core_pending_timing_review',blocks,ports,box,edges:d.edges,connections:d.connections,routes:d.connections.map(v=>({name:v.name,path:v.path})),removed:d.removed,metrics:{...old.metrics,blocks:blocks.length,compact_fault_removed:d.removed.length,compact_fault_added:d.blocks.length,compact_fault_savings:d.metrics.net_cell_reduction},master_composition_accepted:false,complete_gpu_layout:false,native_acceptance:false,compact_fault_parent:{path:'artifacts/full-gpu-layout-v1/control-reset-master-compatible-v3/design.json',sha256:sha('../control-reset-master-compatible-v3/design.json')},compact_fault_patch_sha256:sha('trial-design.json'),route_metadata_scope:'Only the moved cluster and its fifteen incident routes are listed here. Full-core dependencies must be reconstructed from actual blocks; historical metadata remains in the pinned parent.'};
writeLargeDesign(fileURLToPath(new URL('design.json',import.meta.url)),out);writeFileSync(new URL('materialization.json',import.meta.url),JSON.stringify({status:out.status,blocks:blocks.length,retained_bits:out.metrics.retained_bits,port_moves:portMoves,box,parent:out.compact_fault_parent,trial_sha256:out.compact_fault_patch_sha256,design_sha256:sha('design.json'),complete_gpu_layout:false,native_acceptance:false},null,2)+'\n');console.log(JSON.stringify({blocks:blocks.length,savings:d.metrics.net_cell_reduction,retained_bits:out.metrics.retained_bits,exported_port_positions_rebound:portMoves.length}));
