import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{makeCommitIntegration}from'./prepare.mjs';import{possibleStrengths}from'../register-sequencer-v1/connected-controller/check-strength-independent.mjs';import{checkProtocol}from'./protocol.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(D),pair=(a,b)=>[K(a),K(b)].sort().join('|'),S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',diode=b=>['minecraft:repeater','minecraft:comparator'].includes(b?.id),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export function screen(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(Object.keys(d.parents)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,contacts=0,sides=0,rears=0,sets=0;
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;let p=P(v.position.x,v.position.y-1,v.position.z);if(v.block.id==='minecraft:redstone_wall_torch'){const[x,z]=D[v.block.properties.facing];p=P(v.position.x+x,v.position.y,v.position.z+z);}assert.equal(at(p)?.block.id,S,'Support '+K(v.position));supports++;}
 for(const v of d.blocks.filter(v=>v.block.id===W))for(const[x,z]of dirs)for(const dy of[-1,0,1]){const p=P(v.position.x+x,v.position.y+dy,v.position.z+z),b=at(p);if(!b||b.block.id.endsWith('_concrete')||v.part===b.part&&parents.has(v.part))continue;if(dy&&b.block.id!==W)continue;if(dy===1&&at(P(v.position.x,v.position.y+1,v.position.z)))continue;if(dy===-1&&at(P(p.x,p.y+1,p.z)))continue;assert(allowed.has(pair(v.position,p)),'Foreign '+v.part+' '+K(v.position)+' -> '+b.part+' '+K(p));contacts++;}
 for(const v of d.blocks.filter(v=>diode(v.block))){const[x,z]=D[v.block.properties.facing];for(const[dx,dz]of[[z,x],[-z,-x]]){const b=at(P(v.position.x+dx,v.position.y,v.position.z+dz));if(diode(b?.block)&&!(b.part===v.part&&parents.has(v.part)))assert(allowed.has(pair(v.position,b.position)),'Foreign diode side '+K(v.position));sides++;}if(!parents.has(v.part)&&v.block.id==='minecraft:repeater'){const rear=P(v.position.x-x,v.position.y,v.position.z-z),out=P(v.position.x+x,v.position.y,v.position.z+z);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'New diode direction '+K(v.position));rears++;}}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);assert.equal(at(P(c.x,c.top,c.z))?.block.id,W);for(let y=c.bottom;y<c.top;y+=2){const p=P(c.x,y,c.z),got=[];assert.equal(at(p)?.block.id,S);assert.equal(at(P(c.x,y+1,c.z))?.block.id,y+1===c.top?W:'minecraft:redstone_torch');for(const[x,z]of dirs){const q=P(p.x-x,y,p.z-z),b=at(q)?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z]))got.push(K(q));}for(const[dy,id]of[[1,W],[-1,'minecraft:redstone_torch']]){const q=P(c.x,y+dy,c.z);if(at(q)?.block.id===id)got.push(K(q));}
  const entries=[c.entry,...c.extra_entries??[]].filter(e=>e.y===y);for(const e of entries){assert.equal(at(e)?.block.id,'minecraft:repeater','Column feed must be a diode');assert.deepEqual(P(e.x+D[at(e).block.properties.facing][0],e.y,e.z+D[at(e).block.properties.facing][1]),p);}
  const want=[K(y===c.bottom?c.entry:P(c.x,y-1,c.z)),...(c.extra_entries??[]).filter(p=>p.y===y).map(K)];if(y===c.top-1)want.push(K(P(c.x,c.top,c.z)));assert.deepEqual(got.sort(),want.sort(),'Column source '+c.name+' '+K(p));sets++;
 }}

 let mediated=0,cross=0,diodeFeeds=0,stairs=0;
 for(const solid of d.blocks.filter(v=>v.block.id===S)){const p=solid.position,src=[],dst=[];for(const[x,z]of dirs){let v=at(P(p.x-x,p.y,p.z-z)),b=v?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z]))src.push(v);v=at(P(p.x+x,p.y,p.z+z));b=v?.block;if(b?.id===W||diode(b)&&eq(D[b.properties.facing],[x,z])||b?.id==='minecraft:redstone_wall_torch'&&eq(D[b.properties.facing],[-x,-z]))dst.push(v);}const up=at(P(p.x,p.y+1,p.z)),down=at(P(p.x,p.y-1,p.z));if(up?.block.id===W)src.push(up);if(down?.block.id==='minecraft:redstone_torch')src.push(down);if([W,'minecraft:redstone_torch'].includes(up?.block.id))dst.push(up);if(down?.block.id===W)dst.push(down);for(const a of src)for(const b of dst){if(a===b||a.part===b.part&&parents.has(a.part))continue;mediated++;if(a.part===b.part)continue;cross++;if(a.block.id==='minecraft:repeater'&&b.block.id==='minecraft:redstone_torch'){const c=d.columns.find(c=>p.x===c.x&&p.z===c.z&&[c.entry,...c.extra_entries??[]].some(e=>eq(e,a.position)));assert(c);assert.equal((p.y-c.bottom)%4,0);assert.deepEqual(b.position,P(c.x,p.y+1,c.z));diodeFeeds++;}else{assert.equal(a.block.id,W);assert.equal(b.block.id,W);assert(allowed.has(pair(a.position,b.position)),'Unlisted solid stair pair '+K(p));stairs++;}}}

 const events=checkEvents(d);const capacity=possibleStrengths({...d,parents:[...parents].map(id=>({id}))});assert.equal(capacity.failed.length,0,JSON.stringify(capacity.failed));for(const t of capacity.taps){const c=d.connections.find(c=>c.name===t.name),id=at(c.source)?.block.id;t.source_type=id;if(['minecraft:redstone_torch','minecraft:redstone_block'].includes(id)){t.source_power=15;t.tap_power=15;t.capacity_basis=id==='minecraft:redstone_block'?'Actual constant source':'Possible direct torch output; phase/Boolean assertion remains separate';}}return{supports,listed_contacts:contacts,diode_side_faces:sides,new_directed_repeaters:rears,positive_column_source_sets:sets,conservative_solid_paths:mediated,cross_part_solid_paths:cross,actual_diode_column_feeds:diodeFeeds,same_net_stair_pairs:stairs,event_checks:events,...capacity};}

function checkEvents(d){const m=new Map(d.blocks.map(v=>[K(v.position),v.block])),at=p=>m.get(K(p)),expectRep=(p,travel)=>{assert.equal(at(p)?.id,'minecraft:repeater');assert.deepEqual(D[at(p).properties.facing],travel);};
 const or=d.columns.find(c=>c.name==='owner_request_or');assert.deepEqual([or.bottom,or.top],[225,250]);assert.deepEqual(or.extra_entries,[P(667,233,-420)]);for(const y of[225,233])expectRep(P(667,y,-420),[1,0]);
 const gate=P(660,253,-352);assert.equal(at(gate)?.id,'minecraft:comparator');assert.deepEqual(at(gate).properties,{facing:'west',mode:'subtract'});expectRep(P(659,253,-352),[1,0]);expectRep(P(661,253,-352),[1,0]);expectRep(P(660,253,-353),[0,1]);
 assert.deepEqual(at(P(683,253,-440)),{id:'minecraft:redstone_wall_torch',properties:{facing:'east'}});expectRep(P(681,253,-440),[1,0]);assert.equal(at(P(682,253,-440))?.id,S);
 assert.deepEqual(at(P(820,233,-413)),{id:'minecraft:redstone_wall_torch',properties:{facing:'south'}});expectRep(P(820,233,-415),[0,1]);assert.equal(at(P(820,233,-414))?.id,S);
 for(const[name,port,bit]of[['held_owner_kind0_to_rf','event_kind_0',0],['held_owner_kind1_to_rf','event_kind_1',1],['held_owner_request_to_rf','event_request',0]]){const c=d.connections.find(c=>c.name===name);assert.deepEqual(c.destination,d.ports.rf[port].bits[0].position);assert.deepEqual(c.source,(name.includes('request')?d.ports.rf_intent:d.ports.owner_kind).state.bits[bit].position);}
 for(const[name,port,index]of[['rf_ack_to_owner_wait','advance_conditions',4],['rf_ack_low_to_owner_release','advance_conditions',6]])assert.deepEqual(d.connections.find(c=>c.name===name).destination,d.ports.owner[port].bits[index].position);
 let values=0;for(let state=0;state<8;state++)for(let phase=0;phase<2;phase++){let level=false;for(let y=or.bottom;y<or.top;y+=2){const injected=(y===225&&state===3)||(y===233&&state===4);if(y===or.top-1)break;level=!(level||injected);}assert.equal(level,state===3||state===4);const mask=!(state===1),open=!!phase&&!mask;assert.equal(open,!!phase&&state===1);values++;}
 const constants=d.connections.filter(c=>c.name.includes('full_cycle_advance'));assert.equal(constants.length,7);for(const c of constants)assert.equal(at(c.source)?.id,'minecraft:redstone_block');return{event_polarity_cases:values,actual_constant_advances:constants.length,held_field_bindings:3,actual_ack_polarities:2};}

const d=makeCommitIntegration();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));let rejected=0;for(const mutate of[c=>c.blocks.find(v=>K(v.position)==='667,233,-420').block={id:W},c=>c.blocks.find(v=>K(v.position)==='660,253,-352').block.properties.facing='east',c=>c.blocks.find(v=>K(v.position)==='820,233,-413').block.properties.facing='north',c=>c.connections.find(v=>v.name==='held_owner_kind0_to_rf').destination.y+=4]){const bad=structuredClone(d);mutate(bad);assert.throws(()=>screen(bad));rejected++;}const r={corruption_refusals:rejected,status:'draft_route_screen_only',...d.metrics,...screen(d),protocol_reference:checkProtocol(),native_acceptance:false,complete_controller:false,missing:d.missing};if(process.argv.includes('--save'))writeFileSync(new URL('draft-checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r));
