// Complete the independent review with ancestry, numerical cross-checks,
// actual physical mutations and exact counted cost. Imports rebuild the map.
import assert from 'node:assert/strict';
import {pins,P,K,W,R,C,T,WT,bytes,read,write,insert} from './common.mjs';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
import {makeSettledEvaluator} from '../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs';
import {BDD,cone,symbolic} from './network.mjs';
import {S,d,parent,ep,oldEp,decl,base,world,old,oldCount,sourceProofs,oldSeeds,currentSeeds,aliasMutations,bodyRows,addedKeys,receivers,supports,actualInputs,priorInputs,newInputs,stores,columns,names,states,maskNames,bdd,expected,observedOld,observedCurrent,currentPositions,oldPositions,current,original,passive} from './review.mjs';
const tapNames=['scratch0','zero_active0','epoch_enable0'],tapProofs=[],duplicateMutations=[],rejected=read(S+'history/redundant-feedback-draft-v1/design-delta.json'),rejectedWorld=new Map(base);insert(rejectedWorld,rejected.logic_bodies.flatMap(g=>g.blocks));insert(rejectedWorld,rejected.added);assert.equal(rejectedWorld.size,997427);
for(const name of tapNames){const descriptor=decl.historical_taps.find(t=>t.name==='released_'+name),tip=ep.mapping[K(descriptor.source)].position,roots=[currentSeeds[name]],oldRoots=[oldSeeds[name]],ps=cone(base,[tip],roots),oldps=cone(old,[descriptor.source],oldRoots),nonBoundary=new Set(ps.filter(p=>!roots.some(q=>K(p)===K(q))).map(K));for(const p of ps)if(nonBoundary.has(K(p)))for(const q of inputs(base,p))assert(nonBoundary.has(K(q))||K(q)===K(roots[0]));const direct=passive(base,tip),ev=makeSettledEvaluator(base,ps,roots),oldEv=makeSettledEvaluator(old,oldps,oldRoots),values=[0,15].map(v=>({source:v,parent_tap:ev(new Map([[K(roots[0]),v]])).power.get(K(tip))??0,old_tap:oldEv(new Map([[K(oldRoots[0]),v]])).power.get(K(descriptor.source))??0}));assert.deepEqual(values.map(v=>v.parent_tap),[0,5]);assert.deepEqual(values.map(v=>v.old_tap),[0,5]);assert(!d.connections.some(c=>c.name===name+'_restore_historical_source'));const after=passive(world,tip);assert.deepEqual(after.drivers,direct.drivers);const bad=passive(rejectedWorld,tip);assert.equal(direct.drivers.length,1);assert.equal(bad.drivers.length,2);const restoring=rejected.connections.find(c=>c.name===name+'_restore_historical_source');assert(restoring);assert(bad.drivers.some(p=>K(p)===K(restoring.arrival)));duplicateMutations.push({name,tip,parent_drivers:direct.drivers,rejected_drivers:bad.drivers,rejected_arrival:restoring.arrival});tapProofs.push({name,old_tip:descriptor.source,current_tip:tip,actual_old_seed:oldRoots[0],actual_current_seed:roots[0],old_nodes:oldps.length,parent_nodes:ps.length,values,actual_parent_driver:direct.drivers[0]});}
const stopOld=P(-416,197,433),stopCurrent=P(-144,218,643),stopReceiver=P(-144,218,645);assert(!base.has(K(stopCurrent)));assert.equal(inputs(base,stopReceiver).length,0);assert.deepEqual(ep.mapping[K(stopOld)].position,stopCurrent);assert(d.connections.some(c=>c.name==='zero_stop0_restore_historical_source'));const stopPs=cone(world,[stopCurrent,stopReceiver],[currentSeeds.zero_stop0]),stopEval=makeSettledEvaluator(world,stopPs,[currentSeeds.zero_stop0]);for(const v of [0,15]){const got=stopEval(new Map([[K(currentSeeds.zero_stop0),v]])).power;assert.equal(got.get(K(stopCurrent)),v);assert.equal(got.get(K(stopReceiver)),v);}
// Preserve the actual two-source downstream merge, while the historical warm
// tap remains only epoch_clear0. No initialize/cold same-name alias is used.
const warmOld=P(-104,64,-4),nominalOld=P(-104,64,-6),warmCurrent=ep.replacement_interface_map[K(warmOld)].position,nominalCurrent=ep.mapping[K(nominalOld)].position,oldMerge=passive(old,nominalOld),currentMerge=passive(world,nominalCurrent),priorMerge=passive(base,nominalCurrent);assert.equal(oldMerge.drivers.length,2);assert.equal(currentMerge.drivers.length,2);assert.equal(priorMerge.drivers.length,1);const currentCold=priorMerge.drivers[0],oldCold=oldMerge.drivers.find(p=>ep.mapping[K(p)]&&K(ep.mapping[K(p)].position)===K(currentCold));assert(oldCold,'Exact retained cold driver identity missing');const warmCases=[];
for(const [side,map,tip,target,roots]of [['old',old,warmOld,nominalOld,[oldSeeds.epoch_clear0,oldCold]],['current',world,warmCurrent,nominalCurrent,[currentSeeds.epoch_clear0,currentCold]]]){const ps=cone(map,[tip,target],roots),ev=makeSettledEvaluator(map,ps,roots);for(let mask=0;mask<4;mask++){const v=ev(new Map(roots.map((p,i)=>[K(p),mask>>i&1?15:0]))).power,warm=v.get(K(tip))??0,merged=v.get(K(target))??0;assert.equal(warm>0,!!(mask&1));assert.equal(merged>0,!!mask);warmCases.push({side,mask,warm,merged});}}assert(warmCases.some(r=>r.mask===2&&r.warm===0&&r.merged>0));aliasMutations.push({name:'warm_epoch_is_not_cold_merged_receiver',wrong_current_source:nominalCurrent,witness:{warm:0,cold:15}});
// Numeric cross-check deliberately uses independently selected sparse patterns
// and every combination of the five qualified-mask dependencies.
const bits=new Set([0,(1<<20)-1]);for(let i=0;i<20;i++){bits.add(1<<i);bits.add(((1<<20)-1)^(1<<i));for(let j=i+1;j<20;j++)bits.add((1<<i)|(1<<j));}const maskVariables=['initialize','zero_active0','epoch_clear0','epoch_clear1','epoch_clear2','epoch_clear3','withdrawal_local'];for(let n=0;n<128;n++){let m=0;maskVariables.forEach((name,i)=>{if(n>>i&1)m|=1<<names.indexOf(name);});bits.add(m);}
const numerical=makeSettledEvaluator(world,currentPositions,Object.values(currentSeeds)),oldNumerical=makeSettledEvaluator(old,oldPositions,Object.values(oldSeeds)),cases=[],observations=[...states,...maskNames,'guard','final_logic'];
for(const mask of bits){const values=seeds=>new Map(names.map((n,i)=>[K(seeds[n]),mask>>i&1?15:0])),a=oldNumerical(values(oldSeeds)).power,z=numerical(values(currentSeeds)).power,outputs={};for(const name of observations){const want=bdd.value(expected[name],mask)?15:0;assert.equal(a.get(K(observedOld[name]))??0,want);assert.equal(z.get(K(observedCurrent[name]))??0,want);assert.equal(current.value(observedCurrent[name],mask),want);outputs[name]=want;}cases.push({mask,outputs});}
const strengths=[];for(const c of d.connections){const predicate=current.at(c.actual_source)[1];assert(predicate,'Dead actual route source');let minimum=15;for(let i=1;i<c.path.length;i++)if(world.get(K(c.path[i])).id===R){const ins=inputs(world,c.path[i]);assert.equal(ins.length,1);let level=0;for(let k=1;k<=15;k++)if(bdd.and(predicate,bdd.not(current.at(ins[0])[k]))===0)level=k;assert(level>0);minimum=Math.min(minimum,level);}strengths.push({name:c.name,minimum_rear:minimum});}assert.equal(Math.min(...strengths.map(r=>r.minimum_rear)),4);
const reverse=b=>({...b,properties:{...b.properties,facing:{east:'west',west:'east',north:'south',south:'north'}[b.properties.facing]}}),mutations=[],oldMutations=[];
function mutate(map,baseline,positions,seeds,name,p,change){const saved=map.get(K(p));assert(saved);map.set(K(p),change(saved));let witness=null,refusal=null;try{const bad=symbolic(map,positions,seeds,bdd);let difference=0;for(let k=1;k<=15;k++)difference=bdd.or(difference,bdd.or(bdd.and(baseline.at(p)[k],bdd.not(bad.at(p)[k])),bdd.and(bad.at(p)[k],bdd.not(baseline.at(p)[k]))));assert(difference,'Mutation survived '+name);const mask=bdd.witness(difference),expected=baseline.value(p,mask),got=makeSettledEvaluator(map,positions,Object.values(seeds))(new Map(names.map((n,i)=>[K(seeds[n]),mask>>i&1?15:0]))).power.get(K(p))??0;assert.notEqual(got,expected,'Numeric witness failed '+name);witness={mask,expected,actual:got};}catch(e){if(String(e).includes('Mutation survived')||String(e).includes('Numeric witness failed'))throw e;refusal=String(e);}finally{map.set(K(p),saved);}return{name,position:p,witness,structural_refusal:refusal};}
for(const c of d.connections)mutations.push(mutate(world,current,currentPositions,currentSeeds,'reverse_arrival_'+c.name,c.arrival,reverse));
for(const name of [...states,...maskNames]){const p=observedCurrent[name],q=observedOld[name];mutations.push(mutate(world,current,currentPositions,currentSeeds,'reverse_guard_input_'+name,P(p.x+1,p.y,p.z),reverse));oldMutations.push(mutate(old,original,oldPositions,oldSeeds,'reverse_old_guard_input_'+name,P(q.x+1,q.y,q.z),reverse));}
for(const g of d.logic_bodies.filter(g=>g.kind.endsWith('_OR')||g.kind==='withdrawal_local_subtract'))for(const r of g.blocks){if(r.block.id===R)mutations.push(mutate(world,current,currentPositions,currentSeeds,'reverse_predicate_'+g.kind+'_'+K(r.position),r.position,reverse));if(r.block.id===C)mutations.push(mutate(world,current,currentPositions,currentSeeds,'bypass_actual_withdrawal_mask',r.position,b=>({...b,properties:{...b.properties,mode:'compare'}})));}
oldMutations.push(mutate(old,original,oldPositions,oldSeeds,'bypass_original_withdrawal_mask',P(-324,228,446),b=>({...b,properties:{...b.properties,mode:'compare'}})));assert.equal(mutations.length,64);assert.equal(oldMutations.length,20);
const count=rows=>{const out={};for(const r of rows)out[r.block.id]=(out[r.block.id]??0)+1;return out;},parentColumns=new Set(parent.blocks.map(r=>Math.floor(r.position.x/16)+','+Math.floor(r.position.z/16))),box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const r of d.blocks)for(const a of ['x','y','z']){box.from[a]=Math.min(box.from[a],r.position[a]);box.to[a]=Math.max(box.to[a],r.position[a]);}const cost={parent_cells:base.size,gate_interface_cells:bodyRows.length,cable_cells:d.added.length,total_cells:world.size,parent_columns:parentColumns.size,current_columns:columns.size,box,gate_materials:count(bodyRows),cable_materials:count(d.added),path_vertices:d.connections.reduce((n,c)=>n+c.path.length,0),new_routes:d.connections.length,no_removed_parent_cells:true};assert.equal(cost.path_vertices,10788);assert.equal(cost.parent_columns,3404);
for(const n of ['common.mjs','network.mjs','review.mjs','finish.mjs','../memory/fabric-colocation-v2/cut-inputs.mjs','../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs'])bytes(n);
write('receipt.json',{status:'passed_independent_core_stage_clear_sources_geometry_functions_and_mutations',metrics:{cells:world.size,parent_cells:base.size,receivers,supports,actual_inputs:actualInputs,preserved_inputs:priorInputs,new_device_inputs:newInputs,stores:stores.size,guard_cells:628,held_boundaries:20,retained_driver_boundaries:19,assignments:1048576,thresholds:15,qualified_guard_observations:21,numeric_cases:cases.length,current_mutations:mutations.length,old_mutations:oldMutations.length,duplicate_feedback_refusals:duplicateMutations.length,alias_refusals:aliasMutations.length,minimum_rear:4},current_symbolic:current.metrics,original_symbolic:original.metrics,source_identities:sourceProofs,tap_proofs:tapProofs,missing_zero_stop:{original:stopOld,current:stopCurrent,receiver:stopReceiver,parent_input_count:0},warm_before_cold:{old_warm:warmOld,current_warm:warmCurrent,old_nominal:nominalOld,current_nominal:nominalCurrent,actual_old_cold_driver:oldCold,actual_current_cold_driver:currentCold,cases:warmCases},numeric_cases:cases,strengths,mutations,old_mutations:oldMutations,duplicate_feedback_mutations:duplicateMutations,alias_mutations:aliasMutations,cost,source_sha256:pins,limits:['Nineteen actual retained output drivers and one existing undriven initialize input are held boundaries. Source production, state capture and pulse sequencing are not proved.','Independent threshold-BDD wire-component evaluator proves actual old/current mask and guard predicates; input physics model is shared and remains conditional.','Warm-only epoch return is distinct from the downstream actual cold merge. Three inherited weak feedback paths are reused; only missing zero-stop is restored among those four observations.','Cost and full map are exact frozen997299-cell final-stage-clear scope. Newer flags geometry, both-core placement and shared-frame integration are excluded.','Conditional100–354 nominal-tick claims are not evaluated as event bounds here. Full clock timing, reset convergence/release, native Minecraft and whole GPU acceptance remain open.']});console.log(JSON.stringify({status:'source_function_review_pass',numeric_cases:cases.length,current_mutations:mutations.length,old_mutations:oldMutations.length,duplicate_refusals:duplicateMutations.length,alias_refusals:aliasMutations.length,cost}));
