// Actual frozen core map, source identities and independent threshold functions.
import assert from 'node:assert/strict';
import {H,ROOT,pins,P,K,A,W,R,C,T,WT,D,solid,bytes,read,write,insert,scanBlocks} from './common.mjs';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
import {makeSettledEvaluator} from '../loader-program-colocation-v1/service-live-busy-delivery-v1/settled-dag.mjs';
import {BDD,cone,symbolic} from './network.mjs';
const S='../core-lane-colocation-v1/final-stage-clear-connected-v1/';
read(S+'source-manifest.json','a5d1c7f216e1c6263a6c31c691dcaccab1c4cc4e6ff91cdf73253b817d85feb1');
const d=read(S+'design.json','3a9eefac1388c7a4df50180958548de93e85c4be3807dc0c863fb511e368e4f2'),parent=read('../core-lane-colocation-v1/final-exit-control-connected-v1/design.json'),ep=read(S+'endpoint-map.json'),oldEp=read('../core-lane-colocation-v1/final-exit-control-connected-v1/endpoint-map.json'),decl=read(S+'original-functions.json'),originalStores=read('../core-lane-colocation-v1/stores.json').stores,base=new Map(),world=new Map(),old=new Map();insert(base,parent.blocks);insert(world,d.blocks);assert.equal(base.size,975791);assert.equal(world.size,997299);for(const[k,b]of base)assert.deepEqual(world.get(k),b);
const oldCount=scanBlocks(bytes('../compact-core-guard-v1/design.json'),r=>insert(old,[r]));assert.equal(oldCount,decl.original_cells);assert.equal(decl.gate.blocks.length,628);
for(const r of decl.gate.blocks){assert.deepEqual(old.get(K(r.original_position)),r.block);assert.deepEqual(base.get(K(r.position)),r.block);assert.deepEqual(ep.mapping[K(r.original_position)].position,r.position);}
for(const[k,v]of Object.entries(oldEp.mapping))assert.deepEqual(ep.mapping[k],v);assert.equal(Object.keys(ep.mapping).length-Object.keys(oldEp.mapping).length,8);
function passive(map,tip){assert.equal(map.get(K(tip)).id,W);const component=new Map([[K(tip),tip]]),queue=[tip];for(let i=0;i<queue.length;i++)for(const p of inputs(map,queue[i]))if(map.get(K(p))?.id===W&&inputs(map,p).some(q=>K(q)===K(queue[i]))&&!component.has(K(p))){component.set(K(p),p);queue.push(p);}const drivers=new Map();for(const p of component.values())for(const q of inputs(map,p))if(!component.has(K(q)))drivers.set(K(q),q);return{component:[...component.values()],drivers:[...drivers.values()]};}
const sourceProofs=[],oldSeeds={},currentSeeds={},aliasMutations=[];
for(const s of decl.sources){const a=passive(old,s.old_tip),b=passive(world,s.current_tip);assert.deepEqual(ep.mapping[K(s.old_tip)].position,s.current_tip);if(s.name==='initialize'){assert.equal(a.drivers.length,0);assert.equal(b.drivers.length,0);assert.deepEqual(s.old_seed,s.old_tip);assert.deepEqual(s.current_seed,s.current_tip);}else{assert.equal(a.drivers.length,1);assert.equal(b.drivers.length,1);assert.deepEqual(a.drivers[0],s.old_seed);assert.deepEqual(b.drivers[0],s.current_seed);assert.deepEqual(ep.mapping[K(a.drivers[0])].position,b.drivers[0]);assert.deepEqual(old.get(K(a.drivers[0])),world.get(K(b.drivers[0])));assert.equal(world.get(K(b.drivers[0])).id,R);}oldSeeds[s.name]=s.old_seed;currentSeeds[s.name]=s.current_seed;sourceProofs.push({name:s.name,old_seed:s.old_seed,current_seed:s.current_seed,old_tip:s.old_tip,current_tip:s.current_tip,old_passive:a,current_passive:b,block:world.get(K(s.current_seed))});}
assert.equal(sourceProofs.length,20);assert.equal(new Set(Object.values(currentSeeds).map(K)).size,20);assert.equal(new Set(Object.values(oldSeeds).map(K)).size,20);
for(let i=0;i<20;i++){const a=sourceProofs[i],b=sourceProofs[(i+1)%20];assert.throws(()=>assert.deepEqual(ep.mapping[K(a.old_seed)].position,b.current_seed));aliasMutations.push({name:a.name,wrong_same_schema_source:b.current_seed});}
// Derive every permitted new body edge from the isolated actual blocks and its
// explicit retained receiver, then every route edge from adjacent vertices.
const addedKeys=new Set([...world.keys()].filter(k=>!base.has(k))),bodyRows=d.logic_bodies.flatMap(g=>g.blocks),body=new Map();insert(body,bodyRows);assert.equal(body.size,64);assert.equal(d.added.length,21444);assert.equal(addedKeys.size,21508);for(const r of [...bodyRows,...d.added]){assert(addedKeys.has(K(r.position)));assert.deepEqual(world.get(K(r.position)),r.block);}const permitted=new Map(),add=(q,p)=>{const k=K(p);if(!permitted.has(k))permitted.set(k,new Set());permitted.get(k).add(K(q));};
for(const g of d.logic_bodies){const local=new Map(g.blocks.map(r=>[K(r.position),r.block]));if(g.ports.receiver){assert(base.has(K(g.ports.receiver)));local.set(K(g.ports.receiver),base.get(K(g.ports.receiver)));}for(const[k,b]of local)if(active(b)){const p=P(...k.split(',').map(Number));for(const q of inputs(local,p))add(q,p);}}
for(const c of d.connections){assert.equal(c.path.length,c.path_vertices??c.path.length);assert.deepEqual(c.path[0],c.actual_source);assert.deepEqual(c.path.at(-1),c.destination);for(let i=1;i<c.path.length;i++){const a=c.path[i-1],b=c.path[i];assert(inputs(world,b).some(q=>K(q)===K(a)));add(a,b);if(world.get(K(a)).id===W&&world.get(K(b)).id===W)add(b,a);}}
let receivers=0,supports=0,actualInputs=0,priorInputs=0,newInputs=0;const stores=new Map(),columns=new Set();
for(const[k,b]of world){const p=P(...k.split(',').map(Number));columns.add(Math.floor(p.x/16)+','+Math.floor(p.z/16));let support;if(b.id===WT)support=A(p,D[b.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(b.id))support=P(p.x,p.y-1,p.z);if(support){assert(solid(world.get(K(support))),'Missing support '+k);supports++;}if(active(b)){receivers++;const actual=inputs(world,p).map(K).sort(),expected=base.has(k)?inputs(base,p).map(K):[];priorInputs+=expected.length;expected.push(...permitted.get(k)??[]);assert.deepEqual(actual,[...new Set(expected)].sort(),'Unaccounted input '+k);actualInputs+=actual.length;if(!base.has(k))newInputs+=actual.length;}if(b.id===R){const v=D[b.properties.facing],locks=[];for(const s of Object.values(D)){if(v.x*s.x+v.z*s.z)continue;const q=A(p,s),bq=world.get(K(q));if([R,C].includes(bq?.id)&&K(A(q,D[bq.properties.facing]))===k)locks.push(q);}if(locks.length)stores.set(k,locks);}}
assert.equal(stores.size,1117);assert.equal(originalStores.length,1117);for(const s of originalStores){const p=ep.mapping[K(s.position)].position;assert.deepEqual(stores.get(K(p)).map(K).sort(),s.locks.map(q=>K(ep.mapping[K(q)].position)).sort());}assert.equal(priorInputs,817302);assert.equal(actualInputs,836930);assert.equal(receivers,498064);assert.equal(columns.size,3441);console.log('full map',world.size,receivers,actualInputs,stores.size);
const names=sourceProofs.map(r=>r.name),states=names.slice(0,14),maskNames=['arch_mask','epoch_mask','intent_mask','sample_mask','local_reset'],bdd=new BDD(names),variables=Object.fromEntries(names.map((n,i)=>[n,bdd.vars[i]])),expected={...variables,arch_mask:bdd.or(variables.initialize,variables.zero_active0),epoch_mask:variables.epoch_clear0,intent_mask:variables.epoch_clear1,sample_mask:bdd.or(variables.initialize,variables.epoch_clear2),local_reset:bdd.and(variables.epoch_clear3,bdd.not(variables.withdrawal_local))};let guard=1;for(const name of [...states,...maskNames])guard=bdd.and(guard,bdd.not(expected[name]));expected.guard=guard;expected.final_logic=guard;
const observedOld={...decl.gate.original_ports,guard:decl.gate.original_ports.stages_clear,final_logic:decl.original_function.old_final_receiver},observedCurrent={...decl.gate.ports,guard:decl.gate.ports.stages_clear,final_logic:decl.original_function.current_final_receiver};
const currentTargets=[...Object.values(observedCurrent),...Object.values(currentSeeds),...bodyRows.filter(r=>active(r.block)).map(r=>r.position),...d.connections.flatMap(c=>c.path)],oldTargets=[...Object.values(observedOld),...Object.values(oldSeeds),...decl.historical_taps.map(t=>t.source)];
const currentPositions=cone(world,currentTargets,Object.values(currentSeeds)),oldPositions=cone(old,oldTargets,Object.values(oldSeeds)),current=symbolic(world,currentPositions,currentSeeds,bdd),original=symbolic(old,oldPositions,oldSeeds,bdd);
for(const name of [...states,...maskNames,'guard','final_logic'])for(let k=1;k<=15;k++){assert.equal(current.at(observedCurrent[name])[k],expected[name],'Current function '+name+'/'+k);assert.equal(original.at(observedOld[name])[k],expected[name],'Original function '+name+'/'+k);}console.log('all threshold functions',current.metrics,original.metrics);
write('checkpoint.json',{status:'full_static_and_independent_all_threshold_functions_passed_mutations_and_cut_review_pending',metrics:{cells:world.size,receivers,supports,inputs:actualInputs,parent_inputs:priorInputs,stores:stores.size,gate_cells:628,source_boundaries:20,current:current.metrics,original:original.metrics},source_sha256:pins,limits:['No freeze; tap ancestry, mutations, exact cuts and final cost receipt still pending.','Held-state, settled physical model only; source generation, event timing, latest flags derivative and native execution excluded.']});
// Save source-only context so subsequent independent checks can reuse the exact
// recovered graph without substituting declared signal names for physical roots.
export {S,d,parent,ep,oldEp,decl,base,world,old,oldCount,sourceProofs,oldSeeds,currentSeeds,aliasMutations,bodyRows,addedKeys,receivers,supports,actualInputs,priorInputs,newInputs,stores,columns,names,states,maskNames,bdd,expected,observedOld,observedCurrent,currentPositions,oldPositions,current,original,passive};
