import assert from 'node:assert/strict';
import {readFileSync,writeFileSync}from'node:fs';
import {makeClosure}from'./prepare.mjs';
import {rails,laneOffsets,laneDefinition,joinDefinition,inventory}from'./logic.mjs';
import {makeMatrix}from'../control-lsu-v2/matrix.mjs';
import {screen}from'../control-reset-retire-v1/check-interactions.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
const d=makeClosure(),base=read('../control-reset-scratch-v1/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v]));assert.deepEqual(d,read('design.json'));for(const v of base.blocks)assert.deepEqual(m.get(K(v.position))?.block,v.block,'Parent changed '+K(v.position));
const inv=inventory();assert.deepEqual(d.lock_inventory,inv);assert.equal(inv.length,228);assert.equal(inv.filter(v=>v.observed).length,60);for(let i=0;i<4;i++){assert.equal(inv.filter(v=>v.lane===i).length,57);for(const rail of rails)assert.equal(inv.filter(v=>v.lane===i&&v.rail===rail&&v.observed).length,1);}
for(const v of inv){assert.deepEqual(m.get(K(v.lock)).block,{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});assert.equal(K(v.store),K(P(v.lock.x,v.lock.y,v.lock.z-1)));assert.equal(K(v.rear),K(P(v.lock.x,v.lock.y,v.lock.z+1)));assert.equal(m.get(K(v.store)).block.id,'minecraft:repeater');assert.equal(m.get(K(v.rear)).block.id,'minecraft:redstone_wire');if(v.observed)assert.deepEqual(d.connections.find(c=>c.name==='lane'+v.lane+'_'+v.rail).source,v.rear);}
const evalDef=(def,v)=>Object.fromEntries(def.outputs.map(out=>[out,def.products.some(t=>t.out===out&&Object.entries(t.literals).every(([n,w])=>!!v[n]===!!w))]));let cases=0,physicalGates=0;
for(const def of[laneDefinition(),joinDefinition()]){const mat=makeMatrix(def);for(let mask=0;mask<2**def.inputs.length;mask++){const v=Object.fromEntries(def.inputs.map((n,i)=>[n,!!(mask&(1<<i))])),got=evalDef(def,v);if(def.outputs.length===1)assert.equal(got.rails_closed,rails.every(n=>v[n]));else{const c=[v.lane0,v.lane1,v.lane2,v.lane3,v.active,v.reset_wait,!v.initialize,!v.release].every(Boolean);assert.deepEqual(got,{armed_D:c,qualified_D:c&&v.armed,closure:c&&v.armed&&v.qualified});}for(const t of mat.products){let power=15;for(const g of t.gates){power=Math.max(0,power-(v[g.name]===!!g.want?0:15));physicalGates++;}assert.equal(power>0,Object.entries(t.literals).every(([n,w])=>v[n]===!!w));}cases++;}}
const def=joinDefinition(),condition={lane0:1,lane1:1,lane2:1,lane3:1,active:1,reset_wait:1},logic=(c,v)=>evalDef(def,{...v,armed:c[0],qualified:c[1]});let initCases=0;
for(let bits=0;bits<16;bits++)for(const first of['A','B']){let c=[!!(bits&1),!!(bits&2)],n=[!!(bits&4),!!(bits&8)];for(const phase of[first,...(first==='A'?['B']:['A','B'])]){if(phase==='A'){const q=logic(c,{initialize:1});n=[q.armed_D,q.qualified_D];}else c=[...n];}assert.deepEqual(c,[false,false]);assert.deepEqual(n,[false,false]);initCases++;}
let c=[false,false],n=[false,false];const phases=[];for(const phase of['A','B','A','B']){const before=logic(c,condition);if(phase==='A')n=[before.armed_D,before.qualified_D];else c=[...n];phases.push(logic(c,condition).closure);}assert.deepEqual(phases,[false,false,false,true]);
let guardNegatives=0;for(const name of['lane0','lane1','lane2','lane3','active','reset_wait']){assert.equal(logic([1,1],{...condition,[name]:0}).closure,false);guardNegatives++;}for(const name of['initialize','release']){assert.equal(logic([1,1],{...condition,[name]:1}).closure,false);guardNegatives++;}
assert.deepEqual(d.connections.find(c=>c.name==='qualified_closure').destination,base.ports.reset_scratch.closure.bits[0].position);assert.equal(d.metrics.retained_bits,1040);assert.equal(d.connections.length,75);
const eligible=new Set(base.blocks.filter(v=>v.block.id==='minecraft:redstone_wire').map(v=>K(v.position)));let oldEdges=0;
function neighbors(p,map){const out=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(!eligible.has(K(q)))continue;if(y===1&&map.has(K(P(p.x,p.y+1,p.z))))continue;if(y===-1&&map.has(K(P(q.x,q.y+1,q.z))))continue;out.push(K(q));}return out.sort();}
for(const k of eligible){const p=old.get(k).position,a=neighbors(p,old);assert.deepEqual(neighbors(p,m),a,'Old wire graph changed '+k);oldEdges+=a.length;}
const report={status:'author_static_actual_lock_rail_closure_check',...d.metrics,preserved_parent_cells:base.blocks.length,preserved_old_wire_edges:oldEdges,boolean_cases:cases,physical_product_gate_cases:physicalGates,initialization_cases:initCases,qualification_phases:phases,guard_refusals:guardNegatives,...screen(d),native_acceptance:false,all_branches_dynamic_closure_proven:false,final_reset_ack_proven:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,taps:undefined}));
