import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{resolve}from'node:path';
const root=fileURLToPath(new URL('../../../',import.meta.url)),prefix='artifacts/full-gpu-layout-v1/initial-loader-v1/',read=p=>readFileSync(resolve(root,p)),json=p=>JSON.parse(read(p)),sha=p=>createHash('sha256').update(read(p)).digest('hex'),files=new Set();
for(const[p,h]of[
 ['artifacts/full-gpu-layout-v1/memory/bank-tail-sources-v1/source-manifest.json','92c4b189f7aa518dded08932c01f6e22f58ff6f5f0c657a0a0d08d1dec9219db'],
 ['artifacts/full-gpu-layout-v1/memory/program-quiet-v1/source-manifest.json','af29fb59aacf6d8ba4939bd65f1fb5eb661a311c8f7a430eb9d894a11311fb75'],
 ['artifacts/full-gpu-layout-v1/memory/program-rom-folded-v2/source-manifest.json','93177a54ca3fdd037b25a4cff63a845ffe914dd60b290ef631be6c303598a451']]){assert.equal(sha(p),h,p);files.add(p);for(const[q,v]of Object.entries(json(p).source_sha256??json(p).files)){assert.equal(sha(q),v,q);files.add(q);}}
for(const p of['hardware/full-gpu-config-panel.mjs','hardware/full-gpu-dcr.mjs','hardware/register-reset.mjs','artifacts/full-gpu-layout-v1/config-panel/design.json','artifacts/full-gpu-layout-v1/config-panel/check.mjs','artifacts/full-gpu-layout-v1/control-commit-v2/route.mjs','hardware/memory-layout-subarray.mjs','hardware/memory-layout-data-bank.mjs','hardware/memory-layout-data-owned-bank.mjs','hardware/memory-layout-data-channel.mjs','hardware/memory-layout-channel-backend-control.mjs'])files.add(p);
for(const n of['prepare.mjs','routes.json','design.json','ports.json','image-source-map.json','image.mjs','README.md','check-geometry.py','check-preservation.py','check-logic.mjs','check-all.mjs','checks.json','manifest.mjs','logic/matrix.mjs','logic/terms.mjs','logic/check-matrix.mjs','timing-obligations.json'])files.add(prefix+n);
const d=json(prefix+'design.json'),report={status:d.status,source_sha256:Object.fromEntries([...files].sort().map(p=>[p,sha(p)])),metrics:d.metrics,box:d.box,declared_parent_substitutions:d.changes,changed_quiet_roles:d.quietRoleChanges,boundary_inputs:d.boundary_inputs,complete_gpu_layout:false,independent_review:false,native_calls:0,native_acceptance:false,missing:d.missing},encoded=JSON.stringify(report,null,2)+'\n',mp=prefix+'source-manifest.json';if(process.argv.includes('--check'))assert.equal(read(mp).toString(),encoded);else writeFileSync(resolve(root,mp),encoded);console.log(JSON.stringify({manifest_sha256:sha(mp),source_pins:files.size,blocks:d.blocks.length,added_blocks:d.metrics.added_blocks}));
