// Initial physical RAM loader and ROM source map. Pure offline generation.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';

import{makeControlMatrix}from'./logic/matrix.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),sha=n=>createHash('sha256').update(readFileSync(new URL(n,import.meta.url))).digest('hex'),W='minecraft:redstone_wire',S='minecraft:light_gray_concrete';
export function makeInitialLoader({plan=false}={}){
 assert.equal(sha('../memory/bank-tail-sources-v1/source-manifest.json'),'92c4b189f7aa518dded08932c01f6e22f58ff6f5f0c657a0a0d08d1dec9219db');
 assert.equal(sha('../memory/program-quiet-v1/source-manifest.json'),'af29fb59aacf6d8ba4939bd65f1fb5eb661a311c8f7a430eb9d894a11311fb75');
 const data=read('../memory/bank-tail-sources-v1/design.json'),program=read('../memory/program-quiet-v1/design.json'),config=read('../config-panel/design.json'),rom=read('../memory/program-rom-folded-v2/design.json');
 const map=new Map(),parents=[],edges=[],routes=[],connections=[],changes=[],quietRoleChanges=[],panels=[],constants=[],switches=[],components=[];let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to});
 function insert(name,d,t){const move=v=>Array.isArray(v)?v.map(move):v&&typeof v==='object'?(['x','y','z'].every(a=>Number.isSafeInteger(v[a]))?P(v.x+t.x,v.y+t.y,v.z+t.z):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,k==='travel'?structuredClone(x):move(x)]))):v;const q={blocks:d.blocks.map(v=>({position:move(v.position),block:v.block})),ports:move(d.ports)};for(const v of q.blocks){assert(!map.has(K(v.position)),'Parent overlap '+name+' '+K(v.position));map.set(K(v.position),{position:v.position,block:v.block,part:name+'_parent'});}parents.push({name,translation:t,blocks:d.blocks.length});for(const e of d.edges??[])edges.push({from:P(e.from.x+t.x,e.from.y+t.y,e.from.z+t.z),to:P(e.to.x+t.x,e.to.y+t.y,e.to.z+t.z)});return q;}
 insert('data',data,P(0,0,0));const programT=P(-600,0,1100),pr=insert('program',program,programT),panel=insert('config_panel',config,P(-400,0,600)),logic=insert('loader_logic',makeControlMatrix(),P(-400,20,700));
 const port=(d,n)=>d.ports[n].bits[0].position,L=n=>port(logic,n);
 function put(p,id,properties){const block={id:id.startsWith('minecraft:')?id:'minecraft:'+id,...properties?{properties}:{}},v=at(p);if(v){assert.equal(block.id,S,'Collision '+part+' '+K(p)+' '+v.part);assert.deepEqual(v.block,block);return;}map.set(K(p),{position:p,block,part});}
 const solid=p=>put(p,S),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'}),cmp=(p,d)=>dev(p,'comparator',{facing:F[d],mode:'subtract'}),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n);
 function direct(name,ps){part=name;for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);}
 function fixed(name,points){part=name;const ps=[points[0]];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,n=Math.abs(dx)+Math.abs(dz);assert(n&&(!dx||!dz)&&(!dy||Math.abs(dy)===n));for(let j=1;j<=n;j++)ps.push(P(a.x+Math.sign(dx)*j,a.y+Math.sign(dy)*j,a.z+Math.sign(dz)*j));}const refresh=refreshIndices(ps);for(let i=0;i<ps.length;i++){if(!at(ps[i])){if(refresh.includes(i)){const q=ps[i+1],d=Object.keys(V).find(d=>K(step(ps[i],d))===K(q));rep(ps[i],d);}else wire(ps[i]);}if(i)edge(ps[i-1],ps[i]);}routes.push({name,path:ps,refresh_indices:refresh});return ps;}
 // One retained mode owner. CLEAR is downstream-drained AND all four writers low.
 part='load_owner';const x=-480,y=70,z=720;
 solid(P(x,y,z));put(P(x+1,y,z),'redstone_wall_torch',{facing:'east'});wire(P(x+2,y,z));rep(P(x+2,y,z-1),'north');edge(P(x,y,z),P(x+1,y,z));edge(P(x+1,y,z),P(x+2,y,z));edge(P(x+2,y,z),P(x+2,y,z-1));
 fixed('load_owner_feedback_set',[P(x+2,y,z-2),P(x+2,y,z-4),P(x+12,y,z-4)]);part='load_owner';rep(P(x+12,y,z-3),'south');wire(P(x+12,y,z-2));rep(P(x+12,y,z-1),'south');solid(P(x+12,y,z));put(P(x+11,y,z),'redstone_wall_torch',{facing:'west'});wire(P(x+10,y,z));rep(P(x+10,y,z+1),'south');
 direct(part,[P(x+2,y,z-1),P(x+2,y,z-2)]);direct(part,[P(x+12,y,z-4),P(x+12,y,z-3),P(x+12,y,z-2),P(x+12,y,z-1),P(x+12,y,z),P(x+11,y,z),P(x+10,y,z),P(x+10,y,z+1)]);
 fixed('load_owner_feedback_clear',[P(x+10,y,z+2),P(x+10,y,z+4),P(x,y,z+4)]);part='load_owner';rep(P(x,y,z+3),'north');wire(P(x,y,z+2));rep(P(x,y,z+1),'north');direct(part,[P(x+10,y,z+1),P(x+10,y,z+2)]);direct(part,[P(x,y,z+4),P(x,y,z+3),P(x,y,z+2),P(x,y,z+1),P(x,y,z)]);
 const ownerSet=P(x+14,y,z),ownerClear=P(x-4,y,z),owner=P(x+2,y,z);wire(ownerSet);rep(P(x+13,y,z),'west');direct(part,[ownerSet,P(x+13,y,z),P(x+12,y,z)]);wire(ownerClear);rep(P(x-3,y,z),'east');wire(P(x-2,y,z));rep(P(x-1,y,z),'east');direct(part,[ownerClear,P(x-3,y,z),P(x-2,y,z),P(x-1,y,z),P(x,y,z)]);
 // The new LOAD switch does not duplicate DCR or START storage.
 for(const name of ['load_request','boot','image_verified']){part=name+'_switch';const lever=step(L(name),'west',2);dev(lever,'lever',{face:'floor',facing:'west',powered:'false'});rep(step(L(name),'west'),'east');direct(part,[lever,step(L(name),'west'),L(name)]);switches.push({name,position:lever});}
 // Four short panel interfaces use only previously unclaimed bank requester4.
 for(const bank of data.banks){const b=bank.bank,wa=bank.ports.write_address.positions.slice(32,40),wd=bank.ports.write_data.positions.slice(32,40),wv=bank.ports.write_valid.positions[4],ready=bank.ports.write_ready.positions[4],quiet=data.quiet.find(q=>q.bank===b&&q.slot===4&&q.kind==='write_valid');const local=[];
  for(const [kind,ps]of[['address',wa],['data',wd]])for(const[i,p]of ps.entries()){
   part='bank'+b+'_load_'+kind+i;const source=step(p,'east',4);rep(step(p,'east'),'west');wire(step(p,'east',2));rep(step(p,'east',3),'west');
   if(kind==='address'&&i<2){dev(source,(b>>i)&1?'redstone_block':'light_gray_concrete');constants.push({bank:b,bit:i,source,value:(b>>i)&1});}else{dev(source,'lever',{face:'floor',facing:'west',powered:'false'});const sw={name:'bank'+b+'_'+kind+(kind==='address'?i-2:i),position:source,kind,bit:kind==='address'?i-2:i};switches.push(sw);local.push(sw);}
   direct(part,[source,step(p,'east',3),step(p,'east',2),step(p,'east'),p]);
  }
  part='bank'+b+'_loader_strobe';const g=P(wv.x+10,wv.y,wv.z),grant=P(g.x+2,g.y,g.z+4),strobe=P(g.x+4,g.y,g.z);dev(strobe,'lever',{face:'floor',facing:'west',powered:'false'});rep(P(g.x+3,g.y,g.z),'west');wire(P(g.x+2,g.y,g.z));rep(P(g.x+1,g.y,g.z),'west');cmp(g,'west');rep(P(g.x-1,g.y,g.z),'west');
  for(let xx=g.x-2;xx>=wv.x+4;xx--)wire(P(xx,g.y,g.z));rep(P(wv.x+3,g.y,g.z),'west');direct(part,[strobe,P(g.x+3,g.y,g.z),P(g.x+2,g.y,g.z),P(g.x+1,g.y,g.z),g,P(g.x-1,g.y,g.z),...Array.from({length:g.x-2-(wv.x+4)+1},(_,i)=>P(g.x-2-i,g.y,g.z)),P(wv.x+3,g.y,g.z),quiet.rear,quiet.driver,wv]);
  wire(grant);rep(P(g.x+1,g.y,g.z+4),'west');solid(P(g.x,g.y,g.z+4));put(P(g.x,g.y,g.z+3),'redstone_wall_torch',{facing:'north'});wire(P(g.x,g.y,g.z+2));rep(P(g.x,g.y,g.z+1),'north');direct(part,[grant,P(g.x+1,g.y,g.z+4),P(g.x,g.y,g.z+4),P(g.x,g.y,g.z+3),P(g.x,g.y,g.z+2),P(g.x,g.y,g.z+1),g]);
  const sw={name:'bank'+b+'_write',position:strobe};switches.push(sw);quietRoleChanges.push({...quiet,new_strong_source:P(wv.x+3,g.y,g.z),new_role:'pre_run_only_slot4_write'});panels.push({bank:b,slot:4,address_mapping:'word=(local_address<<2)|bank',switches:local,strobe,grant,ready,write_valid:wv,write_address:wa,write_data:wd,read_valid_stays_quiet:bank.ports.read_valid.positions[4]});
 }
 // Block new allocation only; retained owners still see original raw valids.
 const admissionMasks=[];for(let i=0;i<8;i++){part='runtime_new_request_mask_'+i;const p=P(5*i,1,-6),v=at(p),to={id:'minecraft:comparator',properties:{facing:'north',mode:'subtract'}};assert.deepEqual(v.block,{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});changes.push({position:p,from:v.block,to});v.block=to;v.part=part;const input=P(p.x+2,p.y,p.z);wire(input);rep(P(p.x+1,p.y,p.z),'west');direct(part,[P(p.x,1,-7),p,P(p.x,1,-5)]);edge(P(p.x,1,-5),P(p.x,1,-4));edge(P(p.x,1,-5),P(p.x,2,-5));direct(part,[input,P(p.x+1,p.y,p.z),p]);for(let yy=-4;yy<0;yy++){put(P(input.x,yy,input.z),yy%2===0?S:'redstone_torch');edge(P(input.x,yy,input.z),P(input.x,yy+1,input.z));}edge(P(input.x,0,input.z),input);const lower=P(input.x,-4,input.z+2);wire(lower);rep(P(input.x,-4,input.z+1),'north');direct(part,[lower,P(input.x,-4,input.z+1),P(input.x,-4,input.z)]);admissionMasks.push(lower);}
 // Program ACTIVE SET gets the same new-admission mask, not owned-valid masking.
 part='program_new_request_mask';const pg=P(programT.x-44,-49,programT.z-180),old=at(pg),to={id:'minecraft:comparator',properties:{facing:'east',mode:'subtract'}};assert.deepEqual(old.block,{id:'minecraft:repeater',properties:{facing:'east',delay:'1'}});changes.push({position:pg,from:old.block,to});old.block=to;old.part=part;const programMask=P(pg.x,pg.y,pg.z-2);wire(programMask);rep(P(pg.x,pg.y,pg.z-1),'south');direct(part,[P(pg.x+1,pg.y,pg.z),pg,P(pg.x-1,pg.y,pg.z)]);direct(part,[programMask,P(pg.x,pg.y,pg.z-1),pg]);
 part='staged_dcr_reset';const dg=P(-406,-4,595),dgold=at(dg),dgnew={id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}};assert.deepEqual(dgold.block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});changes.push({position:dg,from:dgold.block,to:dgnew});dgold.block=dgnew;dgold.part=part;const dcrPermit=P(-408,-4,599);wire(dcrPermit);rep(P(-407,-4,599),'east');solid(P(-406,-4,599));put(P(-406,-4,598),'redstone_wall_torch',{facing:'north'});wire(P(-406,-4,597));rep(P(-406,-4,596),'north');direct(part,[dcrPermit,P(-407,-4,599),P(-406,-4,599),P(-406,-4,598),P(-406,-4,597),P(-406,-4,596),dg]);direct(part,[P(-407,-4,595),dg,P(-405,-4,595)]);
 const cacheURL=new URL('routes.json',import.meta.url),cache=existsSync(cacheURL)?read('routes.json'):{},pending=[],reserved=[],reserve=(s,sd,d,ad)=>[...Array.from({length:18},(_,i)=>step(s,sd,i+2)),...Array.from({length:18},(_,i)=>step(d,ad,-i-2))];
 function draw(name,source,sd,destination,ad,stubs=false){part=name;assert.equal(at(source)?.block.id,W,'source '+name);assert.equal(at(destination)?.block.id,W,'destination '+name);const first=step(source,sd),start=step(source,sd,2),last=step(destination,ad,-1),end=step(destination,ad,-2);if(stubs){rep(first,sd);wire(start);rep(last,ad);wire(end);direct(name,[source,first,start]);direct(name,[end,last,destination]);return;}let path=cache[name]?.path;if(path&&plan&&(K(path[0])!==K(start)||K(path.at(-1))!==K(end)||path.slice(1,-1).some(p=>at(p))))path=undefined;if(!path){assert(plan,'Missing route '+name);const ignore=[...reserve(source,sd,destination,ad),first,start,last,end,...[first,start,last,end].map(p=>P(p.x,p.y-1,p.z))],forbidden=[first,last].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![source,start,end,destination].some(q=>K(p)===K(q))),opts={ignore:[...ignore,source,destination],reserved,forbidden},via=name.startsWith('load_grant_bank')?[P(start.x+55,-55,start.z+10),P(end.x,name==='load_grant_bank3'?-48:-55,end.z+55)]:[],ends=[...via,end],all=[start];let expanded=0;for(const target of ends){const r=searchPath(map,all.at(-1),target,{...opts,reserved:[...reserved,...all.slice(0,-1)]});all.push(...r.path.slice(1));expanded+=r.expanded;}const r={path:all,expanded};path=r.path;cache[name]={source,destination,path,expanded:r.expanded};writeFileSync(cacheURL,JSON.stringify(cache)+'\n');console.error(name+': '+path.length+' / '+r.expanded);}assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i)){const dir=Object.keys(V).find(d=>K(step(p,d))===K(q));rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source,tap:first,destination,arrival:last});}
 pending.push(['panel_start_to_loader',port(panel,'start'),'north',L('raw_start'),'south'],['panel_reset_to_loader',port(panel,'global_reset'),'north',L('raw_reset'),'south'],['retained_owner_to_logic',owner,'east',L('owner'),'south'],['loader_set_to_owner',L('owner_set'),'south',ownerSet,'west'],['loader_clear_to_owner',L('owner_clear'),'south',ownerClear,'east']);
 let grant=L('ram_grant');for(const b of panels){pending.push(['load_grant_bank'+b.bank,grant,b.bank?'east':'south',b.grant,'north']);grant=b.grant;const raw=P(b.strobe.x-2,b.strobe.y,b.strobe.z);pending.push(['bank'+b.bank+'_writer_to_owner',raw,'north',L('writer'+b.bank),'south']);}
 let block=L('runtime_block');for(let i=0;i<8;i++){pending.push(['new_runtime_admission_mask_'+i,block,i?'east':'south',admissionMasks[i],'north']);block=admissionMasks[i];}pending.push(['new_program_admission_mask',step(L('runtime_block'),'south',2),'east',programMask,'south']);
 pending.push(['staged_dcr_reset_permit',L('dcr_reset_permit'),'south',dcrPermit,'east']);pending.push(['actual_program_quiet',port(pr,'channel_quiet'),'south',L('program_drained'),'south']);for(let b=0;b<4;b++)pending.push(['actual_bank_tail_'+b,data.ports.bank_busy_any.positions[b],'south',L('bank'+b+'_busy'),'south']);
 for(const[,s,sd,d,ad]of pending)reserved.push(...reserve(s,sd,d,ad));for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const configuration=rom.configuration.map(v=>({...v,position:P(v.position.x+programT.x,v.position.y,v.position.z+programT.z)}));for(const v of configuration)assert.equal(at(v.position)?.block.id,v.value?'minecraft:redstone_block':S);
 const ramReadback=[];for(let address=0;address<256;address++){const bank=address&3,local=address>>2,card=local>>4,row=local&15,o=data.banks[bank].origin;for(let bit=0;bit<8;bit++){const position=P(o.x+(bit<4?2:10),o.y+1+8*row+140*(card>>1),o.z+8*(bit%4)+64*(card&1)),lock=P(position.x,position.y,position.z+1);assert.deepEqual(at(position)?.block,{id:'minecraft:repeater',properties:{facing:bit<4?'west':'east',delay:'1'}});assert.deepEqual(at(lock)?.block,{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});ramReadback.push({address,bank,local_address:local,card,row,bit,position,property:'powered',lock,lock_property:'powered',required_lock:true});}}
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=blocks.reduce((n,v)=>Math.min(n,v.position[a]),Infinity);box.to[a]=blocks.reduce((n,v)=>Math.max(n,v.position[a]),-Infinity);}const counts={};for(const v of blocks)counts[v.part]=(counts[v.part]??0)+1;
 return{status:'offline_initial_loader_connected_candidate_unmeasured',blocks,box,edges,routes,connections,parents,changes,quietRoleChanges,panels,constants,switches,configuration,ramReadback,owner:{positive:owner,set:ownerSet,clear:ownerClear},ports:{config:panel.ports,loader:logic.ports,program:pr.ports,data:data.ports},metrics:{blocks:blocks.length,parent_blocks:parents.filter(p=>p.name!=='loader_logic').reduce((n,p)=>n+p.blocks,0),added_blocks:blocks.length-parents.filter(p=>p.name!=='loader_logic').reduce((n,p)=>n+p.blocks,0),new_retained_bits:1,manual_switches:config.switches.length+switches.length,program_bits:configuration.length,data_bytes:256,route_count:connections.length,part_counts:counts},boundary_inputs:['cores_held_reset','global_channels_drained','cold_initialized'],native_calls:0,native_acceptance:false,missing:['Actual cores_held_reset, global_channels_drained and cold_initialized producers/routes remain external. Four actual bank any_busy and program channel_quiet returns are connected, with native far-tail timing still unmeasured.','Mapped DCR/reset/launch/BOOT outputs need final dispatch/core/global-reset integration. Warm staged RESET preserves owners; BOOT is destructive pre-run scrub only and never waits on an arbitrary initial ACK.','Every native closure, cold initialization, admission-mask settling and complete tail/drain bound remains unmeasured.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeInitialLoader({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else{writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');writeFileSync(new URL('ports.json',import.meta.url),JSON.stringify({status:'physical_outputs_and_explicit_unjoined_inputs',ports:d.ports,boundary_inputs:d.boundary_inputs,owner:d.owner,panels:d.panels},null,2)+'\n');writeFileSync(new URL('image-source-map.json',import.meta.url),JSON.stringify({status:'pre_run_source_and_retained_state_map_only',program:d.configuration,ram:d.ramReadback})+'\n');}console.log(JSON.stringify({...d.metrics,part_counts:undefined}));}
