// Preserve all old slice dependencies and the actual extracted IR internals;
// admit only ten explicit new source-to-input cables.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{P,K}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),d=read('design.json'),parent=read('../four-lane-data-v1/design.json'),ir=read('../shared-ir-body.json'),placed=materializeInstance(ir,{id:'shared_ir',...d.ir_transform}),before=new Map(parent.blocks.map(v=>[K(v.position),v.block])),after=new Map(d.blocks.map(v=>[K(v.position),v.block]));
const W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',S='minecraft:light_gray_concrete',solid=b=>b?.id.endsWith('_concrete'),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),pair=(a,b)=>K(a)+'>'+K(b);
assert.equal(after.size,d.blocks.length);for(const v of[...parent.blocks,...placed.blocks])assert.deepEqual(after.get(K(v.position)),v.block);
const expected=new Set(),preserved=[];for(const v of parent.blocks)if(active(v.block))for(const q of inputs(before,v.position)){expected.add(pair(q,v.position));preserved.push({from:q,to:v.position});}for(const e of d.shared_ir_original_internal_edges){expected.add(pair(e.from,e.to));preserved.push(e);}
for(const e of d.edges){expected.add(pair(e.from,e.to));if(after.get(K(e.from))?.id===W&&after.get(K(e.to))?.id===W)expected.add(pair(e.to,e.from));}
const actual=new Set(),unexpected=[];let supports=0,receivers=0;for(const v of d.blocks){if([W,R,C,T].includes(v.block.id)){assert(solid(after.get(K(P(v.position.x,v.position.y-1,v.position.z)))));supports++;}if(!active(v.block))continue;receivers++;for(const q of inputs(after,v.position)){const e=pair(q,v.position);actual.add(e);if(!expected.has(e))unexpected.push({from:q,to:v.position,from_block:after.get(K(q)),to_block:v.block});}}
const lost=preserved.filter(e=>!actual.has(pair(e.from,e.to))),missing=d.edges.filter(e=>!actual.has(pair(e.from,e.to)));const D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};let stores=0;for(const v of d.blocks){if(v.block.id!==R)continue;const dr=D[v.block.properties.facing];if(Object.values(D).some(s=>{if(s.x*dr.x+s.z*dr.z)return false;const q=add(v.position,s),qb=after.get(K(q));return[R,C].includes(qb?.id)&&K(add(q,D[qb.properties.facing]))===K(v.position);} ))stores++;}assert.equal(stores,940);
const wb=read('../../writeback/design.json'),routes=[];for(const r of d.connections){const bus=d.buses[r.signal],src=bus.field==='immediate'?placed.ports.immediate.bits[bus.bit]:placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_'+bus.bit);assert.deepEqual(bus.source,src.position);if(bus.field==='immediate')assert.equal(src.instruction_bit,bus.bit);
 if(r.role==='retained_IR_to_shared_bus'){assert.deepEqual(r.source,src.position);assert.deepEqual(r.destination,bus.header);}else{assert.equal(r.role,'shared_bus_to_writeback');assert.deepEqual(r.source,bus.outputs[r.lane].position);assert.deepEqual(r.destination,add(wb.ports[bus.field].bits[bus.bit].position,P(320*(r.lane%2),-10-4*r.lane,400*Math.floor(r.lane/2)-30)));}
 const qs=inputs(after,r.source);assert.equal(qs.length,1,r.name+' source inputs');assert.equal(after.get(K(qs[0])).id,R);assert.deepEqual(inputs(after,r.tap),[r.source]);assert.deepEqual(inputs(after,r.arrival),[r.end]);let run=0,max=0,delay=0;for(const p of[r.tap,...r.path,r.arrival]){const b=after.get(K(p));if(b.id===R){run=0;delay+=2*Number(b.properties.delay);}else{assert.equal(b.id,W);max=Math.max(max,++run);}}assert(max<=12);routes.push({name:r.name,source:r.source,destination:r.destination,cable_nominal_ticks:delay,max_dust_run:max,minimum_rear_high_power:16-max});}
// Follow the real directed new network from each held-IR terminal. It must
// reach exactly that field's four actual writeback inputs and no other field.
const newKeys=new Set(d.blocks.slice(d.parent_cells).map(v=>K(v.position))),adj=new Map();for(const e of d.edges){const k=K(e.from);if(!adj.has(k))adj.set(k,[]);adj.get(k).push(K(e.to));if(after.get(k)?.id===W&&after.get(K(e.to))?.id===W){if(!adj.has(K(e.to)))adj.set(K(e.to),[]);adj.get(K(e.to)).push(k);}}
const fanout=[];for(const bus of d.buses){const visited=new Set([K(bus.source)]),queue=[K(bus.source)];for(let i=0;i<queue.length;i++)for(const k of adj.get(queue[i])??[])if(!visited.has(k)){visited.add(k);queue.push(k);}const reached=d.connections.filter(r=>r.role==='shared_bus_to_writeback'&&visited.has(K(r.destination)));assert.equal(reached.length,4,'Fanout '+bus.signal);assert(reached.every(r=>r.signal===bus.signal));fanout.push({signal:bus.signal,visited_nodes:visited.size,destinations:reached.map(r=>({lane:r.lane,position:r.destination}))});}
// Fixed high-power capacity of each pure cable tree, using actual edge types.
// This does not predict signal timing or whether the held source is high.
const capacity=[];const poweredUnion=new Set();for(const bus of d.buses){const power=new Map([[K(bus.source),15]]),queue=[K(bus.source)];for(let i=0;i<queue.length;i++){const a=queue[i],av=power.get(a),ab=after.get(a);for(const b of adj.get(a)??[]){const bb=after.get(b),v=bb.id===R?15:bb.id===W?(ab.id===W?av-1:av):0;if(v>0&&v>(power.get(b)??0)){power.set(b,v);queue.push(b);}}}let minRear=15,repeaterCount=0;for(const[k,value]of power){if(newKeys.has(k))poweredUnion.add(k);if(after.get(k)?.id===R&&newKeys.has(k)){const p=Object.fromEntries(k.split(',').map((v,i)=>[['x','y','z'][i],Number(v)])),sources=inputs(after,p),rear=Math.max(0,...sources.map(q=>power.get(K(q))??0));assert(rear>0);minRear=Math.min(minRear,rear);repeaterCount++;}}
for(const r of d.connections.filter(r=>r.signal===bus.signal&&r.role==='shared_bus_to_writeback'))assert.equal(power.get(K(r.destination)),15);capacity.push({signal:bus.signal,repeaterCount,minimum_positive_rear:minRear,destination_high_power:15});}
const addedActive=d.blocks.slice(d.parent_cells).filter(v=>active(v.block));assert.equal(poweredUnion.size,addedActive.length,'Unreached added component');
let negatives=0;const r=d.connections.find(r=>r.role==='shared_bus_to_writeback'),old=after.get(K(r.arrival)),opposite={east:'west',west:'east',north:'south',south:'north'};after.set(K(r.arrival),{...old,properties:{...old.properties,facing:opposite[old.properties.facing]}});assert(!inputs(after,r.destination).some(q=>K(q)===K(r.arrival)));after.set(K(r.arrival),old);negatives++;
const bus=d.buses[8],wrong=d.buses[9].source;assert.throws(()=>assert.deepEqual(wrong,placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_'+bus.bit).position));negatives++;
const middle=P(299,-30,-90),midOld=after.get(K(middle));assert.equal(midOld.id,R);after.set(K(middle),{...midOld,properties:{...midOld.properties,facing:'east'}});assert(!inputs(after,P(300,-30,-90)).some(q=>K(q)===K(middle)));after.set(K(middle),midOld);negatives++;
const status=unexpected.length||lost.length||missing.length?'refused':'actual_four_lane_complete_data_slice_dependency_screen_passed',report={status,cells:d.blocks.length,parent_lane_cells:parent.blocks.length,shared_ir_cells:placed.blocks.length,added_cable_cells:d.added_cells,stores,supports,receivers,preserved_dependencies:preserved.length,actual_dependencies:actual.size,unexpected,lost,missing,routes,fanout,capacity,new_active_components_powered:poweredUnion.size,negative_checks:negatives,source_sha256:Object.fromEntries(['prepare.mjs','check.mjs','design.json','paths.json','../four-lane-data-v1/design.json','../shared-ir-body.json'].map(n=>[n,createHash('sha256').update(readFileSync(new URL(n,H))).digest('hex')])),scope:['All 136 missing bit connections for four lanes are now real paths from the retained RF/ALU/IR sources into actual receiving pads.','This does not connect the 177 other shared stores or shared phase/reset/control/status cuts. The same 16 IR stores are relocated, not added to the architectural state.','The body preservation and possible-input graph are static evidence, not pulse/timing/native acceptance.'],complete_core:false,native_acceptance:false};writeFileSync(new URL('checks.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,unexpected:unexpected.slice(0,15),lost:lost.slice(0,15),missing:missing.slice(0,15)},null,2));assert.equal(status,'actual_four_lane_complete_data_slice_dependency_screen_passed');
