// One real retained IR/opcode body and ten shared noninverting fanouts.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{materializeInstance,rotatePosition}from'../../../../hardware/gpu-layout-assembly.mjs';import{P,K,V,F,searchPath,refreshIndices}from'../../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),W='minecraft:redstone_wire',R='minecraft:repeater',S='minecraft:light_gray_concrete',A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),under=p=>P(p.x,p.y-1,p.z),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n);
const parent=read('../four-lane-data-v1/design.json'),ir=read('../shared-ir-body.json'),transform={quarter_turns:2,translation:P(-40,0,-40)},placed=materializeInstance(ir,{id:'shared_ir',...transform}),irAt=p=>A(rotatePosition(p,2),transform.translation);
const parentRows=[...parent.blocks,...placed.blocks.map(b=>({...b,body:'shared/held_ir'}))],map=new Map(parentRows.map(v=>[K(v.position),v])),rows=[...parentRows];assert.equal(map.size,rows.length);let part='';const edges=[],connections=[],buses=[];
function put(p,id,properties){const block={id,...properties?{properties}:{}},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'Collision '+part+' '+K(p));assert(id===S||part===old.part,'Unowned join '+part+' '+K(p));return;}const b={position:p,block,part};map.set(K(p),b);rows.push(b);}
const dev=(p,id,pr)=>{put(under(p),S);put(p,id,pr)},wire=p=>dev(p,W),rep=(p,d)=>dev(p,R,{facing:F[d],delay:'1'}),edge=(a,b)=>edges.push({from:a,to:b,route:part});
const wb=read('../../writeback/design.json'),wp=(lane,name,bit)=>A(wb.ports[name].bits[bit].position,P(320*(lane%2),-10-4*lane,400*Math.floor(lane/2)-30));
function pending(name,source,sd,destination,ad,meta={}){assert.equal(map.get(K(source))?.block.id,W,name+' source');assert.equal(map.get(K(destination))?.block.id,W,name+' destination');connections.push({name,source,source_direction:sd,destination,arrival_direction:ad,...meta,tap:step(source,sd),start:step(source,sd,2),arrival:step(destination,ad,-1),end:step(destination,ad,-2)});}
for(let n=0;n<10;n++){
 const immediate=n<8,bit=immediate?n:n-8,y=-30-3*n,zout=immediate?-22+8*bit:-30,src=immediate?placed.ports.immediate.bits[bit]:placed.ports.controls.bits.find(p=>p.name==='reg_input_mux_'+bit);part='bus'+n;
 for(let x=-80;x<=300;x++){const p=P(x,y,-90),refresh=x!==-20&&x!==300&&(x===-21||x===299||(x+79)%10===0);if(refresh)rep(p,'east');else wire(p);if(x>-80)edge(P(x-1,y,-90),p);}
 for(const x of[-20,300])for(let z=-89;z<=400+zout;z++){const p=P(x,y,z),refresh=z!==zout&&z!==400+zout&&(z===zout-1||z===zout+1||z===400+zout-1||(z+89)%10===0);if(refresh)rep(p,'south');else wire(p);edge(P(x,y,z-1),p);}
 buses.push({signal:n,field:immediate?'immediate':'select',bit,y,source:src.position,header:P(-80,y,-90),outputs:[0,1,2,3].map(lane=>({lane,position:P(lane%2?300:-20,y,zout+400*Math.floor(lane/2))}))});
 pending('IR_to_bus'+n,src.position,src.travel,P(-80,y,-90),'east',{signal:n,field:immediate?'immediate':'select',bit,role:'retained_IR_to_shared_bus'});
 for(let lane=0;lane<4;lane++)pending('bus'+n+'_lane'+lane,buses.at(-1).outputs[lane].position,'east',wp(lane,immediate?'immediate':'select',bit),immediate?'south':bit?'west':'east',{signal:n,field:immediate?'immediate':'select',bit,lane,role:'shared_bus_to_writeback'});
}
// Every target escape is occupied before route search, including all40 actual
// final receivers; source data never comes from an invented test lever.
const reserve=c=>[...Array.from({length:8},(_,i)=>step(c.source,c.source_direction,i+2)),...Array.from({length:8},(_,i)=>step(c.destination,c.arrival_direction,-i-2))],reserved=connections.flatMap(reserve);
for(const c of connections){part=c.name;rep(c.tap,c.source_direction);wire(c.start);rep(c.arrival,c.arrival_direction);wire(c.end);edge(c.source,c.tap);edge(c.tap,c.start);edge(c.end,c.arrival);edge(c.arrival,c.destination);}
const cacheURL=new URL('paths.json',H),cache=existsSync(cacheURL)?read('paths.json'):{};
for(const c of connections){part=c.name;let path=cache[c.name]?.path;if(!path){const ignore=[c.tap,c.start,c.arrival,c.end,...[c.tap,c.start,c.arrival,c.end].map(under),...reserve(c)];const r=searchPath(map,c.start,c.end,{ignore,reserved,limit:1200000});path=r.path;cache[c.name]={source:c.source,destination:c.destination,path,expanded:r.expanded};writeFileSync(cacheURL,JSON.stringify(cache)+'\n');console.log(JSON.stringify({name:c.name,cells:path.length,expanded:r.expanded}));}else{assert.deepEqual(cache[c.name].source,c.source);assert.deepEqual(cache[c.name].destination,c.destination);}
 const refresh=new Set(refreshIndices(path));for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.has(i)){const dir=Object.keys(V).find(n=>K(step(p,n))===K(q));assert(dir);rep(p,dir);}else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);c.path=path;c.refresh_indices=[...refresh];}
const box={from:P(Infinity,Infinity,Infinity),to:P(-Infinity,-Infinity,-Infinity)};for(const r of rows)for(const a of['x','y','z']){box.from[a]=Math.min(box.from[a],r.position[a]);box.to[a]=Math.max(box.to[a],r.position[a]);}
const out={status:'four_lane_all136_missing_data_paths_drawn_unchecked',blocks:rows,connections,edges,buses,ports:{shared_ir:placed.ports},ir_transform:transform,parent_cells:parentRows.length,ir_cells:placed.blocks.length,added_cells:rows.length-parentRows.length,box,metrics:{cells:rows.length,lane_stores:924,shared_IR_stores:16,total_stores:940,complete_data_destinations:232,original_missing_bit_paths_completed:136},shared_ir_original_internal_edges:ir.internal.map(e=>({from:irAt(e.from),to:irAt(e.to)})),remaining:['The 177 other shared stores and all shared command/phase/init/status cuts are still required.','Data static electrical checks and full shared timing/closure remain pending.'],native_acceptance:false,complete_core:false};writeFileSync(new URL('design.json',H),JSON.stringify(out)+'\n');console.log(JSON.stringify({cells:rows.length,added:out.added_cells,box}));
