import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{makeResetEpoch}from'./prepare.mjs';import{screen}from'./check-interactions.mjs';import{checkLogic}from'./check-logic.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),W='minecraft:redstone_wire';
const d=makeResetEpoch(),base=read('../control-reset-zero-v1/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v]));assert.deepEqual(d,read('design.json'));assert.equal(d.removed.length,0);assert.equal(d.substitutions.length,0);assert.equal(d.metrics.retained_bits,1109);for(const v of base.blocks)assert.deepEqual(m.get(K(v.position))?.block,v.block,'Unexpected parent mutation '+K(v.position));
const eligible=new Set(base.blocks.filter(v=>v.block.id===W).map(v=>K(v.position)));let oldEdges=0;function neighbors(p,map){const a=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const dy of[-1,0,1]){const q=P(p.x+x,p.y+dy,p.z+z);if(!eligible.has(K(q)))continue;if(dy===1&&map.has(K(P(p.x,p.y+1,p.z))))continue;if(dy===-1&&map.has(K(P(q.x,q.y+1,q.z))))continue;a.push(K(q));}return a.sort();}for(const k of eligible){const before=neighbors(old.get(k).position,old);assert.deepEqual(neighbors(old.get(k).position,m),before,'Parent wire shape '+k);oldEdges+=before.length;}
let locks=0;for(const[name,v]of Object.entries(d.parents).filter(([n])=>/^epoch_(prepared|committed|settled|A_held_enable)$/.test(n))){const t=v.translation;for(const x of name==='epoch_A_held_enable'?[0]:[0,12]){assert.deepEqual(m.get(K(P(t.x+x+2,t.y+1,t.z))).block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(m.get(K(P(t.x+x+2,t.y+1,t.z+1))).block,{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});assert.equal(m.get(K(P(t.x+x+2,t.y+1,t.z+2))).block.id,W);locks++;}}assert.equal(locks,7);
function bindings(candidate){const c=n=>candidate.connections.find(v=>v.name===n);assert.deepEqual(c('upper_core_commit_owner_zero').destination,P(-104,64,-6));assert.deepEqual(c('retained_front_intent_clear').destination,P(-44,-2,85));assert.deepEqual(c('advance_samples_and_DONE_clear').destination,P(108,-3,-110));assert.deepEqual(c('local_architectural_reset_blank').destination,P(-140,1,-2));assert.deepEqual(c('A_held_epoch_bank_permit').source,P(-305,181,410));assert.deepEqual(c('A_held_epoch_bank_permit').destination,P(-90,1,0));for(const n of ['start_request','reset_request','core_done'])assert.deepEqual(candidate.ports[n],base.ports[n]);assert.deepEqual(candidate.ports.front.program_address,base.ports.front.program_address);}
bindings(d);let corruptions=0;for(const[name,field,p]of[['upper_core_commit_owner_zero','destination',P(-100,1,-8)],['A_held_epoch_bank_permit','source',P(-403,181,410)]]){assert.throws(()=>bindings({...d,connections:d.connections.map(c=>c.name===name?{...c,[field]:p}:c)}));corruptions++;}
const low=P(-363,180,415),high=P(-362,181,415),cap=P(-363,181,415);assert.equal(m.get(K(low)).block.id,W);assert.equal(m.get(K(high)).block.id,W);assert.equal(m.get(K(cap)).block.id,'minecraft:light_gray_concrete');const exposed=x=>!x.has(K(cap));assert(!exposed(m));const without=new Map(m);without.delete(K(cap));assert(exposed(without));corruptions++;
for(const[z,f]of[[-3,'south'],[-1,'north']]){assert.deepEqual(m.get(K(P(-138,1,z))).block,{id:'minecraft:repeater',properties:{facing:f,delay:'1'}});assert(d.edges.some(e=>K(e.from)==='-138,1,-2'&&K(e.to)===`-138,1,${z}`));}
const report={status:'author_checked_connected_control_epoch_zero_candidate',...d.metrics,preserved_parent_cells:base.blocks.length,preserved_old_wire_edges:oldEdges,explicit_lock_directions:locks,boundary_corruptions:corruptions,...checkLogic(),...screen(d),native_acceptance:false,complete_core_reset:false,final_reset_ack:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,taps:undefined}));
