// Concrete level-handshake fetch-control candidate, pure offline geometry.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,V={east:[1,0],west:[-1,0],south:[0,1],north:[0,-1]},F={east:'west',west:'east',south:'north',north:'south'};
export function makeFetchControl(){
 const map=new Map(),edges=[],routes=[],gates=[],ports={},delays=[];
 const edge=(a,b,kind='signal')=>edges.push({from:a,to:b,kind}),join=ps=>{for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);};
 function put(p,id,props,part){const block={id:'minecraft:'+id,...(props?{properties:props}:{})},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'collision '+K(p));return;}map.set(K(p),{position:p,block,part});}
 const solid=(p,part)=>put(p,'light_gray_concrete',undefined,part),dev=(p,id,props,part)=>{solid(P(p.x,p.y-1,p.z),part+'_support');put(p,id,props,part);};
 const wire=(p,n)=>dev(p,'redstone_wire',undefined,n),rep=(p,d,n,delay=1)=>dev(p,'repeater',{facing:F[d],delay:String(delay)},n);
 function route(n,ws){const path=[P(...ws[0])];for(let i=1;i<ws.length;i++){const a=ws[i-1],b=ws[i],delta=b.map((v,j)=>v-a[j]),steps=Math.abs(delta[0])+Math.abs(delta[2]);assert(steps&&(!delta[0]||!delta[2])&&(!delta[1]||Math.abs(delta[1])===steps));for(let j=1;j<=steps;j++)path.push(P(...a.map((v,k)=>v+Math.sign(delta[k])*j)));}
  const candidates=[-1];for(let i=1;i<path.length-1;i++){const a=path[i-1],p=path[i],b=path[i+1];if(!map.has(K(p))&&a.y===p.y&&b.y===p.y&&p.x-a.x===b.x-p.x&&p.z-a.z===b.z-p.z)candidates.push(i);}candidates.push(path.length);const cost=new Map([[-1,0]]),prev=new Map();for(const end of candidates.slice(1))for(const start of candidates){if(start>=end)break;if(!cost.has(start)||end-start>13)continue;const value=cost.get(start)+(end===path.length?0:1);if(value<(cost.get(end)??Infinity)){cost.set(end,value);prev.set(end,start);}}assert(prev.has(path.length),'unrefreshable '+n);const refresh=[];for(let at=prev.get(path.length);at!==-1;at=prev.get(at))refresh.push(at);refresh.sort((a,b)=>a-b);
  let power=15;for(let i=0;i<path.length;i++){const p=path[i],b=path[i+1],old=map.get(K(p));if(old){assert.equal(old.block.id,'minecraft:redstone_wire','route endpoint '+n);power=15;}else if(refresh.includes(i)){const d=Object.keys(V).find(d=>p.x+V[d][0]===b.x&&p.z+V[d][1]===b.z);rep(p,d,n);power=15;}else{wire(p,n);power--;assert(power>0,'attenuation '+n);}}join(path);routes.push({name:n,path,refresh_indices:refresh,nominal_ticks:refresh.length*2});return path;}
 function gate(n,x,z){const rear=P(x-2,1,z),side=P(x,1,z-2),center=P(x,1,z),out=P(x+2,1,z);wire(rear,n+'_rear');rep(P(x-1,1,z),'east',n+'_rear_driver');dev(center,'comparator',{facing:'west',mode:'subtract'},n);rep(P(x+1,1,z),'east',n+'_out_driver');wire(out,n+'_out');wire(side,n+'_side');rep(P(x,1,z-1),'south',n+'_side_driver');join([rear,P(x-1,1,z),center,P(x+1,1,z),out]);join([side,P(x,1,z-1),center]);const g={name:n,rear,side,center,out};gates.push(g);return g;}
 const a=gate('effective_request',0,0),valid=gate('memory_valid',20,0),response=gate('response_present',40,0),open=gate('ir_capture_request',40,10),hold=gate('captured_hold',0,-20),complete=gate('fetch_complete',70,-20);
 route('request_to_valid',[[2,1,0],[18,1,0]]);route('valid_to_response',[[22,1,0],[38,1,0]]);
 // Active-high ready is inverted only for Q=valid&&!notReady; raw ready gates complete.
 const ready=P(40,1,-34);wire(ready,'memory_ready');rep(P(40,1,-33),'south','ready_inverter_input');solid(P(40,1,-32),'ready_support');solid(P(40,0,-32),'ready_floor');put(P(40,1,-31),'redstone_wall_torch',{facing:'south'},'not_ready');wire(P(40,1,-30),'not_ready_pad');rep(P(40,1,-29),'south','not_ready_normalize');wire(P(40,1,-28),'not_ready_wire');join([ready,P(40,1,-33),P(40,1,-32)]);join([P(40,1,-31),P(40,1,-30),P(40,1,-29),P(40,1,-28)]);route('not_ready_to_response',[[40,1,-28],[40,1,-2]]);
 rep(P(41,1,-34),'east','raw_ready_branch');wire(P(42,1,-34),'raw_ready_pad');join([ready,P(41,1,-34),P(42,1,-34)]);route('ready_to_complete_mask',[[42,1,-34],[70,1,-34],[70,1,-22]]);
 route('response_to_delay',[[42,1,0],[49,1,0]]);
 function delay(n,lo,hi,z){const ps=[];for(let x=lo;x<=hi;x++){const p=P(x,1,z);rep(p,'east',n,4);ps.push(p);}const inPad=P(lo-1,1,z),outPad=P(hi+1,1,z);wire(inPad,n+'_in');wire(outPad,n+'_out');join([inPad,...ps,outPad]);delays.push({name:n,input:inPad,output:outPad,cells:ps,nominal_ticks:ps.length*8});return outPad;}
 const d1=delay('capture_window',50,113,0),d2=delay('close_window',115,146,0);
 rep(P(42,1,1),'south','response_open_branch');wire(P(42,1,2),'response_open_pad');join([response.out,P(42,1,1),P(42,1,2)]);route('response_to_open',[[42,1,2],[42,1,6],[38,1,6],[38,1,10]]);
 rep(P(114,1,1),'south','capture_tail_branch');wire(P(114,1,2),'capture_tail_pad');join([d1,P(114,1,1),P(114,1,2)]);route('capture_tail_to_open_mask',[[114,1,2],[114,1,8],[40,1,8]]);
 route('close_tail_to_hold_mask',[[147,1,0],[147,1,-40],[0,1,-40],[0,1,-22]]);
 // Retained captured bit: D follows delayed A, HOLD=A&&!D2. On request rise
 // HOLD closes well before D rises; D2 later opens it to capture1. Request low
 // opens it and returns D to0. No clock/host state is hidden in this element.
 rep(P(2,1,-1),'north','request_hold_branch');wire(P(2,1,-2),'request_hold_pad');join([a.out,P(2,1,-1),P(2,1,-2)]);route('request_to_hold',[[2,1,-2],[2,1,-16],[-2,1,-16],[-2,1,-20]]);
 rep(P(3,1,-16),'east','request_data_branch');wire(P(4,1,-16),'request_data_pad');join([P(2,1,-16),P(3,1,-16),P(4,1,-16)]);delay('captured_data_guard',5,12,-16);route('captured_data_to_storage',[[13,1,-16],[23,1,-16]]);
 rep(P(24,1,-16),'east','captured_data_normalize');rep(P(25,1,-16),'east','captured_store');wire(P(26,1,-16),'captured_q');join([P(23,1,-16),P(24,1,-16),P(25,1,-16),P(26,1,-16)]);
 rep(P(25,1,-17),'south','captured_lock');route('hold_to_lock',[[2,1,-20],[25,1,-20],[25,1,-18]]);join([P(25,1,-18),P(25,1,-17),P(25,1,-16)]);
 rep(P(26,1,-15),'south','captured_export');wire(P(26,1,-14),'captured_export_pad');join([P(26,1,-16),P(26,1,-15),P(26,1,-14)]);route('captured_to_valid_mask',[[26,1,-14],[26,1,-8],[20,1,-8],[20,1,-2]]);
 // Crossing not-ready at x40 has four blocks of vertical clearance.
 route('captured_to_complete',[[26,1,-8],[28,1,-8],[32,5,-8],[50,5,-8],[54,1,-8],[62,1,-8],[62,1,-20],[68,1,-20]]);
 const port=(name,dir,p)=>ports[name]={direction:dir,width:1,polarity:'active_high',bits:[{bit:0,position:p,...(dir==='input'?{required_high_power:15}:{})}]};
 port('fetch_request','input',a.rear);port('reset_request','input',a.side);port('memory_ready','input',ready);port('memory_valid','output',valid.out);port('ir_open_request','output',open.out);port('fetch_complete','output',complete.out);port('captured','output',P(26,1,-16));port('capture_tail','output',d1);port('close_tail','output',d2);
 const blocks=[...map.values()],box={from:{},to:{}};for(const axis of ['x','y','z']){box.from[axis]=Math.min(...blocks.map(b=>b.position[axis]));box.to[axis]=Math.max(...blocks.map(b=>b.position[axis]));}
 return{status:'level_fetch_control_offline_candidate_unverified',blocks,box,ports,gates,delays,routes,edges,captured:{data:P(24,1,-16),store:P(25,1,-16),lock:P(25,1,-17),q:P(26,1,-16)},metrics:{blocks:blocks.length,stored_bits:1,comparators:6,delay_repeaters:104,dimensions:Object.fromEntries(['x','y','z'].map(axis=>[axis,box.to[axis]-box.from[axis]+1]))},equations:{A:'fetch_request && !reset_request',memory_valid:'A && !captured',Q:'memory_valid && memory_ready',capture_tail:'delayed Q',close_tail:'later delayed capture_tail',ir_open_request:'Q && !capture_tail',captured_D:'delayed A',captured_HOLD:'A && !close_tail',fetch_complete:'captured && !memory_ready'},protocol:{start:'Only after prior complete/return-to-zero, ready low, IR decode request/tail low and physical pipeline flush. Hold current PC stable as memory address.',response:'Memory owner must hold ready and instruction payload stable while memory_valid high. Capture command opens IR, then capture_tail closes it; close_tail waits further before captured commits1 and drops memory_valid.',finish:'fetch_complete requires captured1 AND ready0. Scheduler may then request decode; it lowers fetch_request and waits captured/complete0 before another fetch. PC stays unchanged until UPDATE.',reset:'Normal reset begins quiescent. reset_request blanks A and clears captured through real D/OPEN; it must remain asserted for a full validated delay-line flush before reset_ack from core. This module intentionally has no premature combinational reset_ack.',invalid:'Early ready/payload withdrawal, rapid request abort/rearm or simultaneous external decode/request violations are protocol faults. Delay count alone does not establish their native safety.'},missing:['External IR-open/PC-address/data routes and core scheduler decode-request/reset-ack generation.','Actual measured compatibility with held-IR open/close paths and any changed decoder load.','Runtime fault capture for a backend violating its ready/payload hold contract.'],native_acceptance:false,complete_gpu:false};
}
export function checkFetchControl(d){
 const m=new Map(d.blocks.map(b=>[K(b.position),b])),allowed=new Set(d.edges.map(e=>[K(e.from),K(e.to)].sort().join('|')));assert.equal(m.size,d.blocks.length);let supports=0,contacts=0,sides=0;
 for(const b of d.blocks){if(b.block.id.endsWith('_concrete'))continue;let p=P(b.position.x,b.position.y-1,b.position.z);if(b.block.id==='minecraft:redstone_wall_torch'){const[x,z]=V[b.block.properties.facing];p=P(b.position.x-x,b.position.y,b.position.z-z);}assert.equal(m.get(K(p))?.block.id,'minecraft:light_gray_concrete','support '+K(b.position));supports++;}
 for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))for(const[x,z]of Object.values(V))for(const y of [-1,0,1]){const p=P(b.position.x+x,b.position.y+y,b.position.z+z),o=m.get(K(p));if(!o||o.block.id.endsWith('_concrete'))continue;if(y&&o.block.id!=='minecraft:redstone_wire')continue;if(y===1&&m.has(K(P(b.position.x,b.position.y+1,b.position.z))))continue;if(y===-1&&m.has(K(P(p.x,p.y+1,p.z))))continue;assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign dust '+K(b.position)+' '+K(p));contacts++;}
 for(const b of d.blocks.filter(b=>['minecraft:repeater','minecraft:comparator'].includes(b.block.id))){const dir=Object.keys(F).find(d=>F[d]===b.block.properties.facing),[dx,dz]=V[dir];for(const[x,z]of[[dz,dx],[-dz,-dx]]){const p=P(b.position.x+x,b.position.y,b.position.z+z),o=m.get(K(p));if(o&&['minecraft:repeater','minecraft:comparator'].includes(o.block.id))assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign diode side '+K(b.position)+' '+K(p));sides++;}}
 for(const g of d.gates){const b=m.get(K(g.center)).block;assert.equal(b.properties.mode,'subtract');assert.equal(b.properties.facing,'west');}assert.equal(m.get(K(d.captured.lock)).block.properties.facing,'north');assert.equal(d.captured.lock.z+1,d.captured.store.z);assert.equal(m.get(K(d.captured.store)).block.properties.facing,'west');
 for(const delay of d.delays){for(const p of delay.cells)assert.deepEqual(m.get(K(p)).block.properties,{facing:'west',delay:'4'});assert.equal(delay.nominal_ticks,delay.cells.length*8);}
 assert.deepEqual(d.delays.map(v=>v.cells.length),[64,32,8]);
 return{status:'author_static_fetch_control_checks_passed',...d.metrics,support_checks:supports,dust_contact_checks:contacts,diode_side_faces:sides,nominal_only:{response_capture_window:512,subsequent_close_window:256,captured_data_guard:64},native_calls:0,limits:['No scheduled-tick simulation or native timing result.','Level protocol and real measured IR close/flush margins are prerequisites.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeFetchControl(),r=checkFetchControl(d);if(process.argv.includes('--check'))assert.deepEqual(JSON.parse(readFileSync(new URL('design.json',import.meta.url))),d);else{writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');writeFileSync(new URL('offline-check.json',import.meta.url),JSON.stringify(r,null,2)+'\n');}console.log(JSON.stringify(r,null,2));}
