import assert from 'node:assert/strict';
import {readFileSync,writeFileSync}from'node:fs';
import {makeGuardSampling}from'./prepare.mjs';
import {guardDefinition,nextDefinition,equation,nextState,stateValues}from'../control-lsu-v2/logic.mjs';
import {screen}from'./check-interactions.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
const d=makeGuardSampling(),base=read('../control-reset-closure-v1/design.json'),local=read('../control-lsu-v2/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v])),removed=new Set(d.removed.map(v=>K(v.position)));
assert.deepEqual(d,read('design.json'));let preserved=0;for(const v of base.blocks)if(!removed.has(K(v.position))){assert.deepEqual(m.get(K(v.position))?.block,v.block,'Unexpected parent edit '+K(v.position));preserved++;}
const core=read('../control-lsu-core-v1/design.json');const inheritedInit=core.routes.find(r=>r.name==='shared_initialize_lane3');assert(inheritedInit.path.some(p=>K(p)==='555,187,483'));assert.deepEqual(old.get('554,187,483').block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(d.connections.find(c=>c.name==='lane2_guard_initialize').source,P(555,187,483));
const expectedFields=['request','enable','mem_read','mem_write','reset','read_ready','write_ready','drained','update'];assert.deepEqual(d.guard_fields,expectedFields);assert.equal(new Set(d.removed.map(v=>`${v.lane}:${v.old_route}`)).size,44);assert.equal(d.bindings.length,44);assert.equal(d.connections.length,56);assert.equal(d.metrics.held_guard_bits,36);assert.equal(d.metrics.retained_bits,1076);
for(let lane=0;lane<4;lane++){const t=P(lane%2?600:300,lane>=2?150:0,400),move=p=>P(p.x+t.x,p.y+t.y,p.z+t.z);for(const[bit,name]of expectedFields.entries()){const y=1+4*bit,rows=d.bindings.filter(v=>v.lane===lane&&v.name===name);assert.equal(rows.length,['request','reset'].includes(name)?2:1);for(const b of rows){assert.deepEqual(b.raw_source,move(P(242,y,80)));assert.deepEqual(b.held_output,move(P(255,y,80)));const prior=local.connections.find(v=>v.name===b.removed_route);assert.deepEqual(b.next_receiver,move(prior.destination));const c=d.connections.find(v=>v.name===`lane${lane}_${b.removed_route}_held`);assert.deepEqual(c.source,b.held_output);assert.deepEqual(c.destination,b.next_receiver);}
assert.deepEqual(m.get(K(move(P(252,y,80)))).block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(m.get(K(move(P(252,y,79)))).block,{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});assert.deepEqual(m.get(K(move(P(246,y,80)))).block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});}
for(const kind of ['done','reset_ack','fault']){const x={done:102,reset_ack:122,fault:142}[kind];assert.deepEqual(m.get(K(move(P(x,1,60)))).block,old.get(K(move(P(x,1,60)))).block);for(const v of local.blocks.filter(v=>v.part==='status_data_'+kind))assert.deepEqual(m.get(K(move(v.position)))?.block,v.block);}
for(const suffix of ['low','high']){const c=d.connections.find(v=>v.name===`lane${lane}_guard_B_${suffix}`);assert.deepEqual(c.source,move(P(242,45,80)));assert.deepEqual(c.destination,move(P(250,suffix==='low'?0:32,77)));}
}
const def=nextDefinition(),decode=o=>Object.entries(o).reduce((s,[n,v])=>s+(v?1<<Number(n.slice(1)):0),0);let cases=0,lateA=0,resetPriority=0;
for(let bits=0;bits<512;bits++){const held=Object.fromEntries(expectedFields.map((n,i)=>[n,!!(bits&(1<<i))]));for(const is_write of[false,true])for(let s=0;s<16;s++){const guards=equation(guardDefinition(),{...held,is_write}),v={...held,...guards};assert.equal(decode(equation(def,{...stateValues(s),...v,initialize:false})),nextState(s,v));cases++;for(const name of expectedFields){const rawLater={...held,[name]:!held[name]};assert.notDeepEqual(rawLater,held);const stillHeld=equation(guardDefinition(),{...held,is_write});assert.equal(decode(equation(def,{...stateValues(s),...held,...stillHeld,initialize:false})),nextState(s,v));lateA++;}if(held.reset){assert(!guards.start&&!guards.invalid);resetPriority++;}}}
// Old derived-start plus independently sampled reset admits an incoherent value.
const incoherent={start:true,invalid:false,reset:true,safe:true};assert.equal(decode(equation(def,{...stateValues(0),...incoherent,initialize:false})),11);assert.equal(nextState(0,incoherent),11);
// With invalid also stale-high, the old product matrix ORs 11 with 15. Raw sampling recomputes both false under held reset.
assert.equal(decode(equation(def,{...stateValues(0),...incoherent,invalid:true,initialize:false})),15);assert.equal(nextState(0,{...incoherent,invalid:true}),11);
let zeroClampCases=0;for(let power=0;power<=15;power++){assert.equal(Math.max(0,power-15),0);zeroClampCases++;}for(let unknown=0;unknown<512;unknown++){let held=expectedFields.map((_,b)=>!!(unknown&(1<<b)));const withoutB=[...held];held=held.map(()=>false);assert(held.every(v=>!v));if(unknown)assert(withoutB.some(Boolean));zeroClampCases++;}
const eligible=new Set(base.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'&&!removed.has(K(v.position))).map(v=>K(v.position)));let oldEdges=0;
function neighbors(p,map){const out=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(!eligible.has(K(q)))continue;if(y===1&&map.has(K(P(p.x,p.y+1,p.z))))continue;if(y===-1&&map.has(K(P(q.x,q.y+1,q.z))))continue;out.push(K(q));}return out.sort();}
for(const k of eligible){const p=old.get(k).position,a=neighbors(p,old);assert.deepEqual(neighbors(p,m),a,'Retained wire graph changed '+k);oldEdges+=a.length;}
const report={status:'author_static_B_held_raw_LSU_guard_check',...d.metrics,preserved_parent_cells:preserved,preserved_old_wire_edges:oldEdges,settled_next_cases:cases,late_A_raw_change_models:lateA,reset_guard_priority_cases:resetPriority,zero_clamp_models:zeroClampCases,existing_held_status_cells_preserved:12,...screen(d),native_acceptance:false,asynchronous_capture_timing_proven:false,final_reset_ack_proven:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,taps:undefined}));
