// Recover real operator levers and actual old/current START and raw RESET delivery.
import assert from 'node:assert/strict';import {writeFileSync}from'node:fs';
import {H,read,bytes,K,pins,loadFrame}from'./frame.mjs';
import {inputs,active}from'../memory/fabric-colocation-v2/cut-inputs.mjs';
import {evaluate}from'../dispatch-external-bindings-v1/transport-functions.mjs';
import {backwardCone,makeSettledEvaluator}from'../program-global-delivery-v1/settled-program-network.mjs';
import {checkFeedback}from'../loader-program-colocation-v1/service-mask-memory-composition-v1/feedback.mjs';
import {scanBlocks}from'../global-loader-return-review-v1/independent-network.mjs';
const P=(x,y,z)=>({x,y,z}),A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),write=(n,d)=>writeFileSync(new URL(n,H),JSON.stringify(d,null,2)+'\n');
const assignment=read('../panel-loader-input-recovery-v1/assignment.json','d55df62d13faf06711a924faf4d37c6593b30964e2fa8d6e4f7a0823058cf49f'),buffer=bytes('../initial-loader-warm-drain-v3/design.json'),parts=new Set(['config_panel_parent',...assignment.connections.map(c=>c.name)]),selectedRows=[];
const scanned=scanBlocks(buffer,r=>{if(parts.has(r.part))selectedRows.push(r);});assert(selectedRows.length>0);const wanted=new Set();for(const r of selectedRows)for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++)wanted.add(K(A(r.position,P(x,y,z))));const old=new Map();scanBlocks(buffer,r=>{if(wanted.has(K(r.position))){assert(!old.has(K(r.position)));old.set(K(r.position),r.block);}});
const {world}=loadFrame(),translation=P(296,-35,-880),allBoundaries=[{name:'raw_start',old:P(-412,-4,584)},{name:'raw_reset',old:P(-407,-4,595)}].map(b=>({...b,current:A(b.old,translation)})),selected=[],sources=[];
for(const record of assignment.connections){const original=record.old_connection,index=record.direct_index;const boundary=allBoundaries[index-1];assert.equal(old.get(K(boundary.old)).id,'minecraft:lever');assert.deepEqual(old.get(K(boundary.old)),world.get(K(boundary.current)));assert.deepEqual(old.get(K(original.source)),world.get(K(record.current_source)));assert.deepEqual(old.get(K(original.destination)),world.get(K(record.current_destination)));assert.equal(inputs(world,record.current_destination).length,0);
 const owned=new Set(selectedRows.filter(r=>r.part===record.name&&active(r.block)).map(r=>K(r.position))),transport=new Set(),todo=[original.arrival];for(let i=0;i<todo.length;i++){const p=todo[i],k=K(p);if(k===K(original.source)||transport.has(k))continue;assert(owned.has(k),'Foreign old transport '+k);transport.add(k);todo.push(...inputs(old,p));}const func=evaluate(old,transport).get(original.arrival);assert.deepEqual(func,{roots:[original.source],table:2});assert(inputs(old,original.destination).some(p=>K(p)===K(original.arrival)));
 const oldPositions=backwardCone(old,original.source,[boundary.old]),currentPositions=backwardCone(world,record.current_source,[boundary.current]);assert.deepEqual(new Set(oldPositions.map(p=>K(A(p,translation)))),new Set(currentPositions.map(K)));assert.equal(oldPositions.length,3);for(const p of oldPositions)assert.deepEqual(old.get(K(p)),world.get(K(A(p,translation))));
 const a=makeSettledEvaluator(old,oldPositions,[boundary.old]),b=makeSettledEvaluator(world,currentPositions,[boundary.current]),full=makeSettledEvaluator(old,backwardCone(old,original.destination,[boundary.old]),[boundary.old]),cases=[];for(let mask=0;mask<2;mask++){const expected=mask?15:0,oldValue=a(new Map([[K(boundary.old),expected]])).power.get(K(original.source))??0,currentValue=b(new Map([[K(boundary.current),expected]])).power.get(K(record.current_source))??0,oldArrival=full(new Map([[K(boundary.old),expected]])).power.get(K(original.destination))??0;assert.deepEqual([oldValue,currentValue,oldArrival],[expected,expected,expected]);cases.push({mask,values:{[boundary.name]:!!mask},old_output:oldValue,current_output:currentValue,old_arrival:oldArrival});}
 selected.push({name:record.name,transfer_index:index,direct_index:index,loader_index:record.loader_index,new_source:record.current_source,new_destination:record.current_destination,source:original.source,target:original.destination,old_normalizer:original.arrival,old_route_function:func,old_transport_vertices:transport.size,old_source_successors:[...transport].map(k=>P(...k.split(',').map(Number))).filter(p=>inputs(old,p).some(q=>K(q)===K(original.source)))});sources.push({transfer_index:index,boundaries:[boundary],cases,original_cone:oldPositions.map(p=>({position:p,block:old.get(K(p)),inputs:K(p)===K(boundary.old)?[]:inputs(old,p)})),current_cone:currentPositions.map(p=>({position:p,block:world.get(K(p)),inputs:K(p)===K(boundary.current)?[]:inputs(world,p)})),feedback:checkFeedback(world,currentPositions,[boundary.current])});}
bytes('../global-loader-return-review-v1/independent-network.mjs');write('source-functions.json',{status:'actual_original_panel_loader_deliveries_positive',selected,sources,scanned_original_cells:scanned,actual_original_context_cells:old.size,original_selected_cells:selectedRows.length,source_sha256:pins,limits:['Only the two real panel levers are test boundaries. Their original three-device producer chains and original positive transports are checked.','No host control source or replacement state is introduced. Preserve all retained fanout.','Raw RESET is the operator signal before the independent DCR mask. Loader admission/edge timing and whole-system transitions remain unverified.','No Minecraft changes or physical proof.']});console.log(JSON.stringify({status:'sources_pass',routes:selected.length,cases:sources.reduce((n,s)=>n+s.cases.length,0),original_cells:scanned,old_context:old.size,old_transport:selected.reduce((n,s)=>n+s.old_transport_vertices,0)}));
