// Two actual operator panel deliveries against the exact accepted shared frame.
import assert from'node:assert/strict';import{loadFrame,pins}from'./frame.mjs';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{inputs,active}from'../memory/fabric-colocation-v2/cut-inputs.mjs';import{searchPath,refreshIndices,P,K,F}from'../control-commit-v2/route.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v)+'\n'),A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),S=(p,n)=>P(p.x*n,p.y*n,p.z*n),U=p=>A(p,P(0,-1,0)),DIR=[P(1,0,0),P(0,0,1),P(-1,0,0),P(0,0,-1)],dir=v=>v.x>0?'east':v.x<0?'west':v.z>0?'south':'north',W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',SOL='minecraft:light_gray_concrete';
const {world}=loadFrame(),functions=read('source-functions.json');assert.equal(functions.status,'actual_original_panel_loader_deliveries_positive');
const near=[];for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)near.push(P(x,y,z));
const added=[],checks=[],refusals=[],routes=[],connections=[],cache=existsSync(new URL('paths.json',H))?read('paths.json'):{},dev=(p,id=W,properties)=>[{position:U(p),block:{id:SOL}},{position:p,block:{id,...properties?{properties}:{}}}];
function patch(name,rows,{extra=[],expectedInputs=[],commit=false}={}){
 const keys=new Set(),affected=new Map();for(const r of rows){const k=K(r.position);if(world.has(k)||keys.has(k))return{ok:false,why:'occupied_or_duplicate',point:r.position};keys.add(k);for(const o of near){const p=A(r.position,o),b=world.get(K(p));if(active(b)&&!affected.has(K(p)))affected.set(K(p),{p,inputs:inputs(world,p).map(K).sort()});}}
 for(const r of rows)world.set(K(r.position),r.block);let bad;for(const [k,v]of affected){const expected=[...new Set([...v.inputs,...extra.filter(e=>K(e.target)===k).map(e=>K(e.source))])].sort(),actual=inputs(world,v.p).map(K).sort();if(JSON.stringify(expected)!==JSON.stringify(actual)){bad={why:'old_input_changed',point:v.p,expected,actual};break;}}
 if(!bad)for(const e of expectedInputs){const actual=inputs(world,e.target).map(K).sort(),expected=e.sources.map(K).sort();if(JSON.stringify(actual)!==JSON.stringify(expected)){bad={why:'new_input_wrong',point:e.target,expected,actual};break;}}
 if(bad||!commit)for(const r of rows)world.delete(K(r.position));if(bad)return{ok:false,...bad};if(commit){added.push(...rows.map(r=>({...r,part:name})));checks.push({name,added_cells:rows.length,old_receivers:affected.size,permitted_extra:extra});}return{ok:true,rows,old_receivers:affected.size};
}
function knownPath(name,path,{existingFirst=true,existingLast=false,lastRepeater=false,direction,extra=[]}={}){const rows=[],expect=[];for(let i=existingFirst?1:0;i<path.length-(existingLast?1:0);i++){const p=path[i],isR=lastRepeater&&i===path.length-1;rows.push(...dev(p,isR?R:W,isR?{facing:F[direction],delay:'1'}:undefined));expect.push({target:p,sources:[path[i-1],!isR&&i+1<path.length&&world.get(K(path[i+1]))?.id!==R?path[i+1]:null].filter(Boolean)});}return{rows,expectedInputs:expect,extra};}
const plans=[];
function sourceStub(name,source,preferred=P(0,0,-1)){
 for(const d of [preferred,...DIR])for(const dy of [0,1,-1]){const path=[1,2,3,4,5,6].map(i=>A(A(source,S(d,i)),P(0,dy*Math.min(i-1,3),0))),rows=path.flatMap((p,i)=>dev(p,i===0||i===4?R:W,i===0||i===4?{facing:F[dir(d)],delay:'1'}:undefined)),expectedInputs=path.map((p,i)=>({target:p,sources:[i?path[i-1]:source,i!==0&&i!==4&&i+1!==4?path[i+1]:null].filter(Boolean)}));
 const tip=path.at(-1),escape=A(tip,A(d,P(0,dy,0)));if(near.filter(o=>Math.abs(o.x)+Math.abs(o.y)+Math.abs(o.z)<=2).some(o=>world.has(K(A(escape,o)))))continue;
 const r=patch(name+'_departure',rows,{expectedInputs,commit:true});if(r.ok)return{source,source_isolator:path[0],source_stub:path};refusals.push({name:name+'_departure',d,dy,...r});}write('refusals.json',refusals);throw Error('No source stub '+name);
}
function receiverStub(name,destination,preferred=P(0,0,-1)){
 // d points from terminal toward the receiving cable.
 for(const d of [preferred,...DIR]){const tail=[4,3,2,1].map(i=>A(destination,S(d,i))),normalizer=tail.at(-1),rows=tail.flatMap((p,i)=>dev(p,i===0||i===tail.length-1?R:W,i===0||i===tail.length-1?{facing:F[dir(S(d,-1))],delay:'1'}:undefined)),expectedInputs=tail.map((p,i)=>({target:p,sources:[tail[i-1],i>0&&i<tail.length-2?tail[i+1]:null].filter(Boolean)}));const r=patch(name+'_arrival',rows,{extra:[{target:destination,source:normalizer}],expectedInputs,commit:true});if(r.ok)return{destination,receiving_stub:tail,normalizer,extra:[{target:destination,source:normalizer}],final_graph:[...tail,destination]};refusals.push({name:name+'_arrival',d,...r});}write('refusals.json',refusals);throw Error('No receiver stub '+name);
}
for(const b of functions.selected){const name=b.name;plans.push({name,kind:'panel_loader_control',root:b.new_source,...sourceStub(name,b.new_source),...receiverStub(name,b.new_destination)});}
write('planned-connections.json',{plans,checks,refusals});
for(const c of plans){const front=c.source_stub,tail=c.receiving_stub,start=front.at(-1),end=tail[0],fixed=[...front,...tail,...front.map(U),...tail.map(U)],allow=new Set([start,end,...[start,end].flatMap(p=>DIR.flatMap(v=>[-1,0,1].map(dy=>A(A(p,v),P(0,dy,0)))))].map(K)),forbidden=[];
 for(const q of[c.source,c.destination,...front,...tail])for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)for(let dy=-2;dy<=2;dy++){if(Math.abs(dx)+Math.abs(dz)>1)continue;const p=A(q,P(dx,dy,dz));if(!allow.has(K(p)))forbidden.push(p);}const step=P(start.x-front.at(-2).x,0,start.z-front.at(-2).z);for(const dy of[-1,0,1])forbidden.push(A(start,P(-step.x,dy,-step.z)));
 const receiverRear=P(2*end.x-tail[1].x,end.y,2*end.z-tail[1].z);for(const v of DIR)for(const dy of[-1,0,1]){const p=A(A(end,v),P(0,dy,0));if(K(p)!==K(receiverRear))forbidden.push(p);}
 const reserved=plans.filter(v=>v.name!==c.name).flatMap(v=>[...v.source_stub,...v.receiving_stub]).flatMap(p=>[-1,0,1].map(dy=>A(p,P(0,dy,0))));let path=cache[c.name];if(path&&(K(path[0])!==K(start)||K(path.at(-1))!==K(end)||K(path.at(-2))!==K(receiverRear)))path=null;if(!path){const result=searchPath(world,end,start,{limit:900000,ignore:[c.source,c.destination,...fixed],forbidden,reserved});path=result.path.reverse();cache[c.name]=path;write('paths.json',cache);console.log(JSON.stringify({name:c.name,vertices:path.length,expanded:result.expanded}));}assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=new Set(refreshIndices(path)),rows=[];for(let i=1;i<path.length-1;i++){const p=path[i],v=P(path[i+1].x-p.x,0,path[i+1].z-p.z);rows.push(...dev(p,refresh.has(i)?R:W,refresh.has(i)?{facing:F[dir(v)],delay:'1'}:undefined));}
 // Endpoints were already drawn; add the selected route then require complete
 // normalized geometry in check.mjs, including all old/body input comparisons.
 for(const r of rows){assert(!world.has(K(r.position)),'Route collision '+c.name+' '+K(r.position));world.set(K(r.position),r.block);added.push({...r,part:c.name});}
 const complete=[c.source,...front.slice(0,-1),...path,...c.final_graph.slice(1)];
 routes.push({name:c.name,path:complete});connections.push({...c,path_vertices:complete.length});write('routing-progress.json',{completed:routes.map(r=>r.name),pending:plans.filter(v=>!routes.some(r=>r.name===v.name)).map(r=>r.name),added_cells:added.length});
}
const result={status:'mutable_panel_loader_delivery_requires_checks',base_cells:2192096,concurrent_obstacle_cells:0,new_cells:added,connections,routes,source_stub_checks:checks,source_sha256:{...functions.source_sha256,...pins},new_routes:routes.length};write('delta.json',result);console.log(JSON.stringify({routes:routes.length,added_cells:added.length}));
