import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {makeStateDecoder} from '../../../../hardware/full-gpu-state-decoder.mjs';
import {makeAddressDecoder4} from '../../../../hardware/address-decoder4.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D);
const d=makeStateDecoder(),parent=makeAddressDecoder4({origin:P(0,0,0),id:'gpu_state_decoder_source'});assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),removed=new Set(d.removed_source_cells.map(v=>K(v.position)));let inherited=0,supports=0,sides=0;
for(let bank=0;bank<2;bank++)for(const v of parent.blocks){const q={...v.position,y:v.position.y+128*bank};if(removed.has(K(q)))continue;assert.deepEqual(at(q).block,v.block);inherited++;}
for(const v of d.blocks){if(v.block.id==='minecraft:light_gray_concrete')continue;const support=v.block.id==='minecraft:redstone_wall_torch'?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(support)?.block.id,'minecraft:light_gray_concrete','support '+K(v.position));supports++;}
for(const v of d.blocks.filter(v=>!v.part.startsWith('decoder4_')&&['minecraft:repeater','minecraft:comparator'].includes(v.block.id))){const delta=D[v.block.properties.facing];for(const s of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,s),b=at(p)?.block;if(!b||b.id==='minecraft:light_gray_concrete'){sides++;continue;}assert(v.block.id==='minecraft:comparator'&&p.x===12&&p.z===5&&b.id==='minecraft:repeater','Foreign diode side '+K(v.position));assert.deepEqual(add(p,D[b.properties.facing]),v.position);sides++;}}
// All old active cells are unchanged. Screen newly created dust contacts into
// their boundary and across state planes, including diagonal dust slopes.
let dustFaces=0;const boundary=new Set();for(let state=0;state<32;state++){const y=1+8*state;boundary.add([K(P(10,y,6)),K(P(9,y,6))].sort().join('|'));}
for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'&&!v.part.startsWith('decoder4_')))for(const dir of dirs){const p=add(v.position,dir),other=at(p);if(other&&!['minecraft:light_gray_concrete','minecraft:redstone_torch'].includes(other.block.id)&&other.part.startsWith('decoder4_'))assert(boundary.has([K(p),K(v.position)].sort().join('|')),'Foreign parent contact');for(const dy of[-1,1]){const q={...p,y:p.y+dy};if(at(q)?.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert.fail('Unexpected dust slope');}dustFaces++;}
let directedSteps=0;
const directed=(position,output)=>{const b=at(position)?.block;assert.equal(b?.id,'minecraft:repeater');assert.deepEqual(add(position,D[b.properties.facing]),output);directedSteps++;};
for(const input of d.ports.state.bits)directed(input.receiver,P(input.column.x,-3,input.column.z));
for(const branch of d.maskBranches){const y=branch.comparator.y;if(!branch.high)directed(P(18,y,0),P(17,y,0));else assert.deepEqual(at(P(17,y,0)).block.properties,{facing:'west'});
 directed(P(15,y,0),P(14,y,0));directed(P(12,y,5),P(12,y,6));directed(P(11,y,6),P(12,y,6));directed(P(14,y,6),P(15,y,6));assert.deepEqual(at(P(12,y,6)).block.properties,{facing:'west',mode:'subtract'});
 const path=[P(14,y,0),P(14,y,1),P(14,y,2),P(14,y,3),P(14,y,4),P(13,y,4),P(12,y,4)];let power=15;for(const pos of path){assert.equal(at(pos).block.id,'minecraft:redstone_wire');assert(power>0);power--;}
}
let polarityCases=0;
for(let value=0;value<32;value++){const one=[];for(const branch of d.maskBranches){const low=value%16===branch.state%16?15:0,high=(value>>4)&1;const mask=branch.inverter?(!high?15:0):(high?15:0);assert.equal(at(branch.comparator).block.properties.mode,'subtract');const signal=Math.max(0,low-mask);if(signal>0)one.push(branch.state);polarityCases++;}assert.deepEqual(one,[value]);}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const result={status:'offline_shared_state_decoder_static_checks_pass',blocks:d.blocks.length,unchanged_parent_cells:inherited,removed_fixture_source_cells:removed.size,supports,new_diode_side_faces:sides,directed_new_repeater_steps:directedSteps,new_dust_neighbor_screens:dustFaces,settled_state_output_cases:polarityCases,sources:{generator:sha('../../../../hardware/full-gpu-state-decoder.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,limits:['The low-nibble decode truth follows unchanged source topology; this is not complete electrical simulation.','Tall-column initialization, transition hazards, new mask paths and timing remain native gates.','Control-state conditioning, microinstruction output matrix and physical controller remain missing.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
