import assert from 'node:assert/strict';
import {readFileSync,writeFileSync}from'node:fs';
import {makeCoreGuards,doneDefinition}from'./prepare.mjs';
import {equation}from'../control-lsu-v2/logic.mjs';
import {nextCoreState}from'../control-core-v1/prepare.mjs';
import {screen}from'./check-interactions.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
const d=makeCoreGuards(),base=read('../control-lsu-guards-v3/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v])),removed=new Set(d.removed.map(v=>K(v.position)));
assert.deepEqual(d,read('design.json'));assert.equal(removed.size,64);assert.equal(d.bindings.length,16);assert.equal(d.metrics.advance_sample_bits,16);assert.equal(d.metrics.held_done_bits,1);assert.equal(d.metrics.retained_bits,1093);
let preserved=0;for(const v of base.blocks)if(!removed.has(K(v.position))){assert.deepEqual(m.get(K(v.position))?.block,v.block,'Unexpected parent edit '+K(v.position));preserved++;}
for(const b of d.bindings){const g=d.groups.find(g=>g.name===b.group),rowY=g.t.y+1+8*b.row;assert.deepEqual(b.raw_final_masked_pad,P(g.t.x+22,rowY,g.t.z-2));assert.deepEqual(b.hold_receiver,P(g.t.x+20,rowY,g.t.z-2));assert.deepEqual(b.inverse_receiver,P(g.t.x+22,rowY,g.t.z+2));for(const suffix of ['held_hold','held_inverse_driver']){const c=d.connections.find(c=>c.name===`${g.name}_row${b.row}_${suffix}`);assert.deepEqual(c.source,b.held);}const c=d.connections.find(c=>c.name===`${g.name}_row${b.row}_capture`);assert.deepEqual(c.source,b.raw_final_masked_pad);assert.deepEqual(m.get(K(c.tap)).block,{id:'minecraft:repeater',properties:{facing:'north',delay:'1'}});assert.deepEqual(m.get(K(b.inverse_torch)).block,{id:'minecraft:redstone_wall_torch',properties:{facing:'south'}});assert(!m.has(K(P(g.t.x+21,rowY,g.t.z-2))),'Raw hold branch was restored');assert.equal(m.get(K(P(g.t.x+22,rowY,g.t.z))).block.id,'minecraft:redstone_wire');assert.notEqual(m.get(K(P(g.t.x+22,rowY,g.t.z+1)))?.block.id,'minecraft:redstone_wall_torch','Raw inverse torch was restored');}
assert.equal(m.get('22,50,2').block.id,'minecraft:light_gray_concrete');assert.equal(m.get('22,49,2').block.id,'minecraft:redstone_wire');
function latchDirections(storage,lock){assert.deepEqual(storage,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(lock,{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});}
let lockDirections=0;for(const g of [...d.groups,{bank:P(180,40,-160),rows:[0]}])for(let b=0;b<g.rows.length;b++){const p=P(g.bank.x+2,g.bank.y+1+4*b,g.bank.z);latchDirections(m.get(K(p)).block,m.get(K(P(p.x,p.y,p.z+1))).block);assert.equal(m.get(K(P(p.x,p.y,p.z+2))).block.id,'minecraft:redstone_wire');lockDirections++;}
let corruptions=0;for(const facing of ['north','east','west']){assert.throws(()=>latchDirections({id:'minecraft:repeater',properties:{facing:'west',delay:'1'}},{id:'minecraft:repeater',properties:{facing,delay:'1'}}));corruptions++;}
assert.throws(()=>latchDirections({id:'minecraft:repeater',properties:{facing:'east',delay:'1'}},{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}}));corruptions++;
let sampledCases=0;for(let s=0;s<8;s++)for(let held=0;held<128;held++)for(let late=0;late<2;late++)for(let ret=0;ret<2;ret++){const advance=!!(held&(1<<s)),rawAfterA=!!late;const expected=nextCoreState(s,advance,!!ret);assert.equal(nextCoreState(s,advance,!!ret),expected);if(rawAfterA!==advance)assert.equal(nextCoreState(s,advance,!!ret),expected);sampledCases++;}
let doneCases=0;const def=doneDefinition();for(let v=0;v<512;v++){const inputs=Object.fromEntries(def.inputs.map((n,b)=>[n,!!(v&(1<<b))])),expected=!inputs.fault&&!inputs.initialize&&(inputs.held_done||(inputs.terminal&&inputs.commit_idle&&inputs.owner_idle&&inputs.rf_quiet&&inputs.lsu_quiet&&inputs.all_status_low));assert.equal(!!equation(def,inputs).done_D,expected);doneCases++;}
// Explicit unconstrained binary order: UPDATE6→FETCH1 can transiently pass DONE7.
const transient=[6,7,3,1];assert(transient.includes(7));let heldDone=false;for(const s of transient){const raw=s===7;assert.equal(heldDone,false);void raw;}const settled={terminal:false,commit_idle:true,owner_idle:true,rf_quiet:true,lsu_quiet:true,all_status_low:true,fault:false,initialize:false,held_done:heldDone};heldDone=!!equation(def,settled).done_D;assert.equal(heldDone,false);settled.terminal=true;heldDone=!!equation(def,settled).done_D;assert.equal(heldDone,true);settled.held_done=true;settled.terminal=false;assert(equation(def,settled).done_D);assert(!equation(def,{...settled,initialize:true}).done_D);assert(!equation(def,{...settled,fault:true}).done_D);
const eligible=new Set(base.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'&&!removed.has(K(v.position))).map(v=>K(v.position)));let oldEdges=0;
function neighbors(p,map){const out=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(!eligible.has(K(q)))continue;if(y===1&&map.has(K(P(p.x,p.y+1,p.z))))continue;if(y===-1&&map.has(K(P(q.x,q.y+1,q.z))))continue;out.push(K(q));}return out.sort();}
for(const k of eligible){const p=old.get(k).position,a=neighbors(p,old);assert.deepEqual(neighbors(p,m),a,'Retained wire graph changed '+k);oldEdges+=a.length;}
const report={status:'author_static_final_guard_sampling_and_held_DONE_candidate',...d.metrics,preserved_parent_cells:preserved,preserved_old_wire_edges:oldEdges,conditional_held_core_cases:sampledCases,done_truth_cases:doneCases,actual_lock_directions:lockDirections,wrong_direction_rejections:corruptions,transient_decode_example:transient,...screen(d),native_acceptance:false,phase_timing_proven:false,complete_reset_ack:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,taps:undefined}));
