// Hold final qualified advance decisions across NEXT-A; never sample raw DONE remotely.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync}from'node:fs';
import {createHash}from'node:crypto';
import {pathToFileURL}from'node:url';
import {makeStateBank}from'../../../hardware/full-gpu-state-bank.mjs';
import {materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
import {makeMatrix}from'../control-lsu-v2/matrix.mjs';
import {P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),W='minecraft:redstone_wire';
export const doneDefinition=()=>({inputs:['terminal','commit_idle','owner_idle','rf_quiet','lsu_quiet','all_status_low','fault','initialize','held_done'],outputs:['done_D'],products:[{out:'done_D',literals:{held_done:true,fault:false,initialize:false}},{out:'done_D',literals:{terminal:true,commit_idle:true,owner_idle:true,rf_quiet:true,lsu_quiet:true,all_status_low:true,fault:false,initialize:false}}]});
export function makeCoreGuards({plan=false}={}){
 assert.equal(createHash('sha256').update(readFileSync(new URL('../control-lsu-guards-v3/source-manifest.json',import.meta.url))).digest('hex'),'0ac3cc3488ea4169a4e83d5e67c2b51ce871efae5e34f363bc1ca199d1809ea5');const pm=read('../control-lsu-guards-v3/source-manifest.json');assert.equal(createHash('sha256').update(readFileSync(new URL('../control-lsu-guards-v3/design.json',import.meta.url))).digest('hex'),pm.source_sha256['artifacts/full-gpu-layout-v1/control-lsu-guards-v3/design.json']);
 const base=read('../control-lsu-guards-v3/design.json'),map=new Map(base.blocks.map(v=>[K(v.position),{...v,part:'base'}])),parents={base:{blocks:base.blocks.length,translation:P(0,0,0)}},edges=[],routes=[],connections=[],removed=[],bindings=[],clear_columns=[],positive_columns=[];let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to}),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),move=(p,t)=>P(p.x+t.x,p.y+t.y,p.z+t.z);
 function put(p,id,properties){const block={id:'minecraft:'+id,...properties?{properties}:{}};if(at(p)){assert.equal(id,'light_gray_concrete','Collision '+part+' '+K(p));assert.deepEqual(at(p).block,block);return;}map.set(K(p),{position:p,block,part});}
 const solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'});
 function insert(name,d,t){const r=materializeInstance(d,{id:name,translation:t});for(const v of r.blocks){assert(!at(v.position),'Component collision '+name+' '+K(v.position));map.set(K(v.position),{...v,part:name});}for(const e of d.edges??[])edge(move(e.from,t),move(e.to,t));parents[name]={blocks:d.blocks.length,translation:t};return r;}
 const pt=(d,n,b=0)=>d.ports[n].bits[b].position,pending=[],connect=(...a)=>pending.push(a);
 const groups=[{name:'core',rows:[0,1,2,3,4,5,6],t:P(0,0,0),bank:P(80,0,-120)},{name:'owner',rows:[0,1,4,6,7],t:P(600,200,-400),bank:P(660,180,-430)},{name:'commit',rows:[0,5,6,7],t:P(350,200,-400),bank:P(450,200,-450)}];
 // Split both consumers of the actual final masked pad. The live pad continues
 // only into the new sampler; held Q drives hold and its inverse separately.
 for(const g of groups)for(const row of g.rows){const y=1+8*row;const targets=[[P(21,y,-2),{id:'minecraft:repeater',properties:{facing:'east',delay:'1'}}],[P(22,y,0),{id:'minecraft:light_gray_concrete'}],[P(22,y,1),{id:'minecraft:redstone_wall_torch',properties:{facing:'south'}}]];for(const[p,expected]of targets){const q=move(p,g.t);assert.deepEqual(at(q)?.block,expected,'Raw consumer '+g.name+' '+row+' '+K(q));removed.push({...at(q),position:q,group:g.name,row});map.delete(K(q));if(p.x===21){const a=P(q.x,q.y-1,q.z);removed.push({...at(a),position:a,group:g.name,row});map.delete(K(a));}}}
 const removedKeys=new Set(removed.map(v=>K(v.position)));for(const e of base.edges)if(!removedKeys.has(K(e.from))&&!removedKeys.has(K(e.to)))edge(e.from,e.to);
 // Common positive phase-B and initialize columns are actual physical fanout.
 const column=(name,x,bottom,top)=>{part=name;for(let y=bottom;y<=top;y++)put(P(x,y,-110),(y-bottom)%2===0?'light_gray_concrete':'redstone_torch');wire(P(x-2,bottom,-110));rep(P(x-1,bottom,-110),'east');edge(P(x-2,bottom,-110),P(x-1,bottom,-110));edge(P(x-1,bottom,-110),P(x,bottom,-110));edge(P(x-1,bottom,-110),P(x,bottom+1,-110));for(let y=bottom+1;y<top;y+=2)edge(P(x,y,-110),P(x,y+2,-110));const outputs=[];for(const y of(name==='sample_B_column'?[0,180,200]:[-3,177,197])){assert.equal((y-bottom)%4,0);wire(P(x+1,y,-110));rep(P(x+2,y,-110),'east');wire(P(x+3,y,-110));edge(P(x,y,-110),P(x+1,y,-110));edge(P(x+1,y,-110),P(x+2,y,-110));edge(P(x+2,y,-110),P(x+3,y,-110));if(y>bottom)edge(P(x,y-1,-110),P(x+1,y,-110));else edge(P(x-1,y,-110),P(x+1,y,-110));if(y<top)edge(P(x+1,y,-110),P(x,y+1,-110));outputs.push({solid:P(x,y,-110),wire:P(x+1,y,-110),effective_source:y===bottom?P(x-1,y,-110):P(x,y-1,-110),output:P(x+3,y,-110)});}positive_columns.push({name,x,z:-110,bottom,top,outputs});return P(x-2,bottom,-110);};
 const bInput=column('sample_B_column',100,0,200),iInput=column('sample_initialize_column',110,-3,197);
 connect('actual_B_to_sampler_column',P(-52,2,17),'south',bInput,'east');connect('actual_initialize_to_sampler_column',P(-67,21,-6),'east',iInput,'east');
 const samples=[];
 for(const g of groups){const bank=insert(g.name+'_advance_samples',makeStateBank({width:g.rows.length,pair:false}),g.bank);samples.push({group:g.name,ports:bank.ports});const {x,y,z}=g.bank,cx=x-4,cz=z-4;part=g.name+'_sample_clear';for(let q=y-3;q<=y+1+4*(g.rows.length-1);q++)put(P(cx,q,cz),(q-y+3)%2===0?'light_gray_concrete':'redstone_torch');for(let q=y-2;q<y+4*(g.rows.length-1);q+=2)edge(P(cx,q,cz),P(cx,q+2,cz));wire(P(cx,y-3,cz-3));wire(P(cx,y-3,cz-2));rep(P(cx,y-3,cz-1),'south');edge(P(cx,y-3,cz-3),P(cx,y-3,cz-2));edge(P(cx,y-3,cz-2),P(cx,y-3,cz-1));edge(P(cx,y-3,cz-1),P(cx,y-3,cz));edge(P(cx,y-3,cz-1),P(cx,y-2,cz));const outputs=[];
 for(const[bit,row]of g.rows.entries()){const by=y+1+4*bit,ry=g.t.y+1+8*row;part=g.name+'_sample_clamp_'+row;wire(P(x-8,by,z));rep(P(x-7,by,z),'east');wire(P(x-6,by,z));rep(P(x-5,by,z),'east');dev(P(x-4,by,z),'comparator',{facing:'west',mode:'subtract'});rep(P(x-3,by,z),'east');wire(P(x-2,by,z));rep(P(x-1,by,z),'east');for(let q=x-8;q<x;q++)edge(P(q,by,z),P(q+1,by,z));wire(P(cx,by,cz+1));wire(P(cx,by,cz+2));rep(P(cx,by,cz+3),'south');for(let q=cz;q<z;q++)edge(P(cx,by,q),P(cx,by,q+1));edge(P(cx,by-1,cz),P(cx,by,cz+1));if(bit<g.rows.length-1)edge(P(cx,by,cz+1),P(cx,by+1,cz));outputs.push({solid:P(cx,by,cz),torch:P(cx,by-1,cz),wire:P(cx,by,cz+1)});
 const raw=move(P(22,1+8*row,-2),g.t),hold=move(P(20,1+8*row,-2),g.t),inverse=move(P(22,1+8*row,2),g.t);assert.equal(at(hold)?.block.id,W);assert.equal(at(inverse)?.block.id,W);
 // The old positive source escapes through its existing south isolator.
 // The removed wall inverter is rebuilt beside the held sample, so neither
 // old matrix branch can observe the unheld condition.
 const invIn=P(x+9,by,z+6),invDriver=P(x+9,by,z+7),invSolid=P(x+9,by,z+8),invTorch=P(x+9,by,z+9),invOut=P(x+9,by,z+10);
 wire(invIn);rep(invDriver,'south');solid(invSolid);solid(P(invSolid.x,invSolid.y-1,invSolid.z));put(invTorch,'redstone_wall_torch',{facing:'south'});wire(invOut);edge(invIn,invDriver);edge(invDriver,invSolid);edge(invDriver,invTorch);edge(invTorch,invOut);
 const holdArrival=['south','north'].find(dir=>[1,2].every(n=>{const p=step(hold,dir,-n);return !at(p)&&(!at(P(p.x,p.y-1,p.z))||at(P(p.x,p.y-1,p.z)).block.id==='minecraft:light_gray_concrete');}));assert(holdArrival,'No hold approach '+g.name+' '+row);connect(g.name+'_row'+row+'_capture',raw,'south',P(x-8,by,z),'east');connect(g.name+'_row'+row+'_held_hold',pt(bank,'state',bit),'east',hold,holdArrival);connect(g.name+'_row'+row+'_held_inverse_driver',pt(bank,'state',bit),'north',invIn,'south');connect(g.name+'_row'+row+'_held_inverse',invOut,'east',inverse,'east');bindings.push({group:g.name,row,raw_final_masked_pad:raw,held:pt(bank,'state',bit),hold_receiver:hold,inverse_receiver:inverse,inverse_input:invIn,inverse_driver:invDriver,inverse_solid:invSolid,inverse_torch:invTorch,inverse_output:invOut});

 }
 clear_columns.push({outputs});connect(g.name+'_sample_B',P(103,g.bank.y,-110),'south',pt(bank,'state_open'),'east');connect(g.name+'_sample_initialize',P(113,g.bank.y-3,-110),'south',P(cx,y-3,cz-3),'south');
 }
 const doneMatrix=insert('done_qualification',makeMatrix(doneDefinition()),P(80,40,-180)),done=insert('held_external_done',makeStateBank({width:1,pair:false}),P(180,40,-160));
 const dp=n=>pt(doneMatrix,n);
 for(const[n,s,dir]of[['terminal',P(14,57,4),'north'],['commit_idle',P(364,201,-396),'west'],['owner_idle',P(603,192,-396),'south'],['rf_quiet',base.ports.reset_barrier.rf_quiet.bits[0].position,'south'],['lsu_quiet',base.ports.reset_barrier.lsu_quiet.bits[0].position,'south'],['all_status_low',P(2129,308,122),'south'],['fault',base.ports.architectural_fault.bits[0].position,'south'],['initialize',P(113,-3,-110),'east'],['held_done',pt(done,'state'),'east']]){const chosen=[dir,...Object.keys(V).filter(v=>v!==dir)].find(dir=>[1,2].every(k=>{const p=step(s,dir,k);return !at(p)&&(!at(P(p.x,p.y-1,p.z))||at(P(p.x,p.y-1,p.z)).block.id==='minecraft:light_gray_concrete');}));assert(chosen,'No DONE source tap '+n);connect('done_'+n,s,chosen,dp(n),'south');}
 connect('qualified_done_to_store',dp('done_D'),'south',pt(done,'next_data'),'east');connect('actual_A_to_done_store',P(-73,5,8),'south',pt(done,'state_open'),'east');
 // Cap the retained negative-mask wire: the nearby raw capture climb must not
 // create a descending dust edge into the held matrix output.
 part='core_row6_inverse_cap';solid(P(22,50,2));
 const tails={};
 const cacheUrl=new URL('routes.json',import.meta.url),cache=existsSync(cacheUrl)?read('routes.json'):{},reserved=[];
 for(const path of Object.values(tails))reserved.push(...path);
 for(const[n,s,sd,d,ad]of pending)reserved.push(...Array.from({length:12},(_,i)=>step(s,sd,i+2)),...Array.from({length:12},(_,i)=>step(d,ad,-i-2)));
 function draw(name,s,sd,d,ad,stubs=false){part=name;assert.equal(at(s)?.block.id,W,'Source '+name+' '+K(s));assert.equal(at(d)?.block.id,W,'Destination '+name);const tap=step(s,sd),start=step(s,sd,2),arrival=step(d,ad,-1),end=step(d,ad,-2);
  if(stubs){if(!at(tap))rep(tap,sd);else assert.deepEqual(at(tap).block,{id:'minecraft:repeater',properties:{facing:F[sd],delay:'1'}},'Tap '+name+' '+K(tap));wire(start);rep(arrival,ad);wire(end);edge(s,tap);edge(tap,start);edge(end,arrival);edge(arrival,d);return;}
  let path=cache[name]?.path;if(!path){assert(plan,'Missing route '+name);const ignore=[tap,start,arrival,end,...[tap,start,arrival,end].map(p=>P(p.x,p.y-1,p.z)),...Array.from({length:12},(_,i)=>step(s,sd,i+2)),...Array.from({length:12},(_,i)=>step(d,ad,-i-2))],forbidden=[tap,arrival].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![s,start,end,d].some(q=>K(p)===K(q)));const tail=tails[name]??[end],approach=tail[0];ignore.push(...tail,...tail.map(p=>P(p.x,p.y-1,p.z)));forbidden.push(...[-2,-1,1,2].map(y=>P(approach.x,approach.y+y,approach.z)));for(const p of tail.slice(1)){forbidden.push(...[-2,-1,0,1,2].map(y=>P(p.x,p.y+y,p.z)),...Object.values(V).flatMap(([x,z])=>[-1,0,1].map(y=>P(p.x+x,p.y+y,p.z+z))));}let found;try{found=searchPath(map,start,approach,{ignore,reserved,forbidden});}catch(error){console.error(JSON.stringify([...map.values()].filter(v=>Math.abs(v.position.x-approach.x)<=2&&Math.abs(v.position.y-approach.y)<=2&&Math.abs(v.position.z-approach.z)<=3)));throw error;}path=[...found.path,...tail.slice(1)];cache[name]={source:s,destination:d,path,expanded:found.expanded};writeFileSync(cacheUrl,JSON.stringify(cache)+'\n');console.error(name+': '+path.length);}
  assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i))rep(p,Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z));else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source:s,tap,destination:d,arrival});
 }
 for(const v of Object.values(cache))reserved.push(...v.path);
 for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const ports={...base.ports,held_advance_samples:samples.map(v=>({group:v.group,state:v.ports.state})),core_done:{...done.ports.state,meaning:'Core-phase-held terminal completion after local owner/commit retirement; sticky until quiescent initialize. Raw binary onehot is not the external DONE.'}};
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of ['x','y','z']){box.from[a]=blocks.reduce((v,b)=>Math.min(v,b.position[a]),Infinity);box.to[a]=blocks.reduce((v,b)=>Math.max(v,b.position[a]),-Infinity);}
 return{status:'connected_final_advance_sampling_and_held_DONE_candidate',blocks,parents,ports,edges,routes,connections,removed,bindings,groups,clear_columns,positive_columns,box,metrics:{blocks:blocks.length,parent_blocks:base.blocks.length,retained_bits:1093,connections:connections.length,advance_sample_bits:16,held_done_bits:1,removed_cells:removed.length},native_acceptance:false,complete_core_reset:false,missing:['Raw asynchronous levels are sampled on B before A; actual far closure and logic settling remain quantitative timing obligations.','Core DONE is a core-phase held boundary, not a remote sample of a raw binary decode. Full native timing is unproved.','Architectural zero/reset release/final ACK and global memory interconnects remain to be completed.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeCoreGuards({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
