import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeChannelBackend}from'../../../../hardware/memory-layout-channel-backend.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url))),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),d=makeChannelBackend(),saved=read('design.json'),parent=read('../channel-payload-v1/design.json'),local=read('../channel-backend-control-v1/design.json');assert.equal(hash(d),hash(saved));const K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},m=new Map(d.blocks.map(v=>[K(v.position),v.block]));
function check(mm){for(const p of parent.blocks)assert.deepEqual(mm.get(K(p.position)),p.block);for(const c of d.controllers)for(const p of local.blocks){const q=P(p.position.x+c.origin.x,p.position.y+c.origin.y,p.position.z+c.origin.z);assert.deepEqual(mm.get(K(q)),p.block);}
 for(const c of d.bindings){const r=mm.get(K(c.normalizer));assert.equal(r?.id,'minecraft:repeater');const v=D[r.properties.facing];assert.deepEqual(P(c.normalizer.x+v.x,c.normalizer.y,c.normalizer.z+v.z),c.destination);assert.equal(mm.get(K(c.destination))?.id,'minecraft:redstone_wire');const ch=c.channel,X=128*ch,Y=80*ch;if(c.name==='active')assert.deepEqual(c.source,P(X+50,Y+1,172));if(c.name==='retire')assert.deepEqual(c.destination,P(X+44,Y+1,172));if(c.name==='backend_busy'){assert(c.or_with_existing_active);assert.deepEqual(c.destination,P(X+48,Y+1,16));assert.deepEqual(mm.get(K(P(X+48,Y+1,15))),{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});}if(c.name==='reset_blocked')assert.deepEqual(c.source,P(-20,-31,234));}
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],b=mm.get(K(p));assert(b,'cut '+r.name);if(b.id==='minecraft:repeater'){const v=D[b.properties.facing];if(i)assert.deepEqual(r.path[i-1],P(p.x-v.x,p.y,p.z-v.z));if(i+1<r.path.length)assert.deepEqual(r.path[i+1],P(p.x+v.x,p.y,p.z+v.z));}else assert.equal(b.id,'minecraft:redstone_wire');}
}
check(m);assert.equal(d.bindings.length,16);assert.equal(d.controllers.length,4);let n=0;for(const b of d.bindings){const mm=new Map(m);mm.set(K(b.normalizer),{id:'minecraft:repeater',properties:{facing:m.get(K(b.normalizer)).properties.facing==='north'?'south':'north',delay:'1'}});assert.throws(()=>check(mm));n++;}for(const key of[K(parent.blocks[0].position),K(d.routes[0].path[5])]){const mm=new Map(m);mm.delete(key);assert.throws(()=>check(mm));n++;}
let busyCases=0;for(const active of[0,1])for(const captured of[0,1])for(const retiring of[0,1])for(const tail of[0,1])for(const bankReady of[0,1])for(const readyTail of[0,1]){const backend=captured||retiring||tail||bankReady||readyTail,actual=Number(active||backend);assert.equal(actual,Number(!!(active+captured+retiring+tail+bankReady+readyTail)));busyCases++;}
const occupied=new Set(d.blocks.map(v=>`${Math.floor(v.position.x/16)},${Math.floor(v.position.z/16)}`));const out={status:'offline_connected_channel_backend_geometry_pass',...d.metrics,exact_regeneration:true,occupied_chunk_columns:occupied.size,corruptions_rejected:n,settled_busy_or_cases:busyCases,parent_maps_unchanged:true,remaining:d.missing,native_acceptance:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
