import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeProgramCapture} from '../../../../hardware/memory-layout-program-capture.mjs';
import {makeFoldedProgramROM} from '../../../../hardware/memory-layout-program-folded.mjs';
import {key} from '../../../../hardware/memory-layout-subarray.mjs';
import {circuitSchema} from '../../../../tools/minecraft-redstone/scripts/circuit-service.mjs';
const P=(x,y,z)=>({x,y,z}),S='minecraft:light_gray_concrete',solid=b=>[S,'minecraft:redstone_block'].includes(b?.id),V={east:[-1,0],west:[1,0],north:[0,1],south:[0,-1]},dirs=Object.values(V);
const d=makeProgramCapture(),parent=makeFoldedProgramROM();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));
const m=new Map(d.blocks.map(v=>[key(v.position),v.block])),added=new Set(d.added_blocks.map(v=>key(v.position))),get=(x,y,z)=>m.get(key(P(x,y,z)));assert.equal(m.size,d.blocks.length);
for(const v of parent.blocks)assert.deepEqual(m.get(key(v.position)),v.block,'Changed ROM '+key(v.position));
const rep=(x,y,z,facing)=>assert.deepEqual(get(x,y,z),{id:'minecraft:repeater',properties:{facing,delay:'1'}}),wire=(x,y,z)=>assert.equal(get(x,y,z)?.id,'minecraft:redstone_wire');
const pair=(a,b)=>[key(a),key(b)].sort().join('|'),allowed=new Set(),edge=(a,b)=>allowed.add(pair(a,b));
edge(P(47,-37,-85),P(48,-37,-85));edge(P(48,-37,-84),P(48,-37,-85));
for(const c of d.stores){edge(c.driver,c.storage);edge(c.lock,c.storage);const block=m.get(key(c.storage)),driver=m.get(key(c.driver)),lock=m.get(key(c.lock));assert.equal(block.id,'minecraft:repeater');assert.equal(driver.id,'minecraft:repeater');assert.equal(lock.id,'minecraft:repeater');assert.equal(block.properties.facing,driver.properties.facing);const [dx,dz]=V[block.properties.facing],[lx,lz]=V[lock.properties.facing];assert.deepEqual(P(c.driver.x+dx,c.driver.y,c.driver.z+dz),c.storage);assert.deepEqual(P(c.lock.x+lx,c.lock.y,c.lock.z+lz),c.storage);assert.equal(dx*lx+dz*lz,0);}
const depth=[-4,-8,-12,-16,-25,-21,-33,-29];
for(let b=0;b<8;b++){const y=depth[b];for(const x of[64,72])edge(P(x,y,-76),P(x,y,-75));edge(P(63,y,-75),P(64,y,-75));edge(P(73,y,-75),P(72,y,-75));for(const x of[64,72]){assert.deepEqual(get(x,y,-75),{id:'minecraft:comparator',properties:{facing:'north',mode:'subtract'}});rep(x,y,-77,'north');rep(x,y,-74,'north');assert.deepEqual(d.ports.consumer_read_address.positions[(x===72?8:0)+b],P(x,y,-78));}rep(63,y,-75,'west');rep(73,y,-75,'east');rep(68,y,-55,'north');assert.deepEqual(d.muxes[b].destination,parent.ports.address.positions[b]);
 const low=b<4;assert.equal(get(60,low?y-1:y,-75)?.id,S);rep(low?61:63,low?y-1:y,-75,'west');assert.equal(get(80,low?y-1:y,-75)?.id,S);assert.equal(get(low?75:77,y,-75)?.id,'minecraft:redstone_wall_torch');rep(75,low?y-1:y,-69,'east');assert.equal(get(76,low?y-1:y,-69)?.id,S);
}
let supports=0,contacts=0,sideLocks=0,foreignSteps=0,foreignStrongRear=0;
for(const v of d.added_blocks){const a=v.position,b=v.block;if(solid(b))continue;let q=P(a.x,a.y-1,a.z);if(b.id==='minecraft:redstone_wall_torch'){const[dx,dz]=V[b.properties.facing];q=P(a.x+dx,a.y,a.z+dz);}assert(solid(m.get(key(q))),'Missing support '+key(a));supports++;
 for(const[dx,dz]of dirs){const q=P(a.x+dx,a.y,a.z+dz),bb=m.get(key(q));if(bb&&!solid(bb)&&d.nets[key(a)]!==d.nets[key(q)]){assert(allowed.has(pair(a,q)),'Foreign face '+key(a)+'>'+key(q));contacts++;}if(b.id==='minecraft:redstone_wire')for(const dy of[-1,1]){const r=P(q.x,a.y+dy,q.z),rb=m.get(key(r));if(rb?.id!=='minecraft:redstone_wire'||d.nets[key(a)]===d.nets[key(r)])continue;if(dy>0&&m.has(key(P(a.x,a.y+1,a.z))))continue;if(dy<0&&m.has(key(P(r.x,a.y,r.z))))continue;foreignSteps++;assert.fail('Foreign slope '+key(a));}}
 if(b.id==='minecraft:repeater'){const[dx,dz]=V[b.properties.facing];for(const s of[-1,1]){const q=P(a.x+s*dz,a.y,a.z+s*dx),bb=m.get(key(q));if(!['minecraft:repeater','minecraft:comparator'].includes(bb?.id))continue;const[xx,zz]=V[bb.properties.facing];if(q.x+xx===a.x&&q.z+zz===a.z){assert(d.stores.some(c=>key(c.storage)===key(a)&&key(c.lock)===key(q)));sideLocks++;}}}
}
for(const v of d.blocks){const a=v.position,b=v.block;if(!['minecraft:repeater','minecraft:comparator'].includes(b.id))continue;const[dx,dz]=V[b.properties.facing],r=P(a.x-dx,a.y,a.z-dz);if(!solid(m.get(key(r))))continue;const ss=[],above=P(r.x,r.y+1,r.z);if(m.get(key(above))?.id==='minecraft:redstone_wire')ss.push(above);for(const[xx,zz]of dirs){const q=P(r.x-xx,r.y,r.z-zz),bb=m.get(key(q));if(['minecraft:repeater','minecraft:comparator'].includes(bb?.id)&&JSON.stringify(V[bb.properties.facing])===JSON.stringify([xx,zz]))ss.push(q);}for(const q of ss){if(!added.has(key(q))&&!added.has(key(a))||d.nets[key(q)]===d.nets[key(a)])continue;foreignStrongRear++;assert.fail('Foreign strong rear '+key(q)+'>'+key(a));}}
assert.equal(sideLocks,25);assert.equal(contacts,168);assert.equal(allowed.size,84);assert.equal(foreignSteps,0);assert.equal(foreignStrongRear,0);
for(let b=0;b<16;b++){const z=-60-2*b,y=b%2?283:279;rep(71,279,z,'west');for(let yy=279;yy<=y;yy++)assert.equal(get(72,yy,z)?.id,(yy-279)%2?'minecraft:redstone_torch':S);rep(74,y,z,'west');rep(75,y,z,'west');rep(75,y,z+1,'south');assert.deepEqual(d.ports.response.positions[b],P(78,y,z));assert.deepEqual(parent.ports.read_data.positions[b],P(70,279,z));}
for(const [x,z]of[[60,-75],[80,-75],[76,-69]])for(let y=-37;y<=-5;y++)assert.equal(get(x,y,z)?.id,(y+37)%2?'minecraft:redstone_torch':S);
for(const y of[279,283])for(let z=-49;z>=-88;z--){const b=get(82,y,z);assert.equal(b.id,(-z-51)%12===0?'minecraft:repeater':'minecraft:redstone_wire');if(b.id==='minecraft:repeater')assert.equal(b.properties.facing,'south');}
for(const c of d.circuits)circuitSchema.parse(c);assert.deepEqual(d.circuits.map(c=>c.signals.length),[29,49]);
let addressOracleCases=0;for(const owner of[0,1])for(let a0=0;a0<256;a0++)for(let a1=0;a1<256;a1++){let out=0;for(let b=0;b<8;b++){const left=Math.max(15*((a0>>b)&1)-15*owner,0),right=Math.max(15*((a1>>b)&1)-15*(1-owner),0);out|=Number(!!(left||right))<<b;}assert.equal(out,owner?a1:a0);addressOracleCases++;}
for(const v0 of[0,1])for(const v1 of[0,1])assert.equal(Number(Math.max(15*v1-15*v0,0)>0),v1&&!v0?1:0);
const report={status:'offline_payload_capture_geometry_checked_no_handshake_or_native_acceptance',...d.metrics,parent_positions_unchanged:parent.blocks.length,added_support_checks:supports,intended_cross_net_directed_contacts:contacts,actual_perpendicular_locks:sideLocks,foreign_step_dust_candidates:foreignSteps,foreign_strong_rear_paths:foreignStrongRear,software_address_selector_cases:addressOracleCases,software_priority_cases:4,observed_scope_per_view:d.circuits.map(c=>({id:c.id,signals:c.signals.length})),native_calls:0,missing:d.missing,limits:['Static supports/endpoints/polarity/contacts only; no timing or analog simulation.','Three OPEN pads are unresolved physical-controller inputs. No host sequencing may stand in for the running memory controller.','Priority and address oracle are test calculations, not physical arbitration acceptance.']};
if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
