import assert from'node:assert/strict';import{pathToFileURL}from'node:url';import{definition,eligibilityDefinition,exitsDefinition}from'./logic.mjs';const d=definition(),run=v=>Object.fromEntries(d.outputs.map(n=>[n,d.products.some(p=>p.out===n&&Object.entries(p.literals).every(([k,x])=>!!v[k]===x))]));
export function checkLogic(){let truth=0;for(let n=0;n<2**d.inputs.length;n++){const v=Object.fromEntries(d.inputs.map((k,i)=>[k,!!(n>>i&1)])),r=run(v),live=!v.initialize&&!v.fault;assert.equal(r.ack_D,live&&!v.cleanup&&(v.ack||v.eligible&&v.request&&!v.withdraw&&!v.release));assert.equal(r.withdraw_D,live&&!v.cleanup&&(v.withdraw||v.ack&&!v.request));assert.equal(r.release_D,live&&!v.cleanup&&(v.release||v.withdraw&&v.exits_quiet&&!v.start));assert.equal(r.cleanup_D,live&&(v.release&&v.stages_clear||v.cleanup&&(v.ack||v.withdraw||v.release)));assert.equal(r.external_ack_D,live&&(v.ack||v.withdraw||v.release||v.cleanup));truth++;}
 let traces=0;for(let exitDelay=0;exitDelay<5;exitDelay++)for(let clearDelay=0;clearDelay<5;clearDelay++){let q={ack:false,withdraw:false,release:false,cleanup:false},n={},out=false,ackSeen=false,request=true,withdrawAt=-1,releaseAt=-1,clearedAt=-1,outFell=false;for(let cycle=0;cycle<40;cycle++){if(ackSeen&&cycle>3)request=false;const exits=withdrawAt>=0&&cycle>=withdrawAt+exitDelay,stages=releaseAt>=0&&cycle>=releaseAt+clearDelay,oldOut=out,r=run({...q,eligible:cycle>=1,request,start:false,exits_quiet:exits,stages_clear:stages,initialize:false,fault:false});
  // A captures external ACK and all NEXT; B commits the three scalar pairs.
  out=r.external_ack_D;q.ack=r.ack_D;n={withdraw:r.withdraw_D,release:r.release_D,cleanup:r.cleanup_D};Object.assign(q,n);if(out)ackSeen=true;if(q.withdraw&&withdrawAt<0)withdrawAt=cycle;if(q.release&&releaseAt<0)releaseAt=cycle;if(stages&&clearedAt<0)clearedAt=cycle;if(oldOut&&!out){assert(clearedAt>=0&&Object.values(q).every(v=>!v));outFell=true;}if(q.release)assert(exits);}
 assert(ackSeen&&outFell&&!out&&Object.values(q).every(v=>!v));traces++;}
 // Withheld exits or uncleared stages must hold external ACK indefinitely.
 for(const block of['exits','clear']){let q={ack:true,withdraw:false,release:false,cleanup:false},out=true;for(let cycle=0;cycle<30;cycle++){const r=run({...q,request:false,eligible:true,start:false,exits_quiet:block!=='exits',stages_clear:block!=='clear'});out=r.external_ack_D;q={ack:r.ack_D,withdraw:r.withdraw_D,release:r.release_D,cleanup:r.cleanup_D};assert(out);}traces++;}
 let cold=0;for(let bits=0;bits<256;bits++){let q={ack:!!(bits&1),withdraw:!!(bits&2),release:!!(bits&4),cleanup:!!(bits&8)},n={withdraw:!!(bits&16),release:!!(bits&32),cleanup:!!(bits&64)},out=!!(bits&128);for(const initial of ['A','B']){let x={...q},next={...n},external=out;for(const phase of [initial,...['A','B','A','B']]){if(phase==='A'){const r=run({...x,initialize:true,fault:false});x.ack=r.ack_D;external=r.external_ack_D;next={withdraw:r.withdraw_D,release:r.release_D,cleanup:r.cleanup_D};}else Object.assign(x,next);}assert(!external&&Object.values(x).every(v=>!v));cold++;}}
 let guardCases=0;for(const def of [eligibilityDefinition(),exitsDefinition()])for(let bits=0;bits<2**def.inputs.length;bits++){const v=Object.fromEntries(def.inputs.map((n,i)=>[n,!!(bits&(1<<i))])),got=def.products.every(p=>Object.entries(p.literals).every(([n,w])=>v[n]===w));const expected=def.outputs[0]==='eligible'?v.arch_zero&&v.epochs_zero&&v.intents_zero&&v.locks_closed&&v.rf_ack&&v.scratch_complete&&v.epoch_settled&&!v.epoch_enable&&v.arch_stop&&!v.initialize&&!v.fault:!v.rf_ack&&!v.rf_event_ack&&v.alu_idle&&v.alu_status_low&&!v.lsu_ack&&v.program_quiet&&!v.program_ready&&v.lsu_quiet&&!v.program_valid&&!v.decode_valid&&!v.request_tail;assert.equal(got,expected);guardCases++;}
 for(const fault of[false,true]){let q={ack:true,withdraw:true,release:false,cleanup:false};for(let i=0;i<10;i++){const r=run({...q,request:false,start:true,exits_quiet:true,stages_clear:false,fault});assert(!r.release_D);if(fault)assert(!r.external_ack_D&&!r.ack_D&&!r.withdraw_D&&!r.cleanup_D);}}
 return{truth_cases:truth,ordered_reset_release_traces:traces,arbitrary_cold_phase_cases:cold,completion_exit_guard_cases:guardCases,native_acceptance:false,limits:['Scalar stages require their actual source/return setup and full A-close-B-close intervals. This logic model does not establish physical timing.','External ACK is held from overlapping retained stages, and falls only after cleanup. Fault-to-ACK visibility still requires the documented far-fault ordering.']};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)console.log(JSON.stringify(checkLogic()));
