import assert from 'node:assert/strict';
import {readFileSync,writeFileSync}from'node:fs';
import {makeFinalReset}from'./prepare.mjs';
import {checkLogic}from'./check-logic.mjs';
import {screen}from'./check-interactions.mjs';
import {boundary}from'./boundary.mjs';
import {checkObservationTaps}from'./check-observation-taps.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z}),W='minecraft:redstone_wire',S='minecraft:light_gray_concrete';
const d=makeFinalReset(),base=read('../control-reset-epoch-v1/design.json'),m=new Map(d.blocks.map(v=>[K(v.position),v])),old=new Map(base.blocks.map(v=>[K(v.position),v]));assert.deepEqual(d,read('design.json'));assert.deepEqual(boundary(d),read('machine-boundary.json'));assert.equal(d.removed.length,0);assert.equal(d.substitutions.length,5);assert.equal(d.metrics.retained_bits,1117);
for(const v of base.blocks){const sub=d.substitutions.find(s=>K(s.position)===K(v.position));if(sub){assert.deepEqual(sub.before,v.block);assert.deepEqual(m.get(K(v.position)).block,sub.after);if(sub.name.endsWith('_rear_normalizer')){assert.equal(sub.before.id,W);assert.equal(sub.after.id,'minecraft:repeater');}else{assert.equal(sub.before.id,'minecraft:repeater');assert.equal(sub.after.id,'minecraft:comparator');assert.equal(sub.after.properties.mode,'subtract');assert.equal(sub.after.properties.facing,sub.before.properties.facing);}}else assert.deepEqual(m.get(K(v.position))?.block,v.block,'Parent mutation '+K(v.position));}
const eligible=new Set(base.blocks.filter(v=>v.block.id===W&&!d.substitutions.some(s=>K(s.position)===K(v.position))).map(v=>K(v.position)));let oldEdges=0;function neighbors(p,map){const a=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const dy of[-1,0,1]){const q=P(p.x+x,p.y+dy,p.z+z);if(!eligible.has(K(q)))continue;if(dy===1&&map.has(K(P(p.x,p.y+1,p.z))))continue;if(dy===-1&&map.has(K(P(q.x,q.y+1,q.z))))continue;a.push(K(q));}return a.sort();}for(const k of eligible){const before=neighbors(old.get(k).position,old);assert.deepEqual(neighbors(old.get(k).position,m),before,'Parent wire shape '+k);oldEdges+=before.length;}
let locks=0;for(const[name,v]of Object.entries(d.parents).filter(([n])=>['final_withdraw','final_release','final_cleanup','internal_reset_complete','held_external_reset_ACK'].includes(n))){const t=v.translation;for(const x of name.startsWith('final_')?[0,12]:[0]){assert.deepEqual(m.get(K(P(t.x+x+2,t.y+1,t.z))).block,{id:'minecraft:repeater',properties:{facing:'west',delay:'1'}});assert.deepEqual(m.get(K(P(t.x+x+2,t.y+1,t.z+1))).block,{id:'minecraft:repeater',properties:{facing:'south',delay:'1'}});assert.equal(m.get(K(P(t.x+x+2,t.y+1,t.z+2))).block.id,W);locks++;}}assert.equal(locks,8);
const travel={north:[0,1],south:[0,-1],east:[-1,0],west:[1,0]};for(const q of d.lock_inventory){assert.equal(m.get(K(q.rear))?.block.id,W,q.name);const lock=m.get(K(q.lock))?.block;assert.equal(lock?.id,'minecraft:repeater',q.name);assert.equal(lock.properties.facing,q.facing,q.name);const[x,z]=travel[q.facing];assert.deepEqual(q.rear,P(q.lock.x-x,q.lock.y,q.lock.z-z));assert.deepEqual(q.storage,P(q.lock.x+x,q.lock.y,q.lock.z+z));assert.equal(m.get(K(q.storage))?.block.id,'minecraft:repeater');}assert.equal(d.lock_inventory.length,16);
function bindings(c){for(const n of['start_request','reset_request','core_done'])assert.deepEqual(c.ports[n],base.ports[n]);for(const n of['program_address','program_data','program_ready','program_valid','normal_permit','lane_enable'])assert.deepEqual(c.ports.front[n],base.ports.front[n]);assert.deepEqual(c.ports.rf.startup_initialize_request,base.ports.rf.startup_initialize_request);assert.deepEqual(c.ports.alu_startup.logic.normal_permit,base.ports.alu_startup.logic.normal_permit);assert.deepEqual(c.ports.reset_ack.bits[0].position,P(-395,36,540));const get=n=>c.connections.find(x=>x.name===n);assert.deepEqual(get('held_external_ACK_D').destination,P(-400,36,540));assert.deepEqual(get('withdraw_RF_reset').destination,base.ports.architectural_zero.withdraw.bits[0].position);assert.deepEqual(get('rf_ack_to_completion').source,base.ports.rf.reset_ack.bits[0].position);assert.deepEqual(get('exit_program_quiet').destination,c.ports.reset_final.exits.program_quiet.bits[0].position);assert(!c.connections.some(x=>K(x.tap)==='185,41,-161'),'Reserved master DONE north tap');assert(c.terminal_columns.some(x=>K(x.target)===K(base.ports.reset_barrier.release_complete.bits[0].position)));}
bindings(d);let corruptions=0;for(const name of['rf_ack_to_completion','exit_program_quiet']){const changed={...d,connections:d.connections.map(c=>c.name===name?{...c,[name==='rf_ack_to_completion'?'source':'destination']:P(0,0,0)}:c)};assert.throws(()=>bindings(changed));corruptions++;}assert.throws(()=>bindings({...d,ports:{...d.ports,reset_ack:base.ports.core_done}}));corruptions++;
// Each withdrawn source was a literal normalized wire before its initial diode.
for(const sub of d.substitutions.filter(s=>s.after.id==='minecraft:comparator')){const[x,z]=travel[sub.after.properties.facing],source=P(sub.position.x-x,sub.position.y,sub.position.z-z);if(m.get(K(source))?.block.id==='minecraft:repeater'){assert.equal(m.get(K(source)).block.properties.facing,sub.after.properties.facing);continue;}assert.equal(old.get(K(source))?.block.id,W);const incoming=[];for(const[face,[dx,dz]]of Object.entries(travel)){const p=P(source.x-dx,source.y,source.z-dz),b=old.get(K(p))?.block;if(b?.id==='minecraft:repeater'&&b.properties.facing===face)incoming.push(p);}assert(incoming.length>0,'Withdrawal source is not normalized '+sub.name);}
for(const sub of d.substitutions.filter(s=>s.name.endsWith('_rear_normalizer'))){const p=sub.position,[dx,dz]=travel[sub.after.properties.facing],expected=P(p.x-dx,p.y,p.z-dz),sources=[];for(const[x,z]of[[1,0],[-1,0],[0,1],[0,-1]])for(const y of[-1,0,1]){const q=P(p.x+x,p.y+y,p.z+z);if(old.get(K(q))?.block.id!==W||y===1&&old.has(K(P(p.x,p.y+1,p.z)))||y===-1&&old.has(K(P(q.x,q.y+1,q.z))))continue;sources.push(K(q));}assert.deepEqual(sources.sort(),[K(expected)],'Rear normalizer would remove a parent branch');}
for(const o of d.observation_taps){const r=JSON.parse(readFileSync(o.parent_route_file))[o.parent_route_name];assert(K(r.source)===K(o.original_source)||K(r.destination)===K(o.original_source));if(['local_architectural_reset_blank','scratch_reset_to_LSU','scratch_reset_to_ALU'].includes(o.parent_route_name))assert.equal(K(o.original_source),K(r.destination),'Unmasked observation cannot use withdrawn cable');assert.deepEqual(r.path[o.index],o.source);assert(r.path.every(p=>['minecraft:redstone_wire','minecraft:repeater'].includes(old.get(K(p))?.block.id)));}
const report={status:'author_checked_connected_final_reset_candidate',...d.metrics,preserved_parent_cells:base.blocks.length-d.substitutions.length,explicit_withdrawal_substitutions:d.substitutions.length,preserved_old_wire_edges:oldEdges,new_stored_lock_directions:locks,observed_architecture_lock_rails:d.lock_inventory.length,source_bound_inherited_taps:d.observation_taps.length,boundary_corruptions:corruptions,...checkLogic(),...checkObservationTaps(d),...screen(d),native_acceptance:false,complete_core_reset:false,final_reset_ack_geometry:true};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,taps:undefined}));
