// Connected narrow control-epoch zero transfer after architectural reset. Offline only.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync}from'node:fs';
import {createHash}from'node:crypto';
import {pathToFileURL}from'node:url';
import {makeStateBank}from'../../../hardware/full-gpu-state-bank.mjs';
import {materializeInstance}from'../../../hardware/gpu-layout-assembly.mjs';
import {makeMatrix}from'../control-lsu-v2/matrix.mjs';
import {P,K,V,F,searchPath,refreshIndices}from'../control-commit-v2/route.mjs';
import {definition,allDefinition,eligibilityDefinition,exitsDefinition}from'./logic.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))),W='minecraft:redstone_wire';
export function makeFinalReset({plan=false}={}){
 assert.equal(createHash('sha256').update(readFileSync(new URL('../control-reset-epoch-v1/source-manifest.json',import.meta.url))).digest('hex'),'b247c56b203ae01f441ad53b755b93bdde7784795be41eea446b57d2337b98ca');const pm=read('../control-reset-epoch-v1/source-manifest.json');assert.equal(createHash('sha256').update(readFileSync(new URL('../control-reset-epoch-v1/design.json',import.meta.url))).digest('hex'),pm.source_sha256['artifacts/full-gpu-layout-v1/control-reset-epoch-v1/design.json']);
 const base=read('../control-reset-epoch-v1/design.json'),map=new Map(base.blocks.map(v=>[K(v.position),{...v,part:'base'}])),parents={base:{blocks:base.blocks.length,translation:P(0,0,0)}},edges=[],routes=[],connections=[],removed=[],clear_columns=[],positive_columns=[];let part='';const at=p=>map.get(K(p)),edge=(from,to)=>edges.push({from,to}),step=(p,d,n=1)=>P(p.x+V[d][0]*n,p.y,p.z+V[d][1]*n),move=(p,t)=>P(p.x+t.x,p.y+t.y,p.z+t.z);
 function put(p,id,properties){const block={id:'minecraft:'+id,...properties?{properties}:{}};if(at(p)){assert.equal(id,'light_gray_concrete','Collision '+part+' '+K(p));assert.deepEqual(at(p).block,block,part+" support "+K(p)+" existing "+at(p).part);return;}map.set(K(p),{position:p,block,part});}
 const solid=p=>put(p,'light_gray_concrete'),dev=(p,id,props)=>{solid(P(p.x,p.y-1,p.z));put(p,id,props);},wire=p=>dev(p,'redstone_wire'),rep=(p,d)=>dev(p,'repeater',{facing:F[d],delay:'1'});
 function insert(name,d,t){const r=materializeInstance(d,{id:name,translation:t});for(const v of r.blocks){assert(!at(v.position),'Component collision '+name+' '+K(v.position));map.set(K(v.position),{...v,part:name});}for(const e of d.edges??[])edge(move(e.from,t),move(e.to,t));parents[name]={blocks:d.blocks.length,translation:t};return r;}
 const pt=(d,n,b=0)=>d.ports[n].bits[b].position,pending=[],claimedTaps=new Set([K(P(185,41,-161))]),connect=(...a)=>{pending.push(a);claimedTaps.add(K(step(a[1],a[2])));};

 const substitutions=[],states={},observations=[],lock_inventory=[],terminal_columns=[],lower_taps=[],customTaps={},isolation_caps=[];
 const logic=insert('final_reset_logic',makeMatrix(definition()),P(-570,65,580));
 for(const[i,name]of ['withdraw','release','cleanup'].entries())states[name]=insert('final_'+name,makeStateBank({width:1,pair:true}),P(-550+30*i,35,540));
 states.ack=insert('internal_reset_complete',makeStateBank({width:1,pair:false}),P(-440,35,540));states.external_ack=insert('held_external_reset_ACK',makeStateBank({width:1,pair:false}),P(-400,35,540));
 const selectTap=(s,preferred)=>[preferred,...Object.keys(V).filter(d=>d!==preferred)].find(dir=>!claimedTaps.has(K(step(s,dir)))&&[1,2].every(n=>{const p=step(s,dir,n);return !at(p)&&at(P(p.x,p.y-2,p.z))?.block.id!==W&&(!at(P(p.x,p.y-1,p.z))||at(P(p.x,p.y-1,p.z)).block.id==='minecraft:light_gray_concrete');}));
 const inheritedRoutes=[];for(const file of Object.keys(pm.source_sha256).filter(p=>p.endsWith('/routes.json'))){const data=JSON.parse(readFileSync(file));for(const[n,r]of Object.entries(data))if(r?.source&&Array.isArray(r.path))inheritedRoutes.push({file,name:n,...r});}
 const freeEscape=(s,dir)=>{const start=step(s,dir,2);return Object.entries(V).filter(([n])=>V[n][0]!==-V[dir][0]||V[n][1]!==-V[dir][1]).some(([,[dx,dz]])=>[-1,0,1].some(dy=>{const p=P(start.x+dx,start.y+dy,start.z+dz);if(at(p)||at(P(p.x,p.y-1,p.z)))return false;for(const[x,z]of Object.values(V))for(const y of[-1,0,1])if(at(P(p.x+x,p.y+y,p.z+z)))return false;for(const y of[-2,1,2])if(at(P(p.x,p.y+y,p.z)))return false;return true;}));};
 const observation_taps=[];
 const auto=(n,s,sd,d,ad)=>{if(customTaps[n]){connect(n,s,'west',d,ad);return;}const pick=p=>n.startsWith('released_')?[sd,...Object.keys(V).filter(v=>v!==sd)].find(dir=>selectTap(p,dir)===dir&&freeEscape(p,dir)):selectTap(p,sd);let chosen=pick(s),actual=s;if(!chosen){const candidates=inheritedRoutes.filter(r=>(K(r.source)===K(s)||K(r.destination)===K(s))&&(!['local_architectural_reset_blank','scratch_reset_to_LSU','scratch_reset_to_ALU'].includes(r.name)||K(r.destination)===K(s)));outer:for(const r of candidates){if(!r.path.every(p=>['minecraft:redstone_wire','minecraft:repeater'].includes(at(p)?.block.id)))continue;for(let i=r.path.length-1-(n==='released_local_reset'?30:0);i>=0;i--){const p=r.path[i];if(at(p)?.block.id!==W)continue;chosen=pick(p);if(chosen){actual=p;observation_taps.push({name:n,original_source:s,source:p,parent_route_file:r.file,parent_route_name:r.name,index:i});break outer;}}}}assert(chosen,'No source escape '+n+' '+K(s));connect(n,actual,chosen,d,ad);};
 const cachedParentRoutes=read('../control-reset-epoch-v1/routes.json');
 function pathSource(name,dir='east'){for(const p of [...cachedParentRoutes[name].path].reverse()){if(at(p)?.block.id!==W)continue;const d=selectTap(p,dir);if(d)return[p,d];}throw Error('No source tap '+name);}
 for(const name of ['withdraw','release','cleanup','ack']){connect(name+'_D',pt(logic,name+'_D'),'south',pt(states[name],'next_data'),'east');connect(name+'_feedback',pt(states[name],'state'),'east',pt(logic,name),'south');}
 connect('held_external_ACK_D',pt(logic,'external_ack_D'),'south',pt(states.external_ack,'next_data'),'east');
 const phaseA=insert('final_A_fanout',makeMatrix({inputs:['phase'],outputs:['a0','a1','a2','a3','a4'],products:[0,1,2,3,4].map(i=>({out:'a'+i,literals:{phase:true}}))}),P(-580,175,540));
 const phaseB=insert('final_B_fanout',makeMatrix({inputs:['phase'],outputs:['b0','b1','b2'],products:[0,1,2].map(i=>({out:'b'+i,literals:{phase:true}}))}),P(-580,205,540));
 for(const[n,d]of[['A',phaseA],['B',phaseB]]){const[s,sd]=pathSource('actual_'+n+'_to_epoch');connect('actual_'+n+'_to_final',s,sd,pt(d,'phase'),'south');}
 for(const[i,n]of ['withdraw','release','cleanup','ack','external_ack'].entries())connect(n+'_A',pt(phaseA,'a'+i),'south',pt(states[n],['ack','external_ack'].includes(n)?'state_open':'next_open'),'east');
 for(const[i,n]of ['withdraw','release','cleanup'].entries())connect(n+'_B',pt(phaseB,'b'+i),'south',pt(states[n],'current_open'),'east');
 const architecture=[];for(const b of base.ports.front.pc.bits)architecture.push({name:'pc'+b.bit,source:b.position});for(let l=0;l<4;l++)for(let b=0;b<3;b++)architecture.push({name:'nzp'+l+'_'+b,source:P(175+32*l,285,-12+16*b)});
 // Capped lower normalizers preserve the crowded final NZP output wire.
 for(const[lane,bit]of[[0,1],[0,2],[1,2],[2,2],[3,2],[3,0],[3,1]]){const name='arch_zero_nzp'+lane+'_'+bit,z=-12+16*bit,source=P(175+32*lane,285,z),cap=P(source.x,286,z),support=P(source.x,284,z),tap=P(source.x-1,284,z),start=P(source.x-2,284,z);part=name+'_lower_tap';assert.equal(at(support)?.block.id,'minecraft:light_gray_concrete');solid(cap);rep(tap,'west');wire(start);edge(source,tap);edge(support,tap);edge(tap,start);customTaps[name]={tap,start};claimedTaps.add(K(tap));lower_taps.push({name,source,support,cap,tap,start,direction:'west'});}
 const epochs=[['core',P(14,1,6)],['commit',P(364,201,-396)],['owner',P(603,192,-396)]].map(([name,source])=>({name,source}));
 const intents=[];for(const[name,p]of [['front',base.ports.front.intent_state],['update',base.ports.update_intent.state],['operand',base.ports.operand_intent.state],['rf_request',base.ports.rf_intent.state],['other',base.ports.other_claim],['done',base.ports.core_done]])for(const b of p.bits)intents.push({name:name+b.bit,source:b.position});
 // Exact farthest branch per independently driven architecture/control rail.
 for(const[n,t]of [['core',P(0,0,0)],['commit',P(350,200,-400)],['owner',P(600,200,-400)]])for(const [bank,x]of[['next',-20],['current',-8]])lock_inventory.push({name:n+'_'+bank,rear:move(P(x,9,2),t),lock:move(P(x,9,1),t),storage:move(P(x,9,0),t),facing:'south',rail_bits:3});
 lock_inventory.push({name:'pc_next',rear:P(30,252,50),lock:P(30,252,51),storage:P(30,252,52),facing:'north',rail_bits:8},{name:'pc_current',rear:P(38,256,56),lock:P(38,256,55),storage:P(38,256,54),facing:'south',rail_bits:8});
 for(let l=0;l<4;l++)lock_inventory.push({name:'flags'+l,rear:P(182+32*l,285,26),lock:P(182+32*l,285,25),storage:P(182+32*l,285,24),facing:'south',rail_bits:3});
 for(const[n,t,width]of[['front_intents',P(-40,0,90),2],['update_intent',P(300,48,-60),1],['operand_intent',P(300,28,-52),1],['rf_intent',P(640,249,-320),1]])lock_inventory.push({name:n,rear:P(t.x+2,t.y+1+4*(width-1),t.z+2),lock:P(t.x+2,t.y+1+4*(width-1),t.z+1),storage:P(t.x+2,t.y+1+4*(width-1),t.z),facing:'south',rail_bits:width});

 for(let lane=1;lane<4;lane++){const name='locks_closed_flags'+lane,source=P(182+32*lane,285,26),cap=P(source.x,286,26),support=P(source.x,284,26),tap=P(source.x-1,284,26),start=P(source.x-2,284,26);part=name+'_lower_tap';assert.equal(at(support)?.block.id,'minecraft:light_gray_concrete');solid(cap);rep(tap,'west');wire(start);edge(source,tap);edge(support,tap);edge(tap,start);customTaps[name]={tap,start};claimedTaps.add(K(tap));lower_taps.push({name,source,support,cap,tap,start,direction:'west'});}
 const guardDefs=[['arch_zero',architecture,false,P(-220,272,480)],['epochs_zero',epochs,true,P(20,190,480)],['intents_zero',intents,false,P(-100,215,540)],['locks_closed',lock_inventory.map(v=>({name:v.name,source:v.rear})),true,P(30,270,540)]];
 const guards={};for(const[name,points,high,t]of guardDefs){guards[name]=insert(name,makeMatrix(allDefinition(points.map(v=>v.name),high,name)),t);for(const q of points){assert.equal(at(q.source)?.block.id,W,'Return '+q.name);
 auto(name+'_'+q.name,q.source,name==='locks_closed'?'west':'north',pt(guards[name],q.name),'south');observations.push({...q,high,group:name});}}
 const eligible=insert('physical_reset_completion',makeMatrix(eligibilityDefinition()),P(-220,238,570));for(const n of['arch_zero','epochs_zero','intents_zero','locks_closed'])connect(n+'_to_completion',pt(guards[n],n),'south',pt(eligible,n),'south');
 for(const[n,s]of [['rf_ack',base.ports.rf.reset_ack.bits[0].position],['scratch_complete',base.ports.reset_scratch.scratch_complete.bits[0].position],['epoch_settled',base.ports.reset_epoch.states.settled.bits[0].position],['epoch_enable',base.ports.reset_epoch.states.enable.bits[0].position],['arch_stop',base.ports.architectural_zero.states.stop.bits[0].position]])auto(n+'_to_completion',s,'north',pt(eligible,n),'south');
 connect('actual_completion_to_ACK',pt(eligible,'eligible'),'south',pt(logic,'eligible'),'south');
 const exit=insert('actual_reset_exit_join',makeMatrix(exitsDefinition()),P(10,210,580));
 for(const[n,s]of [['rf_ack',base.ports.rf.reset_ack.bits[0].position],['rf_event_ack',base.ports.rf.event_ack.bits[0].position],['alu_idle',P(1415,-9,8)],['alu_status_low',P(2129,308,122)],['lsu_ack',base.ports.lsu_reset_ack.bits[0].position],['program_quiet',base.ports.reset_barrier.program_quiet.bits[0].position],['program_ready',base.ports.front.program_ready.bits[0].position],['lsu_quiet',base.ports.reset_barrier.lsu_quiet.bits[0].position],['program_valid',base.ports.front.program_valid.bits[0].position],['decode_valid',base.ports.front.decode_valid.bits[0].position],['request_tail',base.ports.front.request_tail.bits[0].position]])auto('exit_'+n,s,'south',pt(exit,n),'south');
 connect('actual_downstream_reset_exit',pt(exit,'exits_quiet'),'south',pt(logic,'exits_quiet'),'south');
 const clearPoints=[];for(const[n,p]of [['barrier',base.ports.reset_barrier.state],['scratch',base.ports.reset_scratch.active],...Object.entries(base.ports.architectural_zero.states).map(([n,p])=>['zero_'+n,p]),...Object.entries(base.ports.reset_epoch.states).map(([n,p])=>['epoch_'+n,p]),['rail_armed',base.ports.reset_closure.armed],['rail_qualified',base.ports.reset_closure.qualified]])for(const b of p.bits)clearPoints.push({name:n+b.bit,source:b.position});
 for(const[n,source]of[['arch_mask',P(-114,310,-90)],['epoch_mask',P(-104,64,-6)],['intent_mask',P(-44,-2,85)],['sample_mask',P(113,197,-110)],['local_reset',P(-140,1,-2)]])clearPoints.push({name:n,source});
 const clear=insert('delivered_release_and_stage_clear',makeMatrix(allDefinition(clearPoints.map(v=>v.name),false,'stages_clear')),P(190,250,540));for(const q of clearPoints){auto('released_'+q.name,q.source,'north',pt(clear,q.name),'south');observations.push({...q,high:false,group:'stages_clear'});}connect('actual_release_clear_return',pt(clear,'stages_clear'),'south',pt(logic,'stages_clear'),'south');
 for(const[n,path]of[['initialize','cold_initialize_to_epoch'],['fault','fault_to_epoch']]){const[s,sd]=pathSource(path);connect(n+'_to_final',s,sd,pt(logic,n),'south');auto(n+'_to_completion',s,'north',pt(eligible,n),'south');}
 auto('external_reset_request',base.ports.reset_request.bits[0].position,'south',pt(logic,'request'),'south');auto('actual_START_low_guard',base.ports.start_request.bits[0].position,'north',pt(logic,'start'),'south');
 // The retained release is a real physical source of the former unbound pad.
 {part='release_positive_injection';const target=base.ports.reset_barrier.release_complete.bits[0].position,bottom=P(target.x,target.y-5,target.z),input=P(target.x-2,target.y-5,target.z),driver=P(target.x-1,target.y-5,target.z),t1=P(target.x,target.y-4,target.z),mid=P(target.x,target.y-3,target.z),t2=P(target.x,target.y-2,target.z),top=P(target.x,target.y-1,target.z);assert.equal(at(top)?.block.id,'minecraft:light_gray_concrete');solid(bottom);wire(input);rep(driver,'east');put(t1,'redstone_torch');solid(mid);put(t2,'redstone_torch');edge(input,driver);edge(driver,bottom);edge(driver,t1);edge(t1,t2);edge(t2,target);terminal_columns.push({name:part,input,driver,bottom,t1,mid,t2,top,target,polarity:'positive_two_inversions'});connect('retained_release_to_all_prior_stages',pt(logic,'release_level'),'south',input,'east');}
 const withdrawal=insert('withdrawal_fanout',makeMatrix({inputs:['withdraw'],outputs:['rf','local','lsu','alu'],products:['rf','local','lsu','alu'].map(out=>({out,literals:{withdraw:true}}))}),P(320,170,540));
 connect('withdraw_to_fanout',pt(logic,'withdraw_level'),'south',pt(withdrawal,'withdraw'),'south');
 connect('withdraw_RF_reset',pt(withdrawal,'rf'),'south',base.ports.architectural_zero.withdraw.bits[0].position,'south');
 // Withdraw the three real reset deliveries using source-normalized subtract
 // masks. The parked barrier and narrow data clears remain asserted.
 const previous=[['epoch_local_reset',read('../control-reset-epoch-v1/design.json').connections.find(v=>v.name==='local_architectural_reset_blank')],...['scratch_reset_to_LSU','scratch_reset_to_ALU'].map(n=>[n,read('../control-reset-scratch-v1/design.json').connections.find(v=>v.name===n)])];
 for(const[n,c]of previous){let p=c.tap,old=at(p),side;let dir=Object.keys(F).find(d=>F[d]===old.block.properties.facing);
  const findSide=q=>['north','south','east','west'].filter(v=>V[v][0]*V[dir][0]+V[v][1]*V[dir][1]===0).find(v=>[1,2,3,4].every(i=>{const a=step(q,v,i);if(at(a)||at(P(a.x,a.y-1,a.z)))return false;return Object.values(V).every(([x,z])=>[-1,0,1].every(y=>{const t=P(a.x+x,a.y+y,a.z+z);return K(t)===K(q)||!at(t)||at(t).block.id.endsWith('_concrete');}));}));
  if(n.startsWith('scratch_')){const r=read('../control-reset-scratch-v1/routes.json')[n];let found;for(let i=20;i<r.path.length-4;i++){const q=r.path[i],b=at(q)?.block;if(b?.id!=='minecraft:repeater')continue;dir=Object.keys(F).find(d=>F[d]===b.properties.facing);const rear=step(q,dir,-1),prev=step(q,dir,-2);if(K(rear)!==K(r.path[i-1])||K(prev)!==K(r.path[i-2])||at(rear)?.block.id!==W||at(prev)?.block.id!==W)continue;const sd=findSide(q);if(sd){found={q,rear,sd};break;}}assert(found,'No isolated normalized withdrawal section '+n);p=found.q;old=at(p);side=found.sd;const before=at(found.rear),after={id:'minecraft:repeater',properties:{facing:F[dir],delay:'1'}};map.set(K(found.rear),{...before,block:after,part:n+'_rear_normalizer'});substitutions.push({name:n+'_rear_normalizer',position:found.rear,before:before.block,after});
  }else side=['north','south','east','west'].filter(v=>V[v][0]*V[dir][0]+V[v][1]*V[dir][1]===0).find(v=>[1,2].every(i=>!at(step(p,v,i))&&(!at(P(step(p,v,i).x,p.y-1,step(p,v,i).z))||at(P(step(p,v,i).x,p.y-1,step(p,v,i).z)).block.id==='minecraft:light_gray_concrete')));assert(side,'No withdrawal side '+n);
  const after={id:'minecraft:comparator',properties:{facing:F[dir],mode:'subtract'}};map.set(K(p),{...old,block:after,part:n+'_withdraw_mask'});substitutions.push({name:n,position:p,before:old.block,after});part=n+'_withdraw_side';const sideDir=Object.keys(V).find(v=>V[v][0]===-V[side][0]&&V[v][1]===-V[side][1]);rep(step(p,side),sideDir);wire(step(p,side,2));edge(step(p,side,2),step(p,side));edge(step(p,side),p);connect('withdraw_'+n,pt(withdrawal,({epoch_local_reset:'local',scratch_reset_to_LSU:'lsu',scratch_reset_to_ALU:'alu'})[n]),'south',step(p,side,2),sideDir);
 }
 for(const p of[P(300,49,-57),P(300,29,-49),P(640,250,-317),P(-343,181,413),P(370,250,-406),P(110,38,-188),P(92,38,-188)]){part='explicit_slope_isolation_cap';solid(p);isolation_caps.push(p);}

 for(const e of base.edges)edge(e.from,e.to);
 const prefixes=Object.fromEntries(lower_taps.map(t=>[t.name,t.name==='arch_zero_nzp0_1'?[...Array.from({length:5},(_,i)=>P(t.start.x,t.start.y-i,t.start.z-i)),P(t.start.x,t.start.y-4,t.start.z-5),P(t.start.x,t.start.y-4,t.start.z-6)]:['arch_zero_nzp3_0','arch_zero_nzp3_1'].includes(t.name)?[...Array.from({length:5},(_,i)=>P(t.start.x,t.start.y-i,t.start.z+i)),P(t.start.x,t.start.y-4,t.start.z+5),P(t.start.x,t.start.y-4,t.start.z+6)]:[...Array.from({length:5},(_,i)=>P(t.start.x-i,t.start.y-i,t.start.z)),P(t.start.x-5,t.start.y-4,t.start.z),P(t.start.x-6,t.start.y-4,t.start.z)]]));
 const tails={};
 for(const[n,s,sd,d,ad]of pending)if(ad==='south'){const end=step(d,ad,-2);tails[n]=Array.from({length:17},(_,i)=>step(end,ad,i-16));}
 const halo=p=>{const out=[];for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++)for(let z=-2;z<=2;z++)out.push(P(p.x+x,p.y+y,p.z+z));return out;};
 const cacheUrl=new URL('routes.json',import.meta.url),cache=existsSync(cacheUrl)?read('routes.json'):{},reserved=[];
 for(const path of Object.values(tails))reserved.push(...path,...halo(path[0]));for(const path of Object.values(prefixes))reserved.push(...path);
 for(const[n,s,sd,d,ad]of pending)reserved.push(...Array.from({length:12},(_,i)=>step(s,sd,i+2)),...Array.from({length:12},(_,i)=>step(d,ad,-i-2)));
 function draw(name,s,sd,d,ad,stubs=false){part=name;assert.equal(at(s)?.block.id,W,'Source '+name+' '+K(s));assert.equal(at(d)?.block.id,W,'Destination '+name);const tap=customTaps[name]?.tap??step(s,sd),start=customTaps[name]?.start??step(s,sd,2),arrival=step(d,ad,-1),end=step(d,ad,-2);
  if(stubs){if(!at(tap))rep(tap,sd);else assert.deepEqual(at(tap).block,{id:'minecraft:repeater',properties:{facing:F[sd],delay:'1'}},'Tap '+name+' '+K(tap));if(!at(start))wire(start);else assert.equal(at(start).block.id,W);rep(arrival,ad);wire(end);edge(s,tap);edge(tap,start);edge(end,arrival);edge(arrival,d);return;}
  let path=cache[name]?.path;if(!path){assert(plan,'Missing route '+name);const ignore=[tap,start,arrival,end,...[tap,start,arrival,end].map(p=>P(p.x,p.y-1,p.z)),...Array.from({length:12},(_,i)=>step(s,sd,i+2)),...Array.from({length:12},(_,i)=>step(d,ad,-i-2))],forbidden=[tap,arrival].flatMap(p=>Object.values(V).map(([x,z])=>P(p.x+x,p.y,p.z+z))).filter(p=>![s,start,end,d].some(q=>K(p)===K(q)));const tail=tails[name]??[end],approach=tail[0];ignore.push(...tail,...tail.map(p=>P(p.x,p.y-1,p.z)),...halo(approach).filter(p=>!at(p)));forbidden.push(...[-2,-1,1,2].map(y=>P(approach.x,approach.y+y,approach.z)));for(const p of tail.slice(1)){forbidden.push(...[-2,-1,0,1,2].map(y=>P(p.x,p.y+y,p.z)),...Object.values(V).flatMap(([x,z])=>[-1,0,1].map(y=>P(p.x+x,p.y+y,p.z+z))));}const prefix=prefixes[name]??[start];assert.deepEqual(prefix[0],start);ignore.push(...prefix,...prefix.map(p=>P(p.x,p.y-1,p.z)));for(const p of prefix.slice(0,-2))forbidden.push(...[-2,-1,0,1,2].map(y=>P(p.x,p.y+y,p.z)),...Object.values(V).flatMap(([x,z])=>[-1,0,1].map(y=>P(p.x+x,p.y+y,p.z+z))));let found;try{found=searchPath(map,prefix.at(-1),approach,{ignore,reserved,forbidden});}catch(error){console.error(JSON.stringify([...map.values()].filter(v=>Math.abs(v.position.x-approach.x)<=2&&Math.abs(v.position.y-approach.y)<=2&&Math.abs(v.position.z-approach.z)<=3)));throw error;}path=[...prefix.slice(0,-1),...found.path,...tail.slice(1)];cache[name]={source:s,destination:d,path,expanded:found.expanded};writeFileSync(cacheUrl,JSON.stringify(cache)+'\n');console.error(name+': '+path.length);}
  assert.deepEqual(path[0],start);assert.deepEqual(path.at(-1),end);const refresh=refreshIndices(path);for(let i=1;i<path.length-1;i++){const p=path[i],q=path[i+1];if(refresh.includes(i))rep(p,Object.keys(V).find(d=>p.x+V[d][0]===q.x&&p.z+V[d][1]===q.z));else wire(p);}for(let i=1;i<path.length;i++)edge(path[i-1],path[i]);routes.push({name,path,refresh_indices:refresh});connections.push({name,source:s,tap,destination:d,arrival});
 }
 for(const v of Object.values(cache))reserved.push(...v.path);
 for(const a of pending)draw(...a,true);for(const a of pending)draw(...a);
 const ports={...base.ports,reset_ack:{...states.external_ack.ports.state,meaning:'Held whole-core warm-reset completion through downstream withdrawal and final rearm. Static geometry; timing/native acceptance remains unproved.'},reset_final:{...logic.ports,states:Object.fromEntries(Object.entries(states).map(([n,v])=>[n,v.ports.state])),completion:eligible.ports,exits:exit.ports,cleared:clear.ports}};
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=blocks.reduce((v,b)=>Math.min(v,b.position[a]),Infinity);box.to[a]=blocks.reduce((v,b)=>Math.max(v,b.position[a]),-Infinity);}
 return{status:'connected_final_reset_ack_withdrawal_rearm_candidate',blocks,parents,ports,edges,routes,connections,substitutions,removed,observations,observation_taps,lock_inventory,clear_columns,positive_columns,terminal_columns,lower_taps,isolation_caps,box,metrics:{blocks:blocks.length,parent_blocks:base.blocks.length,retained_bits:1117,new_pipeline_bits:8,connections:connections.length},native_acceptance:false,complete_core_reset:false,missing:['Physical propagation, phase nonoverlap and far closure/ACK visibility inequalities remain unproved.','No native execution or whole-machine admission is claimed.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeFinalReset({plan:process.argv.includes('--plan')});if(process.argv.includes('--check'))assert.deepEqual(d,read('design.json'));else writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');console.log(JSON.stringify(d.metrics));}
