import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {makeOwnedDataBank} from '../../../../hardware/memory-layout-data-owned-bank.mjs';
import {makeDataBank64} from '../../../../hardware/memory-layout-data-bank.mjs';
import {makeDataOwner} from '../../../../hardware/memory-layout-data-owner.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,S='minecraft:light_gray_concrete',W='minecraft:redstone_wire',V={west:[1,0],east:[-1,0],north:[0,1],south:[0,-1]},dirs=Object.values(V),edge=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeOwnedDataBank(),bank=makeDataBank64(),owner=makeDataOwner();assert.deepEqual(d,JSON.parse(readFileSync(new URL('design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v.block])),get=p=>m.get(K(p)),parents=new Map(),allowed=new Set();let preserved=0,supports=0,faces=0,chronological=0;assert.equal(m.size,d.blocks.length);
 const rep=(p,f)=>assert.deepEqual(get(p),{id:'minecraft:repeater',properties:{facing:f,delay:'1'}});
 for(const[parent,o]of[[bank,P(0,0,0)],[owner,d.owner_offset]])for(const v of parent.blocks){const p=P(v.position.x+o.x,v.position.y+o.y,v.position.z+o.z);assert.deepEqual(get(p),v.block,'parent '+K(p));parents.set(K(p),v.block);preserved++;}
 for(const v of d.blocks){if(parents.has(K(v.position)))continue;const p=v.position,b=v.block;if(b.id===S)continue;let q=P(p.x,p.y-1,p.z);if(b.id==='minecraft:redstone_wall_torch'){const[dx,dz]=V[b.properties.facing];q=P(p.x+dx,p.y,p.z+dz);}assert.equal(get(q)?.id,S,'support '+K(p));supports++;}
 assert.equal(d.connections.length,15);for(const r of d.routes){assert(r.max_dust_run<=14);const index=new Map(r.path.map((p,i)=>[K(p),i]));for(let i=0;i<r.path.length;i++){const p=r.path[i],b=get(p);assert(b);if(i){const a=r.path[i-1];if(p.y>a.y)assert(!get(P(a.x,a.y+1,a.z)),'uphill headroom');if(p.y<a.y)assert(!get(P(p.x,a.y,p.z)),'downhill headroom');}if(b.id==='minecraft:repeater'){const[dx,dz]=V[b.properties.facing];assert.deepEqual(r.path[i-1],P(p.x-dx,p.y,p.z-dz));assert.deepEqual(r.path[i+1],P(p.x+dx,p.y,p.z+dz));}else{assert.equal(b.id,W);for(const[dx,dz]of dirs)for(const dy of[-1,0,1]){const q=P(p.x+dx,p.y+dy,p.z+dz),k=index.get(K(q));if(k===undefined||dy&&get(q)?.id!==W)continue;if(dy>0&&get(P(p.x,p.y+1,p.z))||dy<0&&get(P(q.x,p.y,q.z)))continue;assert.equal(Math.abs(k-i),1,'same-route shortcut');chronological++;}}}}
 for(const x of d.connections){const b=x.field,expected=b<6?bank.ports.address.positions[b]:b<14?bank.ports.write_data.positions[b-6]:P(80,-59,-60);assert.deepEqual(x.destination,expected);rep(x.final_driver,b===14?'west':'north');if(b<14)allowed.add(edge(x.final_driver,x.destination));}
 assert.deepEqual(get(P(88,-59,-56)),{id:'minecraft:comparator',properties:{facing:'north',mode:'subtract'}});rep(P(87,-59,-56),'west');rep(P(88,-59,-57),'north');rep(P(88,-59,-55),'north');assert.deepEqual(get(P(83,-59,-60)),{id:'minecraft:redstone_wall_torch',properties:{facing:'east'}});for(const p of[P(87,-59,-56),P(88,-59,-57)])allowed.add(edge(p,P(88,-59,-56)));allowed.add(edge(P(88,-59,-55),bank.ports.write_open.positions[0]));
 assert.equal(d.responses.length,8);for(const q of d.responses){rep(q.driver,'south');rep(q.storage,'south');rep(q.lock,'east');assert.equal(q.lock.x,q.storage.x+1);assert.equal(q.lock.z,q.storage.z);allowed.add(edge(q.driver,q.storage));allowed.add(edge(q.storage,q.lock));rep(P(q.storage.x+2,279,-65),'north');for(let n=0;n<=4;n++)assert.equal(get(P(q.storage.x+2,279-n,-64+n))?.id,W);}
 for(const v of d.blocks){const p=v.position,b=v.block;if(parents.has(K(p))||b.id===S)continue;for(const[dx,dz]of dirs){const q=P(p.x+dx,p.y,p.z+dz),bb=get(q);if(bb&&bb.id!==S&&d.nets[K(p)]!==d.nets[K(q)]){assert(allowed.has(edge(p,q)),'foreign face '+K(p)+' '+K(q));faces++;}if(b.id===W)for(const dy of[-1,1]){const q=P(p.x+dx,p.y+dy,p.z+dz);if(get(q)?.id!==W||d.nets[K(p)]===d.nets[K(q)])continue;if(dy>0&&get(P(p.x,p.y+1,p.z))||dy<0&&get(P(q.x,p.y,q.z)))continue;assert.fail('foreign slope '+K(p)+' '+K(q));}}if(['minecraft:repeater','minecraft:comparator'].includes(b.id)){const[dx,dz]=V[b.properties.facing];for(const[sx,sz]of dirs.filter(([x,z])=>x*dx+z*dz===0)){const q=P(p.x+sx,p.y,p.z+sz),bb=get(q);if(!['minecraft:repeater','minecraft:comparator'].includes(bb?.id))continue;const[x,z]=V[bb.properties.facing];if(q.x+x===p.x&&q.z+z===p.z)assert(allowed.has(edge(p,q)),'new side source');}}}assert.equal(faces,51);
 return{preserved_parent_blocks:preserved,new_support_checks:supports,new_intended_directed_boundary_faces:faces,new_foreign_dust_steps:0,within_route_chronological_contacts:chronological,request_fields_routed:15};}
const checked=check(d);let negatives=0;function bad(fn){const x=structuredClone(d);fn(x);assert.throws(()=>check(x));negatives++;}bad(x=>x.blocks.find(v=>K(v.position)==='88,-59,-56').block.properties.mode='compare');bad(x=>x.blocks.find(v=>K(v.position)==='87,-59,-56').block.properties.facing='east');bad(x=>x.blocks=x.blocks.filter(v=>K(v.position)==='-24,34,-325'));bad(x=>x.connections[0].destination=structuredClone(x.connections[1].destination));bad(x=>x.blocks.find(v=>K(v.position)==='88,-4,-55').block.properties.facing='south');bad(x=>x.blocks.find(v=>K(v.position)==='-5,275,-58').block.properties.facing='west');
const out={status:'offline_owned_bank_connections_pass',...d.metrics,...checked,negative_cases:negatives,complete_channel:false,native_acceptance:false};if(process.argv.includes('--save'))writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
