import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{rotatePosition,transformBlock}from'../../../../hardware/gpu-layout-assembly.mjs';import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{inputs,active}from'../../memory/fabric-colocation-v2/cut-inputs.mjs';import{fileURLToPath}from'node:url';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H))),P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),base=read('../shared-logic-placement-v1/body-placement.json'),moved=new Map(base.blocks.map(b=>[K(b.position),b.block])),mapping={},claims=new Map;
function add(o,n,block,body){assert(moved.has(K(n)),body+' missing cell '+K(n));assert.deepEqual(moved.get(K(n)),block,body+' state '+K(n));const k=K(o);if(mapping[k])assert.deepEqual(mapping[k].position,n,'Double original '+k);else{mapping[k]={position:n,body};claims.set(k,body);}}
const lanes=read('../bodies.json'),t=read('../four-lane-data-v1/design.json').transforms;for(const b of lanes.blocks){const[l,c]=b.body.split('/');add(b.position,A(b.position,t[l][c]),b.block,b.body);}
const ir=read('../shared-ir-body.json'),it=read('../four-lane-ir-fanout-v1/design.json').ir_transform;for(const b of ir.blocks)add(b.original_position,A(rotatePosition(b.position,it.quarter_turns),it.translation),transformBlock(b.block,it.quarter_turns),'held_ir');
for(const g of read('../shared-spine-v1/bodies.json').groups)for(const b of g.blocks)add(b.original_position,A(b.position,g.translation),b.block,g.name);
const clock=read('../shared-clock-v1/design.json').clock_transform;for(const b of read('../shared-state-inventory-v1/bodies.json').groups.find(g=>g.name==='shared_clock_scanner').blocks)add(b.position,A(b.position,clock.delta),b.block,'clock');for(const b of read('../rf-conditioning-v1/body.json').blocks)add(b.original_position,b.position,b.block,'RF_conditioning');
for(const b of base.blocks.filter(b=>b.placement_island))add(b.original_position,b.position,b.block,b.placement_island);
const core=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H))),world=new Map(core.blocks.map(b=>[K(b.position),b.block]));console.log('mapped',claims.size,'actual reference',world.size);
// Reconstruct actual incoming dependencies, walking only positive transport.
// Any unplaced logic device is a real unresolved source boundary, not crossed
// as though its Boolean function were a wire.
const cuts=[],selected=base.placements.map(p=>p.name),grouped=new Set(selected);let count=0;
for(const b of core.blocks){if(!active(b.block))continue;const target=claims.get(K(b.position));for(const q of inputs(world,b.position)){const source=claims.get(K(q));if((source&&grouped.has(source)||target&&grouped.has(target))&&source!==target)cuts.push({from:q,to:b.position,source_body:source??null,target_body:target??null,new_from:mapping[K(q)]?.position??null,new_to:mapping[K(b.position)]?.position??null});count++;}}
function upstream(target){const queue=[{p:target,parity:0}],seen=new Set([K(target)+':0']),found=new Map,unplaced=[],torchStages=new Set;for(let i=0;i<queue.length;i++){const {p,parity}=queue[i];for(const q of inputs(world,p)){const b=world.get(K(q)),invert=['minecraft:redstone_torch','minecraft:redstone_wall_torch'].includes(b.id),nextParity=parity+Number(invert)&1,k=K(q),state=k+':'+nextParity;if(seen.has(state))continue;seen.add(state);if(claims.has(k)){found.set(state,{position:q,parity:nextParity});continue;}if(invert){const ins=inputs(world,q);if(ins.length!==1){unplaced.push({position:q,block:b,reason:'not_unary_inverter',inputs:ins});continue;}torchStages.add(k);}else if(!['minecraft:redstone_wire','minecraft:repeater'].includes(b.id)){unplaced.push({position:q,block:b,reason:'not_transport'});continue;}else if(b.id==='minecraft:repeater'){const ins=inputs(world,q);if(ins.some(s=>Math.abs(q.x-s.x)+Math.abs(q.z-s.z)===1&&['minecraft:repeater','minecraft:comparator'].includes(world.get(K(s))?.id)&&((b.properties.facing==='north'||b.properties.facing==='south')?q.x!==s.x:q.z!==s.z))){unplaced.push({position:q,reason:'locked_transport'});continue;}}queue.push({p:q,parity:nextParity});}}return{found:[...found.values()],unplaced,visited:seen.size,unary_torch_stages:torchStages.size};}
const v1=read('../../control-front-pc-v1/design.json'),v2=read('../../control-front-pc-v2/design.json'),planned=[...v1.connections.map((c,i)=>({...c,name:'IR_immediate_to_PC_'+i})),...v2.connections],connections=[],unmatched=[];for(const c of planned){assert(mapping[K(c.source)]&&mapping[K(c.destination)],'Unmapped '+c.name);const walk=upstream(c.destination),sources=walk.found.filter(q=>K(q.position)!==K(c.destination));if(walk.unplaced.length||sources.length!==1||K(sources[0].position)!==K(c.source)||sources[0].parity!==0){unmatched.push({...c,actual_sources:sources,unplaced:walk.unplaced});continue;}connections.push({...c,original_source:c.source,original_destination:c.destination,source:mapping[K(c.source)].position,destination:mapping[K(c.destination)].position,source_body:mapping[K(c.source)].body,target_body:mapping[K(c.destination)].body,actual_reference_upstream:sources,upstream_transport_nodes:walk.visited,unary_torch_stages:walk.unary_torch_stages});}
writeFileSync(new URL('endpoint-map.json',H),JSON.stringify({mapping,cuts,connections,unmatched,parent_cells:base.blocks.length,mapped_original_cells:claims.size,selected_body_cuts:cuts.length,original_effective_input_count:count,complete_core:false,native_acceptance:false})+'\n');console.log(JSON.stringify({connections:connections.map(c=>({name:c.name,source:c.source,destination:c.destination})),unmatched,cuts:cuts.length},null,2));
