// Explicit replacement of the four old direct command source stubs.
// The long columns/flights/recipient arrivals remain byte-identical.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='artifacts/full-gpu-layout-v1/',oldPath=root+'master-core-command-routes-v1/design.json',read=p=>JSON.parse(readFileSync(p)),sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),K=p=>`${p.x},${p.y},${p.z}`;
const old=read(oldPath),names=old.connections.map(c=>c.name),removed=old.blocks.filter(v=>names.some(n=>['tap','source_drop','source_feed'].some(t=>v.part===n+'_'+t))),remove=new Set(removed.map(v=>K(v.position))),blocks=old.blocks.filter(v=>!remove.has(K(v.position)));
assert.equal(blocks.length+removed.length,old.blocks.length);
const connections=old.connections.map(c=>{const route=old.routes.find(r=>r.name===c.name+'_source_feed');assert(route);const input=route.path.at(-1);return {...c,original_source:c.source,source:null,source_normalizer:null,source_instance:'serialized_reset_requester'+c.destination_instance.slice(-1),source_port:c.name.includes('warm_reset')?'reset':'start_command',receiver:input,required_companion:'master-reset-requesters-v1/connected-design.json',semantics:'Held requester output is the sole driver of this retained long command trunk; original global output only enters requester sampling.'};});
const inventory={status:'explicit_generated_geometry_replacement',old_design:oldPath,old_design_sha256:sha(oldPath),replace_entire_artifact:'master-core-command-routes-v1',replacement_artifact:'master-core-command-routes-v2',removed_cells:removed,preserved_cells:blocks.length,removed_blocks:removed.length,receiver_wires_recreated_by_companion:connections.map(c=>({name:c.name,position:c.receiver})),no_implicit_world_patch:true,native_acceptance:false};
const design={...old,status:'retained_command_trunks_require_serialized_requester_companion',blocks,connections,routes:old.routes.filter(r=>!names.some(n=>r.name===n+'_source_drop'||r.name===n+'_source_feed')),edges:old.edges.filter(e=>!remove.has(K(e.from))&&!remove.has(K(e.to))),source_bindings:{parent_design_sha256:sha(oldPath)},metrics:{...old.metrics,blocks:blocks.length,removed_source_blocks:removed.length},native_acceptance:false,complete_gpu_layout:false};
for(const[name,value]of Object.entries({'design.json':design,'replacement-inventory.json':inventory})){const text=JSON.stringify(value)+'\n',p=root+'master-core-command-routes-v2/'+name;if(process.argv.includes('--check'))assert.equal(readFileSync(p,'utf8'),text);else writeFileSync(p,text);}
console.log(JSON.stringify({preserved:blocks.length,removed:removed.length,receivers:connections.map(c=>({name:c.name,position:c.receiver}))}));
