import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {readLargeDesign} from '../../../../hardware/memory-layout-large-json-v2.mjs';
import {inputs,active} from '../../memory/fabric-colocation-v2/cut-inputs.mjs';
import {symbolicPower} from '../final-architecture-observers-v1/symbolic-power.mjs';
import {evaluator} from '../rf-quiet-connected-v1/settled.mjs';
const H=new URL('./',import.meta.url),read=n=>JSON.parse(readFileSync(new URL(n,H)));
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`;
const d=read('design.json'),ep=read('endpoint-map.json'),r=read('original-functions.json'),arrivals=read('arrival-obligations.json');
const old=readLargeDesign(fileURLToPath(new URL('../../compact-core-guard-v1/design.json',H)));
const currentWorld=new Map(d.blocks.map(b=>[K(b.position),b.block])),oldWorld=new Map(old.blocks.map(b=>[K(b.position),b.block]));
function network(world,side){
 const seeds=Object.fromEntries(r.sources.map(s=>[s.name,s[side==='current'?'current_seed':'old_seed']])),bindings=Object.fromEntries(r.sources.map(s=>[s.name,{seed:seeds[s.name],classification:s.classification}])),observed={},expectedSource={},nodes=new Map;
 for(const s of r.sources){const proof=s[side+'_proof'];assert.deepEqual(world.get(K(proof.driver)),(side==='current'?currentWorld:oldWorld).get(K(proof.driver)));nodes.set(K(proof.tip),proof.tip);nodes.set(K(proof.driver),proof.driver);}
 for(const row of r.results){
  const original=row.original_comparator,p=side==='current'?row.current_comparator:original,dataOriginal=P(original.x+3,original.y,original.z),data=side==='current'?ep.mapping[K(dataOriginal)].position:dataOriginal;
  assert.deepEqual(world.get(K(p)),{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});
  for(const [kind,position] of [['comparator',p],['flags_data_driver',data]]){const name=`lane${row.lane}_bit${row.bit}_${kind}`;observed[name]=position;expectedSource[name]=row.source_name;nodes.set(K(position),position);}
 }
 if(side==='current'){for(const g of d.logic_bodies)for(const b of g.blocks)if(active(b.block))nodes.set(K(b.position),b.position);for(const a of arrivals.routes)for(const p of a.actual_path)nodes.set(K(p),p);}
 const stops=new Set(Object.values(seeds).map(K)),queue=[...nodes.values()];for(let i=0;i<queue.length;i++){const p=queue[i];if(stops.has(K(p)))continue;for(const q of inputs(world,p))if(!nodes.has(K(q))){nodes.set(K(q),q);queue.push(q);}}
 const positions=[...nodes.values()],m=symbolicPower(world,positions,seeds),e=evaluator(world,positions,seeds),vars=Object.fromEntries(m.bdd.names.map((n,i)=>[n,m.bdd.vars[i]]));
 for(const [name,p]of Object.entries(observed)){const wanted=m.bdd.and(vars[expectedSource[name]],m.bdd.not(vars.architecture_active));for(let k=1;k<=15;k++)assert.equal(m.at(p)[k],wanted,side+'/'+name);}
 return{positions,seeds,bindings,observed,expectedSource,m,e};
}
const current=network(currentWorld,'current'),original=network(oldWorld,'old');assert.equal(current.m.summary().BDD_variables,13);
const cases=[],testBits=new Set([0,8191]);for(let lane=0;lane<4;lane++)for(let bits=0;bits<8;bits++)for(let mask=0;mask<2;mask++)testBits.add((bits<<(lane*3))+(mask<<12));for(let i=0;i<64;i++)testBits.add(((i+1)*3677+359)&8191);
for(const bits of testBits){const assignment=Object.fromEntries(r.sources.map((s,i)=>[s.name,(bits>>i)&1])),cv=current.e.solve(assignment),ov=original.e.solve(assignment),outputs={};for(const [name,p]of Object.entries(current.observed)){const want=assignment[current.expectedSource[name]]&&!assignment.architecture_active?15:0;assert.equal(cv.at(p),want);assert.equal(ov.at(original.observed[name]),want);outputs[name]=want;}cases.push({bits,outputs});}
const receiverAdapterProofs=[];for(const c of d.connections.filter(c=>c.receiver_adapter)){const variable=current.m.bdd.vars[current.m.bdd.names.indexOf('architecture_active')];for(let k=1;k<=15;k++)assert.equal(current.m.at(c.exact_original_receiver)[k],variable,'Exact mask pad after adapter '+c.name);receiverAdapterProofs.push({name:c.receiver_adapter,physical_route_receiver:c.destination,exact_original_mask_pad:c.exact_original_receiver,original_mask_pad:c.original_destination,all_thresholds_positive_after_actual_adapter:true});}
const strengths=[];for(const route of arrivals.routes){const predicate=current.m.at(route.origin)[1];assert.notEqual(predicate,0);let minimum=15;for(let i=1;i<route.actual_path.length;i++)if(currentWorld.get(K(route.actual_path[i])).id==='minecraft:repeater'){let high=0;for(let k=1;k<=15;k++)if(current.m.bdd.and(predicate,current.m.bdd.not(current.m.at(route.actual_path[i-1])[k]))===0)high=k;assert(high>0,'Actual source attenuation '+route.name);minimum=Math.min(minimum,high);}strengths.push({name:route.name,minimum_active_repeater_rear:minimum,complete_source_driver_ancestry:true});}
const reverse=b=>({...b,properties:{...b.properties,facing:({west:'east',east:'west',north:'south',south:'north'})[b.properties.facing]}});
function convert(source,target,id,memo=new Map([[0,0],[1,1]])){if(memo.has(id))return memo.get(id);const n=source.nodes[id],out=target.mk(n.v,convert(source,target,n.lo,memo),convert(source,target,n.hi,memo));memo.set(id,out);return out;}
function mutate(world,net,name,p,change){const saved=world.get(K(p));assert(saved);world.set(K(p),change(saved));let witness=null,refusal=null;try{const m=symbolicPower(world,net.positions,net.seeds);assert.deepEqual(m.bdd.names,net.m.bdd.names);let difference=0;for(let k=1;k<=15;k++){const a=convert(net.m.bdd,m.bdd,net.m.at(p)[k]),b=m.at(p)[k];difference=m.bdd.or(difference,m.bdd.or(m.bdd.and(a,m.bdd.not(b)),m.bdd.and(b,m.bdd.not(a))));}assert.notEqual(difference,0,'Mutation escaped '+name);const assignment=m.bdd.model(difference),expected=net.m.evaluate(p,assignment),actual=evaluator(world,net.positions,net.seeds).solve(assignment).at(p);assert.notEqual(expected,actual,'Mutation did not reproduce '+name);witness={assignment,expected,actual};}catch(error){if(/Mutation escaped|Mutation did not reproduce/.test(String(error)))throw error;refusal=String(error);}world.set(K(p),saved);return{name,position:p,witness,structural_refusal:refusal,result:'refused'};}
const negatives=[];for(const c of d.connections)negatives.push(mutate(currentWorld,current,'reverse_arrival_'+c.name,c.arrival,reverse));
for(const g of d.logic_bodies)for(const b of g.blocks){if(b.block.id==='minecraft:repeater')negatives.push(mutate(currentWorld,current,'reverse_'+g.kind+'_'+K(b.position),b.position,reverse));if(b.block.id.includes('torch'))negatives.push(mutate(currentWorld,current,'constant_high_'+g.kind+'_'+K(b.position),b.position,()=>({id:'minecraft:redstone_block'})));}
for(const row of r.results)negatives.push(mutate(currentWorld,current,'bypass_reset_zero_'+row.lane+'_'+row.bit,row.current_comparator,b=>({...b,properties:{...b.properties,mode:'compare'}})));
const originalNegatives=[];for(const row of r.results){const p=row.original_comparator;for(const [name,q]of [['rear',P(p.x-1,p.y,p.z)],['side',P(p.x,p.y,p.z+1)]])originalNegatives.push(mutate(oldWorld,original,'original_reverse_'+name+'_'+row.lane+'_'+row.bit,q,reverse));originalNegatives.push(mutate(oldWorld,original,'original_bypass_reset_zero_'+row.lane+'_'+row.bit,p,b=>({...b,properties:{...b.properties,mode:'compare'}})));}
const out={status:'twelve_actual_flags_reset_zero_functions_match_original_with_exact_CMP_source_identities',...current.m.summary(),exact_all_input_assignments:8192,original:{...original.m.summary(),negative_mutations:originalNegatives},cases,current_boundary_bindings:current.bindings,original_boundary_bindings:original.bindings,current_positions:current.positions,observed_current_pads:current.observed,route_strengths:strengths,negative_mutations:negatives,retained_original_comparators:12,original_flag_store_inputs:12,new_positive_receiver_adapters:12,receiver_adapter_proofs:receiverAdapterProofs,new_transports:d.connections.length,limits:['The original low result bits are architectural P/Z/N only under the unchanged compare-and-ready/qualified flags OPEN protocol. ALU operation generation and flag capture/hold are separate prerequisites.','Thirteen actual retained output drivers are conditional held boundaries. Their old/current exact one-store ancestry and normalized amplitude are separately checked in original-functions.json.','Original intermediate dust attenuation is retained in source proofs; new normalized arrivals may be stronger before the same original rear/side normalizers. Comparator and flag-data-driver functions match at all thresholds.','The twelve positive two-torch adapters preserve polarity but add delay and require later pulse/burnout/native validation.','Four lock-observer prefixes are repaired separately and their complete AND16/lock identity function is rechecked on this final map.','No external inputs are bound, state added or world changed. Whole-core timing, two-core placement and native execution remain open.'],complete_core:false,native_acceptance:false};
writeFileSync(new URL('function-checks.json',H),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,...current.m.summary(),old:original.m.summary(),cases:cases.length,current_mutations:negatives.length,old_mutations:originalNegatives.length,min_rear:Math.min(...strengths.map(r=>r.minimum_active_repeater_rear))}));
