import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeDispatchPayloadBank}from'../../../../hardware/full-gpu-dispatch-payload-bank.mjs';import{makeStateBank}from'../../../../hardware/full-gpu-state-bank.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');const d=makeDispatchPayloadBank();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));const parents=d.parents.map(p=>materializeInstance(makeStateBank({width:p.id==='block_id'?8:4}),{id:p.id,translation:p.origin}));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to))),parentIds=new Set(d.parents.map(v=>v.id));assert.equal(m.size,d.blocks.length);let inherited=0,supports=0,contacts=0,directions=0;for(const p of parents)for(const v of p.blocks){assert.deepEqual(at(v.position)?.block,v.block);inherited++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const c of d.columns)for(let y=c.first;y<=c.last;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.first)%2===0?'light_gray_concrete':'redstone_torch'));

 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||o.block.id.endsWith('_concrete'))continue;if(parentIds.has(v.part)&&o.part===v.part)continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q));contacts++;}
 for(const v of d.blocks.filter(v=>!parentIds.has(v.part)&&v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const s of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete')||(o.block.id==='minecraft:comparator'&&allowed.has(pair(v.position,o.position))),'Foreign side '+K(v.position));}directions++;}
 assert.equal(d.bindings.length,16);for(const c of d.bindings.filter(c=>c.input)){const bank=parents.find(p=>p.id===c.name);assert.deepEqual(c.next,bank.ports.next_data.bits[c.bit].position);assert.deepEqual(c.current,bank.ports.state.bits[c.bit].position);assert.equal(at(c.input)?.block.id,'minecraft:redstone_wire');const g=at(c.gate);assert.equal(g.block.id,'minecraft:'+(c.name==='block_id'?'comparator':'redstone_wire'));if(c.name==='block_id')assert.deepEqual(g.block.properties,{facing:'west',mode:'subtract'});assert.deepEqual(add(c.init_normalizer,D[at(c.init_normalizer).block.properties.facing]),c.gate);}
 let cases=0;for(let word=0;word<4096;word++)for(let init=0;init<2;init++){let actual=0;for(const c of d.bindings.filter(c=>c.input)){const bit=c.bit+(c.name==='lane_mask'?8:0),v=word>>bit&1,on=c.name==='block_id'?Math.max(0,v*15-init*15)>0:Math.max(v*15,init*15)>0;if(on)actual|=1<<bit;}assert.equal(actual,init?3840:word);cases++;}
 for(const c of d.bindings.filter(c=>c.destination)){assert(['phase_a','phase_b'].includes(c.name));assert.equal(at(c.tap)?.block.id,'minecraft:light_gray_concrete');}
 const power=possibleStrengths({...d,connections:d.bindings.filter(c=>c.input).map(c=>({name:c.name+c.bit,source:c.input}))});assert.deepEqual(power.failed,[]);return{preserved_parent_cells:inherited,support_checks:supports,new_wire_contact_checks:contacts,new_directed_repeaters:directions,data_init_cases:cases,actual_data_bindings:12,actual_phase_bindings:4,possible_strength:power};}
const checks=check(d);let negatives=0;for(const mutate of[c=>{c.blocks.find(v=>K(v.position)==='-3,1,0').block.properties.mode='compare';},c=>{c.bindings[0].current=c.bindings[1].current;},c=>{c.blocks=c.blocks.filter(v=>K(v.position)==='-13,40,-5'?false:true);}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));negatives++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),r={status:'offline_dispatch_retained_payload_bank_checks_pass',...d.metrics,...checks,corruption_refusals:negatives,sources:{generator:sha('../../../../hardware/full-gpu-dispatch-payload-bank.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_calls:0,world_mutations:0,native_acceptance:false,complete_gpu_layout:false,limits:d.missing};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({...r,possible_strength:{...r.possible_strength,taps:undefined}}));
