// Recover source-specific settled functions from complete actual block maps.
// Explicit state/phase boundaries are held for this check; no transition claim.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../../memory/fabric-colocation-v2/cut-inputs.mjs';
import {backwardCone,makeSettledEvaluator} from '../../memory/fabric-colocation-v2/settled-network.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`;
function bytes(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return b;}
const read=n=>JSON.parse(bytes(n)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function scan(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,chunk=i,depth=0,quoted=false,escape=false,count=0,index=0;const accept=end=>{const s=buffer.subarray(chunk,end).toString();if(s.trim())for(const row of JSON.parse('['+s+']'))visit(row,index++);};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){accept(i);return index;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++count===4096){accept(i);chunk=i+1;count=0;}}throw Error('Unterminated stream');}
const census=read('endpoint-candidates.json'),oldMap=new Map(),currentMap=new Map();
const paths={old:'../../memory/master-cold-compatible-v2/design.json',current:'../../memory/fabric-colocation-v2/channel1-write-data-design.json'};
const counts={};for(const [kind,map] of [['old',oldMap],['current',currentMap]]){counts[kind]=scan(bytes(paths[kind]),r=>{assert(!map.has(K(r.position)));map.set(K(r.position),r.block);});console.log(kind,counts[kind]);}
assert.equal(pins['artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v2/design.json'],'364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');
assert.equal(pins['artifacts/full-gpu-layout-v1/memory/fabric-colocation-v2/channel1-write-data-design.json'],'e4eff97b262f65345b147d78e27ab1e70907a8118c8b6cb1b4ab734785c0a5a6');
bytes('../../memory/fabric-colocation-v2/channel1-write-data-source-manifest.json');bytes('../service-quiet-loader-link-v1/source-manifest.json');
const body=read('../../memory/fabric-colocation-v2/active-busy-body.json'),commit=read('../../memory/fabric-colocation-v2/owner-commit-design.json'),phase=read('../../memory/fabric-colocation-v2/snapshot-phase-body.json'),direct=read('../../memory/fabric-colocation-v2/direct-design.json'),loader=read('../control-owner-v1/endpoint-map.json'),oldRet=read('../../memory/channel-retention-v1/design.json');
const out=[],scopes={old:new Set(),current:new Set()},errors=[];
const neighborhoods=(m,p)=>{const a=[];for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++){const q=P(p.x+dx,p.y+dy,p.z+dz),b=m.get(K(q));if(b&&active(b)&&inputs(m,q).some(i=>K(i)===K(p)))a.push({position:q,block:b});}return a;};
function prove(name,kind,map,end,roots,expected){
 for(const r of roots)assert(active(map.get(K(r.position))),`Missing boundary ${name}/${kind}/${r.role} ${K(r.position)}`);
 const cone=backwardCone(map,end,roots.map(r=>r.position));for(const p of cone)scopes[kind].add(K(p));
 const actualRoots=cone.filter(p=>roots.some(r=>K(r.position)===K(p)));
 const boundaryKeys=new Set(roots.map(r=>K(r.position))),unbound=cone.filter(p=>!boundaryKeys.has(K(p))&&inputs(map,p).length===0);
 assert.equal(unbound.length,0,'Unexpected root '+name+'/'+kind+' '+unbound.map(K));
 assert.equal(actualRoots.length,roots.length,'Unused boundary '+name+'/'+kind);
 const evalCone=makeSettledEvaluator(map,cone,roots.map(r=>r.position)),table=[],samples=[],expected_mismatches=[];
 for(let bits=0;bits<2**roots.length;bits++){const values=roots.map((r,i)=>(bits>>i)&1),v=evalCone(new Map(roots.map((r,i)=>[K(r.position),15*values[i]]))),power=v.power.get(K(end))??0,truth=power>0?1:0;table.push(truth);if(truth!==expected(values))expected_mismatches.push({case:bits,values,expected:expected(values),actual_power:power,actual_truth:truth,powers:cone.map(p=>({position:p,power:v.power.get(K(p))??0}))});samples.push(power);}
 return{endpoint:end,block:map.get(K(end)),roots,vertices:cone.length,inputs:cone.reduce((n,p)=>n+(boundaryKeys.has(K(p))?0:inputs(map,p).length),0),cases:table.length,expected_mismatches,truth_table:table,power_table:samples,cone:cone.map(p=>({position:p,block:map.get(K(p)),inputs:boundaryKeys.has(K(p))?[]:inputs(map,p)})),direct_fanout:neighborhoods(map,end)};
}
for(const c of census.candidates){
 const i=Number(c.name.match(/\d+$/)?.[0]??0),X=480*(i%2),L=176*Math.floor(i/2),OX=128*i,OY=80*i,role=c.name.replace(/\d+$/,'');
 let rootsOld=[],rootsNew=[],expected,formula,status='source_function_checked_shared_placement_pending';const root=(role,position)=>({role,position});
 if(role==='mask'){rootsOld=[root('loader.runtime_block',P(-272,88,705))];expected=v=>v[0];formula='runtime_block after actual local two-inverter inhibit body and original chained input delivery';status='missing_loader_mask_body_and_allocator_comparator_integration';}
 else if(['owner_open','payload_open'].includes(role)){const ph=role==='owner_open'?'open_address':'write_phase';rootsOld=[root('actual_shared_'+ph,oldRet.masterPorts[ph]),root('retained_busy_snapshot',oldRet.busySnapshots[i].storage)];rootsNew=[root('actual_shared_'+ph,phase.ports[ph]),root('retained_busy_snapshot',body.statePorts[i].busy_store)];expected=v=>v[0]&&!v[1]?1:0;formula=ph+' AND NOT retained_busy_snapshot';}
 else if(role==='commit_phase'){rootsOld=[root('actual_shared_open_response',oldRet.masterPorts.open_response)];rootsNew=[root('actual_shared_open_response',phase.ports.open_response)];expected=v=>v[0];formula='actual local positive commit phase column from shared open_response; local observation retains its physical delay obligation';}
 else if(role==='any_owner'||role==='commit_input'){rootsOld=Array.from({length:8},(_,j)=>root('retained_negative_owner_'+j,P(OX+120,OY+1+4*j,122)));rootsNew=commit.owners.filter(r=>r.channel===i).map(r=>root('retained_negative_owner_'+r.consumer,r.source));if(role==='commit_input'){rootsOld.push(root('actual_shared_open_response',oldRet.masterPorts.open_response));rootsNew.push(root('actual_shared_open_response',phase.ports.open_response));}expected=v=>v.slice(0,8).some(x=>!x)&&(role==='any_owner'||v[8])?1:0;formula='OR of eight retained positive owners'+(role==='commit_input'?' AND actual commit phase, observed before separate SR reset SET mask':'');}
 else if(role==='active'){rootsOld=[root('retained_ACTIVE_Q',oldRet.activeStates[i].positive)];rootsNew=[root('retained_ACTIVE_Q',body.statePorts[i].active)];expected=v=>v[0];formula='retained ACTIVE Q; old two-inverter positive export removed in new body';}
 else if(role==='busy'){const bx=1024+512*(i%2),by=8*i,bz=480+704*Math.floor(i/2);rootsOld=[root('retained_ACTIVE_Q',oldRet.activeStates[i].positive),root('raw_backend_busy',P(bx+104,by+61,bz+162)),root('owned_downstream_bank_busy',P(bx+284,by+61,bz+165))];rootsNew=[root('retained_ACTIVE_Q',body.statePorts[i].active),root('raw_backend_busy',P(X+104,L+61,162)),root('owned_downstream_bank_busy',P(X+110,L+61,172))];expected=v=>v.some(Boolean)?1:0;formula='ACTIVE OR raw_backend_busy OR owned_downstream_bank_busy; actual pre-snapshot live bus';}
 else {assert.equal(role,'initialize');rootsOld=[root('raw_held_reset',c.old_effective_source)];rootsNew=[root('raw_held_reset',c.current_effective_source)];expected=v=>v[0];formula='raw held reset input, distinct from admission_blocked; actual master source delivery still pending';}
 const r={name:c.name,role,old_physical_pad:c.old_pad,current_physical_pad:role==='mask'?null:c.current_pad,witness_receiver_local:c.current_receiver,formula,status};
 try{r.original=prove(c.name,'old',oldMap,c.old_effective_source,rootsOld,expected);if(role!=='mask'){r.current=prove(c.name,'current',currentMap,c.current_effective_source,rootsNew,expected);assert.equal(r.current.expected_mismatches.length,0,'Current held truth differs from required function');if(role==='payload_open'){assert.equal(r.original.expected_mismatches.length,1);assert.equal(r.original.expected_mismatches[0].case,3);r.deliberate_correction={source:'memory/fabric-colocation-v2/busy-attenuation-repair.json',reason:'Original busy-to-payload branch loses asserted mask. Existing compact producer restores it with one actual refresh repeater per channel; no numeric old/new equivalence claimed.'};}else assert.equal(r.original.expected_mismatches.length,0,'Original held truth differs from required function');}else{r.rejected_candidate={position:c.current_pad,block:currentMap.get(K(c.current_pad))??null,reason:'Loader-owned gadget absent; neighboring allocator translation is not a source identity'};r.allocator_receiver={original:P(5*i,1,-6),original_block:oldMap.get(`${5*i},1,-6`),current:P(5*i,-39,-26),current_block:currentMap.get(`${5*i},-39,-26`),required:'replace preserved repeater by north-facing subtract comparator and connect actual loader inhibit side; current frozen map unchanged'};}}
 catch(e){r.status='function_check_refused';r.error=e.message;errors.push({name:c.name,error:e.message});}
 out.push(r);console.log(c.name,r.status,r.original?.vertices,r.current?.vertices,r.error?.slice(0,200)??'');
}
bytes('../../memory/fabric-colocation-v2/busy-attenuation-repair.json');bytes('../../memory/bank-busy-return-v1/design.json');bytes('trace.mjs');bytes('../../memory/fabric-colocation-v2/settled-network.mjs');bytes('../../memory/fabric-colocation-v2/cut-inputs.mjs');
write('source-functions.json',{status:errors.length?'partial_source_function_checks_refused':'all37_source_roles_classified_with29current_functions',bindings:out,errors,scanned_cells:counts,union_cone_vertices:{old:scopes.old.size,current:scopes.current.size},source_sha256:pins,limits:['Held binary values at actual retained state/phase boundaries only; no state-transition, phase freshness or timing acceptance.','No shared loader-memory transform has been selected and none of37 witness incoming routes is drawn.','Eight loader masks and their allocator comparator replacements are absent from current memory; apparent coordinate collisions are not mappings.','Complete actual maps were queried for every cone input; final whole-assembly geometry/support checks remain pending until placement and routes exist.']});
console.log(JSON.stringify({errors,counts,checks:out.filter(r=>r.status!=='function_check_refused').length}));
