// Independent exact bank/fabric cut changes for the final64runtime address pads.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{inputs}from'../fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`;
function read(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return JSON.parse(b);}
read('../fabric-colocation-v2/channel3-address-source-manifest.json','83b1c8764e62e7c14203eecc780836298c9301c184536759f4ee8d5cbcfcd08c');const before=read('../fabric-colocation-v2/channel2-address-cut-ledger.json'),after=read('../fabric-colocation-v2/channel3-address-cut-ledger.json'),d=read('../fabric-colocation-v2/channel3-address-design.json'),cuts=read('../fabric-colocation-v2/actual-cuts.json').cuts,world=new Map(d.blocks.map(r=>[K(r.position),r.block])),selected=new Map(d.bindings.map(b=>[b.original_cut_index,b])),fabricSelected=new Map([708,709,693,694,695,696,697,698].map((v,i)=>[v,i])),changes=[],negatives=[];assert.equal(selected.size,64);assert.equal(after.bank_inventory.entries.length,572);assert.equal(after.fabric_inventory.entries.length,944);
function bankBinding(b){const actual=d.bindings.find(x=>x.bank===b.bank&&x.bit===b.bit&&x.kind===b.kind),c=d.connections.find(x=>x.kind==='address_bank_branch'&&x.bank===b.bank&&x.bit===b.bit);assert(actual&&c);assert.equal(b.channel,3);assert.equal(b.original_cut_index,actual.original_cut_index);assert.equal(b.cut_sha256,actual.cut_sha256);assert.deepEqual(b.original,actual.original);assert.deepEqual(b.current_destination,actual.current_destination);assert.deepEqual(b.current_retained_cell,d.placedSources[b.bit].storage);assert.deepEqual(b.actual_driver,c.arrival);assert.equal(b.cable,c.name);assert(inputs(world,b.current_destination).some(p=>K(p)===K(c.arrival)));return c;}
for(let i=0;i<572;i++){const a=before.bank_inventory.entries[i],b=after.bank_inventory.entries[i];if(!selected.has(i)){assert.deepEqual(b,a,'Unrelated bank cut '+i);continue;}for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v);assert.equal(a.status,'outside_this_group_reconciliation_pending');assert.equal(b.status,'actual_channel3_address_rebound');bankBinding(b.binding);for(const [key,value]of[['bit',(b.binding.bit+1)%8],['bank',(b.binding.bank+1)%4]]){assert.throws(()=>bankBinding({...b.binding,[key]:value}));negatives.push({inventory:'bank',index:i,field:key,wrong:value});}changes.push({inventory:'bank',index:i});}
function fabricBinding(b,bit){const s=d.placedSources[bit],c=d.connections.find(c=>c.kind==='address_actual_source'&&c.bit===bit);assert.equal(b.channel,3);assert.equal(b.bit,bit);assert.deepEqual(b.current_retained_cell,s.storage);assert.deepEqual(b.original_retained_cell,s.original_storage);assert.deepEqual(b.current_positive_source,c.source);assert.deepEqual(b.current_departure,c.tap);assert.equal(b.cable,c.name);assert(inputs(world,c.tap).some(p=>K(p)===K(c.source)));}
for(let i=0;i<944;i++){const a=before.fabric_inventory.entries[i],b=after.fabric_inventory.entries[i];if(!fabricSelected.has(i)){assert.deepEqual(b,a,'Unrelated fabric cut '+i);continue;}const bit=fabricSelected.get(i);for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v);assert.equal(a.status,'outside_this_group_reconciliation_pending');assert.equal(b.status,'actual_channel3_retained_address_source_rebound');assert.deepEqual(b.binding.original,cuts[i]);assert.equal(cuts[i].target.net,'retained_address3_'+bit);assert.equal(cuts[i].source.group,'channel-retention-v1/payload_exports');fabricBinding(b.binding,bit);assert.throws(()=>fabricBinding({...b.binding,bit:(bit+1)%8},bit));negatives.push({inventory:'fabric',index:i,field:'bit',wrong:(bit+1)%8});changes.push({inventory:'fabric',index:i});}
const bankPending=after.bank_inventory.entries.filter(r=>r.status==='outside_this_group_reconciliation_pending'),fabricPending=after.fabric_inventory.entries.filter(r=>r.status==='outside_this_group_reconciliation_pending');assert.equal(bankPending.length,136);assert.equal(fabricPending.length,836);assert.equal(bankPending.filter(e=>['current/paired_bank_address_adapter','current/bank_write_data_adapter'].includes(e.original.source.group)).length,0);assert.deepEqual([536,537,538,539].map(i=>after.bank_inventory.entries[i]),[536,537,538,539].map(i=>before.bank_inventory.entries[i]));assert.equal(changes.length,72);assert.equal(negatives.length,136);
const self=new URL('ledger-review.mjs',H);pins[fileURLToPath(self).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(self)).digest('hex');const report={status:'passed_exact_channel3_bank_and_fabric_ledger_delta',metrics:{bank_records:572,fabric_records:944,new_bank_bindings:64,new_fabric_bindings:8,unchanged_bank_records:508,unchanged_fabric_records:936,bank_pending:136,fabric_pending:836,runtime_payload_inputs_pending:0,wrong_binding_mutations:136},changes,negative_cases:negatives,source_sha256:pins,limits:['Exactly64channel3bank address cuts and8same-retained-source fabric cuts change; every other full record is unchanged.','Zero pending runtime payload transport does not mean complete memory:68loader inputs,32READY,32response and4loader-tail outputs remain, with protocol/timing still open.']};writeFileSync(new URL('ledger-receipt.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
