import assert from 'node:assert/strict';import{possibleStrengths}from'../connected-controller/check-strength-independent.mjs';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeRegisterSharedControl}from'../../../../hardware/full-gpu-register-shared-control.mjs';import{makeRegisterController}from'../../../../hardware/full-gpu-register-controller-v2.mjs';
import{makeRegisterCounterDatapath}from'../../../../hardware/full-gpu-register-counter-datapath.mjs';import{makeCounterGuards}from'../../../../hardware/full-gpu-counter-guards.mjs';import{step}from'../microprogram.mjs';import{makeStateBank}from'../../../../hardware/full-gpu-state-bank.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeRegisterSharedControl();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0,minRear=15;
 const original=makeRegisterController();for(const v of original.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Parent changed '+K(v.position));inherited++;}

 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){for(let y=c.bottom;y<=c.top;y++){const id=y===c.top&&!c.ends_solid&&c.wire_top?'redstone_wire':(y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch';assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+id);}if(c.wire_top)assert.equal((c.top-c.bottom)%4,1);}

 for(const r of d.routes){let power=15;for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);minRear=Math.min(minRear,power);assert(power>0);power=15;}else{assert.equal(v.block.id,'minecraft:redstone_wire');if(i&&at(r.path[i-1]).block.id==='minecraft:redstone_wire')power--;assert(power>0,'Attenuated '+r.name);}}}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 assert.equal(d.connections.length,7);for(const c of d.connections){assert.equal(at(c.destination)?.block.id,'minecraft:redstone_wire');assert.deepEqual(c.destination,original.ports[c.name].bits[0].position);}
 const capacity=possibleStrengths(d);assert.equal(capacity.failed.length,0,'Actual dust graph cannot reach a receiver');
 for(const z of[140,160]){assert.equal(at(P(-45,-82,z)).block.id,'minecraft:repeater');assert.deepEqual(at(P(-44,-82,z)).block,{id:'minecraft:comparator',properties:{facing:'west',mode:'subtract'}});assert.equal(at(P(-42,-82,z)).block.id,'minecraft:repeater');}
 assert.equal(at(P(-61,-82,148)).block.id,'minecraft:redstone_wall_torch');

 return{preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,minimum_route_repeater_input:minRear,actual_dust_capacity:capacity};}
const checks=check(d);
let cases=0;
for(const permit of[false,true])for(const a of[false,true])for(const b of[false,true]){
 const negative=permit?0:15;const next=Math.max((a?15:0)-negative,0),current=Math.max((b?15:0)-negative,0);assert.equal(!!next,a&&permit);assert.equal(!!current,b&&permit);cases++;
}
let polarities=0;for(const c of d.columns)for(const value of[false,true]){let out=value;for(let y=c.bottom+1;y<c.top;y+=2)out=!out;assert.equal(out,value);polarities++;}
let negatives=0;for(const mutate of[c=>{const r=c.routes.find(r=>r.name==='initialize_clamp_feed');c.blocks=c.blocks.filter(v=>K(v.position)!==K(r.path[30]));},c=>{c.blocks.find(v=>K(v.position)==='-44,-82,141').block.properties.facing='north';},c=>{c.connections.find(c=>c.name==='counter_boot_initialize').destination.x++;},c=>{c.blocks.find(v=>K(v.position)==='-44,-82,140').block.properties.mode='compare';}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));negatives++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),result={status:'offline_register_shared_control_geometry_checks_pass',...d.metrics,...checks,settled_phase_mask_cases:cases,settled_column_polarity_cases:polarities,corruption_refusals:negatives,sources:{generator:sha('../../../../hardware/full-gpu-register-shared-control.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,complete_gpu_layout:false,limits:['Static exact geometry plus settled arithmetic only, not arbitrary game updates or storage initialization.','External shared phase source, retained permit/startup, all32-state conditioning and architectural actions remain missing; seven common control routes are drawn.','A smaller incomplete datapath cannot be compared as a complete controller saving.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
