import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeProgramQuiet}from'../../../../hardware/memory-layout-program-quiet.mjs';import{makeProgramController}from'../../../../hardware/memory-layout-program-controller.mjs';import{makeProgramQuietLogic}from'../../../../hardware/memory-layout-program-quiet-logic.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');const d=makeProgramQuiet();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));const program=makeProgramController(),normalized={...program,ports:Object.fromEntries(Object.entries(program.ports).map(([n,p])=>[n,{...p,bits:p.positions.map((position,bit)=>({bit,position}))}]))};const parents=d.parents.map(p=>materializeInstance(p.id==='program'?normalized:p.id==='quiet_logic'?makeProgramQuietLogic():makeSignalDescent(p.parameters),{id:p.id,translation:p.origin}));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to))),parentIds=new Set(d.parents.map(v=>v.id));assert.equal(m.size,d.blocks.length);let inherited=0,supports=0,contacts=0,directions=0;for(const p of parents)for(const v of p.blocks){assert.deepEqual(at(v.position)?.block,v.block);inherited++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete')||v.block.id==='minecraft:redstone_block')continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.output_y-c.bottom)%4,1);for(let y=c.bottom;y<c.output_y;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.output_y,c.z))?.block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||o.block.id.endsWith('_concrete'))continue;if(parentIds.has(v.part)&&o.part===v.part)continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q));contacts++;}
 for(const v of d.blocks.filter(v=>!parentIds.has(v.part)&&v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const s of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete'),'Foreign side '+K(v.position));}directions++;}
 const reset=program.routes.find(r=>r.name==='reset_busy_main').path.filter(p=>p.z===-204&&p.x>=-216&&p.x<=-208&&at(p).block.id==='minecraft:redstone_wire')[0],expected=[P(-52,-41,-184),P(-47,-41,-184),reset];assert.equal(d.connections.length,3);for(const [bit,c]of d.connections.entries()){assert.deepEqual(c.source,expected[bit]);assert.equal(at(c.source)?.block.id,'minecraft:redstone_wire');assert.equal(c.source_net,program.nets[K(c.source)]);assert.deepEqual(c.destination,parents[1].ports[['active','normal_tail','reset_blocked'][bit]].bits[0].position);const r=at(c.normalizer);assert.equal(r.block.id,'minecraft:repeater');assert.deepEqual(add(c.normalizer,D[r.block.properties.facing]),c.destination);}
 const tail=P(-49,-41,-184);assert.equal(at(tail)?.block.id,'minecraft:repeater');assert.equal(at(tail)?.block.properties.facing,'west');for(const x of[-50,-48,-47])assert.equal(at(P(x,-41,-184))?.block.id,'minecraft:redstone_wire');for(const [i,n]of['core0_drained','core1_drained','channel_quiet'].entries())assert.deepEqual(d.ports[n].bits[0].position,parents[1].ports.next_values.bits[i].position);
 const power=possibleStrengths(d);assert.deepEqual(power.failed,[]);return{preserved_parent_cells:inherited,support_checks:supports,new_wire_contact_checks:contacts,new_directed_repeaters:directions,actual_protocol_quiet_arrivals:3,possible_strength:power};}

const checks=check(d);let negatives=0;for(const mutate of[c=>{const q=c.connections[0].normalizer;c.blocks.find(v=>K(v.position)===K(q)).block.properties.facing='east';},c=>{c.connections[1].source=P(-50,-41,-184);},c=>{const q=c.columns[0];c.blocks=c.blocks.filter(v=>K(v.position)!==K(P(q.x,q.bottom+2,q.z)));}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));negatives++;}

const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),r={status:'offline_program_actual_shared_quiet_routes_pass',...d.metrics,...checks,corruption_refusals:negatives,sources:{generator:sha('../../../../hardware/memory-layout-program-quiet.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_calls:0,world_mutations:0,native_acceptance:false,complete_gpu_layout:false,limits:d.missing};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({...r,possible_strength:{...r.possible_strength,taps:undefined}}));
