// Compose the two already-reviewed cold corrections into one exact memory map.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';
import{readLargeDesign,writeLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{makeSourcePinHasher}from'../../../../scripts/source-pin-hasher.mjs';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),B='artifacts/full-gpu-layout-v1/memory/',audit=makeSourcePinHasher(ROOT),read=p=>JSON.parse(readFileSync(ROOT+'/'+p)),review=read(B+'master-cold-compatible-v2/independent-review.json'),delta=read(B+'cold-extender-removal-v1/delta.json'),K=p=>[p.x,p.y,p.z].join(',');
assert.equal(review.status,'bounded_independent_cold_correction_review_passed');for(const[p,h]of Object.entries(review.source_sha256))assert.equal(audit.hash(p),h,p);
const parent=B+'master-cold-compatible-v1/design.json',d=readLargeDesign(ROOT+'/'+parent),changes=new Map(delta.changes.map(v=>[K(v.position),v])),ports=JSON.stringify(d.ports),box=JSON.stringify(d.box);let replaced=0;
for(const v of d.blocks){const c=changes.get(K(v.position));if(c){assert.deepEqual(v.block,c.before);v.block=structuredClone(c.after);replaced++;}}
assert.equal(replaced,6);assert.equal(d.blocks.length,3381962);assert.equal(JSON.stringify(d.ports),ports);assert.equal(JSON.stringify(d.box),box);
d.status='offline_memory_integrated_held_cold_contract';d.cold_extender_replacement={parent,parent_sha256:audit.hash(parent),patch:B+'cold-extender-removal-v1/delta.json',patch_sha256:audit.hash(B+'cold-extender-removal-v1/delta.json'),changes:delta.changes};
d.cold_reset_contract={cold_only:true,pulse_extenders:false,protocol_bits_removed:6,raw_cold_requirement:'Held by the actual integrated global controller until clear and closure, followed by fresh hardware conditioning and actual drain/flush witnesses.',standalone_short_pulse_reset_admitted:false,timing_certificate:B+'cold-reset-timing-v1/integrated-cold.json',nominal_only:true};d.native_acceptance=false;d.complete_gpu_layout=false;
writeLargeDesign(fileURLToPath(new URL('design.json',import.meta.url)),d);const source_sha256={...review.source_sha256};for(const p of[B+'master-cold-compatible-v2/prepare.mjs',B+'master-cold-compatible-v2/independent-review.json',B+'master-cold-compatible-v2/design.json','hardware/memory-layout-large-json-v2.mjs','scripts/source-pin-hasher.mjs'])source_sha256[p]=audit.hash(p);audit.assertStable();
writeFileSync(new URL('checks.json',import.meta.url),JSON.stringify({status:'exact_two_plus_six_cell_cold_memory_replacement_materialized',source_sha256,actual_cells:d.blocks.length,replacements_from_v1:replaced,replacements_from_original:8,added:0,removed:0,protocol_extender_bits_removed:6,interfaces_and_bounds_unchanged:true,owner_payload_RAM_unchanged:true,standalone_short_pulse_reset_admitted:false,complete_gpu_layout:false,native_acceptance:false},null,2)+'\n');console.log(JSON.stringify({cells:d.blocks.length,replaced,design_sha256:source_sha256[B+'master-cold-compatible-v2/design.json']}));
