// Bounded root review of the six-source cold correction and nominal certificate.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{fileURLToPath}from'node:url';
import{readLargeDesign}from'../../../../hardware/memory-layout-large-json-v2.mjs';import{makeSourcePinHasher}from'../../../../scripts/source-pin-hasher.mjs';
const ROOT=fileURLToPath(new URL('../../../../',import.meta.url)),B='artifacts/full-gpu-layout-v1/',M=B+'memory/',audit=makeSourcePinHasher(ROOT),pins={},read=p=>JSON.parse(readFileSync(new URL('../../../../'+p,import.meta.url))),P=(x,y,z)=>({x,y,z}),K=p=>[p.x,p.y,p.z].join(','),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z);
function bind(p,h){const actual=audit.hash(p);assert.equal(actual,h??actual,p);assert(!pins[p]||pins[p]===actual);pins[p]=actual;}
for(const f of['cold-extender-removal-v1','cold-reset-timing-v1','master-cold-compatible-v1']){const p=M+f+'/source-manifest.json';bind(p);for(const[q,h]of Object.entries(read(p).source_sha256))bind(q,h);}
const delta=read(M+'cold-extender-removal-v1/delta.json'),cert=read(M+'cold-reset-timing-v1/integrated-cold.json'),d=readLargeDesign(ROOT+'/'+M+'master-cold-compatible-v1/design.json'),centres=delta.changes.map(v=>v.position),inside=p=>centres.some(q=>['x','y','z'].every(a=>Math.abs(p[a]-q[a])<=6)),world=new Map(d.blocks.filter(v=>inside(v.position)).map(v=>[K(v.position),v.block]));
assert.equal(d.blocks.length,3381962);assert.equal(delta.changes.length,6);assert.equal(new Set(delta.changes.map(v=>K(v.position))).size,6);
for(const c of delta.changes){assert.deepEqual(world.get(K(c.position)),c.before);assert.equal(c.before.id,'minecraft:redstone_wall_torch');assert.deepEqual(c.after,{id:'minecraft:light_gray_concrete'});world.set(K(c.position),c.after);}
const W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',S='minecraft:light_gray_concrete',RB='minecraft:redstone_block',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},H=Object.values(D),dirs=[...H,P(0,1,0),P(0,-1,0)],at=p=>world.get(K(p)),eq=(a,b)=>K(a)===K(b);
function emits(src,dst){const b=at(src);if([R,C].includes(b?.id))return eq(add(src,D[b.properties.facing]),dst);if([T,WT].includes(b?.id))return !eq(add(src,b.id===T?P(0,-1,0):D[b.properties.facing]),dst);return [RB,'minecraft:lever'].includes(b?.id);}
const rows=[];for(const c of delta.changes){const root=add(c.position,P(1,0,0));assert.equal(at(root)?.id,W);const todo=[root],seen=new Set([K(root)]);let concreteChecks=0;
 for(let i=0;i<todo.length;i++){const p=todo[i];assert(centres.some(q=>['x','y','z'].every(a=>Math.abs(p[a]-q[a])<=3)),'Zero cone escaped fully inspected halo');
  const next=[];for(const s of dirs){const q=add(p,s),b=at(q);assert(!emits(q,p),'Live active source reaches F export');if(b?.id===S){for(const t of dirs){const a=add(q,t),v=at(a);assert(!([R,C].includes(v?.id)&&emits(a,q))&&!([T,WT].includes(v?.id)&&t.y===-1),'Strong source reaches F export');}concreteChecks++;}}
  for(const s of H){const q=add(p,s);if(at(q)?.id===W)next.push(q);if(at(q)?.id===S&&at(add(p,P(0,1,0)))?.id!==S&&at(add(q,P(0,1,0)))?.id===W)next.push(add(q,P(0,1,0)));if(at(q)?.id!==S&&at(add(q,P(0,-1,0)))?.id===W)next.push(add(q,P(0,-1,0)));}
  for(const q of next)if(!seen.has(K(q))){seen.add(K(q));todo.push(q);}
 }
 rows.push({instance:c.instance,F_export:root,wire_ancestors:seen.size,adjacent_conductors_checked:concreteChecks,active_source_ancestors:0});
}
// Independent arithmetic at one origin, retaining all certificate premises.
const clock=read(B+'core-phase-source/design.json').nominal_component_sums,scan=read(M+'cold-reset-timing-v1/scanner-admission-paths.json').reports;
assert.equal(clock.cycle_ticks,3160);assert.equal(clock.phase_a_width_ticks,544);assert.equal(clock.phase_b_width_ticks,540);assert.equal(scan.stores.length,16);
const cold=3*clock.cycle_ticks-clock.phase_a_width_ticks-4;assert.equal(cold,cert.cold_high_min_nominal);assert(cold>cert.scanner_zero_and_closed_max_nominal);assert(cold>Math.max(...Object.values(cert.memory_forced_zero_bounds),...Object.values(cert.normal_control_settled_before_cold_withdrawal)));
assert.equal(cert.fresh_scan_current_transfers,32);assert.equal(cert.fresh_scan_lower_bound,31*clock.cycle_ticks);assert(cert.stale_admission_clear.every(v=>v.nominal_setup_margin>0));
const late=842+Math.max(...Object.values(cert.removed_extender_tail_flush_allowance)),early=Math.min(...cert.stale_admission_clear.map(v=>v.INIT_cable))+31*clock.cycle_ticks;
assert.equal(late,25826);assert.equal(early,98878);assert.equal(early-late,73052);assert.equal(cert.numeric_physical_bounds_established,false);assert.equal(cert.native_acceptance,false);
const sourceMap=read(B+'build-acceptance-v1/image-source-map.json'),changed=new Set(delta.changes.map(v=>K(v.position)));let sourcePositions=0;
function visit(v){if(!v||typeof v!=='object')return;if(['x','y','z'].every(a=>Number.isInteger(v[a]))){sourcePositions++;assert(!changed.has(K(v)),'Cold patch changes an acceptance image/control target');}else for(const q of Object.values(v))visit(q);}visit(sourceMap);
for(const p of[M+'master-cold-compatible-v2/review.mjs',B+'build-acceptance-v1/image-source-map.json'])bind(p);audit.assertStable();
const out={status:'bounded_independent_cold_correction_review_passed',source_sha256:pins,full_materialized_parent_cells_read:d.blocks.length,six_cell_correction:rows,actual_halo_cells:world.size,image_source_position_records_preserved:sourcePositions,independent_nominal_same_origin_margin:early-late,complete_gpu_layout:false,native_acceptance:false,numeric_physical_bounds_established:false,limits:['Full parent read and independent fixed-zero ancestor walk, plus arithmetic/contract cross-check. The author performed the broader support/side-path review; this is not a second exhaustive whole-machine composition audit.','The131072 initial-state cases and route maxima remain authored evidence, not independently rerun here. The working-oscillator/no-burnout/bounded scheduling premises and native gates remain.','The old standalone short cold-pulse extension behavior is intentionally removed. Only the selected long held cold and fresh hardware conditioning sequence is admissible.']};
writeFileSync(new URL('independent-review.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({status:out.status,full_cells:d.blocks.length,F_exports:rows.length,halo_cells:world.size,source_positions:sourcePositions,nominal_margin:early-late,...audit.stats()}));
