// Actual binary core-state storage, decoder and conditional NEXT matrix.
// External qualified phase/event producers are explicit ports, not host steps.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {makeAddressDecoder4} from '../../../hardware/address-decoder4.mjs';
import {makeStateBank} from '../../../hardware/full-gpu-state-bank.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,V={east:[1,0],west:[-1,0],south:[0,1],north:[0,-1]},F={east:'west',west:'east',south:'north',north:'south'};
export const STATES=['IDLE','FETCH','DECODE','REQUEST','WAIT','EXECUTE','UPDATE','DONE'];
export function nextCoreState(state,advance,ret,initialize=false){if(initialize)return 0;if(!advance||state===7)return state;if(state===6)return ret?7:1;return state+1;}
export function makeCoreState(){
 const decoder=makeAddressDecoder4({origin:P(0,0,0),id:'core_state_decoder'}),bank=makeStateBank({width:3,pair:true}),map=new Map(),edges=[],routes=[],gates=[],rows=[],outputs=[],towers=[];
 const edge=(from,to)=>edges.push({from,to}),join=ps=>{for(let i=1;i<ps.length;i++)edge(ps[i-1],ps[i]);};
 function put(p,id,properties,part){const block={id:'minecraft:'+id,...(properties?{properties}:{})},old=map.get(K(p));if(old){assert.deepEqual(old.block,block,'collision '+K(p));return;}map.set(K(p),{position:p,block,part});}
 const solid=(p,n)=>put(p,'light_gray_concrete',undefined,n),dev=(p,id,props,n)=>{solid(P(p.x,p.y-1,p.z),n+'_support');put(p,id,props,n);},wire=(p,n)=>dev(p,'redstone_wire',undefined,n),rep=(p,d,n,delay=1)=>dev(p,'repeater',{facing:F[d],delay:String(delay)},n);
 for(const b of decoder.blocks){const p=b.position;if(p.y>58)continue;if(p.z===12&&(p.x===12||(p.y<=1&&p.x>=13)))continue;put(p,b.block.id.slice(10),b.block.properties,'decoder_parent');}
 const move=p=>P(p.x-22,p.y,p.z);for(const b of bank.blocks)put(move(b.position),b.block.id.slice(10),b.block.properties,'state_parent');
 const parentKeys=new Set(map.keys());
 for(let bit=0;bit<3;bit++){const p=decoder.inputs[bit].position;assert.equal(map.get(K(p)).block.id,'minecraft:lever');map.get(K(p)).block={id:'minecraft:redstone_wire'};map.get(K(p)).part='state_decoder_pad';}
 function route(n,ws){const path=[P(...ws[0])];for(let i=1;i<ws.length;i++){const a=ws[i-1],b=ws[i],delta=b.map((v,j)=>v-a[j]),steps=Math.abs(delta[0])+Math.abs(delta[2]);assert(steps&&(!delta[0]||!delta[2])&&(!delta[1]||Math.abs(delta[1])===steps));for(let j=1;j<=steps;j++)path.push(P(...a.map((v,k)=>v+Math.sign(delta[k])*j)));}
  const candidates=[-1];for(let i=1;i<path.length-1;i++){const a=path[i-1],p=path[i],b=path[i+1];if(!map.has(K(p))&&a.y===p.y&&b.y===p.y&&p.x-a.x===b.x-p.x&&p.z-a.z===b.z-p.z)candidates.push(i);}candidates.push(path.length);const cost=new Map([[-1,0]]),prev=new Map();for(const end of candidates.slice(1))for(const start of candidates){if(start>=end)break;if(!cost.has(start)||end-start>13)continue;const value=cost.get(start)+(end===path.length?0:1);if(value<(cost.get(end)??Infinity)){cost.set(end,value);prev.set(end,start);}}assert(prev.has(path.length),'unrefreshable '+n);const refresh=[];for(let at=prev.get(path.length);at!==-1;at=prev.get(at))refresh.push(at);refresh.sort((a,b)=>a-b);
  for(let i=0;i<path.length;i++){const p=path[i],b=path[i+1],old=map.get(K(p));if(old)assert.equal(old.block.id,'minecraft:redstone_wire','route endpoint '+n+' '+K(p));else if(refresh.includes(i)){const d=Object.keys(V).find(d=>p.x+V[d][0]===b.x&&p.z+V[d][1]===b.z);rep(p,d,n);}else wire(p,n);}join(path);routes.push({name:n,path,refresh_indices:refresh});return path;}
 const gate=(name,x,y,z)=>{wire(P(x-2,y,z),name+'_rear');rep(P(x-1,y,z),'east',name+'_rear_driver');dev(P(x,y,z),'comparator',{facing:'west',mode:'subtract'},name);rep(P(x+1,y,z),'east',name+'_output');wire(P(x+2,y,z),name+'_out');wire(P(x,y,z-2),name+'_mask');rep(P(x,y,z-1),'south',name+'_mask_driver');join([x-2,x-1,x,x+1,x+2].map(x=>P(x,y,z)));join([P(x,y,z-2),P(x,y,z-1),P(x,y,z)]);gates.push({name,center:P(x,y,z),rear:P(x-2,y,z),mask:P(x,y,z-2),out:P(x+2,y,z)});};
 // Three actual CURRENT bits drive the decoder. The absent fourth source is a
 // physically unconnected zero leg; only the eight low-address rows remain.
 route('state_bit0',[[-5,1,0],[-2,1,0]]);
 rep(P(-5,5,-1),'north','state1_branch');wire(P(-5,5,-2),'state1_pad');join([P(-5,5,0),P(-5,5,-1),P(-5,5,-2)]);route('state_bit1',[[-5,5,-2],[-5,5,-4],[18,5,-4],[18,5,-8],[14,1,-8],[14,1,0]]);
 rep(P(-5,9,1),'south','state2_branch');wire(P(-5,9,2),'state2_pad');join([P(-5,9,0),P(-5,9,1),P(-5,9,2)]);route('state_bit2',[[-5,9,2],[-5,9,4],[-5,1,12],[-2,1,12]]);
 for(let bit=0;bit<3;bit++){const x=30+4*bit;for(let y=1;y<=59;y++)if(y%2)solid(P(x,y,4),'next_or');else put(P(x,y,4),'redstone_torch',undefined,'next_or');solid(P(x,0,4),'next_or_floor');put(P(x,60,4),'redstone_torch',undefined,'next_positive');rep(P(x,60,3),'north','next_export');wire(P(x,60,2),'next_selected');join([P(x,60,4),P(x,60,3),P(x,60,2)]);towers.push({bit,x,z:4});}
 for(let state=0;state<8;state++){const y=1+8*state;route('decoded_'+state,[[10,y,6],[14,y,6]]);edge(P(9,y,6),P(10,y,6));gate('hold_'+state,16,y,6);gate('advance_'+state,16,y,14);
  rep(P(14,y,7),'south','onehot_branch');wire(P(14,y,8),'onehot_pad');join([P(14,y,6),P(14,y,7),P(14,y,8)]);route('onehot_to_advance_'+state,[[14,y,8],[14,y,14]]);
  wire(P(22,y,-4),'advance_input');rep(P(22,y,-3),'south','advance_input_driver');wire(P(22,y,-2),'advance_pad');rep(P(21,y,-2),'west','advance_raw_branch');wire(P(20,y,-2),'advance_raw_pad');join([P(22,y,-4),P(22,y,-3),P(22,y,-2),P(21,y,-2),P(20,y,-2)]);route('advance_mask_'+state,[[20,y,-2],[16,y,-2],[16,y,4]]);
  rep(P(22,y,-1),'south','advance_inverter_input');solid(P(22,y,0),'advance_inverter');solid(P(22,y-1,0),'advance_inverter_floor');put(P(22,y,1),'redstone_wall_torch',{facing:'south'},'not_advance');wire(P(22,y,2),'not_advance_pad');rep(P(22,y,3),'south','not_advance_driver');wire(P(22,y,4),'not_advance_wire');join([P(22,y,-2),P(22,y,-1),P(22,y,0)]);join([P(22,y,1),P(22,y,2),P(22,y,3),P(22,y,4)]);route('not_advance_mask_'+state,[[22,y,4],[26,y+4,4],[26,y+4,12],[22,y,12],[16,y,12]]);
  route('hold_bus_'+state,[[18,y,6],[40,y,6]]);route('advance_bus_'+state,[[18,y,14],[44,y,14],[44,y,2],[30,y,2]]);
  const next=state===6?1:state===7?7:state+1;for(let bit=0;bit<3;bit++){const x=30+4*bit;if(state>>bit&1){rep(P(x,y,5),'north','held_bit_inject');join([P(x,y,6),P(x,y,5),P(x,y,4)]);}if(next>>bit&1){rep(P(x,y,3),'south','advanced_bit_inject');join([P(x,y,2),P(x,y,3),P(x,y,4)]);}}
  rows.push({state,name:STATES[state],y,advance_input:P(22,y,-4),onehot:P(14,y,6),hold:P(18,y,6),advance:P(18,y,14),normal_next:next});
 }
 // RET contributes bits1/2 only when UPDATE actually advances. Intermediate
 // positive tower level53 carries this extra OR without crossing row buses.
 const y=49;rep(P(18,y,15),'south','update_advance_branch');wire(P(18,y,16),'update_advance_pad');join([P(18,y,14),P(18,y,15),P(18,y,16)]);route('update_to_ret_gate',[[18,y,16],[16,y,16],[16,y,22]]);
 rep(P(17,y,22),'east','ret_gate_rear');dev(P(18,y,22),'comparator',{facing:'west',mode:'subtract'},'ret_gate');rep(P(19,y,22),'east','ret_gate_output');wire(P(20,y,22),'ret_gate_pad');join([16,17,18,19,20].map(x=>P(x,y,22)));
 wire(P(18,y,28),'ret_input');rep(P(18,y,27),'north','ret_input_driver');solid(P(18,y,26),'ret_inverter');solid(P(18,y-1,26),'ret_inverter_floor');put(P(18,y,25),'redstone_wall_torch',{facing:'north'},'ret_not');wire(P(18,y,24),'ret_not_pad');rep(P(18,y,23),'north','ret_side');join([P(18,y,28),P(18,y,27),P(18,y,26)]);join([P(18,y,25),P(18,y,24),P(18,y,23),P(18,y,22)]);
 route('ret_extra_bits',[[20,49,22],[24,53,22],[40,53,22]]);for(const x of[34,38]){rep(P(x+2,53,21),'north','ret_branch_normalize');wire(P(x+2,53,20),'ret_branch_pad');join([P(x+2,53,22),P(x+2,53,21),P(x+2,53,20)]);route('ret_bit_'+x,[[x+2,53,20],[x+2,53,4]]);rep(P(x+1,53,4),'west','ret_bit_inject');join([P(x+2,53,4),P(x+1,53,4),P(x,53,4)]);}
 // Initialization clamps the real NEXT data to zero; phase cadence continues.
 wire(P(28,64,4),'initialize');rep(P(29,64,4),'east','initialize_driver');wire(P(30,64,4),'initialize_pad');join([P(28,64,4),P(29,64,4),P(30,64,4)]);route('initialize_rail',[[30,64,4],[40,64,4]]);
 for(let bit=0;bit<3;bit++){const x=30+4*bit;rep(P(x,60,1),'north','next_clamp_rear');dev(P(x,60,0),'comparator',{facing:'south',mode:'subtract'},'next_init_clamp');rep(P(x,60,-1),'north','next_clamp_output');wire(P(x,60,-2),'clamped_next');join([2,1,0,-1,-2].map(z=>P(x,60,z)));
  // One extra flat cell precedes the four-step descent; mask terminal lies east.
  route('initialize_mask_'+bit,[[x+2,64,4],[x+2,60,0]]);rep(P(x+1,60,0),'west','initialize_mask_driver');join([P(x+2,60,0),P(x+1,60,0),P(x,60,0)]);
  const targetY=1+4*bit,ws=[[x,60,-2]];let h=60,z=-2;while(h>targetY){const drop=Math.min(8,h-targetY);h-=drop;z-=drop;ws.push([x,h,z]);if(h>targetY){z-=3;ws.push([x,h,z]);}}z=Math.min(z-2,-84);ws.push([x,h,z],[-22,h,z],[-22,h,0]);route('next_feedback_'+bit,ws);outputs.push({bit,selected:P(x,60,2),clamped:P(x,60,-2),destination:P(-22,targetY,0)});
 }
 const ports={};const port=(name,direction,ps,meaning)=>ports[name]={direction,width:ps.length,polarity:'active_high',bit_order:'LSB_first',bits:ps.map((position,bit)=>({bit,position})),meaning};
 port('advance_conditions','input',rows.map(r=>r.advance_input),'Qualified completion event for each state; absent/false holds state. DONE input is functionally ignored. These are physical wires, producers remain external.');port('ret','input',[P(18,49,28)],'Held decoded RET flag, sampled only by completed UPDATE advance.');port('initialize','input',[P(28,64,4)],'High forces NEXT000 through actual subtract gates; run ordered NEXT-close-CURRENT-close with side effects blank.');
 port('next_open','input',[move(bank.ports.next_open.bits[0].position)],'Locally qualified phaseA; not an unconditional raw phase connection.');port('current_open','input',[move(bank.ports.current_open.bits[0].position)],'Locally qualified phaseB after all NEXT locks close.');port('state','output',bank.ports.state.bits.map(b=>move(b.position)),'Retained original eight-state encoding.');port('state_onehot','output',rows.map(r=>r.onehot),'Combinational decoded state; outputs may glitch during CURRENT changes and cannot directly drive architectural writes.');
 const blocks=[...map.values()],box={from:{},to:{}};for(const a of['x','y','z']){box.from[a]=Math.min(...blocks.map(b=>b.position[a]));box.to[a]=Math.max(...blocks.map(b=>b.position[a]));}
 return{status:'physical_core_state_next_matrix_offline_unverified',blocks,box,ports,edges,routes,rows,outputs,towers,gates,parent_keys:[...parentKeys],bank,metrics:{blocks:blocks.length,stored_bits:6,state_decode_rows:8,dimensions:Object.fromEntries(['x','y','z'].map(a=>[a,box.to[a]-box.from[a]+1]))},semantics:'CURRENT holds original 3-bit core state. Qualified advance selects successor, with UPDATE choosing FETCH or DONE from RET. DONE retains itself. Initialization clamps actual NEXT to000. All routes from CURRENT through decode/matrix back to NEXT and NEXT→CURRENT are drawn.',phase_contract:'One producer per core continues through reset/handshake wait. NEXT may open only in qualified phaseA; it must fully close before qualified phaseB opens CURRENT. Physical state and decoder must settle before any action window. Raw reset blanks architectural outputs but must not freeze this initialization cadence.',missing:['Actual producers/reducers for eight advance conditions and retained fault inhibition.','Action qualification matrix and all RF/LSU/fetch/ALU/PC request routes.','Shared phase producer/fanout and measured worst-path budgets; no native timing margin.','Core reset/initialize acknowledgement sequence and dispatch/start ownership.'],native_acceptance:false,complete_gpu:false};
}
export function checkCoreState(d){const map=new Map(d.blocks.map(b=>[K(b.position),b])),old=new Set(d.parent_keys),allowed=new Set(d.edges.map(e=>[K(e.from),K(e.to)].sort().join('|')));assert.equal(map.size,d.blocks.length);let supports=0,contacts=0;
 for(const b of d.blocks){if(b.block.id.endsWith('_concrete'))continue;let p=P(b.position.x,b.position.y-1,b.position.z);if(b.block.id==='minecraft:redstone_wall_torch'){const[x,z]=V[b.block.properties.facing];p=P(b.position.x-x,b.position.y,b.position.z-z);}assert.equal(map.get(K(p))?.block.id,'minecraft:light_gray_concrete','support '+K(b.position));supports++;}
 for(const b of d.blocks.filter(b=>b.block.id==='minecraft:redstone_wire'))for(const[x,z]of Object.values(V))for(const dy of[-1,0,1]){const p=P(b.position.x+x,b.position.y+dy,b.position.z+z),o=map.get(K(p));if(!o||o.block.id.endsWith('_concrete'))continue;if(old.has(K(b.position))&&old.has(K(p)))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&map.has(K(P(b.position.x,b.position.y+1,b.position.z))))continue;if(dy===-1&&map.has(K(P(p.x,p.y+1,p.z))))continue;assert(allowed.has([K(b.position),K(p)].sort().join('|')),'foreign dust '+K(b.position)+' '+K(p));contacts++;}
 let cases=0;for(let state=0;state<8;state++)for(let advance=0;advance<2;advance++)for(let ret=0;ret<2;ret++)for(let init=0;init<2;init++){let result=0;for(let bit=0;bit<3;bit++){let prior=false,torch=false;for(let y=1;y<=59;y+=2){const row=d.rows.find(r=>r.y===y),hold=row?.state===state&&!advance,go=row?.state===state&&advance,extra=y===53&&state===6&&advance&&ret&&bit>0;const inject=(hold&&!!(state>>bit&1))||(go&&!!(row.normal_next>>bit&1))||extra;torch=!(prior||inject);prior=torch;}result|=(!init&&torch?1:0)<<bit;}assert.equal(result,nextCoreState(state,!!advance,!!ret,!!init));cases++;}
 return{status:'author_static_connected_core_state_checks_passed',...d.metrics,support_checks:supports,new_dust_contacts:contacts,core_transition_cases:cases,native_calls:0,limits:['Local contact/polarity checks and exact sequential function, not Minecraft timing or architectural action admission.','Decoder parent contact correctness inherited; fourth-source removal and new crossings still need independent review.']};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const d=makeCoreState(),r=checkCoreState(d);if(process.argv.includes('--check'))assert.deepEqual(JSON.parse(readFileSync(new URL('design.json',import.meta.url))),d);else{writeFileSync(new URL('design.json',import.meta.url),JSON.stringify(d)+'\n');writeFileSync(new URL('offline-check.json',import.meta.url),JSON.stringify(r,null,2)+'\n');}console.log(JSON.stringify(r,null,2));}
