// Independently reconcile exact old egress/ingress identities with checked cables.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`;
function read(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return JSON.parse(b);}
read('../loader-global-delivery-v1/source-manifest.json','9b2aeb1a9a719f21354db91a9fc0cc8d02b35bde96019dcfc141eed1b017ada3');
const before=read('../bank-global-delivery-v1/remaining-cuts.json'),after=read('../loader-global-delivery-v1/remaining-cuts.json'),service=read('../loader-program-colocation-v1/service-any-owner-delivery-v1/remaining-cuts.json'),memory=read('../memory/fabric-colocation-v2/channel3-address-cut-ledger.json'),delta=read('../loader-global-delivery-v1/delta.json'),endpoint=read('../loader-global-delivery-v1/endpoint-map.json'),original=read('../master-loader-control-routes-v1/design.json'),scope=read('../loader-program-colocation-v1/reference-scope.json'),receipt=read('receipt.json'),indices=[261,287,319,320],selected=new Map(indices.map((v,i)=>[v,delta.connections[i]])),cutSelected=new Map(),changes=[];
const oldMap=new Map([...scope.blocks,...scope.foreign_context,...original.blocks].map(r=>[K(r.position),r.block])),newMap=new Map(delta.new_cells.map(r=>[K(r.position),r.block]));
for(const[index,c]of selected){const t=before.dispatch.transfers[index],matches=before.dispatch.effective_cut_ledger.map((v,i)=>[v,i]).filter(([v])=>K(v.source)===K(t.source)&&K(v.target)===K(t.target));assert.equal(matches.length,1);cutSelected.set(matches[0][1],c);}
for(const[field,n,picks]of[['transfers',352,selected],['effective_cut_ledger',661,cutSelected],['direct_foreign_boundaries',48,new Map()]]){assert.equal(before.dispatch[field].length,n);assert.equal(after.dispatch[field].length,n);for(let i=0;i<n;i++){const a=before.dispatch[field][i],b=after.dispatch[field][i],c=picks.get(i);if(!c){assert.deepEqual(b,a,field+'/'+i);continue;}for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v,field+'/'+i+'/'+k);assert.notEqual(b.status,a.status);assert.deepEqual(b.shared_actual_producer,c.root);assert.deepEqual(b.shared_target,c.destination);assert.equal(b.shared_route,c.name);if(field==='transfers'){assert.deepEqual(b.shared_arrival_normalizer,c.normalizer);assert.deepEqual(b.shared_retained_target,c.destination);}else assert.deepEqual(b.shared_source,c.normalizer);changes.push({ledger:field,index:i,old_status:a.status,new_status:b.status});}}
for(const[k,v]of Object.entries(before.dispatch))if(!['transfers','effective_cut_ledger','transfer_counts'].includes(k))assert.deepEqual(after.dispatch[k],v,'dispatch metadata '+k);
assert.equal(after.service.loader_control.length,28);assert.equal(service.loader_control.length,28);const loaderProofs=[];
for(let i=0;i<28;i++){const a=service.loader_control[i],b=after.service.loader_control[i];if(i<24){assert.deepEqual(b,a);continue;}const c=delta.connections[i-24],proof=receipt.original.proofs[i-24],old=original.connections.filter(r=>K(r.source)===K(a.source)&&K(r.destination)===K(proof.original_receiver));assert.equal(old.length,1);assert.equal(old[0].name,c.name);assert.equal(a.direction,'outgoing');assert.equal(a.status,'pending');assert.equal(b.index,i);for(const[k,v]of Object.entries(a))if(k!=='status')assert.deepEqual(b[k],v);assert.equal(b.status,'bound_actual_loader_global_control_egress');assert.deepEqual(a.source,proof.original_source);assert.deepEqual(oldMap.get(K(a.source)),a.source_block);assert.deepEqual(oldMap.get(K(a.target)),a.target_block);assert(inputs(oldMap,a.target).some(p=>K(p)===K(a.source)),'Actual old source-to-departure edge absent');assert.deepEqual(old[0].normalizer,before.dispatch.transfers[indices[i-24]].source);assert.deepEqual(old[0].destination,before.dispatch.transfers[indices[i-24]].target);
 assert.deepEqual(b.shared_source,c.root);assert.deepEqual(b.shared_departure,c.source_isolator);assert.deepEqual(b.shared_receiver,c.destination);assert.deepEqual(b.shared_normalizer,c.normalizer);assert.equal(b.shared_route,c.name);assert.equal(b.transfer_index,indices[i-24]);assert.deepEqual(receipt.current.proofs[i-24].source,c.root);assert.deepEqual(receipt.current.proofs[i-24].receiver,c.destination);const route=delta.routes.find(r=>r.name===c.name);assert(route);assert.deepEqual(route.path[0],c.root);assert.deepEqual(route.path[1],c.source_isolator);assert.deepEqual(route.path.at(-2),c.normalizer);assert.deepEqual(route.path.at(-1),c.destination);newMap.set(K(c.root),a.source_block);assert(inputs(newMap,c.source_isolator).some(p=>K(p)===K(c.root)));
 loaderProofs.push({loader_index:i,transfer_index:indices[i-24],original_source:a.source,original_departure:a.target,original_receiver:old[0].destination,current_source:c.root,current_departure:c.source_isolator,current_receiver:c.destination});}
for(const[k,v]of Object.entries(service))if(!['loader_control','counts'].includes(k))assert.deepEqual(after.service[k],v,'service metadata '+k);
const expectedCounts={...service.counts,loader_pending:15,loader_control_bound_total:13,loader_control_pending:15};assert.deepEqual(after.service.counts,expectedCounts);assert.equal(after.service.loader_control.filter(r=>r.status==='pending').length,15);assert.equal(after.service.counts.witness_input_bound_total,28);assert.equal(after.service.counts.witness_input_pending,9);assert.equal(after.service.witness_body_incident.length,81);assert.equal(after.service.witness_external_inputs.length,37);assert.equal(after.service.panel_cuts.length,79);assert.equal(after.service.counts.panel_pending,11);
assert.deepEqual(after.program,before.program);assert.deepEqual(after.bank_quiet,before.bank_quiet);assert.deepEqual(after.memory_cut_ledger,memory);assert.equal(memory.bank_inventory.entries.length,572);assert.equal(memory.fabric_inventory.entries.length,944);assert.equal(memory.payload_remaining,0);const counts={};for(const r of after.dispatch.transfers)counts[r.status]=(counts[r.status]??0)+1;assert.deepEqual(after.dispatch.transfer_counts,counts);assert.equal(counts.external_source_transfer_pending,8);assert.equal(after.dispatch.direct_foreign_boundaries.filter(r=>r.status==='pending').length,31);assert.equal(after.program.filter(r=>r.status==='pending_external_master_connection').length,42);assert.deepEqual(endpoint.connections,delta.connections);assert.deepEqual(endpoint.remaining,{global_incoming:8,global_direct_foreign:31,program:42,loader_control:15,service_witness:9,panel:11});
const negative=[];for(let i=0;i<4;i++)for(let j=0;j<4;j++)if(i!==j)for(const field of ['shared_source','shared_receiver']){const b=structuredClone(after.service.loader_control[i+24]);b[field]=field==='shared_source'?delta.connections[j].root:delta.connections[j].destination;let refused=false;try{assert.deepEqual(b[field],field==='shared_source'?delta.connections[i].root:delta.connections[i].destination);}catch{refused=true;}assert(refused);negative.push({loader_index:i+24,field,wrong_connection:delta.connections[j].name});}
for(const n of ['ledger-review.mjs','../memory/fabric-colocation-v2/cut-inputs.mjs']){const p=new URL(n,H);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(readFileSync(p)).digest('hex');}
const report={status:'passed_exact_loader_global_ledger_delta',metrics:{transfers:352,effective_cuts:661,direct_foreign_cuts:48,changed_global_records:8,loader_cuts:28,new_loader_bindings:4,unchanged_loader_records:24,service_body_cuts:81,service_witness_cuts:37,service_witness_bound:28,service_witness_pending:9,panel_cuts:79,panel_pending:11,bank_inventory_entries:572,fabric_inventory_entries:944,program_cuts:44,global_incoming_pending:8,direct_foreign_pending:31,program_pending:42,loader_pending:15,wrong_bindings_refused:negative.length},changes,loader_proofs:loaderProofs,negative,source_sha256:pins,limits:['Only four selected global transfers, their matching four effective cuts, and four original loader egresses change. Actual old source-to-departure inputs and source/consumer identities are checked; no name-only closure.','The already frozen any-owner service ledger supplies the 28/37 witness baseline; all81 body cuts, all37 input records, panel79 records, quiet fanout and other metadata remain identical.','The complete frozen channel3 memory ledger is copied exactly. Program44 and direct48 records and separate bank-to-loader BUSY obligations are unchanged.','Conditional held-input delivery evidence does not establish upstream state, pulse timing, reset protocol or native execution.']};writeFileSync(new URL('ledger-receipt.json',H),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.metrics));
