// Independent bounded review: direct source loading, actual cold context,
// complete input differential, and a separate directed-network strength solver.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function insert(map,rows,{same=false}={}){for(const r of rows){const k=K(r.position);if(map.has(k)){assert(same,'Duplicate cell '+k);assert.deepEqual(map.get(k),r.block);}else map.set(k,r.block);}}
function scanBlocks(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const part=buffer.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){visit(r);count++;}};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated blocks');}
function cone(world,end,root){const roots=Array.isArray(root)?root:[root],stop=new Set(roots.map(K)),seen=new Map(),queue=Array.isArray(end)?[...end]:[end];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(world.get(k)),'Missing actual dependency '+k);seen.set(k,p);if(!stop.has(k))queue.push(...inputs(world,p));}for(const r of roots)assert(seen.has(K(r)),'Source absent from cone '+K(r));return [...seen.values()];}
function network(world,positions,root){
 const roots=Array.isArray(root)?root:[root],index=new Map(positions.map((p,i)=>[K(p),i])),rootIndices=new Set(roots.map(p=>index.get(K(p))));assert(!rootIndices.has(undefined));
 const rows=positions.map(p=>({p,b:world.get(K(p))})),incoming=positions.map(()=>[]),outgoing=positions.map(()=>[]);let edges=0;
 for(let i=0;i<rows.length;i++){assert([W,R,C,T,WT,'minecraft:redstone_block'].includes(rows[i].b.id),'Unexpected transport device '+rows[i].b.id+' '+K(rows[i].p));if(rootIndices.has(i))continue;const deps=inputs(world,rows[i].p);if(rows[i].b.id===R){const v=D[rows[i].b.properties.facing];assert(deps.every(q=>(q.x-rows[i].p.x)*v.x+(q.z-rows[i].p.z)*v.z<0),'Unmodeled side lock');}for(const q of deps){const j=index.get(K(q));assert.notEqual(j,undefined,'Foreign source '+K(q));incoming[i].push(j);outgoing[j].push(i);edges++;}}
 const visited=new Uint8Array(rows.length),order=[];for(let i=0;i<rows.length;i++)if(!visited[i]){visited[i]=1;const stack=[[i,0]];while(stack.length){const r=stack.at(-1);if(r[1]<outgoing[r[0]].length){const j=outgoing[r[0]][r[1]++];if(!visited[j]){visited[j]=1;stack.push([j,0]);}}else{order.push(r[0]);stack.pop();}}}
 const assigned=new Uint8Array(rows.length);let components=0,wireLoops=0;for(let n=order.length-1;n>=0;n--){const i=order[n];if(assigned[i])continue;const members=[i];assigned[i]=1;for(let at=0;at<members.length;at++)for(const j of incoming[members[at]])if(!assigned[j]){assigned[j]=1;members.push(j);}components++;if(members.length>1||outgoing[i].includes(i)){assert(members.every(j=>rows[j].b.id===W),'Nonwire transport feedback');wireLoops++;}}
 function power(strength){const values=new Uint8Array(rows.length),waiting=new Uint8Array(rows.length).fill(1),queue=rows.map((_,i)=>i);for(const p of roots)values[index.get(K(p))]=typeof strength==='number'?strength:strength.get(K(p))??0;let events=0;for(let at=0;at<queue.length;at++){const i=queue[at];waiting[i]=0;if(rootIndices.has(i))continue;assert(++events<1000000,'Nonconvergent network');let value=0;for(const j of incoming[i])value=Math.max(value,values[j]-(rows[i].b.id===W&&rows[j].b.id===W?1:0));if(rows[i].b.id===R)value=value>0?15:0;else if([T,WT].includes(rows[i].b.id))value=value>0?0:15;else if(rows[i].b.id==='minecraft:redstone_block')value=15;else if(rows[i].b.id===C){const d=D[rows[i].b.properties.facing],rear=incoming[i].filter(j=>(rows[j].p.x-rows[i].p.x)*d.x+(rows[j].p.z-rows[i].p.z)*d.z<0),side=incoming[i].filter(j=>!rear.includes(j)),a=Math.max(0,...rear.map(j=>values[j])),b=Math.max(0,...side.map(j=>values[j]));value=rows[i].b.properties.mode==='subtract'?Math.max(0,a-b):a>=b?a:0;}if(value!==values[i]){values[i]=value;for(const j of outgoing[i])if(!waiting[j]){waiting[j]=1;queue.push(j);}}}return {values,get:p=>values[index.get(K(p))]??0,events};}
 return {power,metrics:{devices:rows.length,edges,components,torch_vertices:rows.filter(r=>[T,WT].includes(r.b.id)).length,wire_conductance_components:wireLoops,nonwire_feedback_components:0},minimumRear(powers,subset){return Math.min(...rows.flatMap((r,i)=>r.b.id===R&&(!subset||subset.has(K(r.p)))?[Math.max(0,...incoming[i].map(j=>powers.values[j]))]:[]));}};
}
read('../loader-global-delivery-v1/source-manifest.json','9b2aeb1a9a719f21354db91a9fc0cc8d02b35bde96019dcfc141eed1b017ada3');
const memory=read('../memory/fabric-colocation-v2/channel3-write-data-design.json'),panels=read('../loader-bank-panels-v1/delta.json'),program=read('../program-service-composition-v1/new-program-obstacles.json'),programQuiet=read('../program-service-composition-v1/cable-delta.json'),masks=read('../loader-program-colocation-v1/service-mask-memory-composition-v1/composed-delta.json'),address0=read('../memory/fabric-colocation-v2/channel0-address-delta.json'),address1=read('../memory/fabric-colocation-v2/channel1-address-delta.json'),owner=read('../loader-program-colocation-v1/service-owner-open-delivery-v1/delta.json'),payload=read('../loader-program-colocation-v1/service-payload-open-delivery-v1/delta.json'),dispatch=read('../dispatcher-service-colocation-v1/placement.json'),serviceQuiet=read('../dispatcher-service-colocation-v1/delta.json');
const base=new Map();insert(base,[...memory.blocks,...panels.blocks,...program.blocks,...programQuiet.blocks,...masks.placed_loader,...masks.placed_masks,...masks.new_cells,...address0.blocks,...address1.blocks,...owner.new_cells,...payload.new_cells,...dispatch.blocks,...serviceQuiet.new_cells]);for(const r of masks.replacements){assert.deepEqual(base.get(K(r.position)),r.before);base.set(K(r.position),r.after);}assert.equal(base.size,2000594);
const programGlobal=read('../program-global-delivery-v1/delta.json'),activeWitness=read('../loader-program-colocation-v1/service-active-witness-delivery-v1/delta.json'),address2=read('../memory/fabric-colocation-v2/channel2-address-delta.json');insert(base,[...programGlobal.new_cells,...activeWitness.new_cells,...address2.blocks]);assert.equal(base.size,2054908);
const bankGlobal=read('../bank-global-delivery-v1/delta.json'),commit=read('../loader-program-colocation-v1/service-commit-phase-delivery-v1/delta.json'),address3=read('../memory/fabric-colocation-v2/channel3-address-delta.json'),anyOwner=read('../loader-program-colocation-v1/service-any-owner-delivery-v1/delta.json');insert(base,[...bankGlobal.new_cells,...commit.new_cells,...address3.blocks,...anyOwner.new_cells]);assert.equal(base.size,2128184);
const delta=read('../loader-global-delivery-v1/delta.json','93edff164f6cd1be2ef503efb5dad1415c580548517d10648bcafc733f59e606'),world=new Map(base);insert(world,delta.new_cells);assert.equal(world.size,2135072);assert.equal(delta.connections.length,4);
const endpoints=read('../loader-program-colocation-v1/control-owner-v1/endpoint-map.json'),dispatchParent=read('../dispatch-global-colocation-v8-dcr-cold-v1/connected-candidate.json'),scope=read('../dispatch-global-colocation-v1/reference-scope.json'),loaderScope=read('../loader-program-colocation-v1/reference-scope.json'),oldRoutes=read('../master-loader-control-routes-v1/design.json'),bindings=read('../dispatch-external-bindings-v1/bindings.json'),loaderT=P(-160,-32,-176),indices=[261,287,319,320],allPorts=Object.entries(endpoints.ports).filter(([n,p])=>p.direction==='input').map(([name,p])=>({name,old:p.bits[0].original_position,current:A(p.bits[0].position,loaderT)})),discovery=new Map();insert(discovery,[...scope.blocks,...scope.foreign_context,...loaderScope.blocks,...loaderScope.foreign_context,...oldRoutes.blocks],{same:true});
function walk(map,ends,stops){const held=new Set(stops.map(K)),seen=new Map(),queue=Array.isArray(ends)?[...ends]:[ends];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(map.get(k)),'Missing actual dependency '+k);seen.set(k,p);if(!held.has(k))queue.push(...inputs(map,p));}return [...seen.values()];}
const selected=[],want=new Set();for(let i=0;i<4;i++){const c=delta.connections[i],binding=bindings.incoming.find(b=>b.transfer_index===indices[i]),original=binding.old_connection,mapped=endpoints.mapping[K(original.source)],receiver=dispatchParent.blocks.find(r=>r.original_position&&K(r.original_position)===K(original.destination));assert(mapped);assert(receiver);assert.deepEqual(c.root,A(mapped.position,loaderT));assert.deepEqual(c.destination,A(receiver.position,dispatch.translation));assert.deepEqual(world.get(K(c.root)),mapped.block);assert.deepEqual(world.get(K(c.destination)),receiver.block);
 const oldGate=walk(discovery,original.source,allPorts.map(p=>p.old)),currentGate=walk(world,c.root,allPorts.map(p=>p.current)),oldKeys=new Set(oldGate.map(K)),currentKeys=new Set(currentGate.map(K)),ports=allPorts.filter(p=>oldKeys.has(K(p.old))||currentKeys.has(K(p.current)));for(const p of ports){assert(oldKeys.has(K(p.old))&&currentKeys.has(K(p.current)));assert.deepEqual(discovery.get(K(p.old)),world.get(K(p.current)));}assert(ports.length<=7);
 const transport=cone(discovery,original.destination,original.source);for(const p of [...transport,...oldGate])for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)want.add(K(A(p,P(x,y,z))));selected.push({index:indices[i],connection:c,original,oldGate,currentGate,ports,transport});}
const actualOld=new Map(),scanned=scanBlocks(bytes('../memory/master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f'),r=>{if(want.has(K(r.position)))insert(actualOld,[r]);});const config=read('../dispatch-global-colocation-v1/selected-config.json'),globalInstance=config.instances.find(r=>r.name==='global'),globalBody=read('../global-command-assembly-v3/design.json',globalInstance.sha256);insert(actualOld,[...oldRoutes.blocks,...globalBody.blocks.map(r=>({position:A(r.position,globalInstance.translation),block:r.block}))].filter(r=>want.has(K(r.position))),{same:true});
const formula=(index,v)=>index===261?!!v.boot:index===287?!!v.load_request:index===319?!!v.raw_start&&!v.raw_reset&&!v.load_request&&!v.owner&&!v.boot&&!!v.cold_initialized&&!!v.image_verified:!!v.raw_reset||!!v.load_request||!!v.owner||!!v.boot;
const oldProofs=[];for(const s of selected){const transport=cone(actualOld,s.original.destination,s.original.source),gate=cone(actualOld,s.original.source,s.ports.map(p=>p.old));assert.deepEqual(new Set(transport.map(K)),new Set(s.transport.map(K)));assert.deepEqual(new Set(gate.map(K)),new Set(s.oldGate.map(K)));for(const p of [...transport,...gate])assert.deepEqual(actualOld.get(K(p)),discovery.get(K(p)));const held=new Set(s.ports.map(p=>K(p.old))),mappedGate=[];for(const p of gate){const m=endpoints.mapping[K(p)];assert(m,'Gate body mapping absent');const q=A(m.position,loaderT);mappedGate.push(q);assert.deepEqual(world.get(K(q)),actualOld.get(K(p)));if(!held.has(K(p))){const oldInputs=inputs(actualOld,p).map(v=>{const m=endpoints.mapping[K(v)];assert(m);return K(A(m.position,loaderT));}).sort();assert.deepEqual(inputs(world,q).map(K).sort(),oldInputs);}}assert.deepEqual(new Set(mappedGate.map(K)),new Set(s.currentGate.map(K)));
 const oldN=network(actualOld,gate,s.ports.map(p=>p.old)),currentN=network(world,s.currentGate,s.ports.map(p=>p.current)),routeN=network(actualOld,transport,s.original.source),sourceCases=[];for(const level of[0,15])assert.equal(routeN.power(level).get(s.original.destination),level);for(let bits=0;bits<2**s.ports.length;bits++){const values=Object.fromEntries(s.ports.map((p,i)=>[p.name,!!(bits>>i&1)])),a=oldN.power(new Map(s.ports.map(p=>[K(p.old),values[p.name]?15:0]))).get(s.original.source),b=currentN.power(new Map(s.ports.map(p=>[K(p.current),values[p.name]?15:0]))).get(s.connection.root),expected=formula(s.index,values)?15:0;assert.equal(a,expected);assert.equal(b,expected);sourceCases.push({bits,values,original:a,current:b});}oldProofs.push({index:s.index,original_source:s.original.source,original_receiver:s.original.destination,ports:s.ports,original_transport:routeN.metrics,old_gate:oldN.metrics,current_gate:currentN.metrics,cases:sourceCases});}
const newKeys=new Set(delta.new_cells.filter(r=>active(r.block)).map(r=>K(r.position))),edges=new Set(),extras=new Map(delta.connections.map(c=>[K(c.destination),K(c.normalizer)]));for(const r of delta.routes)for(let i=1;i<r.path.length;i++){assert(inputs(world,r.path[i]).some(p=>K(p)===K(r.path[i-1])));edges.add(K(r.path[i-1])+'>'+K(r.path[i]));edges.add(K(r.path[i])+'>'+K(r.path[i-1]));}
let receivers=0,supports=0,actualInputs=0,priorInputs=0,newInputs=0,changedOldReceivers=0;for(const[key,block]of world){const[x,y,z]=key.split(',').map(Number),p=P(x,y,z);let support;if(block.id===WT)support=A(p,D[block.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(block.id))support=P(x,y-1,z);if(support){assert(solid(world.get(K(support))),'Missing support '+key);supports++;}if(!active(block))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;if(base.has(key)){const expected=inputs(base,p).map(K);priorInputs+=expected.length;if(extras.has(key)){expected.push(extras.get(key));changedOldReceivers++;}assert.deepEqual(actual,[...new Set(expected)].sort(),'Retained input changed '+key);}else{assert(newKeys.has(key));for(const q of actual)assert(edges.has(q+'>'+key),'Undeclared cable contact');newInputs+=actual.length;}}assert.equal(changedOldReceivers,4);
const proofs=[],negative=[],rears=new Map(),jointBoundary=new Map(),jointPositions=new Map(),opposite={east:'west',west:'east',north:'south',south:'north'};
for(let i=0;i<4;i++){const s=selected[i],c=s.connection,roots=s.ports.map(p=>p.current),positions=cone(world,[c.root,c.destination],roots),n=network(world,positions,roots),cases=[];for(const p of positions)jointPositions.set(K(p),p);for(const p of s.ports){if(jointBoundary.has(p.name))assert.deepEqual(jointBoundary.get(p.name),p.current);jointBoundary.set(p.name,p.current);}for(const a of oldProofs[i].cases){const v=n.power(new Map(s.ports.map(p=>[K(p.current),a.values[p.name]?15:0]))),outputs=[v.get(c.root),v.get(c.destination)];assert.deepEqual(outputs,[a.current,a.current]);cases.push({values:a.values,outputs});for(const p of positions)if(newKeys.has(K(p))&&world.get(K(p)).id===R&&v.get(p)>0){const rear=Math.max(0,...inputs(world,p).map(q=>v.get(q)));rears.set(K(p),Math.min(rears.get(K(p))??15,rear));}}
 const cablePositions=cone(world,c.destination,c.root),cable=network(world,cablePositions,c.root),strengths=[];for(let strength=0;strength<16;strength++){const v=cable.power(strength);assert.equal(v.get(c.destination),strength?15:0);strengths.push({strength,output:v.get(c.destination)});}
 for(const p of cablePositions){const k=K(p),saved=world.get(k);if(!newKeys.has(k)||saved.id!==R)continue;world.set(k,{...saved,properties:{...saved.properties,facing:opposite[saved.properties.facing]}});let rejected=false;try{rejected=network(world,cone(world,c.destination,c.root),c.root).power(15).get(c.destination)!==15;}catch{rejected=true;}assert(rejected);world.set(k,saved);negative.push({index:s.index,kind:'reverse_actual_cable_repeater',position:p});}
 const support=P(c.normalizer.x,c.normalizer.y-1,c.normalizer.z),savedSupport=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),savedSupport);negative.push({index:s.index,kind:'delete_actual_arrival_support',position:support});
 const gateTorch=s.currentGate.find(p=>[T,WT].includes(world.get(K(p)).id));if(gateTorch){const saved=world.get(K(gateTorch));world.set(K(gateTorch),{id:W});let rejected=false;try{const wrong=network(world,cone(world,c.destination,roots),roots);for(const a of oldProofs[i].cases)if(wrong.power(new Map(s.ports.map(p=>[K(p.current),a.values[p.name]?15:0]))).get(c.destination)!==a.current){rejected=true;break;}}catch{rejected=true;}assert(rejected);world.set(K(gateTorch),saved);negative.push({index:s.index,kind:'replace_actual_source_gate_torch_with_wire',position:gateTorch});}
 proofs.push({index:s.index,source:c.root,receiver:c.destination,graph:n.metrics,cases,cable_graph:cable.metrics,strengths});}
assert.equal(jointBoundary.size,7);const names=[...jointBoundary.keys()],roots=[...jointBoundary.values()],jointNet=network(world,[...jointPositions.values()],roots),jointCases=[];for(let bits=0;bits<128;bits++){const values=Object.fromEntries(names.map((n,i)=>[n,!!(bits>>i&1)])),v=jointNet.power(new Map(names.map(n=>[K(jointBoundary.get(n)),values[n]?15:0]))),outputs=selected.map(s=>v.get(s.connection.destination));assert.deepEqual(outputs,indices.map(i=>formula(i,values)?15:0));jointCases.push({bits,values,outputs});}
assert.equal(rears.size,304);assert.equal(negative.length,311);const minimum=Math.min(...rears.values());assert.equal(minimum,5);bytes('review.mjs');bytes('../memory/fabric-colocation-v2/cut-inputs.mjs');write('receipt.json',{status:'passed_independent_loader_global_commands',metrics:{base_cells:base.size,new_cells:delta.new_cells.length,total_cells:world.size,receivers,supports,actual_inputs:actualInputs,preserved_inputs:priorInputs,new_inputs:newInputs,changed_existing_receivers:changedOldReceivers,path_vertices:delta.routes.reduce((n,r)=>n+r.path.length,0),old_transport_cases:8,old_current_source_cases:oldProofs.reduce((n,p)=>n+p.cases.length,0),delivered_source_cases:proofs.reduce((n,p)=>n+p.cases.length,0),delivered_observations:proofs.reduce((n,p)=>n+2*p.cases.length,0),joint_cases:128,joint_observations:512,strength_cases:64,minimum_new_repeater_rear:minimum,actual_mutations:negative.length},original:{cold_cells_streamed:scanned,actual_context_cells:actualOld.size,proofs:oldProofs},current:{proofs,joint_graph:jointNet.metrics,joint_cases:jointCases},negative_cases:negative,source_sha256:pins,limits:['Independent direct source/full-map reconstruction and numeric/SCC evaluator; normalized physical-input helper shared and conditional, not Minecraft physics validation.','Only actual loader input ports are held. Upstream ownership, loaded/initialized state, drain/reset behavior, command pulses, ordering and timing remain outside this review.','Exact accepted2,135,072-cell partial frame excludes both core instances and unfinished master/response/READY/loading connections. No full-GPU or native acceptance.']});console.log(JSON.stringify({status:'passed',cells:world.size,receivers,supports,actualInputs,oldContext:actualOld.size,jointGraph:jointNet.metrics,minimum,mutations:negative.length}));
