import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeQualifiedRegisterActions}from'../../../../hardware/full-gpu-register-actions-qualified.mjs';import{makeRegisterActions}from'../../../../hardware/full-gpu-register-actions.mjs';import{makeRegisterActionEligibility}from'../../../../hardware/full-gpu-register-action-eligibility.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeQualifiedRegisterActions();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0;
 for(const p of d.parents){const source=p.id==='actions'?makeRegisterActions():makeRegisterActionEligibility(),component=materializeInstance(source,{id:p.id,translation:p.origin});for(const v of component.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Changed frozen parent '+K(v.position));inherited++;}}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);for(let y=c.bottom;y<=c.top;y++){const id=y===c.top?'redstone_wire':(y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch';assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+id);}}
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);}else assert.equal(v.block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 const capacity=possibleStrengths(d);assert.equal(capacity.failed.length,0,'Actual dust capacity failure');assert.equal(d.connections.length,4);for(const c of d.connections){assert.equal(at(c.source)?.block.id,'minecraft:redstone_wire');assert.equal(at(c.destination)?.block.id,'minecraft:redstone_wire');}
 return{preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,actual_dust_capacity:capacity};}
const structural=check(d),elig=makeRegisterActionEligibility(),em=new Map(elig.blocks.map(v=>[K(v.position),v.block]));let truthCases=0,laneCases=0;
for(let input=0;input<256;input++){const names=['rd3','rd2','rd1','rd0','reg_write','open_gpr','open_assign','boot'],values=Object.fromEntries(names.map((n,b)=>[n,!!(input>>b&1)])),actual=[false,false];for(const row of elig.rows){let signal=15;for(const g of row.gates){const cmp=em.get(K(g.comparator));assert.equal(cmp.properties.mode,'subtract');const x=g.tower.x,y=g.tower.y,negative=em.get(K(P(x,y,-4))).id==='minecraft:redstone_wall_torch';const mask=(negative?!values[g.name]:values[g.name])?15:0;signal=Math.max(0,signal-mask);signal=signal?15:0;}for(const b of row.bits)actual[b]||=signal>0;}
 const rd=(values.rd3?8:0)+(values.rd2?4:0)+(values.rd1?2:0)+(values.rd0?1:0);assert.deepEqual(actual,[values.open_gpr&&values.reg_write&&rd<13,values.open_assign&&values.boot]);truthCases++;
 for(let enabled=0;enabled<16;enabled++)for(const window of[false,true])for(let lane=0;lane<4;lane++){const on=!!(enabled>>lane&1),gpr=window&&actual[0]&&on,assign=window&&(actual[1]||(values.open_assign&&on));assert.equal(gpr,window&&values.open_gpr&&values.reg_write&&rd<13&&on);assert.equal(assign,window&&values.open_assign&&(values.boot||on));laneCases++;}}
let rejected=0;for(const mutate of[c=>{c.blocks.find(v=>K(v.position)==='17,-16,-16').block.properties.facing='west';},c=>{c.blocks=c.blocks.filter(v=>K(v.position)!=='16,-7,-16');},c=>{c.blocks.find(v=>K(v.position)==='51,-19,-12').block.properties.facing='east';},c=>{c.blocks=c.blocks.filter(v=>K(v.position)!=='0,0,67');}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));rejected++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),result={status:'offline_connected_register_action_eligibility_checks_pass',...d.metrics,...structural,eligibility_truth_cases:truthCases,lane_mask_window_cases:laneCases,corruption_refusals:rejected,sources:{generator:sha('../../../../hardware/full-gpu-register-actions-qualified.mjs'),eligibility_generator:sha('../../../../hardware/full-gpu-register-action-eligibility.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,complete_gpu_layout:false,limits:['Settled literal/gate arithmetic and listed-contact/positive-capacity checks only, not native timing or arbitrary update ordering.','Upstream raw intents/fields/mask/window and downstream files are still separate physical integration.','Four new connections and inherited lane/window distribution are real geometry; labels do not imply external producers are implemented.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
