import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeQualifiedRegisterActions}from'../../../../hardware/full-gpu-register-actions-qualified.mjs';import{makeRegisterControllerActions}from'../../../../hardware/full-gpu-register-controller-actions.mjs';import{makeRegisterFourFilesWriteback}from'../../../../hardware/full-gpu-register-four-files-writeback.mjs';import{makeRegisterFourFilesBlockId}from'../../../../hardware/full-gpu-register-four-files-block-id.mjs';import{makeRegisterDataSelector}from'../../../../hardware/full-gpu-register-data-selector.mjs';import{makeWritebackMux}from'../../../../hardware/full-gpu-writeback.mjs';import{makeRegisterFourFilesDataControlV2}from'../../../../hardware/full-gpu-register-four-files-data-control-v2.mjs';import{makeRegisterFourFilesAddressedV2}from'../../../../hardware/full-gpu-register-four-files-addressed-v2.mjs';import{makeRegisterFileAddressStage}from'../../../../hardware/full-gpu-register-file-address-stage.mjs';import{makeRegisterControllerAddresses}from'../../../../hardware/full-gpu-register-controller-addresses.mjs';import{makeRegisterAddressSelect}from'../../../../hardware/full-gpu-register-address-select.mjs';import{makeRegisterSharedControl}from'../../../../hardware/full-gpu-register-shared-control.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';import{makeRegisterActions}from'../../../../hardware/full-gpu-register-actions.mjs';import{makeRegisterActionEligibility}from'../../../../hardware/full-gpu-register-action-eligibility.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeRegisterFourFilesBlockId();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0;
 for(const p of d.parents){const source=p.id==='registers'?makeRegisterFourFilesWriteback():makeRegisterDataSelector(),component=materializeInstance(source,{id:p.id,translation:p.origin});for(const v of component.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Changed frozen parent '+K(v.position));inherited++;}}
 for(const v of d.blocks){if(!['redstone_wire','repeater','comparator','redstone_torch','redstone_wall_torch'].some(id=>v.block.id==='minecraft:'+id))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.top-c.bottom)%4,1);for(let y=c.bottom;y<=c.top;y++){const id=y===c.top?'redstone_wire':(y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch';assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+id);}}

 let sourceSets=0;for(const col of d.columns){for(let y=col.bottom;y<col.top;y+=2){const p=P(col.x,y,col.z),got=[];for(const [f,delta]of Object.entries(D)){const q=add(p,neg(delta)),b=at(q)?.block;if(b?.id==='minecraft:redstone_wire'||['minecraft:repeater','minecraft:comparator'].includes(b?.id)&&b.properties.facing===f)got.push(K(q));}for(const[dy,id]of[[1,'minecraft:redstone_wire'],[-1,'minecraft:redstone_torch']]){const q=P(p.x,p.y+dy,p.z);if(at(q)?.block.id===id)got.push(K(q));}const expected=y===col.bottom?d.edges.filter(e=>K(e.to)===K(p)).map(e=>K(e.from)):[K(P(p.x,y-1,p.z))];if(y===col.top-1)expected.push(K(P(p.x,col.top,p.z)));assert.deepEqual(got.sort(),expected.sort(),'Foreign actual column source '+K(p));sourceSets++;}}
 for(const r of d.routes)for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){assert.deepEqual(add(p,D[v.block.properties.facing]),r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);}else assert.equal(v.block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 for(const c of d.connections){const r=at(c.normalizer);assert.equal(r.block.id,'minecraft:repeater');assert.deepEqual(add(c.normalizer,D[r.block.properties.facing]),c.destination,'No direct strength15 output at port');}const capacity=possibleStrengths(d);assert.equal(capacity.failed.length,0,'Actual dust capacity failure');assert.equal(d.connections.length,32);for(const c of d.connections){assert.equal(at(c.source)?.block.id,'minecraft:redstone_wire');assert.equal(at(c.destination)?.block.id,'minecraft:redstone_wire');}
 return{new_column_source_sets:sourceSets,preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_external_wire_contacts:contacts,actual_dust_capacity:capacity};}
const structural=check(d);let rejected=0;for(const mutate of[c=>{const r=c.blocks.find(v=>v.part==='block0_lane0_driver'&&v.block.id==='minecraft:repeater');r.block.properties.facing='east';},c=>{const col=c.columns[0];c.blocks=c.blocks.filter(v=>K(v.position)!==K(P(col.x,col.bottom+4,col.z)));},c=>{const r=c.routes.find(r=>r.name==='block1_lane1_feed');c.blocks=c.blocks.filter(v=>K(v.position)!==K(r.path[4]));},c=>{const r=c.connections[0];c.blocks.find(v=>K(v.position)===K(r.normalizer)).block.properties.facing='east';}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));rejected++;}
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),result={status:'offline_four_files_block_id_connections_author_checks_pass',...d.metrics,...structural,corruption_refusals:rejected,sources:{generator:sha('../../../../hardware/full-gpu-register-four-files-block-id.mjs'),parent:sha('../four-files-writeback-v1/design.json'),selector_source:sha('../data-selector/design.json'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,complete_gpu_layout:false,limits:['Listed contact/support/possible power checks only, not native timing, startup or full functional correctness.','Actual data/mask/block/clock producer distribution and full core interfaces still missing.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
