// Read-only recovery of actual repaired source cells; never regenerate stale parents.
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
import{inputs,active}from'../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},K=p=>`${p.x},${p.y},${p.z}`,P=(x,y,z)=>({x,y,z});
function bytes(n){const p=new URL(n,H),b=readFileSync(p);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=createHash('sha256').update(b).digest('hex');return b;}const read=n=>JSON.parse(bytes(n));
const meta=read('../memory/fabric-colocation-v2/cell-labels.json'),census=read('../memory/fabric-colocation-v2/boundary-census.json'),labelBytes=bytes('../memory/fabric-colocation-v2/cell-labels.u16le'),buffer=bytes('../memory/master-cold-compatible-v2/design.json');assert.equal(pins['artifacts/full-gpu-layout-v1/memory/master-cold-compatible-v2/design.json'],'364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f');
const labels=new Uint16Array(labelBytes.buffer,labelBytes.byteOffset,labelBytes.length/2),ids=new Set(meta.labels.flatMap((n,i)=>/^(loader|program)\//.test(n)?[i]:[]));
function scanBuffer(buffer,visit,expected=null){const marker=Buffer.from('"blocks"'),at=buffer.indexOf(marker);assert(at>=0);const start=buffer.indexOf(91,at+marker.length);let i=start+1,chunk=i,depth=0,quoted=false,escape=false,count=0,index=0;const accept=end=>{const str=buffer.subarray(chunk,end).toString();if(str.trim())for(const row of JSON.parse('['+str+']'))visit(row,index++);};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){accept(i);if(expected!==null)assert.equal(index,expected);return index;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0){if(++count===4096){accept(i);chunk=i+1;count=0;}}}throw Error('Unterminated block stream');}
const own=[],selected=new Map(),buckets=new Set(),bucket=p=>`${Math.floor(p.x/16)},${Math.floor(p.y/16)},${Math.floor(p.z/16)}`,groupCounts={};
scanBuffer(buffer,(v,i)=>{if(!ids.has(labels[i]))return;const group=meta.labels[labels[i]],r={...v,group};own.push(r);selected.set(K(v.position),r);groupCounts[group]=(groupCounts[group]??0)+1;for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)buckets.add(bucket(P(v.position.x+16*x,v.position.y+16*y,v.position.z+16*z)));});assert.equal(own.length,346334);console.log(JSON.stringify({selected:own.length,groups:Object.keys(groupCounts).length}));
const offsets=[];for(let x=-3;x<=3;x++)for(let y=-3;y<=3;y++)for(let z=-3;z<=3;z++)if(Math.abs(x)+Math.abs(y)+Math.abs(z)<=3)offsets.push(P(x,y,z));
const world=new Map(own.map(r=>[K(r.position),r.block])),context=[],groups=new Map(own.map(r=>[K(r.position),r.group]));
scanBuffer(buffer,(v,i)=>{if(ids.has(labels[i])||!buckets.has(bucket(v.position)))return;if(!offsets.some(o=>selected.has(K(P(v.position.x+o.x,v.position.y+o.y,v.position.z+o.z)))))return;world.set(K(v.position),v.block);groups.set(K(v.position),meta.labels[labels[i]]);context.push({...v,group:meta.labels[labels[i]]});});console.log(JSON.stringify({actual_foreign_halo:context.length}));
// External master routes are absent from the memory design; bind the exact original selected world.
const cfg=read('../dispatch-global-colocation-v1/selected-config.json'),master=[];
const paths=[...new Set(cfg.instances.filter(c=>c.name!=='memory').map(c=>c.path))];
for(const path of paths){const data=bytes('../../../'+path),frames=cfg.instances.filter(c=>c.path===path);for(const c of frames)assert.equal(pins[path],c.sha256);
 const count=scanBuffer(data,v=>{for(const c of frames){const p=P(v.position.x+c.translation.x,v.position.y+c.translation.y,v.position.z+c.translation.z);if(!buckets.has(bucket(p))||!offsets.some(o=>selected.has(K(P(p.x+o.x,p.y+o.y,p.z+o.z)))))continue;const k=K(p);assert(!world.has(k),'Foreign overlap '+c.name+' '+k);world.set(k,v.block);groups.set(k,'master/'+c.name);const row={position:p,block:v.block,group:'master/'+c.name};context.push(row);master.push(row);}});console.log(JSON.stringify({foreign_source:path,scanned:count,retained_master:master.length}));
}
const cuts=[],groupCuts=[],internalCounts={},stores=[],R='minecraft:repeater',DIR={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)};let activeReceivers=0,internalInputs=0;
for(const [k,b]of world){if(!active(b))continue;const target=selected.get(k),p=P(...k.split(',').map(Number));if(!target&&!offsets.some(o=>Math.abs(o.x)+Math.abs(o.y)+Math.abs(o.z)<=2&&selected.has(K(P(p.x+o.x,p.y+o.y,p.z+o.z)))))continue;if(target)activeReceivers++;for(const q of inputs(world,p)){const source=selected.get(K(q));if(!source&&!target)continue;const row={source:q,target:p,source_group:groups.get(K(q)),target_group:groups.get(k),source_block:world.get(K(q)),target_block:b};if(source&&target){internalInputs++;if(source.group===target.group)internalCounts[source.group]=(internalCounts[source.group]??0)+1;else groupCuts.push(row);}else cuts.push({...row,direction:source?'outgoing':'incoming'});}
 if(target&&b.id===R){const d=DIR[b.properties.facing],locks=[];for(const o of Object.values(DIR)){if(o.x*d.x+o.z*d.z)continue;const q=P(p.x+o.x,p.y,p.z+o.z),other=world.get(K(q));if([R,'minecraft:comparator'].includes(other?.id)){const v=DIR[other.properties.facing];if(K(P(q.x+v.x,q.y,q.z+v.z))===k)locks.push(q);}}if(locks.length)stores.push({position:p,block:b,locks,group:target.group});}
}
const declarations=read('../memory/fabric-colocation-v2/declared-connections.json'),image=read('../initial-loader-warm-drain-v3/image-source-map.json'),program=read('../memory/program-quiet-v1/design.json');assert.equal(image.program.length,4096);assert.equal(new Set(image.program.map(c=>c.address+':'+c.bit)).size,4096);assert(image.program.every(c=>Number.isInteger(c.address)&&c.address>=0&&c.address<256&&Number.isInteger(c.bit)&&c.bit>=0&&c.bit<16));for(const c of image.program){const v=selected.get(K(c.position));assert(v?.group==='program/preserved_program');assert.equal(v.block.id,c.value?'minecraft:redstone_block':'minecraft:light_gray_concrete');}
const repairs=declarations.later_state_changes.filter(v=>['program','loader'].includes(v.declared_by));assert.equal(repairs.length,4);for(const c of repairs)assert.deepEqual(selected.get(K(c.position)).block,c.current);
assert.equal(stores.length,25);const bodyGroups=['loader/loader_logic_parent','loader/load_owner','loader/load_owner_feedback_set','loader/load_owner_feedback_clear','loader/load_request_switch','loader/boot_switch','loader/image_verified_switch'];const bodySet=new Set(bodyGroups),control=own.filter(v=>bodySet.has(v.group)),controlCuts=[...groupCuts,...cuts].filter(v=>bodySet.has(v.source_group)!==bodySet.has(v.target_group));
const cold=read('../memory/cold-extender-removal-v1/delta.json'),removedProgram=cold.changes.filter(v=>v.instance==='program');assert.equal(removedProgram.length,1);assert.deepEqual(selected.get(K(removedProgram[0].position)).block,removedProgram[0].after);bytes('../memory/master-cold-compatible-v2/source-manifest.json');
bytes('extract.mjs');bytes('../memory/fabric-colocation-v2/cut-inputs.mjs');bytes('../control-commit-v2/route.mjs');
const metrics={source_memory_cells:labels.length,selected_cells:own.length,selected_groups:Object.keys(groupCounts).length,program_cells:groupCounts['program/preserved_program'],loader_cells:own.length-groupCounts['program/preserved_program'],program_source_bits:image.program.length,side_locked_payload_stores:stores.length,historical_protocol_states:3,retained_protocol_states:2,program_active_retained:true,program_reset_extender_retained:false,loader_owner_retained:true,foreign_context_cells:context.length,master_foreign_context_cells:master.length,active_receivers:activeReceivers,within_selected_effective_inputs:internalInputs,external_effective_cuts:cuts.length,internal_group_effective_cuts:groupCuts.length,loader_control_body_cells:control.length,loader_control_effective_cuts:controlCuts.length,current_program_corrections:repairs.length};
const report={status:'actual_repaired_loader_program_full_boundary_inventory',metrics,groupCounts,cold_extender_program_change:removedProgram,groups:census.groups.filter(v=>ids.has(meta.labels.indexOf(v.label))),repairs,program_storage:{side_locked_payload:stores,protocol_state_note:'Program ACTIVE survives. Original reset extender is deliberately removed under held cold; its downstream timing chain remains. Loader SR owner survives. Three historical protocol states are inventoried, only two retained.',historical_states:3,retained_protocol_states:2},source_sha256:pins,limits:['Exact old selected-source inventory only, not a compact placement or connectivity claim.','DCR/panel and all data bank/fabric bodies remain outside this ownership. Global quiet output/tree is assigned to a future separate extraction in this family, not included in these 346334 cells.','Complete effective cuts include both directions, no net-label exemptions. Original source behavior and new routes still require classification before relocation.','State timing, cold/warm convergence, event behavior and native acceptance remain open.'],native_acceptance:false};
writeFileSync(new URL('inventory.json',H),JSON.stringify(report,null,2)+'\n');writeFileSync(new URL('reference-scope.json',H),JSON.stringify({blocks:own,foreign_context:context,source_sha256:pins})+'\n');writeFileSync(new URL('actual-cuts.json',H),JSON.stringify({external:cuts,between_groups:groupCuts,loader_control:controlCuts,source_sha256:pins},null,2)+'\n');writeFileSync(new URL('loader-control-body.json',H),JSON.stringify({blocks:control,groups:bodyGroups,source_sha256:pins})+'\n');writeFileSync(new URL('interfaces.json',H),JSON.stringify({loader:declarations.loader,program_ports:program.ports,program_translation:P(-600,11,1100),program_sources:image.program,source_sha256:pins},null,2)+'\n');console.log(JSON.stringify(metrics));
