// Fixed local owner/commit control product matrix; all gates and ORs are blocks.
import assert from'node:assert/strict';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,F={east:'west',west:'east',north:'south',south:'north'};
export function makeMatrix(definition){const {inputs:INPUTS,outputs:OUTPUTS,products:terms}=definition;const merged=new Map();for(const term of terms){const k=JSON.stringify(Object.entries(term.literals).sort());if(!merged.has(k))merged.set(k,{literals:term.literals,outputs:[]});merged.get(k).outputs.push(term.out);}const map=new Map(),edges=[],columns=[],products=[],t=[...merged.values()],last=1+4*(t.length-1),top=last+3,usedX=new Set(),outX=OUTPUTS.map(name=>{let x=6*(1+Math.max(...t.filter(q=>q.outputs.includes(name)).flatMap(q=>Object.keys(q.literals).map(n=>INPUTS.indexOf(n)))))+14;while(usedX.has(x)||usedX.has(x-1)||usedX.has(x+1))x+=4;usedX.add(x);return x;});let part='';const put=(p,id,properties)=>{const b={position:p,block:{id:'minecraft:'+id,...properties?{properties}:{}},part};if(map.has(K(p)))assert.deepEqual(map.get(K(p)).block,b.block);else map.set(K(p),b);},solid=p=>put(p,'light_gray_concrete'),dev=(p,id,properties)=>{solid(P(p.x,p.y-1,p.z));put(p,id,properties);},wire=p=>dev(p,'redstone_wire'),rep=(p,dir)=>dev(p,'repeater',{facing:F[dir],delay:'1'}),edge=(a,b)=>edges.push({from:a,to:b});
for(const[j,name]of INPUTS.entries()){const x=6+6*j;part='input_'+name;for(let y=-3;y<=last;y++)put(P(x,y,-5),(y+3)%2===0?'light_gray_concrete':'redstone_torch');wire(P(x-2,-3,-5));rep(P(x-1,-3,-5),'east');edge(P(x-2,-3,-5),P(x-1,-3,-5));edge(P(x-1,-3,-5),P(x,-3,-5));columns.push({name,x,z:-5,bottom:-3,top:last});}
for(const[j,name]of OUTPUTS.entries()){const x=outX[j];part='output_'+name;for(let y=1;y<top;y++)put(P(x,y,3),y%2?'light_gray_concrete':'redstone_torch');solid(P(x,0,3));put(P(x,top,3),'redstone_torch');rep(P(x,top,4),'south');wire(P(x,top,5));edge(P(x,top,3),P(x,top,4));edge(P(x,top,4),P(x,top,5));columns.push({name,x,z:3,bottom:1,top});}
for(const[row,term]of t.entries()){const y=1+4*row,first=Math.min(...Object.keys(term.literals).map(n=>INPUTS.indexOf(n))),end=Math.max(...Object.keys(term.literals).map(n=>INPUTS.indexOf(n))),sx=6+6*first;part='product_'+row;dev(P(sx-4,y,0),'redstone_block');rep(P(sx-3,y,0),'east');edge(P(sx-4,y,0),P(sx-3,y,0));for(let x=sx-2;x<sx;x++){wire(P(x,y,0));edge(P(x-1,y,0),P(x,y,0));}const gates=[];
for(let j=first;j<=end;j++){const name=INPUTS[j],x=6+6*j,want=term.literals[name];if(want!==undefined){rep(P(x,y,0),'east');dev(P(x+1,y,0),'comparator',{facing:'west',mode:'subtract'});wire(P(x+2,y,0));rep(P(x+3,y,0),'east');wire(P(x+4,y,0));wire(P(x+5,y,0));if(want){put(P(x,y,-4),'redstone_wall_torch',{facing:'south'});wire(P(x,y,-3));}else{wire(P(x,y,-4));rep(P(x,y,-3),'south');}wire(P(x,y,-2));wire(P(x+1,y,-2));rep(P(x+1,y,-1),'south');for(const[a,b]of[[P(x,y,-5),P(x,y,-4)],[P(x,y,-4),P(x,y,-3)],[P(x,y,-3),P(x,y,-2)],[P(x,y,-2),P(x+1,y,-2)],[P(x+1,y,-2),P(x+1,y,-1)],[P(x+1,y,-1),P(x+1,y,0)]])edge(a,b);gates.push({name,want,comparator:P(x+1,y,0),mask:P(x+1,y,-1)});}else for(let q=0;q<6;q++){if(q===0)rep(P(x,y,0),'east');else wire(P(x+q,y,0));}for(let q=0;q<6;q++)edge(P(x+q-1,y,0),P(x+q,y,0));}
const start=6*(end+1)+6,targets=term.outputs.map(n=>outX[OUTPUTS.indexOf(n)]),target=Math.max(...targets);for(let x=start;x<=target;x++){if((x-start)%10===0&&x<target&&!targets.includes(x))rep(P(x,y,0),'east');else wire(P(x,y,0));edge(P(x-1,y,0),P(x,y,0));}for(const x of targets){wire(P(x,y,1));rep(P(x,y,2),'south');edge(P(x,y,0),P(x,y,1));edge(P(x,y,1),P(x,y,2));edge(P(x,y,2),P(x,y,3));}products.push({...term,row,y,gates,injections:targets.map(x=>P(x,y,3))});}
const port=(direction,p)=>({direction,width:1,polarity:'active_high',bit_order:'LSB_first',bits:[{bit:0,position:p}]}),ports={};for(const[j,n]of INPUTS.entries())ports[n]=port('input',P(4+6*j,-3,-5));for(const[j,n]of OUTPUTS.entries())ports[n]=port('output',P(outX[j],top,5));const blocks=[...map.values()],box={from:{},to:{}};for(const k of['x','y','z']){box.from[k]=Math.min(...blocks.map(v=>v.position[k]));box.to[k]=Math.max(...blocks.map(v=>v.position[k]));}return{status:'physical_lsu_boolean_matrix',definition,blocks,ports,edges,columns,products,box,metrics:{blocks:blocks.length,products:t.length,inputs:INPUTS.length,outputs:OUTPUTS.length},native_acceptance:false};}
