// Independent bounded review: direct source loading, actual cold context,
// complete input differential, and a separate directed-network strength solver.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {inputs,active} from '../memory/fabric-colocation-v2/cut-inputs.mjs';
const H=new URL('./',import.meta.url),ROOT=new URL('../../../',H),pins={},P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,A=(p,q)=>P(p.x+q.x,p.y+q.y,p.z+q.z),W='minecraft:redstone_wire',R='minecraft:repeater',C='minecraft:comparator',T='minecraft:redstone_torch',WT='minecraft:redstone_wall_torch',D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},solid=b=>b?.id.endsWith('_concrete');
function bytes(n,expected){const p=new URL(n,H),b=readFileSync(p),h=createHash('sha256').update(b).digest('hex');if(expected)assert.equal(h,expected,n);pins[fileURLToPath(p).slice(fileURLToPath(ROOT).length)]=h;return b;}
const read=(n,h)=>JSON.parse(bytes(n,h)),write=(n,v)=>writeFileSync(new URL(n,H),JSON.stringify(v,null,2)+'\n');
function insert(map,rows,{same=false}={}){for(const r of rows){const k=K(r.position);if(map.has(k)){assert(same,'Duplicate cell '+k);assert.deepEqual(map.get(k),r.block);}else map.set(k,r.block);}}
function scanBlocks(buffer,visit){const at=buffer.indexOf(Buffer.from('"blocks"'));assert(at>=0);let i=buffer.indexOf(91,at+8)+1,start=i,depth=0,quoted=false,escape=false,batch=0,count=0;const flush=end=>{const part=buffer.subarray(start,end).toString();if(part.trim())for(const r of JSON.parse('['+part+']')){visit(r);count++;}};for(;i<buffer.length;i++){const c=buffer[i];if(quoted){if(escape)escape=false;else if(c===92)escape=true;else if(c===34)quoted=false;continue;}if(c===34){quoted=true;continue;}if(c===93&&depth===0){flush(i);return count;}if(c===123||c===91)depth++;else if(c===125||c===93)depth--;else if(c===44&&depth===0&&++batch===4096){flush(i);start=i+1;batch=0;}}throw Error('Unterminated blocks');}
function cone(world,end,root){const seen=new Map(),queue=[end];for(let i=0;i<queue.length;i++){const p=queue[i],k=K(p);if(seen.has(k))continue;assert(active(world.get(k)),'Missing actual dependency '+k);seen.set(k,p);if(k!==K(root))queue.push(...inputs(world,p));}assert(seen.has(K(root)),'Source absent from cone');return [...seen.values()];}
function network(world,positions,root){
 const index=new Map(positions.map((p,i)=>[K(p),i])),rootIndex=index.get(K(root));assert.notEqual(rootIndex,undefined);
 const rows=positions.map(p=>({p,b:world.get(K(p))})),incoming=positions.map(()=>[]),outgoing=positions.map(()=>[]);let edges=0;
 for(let i=0;i<rows.length;i++){assert([W,R,T,WT].includes(rows[i].b.id),'Unexpected transport device '+rows[i].b.id+' '+K(rows[i].p));if(i===rootIndex)continue;const deps=inputs(world,rows[i].p);if(rows[i].b.id===R){const v=D[rows[i].b.properties.facing];assert(deps.every(q=>(q.x-rows[i].p.x)*v.x+(q.z-rows[i].p.z)*v.z<0),'Unmodeled side lock');}for(const q of deps){const j=index.get(K(q));assert.notEqual(j,undefined,'Foreign source '+K(q));incoming[i].push(j);outgoing[j].push(i);edges++;}}
 const visited=new Uint8Array(rows.length),order=[];for(let i=0;i<rows.length;i++)if(!visited[i]){visited[i]=1;const stack=[[i,0]];while(stack.length){const r=stack.at(-1);if(r[1]<outgoing[r[0]].length){const j=outgoing[r[0]][r[1]++];if(!visited[j]){visited[j]=1;stack.push([j,0]);}}else{order.push(r[0]);stack.pop();}}}
 const assigned=new Uint8Array(rows.length);let components=0,wireLoops=0;for(let n=order.length-1;n>=0;n--){const i=order[n];if(assigned[i])continue;const members=[i];assigned[i]=1;for(let at=0;at<members.length;at++)for(const j of incoming[members[at]])if(!assigned[j]){assigned[j]=1;members.push(j);}components++;if(members.length>1||outgoing[i].includes(i)){assert(members.every(j=>rows[j].b.id===W),'Nonwire transport feedback');wireLoops++;}}
 function power(strength){const values=new Uint8Array(rows.length),waiting=new Uint8Array(rows.length).fill(1),queue=rows.map((_,i)=>i);values[rootIndex]=strength;let events=0;for(let at=0;at<queue.length;at++){const i=queue[at];waiting[i]=0;if(i===rootIndex)continue;assert(++events<1000000,'Nonconvergent network');let value=0;for(const j of incoming[i])value=Math.max(value,values[j]-(rows[i].b.id===W&&rows[j].b.id===W?1:0));if(rows[i].b.id===R)value=value>0?15:0;else if([T,WT].includes(rows[i].b.id))value=value>0?0:15;if(value!==values[i]){values[i]=value;for(const j of outgoing[i])if(!waiting[j]){waiting[j]=1;queue.push(j);}}}return {values,get:p=>values[index.get(K(p))]??0,events};}
 return {power,metrics:{devices:rows.length,edges,components,torch_vertices:rows.filter(r=>[T,WT].includes(r.b.id)).length,wire_conductance_components:wireLoops,nonwire_feedback_components:0},minimumRear(powers,subset){return Math.min(...rows.flatMap((r,i)=>r.b.id===R&&(!subset||subset.has(K(r.p)))?[Math.max(0,...incoming[i].map(j=>powers.values[j]))]:[]));}};
}
// Recover old routing with references only to discover the required neighborhood.
const parent=read('../dispatch-global-colocation-v8-dcr-cold-v1/connected-candidate.json'),ledger=read('../dispatch-global-colocation-v8-dcr-cold-v1/remaining-ledger.json'),bindings=read('../dispatch-external-bindings-v1/bindings.json'),oldRoutes=read('../master-loader-control-routes-v1/design.json'),scope=read('../dispatch-global-colocation-v1/reference-scope.json'),oldLoader=read('../loader-program-colocation-v1/service-quiet-inventory-v1/reference-scope.json');
const b=bindings.incoming.find(r=>r.transfer_index===291);assert(b);assert.equal(ledger.transfers[291].status,'external_source_transfer_pending');assert.equal(b.old_connection.name,'global_channel_quiet');
const originalRoot=P(936,68,-375),originalExport=P(1024,68,-375),originalTarget=P(-1100,-34,550),originalArrival=P(-1101,-34,550);
assert.deepEqual(b.old_connection.source,originalExport);assert.deepEqual(b.old_connection.destination,originalTarget);assert.deepEqual(b.old_connection.normalizer,originalArrival);
const discovery=new Map();insert(discovery,[...scope.blocks,...scope.foreign_context],{same:true});insert(discovery,oldLoader.blocks.filter(r=>r.group==='current/quiet_output_export'||K(r.position)===K(originalRoot)),{same:true});insert(discovery,oldRoutes.blocks,{same:true});
const candidate=cone(discovery,originalTarget,originalRoot),expectedOld=new Set(candidate.map(K)),want=new Set();for(const p of candidate)for(let dx=-3;dx<=3;dx++)for(let dy=-3;dy<=3;dy++)for(let dz=-3;dz<=3;dz++)if(Math.abs(dx)+Math.abs(dy)+Math.abs(dz)<=3)want.add(K(P(p.x+dx,p.y+dy,p.z+dz)));
const actualOld=new Map();const scanned=scanBlocks(bytes('../memory/master-cold-compatible-v2/design.json','364c11e6e3c7e6deafbd8f279b1e95d6baed949a64a2e4f2cb4592c1bca1207f'),r=>{if(want.has(K(r.position)))insert(actualOld,[r]);});
const selected=read('../dispatch-global-colocation-v1/selected-config.json'),globalInstance=selected.instances.find(r=>r.name==='global'),globalBody=read('../global-command-assembly-v3/design.json',globalInstance.sha256);
insert(actualOld,globalBody.blocks.map(r=>({position:A(r.position,globalInstance.translation),block:r.block})).filter(r=>want.has(K(r.position))),{same:true});
insert(actualOld,oldRoutes.blocks.filter(r=>want.has(K(r.position))),{same:true});
const oldCone=cone(actualOld,originalTarget,originalRoot);assert.deepEqual(oldCone.map(K).sort(),[...expectedOld].sort(),'Actual cold source differs from discovered original cone');assert(oldCone.some(p=>K(p)===K(originalExport)));for(const p of oldCone){assert.deepEqual(actualOld.get(K(p)),discovery.get(K(p)));if(K(p)!==K(originalRoot))assert.deepEqual(inputs(actualOld,p).map(K).sort(),inputs(discovery,p).map(K).sort());}
const oldNet=network(actualOld,oldCone,originalRoot),originalCases=[0,15].map(strength=>{const v=oldNet.power(strength);assert.equal(v.get(originalTarget),strength);return {source:strength,export:v.get(originalExport),arrival:v.get(originalArrival),receiver:v.get(originalTarget),minimum_repeater_rear:strength?oldNet.minimumRear(v):null};});
// Rebuild the accepted frame without calling the author's composition loader.
const memory=read('../memory/fabric-colocation-v2/channel3-write-data-design.json'),panels=read('../loader-bank-panels-v1/delta.json'),program=read('../program-service-composition-v1/new-program-obstacles.json'),programQuiet=read('../program-service-composition-v1/cable-delta.json'),masks=read('../loader-program-colocation-v1/service-mask-memory-composition-v1/composed-delta.json'),address=read('../memory/fabric-colocation-v2/channel0-address-delta.json'),owner=read('../loader-program-colocation-v1/service-owner-open-delivery-v1/delta.json'),payload=read('../loader-program-colocation-v1/service-payload-open-delivery-v1/delta.json');
const baseRows=[...memory.blocks,...panels.blocks,...program.blocks,...programQuiet.blocks,...masks.placed_loader,...masks.placed_masks,...masks.new_cells,...address.blocks,...owner.new_cells,...payload.new_cells],base=new Map();insert(base,baseRows);for(const r of masks.replacements){assert.deepEqual(base.get(K(r.position)),r.before);base.set(K(r.position),r.after);}assert.equal(base.size,1752880);
const placement=read('../dispatcher-service-colocation-v1/placement.json','c5aff38f6c938a1a6f033ea531f4dfabdc25475bbf48d2573d24b6488599b3d5'),delta=read('../dispatcher-service-colocation-v1/delta.json','e92925dde9b91d7fa9dc4ca84bcf34dbab2d429487dee7eacb0ff2e76f9af6c6'),local=new Map(parent.blocks.map(r=>[K(r.position),r.block])),world=new Map(base),placed=new Map(placement.blocks.map(r=>[K(r.position),r]));
assert.equal(parent.blocks.length,202786);assert.equal(placed.size,202786);assert.equal(delta.new_cells.length,860);assert.equal(delta.connections.length,1);insert(world,placement.blocks);insert(world,delta.new_cells);assert.equal(world.size,1956526);
const seenLocal=new Set();for(const r of placement.blocks){assert(!seenLocal.has(K(r.local_position)));seenLocal.add(K(r.local_position));assert.deepEqual(r.block,local.get(K(r.local_position)));assert.deepEqual(r.position,A(r.local_position,placement.translation));}assert.equal(seenLocal.size,local.size);
const c=delta.connections[0],root=P(252,36,-171),target=P(268,114,-576),arrival=P(268,114,-577);assert.deepEqual(c.root,root);assert.deepEqual(c.destination,target);assert.deepEqual(c.normalizer,arrival);
const sourceMap=read('../loader-program-colocation-v1/service-quiet-colocation-v1/endpoint-map.json').mapping.find(r=>K(r.original)===K(originalRoot));assert(sourceMap);assert.deepEqual(A(sourceMap.current,P(-160,-32,-176)),root);assert.deepEqual(sourceMap.block,world.get(K(root)));assert.deepEqual(sourceMap.block,actualOld.get(K(originalRoot)));
const receiverIdentity=parent.blocks.find(r=>r.original_position&&K(r.original_position)===K(originalTarget));assert(receiverIdentity);assert.equal(receiverIdentity.body,'global/sample0');assert.deepEqual(A(receiverIdentity.position,placement.translation),target);assert.deepEqual(receiverIdentity.block,actualOld.get(K(originalTarget)));
const edges=new Set();assert.equal(delta.routes.length,1);const path=delta.routes[0].path;assert.deepEqual(path[0],root);assert.deepEqual(path.at(-1),target);for(let i=1;i<path.length;i++){assert(inputs(world,path[i]).some(p=>K(p)===K(path[i-1])));edges.add(K(path[i-1])+'>'+K(path[i]));edges.add(K(path[i])+'>'+K(path[i-1]));}
const newKeys=new Set(delta.new_cells.filter(r=>active(r.block)).map(r=>K(r.position)));let receivers=0,supports=0,actualInputs=0,priorInputs=0,translatedInputs=0,cableInputs=0,changedOldReceivers=0;
for(const [key,block]of world){const [x,y,z]=key.split(',').map(Number),p=P(x,y,z);let support;if(block.id===WT)support=A(p,D[block.properties.facing]);else if([W,R,C,T,'minecraft:lever'].includes(block.id))support=P(x,y-1,z);if(support){assert(solid(world.get(K(support))),'Missing support '+key);supports++;}if(!active(block))continue;receivers++;const actual=inputs(world,p).map(K).sort();actualInputs+=actual.length;let expected;
 if(base.has(key)){expected=inputs(base,p).map(K);priorInputs+=expected.length;}
 else if(placed.has(key)){const row=placed.get(key);expected=inputs(local,row.local_position).map(q=>K(A(q,placement.translation)));translatedInputs+=expected.length;}
 else {assert(newKeys.has(key));for(const q of actual)assert(edges.has(q+'>'+key),'Undeclared cable contact');cableInputs+=actual.length;continue;}
 if(key===K(target)){expected.push(K(arrival));changedOldReceivers++;}assert.deepEqual(actual,[...new Set(expected)].sort(),'Retained input changed '+key);
}
assert.equal(changedOldReceivers,1);
const currentCone=cone(world,target,root),currentNet=network(world,currentCone,root);assert.equal(currentCone.length,432);assert(currentCone.every(p=>K(p)===K(root)||K(p)===K(target)||newKeys.has(K(p))));const strengthCases=[];let high;
for(let strength=0;strength<=15;strength++){const v=currentNet.power(strength),out=strength?15:0;assert.equal(v.get(arrival),out);assert.equal(v.get(target),out);strengthCases.push({source:strength,arrival:v.get(arrival),receiver:v.get(target)});if(strength===15)high=v;}
const minimum=currentNet.minimumRear(high,newKeys);assert.equal(minimum,5);
const negatives=[],opposite={east:'west',west:'east',north:'south',south:'north'};
for(const r of delta.new_cells.filter(r=>r.block.id===R)){
 const key=K(r.position);world.set(key,{...r.block,properties:{...r.block.properties,facing:opposite[r.block.properties.facing]}});let rejected=false;try{const changed=cone(world,target,root),n=network(world,changed,root);rejected=n.power(15).get(target)!==15;}catch{rejected=true;}assert(rejected,'Reversed repeater not rejected');world.set(key,r.block);negatives.push({kind:'reverse_actual_repeater',position:r.position});
 const support=P(r.position.x,r.position.y-1,r.position.z),prior=world.get(K(support));world.delete(K(support));assert(!solid(world.get(K(support))));world.set(K(support),prior);negatives.push({kind:'delete_actual_repeater_support',position:support});
}
const oldCut=ledger.effective_cut_ledger.filter(r=>K(r.source)===K(originalArrival)&&K(r.target)===K(originalTarget));assert.equal(oldCut.length,1);const pending=ledger.transfers.filter(r=>r.status==='external_source_transfer_pending');assert.equal(pending.length,18);
bytes('review.mjs');bytes('../memory/fabric-colocation-v2/cut-inputs.mjs');
write('receipt.json',{status:'passed_independent_dispatcher_translation_and_actual_quiet_delivery',metrics:{accepted_base_cells:base.size,translated_cells:placed.size,cable_cells:delta.new_cells.length,total_cells:world.size,receivers,supports,actual_inputs:actualInputs,preserved_base_inputs:priorInputs,preserved_dispatch_inputs:translatedInputs,new_cable_inputs:cableInputs,changed_existing_receivers:changedOldReceivers,path_vertices:path.length,source_strength_cases:16,original_binary_cases:2,current_minimum_repeater_rear:minimum,actual_block_mutations:negatives.length},original:{cold_cells_streamed:scanned,actual_context_cells:actualOld.size,root:originalRoot,export:originalExport,arrival:originalArrival,receiver:originalTarget,graph:oldNet.metrics,cases:originalCases},current:{root,receiver:target,arrival,graph:currentNet.metrics,cases:strengthCases},cut_reconciliation:{only_closed_transfer:291,original_effective_cut:oldCut[0],current_source:root,current_arrival:arrival,current_receiver:target,other18minus1incoming_pending:17,direct_foreign_boundaries_unchanged:true,witness_inputs_bound:16,witness_inputs_pending:21},negative_cases:negatives,source_sha256:pins,limits:['Independent orchestration and numeric/SCC solver; shared normalized physical-input rule helper is a conditional model, not independent Minecraft physics.','Only transport from the real held quiet-matrix output to the actual translated sampler input is proved. All remaining witness producers and retained/sequential sampler state are outside this review.','Only transfer291 has demonstrated delivery; no other foreign cut or complete-machine timing/physics claim.','Exact accepted geometry only. The4206 partial address reservation is outside this receipt and remains uncredited.']});
console.log(JSON.stringify({status:'passed',cells:world.size,receivers,supports,actualInputs,old_graph:oldNet.metrics,current_graph:currentNet.metrics,minimum,mutations:negatives.length}));
