import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{makeDispatchAdmissionSignals}from'../../../../hardware/full-gpu-dispatch-admission-signals.mjs';import{makeDispatchAdmissionInputs}from'../../../../hardware/full-gpu-dispatch-admission-inputs.mjs';import{makeDispatchOutputFeedback}from'../../../../hardware/full-gpu-dispatch-output-feedback.mjs';import{makeSignalDescent}from'../../../../hardware/full-gpu-signal-descent.mjs';import{materializeInstance}from'../../../../hardware/gpu-layout-assembly.mjs';import{possibleStrengths}from'../../register-sequencer-v1/connected-controller/check-strength-independent.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');const d=makeDispatchAdmissionSignals();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));const parents=d.parents.map(p=>materializeInstance(makeDispatchAdmissionInputs(),{id:p.id,translation:p.origin}));
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to))),parentIds=new Set(d.parents.map(v=>v.id));assert.equal(m.size,d.blocks.length);let inherited=0,supports=0,contacts=0,directions=0;for(const p of parents)for(const v of p.blocks){assert.deepEqual(at(v.position)?.block,v.block);inherited++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.output_y-c.bottom)%4,1);for(let y=c.bottom;y<c.output_y;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.output_y,c.z))?.block.id,'minecraft:redstone_wire');}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const dir of dirs)for(const dy of[-1,0,1]){const q=add(v.position,dir);q.y+=dy;const o=at(q);if(!o||o.block.id.endsWith('_concrete'))continue;if(parentIds.has(v.part)&&o.part===v.part)continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...q,y:v.position.y}))continue;assert(allowed.has(pair(v.position,q)),'Foreign '+pair(v.position,q));contacts++;}
 for(const v of d.blocks.filter(v=>!parentIds.has(v.part)&&v.block.id==='minecraft:repeater')){const dir=D[v.block.properties.facing],rear=add(v.position,neg(dir)),out=add(v.position,dir);assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Direction '+K(v.position));for(const s of dirs.filter(s=>s.x*dir.x+s.z*dir.z===0)){const o=at(add(v.position,s));assert(!o||o.block.id.endsWith('_concrete'),'Foreign side '+K(v.position));}directions++;}
 const base=parents[0],feedback=makeDispatchOutputFeedback();assert.equal(d.connections.length,7);const names=['owner','done','start0','reset0','start1','reset1'],oldNames=['owner_state','done_state','core0_start_state','core0_reset_state','core1_start_state','core1_reset_state'];for(const[bit,name]of names.entries()){const c=d.connections.find(c=>c.name===name);assert.deepEqual(c.source,base.ports.output_state.bits[bit].position);assert.deepEqual(c.destination,base.ports['admission_'+name].bits[0].position);const path=feedback.routes.find(r=>r.name===oldNames[bit]+'_depart').path.map(p=>P(p.x+160,p.y,p.z-32));assert(path.some(p=>K(p)===K(c.tap)));assert.equal(at(c.tap).block.id,'minecraft:redstone_wire');assert(!d.ports['admission_'+name]);}
 const c=d.connections.find(c=>c.name==='capture');assert.deepEqual(c.source,base.ports.sequence_capture_payload.bits[0].position);assert.deepEqual(c.destination,base.ports.admission_capture.bits[0].position);assert(!d.ports.admission_capture);
 const power=possibleStrengths(d);assert.deepEqual(power.failed,[]);return{preserved_parent_cells:inherited,support_checks:supports,new_wire_contact_checks:contacts,new_directed_repeaters:directions,actual_admission_control_arrivals:7,possible_strength:power};}

const checks=check(d);let negatives=0;for(const mutate of[c=>{const r=c.routes.find(r=>r.name==='owner_depart');const q=r.path[r.refresh_indices[0]];c.blocks.find(v=>K(v.position)===K(q)).block.properties.facing='west';},c=>{c.connections.find(c=>c.name==='owner').source=c.connections.find(c=>c.name==='done').source;},c=>{const q=c.columns[0];c.blocks=c.blocks.filter(v=>K(v.position)!==K(P(q.x,q.bottom+2,q.z)));}]){const c=structuredClone(d);mutate(c);assert.throws(()=>check(c));negatives++;}

const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex'),r={status:'offline_dispatch_actual_admission_control_sources_pass',...d.metrics,...checks,corruption_refusals:negatives,sources:{generator:sha('../../../../hardware/full-gpu-dispatch-admission-signals.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_calls:0,world_mutations:0,native_acceptance:false,complete_gpu_layout:false,limits:d.missing};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({...r,possible_strength:{...r.possible_strength,taps:undefined}}));
