import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{makeRegisterSequencer}from'../../../../hardware/full-gpu-register-sequencer.mjs';
import{makeRegisterMicrodecode}from'../../../../hardware/full-gpu-register-microdecode.mjs';import{makeRegisterStateFeedback}from'../../../../hardware/full-gpu-register-state-feedback.mjs';
const P=(x,y,z)=>({x,y,z}),K=p=>`${p.x},${p.y},${p.z}`,D={west:P(1,0,0),east:P(-1,0,0),north:P(0,0,1),south:P(0,0,-1)},dirs=Object.values(D),add=(a,b)=>P(a.x+b.x,a.y+b.y,a.z+b.z),neg=a=>P(-a.x,-a.y,-a.z),pair=(a,b)=>[K(a),K(b)].sort().join('|');
const d=makeRegisterSequencer();assert.deepEqual(d,JSON.parse(readFileSync(new URL('./design.json',import.meta.url))));
const micro=makeRegisterMicrodecode(),fb=makeRegisterStateFeedback();
function check(d){const m=new Map(d.blocks.map(v=>[K(v.position),v])),at=p=>m.get(K(p)),parents=new Set(d.parents.map(p=>p.id)),allowed=new Set(d.edges.map(e=>pair(e.from,e.to))),directed=new Set(d.edges.map(e=>K(e.from)+'>'+K(e.to)));assert.equal(m.size,d.blocks.length);let supports=0,inherited=0,contacts=0,reps=0,minRear=15;
 for(const parent of[micro,fb])for(const v of parent.blocks){assert.deepEqual(at(v.position)?.block,v.block,'Parent cell changed');inherited++;}
 for(const v of d.blocks){if(v.block.id.endsWith('_concrete'))continue;const p=v.block.id.endsWith(':redstone_wall_torch')?add(v.position,D[v.block.properties.facing]):{...v.position,y:v.position.y-1};assert.equal(at(p)?.block.id,'minecraft:light_gray_concrete','Missing support '+K(v.position));supports++;}
 for(const c of d.columns){assert.equal((c.output_y-c.bottom)%4,1);for(let y=c.bottom;y<c.output_y;y++)assert.equal(at(P(c.x,y,c.z))?.block.id,'minecraft:'+((y-c.bottom)%2===0?'light_gray_concrete':'redstone_torch'));assert.equal(at(P(c.x,c.output_y,c.z))?.block.id,'minecraft:redstone_wire');for(const value of[false,true]){let signal=value;for(let y=c.bottom+1;y<c.output_y;y+=2)signal=!signal;assert.equal(signal,value);}}
 for(const r of d.routes){let power=15;for(let i=0;i<r.path.length;i++){const p=r.path[i],v=at(p);assert(v,'Cut '+r.name);if(v.block.id==='minecraft:repeater'){const out=add(p,D[v.block.properties.facing]);assert.deepEqual(out,r.path[i+1],'Backward '+r.name);assert.deepEqual(add(p,neg(D[v.block.properties.facing])),r.path[i-1]);minRear=Math.min(minRear,power);assert(power>0);power=15;}else{assert.equal(v.block.id,'minecraft:redstone_wire');if(i&&at(r.path[i-1]).block.id==='minecraft:redstone_wire')power--;assert(power>0,'Attenuated '+r.name);}}}
 for(const v of d.blocks.filter(v=>!parents.has(v.part)&&v.block.id==='minecraft:repeater')){const delta=D[v.block.properties.facing],out=add(v.position,delta),rear=add(v.position,neg(delta));assert(directed.has(K(rear)+'>'+K(v.position))&&directed.has(K(v.position)+'>'+K(out)),'Unlisted repeater direction '+K(v.position));for(const side of dirs.filter(s=>s.x*delta.x+s.z*delta.z===0)){const p=add(v.position,side),b=at(p)?.block;assert(!b||b.id.endsWith('_concrete'),'Foreign diode side '+pair(p,v.position));}reps++;}
 for(const v of d.blocks.filter(v=>v.block.id==='minecraft:redstone_wire'))for(const delta of dirs)for(const dy of[-1,0,1]){const p=add(v.position,delta);p.y+=dy;const o=at(p);if(!o||o.block.id.endsWith('_concrete'))continue;if(v.part===o.part&&parents.has(v.part))continue;if(dy&&o.block.id!=='minecraft:redstone_wire')continue;if(dy===1&&at({...v.position,y:v.position.y+1}))continue;if(dy===-1&&at({...p,y:v.position.y}))continue;assert(allowed.has(pair(v.position,p)),'Foreign contact '+pair(v.position,p));contacts++;}
 assert.equal(d.connections.length,16);for(const c of d.connections){if(c.name.startsWith('current_to_decode_')){const bit=Number(c.name.split('_').at(-1));assert.deepEqual(c.source,fb.ports.state.bits[bit].position);assert.deepEqual(c.destination,micro.ports.state.bits[bit].position);}else{assert.deepEqual(c.source,micro.ports[c.name].bits[0].position);assert.deepEqual(c.destination,fb.ports[c.name].bits[0].position);}assert.equal(at(c.source).block.id,'minecraft:redstone_wire');assert.equal(at(c.destination).block.id,'minecraft:redstone_wire');}
 return{preserved_parent_cells:inherited,support_checks:supports,new_directed_repeaters:reps,listed_cross_parent_wire_contacts:contacts,positive_lift_columns:d.columns.length,minimum_route_repeater_input:minRear,exact_control_loop_bindings:d.connections.length};}
const checks=check(d);const cut=structuredClone(d);const route=cut.routes.find(r=>r.name==='fixed_next_2_arrive');cut.blocks=cut.blocks.filter(v=>K(v.position)!==K(route.path[20]));assert.throws(()=>check(cut));const reverse=structuredClone(d);reverse.blocks.find(v=>v.part==='current_to_decode_4_lift'&&v.block.id==='minecraft:repeater').block.properties.facing='south';assert.throws(()=>check(reverse));
const sha=p=>createHash('sha256').update(readFileSync(new URL(p,import.meta.url))).digest('hex');const result={status:'offline_microstate_feedback_geometry_binding_checks_pass',...d.metrics,...checks,corruption_refusals:2,sources:{generator:sha('../../../../hardware/full-gpu-register-sequencer.mjs'),design:sha('./design.json'),checker:sha('./check.mjs')},native_acceptance:false,limits:['Parents inherit their focused checks. Closed data-loop geometry is not initialized or autonomous operation.','Boot/address sources, clock/phase/reset admission and lane/file fanout remain missing.','No measured edge timing, complete strong/weak power simulation or game results.']};writeFileSync(new URL('./checks.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
